### ISSUE TITLE
Using a custom type in parameters

### ISSUE THREAD

**Issue by flimzy** [go-swagger/go-swagger#1000]
## Problem statement

Creating a swagger spec with a custom type generates an invalid spec:

    - must validate one and only one schema (oneOf)
    - must validate one and only one schema (oneOf)
    - must validate one and only one schema (oneOf)
    - paths./activity.json.get.parameters.$ref in body is a forbidden property
    - paths./activity.json.get.parameters.in in body should be one of [header]
    - paths./activity.json.get.parameters.type in body is required

In my case, the custom type is a simpler wrapper around `time.Time`, which adds custom marshaler/unmarshaler functionality.

Is there a way to use custom types in parameters?

If additional information is needed, I can produce an MRE.

**Comment by casualjim** [comment]
Have you seen the strfmt types? isn't the DateTime or Time sufficient?
I'd like to see few steps to reproduce, so it's easier to understand what's going on.

**Comment by flimzy** [comment]
> Have you seen the strfmt types?

I had not. Setting my custom type to a `strfmt` does seem to solve my problem. Thank you!
