### ISSUE TITLE
How to define a swagger:response that produces a binary file, application/octet-stream

### ISSUE THREAD

**Issue by dylangleason** [go-swagger/go-swagger#1003]
## Problem statement

I am trying to figure out how to write and annotate a `go-swagger` response struct that produces the following swagger output:

```json
"fileResponse": {
    "description": "OK",
    "schema": {
        "type": "file"
    }
}
```
However, I am unable to figure out how to do this with `go-swagger` response struct and annotations and the documentation doesn't provide any clarity on this specific use-case. I end up with the following:

```json
"fileResponse": {
    "description": "OK",
    "schema": {
        "type": "array",
        "items": {
            "type": "integer",
            "format": "uint8"
        }
    }
}
```

## go-swagger specification

I know this is obviously wrong, but this was the closest I could approximate:

```go
// OK
// swagger:response photoByFilenameResponse
type fileResponse struct {
	// In: body
	File []byte `json:"body,omitempty"`
}
```

For the operation that is returning this response, I've also made sure to specify the MIME type:

```go
// Produces:
// - image/jpeg
// - image/png
// - application/octet-stream
```

## Environment
swagger version: 2.0
go-swagger version: dev
go version: 1.8.0  
OS:   Mac OS X 10.10.5

**Comment by casualjim** [comment]
I think you can use strfmt.File or os.File in your struct

```go
type fileResponse struct {
  // In: body
  File strfmt.File
}
```

**Comment by dylangleason** [comment]
The only reference I've found to `strfmt` is in this package: https://github.com/go-openapi/strfmt

However: `File not declared by package strfmt`

**Comment by casualjim** [comment]
I'm terribly sorry the File type is in the runtime package: `runtime.File`
I believe you can also return a stream like io.Reader
