### ISSUE TITLE
Wrong context package used in generated code

### ISSUE THREAD

**Issue by easeway** [go-swagger/go-swagger#1011]
## Problem statement

All generated code is using `golang.org/x/net/context` however `restapi/operations/app_api.go` is using `context` which makes the generated code fail to compile

## Environment
swagger version: 0.9.0
go version: 1.8
OS:  Linux (Ubuntu 16.10 amd64)

**Comment by casualjim** [comment]
did you generate with --with-context because that is deprecated and no longer necessary because go now has the context on the request object, so no more need to thread it through
