### ISSUE TITLE
Response examples break definition references

### ISSUE THREAD

**Issue by ligustah** [go-swagger/go-swagger#1013]
## Problem statement
go-swagger seems to have problems with `examples` in response objects. When I include examples it doesn't reuse the referenced definitions but creates new types in the `_responses.go` file. If I remove it everything works as expected.

http://swagger.io/specification/#responseObject
http://swagger.io/specification/#exampleObject

## Swagger specification
Without examples:
```
---
swagger: "2.0"
info:
  description: test
  title: test
  version: "0.0.0"
schemes:
  - http
definitions:
  Response:
    type: object
    properties:
      test:
        type: string
paths:
  /test:
    get:
      operationId: test
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Response'
```

With examples:
```
---
swagger: "2.0"
info:
  description: test
  title: test
  version: "0.0.0"
schemes:
  - http
definitions:
  Response:
    type: object
    properties:
      test:
        type: string
paths:
  /test:
    get:
      operationId: test
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Response'
          examples:
            "application/json":
              test: blah
```

## Steps to reproduce
Build both specs and compare the generated code.

## Environment
version: 0.9.0
commit: e341e616eaee0b6bd888b6ba6eb0872d093a23ed
downloaded here: https://github.com/go-swagger/go-swagger/releases/tag/0.9.0

go version: go1.8
OS:  Windows 7

**Comment by fredbi** [comment]
Should work now with current master (fixed expansion in responses)
