### ISSUE TITLE
Generated clients should return errors in all error cases instead of panicking

### ISSUE THREAD

**Issue by ryanwalls** [go-swagger/go-swagger#1021]
## Problem statement
We define a specific "shape" for our error responses from our api.  It is an object that has a `message` field.

If for some reason our API goes down, all the routers in the path to the api (e.g. nginx, haproxy, AWS ELB, etc) return html or plain text instead of json.  When the return is `text/plain`, we get a panic.  

```
panic: interface conversion: interface {} is *models.Error, not *string
...
/go/src/github.com/3dsim/solver-svc/vendor/github.com/go-openapi/runtime/text.go:34
```

I would expect the generated client to return an error instead of panicking if the api returns an object that isn't the right shape.  

Quoting Andrew Gerrand, "The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values."

## Swagger specification for responses:
```
responses:
        "200":
          description: Successfully retrieved list
          schema:
            type: array
            items:
              $ref: '#/definitions/Material'
        "401":
          description: Not authorized
          schema:
            $ref: '#/definitions/Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
```

Swagger for error definition:
```
Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

## Steps to reproduce
Use an object for error response type.  Generate client.  Use client to call a URL that will 404 with a plain text response.  

## Environment
go-swagger version: 0.8.0
go version: 1.8.1

**Comment by ryanwalls** [comment]
@casualjim have a minute to look at this one?  It's pretty painful for us.  Surprised it hasn't come up previously.

**Comment by ryanwalls** [comment]
Currently to work around this we have to recover from a panic before we call any generated client code.  

e.g.
```
func (c *client) Material(materialID int32) (material *models.Material, err error) {
	defer func() {
		// Until this issue is resolved: https://github.com/go-swagger/go-swagger/issues/1021, we need to recover from
		// panics.
		if r := recover(); r != nil {
			err = fmt.Errorf("Recovered from panic: %v", r)
		}
	}()
	token, err := c.tokenFetcher.Token(c.audience)
	if err != nil {
		return nil, err
	}
	response, err := c.client.Operations.GetMaterial(operations.NewGetMaterialParams().WithID(materialID), openapiclient.BearerToken(token))
	if err != nil {
		return nil, err
	}
	return response.Payload, nil
}
```

**Comment by ryanwalls** [comment]
@casualjim Going to bump this again.  Should we be modeling our errors differently to avoid panics?  There must be something we are missing.  Should we not be specifying a schema at all for errors?

**Comment by casualjim** [comment]
I'll try to look into this. I think the main issue is that errors don't have a TextMarshaller interface implemented.

**Comment by EleanorRigby** [comment]
@ryanwalls : can you provide location where panic is coming in runtime.go if you remove that  recovery piece of code? When I look at line 34 of runtime/text.go , it points to nothing

**Comment by ryanwalls** [comment]
@casualjim @EleanorRigby Good news.  Since I created this issue the bug has been fixed.  I updated one of our clients that was experiencing this issue to the more recent packages, and the panic went away.  Sorry about the recent pings.  Should have tried updating the packages before I bumped this issue.
