### ISSUE TITLE
No paths found in basic net/http Web app

### ISSUE THREAD

**Issue by mcandre** [go-swagger/go-swagger#1027]
## Problem statement

I want to generate a Swagger specification from a preexisting net/http application. However, go-swagger appears to have trouble finding the endpoints.

As a new go-swagger user, I'm not sure whether endpoints need to be manually annotated first, in order to assist `swagger generate spec`. Could someone clarify?

## Swagger specification

```json
{
  "swagger": "2.0",
  "paths": {}
}
```
## Steps to reproduce

1. Define endpoints with `net/http`.
2. Run `swagger generate spec`.
3. Run `swagger generate spec -b ./cmd`.
4. Run `swagger generate spec -b ./cmd/server`.
5. Run `swagger generate spec -b ./cmd/server/main.go`.
6. Run `swagger generate spec -b <git server>/<repo>/cmd/server`.

Same no-paths Swagger output each time.

## Environment

go-swagger version: dev
go version: 1.7.5
OS: macOS 10.12

**Comment by casualjim** [comment]
does your main package contain a code path that reaches where you described your routes?

**Comment by mcandre** [comment]
Yes. Maybe I got the syntax wrong?

```go
// swagger:route GET /health
//
// Returns status information for connected elements.
//
// Produces:
// - application/json
//
// Schemes: http, https
//
// Responses:
//   default: genericError
//   200: someResponse
func GetHealth(w http.ResponseWriter, r *http.Request) {
...
}
```

**Comment by mcandre** [comment]
Ah, I was missing the required operation ID field in the swagger syntax.
