### ISSUE TITLE
referenced path item cause an error

### ISSUE THREAD

**Issue by piotrkowalczuk** [go-swagger/go-swagger#1034]
## Problem statement

[$ref](http://swagger.io/specification/#pathItemObject) within path is not resolved properly. Im getting error `no operations were selected`.  `fmt.Println` shows that `Spec.operations` is empty.

## Swagger specification

```
paths:
  "/":
    "$ref": './paths/options.yaml'
```
## Steps to reproduce

Create any spec with referenced path item.

## Environment
swagger version: 0.10.0
go version: go version go1.8.1 darwin/amd64
OS: osx

**Comment by casualjim** [comment]
can you try to flatten your spec first to see if that fixes it?

swagger flatten -o swagger.flat.json swagger.json

**Comment by piotrkowalczuk** [comment]
Yes flattened spec has all operations included. Is such intermediate file recommended way of generation?

**Comment by casualjim** [comment]
I'll make it the default in in the next version. It solves quite a lot of problems
Currently it's a separate operation because it was experimental

**Comment by brandoncole** [comment]
Thanks for posting that solution @casualjim - that will work for me in the interim as well
