### ISSUE TITLE
Cant add aditional flags 

### ISSUE THREAD

**Issue by Menta2L** [go-swagger/go-swagger#1036]
I like to add additional flags 
If i understand well that should happens at configureFlags function in restapi package

So basically i do something like this 

var acmeConfig = struct {
	acmeHost string ``long:"acme-host" description:"Use autocert with specific hostname"
}{}

func configureFlags(api *operations.MdmAPI) {
	api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{
		swag.CommandLineOptionsGroup{
			ShortDescription: "Autocert hostname",
			Options:          &acmeConfig,
		},
	}
}
but after build and execute with  -h option flang did not exist 

## Environment
swagger version: dev
go version: 1.8
OS:    Centos 7.3

**Comment by casualjim** [comment]
Here's an example: https://github.com/go-openapi/kvstore/blob/master/cmd/kvstored/main.go#L50-L57

**Comment by Menta2L** [comment]
Most probably is that i cant find the workflow but 
https://github.com/go-openapi/kvstore/blob/master/cmd/kvstored/main.go#L50
is calling 
https://github.com/go-openapi/kvstore/blob/master/gen/restapi/server.go#L47
witch is calling 
https://github.com/go-openapi/kvstore/blob/master/gen/restapi/configure_kvstore.go#L20
and that is the exact part witch is not working for me

**Comment by Menta2L** [comment]
I found the "issue" and was very lame. I did not expose the flag property  to public.
Everything works like a charm
