### ISSUE TITLE
Inconsistent import/use of package in frontend_client.go generation

### ISSUE THREAD

**Issue by ecnahc515** [go-swagger/go-swagger#104]
Using the swagger schema from https://quay.io/api/v1/discovery:

If I generate a client the use of other clients is inconsistent. I generated a schema which orgiinally included the archivedlogs client, but after regenerating it a few times, it removed the archivedlogs, but added userfiles. It seems it's not always using all clients it generated in the frontend_client constructor.

Here's the diff (it took me a few client generations to get this to happen since it doesn't always occur). It seems to be limited to the archivedlogs and userfiles packages, not sure why the others aren't being added/removed between generation.

```diff
diff --git a/common/go-quay/client/quay_frontend_client.go b/common/go-quay/client/quay_frontend_client.go
index 52b5e16..9487e26 100644
--- a/common/go-quay/client/quay_frontend_client.go
+++ b/common/go-quay/client/quay_frontend_client.go
@@ -7,6 +7,7 @@ import (
 	"github.com/go-swagger/go-swagger/client"
 	"github.com/go-swagger/go-swagger/strfmt"
 
+	"github.com/foo/common/go-quay/client/archivedlogs"
 	"github.com/foo/common/go-quay/client/billing"
 	"github.com/foo/common/go-quay/client/build"
 	"github.com/foo/common/go-quay/client/discovery"
@@ -25,13 +26,14 @@ import (
 	"github.com/foo/common/go-quay/client/team"
 	"github.com/foo/common/go-quay/client/trigger"
 	"github.com/foo/common/go-quay/client/user"
-	"github.com/foo/common/go-quay/client/userfiles"
 )
 
 // New creates a new quay frontend client
 func New(transport client.Transport, formats strfmt.Registry) *QuayFrontend {
 	cli := new(QuayFrontend)
 
+	cli.Archivedlogs = archivedlogs.New(transport, formats)
+
 	cli.Billing = billing.New(transport, formats)
 
 	cli.Build = build.New(transport, formats)
@@ -68,13 +70,13 @@ func New(transport client.Transport, formats strfmt.Registry) *QuayFrontend {
 
 	cli.User = user.New(transport, formats)
 
-	cli.Userfiles = userfiles.New(transport, formats)
-
 	return cli
 }
 
 // QuayFrontend is a client for quay frontend
 type QuayFrontend struct {
+	Archivedlogs *archivedlogs.Client
+
 	Billing *billing.Client
 
 	Build *build.Client
@@ -110,6 +112,4 @@ type QuayFrontend struct {
 	Trigger *trigger.Client
 
 	User *user.Client
-
-	Userfiles *userfiles.Client
 }
```

**Comment by casualjim** [comment]
:100: for weirdness on this one

**Comment by casualjim** [comment]
This has to do with operations that are currently lacking an operation ID.
Unfortunately swagger defines those as optional, but it should do better name mangling

**Comment by casualjim** [comment]
I can't fix this because the reason for this is that there are duplicate operationIds defined. They have to be globally unique to the specification, not just to the tag.

from [the swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5) for operationId:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

**Comment by casualjim** [comment]
this issue has some more context about it: 
https://github.com/swagger-api/swagger-spec/issues/381

**Comment by ecnahc515** [comment]
Reported this upstream to the quay.io folk. I'll leave this open since it seems validation/client generation should probably be able to determine this was, in fact not completely valid. (maybe just do a rough pass at the beginning to check all operations are unique?).

By the way, I wrote a simple JQ query which is able to tell me if any operationIds were repeated if it's of use to anyone finding this themselves.

`curl https://quay.io/api/v1/discovery | jq '.paths[][].operationId?' | uniq -d`
