### ISSUE TITLE
Missing fields in generated marshaler/unmarshaler when the object extends other objects

### ISSUE THREAD

**Issue by yan-zhuang** [go-swagger/go-swagger#1042]
## Problem statement
When an object extends other objects (using `allOf`), the generated Marshaler and Unmarshaler don't handle the fields in enclosing object.

The fix to [#847](https://github.com/go-swagger/go-swagger/issues/847) looks good (not tested myself)

## Swagger specification
[swagger.yaml](https://github.com/yan-zhuang/swagger-allof-test/blob/master/swagger.yaml)

## Steps to reproduce
* generate server from the swagger file.
`swagger generate server`
* verify the generated `models/b.go` file.
* expecting field `F3` and `F4` are handled correctly in MarshalJSON and UnmarshalJSON methods.

## Environment
swagger version: from 71225c4a7882ae49cd57e22292a58dff382908e8 to 0.10.0 and the latest
go version: go version go1.7.1 linux/amd64 
OS:   Linux test 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yan-zhuang** [comment]
See the [diff](https://github.com/yan-zhuang/swagger-allof-test/commit/9cc8549d59756eb813fac7fbe85c45412073d928) that compare the fix 847 with 7125c.

**Comment by sethcleveland** [comment]
I'm seeing this problem as well.  The generated JSON Unmarshallers don't handle property extensions correctly.

**Comment by sethcleveland** [comment]
FWIW's my problem was with generating the client. I realized my swagger api yaml was subtly wrong. In order to get the data composition to work correctly with codeGen, I had to add the extra properties to the 'allOf' array, instead of being in the outside of that array. I noticed my problem when I looked at this example in the swagger spec documentation.

``` yaml
definitions:
  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
    - type: object
      required:
      - rootCause
      properties:
        rootCause:
          type: string```

**Comment by posener** [comment]
Any news about this issue?

**Comment by gregmarr** [comment]
As sethcleveland noted, the `allOf` format in the Swagger document is incorrect.

**Comment by posener** [comment]
Yes! thanks!
Works for me.
Just to make it clear to next person who meets this:
```diff
definitions:
  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
+    - type: object
+      required:
+      - rootCause
+      properties:
+        rootCause:
+          type: string
-   type: object
-   required:
-   - rootCause
-   properties:
-     rootCause:
-       type: string
```
I think this issue can be closed, right?

**Comment by fredbi** [comment]
Common problem with yaml is that errors are just a space away. This a big concern for spec validation.

I suggest we let the original issue raiser close this if appropriate.

**Comment by yan-zhuang** [comment]
I'll re-test with the suggested solution.
Thanks

**Comment by posener** [comment]
The yamls in both cases is valid, and the swagger UI shows both of them the same.

**Comment by gregmarr** [comment]
@posener That's good to know.  I tried using `allOf` that way in the past, but ran into issues, and changed it to match the examples in the spec, which always showed the two complete objects nested under `allOf`.  I thought that there had been Swagger validation errors, but maybe it was only `go-swagger` errors, meaning this one.

**Comment by fredbi** [comment]
Retested and it works with correct spec (both cases). Going to post this in PR as yet another non-reg UT.

@posener : the first invalid spec is correctly detected as invalid by `swagger validate` (I admit that the error message is not obvious to understand).

**Comment by yan-zhuang** [comment]
The version 0.15.0 works with correct syntax. But it didn't report any errors with incorrect syntax.
```
incorrect $ swagger validate swagger.yaml
2018/07/18 15:49:44
The swagger spec at "swagger.yaml" is valid against swagger specification 2.0
```

**Comment by fredbi** [comment]
This is indeed a valid JSONSchema specification, but unsupported by codegen as for now. See recent issue which follows the same structure as yours: #1617
