### ISSUE TITLE
dot symbol in the path cause problems

### ISSUE THREAD

**Issue by onokonem** [go-swagger/go-swagger#1050]
## Problem statement

dot separated (like `/{fileName}.{fileExt}`) parameters in the path are parsed incorrectly.

same spec is working perfectly for [swagger-codegen](http://swagger.io/swagger-codegen/)

## Swagger specification

```
swagger: '2.0'
info:
  description: >-
    Minimal swagger file to demonstrate a dot-in-th-path problem
  version: 0.0.1
  title: test
tags:
  - name: test
    description: test the go-swagger generator bug
paths:
  /{fileName}.{fileExt}:
    get:
      tags:
        - test
      operationId: test
      parameters:
        - name: fileName
          in: path
          required: true
          type: string
        - name: fileExt
          in: path
          required: true
          type: string
      responses:
        '204':
          description: successful operation
        '500':
          description: Operation error

```

## Steps to reproduce

```
$swagger generate client
The swagger spec at "swagger.yml" is invalid against swagger specification 2.0. see errors :
- path param "{fileName}.{fileExt}" has no parameter definition
- path param "fileName" is not present in path "/{fileName}.{fileExt}"
- path param "fileExt" is not present in path "/{fileName}.{fileExt}"
```

## Environment
swagger version: dev  (installed with `go get -u github.com/go-swagger/go-swagger/cmd/swagger`)
go version: go1.8.1 darwin/amd64
OS:   OS X El Capitan (10.11.6)

**Comment by casualjim** [comment]
You can try to generate with `--skip-validation`

**Comment by onokonem** [comment]
I would not say it is good idea to give up on validation for the real world scenarios

**Comment by casualjim** [comment]
this is validation of the spec, I agree it's a bug but skipping validation (a step before generating) would allow you to continue

**Comment by onokonem** [comment]
yes right thank you

fortunately this time I need just a client code which I've generated with swagger-codegen successfully.

by the way, this is a spec this bug appeared with: https://github.com/komikoni/redmine-swagger
