### ISSUE TITLE
Getting started with go-swagger

### ISSUE THREAD

**Issue by ribice** [go-swagger/go-swagger#1053]
Hi,

Is there a 'getting-started' page/file?

I'm pretty new to Golang, but used Swagger earlier on my Java/SpringBoot. I'd like to add Swagger documentation to my RESTful APIs written in Golang but I'm a bit lost here.

How do I get started?

**Comment by casualjim** [comment]
have you seen this? https://goswagger.io/generate/spec.html

**Comment by ribice** [comment]
Yes, and it's pretty fine. The one provided [here ](https://github.com/yvasiyarov/swagger)seems 'simpler'. Anyway didn't have to time to implement swagger yet, feel free to close this issue. Cheers!

**Comment by casualjim** [comment]
that one is for swagger 1.2, this repo is for swagger 2.0

**Comment by pdrum** [comment]
[Here](https://medium.com/@pedram.esmaeeli/generate-swagger-specification-from-go-source-code-648615f7b9d9) is a blog post addressing this same issue.
