### ISSUE TITLE
import's are incorrectly generated if $GOPATH is on a symlink

### ISSUE THREAD

**Issue by PurpleBooth** [go-swagger/go-swagger#1059]
## Problem statement

When the $GOPATH contains a symlink, the import paths are generated to locations using the realpath, rather than to the gopath location.

## Steps to reproduce

For example

```
export GOPATH=$HOME/Documents/Code/golang
```

```
 readlink "$HOME/Documents/Code"
/Users/billie/Dropbox/Documents/Code/
```

Then do your code generation

`swagger generate server swagger.json`

And your imports are generated relative to the realpath, rather than the gopath.

```go
import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../../Dropbox/Documents/Code/golang/src/github.com/purplebooth/realsov/api/models"
)
```

When you compile 

```
go install ./cmd/real-sov-server
restapi/operations/authentication/get_oauth_token_responses.go:11:2: local import "../../../../Dropbox/Documents/Code/golang/src/github.com/purplebooth/realsov/api/models" in non-local package
```

## Environment

```
swagger version
version: 0.10.0
commit: 4d1e79b5a98c6f67bbf06923643d5317ed37a058
```

```
go version
go version go1.8.1 darwin/amd64
```

MacOS Sierra

## Workaround

Remove the symlink from your GOPATH. The imports are correctly generated.

**Comment by dreamlover** [comment]
I have no symlink in my GOPATH, go swagger 0.10.0 also generates relative paths.
`
package opr

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"../../../Works/AYJiaYou/MPos-WebAPI/src/mpos/mod"
	"../../../Works/AYJiaYou/MPos-WebAPI/src/mpos/rest/opr/term"
)
`

**Comment by casualjim** [comment]
how are you running swagger?
what is your gopath env var?
what is your project directory?
what is your OS?

**Comment by PurpleBooth** [comment]
Just to clarify, my issue was definitely the symlink thing. Removed the symlink, worked fine, put it back, it broke, removed it it was totally fine.

**Comment by dreamlover** [comment]
@casualjim 
I'm using `openSUSE Leap 42.2`, my GOPATH env is:
```bash
ee@ay-lfree:~/Works/AYJiaYou/MPos-WebAPI> echo $GOPATH
/home/lfree/opt/Go:/home/lfree/Works/AYJiaYou/AY-Go:/home/lfree/Works/AYJiaYou/BackHarmony:/home/lfree/Works/AYJiaYou/AY-Ad/Server:/home/lfree/Works/AYJiaYou/HealthyID/Server:/home/lfree/Works/AYJiaYou/AY-DDUP:/home/lfree/Works/AYJiaYou/MPos-WebAPI:/home/lfree/Works/github.com
```
I stored gen_server.sh file in `Works/AYJiaYou/MPos-WebAPI/API/` folder and run it within that folder:
```bash
#!/bin/bash

#./swagger_linux_amd64_0.8.0 generate server \
#./swagger_linux_amd64_0.9.0 generate server \
./swagger_linux_amd64_0.10.0 generate server \
    --spec=swagger.yml \
    --api-package=opr \
    --model-package=mod \
    --server-package=rest \
    --target=../src/mpos \
    --name=mpos \
    --principal=mod.RequestInfo \
    --default-scheme=https

for file in `find ../src/mpos/ -type f -name *.go`
do
    sed -i 's/\.\.\/\.\.\/\.\.\/Works\/AYJiaYou\/MPos-WebAPI\/src\///' $file
done
```

**Comment by benpye** [comment]
This seems to occur when your target isn't within the first in your `GOPATH`
