### ISSUE TITLE
Return error to server

### ISSUE THREAD

**Issue by Ragnar-BY** [go-swagger/go-swagger#1060]
## Problem statement

Is it possible to return error to main function of server?

For example, my server saves some configs in file. And I want that if config file is missing, then server must be stopped with some error code. It is possible to do it with panic(err), but I think it is not good way. So can I return error main function of server ?

## Environment
swagger version: 0.9.0

**Comment by casualjim** [comment]
you can make your own main function, I've done that here: https://github.com/go-openapi/kvstore/blob/master/cmd/kvstored/main.go

**Comment by RomanBuzuk** [comment]
But would not be main.go rewritten if I generate server again?

**Comment by gregmarr** [comment]
There is a command line argument to prevent that, `--exclude-main`.

**Comment by fredbi** [comment]
Please tag as question. I'll put it in the FAQ md (being written...)
