### ISSUE TITLE
Is there anyway to change the response format body when validation error?

### ISSUE THREAD

**Issue by ifraixedes** [go-swagger/go-swagger#1061]
I'm wondering if there is a way to change the response body format when the request doesn't pass the validation rules specified in the swagger spec for a specific API call.

For example, if I have a API route like `POST /users` which requires a body with the field `id` and I request without it, I get `{"code":602,"message":"Id in body is required"}`.

Is it possible to change such format by a middleware or anywhere else?
For example to return `{"error": {"code": 602,  "message": "Id in body is required"}}`

**Comment by casualjim** [comment]
you can override the ServeError function in the configure_xxx.go file which allows you to rewrite errors

**Comment by ifraixedes** [comment]
Great thanks!
