### ISSUE TITLE
Consumes wildcard not working

### ISSUE THREAD

**Issue by nelz9999** [go-swagger/go-swagger#1073]
## Problem statement
I would like an endpoint to accept any `Content-Type`, but it seems the checking of it doesn't take the wildcard into account.

Please remove the sections that don't apply

## Swagger specification
```
---
  swagger: "2.0"
  info:
    description: "Show wildcard accept not working"
    version: "1.0.0"
    title: "Acceptable"
    contact:
      email: "nelz@orionlabs.io"
  basePath: "/"
  schemes:
    - "http"
  consumes:
    - "application/json"
  produces:
    - "application/json"
  paths:
    /{filename}:
      put:
        summary: "Put Resource"
        consumes:
          - "*/*"
        description: "Enpoint to upload a resource"
        operationId: "putter"
        parameters:
        - name: filename
          in: path
          description: The unique filename of the resource being uploaded
          required: true
          type: string
          minLength: 1
        - name: content
          in: body
          description: The contents of the file being uploaded
          required: true
          schema:
            type: string
            format: binary
        - name: contentType
          in: header
          description: What Content-Type should be reported when retrieving
          required: true
          default: application/octet-stream
          type: string
        responses:
          201:
            description: successfully uploaded resource
```
## Steps to reproduce
```
$ curl -X PUT -H "Content-Type: incorrect/jif" --data-binary @zombie.gif http://127.0.0.1:8000/zombie_02.gif
{"code":415,"message":"unsupported media type \"incorrect/jif\", only [*/*] are allowed"}
```

After a little bit of spelunking, I believe the problem is here: https://github.com/go-openapi/runtime/blob/master/middleware/validation.go#L65 in `validateContentType(...)`.
* It looks for 0-length allowed, and passes if there's none, but that's not this case.
* It looks for an error parsing the media type, but that's not a problem: https://play.golang.org/p/HOUa8VmcGZ
* It does a case-insensitive search in a slice, but that won't help us: `incorrect/jif` vs `*/*`
* It then fails with no match

On Slack @casualjim said
> we use a proper mimetype library to match

... But I'm not seeing that in this case.

## Environment
swagger version: 
```
$ swagger version
dev
```

go version: 
```
$ go version
go version go1.8 darwin/amd64
```

OS: macOS

**Comment by casualjim** [comment]
it's not accounting for wildcards.
It should probably use a variant of: https://github.com/go-openapi/runtime/blob/master/middleware/negotiate.go#L46
