### ISSUE TITLE
unknown field type ele for

### ISSUE THREAD

**Issue by Zeychiel** [go-swagger/go-swagger#1077]
Hi,
Slices of custom types seem not to be handled properly.

## Steps to reproduce
This :
```
// HomePage response model
//
// This is used to send all the required informations to the home page
//
// swagger:response frontPageData
type FrontPageData struct {
	// the items for this order
	// mininum items: 1
	Matchs []matches.Match `json:"match,omitempty"`
            [...other items...]
	// in: body
	Seasons []seasons.Season `json:"seasons,omitempty"`
}
```
raises an error : 

> unknown field type ele for "match"

The only way to avoid this error seems to add

> // in: body

berfore each item of the struct, like this : 
```
// HomePage response model
//
// This is used to send all the required informations to the home page
//
// swagger:response frontPageData
type FrontPageData struct {
	// in: body
	Matchs []matches.Match `json:"match,omitempty"`
            [...other items...]
	// in: body
	Seasons []seasons.Season `json:"seasons,omitempty"`
}
```

This creates another unwanted behavior ; the generated spec file becomes : 

```
"responses": {
    "frontPageData": {
      "description": "HomePage response model\n\nThis is used to send all the required informations to the home page",
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/season"
        }
      }
    }
  },
```

...only showing the season (or whatever is the last element of the frontPageDataType) as being the frontPageData type. Moreover, frontPageData doesn't appear in the definitions.

The wanted behavior is to have FrontPageData as a response and a type available in the definitions.
Maybe my understanding of response is bad ?!

Thanks for helping,

Edit : may be linked to your answers in #613 

## Environment
go version: 1.8 
OS:   Win10

**Comment by gaplyk** [comment]
There are 2 ways. You can do fake structure and set in:body for the struct you need in the response body, or when you define list of your responses for an endpoint you can do
200: body:YourStruct

**Comment by Zeychiel** [comment]
Hi gaplyk,

Let's not create a fake structure and try the second option.
If I understand you well : 
- I removed the swagger:response annotation from the FrontPageData struct (orelse i'll get the error) and all the //in:body within
- I have the swagger:route : 
```
	//
	// Responses:
	//        200: body:FrontPageData
```
- this produces the spec : 
```
       "operationId": "GetHomePageData",
        "responses": {
          "200": {
            "description": "FrontPageData",
            "schema": {
              "$ref": "#/definitions/FrontPageData"
            }
          },
          "403": {
            "$ref": "#/responses/"
          },
          "500": {
            "$ref": "#/responses/"
          }
        }
```

but definitions/FronPageData does not exist (all the models related to this struc have disappeard from the definitions when i removed the swagger:response tag)

**Comment by gaplyk** [comment]
```go
// swagger:model FrontPageData
type FrontPageData struct {
	// in: body
	Matchs []matches.Match `json:"match,omitempty"`
            [...other items...]
	// in: body
	Seasons []seasons.Season `json:"seasons,omitempty"`
}
```

**Comment by Zeychiel** [comment]
...and with the -m option at generation, this works, thanks.
I though that I read somewhere that the swagger:model tag was only used to rename models and that the detection was using the package manager, is that a bug or the standard way ?
Thanks,

**Comment by jsvisa** [comment]
change `swagger:response` to `swagger:model` works
