### ISSUE TITLE
How to specify nested required in definitions

### ISSUE THREAD

**Issue by nlsun** [go-swagger/go-swagger#1080]
## Problem statement
```yaml
Parent:
  default: {"child": {}}
  required: ???
  properties:
    child:
      $ref: '#/definitions/Child'
Child:
  default: {"key": "value"}
  required: [ "key" ]
```
This fails with error:
```
- definitions.Parent.child.key in body is required
```

How do we fill in the required block in the Parent? "child.key" does not work
## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by nlsun** [comment]
I'm not sure if there's a better way, but I got it to work by setting the in the Parent

```
required: [ "child" ]
```

This then in turn satisfies the requirement that "child" is a default that requires "key"

**Comment by nlsun** [comment]
Actually, that didn't work, it turns out I accidentally had the required commented out. Any thoughts?

**Comment by casualjim** [comment]
it should work like that but you have it. You may even remove the default value for child.
```yaml
Parent:
  required: [ "child" ]
  properties:
    child:
      $ref: '#/definitions/Child'
Child:
  default: {"key": "value"}
  required: [ "key" ]
```

**Comment by nlsun** [comment]
hmm it only seem like it works if i set it all the way in the default:
```
Parent:
  default: {"child": { "key": "value" }}
  properties:
    child:
      $ref: '#/definitions/Child'
Child:
  default: {"key": "value"}
  required: [ "key" ]
`
This is the only way i could get it to work. Also, setting required in Parent didn't seem necessary with the above. However, setting the default in Child was necessary.

However, I was actually just aiming to set the zero values and it seems "x-nullable" fits the bill there. And x-nullable doesn't have this baggage that "required" does.

Are all the various flags documented somewhere? or is there a part of the code that is a good reference for this?

**Comment by casualjim** [comment]
so you are trying to avoid the error message and you want the properties to just use the zero values?

In that case you don't need the required at all. 
They are all explained here: http://swagger.io/specification/

**Comment by nlsun** [comment]
But if I don't set "x-nullable" then won't the "omitempty" in the struct remove the field when marshalling the json if it's the zero value?

For example if the default for an int is 1, if it is input as 0, then won't the default will kick in and set it to 1 (the default)?

**Comment by casualjim** [comment]
yes that's true, that's why we have a x-isnullable

**Comment by nlsun** [comment]
Ok, I think I've got it sorted out now, thanks.
