### ISSUE TITLE
CR #1081 introduced non-compiling errors

### ISSUE THREAD

**Issue by nickrmc83** [go-swagger/go-swagger#1097]
## Problem statement

CR #1081 introduced non-compiling errors. Specifically models that use discriminators generate incorrect unmarshaling code. See entity.go::unmarshalEntity from generating code using the below swagger specification.

## Swagger specification
swagger: '2.0'
info:
  title: Example
  description: Example
  version: "1.0.0"
definitions:
  entity:
    type: object
    discriminator: entity
    properties:
      id:
        description: Unique identifier of the entity
        type: string
      entity:
        description: The type of entity
        type: string
    required:
    - id
    - entity
  car:
    description: A car
    allOf:
    - $ref: '#/definitions/entity'
    - type: object
      properties:
        color:
          description: Car color
          type: string
  bike:
    description: A car
    allOf:
    - $ref: '#/definitions/entity'
    - type: object
      properties:
        brakes:
          description: Type of brakes
          type: string

## Steps to reproduce
swagger generate model -f swagger-file

## Environment
swagger version: HEAD  
go version: 1.7  
OS:   Linux

**Comment by alexmontecucco** [comment]
Sorry for this, made a mistake when I pushed the diff.
Will push again soon. The unittest `TestGenerateModel_Discriminators` will be updated as well to reflect this case.
