### ISSUE TITLE
 incorrect json for overridden `json:"-"` fields from embedded struct

### ISSUE THREAD

**Issue by smacker** [go-swagger/go-swagger#1102]
## Problem statement

go-swagger generates incorrect json for overridden `json:"-"` fields from embedded struct.

## Steps to reproduce

```go
// A SimpleOne is a model with a few simple fields
type SimpleOne struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Age  int32  `json:"age"`
}

// An OverridingOneIgnore is composed of a SimpleOne and overrides a field to ignore it
type OverridingOneIgnore struct {
	SimpleOne
	Age int32 `json:"-"`
}
```

Age property still will appear in result json.

Will you be welcome for pull request similar to this commit https://github.com/smacker/go-swagger-gen/commit/ae481eecf270fabe8ba13b87c29655928c17c30d ?

**Comment by casualjim** [comment]
yes, as a general rule I will accept any improvement as PR
