### ISSUE TITLE
Can't get models in the definitions

### ISSUE THREAD

**Issue by solher** [go-swagger/go-swagger#111]
I'm currently trying to use the spec generator but I can't get the `model` annotation to work.

Here is my code:

```go
package models

// Entity swagger:model 
type Entity struct {
	arangolite.Document
	Created     *time.Time `json:"created,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	Type        *string    `json:"type,omitempty"`
}
```

```go
package controllers

// Find swagger:route GET /entities entities find
// Responses:
//  200: []Entity
func (c *EntitiesCtrl) Find(w http.ResponseWriter, r *http.Request) {
	userID, err := c.pg.GetUserID(r)
	if err != nil {
		c.r.JSONError(w, http.StatusUnauthorized, errs.API.Internal, err)
		return
	}

	filter, err := c.pg.GetFilter(r)
	if err != nil {
		c.r.JSONError(w, http.StatusBadRequest, errs.API.FilterDecoding, err)
		return
	}

	entities, err := c.i.Find(userID, filter)
	if err != nil {
		switch err.(type) {
		case errs.ErrInvalidFilter:
			c.r.JSONError(w, 422, errs.API.InvalidFilter, err)
		default:
			c.r.JSONError(w, http.StatusInternalServerError, errs.API.Internal, err)
		}
		return
	}

	c.r.JSON(w, http.StatusOK, entities)
}
```

I already read the https://github.com/go-swagger/go-swagger/issues/67 issue and tried to add `	_ = models.Entity{}` or `	_ = []models.Entity{}` in the controller to trigger the generation but nothing works.

I also thought that maybe there were some kind of issues with the package naming so I tried to annotate the model with `// swagger:model models.Entity` and the response `//  200: []models.Entity` but it doesn't work either.

Thanks a lot for your help.

**Comment by casualjim** [comment]
The swagger: annotation comments are only detected at the beginning of a line.

Strictly speaking the swagger:model annotation isn't needed unless you want to rename model to something with lower case or something else.

for the response part I think you need a little bit more glue.

```go
package models

// Entity 
// swagger:model 
type Entity struct {
	arangolite.Document
	Created     *time.Time `json:"created,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	Type        *string    `json:"type,omitempty"`
}
```

```go
package controllers

// swagger:response listEntityResponse
type listEntityResponse struct {
  // in: body
  Payload []Entity
}

// Find 
// swagger:route GET /entities find entities
// Responses:
//  200: listEntityResponse
func (c *EntitiesCtrl) Find(w http.ResponseWriter, r *http.Request) {
	userID, err := c.pg.GetUserID(r)
	if err != nil {
		c.r.JSONError(w, http.StatusUnauthorized, errs.API.Internal, err)
		return
	}

	filter, err := c.pg.GetFilter(r)
	if err != nil {
		c.r.JSONError(w, http.StatusBadRequest, errs.API.FilterDecoding, err)
		return
	}

	entities, err := c.i.Find(userID, filter)
	if err != nil {
		switch err.(type) {
		case errs.ErrInvalidFilter:
			c.r.JSONError(w, 422, errs.API.InvalidFilter, err)
		default:
			c.r.JSONError(w, http.StatusInternalServerError, errs.API.Internal, err)
		}
		return
	}

	c.r.JSON(w, http.StatusOK, entities)
}
```

**Comment by solher** [comment]
Oh I have to wrap my models in structs to use it in responses ?
Shouldn't `// swagger:model` be an alias for that ?
I mean, it is kinda weird to have to write actual Go code to make the documentation system work.

**Comment by casualjim** [comment]
By forcing you to use go code to document your API you ensure that if you were to rename your models.Entity class, compilation of your API would fail and your documentation is kept up to date wrt to type information.

So I didn't want to reinvent the type system, and I think ultimately it leads to less work than more work. I also don't think of documentation as just being comments, documentation is what it is ultimately rendered not how you define it.  (eg. go's example functions)

By allowing you to specify the doc comment you tried to use first we'd have introduced more maintenance burden than is absolutely required and we'd have made the go-swagger code even more complex, for a feature that's one of the major features of the go language: static type checking. 

In swagger a response is always headers + body with an optional status code. If you choose to not define any headers that's fine, but it just means there are no response headers as part of the contract your service makes with the world.

**Comment by solher** [comment]
Ok that makes sense.
Thanks a lot for your help and your work ;)
