### ISSUE TITLE
Add 'db' tag to struct

### ISSUE THREAD

**Issue by taylageben** [go-swagger/go-swagger#1113]
## Problem statement
At the moment my generated model struct only contains a json tag. Is there a way to automatically add a db tag as well? If not, could this functionality be added?

For example:
```
type NewPet struct {

	// chip
	Chip string `json:"chip,omitempty" db:"chip"`

	// name
	// Required: true
	Name *string `json:"name" db:"name"`

	// tag
	Tag string `json:"tag,omitempty" db:"tag"`
}
```

**Comment by casualjim** [comment]
you can add a custom tag. see here: https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/todolist.models.yml#L680-L685

**Comment by taylageben** [comment]
Thanks so much! Managed to get it working!

**Comment by jolancornevin** [comment]
The URL is deprecated because it's not a permalink. Here's what @casualjim wanted to reference: https://github.com/go-swagger/go-swagger/blob/78fbe8d8aca5c69f4cc7ff7b1341df4a12375a28/fixtures/codegen/todolist.models.yml#L680-L685
