### ISSUE TITLE
go 1.7.x only supported atm ?

### ISSUE THREAD

**Issue by ashmckenzie** [go-swagger/go-swagger#1127]
Correct me if I'm wrong, but it looks like only go 1.7.x is supported atm?  If that is the case, I think it's worth calling that out somewhere in the docs or the README.md :)

**Comment by casualjim** [comment]
go 1.8 should be supported too, are you on an older version?

**Comment by ashmckenzie** [comment]
Thanks for responding so quickly! :)  When running `go get -u github.com/go-swagger/go-swagger/cmd/swagger` (as indicated in the README.md), I get the following for 1.8.3:

```
go get -u github.com/go-swagger/go-swagger/cmd/swagger
package context: unrecognized import path "context" (import path does not begin with hostname)
```

Interestingly, after switching to use go 1.7.5 (using goenv) and successfully running `go get -u github.com/go-swagger/go-swagger/cmd/swagger`, running `go get -u github.com/go-swagger/go-swagger/cmd/swagger` under go 1.8.3 no longer produces any error output.

Odd!

**Comment by ashmckenzie** [comment]
Can't reproduce..
