### ISSUE TITLE
Generation with custom Template

### ISSUE THREAD

**Issue by mantasmarcinkus** [go-swagger/go-swagger#1129]
## Problem statement
Hello, I am trying to create a custom layout for a project with templates. Everything is fine with *custom* operations  
```target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Package .ServerPackage .APIPackage .Package  }}{{ else }}{{ joinFilePath .Package .ServerPackage .Package  }}{{ end }}"```

However, I also want to move models to different folders too, I tried using this configuration:  
``` target: "{{ joinFilePath .Package .ModelPackage }}" ```
It seems that `.Package` is not defined and everything is moved to `ModelPackage` - that is `models` folder.
**Is there a way to define path like this:**
`operation/models/model_name` ?

### Generated operations do not match imports
While using template below it will generate and `operations` correctly, but it will not correctly import these `operations` inside `restapi/operations/x_api.go`
```target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Package .ServerPackage .APIPackage .Package  }}{{ else }}{{ joinFilePath .Package .ServerPackage .Package  }}{{ end }}"```
It will use default path to operations. 

## Environment
swagger version: dev 
go version: 1.8.3 
OS:   Macos

**Comment by casualjim** [comment]
how are you trying to do the custom layout?
is that following this guide? https://goswagger.io/use/template_layout.html

**Comment by mantasmarcinkus** [comment]
Yes. I pretty much copied the default config and changed `operations` to what I described.
It works for `operations` (it finds and does not overwrite). It does not work with customizing `models`, because it lacks `.Package` property. Is that by design? Can it be added?

**Comment by casualjim** [comment]
I have no objection to somebody adding the functionality.
I suspect the code to fix would be around here somewhere: https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L390

**Comment by mantasmarcinkus** [comment]
I've got into code and found out that model movement is limited by the information that can be provided in `swagger.json` configuration file. Schema does not allow to add information (unless it's a hacky way) about model whereabouts (I assume, that models should be shared).  
  
But the #2 issue that i have, is that when I change the directory (with the template) to move operations to a specific folder, `imports` are not correct in `service/restapi/operations/service_api.go` file. They are imported in the default way `project_name/service/restapi/operations/x`.
@casualjim do you have any ideas where can I find code for this part?

**Comment by casualjim** [comment]
what is it you're trying to achieve? 
Because if you just want to group operations, perhaps look into using tags in the swagger spec, it will do what you want

**Comment by mantasmarcinkus** [comment]
I am trying to achieve this kind of structure:
```
servicex
   - operations
   - models
   ...
   swagger.json
servicey
   - operations
   - models
   ...
   swagger.json
global_swagger.json
```
But it seems I won't be able to do it because the `models` swagger spec part does not contain `Tags` and cannot be added. Because of this, after generating server from `global_swagger.json` you cannot use models from different services, but you can reference operations (operations in swagger spec has `Tags` prop).

**Comment by casualjim** [comment]
why not make more than 1 spec and then merge the specs together with the mixin command?

**Comment by mantasmarcinkus** [comment]
As I stated above, I already do that successfully, however it causes 2 issues:
1) Models cannot be generated to different folders (.Package is not defined while generating with custom template (I assume that it is because `definitions` does not contain `Tags`)) (shown above)
2) The imports in `service/restapi/operations/service_api.go` will point to `default` location instead of the one in custom template, where I have to change auto generated file (which can be ignored by using `skip_exists: true` - but then missing the whole auto generated idea?)

**Comment by casualjim** [comment]
but you just generate 2 applications, is the issue that 1 is using types from the other?

**Comment by mantasmarcinkus** [comment]
No. The goal is to merge 2 (or more) already established applications into 1 application.
P.S. Thank you for answering so quickly

**Comment by casualjim** [comment]
yes but the question is do you need them to be because you want independent code files except that you want the server to present as 1 process with 1 spec. 
At least if I understand your use case correclty if not I apologize for jumping to conclusions.
This you can do by creating your own main file and serving both API's. it's a lot easier to make a  middleware that accommodates this pattern

**Comment by mantasmarcinkus** [comment]
You are correct. It seems that having a middleware and main file might work. I will try doing this. Thank you.
