### ISSUE TITLE
How to specify the header name in a Parameters or Response definition?

### ISSUE THREAD

**Issue by flimzy** [go-swagger/go-swagger#1135]
## Problem statement

What is the proper way to set the header name in a param or response definition?  Example:

    type FooResponse struct {
	// X-Foo header
	//
	// in: header
	// name: X-Foo
	XFoo string
	// ... 
    }

This creates a "valid" swagger definition, as:

      "headers": {
        "XFoo": {
          "type": "string",
          "description": "X-Foo header\n\nin: header\nname: X-Foo"
        },

Is this the best I can do?  Or is there some way to instead get:

      "headers": {
        "X-Foo": {
          "type": "string",
          "description": "X-Foo header"
        },

?

**Comment by casualjim** [comment]
I believe you can use a `json:"X-Foo"` tag to allow for overriding the name

**Comment by flimzy** [comment]
Brilliant! That does indeed do the trick. Thanks!

**Comment by knollfear** [comment]
For anyone that got here via a google search the answer is 

type FooResponse struct {
// X-Foo header
XFoo string `json:"X-Foo"`
// ... 
}

or at least that is what worked for me.
