### ISSUE TITLE
Struct with []byte field has wrong type

### ISSUE THREAD

**Issue by scisci** [go-swagger/go-swagger#1136]
By default when golang marshalls a field of type []byte to json, it uses a base64 string. This should be represented as:

```
type: string
format: byte
```

But currently when generating a spec from code, go-swagger uses:

```
type: array,
items: {
  type: integer,
  format: uint8
}
```

Although that seems more correct. It doesn't match what go will actually do when it marshalls the struct. I think this should be changed because an actual array of integers is rarely is ever returned. I tried adding type/format annotations to the field but they don't seem to work there.

**Comment by casualjim** [comment]
this is for a model right?

we have code like this: https://github.com/go-swagger/go-swagger/blob/master/scan/schema.go#L981-L996

but I think it never gets there so I'd like a more complete example that shows the problem.

**Comment by scisci** [comment]
Ahh yes, adding strfmt base64 fixed it. I didn't know that could be used to tag non-string field.

Thanks
