### ISSUE TITLE
go-openapi/runtime/security - not added to the imports - undefined: security

### ISSUE THREAD

**Issue by krasi-georgiev** [go-swagger/go-swagger#1137]
## Problem statement
on every swagger server generate the go-openapi/runtime/security is missing in the imports in restapi/operations/user_management_service_api.go

## Swagger specification
```
swagger: '2.0'
info:
  description: >-
    a service for user management.
  version: 0.0.1
  title: User Management Service
host: "localhost:8080"
basePath: /v1/account/
tags:
  - name: users
    description: user management - authenticate,create , delete, reset password
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - users
      summary: get an swt token to access protected endpoints
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        200:
          description: A token object.
          schema:
            type: object
            properties:
              token:
                type: string
        404:
          description: A user not found.
        default:
          description: Unexpected error

definitions:
  Login:
      type: "object"
      required:
      - "email"
      - "pass"
      properties:
        email:
          type: "string"
        pass:
          type: "string"
```

## Steps to reproduce
swagger generate server ./swagger.yaml
go run cmd/user-management-service-server/main.go

## Environment
swagger version: dev  
go version: go version go1.8 darwin/amd64
OS:   OSX

go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/krasimir"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

I think the problem is due to line: 2017/08/16 16:52:07 goimports: scanning directory /Users/krasimir/src: permission denied

but I couldn't find where it gets called and the user under which I run the swagger generator is  the owner of this folder 

2017/08/16 16:52:07 building a plan for generation
2017/08/16 16:52:07 planning definitions
2017/08/16 16:52:07 planning operations
2017/08/16 16:52:07 grouping operations into packages
2017/08/16 16:52:07 planning meta data and facades
2017/08/16 16:52:07 rendering 1 models
2017/08/16 16:52:07 rendering 1 templates for model Login
2017/08/16 16:52:07 name field Login
2017/08/16 16:52:07 package field models
2017/08/16 16:52:07 creating "login.go" in "models" as definition
2017/08/16 16:52:07 rendering 1 operation groups (tags)
2017/08/16 16:52:07 rendering 1 operations for users
2017/08/16 16:52:07 rendering 4 templates for operation
2017/08/16 16:52:07 name field PostLogin
2017/08/16 16:52:07 package field users
2017/08/16 16:52:07 creating "post_login_parameters.go" in "restapi/operations/users" as parameters
2017/08/16 16:52:07 name field PostLogin
2017/08/16 16:52:07 package field users
2017/08/16 16:52:07 creating "post_login_urlbuilder.go" in "restapi/operations/users" as urlbuilder
2017/08/16 16:52:07 name field PostLogin
2017/08/16 16:52:07 package field users
2017/08/16 16:52:07 creating "post_login_responses.go" in "restapi/operations/users" as responses
2017/08/16 16:52:07 name field PostLogin
2017/08/16 16:52:07 package field users
2017/08/16 16:52:07 creating "post_login.go" in "restapi/operations/users" as handler
2017/08/16 16:52:07 rendering support
2017/08/16 16:52:07 rendering 6 templates for application UserManagementService
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 skipping restapi/configure_user_management_service.go because it already exists
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 creating "main.go" in "cmd/user-management-service-server" as main
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 creating "embedded_spec.go" in "restapi" as embedded_spec
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 creating "server.go" in "restapi" as server
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 creating "user_management_service_api.go" in "restapi/operations" as builder
2017/08/16 16:52:07 goimports: scanning directory /Users/krasimir/src: permission denied
2017/08/16 16:52:07 name field UserManagementService
2017/08/16 16:52:07 package field operations
2017/08/16 16:52:07 creating "doc.go" in "restapi" as doc

**Comment by casualjim** [comment]
do you have it in your gopath or in your vendor?

**Comment by krasi-georgiev** [comment]
is it in the usual place and it I add it in the imports manually it compiles ok

```
$ ls /Users/krasimir/src/github.com/go-openapi/runtime/security
total 48
-rwxrwxrwx   1 krasimir  staff   4.2K 16 Aug 00:43 bearer_auth_test.go
-rwxrwxrwx   1 krasimir  staff   1.9K 16 Aug 00:43 basic_auth_test.go
-rwxrwxrwx   1 krasimir  staff   4.1K 16 Aug 00:43 authenticator.go
-rwxrwxrwx   1 krasimir  staff   2.6K 16 Aug 00:43 apikey_auth_test.go
drwxrwxrwx  44 krasimir  staff   1.5K 16 Aug 00:43 ..
drwxrwxrwx   6 krasimir  staff   204B 16 Aug 00:43 .
```

**Comment by casualjim** [comment]
I added a default imports list, which will hopefully fix this issue. Can you verify and provide feedback?

**Comment by krasi-georgiev** [comment]
now it ads some packages twice

```
restapi/operations/users/post_login.go:17: validate redeclared as imported package name
previous declaration at restapi/operations/users/post_login.go:15
```

hardcoding doesn't look like a good idea :)

maybe if you give me some pointers where is the goimport called so I can find out if maybe this `permission denied` error is the culprit.

**Comment by casualjim** [comment]
should be fixed now.

formatting happens here: https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L510-L523

**Comment by krasi-georgiev** [comment]
all good now 

didn't spend anytime about the goimport error , but now the last generation didn't even show that error.
