### ISSUE TITLE
Could Client be a concrete implementation of an interface?

### ISSUE THREAD

**Issue by danieljy** [go-swagger/go-swagger#1138]
This would allow for easy mocking out of clients.

https://github.com/go-swagger/go-swagger/blob/f8fdd34ee024def2304ce2417b6bab6046b8cb02/generator/templates/client/client.gotmpl#L33

Or is there a better way to do the mocking?

**Comment by casualjim** [comment]
the transport is an interface. You can use a NOOP roundtripper

**Comment by thomasjungblut** [comment]
It would still be great to have the ability to use a mocking library to assert whether something was called, injecting failure and other nice stuff.

**Comment by fredbi** [comment]
See pr #2151
