### ISSUE TITLE
Consumers do not handle headers with charset in them

### ISSUE THREAD

**Issue by ecnahc515** [go-swagger/go-swagger#114]
If an HTTP response has a Content-Type of `application/json;charset=utf-8` then the generated client's consumer will not properly handle the response and returns an error `no consumer: application/json;charset=utf-8"`. This is a valid header, and it should be able to handle the charset, and potentially other values in a header.

**Comment by casualjim** [comment]
fixed by: b73a1c8351724660a983e177343fbdcfc613581f
