### ISSUE TITLE
"operationId" is not allowed to be same under the different resources/objects

### ISSUE THREAD

**Issue by sun7927** [go-swagger/go-swagger#1141]
## Problem statement
The "operationId" can't be same as under the different resources. It doesn't make sense and make the generated code hard to use because of the meaningless function name. Looks swagger-codegen works better for it.

Is there any workaround or fix for it?
 
## Swagger specification
  ...
  "paths": {
    "/1.0/resource-1": {
      ...
      "get": {
        "operationId": "list",
      }
    },
    "/1.0/resource-2": {
      ...
      "get": {
        "operationId": "list",
        }
      },
   ...
## Steps to reproduce
 go-swagger validate <spec>
 will get error about "list" is defined 2 times

## Environment
swagger version: 2.0  
go version: 1.8.3
OS:   Mac OS

**Comment by casualjim** [comment]
operationId is always globally unique per swagger 2.0 specification. The id MUST be unique among all operations described in the API.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.
