### ISSUE TITLE
is there any option to specify the correct import prefix

### ISSUE THREAD

**Issue by sun7927** [go-swagger/go-swagger#1142]
## Problem statement
The generated code doesn't import the correct package path, which needs more extra effort to patch it.
Is there any option to specify the import prefix when generating code?

**Comment by casualjim** [comment]
this needs more context.
Which spec, what's the $GOPATH and what's the missing package?

**Comment by sun7927** [comment]
For example, go-swagger will generate the code like

storage_client.go
-------
package storage
import (
    "github.com/go-openapi/runtime"
    httptransport "github.com/go-openapi/runtime/client"
    strfmt "github.com/go-openapi/strfmt"

    "../../projects/myself/ui/tools/client/storage/filesystem/authentication"
    "../../projects/myself/ui/tools/client/storage/block/authentication"
)
---------

"storage/filesystem/authentication" and "storage/block/authentication" are also generated by go-swagger. However, they are imported into storage_client.go in a bad way which can't work without patching.

**Comment by jtegile** [comment]
@sun7927 , may I know how do you solve/workaround this issue?

**Comment by sun7927** [comment]
The workaround is:
   1. set GOPATH
   2. set the target to $(GOPATH)/src/github.com/<your pacakge>

**Comment by jtegile** [comment]
Should this issue be kept pen? 

Would it make more sense to generate relative import statement, instead of

"[number of .. from GOPATH-to-root]/[location-where-the-client-is-generated]" 

just using

"../client/[tag]" 
"../models" 

For example,  GOPATH is set to "/gowork" , and run '''swagger generate client" at directory "/gowork/src/company/project" , 

The current import section of /gowork/src/company/project/xxx_client.go will looks like

    import {
      ..
      "../gowork/src/company/project/tag"
    }

So, from "/gowork/src/company/project/xxx_client.go", "../gowork/src/company/project/tag" will not resolve correctly.

**Comment by sun7927** [comment]
Yes, it makes sense to me. As my project is going to be published to github.com, I added github.com ahead of company/project. After it, I can generate the code with correct import like "github.com/my_company/my_project". Not sure if it works correctly without github.com prefix.

**Comment by jtegile** [comment]
What's interesting is, once I set the GOPATH to "/gowork/src/company/project", the generated import section of "/gowork/src/company/project/client/xxx_client.go" becomes 

    import {
      ..
      "../client/tag"
    }

**Comment by casualjim** [comment]
which version of swagger are you using? did you build from master?

**Comment by jtegile** [comment]
0.11.0, from brew . 

Seems like Golang does not support relative import (sorry, still pretty new to Go), maybe the import path should be $PWD - $GOPATH/src , for example.
