### ISSUE TITLE
Duplicate operationId Error (operations are for separate endpoints)

### ISSUE THREAD

**Issue by taylageben** [go-swagger/go-swagger#1143]
## Problem statement

When generating a server and there are multiple endpoints, the `operations` directory in `restapi` contains subdirectories for each of those endpoints.

For example:

```yaml
paths:
  '/users/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: getById
      summary: Get User By ID
      tags:
        - Users
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/user-output'
  '/pets/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: getById
      summary: Get Pet By ID
      tags:
        - Pets
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/pet-output'
```

Should produce the following:
```
└── restapi
    ...
    ├── operations
    │   ├── pets
    │   │   ├── ...
    │   ├── users
    │   │   ├── ...
    │   └── ...
```

However, instead of generating the server I get this error: `"getById" is defined 2 times`

[Assuming I had used `getById` for both operations and it generated a server with no validation errors] When referring to these operations (example for response) in the api, we say `users.NewGetByIdOK()` or `pets.NewGetByIdOK()` which means it doesn't matter if the operation id was the same.

## Possible Solution
Is it possible to bypass this validation error *IF* the operation ids will go into separate directories?

**Comment by taylageben** [comment]
If you add the `--skip-validation` flag only one of the getByID operations will be generated

**Comment by casualjim** [comment]
operationId is always globally unique per swagger 2.0 specification. The id MUST be unique among all operations described in the API.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

**Comment by sun7927** [comment]
I am currently in the same problem. It makes more sense for the operationId to be unique per each endpoint. Per 2.0 spec, can we understand it to be unique as per endpoint but not globally?

**Comment by panania** [comment]
I realize that this is an old issue, but I just got this error in a Azure DevOps pipeline. I'm using the API Management task in my release.

2019-05-16T21:13:16.4509808Z @{code=ValidationError; target=representation; message=Parsing error(s): Cannot have multiple operations with the same operationId: Get}
2019-05-16T21:13:16.7856049Z ##[error]The remote server returned an error: (400) Bad Request.
2019-05-16T21:13:16.8243022Z ##[section]Finishing: API Management - Create/Update API 

sun7927 is right, it doesn't make sense to apply this rule globally; it should be by service. 

Has there been any movement on this?

**Comment by gregmarr** [comment]
No, the Swagger 2.0 spec doesn't allow it.  It says it MUST be globally unique.

**Comment by panania** [comment]
Weird

I did find a Swashbuckle swagger gen line of code for the configure
services that added the service name to the front of the operation making
those unique, but it doesn't help me with the Get (as in get all) and
Get/Id (as in get this one).

Thank you for your help, I'll figure something out.

Peter
