### ISSUE TITLE
How the Response Sample was Executeing?

### ISSUE THREAD

**Issue by Avinash489** [go-swagger/go-swagger#1144]
## Problem statement
We need to know about , How the Models are Running and executing?

We Gone Through the Flow  swagger.go<serve.go<redoc.go 
In redoc.go , we struct at the Point library included redoc.min.js 

Please Guide us Through the flow.
Please remove the sections that don't apply

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by casualjim** [comment]
can you try to explain your question more clearly?
What is it you want to achieve?

the serve command by default serves a redoc ui.
redoc is only to serve a documentation page for your specification, it doesn't implement any logic

**Comment by Avinash489** [comment]
I Need to understand the flow , How the Models has been executing?

**Comment by casualjim** [comment]
I have no idea what you mean by understand the flow, how models has been executing.

there is code generated. a request arrives the routes select a handler and the request is validated, then your code executes

**Comment by kreamyx** [comment]
If this issue is resolved, can we close it?

**Comment by fredbi** [comment]
This thread is leading us nowhere. Maybe a lack of documentation? Let's close it.
