### ISSUE TITLE
Generating spec pulls in unused enumeration types from Protobuf-generated files

### ISSUE THREAD

**Issue by iamtheddrman** [go-swagger/go-swagger#1149]
## Problem statement

I have an enumeration definition that isn't used by any documented routes or models, but is being automatically included in a generated swagger.json file when running swagger generate spec. Due to our code structure, I end up with dozens of these model definitions that serve no purpose in our interface and have no documentation. Is there a way to request that these type definitions be skipped in the generation process?

There are a lot of moving parts with this, so bear with me please.

I have a need to generate Go bindings for a Google Protobuf file, using protoc and protoc-gen-go. In our messages, we have a Message ID enumeration that differentiates the messages, like so:

`message Test
{
    enum MessageId
    {
        ID = 1;
    }
}`

which generates the following Go code:

`type Test_MessageId int32
const (
    Test_ID Test_MessageId = 1
)
var Test_MessageId_name = map[int32]string{
    1: "ID",
}
var Test_MessageId_value = map[string]int32{
    "ID": 1,
}
...
proto.RegisterEnum("Test_MessageId", Test_MessageId_name, Test_MessageId_value`

Nowhere in my Go project is "Test_MessageId" used, other than this file. No go-swagger documented routes or models lead back to this "enum" type definition, yet running the spec generator results in a swagger.json file that contains a definition for the enumeration:

`{
...
  "definitions": 
    "Test_MessageId": {
      "type": "integer",
      "format": "in32",
      "x-go-package": "test/gpb_gen_test"
    },
...
}`

If this problem is prohibitively difficult to workaround (which I suspect it will be given the interaction with GPB and other tools), then would it be possible to have a type comment similar to "swagger:model" that ignores a particular type when generating a spec, such as "swagger:ignore" or "swagger:skip"? That would be sufficient for my needs, as I can programmatically insert those comments as needed during our build process. Thanks in advance!

## Swagger specification
2.0

## Steps to reproduce
1) Create a .proto file with a message containing an enum (shown above)
2) Download protoc and protoc-gen-go, then run "protoc --go_out=. Test.proto" to generate Go bindings
3) Insert said file into a project that has swagger:model and swagger:operation meta-comments without using the enumeration anywhere
4) Run "swagger generate spec -o ./swagger.json -m main.go" on the Go project
5) Inspect swagger.json to see extraneous type definition

## Environment
go-swagger version: 0.11.0
go version: 1.8.3 
OS: Windows 10

**Comment by casualjim** [comment]
if you don't use -m do still see the issue?

**Comment by iamtheddrman** [comment]
I make use of swagger:model to mark the types generated by protoc as definitions for use by the routes. So if I take out -m, I don't get the enumerations, but I also don't get any of the definitions that I do need.

**Comment by fredbi** [comment]
In order to properly close this issue, swagger:ignore annotation should be documented in docs/generate/spec
