### ISSUE TITLE
Generate client does not handle "-" dashes in --client-package consistently

### ISSUE THREAD

**Issue by benderillo** [go-swagger/go-swagger#1157]
## Problem statement
When generating client code from the swagger spec yaml and providing --client-package argument that contains dashes (`-`), generated code will be placed into the folder that has the same name that was given as --client-package but the `import` statements in the generated source code will refer to a folder name where all the dashes are replaced with underscores `_`.

## Swagger specification
2.0

## Steps to reproduce
1. Have a swagger spec file my_api_spec.yaml
2. Issue a command:
`/usr/bin/swagger generate client --client-package my-service --spec my_api_spec.yaml`

**Expected result:**
Client source code is generated under "**my-service**" folder and generated files contain import sections where the modules are referred to as `"<some path>/`**my-service**`/<module name>"`
**OR**
Client source code is generated under "**my_service**" folder and generated files contain import sections where the modules are referred to as `"<some path>/`**my_service**`/<module name>"`

**Actual result:**
Client source code is generated under the "**my-service**" folder BUT generated source code files contain import sections referring to the folder `"<some path>/`**my_service**`/<module name>"`

## Environment
swagger version:
docker image quay.io/goswagger/swagger:0.11.0
go version: 
go1.9 darwin/amd64
OS:   
linux alpine (https://quay.io/repository/goswagger/swagger?tag=0.11.0&tab=tags)

**Comment by ssimono** [comment]
:+1:  I noticed this as well

**Comment by fredbi** [comment]
Seen same behaviour with server generation: path items with '-' are modified by internal "snakize" function.
