### ISSUE TITLE
Can't read $ref Schema properties

### ISSUE THREAD

**Issue by kisPocok** [go-swagger/go-swagger#1159]
## Problem statement

Schema is empty if I use `$ref`. Example below.

## Swagger specification
```
swagger: '2.0'
basePath: /base-path
paths:
  '/some-path':
    get:
      responses:
        '200':
          description: "I can read this value"
          schema:
            $ref: '#/definitions/SomeResponse'
definitions:
  SomeResponse:
    description: No overwrite at all.
    properties:
      someField:
        type: integer
        format: int32
        example: 0
    required:
      - someField
```

## Steps to reproduce

Run the following code:
```
spec, _ := loads.Spec(pathToFile)
spec.Spec().Paths.Paths["/some-path"].Get.Responses.StatusCodeResponses[200].Schema
```
It will return an empty spec.Schema struct. It ignores the whole `$ref` definition. Can't read Schema.Properties or Schema.Required properties.

## Environment
swagger version: 2.0
go version: 1.7.3 & 1.9.0
OS: darwin/amd64

**Comment by casualjim** [comment]
Ref will have been filled out though. It doesn't expand them by default.
But you have options:

* flatten the spec: `swagger flatten --help`
* expand the spec: `swagger expand --help`
* or resolve the ref: `spec.ResolveRef(spec.Spec(), &spec.Spec().Paths.Paths["/some-path"].Get.Responses.StatusCodeResponses[200])`

**Comment by kisPocok** [comment]
Casualjim, you have saved my life. `spec.ResolveRef()` is the solution. Thanks.
