### ISSUE TITLE
No properties generated in json file for swagger:response

### ISSUE THREAD

**Issue by mugdhachauhan** [go-swagger/go-swagger#1161]
## Problem statement
`swagger:response` annotation is not generating `properties`in json file.
I am using same  example as shown in https://github.com/go-swagger/go-swagger/blob/master/docs/generate/spec/response.md

I am not sure what is missing?
similar issue is faced when using `swagger:parmeters` example

## Steps to reproduce
here is code in test.go file
```go
package main
// A ValidationError is an error that is used when the required input fails validation.
// swagger:response validationError
type ValidationError struct {
	// The error message
	// in: body
	Body struct {
		     // The validation message
		     //
		     // Required: true
		     message string
		     // An optional field name to which this validation applies
		     fieldName string
	     }
}
```
execute `swagger generate spec  -o ./swagger.json` command

swagger.json generated is 
```json
{
  "swagger": "2.0",
  "paths": {},
  "responses": {
    "validationError": {
      "description": "A ValidationError is an error that is used when the required input fails validation.",
      "schema": {
        "type": "object"
      }
    }
  }
}
```
## Environment
swagger version: 2.0
go version: 1.8.3
OS:  mac

**Comment by casualjim** [comment]
The properties in the body struct need to be exported otherwise it can't generate json for it or read it in from json

**Comment by mugdhachauhan** [comment]
Sorry but i am not clear what do you mean by `properties in the body struct need to be exported`. can you give a example?

**Comment by casualjim** [comment]
Their names need to be capitalized: 

```go
package main
// A ValidationError is an error that is used when the required input fails validation.
// swagger:response validationError
type ValidationError struct {
	// The error message
	// in: body
	Body struct {
		     // The validation message
		     //
		     // Required: true
		     Message string
		     // An optional field name to which this validation applies
		     FieldName string
	     }
}
```

**Comment by mugdhachauhan** [comment]
But with exporting properties(capitalizing) and running `swagger generate spec -o ./swagger.json` command i see error `unable to determine package `

**Comment by mugdhachauhan** [comment]
So here is my test.go
```
package main

import (
	"testing/validation"
	"fmt"
)
// swagger:route GET /v1/list validationError
//
// Get list of something
//
//     Responses:
//       500: validationError

func main(){
	fmt.Println(validation.ValidationError{})
}
```
And validation.go
```
// swagger:response validationError

type ValidationError struct {
	// The error message
	// in: body
	Body struct {
		     // The validation message
		     //
		     // Required: true
		     Message string
		     // An optional field name to which this validation applies
		     FieldName string
	     }
}
```
and still json generated is 
```
{
  "swagger": "2.0",
  "paths": {
    "/v1/list": {
      "get": {
        "description": "Get list of something",
        "operationId": "validationError",
        "responses": {
          "500": {
            "$ref": "#/responses/validationError"
          }
        }
      }
    }
  }
}
```
Sorry but i just want one basic example to get working so that i work with other files

**Comment by mugdhachauhan** [comment]
Can i get some help with this? `properties` are still missing in `swagger.json` file

**Comment by mugdhachauhan** [comment]
@casualjim I was able to generate correct json file. Thanks for your help :)

**Comment by ianaz** [comment]
How did you solve this? My `swagger:model` struct  is already in a package that's not main

**Comment by ritheshgm** [comment]
+1

**Comment by mfolkeseth** [comment]
I had the same problem when using go via homebrew.

What solved it for me was to install go from the go webside https://go.dev/doc/install and unset `GOROOT` and the path resolved itself

```
GOROOT=/usr/local/go/bin go env -u GOROOT
```
