### ISSUE TITLE
`go-openapi/runtime` introduces backwards incompatible API change

### ISSUE THREAD

**Issue by MatthewHartstonge** [go-swagger/go-swagger#1165]
## Problem statement
The `go-openapi/runtime` library has introduced a [backwards incompatible API change](https://github.com/go-openapi/runtime/commit/0fd0aae5036b889b33df1d058572b8692ae97602), where a new interface, [Authorizer](https://github.com/go-openapi/runtime/commit/0fd0aae5036b889b33df1d058572b8692ae97602#diff-6e4d361807e32222783998dd52ee5ea3R93), is required to be implemented and causes the following error:

```sh
service\http\restapi\operations\my_api.go:344:46: cannot use o (type *MyAPI) as type middleware.RoutableAPI in argument to middleware.NewRoutableContext:
        *MyAPI does not implement middleware.RoutableAPI (missing Authorizer method)

```

## Swagger specification
v2.0

## Steps to reproduce
```sh
swagger generate server -f ./swagger/swagger.yml -t ./service/http
go get github.com/go-openapi/runtime
go get github.com/tylerb/graceful
go get github.com/jessevdk/go-flags
```

## Environment
swagger version: 2
go version: 1.8.3/1.9.0
OS: Windows 10/Alpine Linux

**Comment by MatthewHartstonge** [comment]
I believe #1162 has become victim of this as well.

For now, we are pinning the run time to the hash before the specific commit. We use [Glide](http://glide.sh/) internally for dependency management. For those affected, add this into your `glide.yaml` file:

```yaml
- package: github.com/go-openapi/runtime
  version: f1447ecfd160e50218589d4db3fb28bd24b8dec8
```

**Comment by jorgesece** [comment]
Hi all! how can I solve it with govendor?
Many thanks

**Comment by MatthewHartstonge** [comment]
Having a quick look at the govendor readme, I think: `govendor fetch github.com/go-openapi/runtime@f1447ecfd160e50218589d4db3fb28bd24b8dec8` should do the trick.

**Comment by jorgesece** [comment]
Hi @MatthewHartstonge,
Setting the revision to `f1447ecfd160e50218589d4db3fb28bd24b8dec8` I get another error: `undefined: runtime.Authorizer`.
Do you have any idea how to solve it?

**Comment by casualjim** [comment]
I'll cut a new release today

**Comment by casualjim** [comment]
pushed a new release

**Comment by Crevil** [comment]
This issue seems to be reintroduced in the `latest` image.

**Comment by vaughanb** [comment]
Same issue here. Generated server code won't run because runtime.Authorizer is not defined.

**Comment by ksswr** [comment]
Is this project still active?  I am having this same problem and it does not seem to be being addressed, rolling back version fixes it, but breaks stuff elsewhere.

**Comment by casualjim** [comment]
you have to update your vendor and the swagger binary tool.
The 2 advance in lock-step, it's only an issue with the docker container.

**Comment by casualjim** [comment]
if the runtime.Authorizer is not defined that means that the runtime project or the swagger binary (templates) are not updated to reflect that.

**Comment by hixichen** [comment]
same issue:
 runtime.Authorizer is not defined.

modified the runtime version, but doesnot work. 

swagger version: 0.13

**Comment by hixichen** [comment]
fixed:

update pckage:
go-openapi/runtime
go-openapi/analysis
go-openapi/spec

**Comment by gangtao** [comment]
Having same issue, with swagger version
version: 0.7.3
commit: 01d9ee15ff01cdbfdc735d21949a7cc66ab6ab56

go build ./server/cmd/a-sample-service-server/main.go 
# gangtao/go-service/server/restapi/operations
server/restapi/operations/a_sample_service_api.go:188:46: cannot use o (type *ASampleServiceAPI) as type middleware.RoutableAPI in argument to middleware.NewRoutableContext:
	*ASampleServiceAPI does not implement middleware.RoutableAPI (missing Authorizer method)
server/restapi/operations/get_time.go:41:11: assignment mismatch: 2 variables but 3 values
server/restapi/operations/post_time.go:41:11: assignment mismatch: 2 variables but 3 values
