### ISSUE TITLE
swagger json, title and possibly other constants in a separate package

### ISSUE THREAD

**Issue by sidhman** [go-swagger/go-swagger#1169]
## Problem statement
We need to be able to access various constants from swagger spec (right now only Title, but json spec seems like a good candidate too) from Go code that is not part of the service in question. Right now we are forced to import whole restapi package with server, configuration and everything which brings a lot of unnecessary public code and might break if you happen to have init() code in restapi package.

## Proposal
Either add a separate package for such constants or add those into models package.

Or may be there is a more preferable way to do it?

**Comment by fredbi** [comment]
@isinelnikov  That is really a case study for custom templates. I don't think this particular requirement needs to be included as a feature.

Actually, this would made a perfect example to illustrate how custom templates may be used.

If you wish to submit a documented example with this as a PR, that would be great. Ask for guidance here or on slack if you need help with this.
