### ISSUE TITLE
swagger generate server -f ./swagger.json

### ISSUE THREAD

**Issue by aktwang** [go-swagger/go-swagger#117]
Hi,

When I try to generate a GO server with my swagger.json file (which passes validation), I get the following message:

 2015/11/18 11:23:01 rendered model template: vmid
2015/11/18 11:23:01 generated model vmid
2015/11/18 11:23:01 rendered model template: vmspec
2015/11/18 11:23:01 generated model vmspec
2015/11/18 11:23:01 rendered model template: error
2015/11/18 11:23:01 generated model error
2015/11/18 11:23:01 rendered model template: vmspec_cpu
2015/11/18 11:23:02 generated model vmspec_cpu
2015/11/18 11:23:02 rendered model template: vmspec_memory
2015/11/18 11:23:02 generated model vmspec_memory
2015/11/18 11:23:02 target must reside inside a location in the GOPATH

A models directory is generated.  What does the error mean that target must reside inside a location in the GOPATH?  Thank you.

**Comment by aleksandr-vin** [comment]
Where are you calling `swagger generate`? And what are your GOPATH?

**Comment by casualjim** [comment]
it means that when you generate a server you must do this in a location inside the [GOPATH](https://golang.org/doc/code.html).
go-swagger uses the go build infrastructure so it needs to be able to resolve dependencies etc.

**Comment by aktwang** [comment]
Ah ha.. Thanks.  With this, I got further:
 aktwang@aktwang-VirtualBox:~/.gvm/pkgsets/go1.4/global/src/github.ibm.com/user/json$ echo $GOPATH
/home/aktwang/.gvm/pkgsets/go1.4/global
aktwang@aktwang-VirtualBox:~/.gvm/pkgsets/go1.4/global/src/github.ibm.com/user/json$ swagger generate server -f ./swagger.json
2015/11/18 11:52:41 rendered model template: vmspec_memory
2015/11/18 11:52:42 generated model vmspec_memory
2015/11/18 11:52:42 rendered model template: vmid
2015/11/18 11:52:42 generated model vmid
2015/11/18 11:52:42 rendered model template: vmspec
2015/11/18 11:52:42 generated model vmspec
2015/11/18 11:52:42 rendered model template: error
2015/11/18 11:52:42 generated model error
2015/11/18 11:52:42 rendered model template: vmspec_cpu
2015/11/18 11:52:42 generated model vmspec_cpu
2015/11/18 11:52:42 rendered handler template: Default.VMPost
2015/11/18 11:52:42 generated handler Default.VMPost
2015/11/18 11:52:42 rendered parameters template: Default.VMPostParameters
2015/11/18 11:52:42 generated parameters Default.VMPostParameters
2015/11/18 11:52:42 rendered responses template: Default.VMPostResponses
2015/11/18 11:52:42 generated responses Default.VMPostResponses
2015/11/18 11:52:42 rendered builder template: operations.Genesis
2015/11/18 11:52:42 genesis_api.go:51:17: expected ';', found 'default' (and 3 more errors)
2015/11/18 11:52:42 rendered embedded Swagger JSON template: server.Genesis
2015/11/18 11:52:42 rendered configure api template: operations.ConfigureGenesis
2015/11/18 11:52:42 configure_genesis.go:28:23: expected operand, found 'default' (and 2 more errors)
2015/11/18 11:52:42 rendered main template: server.Genesis
aktwang@aktwang-VirtualBox:~/.gvm/pkgsets/go1.4/global/src/github.ibm.com/user/json$

**Comment by aktwang** [comment]
Hi guys, My server code generation works great!  However, I have a general question.  Let's say if I modify some of my APIs (the swagger.json) file, and having the need to regenerate the server code.  However, I've added my own code into some Handler routines already.  So, does that mean I have to re-do all the work after I regenerate again?  Thanks!

**Comment by casualjim** [comment]
if you put your code in the configure_XXX.go file then it won't get overwritten

**Comment by aktwang** [comment]
casualjim, Thanks for the quick reply. I took a closer look at the server code and now have a better understanding on how to use it.  Another general question, I also generated the client.  (went smoothly!) How do I use the client? :)  I assume I should write my own main(), right?  I see a default_client.go in the default directory and a XXX_client.go file generated.  Thanks again!

**Comment by casualjim** [comment]
to use the client, yes you need your own main()
The code usage is documented a bit here, please let me know of any difficulties you encounter with that:
http://go-swagger.github.io/generate/client/

**Comment by aktwang** [comment]
Ah ha.  This is mighty useful (the doc)! Thanks casualjim.

**Comment by aktwang** [comment]
casualjim, More questions...  What's the difference between using a httptransport to create a client and not using it?  Also, I have two client files generated.  Should I add my main in the default_client.go file, or the XXX_client.go file?  (this one may be a dumb question because I ought to figure it out by reading the code..right? :)

**Comment by casualjim** [comment]
for your own sanity please join: https://slackin.goswagger.io/

**Comment by casualjim** [comment]
for a client for a todo list, you want to use the client facade which is going to be in the ./client package

https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/to_do_list_client.go#L15-L39

There you have 3 things that are immediately useful.
If you don't have to change or configure a thing then you can go with the Default one, no setup is required.
If you're sure you're going to work with HTTP (atm I'm guessing this is 100% of the cases) then the NewHTTPClient() might work fine for you.

if you need more customization then you are required to pass in a transport and so on. This is mostly because after the first release it is getting different transports and I want them to be a matter of config.
