### ISSUE TITLE
Composite Model Generated Structs have changed

### ISSUE THREAD

**Issue by kkarabian** [go-swagger/go-swagger#1172]
This just started happening with 0.12.0 I believe.

## Problem statement

Generated models structure has changed for composites from:
```
type ReportScore struct {
    ScoreData

    LastUpdateTime *string `json:"lastUpdateTime"`
}
```
to
```
type ReportScore struct {
    ScoreData

    ReportScoreAllOf1
}
```
for the following specification:

## Swagger specification
```
  ReportScore:
    allOf:
      - $ref: '#/definitions/ScoreData'
      - type: object
        properties:
          lastUpdateTime:
            type: string
        required: [lastUpdateTime]
```
## Steps to reproduce
swagger generate client -t swaggen -f apispec.yaml

## Environment
swagger version: 0.12.0 
go version: 1.8.3
OS:   Mac OS 10.10.5

**Comment by casualjim** [comment]
if you build the swagger command from master you can generate your client with a `--skip-flatten` flag and that should restore the previous behavior
