### ISSUE TITLE
some codepaths in server generation assume "./src" while other assume "./" 

### ISSUE THREAD

**Issue by notasecret** [go-swagger/go-swagger#1176]
## Problem statement

Try to generate go server code, and it fails, complaining about paths.

```
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ alias swagger="docker run --rm -it -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ swagger version
version: dev
commit: 8110e1bfee9ca99f346cdad6146dfe05161cb905
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ ls src/
morningTulips	xxx		xxx-server
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ echo $GOPATH
/Users/jonmclachlan/xxx/xxx-backend
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ swagger generate server -f swagger/swagger.yaml -A xxx -t xxx
2017/09/18 01:49:40 building a plan for generation
2017/09/18 01:49:40 lstat /Users/jonmclachlan/xxx/xxx-backend/xxx: no such file or directory
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ swagger generate server -f swagger/swagger.yaml -A xxx -t src/xxx
2017/09/18 01:49:51 building a plan for generation
2017/09/18 01:49:51 target must reside inside a location in the $GOPATH/src
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ 
```

This used to work.

## Environment
swagger version: 8110e1bfee9ca99f346cdad6146dfe05161cb905
go version: whatever is in your latest docker img

**Comment by notasecret** [comment]
this is the commit:

commit fb51ecafe32dd2e9ea3cd697d30044fd2ee514a9
Author: Tushar <taggarwal@vmware.com>
Date:   Mon Aug 28 11:36:46 2017 -0700

    Corrected Path generation for Base Imports

**Comment by EleanorRigby** [comment]
@notasecret : Is your target path inside GOPATH? Are there any symlinks that you are using in your path? 
There was a bug due to which all the paths for code generation worked. Now the behavior is corrected.

**Comment by notasecret** [comment]
Is your target path inside GOPATH? 
Yes, as you can verify above.

Are there any symlinks that you are using in your path?
No sym link funny business.

Yea, I am trying to gen inside src. I think the target without the "src" addition passes your code checks, because you added "src" folder to all the possible gopath's swagger finds, and, in other places in swagger server code gen, the target path does not get that "src" folder appended to it, and breaks?

**Comment by casualjim** [comment]
I think as a workaround for now  you can get it to work by running `mkdir -p $GOPATH/src/xxx` prior to generating?

**Comment by notasecret** [comment]
@casualjim , many thx, I tried,

```
Jons-MacBook-Pro-2:xxx-backend jonmclachlan$ ls src/
morningTulips	xxx		xxx-server
```

xxx was the folder.  Has 777 permissions, too.

**Comment by EleanorRigby** [comment]
@notasecret  target without  the src folder fails in very first step of the same function because it cannot see any such directory. That's the lstat error. I was able to reproduce that.

I am not able to reproduce your second error.  When running swagger through docker do you pass environment variable GOPATH , otherwise it defaults to $HOME/go

**Comment by EleanorRigby** [comment]
@notasecret : So, I finally found the problem. I noted that inside docker environment for the dev image I created similar to one on quay.io has `GOPATH=/go`

```
2017/09/19 02:37:45 target path is   src/test
2017/09/19 02:37:45 tgtAbsPath is /Users/taggarwal/go/src/test
2017/09/19 02:37:45 Gopath is /go
2017/09/19 02:37:45 In for loop gopath is /go
2017/09/19 02:37:45 In for loop gopath(symlink) is /go
2017/09/19 02:37:45 In for loop gopath(symlink) with src is /go/src
2017/09/19 02:37:45 Childpath and Parentpath are /Users/taggarwal/go/src/test and /go/src respectively
2017/09/19 02:37:45 Childpath and Parentpath are /Users/taggarwal/go/src/test and /go/src respectively
2017/09/19 02:37:45 Childpath and Parentpath are /Users/taggarwal/go/src/test and /go/src respectively
2017/09/19 02:37:45 target must reside inside a location in the $GOPATH/src
```

So, the GOPATH and target path do not match. You need to pass the intended `GOPATH` as environment variable inside docker run command like the one below. `DO NOT APPEND src to it`
This worked for me and hopefully will unblock you too. 
```
alias swagger="docker run -e GOPATH=/Users/taggarwal/go --rm -it -v $HOME:$HOME -w $(pwd) swagger:dev"
```
Also, create the intended directory before you run this command. 

Evaluation of symlink (confusing stuff but people still use it) in target path raises the lstat error if target path does not exist. I am starting the work to fix this. Possible solution being, creating the target path if it doesn't exist before evaluation of any kind.

**Why it doesn't work now and used to work earlier?**
The earlier code had a bug , it never checked whether the target path is inside GOPATH. While most users had target path inside GOPATH/src but those who did not were facing generation of wrong import paths. Post my commit the correction happened and it stopped working for you.

**Comment by notasecret** [comment]
@EleanorRigby , that was it exactly, my bad, many thx :)

**Comment by notasecret** [comment]
closing.
