### ISSUE TITLE
Recent JSON Marshal/Unmarshal commit broke JSON body parsing

### ISSUE THREAD

**Issue by nugget** [go-swagger/go-swagger#1177]
## Problem statement

I have an API that pulls login credentials from a JSON body payload.  It works fine with 0.12.0 but with master (commit dbc9b97 at this time) it breaks.  Calling the endpoint yields a 400 with the message
```
{
  "code": 400,
  "message": "parsing credentials body from \"\" failed, because json: cannot unmarshal object into Go value of type *models.Credentials"
}
```

Binding in my code is done via:

`api.AuthenticationPostLoginHandler = authentication.PostLoginHandlerFunc(login)`

with function defnition:

`func login(params authentication.PostLoginParams) middleware.Responder { ... }`

If I checkout tag `0.12.0` everything works.  If I checkout master it breaks.

## Swagger specification

Relevant portions of my swagger.yml:

```
paths:
  /login:
    post:
      summary: Login endpoint
      description: 'Login here'
      security: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credentials
          in: body
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Login'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Message'
        '401':
          description: Invalid credentials
          schema:
            $ref: '#/definitions/Message'
```

and

```
definitions:
  Credentials:
    properties:
      username:
        type: string
      password:
        type: string
      token:
        type: string
```

## Steps to reproduce

If it would help I can try to construct a minimal codebase that induces the error, but I'm hoping this is simple enough that the fix will be obvious to @EleanorRigby and won't require that.

## Environment
swagger version: master branch
go version: 1.9
OS:   Linux (CentOS 7)

**Comment by casualjim** [comment]
@EleanorRigby I think this comes from golangs json library using the textmarshaler interfaces itself too.
As such what we didn't isn't very helpful and will break more applications than the fix it's trying to provide.
We should revert this commit and look at why redirects aren't being respected instead

**Comment by EleanorRigby** [comment]
The pull request to back out the change has been  created  #1178

**Comment by nugget** [comment]
Thanks, I'm back to normal now!
