### ISSUE TITLE
feature: support custom swagger type

### ISSUE THREAD

**Issue by imiskolee** [go-swagger/go-swagger#1183]
if we has a custom MarshalJSON/MarshalXML struct.input data type maybe cant matched to out data type.

the feature can be custom a data type ,its Like

```go

//swagger:type string
type OwnerInput struct {

}

func (c *OwnerInput)UnmarshalJSON(data []byte) error {
  //in here,unmarshal a string to a golang struct
}

```

**Comment by imiskolee** [comment]
who can add it to document?

**Comment by casualjim** [comment]
the documentation goes here:
https://github.com/go-swagger/go-swagger/tree/master/docs/generate

**Comment by imiskolee** [comment]
@mrostecki no any flag on command line. just use comment `//swagger:type string` on your type. example:

```go
//swagger:type int
type MyCustomInt int
```

**Comment by imiskolee** [comment]
#1567 already put docs, will closed it.
