### ISSUE TITLE
Override client template parameters.gotmpl

### ISSUE THREAD

**Issue by ilinamitra** [go-swagger/go-swagger#1190]
## Problem statement
I'd like to override the parameters.gotmpl default template file specified here: 
https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/parameter.gotmpl

I've created a new parameters.gotmpl file and am passing it via the --template-dir flag to my swagger generate client command:

swagger generate client --spec=/repo/swagger.yaml --template-dir=/repo/templates ...

However, the generated client code does not seem to be picking up my changes to parameter.gotmpl. I tried placing parameter.gotmpl under a templates folder, as well as under a client folder beneath a templates folder. 

Am I using --template-dir incorrectly? Is it not possible to override the client parameter.gotmpl template?

**Comment by ilinamitra** [comment]
P.S. Unless I remove the Copyright line, I receive the following error:
`can't evaluate field Copyright in type *generator.GenOperation`

**Comment by ilinamitra** [comment]
Update: It seems if I include all the .gotmpl files in templates/server, templates/client, and templates/validation, and then modify the templates/client/parameter.gotmpl file directly, the changes are included in the generated client code. 

However, I'd really like to just have to pass the one parameter.gotmpl file to --template-dir than pull in all the other .gotmpl files (especially since I'm not modifying the other ones).

**Comment by EleanorRigby** [comment]
@ilinamitra : is it possible for you to share your parameters.gotmpl file here?

Also, could you elaborate more on copyright line. Are you removing that line from your own parameters.gotmpl or the one provided in source code?

**Comment by ilinamitra** [comment]
[parameter_gotmpl.txt](https://github.com/go-swagger/go-swagger/files/1354219/parameter_gotmpl.txt)
Yes no problem, All I did was remove the Copyright line, and added an extra comment on line 61 to indicate that the generated code is coming from my template instead of the default.

As I mentioned above, my template does get picked up if I include multiple other .gotmpl files under the client, server, and validation directories.

**Comment by EleanorRigby** [comment]
@ilinamitra : Just to be clear, 

- you are creating a new directory 
- placing your template file inside it as parameter.gotmpl
- This does not work unless you include multiple other gotmpl files under client server, validation dir (When you say multiple other do you mean all the templates or some of them)
- When it does work on including everything the modified template gives you copyright error on omitting that line.

Is this the correct flow of what's happening?

**Comment by ilinamitra** [comment]
Hi @EleanorRigby 

I think I figured out the issue, I had placed the original parameter.gotmpl file under the wrong path. Now I have it under the right path, and no longer need the other .gotmpl files. Apologies for the noise!
