### ISSUE TITLE
Generate with principal from a vendored package

### ISSUE THREAD

**Issue by Crevil** [go-swagger/go-swagger#1196]
## Problem statement

Is it possible to generate server code with a principal model from a vendored package?
With swagger 0.12.0 the import is not resolved and results in a compile error in the generated code, as the type is not found. The package is in the `GOPATH`.

It could be nice if one could supply the full path to the package to the `principal` flag, something like:

```
swagger generate server \
  --principal 'github.com/lunarway/authentication/authentication.Auth'
```
## Steps to reproduce
The folder structure of the a vendored application:

```
|- api
|-- swagger.yaml
|- main.go
|- vendor
|-- github.com
|--- lunarway
|---- authentication
|----- authentication.go
```

And the generate command

```shell
swagger generate server \
  --spec api/swagger.yaml \
  --name service \
  --target ./generated \
  --principal 'authentication.Auth'
```

## Environment
swagger version: 0.12.0  
go version: 1.9.0  
OS:  Apple macOS Sierra 10.12.6

**Comment by Crevil** [comment]
I've got this working by making sure the package was in vendored and in the `GOPATH` and the type had a unique name. In my case renaming `authentication.Auth` to `authentication.Principle`.

**Comment by casualjim** [comment]
there is a way to use a pre-existing type that exists on the file system.
That would be another way to solve this problem.

**Comment by piepmatz** [comment]
> there is a way to use a pre-existing type that exists on the file system.

@casualjim: How?

**Comment by prasannamahajan** [comment]
@casualjim How ?

**Comment by casualjim** [comment]
see here: https://github.com/go-swagger/go-swagger/blob/228b3d56597d89f8ea1543d98c35fd710fa103a3/fixtures/codegen/existing-model.yml#L57-L66

**Comment by prasannamahajan** [comment]
You can use principal defined in other package by using  --existing-models option.

For example,
Suppose the principle I want to use is "User" struct defined in "auth" package which is at path "github.com/prasannamahajan/auth"

So I will use following command

`
swagger -q generate server -t gen -f swagger.yaml  -P auth.User --existing-models "github.com/prasannamahajan/auth"
`
