### ISSUE TITLE
Codegen generates invalid go code for `additionalProperties: true`

### ISSUE THREAD

**Issue by rabisg** [go-swagger/go-swagger#1198]
## Issue
On trying to generate code with the following yaml the model generated has invalid code. The root cause seems to be setting `additionalProperties: <boolean>` instead of `additionalProperties: <object>`.
There seems be some confusion regarding whether setting it to boolean is valid or not in 2.0 (but 3.0 mentions it as a possible value in its docs)

Relevant discussion: https://github.com/OAI/OpenAPI-Specification/issues/668

## Swagger specification
```
swagger: '2.0'
info:
  version: 1.0.0
  title: 'string-body-api'
paths:
  /echo:
    post:
      summary: Post an object
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/pet"
      responses:
        '200':
          description: All is good
definitions:
  pet:
    type: object
    required:
      - date
    properties:
      date:
        additionalProperties: true
        type: object
        description: Foo
```
## Steps to reproduce
`swagger generate client -f <file.yaml>`

## Generated code
```
type Pet struct {

  // Foo
  // Required: true
  Date interface{} `json:"date"`
}
...
func (m *Pet) validateDate(formats strfmt.Registry) error {

  if swag.IsZero(m.Date.DateAdditionalProperties) { // not required
    return nil
  }

  return nil
}
```
## Environment
swagger version: master 
go version: go version go1.7.4 linux/amd64
OS: Centos

**Comment by EleanorRigby** [comment]
@rabisg : The OpenApi spec 2.0 to which go-swagger currently confirms says that AdditionalProperties is a schema object. So, if you change `additionalProperties: true` to `additionalProperties: {}` it will produce a compilable code.

**Comment by EleanorRigby** [comment]
One of the comment on OAI/OpenAPI-Specification#668 states that 

```
Note that in the forthcoming-very-soon-now draft-wright-01 (a.k.a. Draft 06), any schema or subschema, not just "additionalProperties" and "additionalItems", can be a boolean:

true is {}
false is {"not": {}}
```
Since go-swagger supports openapi 2.0 , I will suggest you to put {} instead of true for now and proceed till go-swagger starts supporting openapi 3.0.

**Comment by rabisg** [comment]
I'll try to use that workaround for now but I guess it's still a bug worth fixing. I'll try to give this a shot when I have time.

**Comment by gregmarr** [comment]
Looks good now.
    
    // Validate validates this pet
    func (m *Pet) Validate(formats strfmt.Registry) error {
        var res []error

        if err := m.validateDate(formats); err != nil {
            // prop
            res = append(res, err)
        }

        if len(res) > 0 {
            return errors.CompositeValidationError(res...)
        }
        return nil
    }

**Comment by fredbi** [comment]
@rabisg coudl you please confirm your issue is now solved?

**Comment by rabisg** [comment]
Thanks for the fix. It works now :)
