### ISSUE TITLE
Awkward filenames are generated for some uppercase names

### ISSUE THREAD

**Issue by jaspervdj** [go-swagger/go-swagger#1202]
## Problem statement

Object names like `ELB.HTTPLoadBalancer` are legal in Swagger.  `goswagger` seems to generate reasonable type names (`ELBHTTPLoadBalancer`), but the file names are fairly awkward (`e_l_b_http_load_balancer.go`).  I believe this should be `elb_http_load_balancer.go`.

## Swagger specification

```
swagger: '2.0'
info:
  version: '0.0.1'
  title: Snake case test case
  description: Example of weird snake case filename generation in goswagger
definitions:
  ELB.HTTPLoadBalancer:
    type: object
    properties:
      name:
        type: string
paths:
  /:
    get:
      responses:
        200:
          description: OK
```

## Steps to reproduce

```
swagger generate model -f awkward_names.spec -t target
```

## Environment

swagger version: dev 
go version: 1.9.1  
OS: Archlinux

**Comment by fredbi** [comment]
Got the same awkward generation.
Culprit is github.com/go-openapi/swag/util.go:ToFileName(...) function.
It is design to transform a CamelName into snake_case_name.
It is not smart enough to get consecutive capitals such as ELB.Http or MsgOAI: rule is simple: insert a hyphen at each capital letter (or any other special char such as _, -, . ...)

**Comment by fredbi** [comment]
Created a pull request to go-openapi/swag to fix this.

**Comment by e-zhang** [comment]
I know this issue is already closed and merged in but I had a question about the behavior I'm seeing after picking up this change. 

If I run `swagger generate --name ABC`, I used to get 
```
./restapi/configure_a_b_c.go
./cmd/a-b-c-server/main.go
```
I now get
```
./restapi/configure_abc.go
./cmd/a-b-c-server/main.go
```

It seems a little inconsistent for the filename and the command name to differ in hyphen/underscore. Was this an intended consequence? 

Sorry if this isn't the right place for this comment.

**Comment by casualjim** [comment]
i assume a similar fix needs to be applied to the ToCommandName function
