### ISSUE TITLE
swagger specification validate failed at:  types don't match expect map key string or int got: bool

### ISSUE THREAD

**Issue by rzhang2403** [go-swagger/go-swagger#1209]
When try to validate a swagger 2.0 spec in yaml with "n" as the property name like:

definitions:
  MyModel:
    properties:
      n:
        type: number
        format: double
......

I got the error message, 
2017/10/13 14:05:57 types don't match expect map key string or int got: bool

After use the quote on the property name as 'n', it works.   I don't understand why the swagger generator behaves like this.  Also, I suggest to add the following features:

1. When the validation error occurs, it's useful to print out the line number of the error in the spec file.  For a very large file (over 30K line), it's pain to debug.
2. Can the generator accept the swagger 2.0 JSON format?   The internal does convert the yaml to JSON during the parse.

Thanks.

**Comment by casualjim** [comment]
this is a yaml thing.
You want to single quote your key name: 'n'

**Comment by casualjim** [comment]
Yes the generator works with yaml and json so you can use either.
I agree on line number and column position however default go tooling doesn't provide the right means to do so

**Comment by rzhang2403** [comment]
Can you tell me why the n is a reserved keyword in the Swagger spec?  When I use the JSON file, it has to have the 'n' as well.   Thanks.

**Comment by gregmarr** [comment]
As for the reason, YAML treats these strings as boolean:

**Comment by rzhang2403** [comment]
thanks.

**Comment by casualjim** [comment]
http://yaml.org/type/bool.html
