### ISSUE TITLE
Security definition order is not consistent between code generations

### ISSUE THREAD

**Issue by johnnyg** [go-swagger/go-swagger#1214]
## Problem statement

When we have multiple security definitions, the order they are generated in isn't consistent between runs.

## Swagger specification

`swagger: "2.0"
info:
  version: 0.0.0.0
  title: Test swagger spec for 1214
securityDefinitions:
  header:
    type: apiKey
    name: secret
    in: header
  query:
    type: apiKey
    name: secret
    in: query
security: ["header": [], "query": []]
paths:
  /foo:
    get:
      summary: "Add a new pet to the store"
      description: ""
      responses:
        200:
          description: "Success"`

## Steps to reproduce

Run swagger gen with above spec multiple times.

## Environment
swagger version: 0.12.0  
go version: 1.9.1  
OS: Linux

**Comment by fredbi** [comment]
SecurityDefinitions are naturally stored as a map in structs.go
but it is actually used as a slice in regular ranges by templates, so it may be possible to convert all these maps into slices in the generation structures and sort them.

At the moment, that makes quite some extra work. Is there any genuine added value beyond stable generated output?

**Comment by gregmarr** [comment]
Don't underestimate the value of stable generated output. It makes debugging generation errors much easier. We currently sort model and operation arrays after extracting then from the maps and before iterating over them.

**Comment by fredbi** [comment]
Hi Greg. I don't underestimate. We have had this discussion and you know I am versionning everything...
This is precisely why I am investigating this one.
I already identified a quick improvement to sort AllOf schemas, that's a really easy one.
This one is a bit trickier but quite doable.
Problem is regression testing with this as I only have few working examples at my place to really test it's working. Testing is making 90% of my contribution time ratio now that I got into templates.

**Comment by gregmarr** [comment]
Okay. Just wanted to say that I think stable generated output is enough genuine added value and that you don't have to look for more.

**Comment by gregmarr** [comment]
Now that I read the description again, I'm even more convinced as this is about observable order in the output and not just the order in which files are generated.

**Comment by fredbi** [comment]
Yes. It is just one of the few map structures left in GenXXX structs. That is what is making it random.
