### ISSUE TITLE
oauth2 accessCode flow does not redirect to the authorization server

### ISSUE THREAD

**Issue by huikang** [go-swagger/go-swagger#1217]
## Problem statement

In my understanding, if the _accessCode_ flow is used for oauth2 securitydefinition, the generated server could redirect the authentication to the oauth2 server, e.g., https://accounts.google.com/o/oauth2/v2/auth. However, my generated code does not perform the redirection. Could anyone help on this? Thanks.

## Steps to reproduce
```yams
---
swagger: '2.0'
info:
  title: oauth2 debug
  version: 0.3.0
produces:
- application/json
schemes:
  - http
basePath: /api
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth'
    tokenUrl: 'hhttps://www.googleapis.com/oauth2/v4/token'
    scopes:
      admin: Admin scope
      user: User scope
security:
  - OauthSecurity:
    - user
paths:
  /customers:
  ....
```

Run the server
```shell
go run cmd/oauth-sample-server/main.go   --port 11309
```

Open the browser and access: 127.0.0.1:11309. The generated server does not redirect the browser to the google login page.

**Comment by casualjim** [comment]
Redirection flow is for UI... The spec has them so your UI can do the redirection.
Swagger 2.0 only defines those properties as hints for a UI to work, this doesn't have to be server side. At the same time the redirection flow is not supported in an API but you can use an OAuth 2.0 middleware from any library to get you that functionality

**Comment by huikang** [comment]
@casualjim Thanks for your response. Now I understand the structure of the go-swagger generated code. And I realized that I should implement checking the oauth access token in this function
```go
	api.OauthSecurityAuth = func(token string, scopes []string) (*models.Principal, error) {
		return nil, errors.NotImplemented("oauth2 bearer auth (OauthSecurity) has not yet been implemented")
	}
```

I have another follow up question, which is also applicable to apikey or basic authentication schemes. How can the server remember the authenticated request context? For example, if I uses a browser to access the api server, the request does not need to be checked each time after being authenticated once.
Do you know which go libraries can handle this? Thanks.
