### ISSUE TITLE
Model file cannot compile when a string field has both date format and maxLength

### ISSUE THREAD

**Issue by tfeng** [go-swagger/go-swagger#1220]
## Problem statement

When the swagger file has a string field with both date format and maxLength, the generated model file does not compile.

In this example (adapted from [petstore](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-simple.json), the field "birth" is string, has date format, and a max length of 10.

We should call m.Birth.String() rather than string(m.Birth) in new_pet.go.

## Swagger specification

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore"
  },
  "host": "petstore.swagger.io",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/pets": {
      "post": {
        "operationId": "addPet",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "pet",
            "in": "body",
            "description": "Pet to add to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewPet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NewPet": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "birth": {
          "type": "string",
          "format": "date",
          "maxLength": 10
        }
      }
    }
  }
}
```

## Steps to reproduce

```
$ swagger generate client --spec apis/test.json
$ go build client/swagger_petstore_client.go 
# github.com/neighborly/experiments/pershing-demo/models
models/new_pet.go:60:54: cannot convert m.Birth (type strfmt.Date) to type string
```

## Environment
swagger version: dev
go version: 1.9.1
OS: OSX

**Comment by kreamyx** [comment]
@tfeng Does it work as expected if maxLength is not specified?

**Comment by tfeng** [comment]
@kreamyx Yes, it works as expected without maxLength. The offending line is to test maxLength, so without it, that line doesn't exist in the generated file.

**Comment by kreamyx** [comment]
OK thanks for the info. I will look into it

**Comment by casualjim** [comment]
why would max length matter for an ISO-8601 date?

**Comment by tfeng** [comment]
Perhaps it wouldn't, but this occurs in a large swagger file that we got from an external partner. Instead of modifying their swagger file in many places, I'd rather have a codegen tool that works out of the box.

In general, I think we should either raise an error and don't except the swagger file if date+maxLength is not valid, or generate code that compiles.
