### ISSUE TITLE
client generator expects x-class in a different place than is documented

### ISSUE THREAD

**Issue by ahilananantha** [go-swagger/go-swagger#1221]
## Problem statement

In discriminated.md the spec generator is said to place x-class inside the allOf while the client generator only looks at x-class specified outside the allOf. Since this is an extension, I don't know what is correct but I'm guessing what you documented is what you wanted to have working. You can see in discriminatorInfo in discriminator.go:

```go
func discriminatorInfo(doc *analysis.Spec) *discInfo {
// ...
	for _, sch := range doc.SchemasWithAllOf() {
		for _, ao := range sch.Schema.AllOf {
			if ao.Ref.String() != "" {
				if bt, ok := baseTypes[ao.Ref.String()]; ok {
					name, _ := sch.Schema.Extensions.GetString("x-class")
```

that sch.Schema refers to the schema that contains the allOf for "x-class", when the document says it should be in the allOf's inner schema that doesn't contain a ref. 

## Swagger specification

From discriminated.md:

```yaml
  modelX:
    allOf:
      - $ref: "#/definitions/TeslaCar"
      - title: The ModelX version of the tesla car
        properties:
          doors:
            description: "The number of doors on this Model X"
            type: integer
            format: int32
            x-go-name: Doors
        x-class: "com.tesla.models.ModelX"
        x-go-name: ModelX
```

however the client generator will ignore x-class unless it's done like so:

```yaml
  modelX:
    x-class: "com.tesla.models.ModelX"
    allOf:
      - $ref: "#/definitions/TeslaCar"
      - title: The ModelX version of the tesla car
        properties:
          doors:
            description: "The number of doors on this Model X"
            type: integer
            format: int32
            x-go-name: Doors
        x-go-name: ModelX
```

## Steps to reproduce

Run "swagger generate client" on the definitions in discriminated.md and notice that the Tesla.Model() method returns "modelX" and that unmarshalTesla() looks for "modelX" in the switch statement instead of the expected "com.tesla.models.ModelX". Then try moving the "x-class" like shown above and trying again.

## Environment
swagger version: dev (latest HEAD)
go version: 1.9.0  darwin/amd64
OS:   darwin/amd64

**Comment by ahilananantha** [comment]
I just looked at the behavior of the structure parser and it looks consistent with the client generator. It puts the x-class extension on the same schema object that contains an allOf:

```go
bschema.AddExtension("x-class", mv)
// ...
bschema.AllOf = append(bschema.AllOf, newSch)
```

and the tests are consistent with that. Maybe the documentation just needs to be corrected to match the code?

**Comment by casualjim** [comment]
updated discriminated.md
