### ISSUE TITLE
Examples are not validated

### ISSUE THREAD

**Issue by Zehelein** [go-swagger/go-swagger#1231]
## Problem statement

When using invalid example values for a definition they are not validated with "swagger_windows_amd64.exe validate c:\temp\example.json"

## Swagger specification

```swagger
swagger: '2.0'
info:
  title: test example
  version: "1.0.0"
produces:
  - application/json
paths:
  /v1/customer/{customer_id}:
    get:
      parameters:
        - $ref: "#/parameters/customerIdParam"
      responses:
        200:
          description: Customer
          schema:
            $ref: '#/definitions/customer'            
parameters:
  customerIdParam:
    name: customer_id
    description: The ID of the customer
    in: path
    required: true
    type: string
    format: uuid
definitions:
  customer:
    type: object
    required:
    - id
    properties:
      id:
        type: string
        format: uuid
        description: The unique ID of the customer
        example: 123
      email:
        type: string
        format: email
        description: The email address of the customer
        example: 123
      create_date:
        type: string
        format: date-time
        description: The date and time when the customer was created
        example: 123
```

## Steps to reproduce

Save the swagger definition and run the validate command:
"swagger_windows_amd64.exe validate c:\temp\example.json"

## Environment

This release: https://github.com/go-swagger/go-swagger/releases/tag/0.12.0
OS:   Windows 10

**Comment by fredbi** [comment]
Hello. I tested your case.
Actually, you are not using the proper Swagger 2.0 syntax for examples in responses.
Responses are not examplified the same way as params.

If you specify your response with:
```
responses:
        200:
          description: Customer
          schema:
            $ref: '#/definitions/customer'
         examples:
           application/json:
             id: 123
             email: 123
             create_date: 123
```

You get an invalid spec as expected.

I agree that finding "example" instead of "examples" should trigger a warning, as "blank" validation was probably not what was intended. Will do that in related PR go-openapi/validate#42.

**Comment by Zehelein** [comment]
Hi,

thank you for your response. But what you wrote is only one type of how to provide examples.

There are more ways to provide examples - please check 
https://swagger.io/docs/specification/2-0/adding-examples/

I was using the "Property Examples" while you show the "Response Examples".

**Comment by fredbi** [comment]
Yes. I am in the validation code trying to figure it out and also this page of the specification.
It is not quite explicit that schema examples apply in the context of responses, but we may suppose it is so (I would, like you).
The validation code for responses explicitly search for "examples"... 
I am digging in further and let you know

**Comment by Zehelein** [comment]
Thank you for your efforts!

For me it would be really good to not (only) have it on response level because the input models are just as important (for me) to have them in a consistent state.

**Comment by fredbi** [comment]
It works with params but validation messages are misleading. So something has to be changed anyhow.

**Comment by fredbi** [comment]
I get your use case. I just got the same...

**Comment by fredbi** [comment]
we need to update vendor before closingt this

**Comment by Zehelein** [comment]
Rather late response but I tested it again and now they are validated nicely - thanks for the fix!
