### ISSUE TITLE
Body not written to request on post when schema is discriminated/anyOf/oneOf

### ISSUE THREAD

**Issue by ahilananantha** [go-swagger/go-swagger#1233]
## Problem statement

The fix for #1200 has the side effect of omitting writing the body when the schema has discriminator specified for it. I also tried working around it by specifying "oneOf" with each of the derived schemas but it had the same effect. In parameter.gotmpl there is now:

```
   {{if .IsBodyParam}}
   {{ if and .Schema.IsNullable (not .HasDiscriminator) }}if {{ .ValueExpression }} != nil {
     if err := r.SetBodyParam({{ .ValueExpression }}); err != nil {
       return err
     }
   }{{ end }}
```

Before #1200, the body was always written. Note that marshaling of derived schema specific fields also doesn't work (see #1232).

## Swagger specification

``` yaml
      parameters:
...
        - name: BaseClassRequest
          required: true
          in: body
          schema:
            $ref: '#/definitions/BaseClassRequest'
```

## Environment
swagger version: dev
go version: 1.9.0
OS: darwin/amd64

**Comment by casualjim** [comment]
in openapi 2.0 oneOf and anyOf are not supported.
but we'll look at the rest of the discriminated support

**Comment by ahilananantha** [comment]
Thanks, also I want to clarify that the marshaling issue (#1232) isn't there if --skip-flatten is passed. So it's only this new issue I think that prevents sending out a schema with discriminator in it.

**Comment by fredbi** [comment]
PR #1444 should solve the param binding problem.
Regarding the unmarshalling, see also #1336

**Comment by ahilananantha** [comment]
I haven't had to do any workarounds for quite a while now with recent versions.
