### ISSUE TITLE
Unable to define parameters from URL path

### ISSUE THREAD

**Issue by saiKokkonda** [go-swagger/go-swagger#1236]
Hi , i am new to swagger and  was trying to generate a swagger JSON file by using annotations in GO LANG. I annotated my code using the help of https://goswagger.io/ , but was unable to annotate the parameters that are required in my URL path and always get the following error when i put JSON file in swaggerUI. 

Error: Declared path parameter "id" needs to be defined as a path parameter at either the path or operation level.

Annotated something like this: 
// GetEmployeeData handles a GET to /example/{id}
		//
		// swagger:route GET /example/{id} getEmployee
		//
		// Parameters:	 id int  in:path	true	"id"
		//
		// Returns data of the employee.
		//
		//	Produces:
		//	- application/json
		//
		//     Responses:
		//       200: getEmployee
		func GetEmployee(w http.ResponseWriter, req *http.Request) {
	json.NewEncoder(w).Encode(people)
}

I have tried different ways and also tried creating a struct and annotate it with swagger:parameters and it didn't work.

//swagger:parameters
type id struct{
// in:path
id int 
}

Ran swagger generate spec -o ./rds.yml command to generate the JSON file. 

It would be great if you can assist me.

## Environment
swagger version: 2.0
go version: 1.9
OS:  windows

**Comment by casualjim** [comment]
you need to export the fields in your parameter struct

and `// swagger:parameters getEmployee` needs the operation name(s) it applies to
