### ISSUE TITLE
How to make parameters to lower case? 

### ISSUE THREAD

**Issue by saiKokkonda** [go-swagger/go-swagger#1242]
Hi, we have an existing REST API with many clients using it and i was trying generate swagger.json file using annotations and was successfully able to create and host it. But the problem is with **query parameters.** 

The existing URL looks something like this: **https://swagger/employee?id=value&project=value**

When i use annotations, the parameters structs fields must be exported, so that the swagger:parameters annotation will recognize the params. This is fine in case where there are no query params in the URL.

But in query params case, after generating swagger.json file with annotations  the URL will look something like this: **https://swagger/employee?Id=value&Project=value** , where the first letter of the param key is always upper case and failing to fetch the data. This is because of exporting the fields in parameters struct.

Is there a way to generate these in lower case other than changing the API code and making the clients not to use new URLs ?

## Environment
swagger version: 2.0
go version: 1.8 
OS:  windows

**Comment by casualjim** [comment]
you can reuse the json struct tag to provide a different name for those properties

**Comment by saiKokkonda** [comment]
Great ! Thanks for the reply :)
