### ISSUE TITLE
Keep object's parameters order as specified in swagger spec definition

### ISSUE THREAD

**Issue by aleksandr-vin** [go-swagger/go-swagger#125]
Consider a `swagger` option to produce sorted-order fields in models' structs or a spec-persistent order.

As for me: I place parameters in spec in a specific order to describe the object in domains. But `swagger generate` sorts them alphabetically, and such order is taken for ORM system to generate tables in DB... which are rather hard to read.

**Comment by casualjim** [comment]
I agree that this is a good thing to have, at least a way to order that's not alphabetical.
But for now the implementation uses a map and there is no weight option defined yet, so alphabetical is the only way to get a stable sort (and stable diffs across generations)

**Comment by AlekSi** [comment]
#1939 was merged. Can this one be closed now?
When you plan to make a new release with this feature?
