### ISSUE TITLE
Changing SwaggerUI

### ISSUE THREAD

**Issue by ribice** [go-swagger/go-swagger#1250]
Hello,

With help of @casualjim (on Slack) I managed to set up Swagger in my Go project(s). Although I do prefer the way of setting it up in SpringBoot (which is what I was used to before moving to Go) I can see why it needs to be this way in Go.

The UI that I was used to (and I prefer due to cleanliness) is [THIS](https://api.subledger.com/) one.

The UI that I get when serving the swagger.json file is the [Petstore](http://petstore.swagger.io/#/). 

Is there any way to get the 'other' UI? I don't know how to refer to it, as both are SwaggerUI to me.

**Comment by casualjim** [comment]
you can use: `swagger serve --flavor swagger --doc-url https://api.subledger.com/`

What you're seeing there is an older version of the swagger ui in use on the petstore url

**Comment by ribice** [comment]
I get this:

![image](https://user-images.githubusercontent.com/5403700/32463225-74337c3e-c33c-11e7-9f50-a7eb5649f836.png)

Those are not my apis. I hope I was clear enough, I want to have the same UI as on api.subledger.com (and not like on petstore).

**Comment by ribice** [comment]
The one I wanted is Swagger-UI v2, and the one included with go-swagger is Swagger-UI v3.
