### ISSUE TITLE
Server generation: open 'xxx.json/yyy.json' no such file or directory [cascading $ref]

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1259]
## Problem statement
Server generation fails when referring to cascading $ref in different schema files.
Reference base path is wrongly formed.
```
>swagger generate server -f ../../models/test2-swagger.yaml 
The swagger spec at "../../models/test2-swagger.yaml" is invalid against swagger specification 2.0. see errors :
- open ./test2-schema.json/test2-bis-schema.json: no such file or directory
```

## Swagger specification
2.0
## Steps to reproduce
Swagger YAML files: ($ref to JSON file 1)
[test2-swagger.yaml.txt](https://github.com/go-swagger/go-swagger/files/1481551/test2-swagger.yaml.txt)

JSON schema file #1: ($ref to JSON file 2)
[test2-schema.json.txt](https://github.com/go-swagger/go-swagger/files/1481556/test2-schema.json.txt)

JSON schema file #2 
[test2-bis-schema.json.txt](https://github.com/go-swagger/go-swagger/files/1481557/test2-bis-schema.json.txt)

## Environment
swagger version: build from source cloned from origin/master
```
>git describe
0.12.0-49-g783e5bb
>
```
go version: 1.9
OS:   linux ubuntu 14.04

**Comment by fredbi** [comment]
Reference path resolution is altered by github.com/go-openapi/spec/refmodifier.go, in:
```
func modifyRefs(target *Schema, basePath string) {
        if target.Ref.String() != "" {
                if target.Ref.RemoteURI() == basePath {
                        return
                }
                newURL := fmt.Sprintf("%s%s", basePath, target.Ref.String())
                target.Ref, _ = NewRef(newURL)
        }
...
```

It seems that the basePath is not kept up to date when recursing through a tree of $ref.

**Comment by casualjim** [comment]
You know the ref in a is invalid in syntax.

it has:

```
$ref: ./test2-schema.json/#definitions/a
```

But I suspect it should be:

```
$ref: ./test2-schema.json#/definitions/a
```

**Comment by fredbi** [comment]
You are right. Error messages are so terse... I fix and run again all my test cases. 
I correct: this issue should revert to a (minor) lack of spec validation information. I'll tell you in a moment

**Comment by fredbi** [comment]
Arg. I am testing with the PR ongoing for go-openapi/spec referring to #1260 ... 
With this code, the initial error message disappears, but still the generated model does not compile...
I fixed the definition with the '#', with no significant change in this context. I'll try with the original spec from master.

**Comment by fredbi** [comment]
Ok rolled back to master spec pkg. I checked everywhere for similar faulty syntax (i.e; /# instead of #/). Behaviour reverts to what was originally posted.

**Comment by fredbi** [comment]
Updated test case to remove syntax problem.
I believe it's innocuous anyhow in this case, since paths are cleaned from trailing slash and relative slash rebased with a slash, I mean 'x/#definitions' <=> 'x#definitions' <=> 'x#/definitions'.

But I am not  going to debate such schema compliance issues here: I admit it's a bit far fetched and error prone. So now the testcase focuses on the proper issue, that is cascading $ref.
