### ISSUE TITLE
homebrew installation silently fails on generate

### ISSUE THREAD

**Issue by vanrysss** [go-swagger/go-swagger#1261]
<img width="852" alt="screen shot 2017-11-10 at 8 29 45 pm" src="https://user-images.githubusercontent.com/4421631/32686218-075eb7fa-c656-11e7-9ce2-d162c38843db.png">

<img width="1021" alt="screen shot 2017-11-10 at 8 33 09 pm" src="https://user-images.githubusercontent.com/4421631/32686262-673e059a-c656-11e7-8452-fe089130ecda.png">

The homebrew installed version of this tool silently does nothing

**Comment by fredbi** [comment]
Closed because of stalled status. This issue refers to an old release and should not apply any longer.
Feel free to re-open this if you get similar installation issues with brew.
