### ISSUE TITLE
generate client errors out because of a nullable field in a definition

### ISSUE THREAD

**Issue by dlespiau** [go-swagger/go-swagger#1265]
## Problem statement

go-swagger errors out on a nullable fied in a definition:

```
   "definitions": {
        "AddLabel": {
            "description": "Adds a label to a manifest",
            "properties": {
                "media_type": {
                    "description": "The media type for this label",
                    "enum": [
                        "text/plain",
                        "application/json",
                        null
                    ],
                    "type": [
                        "string",
                        "null"
                    ]
                }
```

The (not obvious at all) error is:

```
template: schemavalidator:370:65: executing "schemavalidator" at <.>: wrong type for value; expected 
```

I'm not well versed into swagger, a quick glance at the 2.0 spec tells me it may not be a valid swagger document, but I gathered I may as well file an issue just in case.

## Swagger specification

Not sure, `https://quay.io/api/v1/discovery`.

## Steps to reproduce

1. Download swagger definition at `https://quay.io/api/v1/discovery`
2. Try go generate client library with `swagger generate client -f api.json -A client -c quay -a quay`
3. This error out with:
```
2017/11/13 13:49:22 rendering 1 templates for model AddLabel
2017/11/13 13:49:22 name field AddLabel
2017/11/13 13:49:22 package field models
2017/11/13 13:49:22 creating "add_label.go" in "models" as definition
template: schemavalidator:370:65: executing "schemavalidator" at <.>: wrong type for value; expected string; got interface {}
```

## Environment
swagger version: `dev` (master, b015bda48dfc648fdd95e7bc81dbb5cefc17c975) as of today
go version: 1.9.0
OS: Linux

**Comment by gregmarr** [comment]
All properties are optional unless you list them in the `required` section.  As such, you don't have to do anything with `"null"` there to make it so.

**Comment by casualjim** [comment]
in addition openapi 2.0 doesn't allow for multiple types in a type field.

**Comment by dlespiau** [comment]
Thanks for the quick answer. Based on that I think we can close this issue.
