### ISSUE TITLE
Was 0.13.0 version released?

### ISSUE THREAD

**Issue by akhobov** [go-swagger/go-swagger#1269]
Was the 0.13.0 version actually released?

I can see a new tag and the change log for it committed but the https://github.com/go-swagger/go-swagger/releases/latest still points to 0.12.0 and https://github.com/go-swagger/go-swagger/releases/download/0.13.0/swagger* returns 404.

**Comment by casualjim** [comment]
no not yet sorry

**Comment by akhobov** [comment]
Looks like 0.13.0 was actually released in the end. Closing...
