### ISSUE TITLE
Feature Request: Renaming interface method from handle to actual method name

### ISSUE THREAD

**Issue by rodriguise** [go-swagger/go-swagger#1271]
Currently the server generates creates handler definitions like this:

```
// CreateDeviceDefinitionHandlerFunc turns a function with the right signature into a create device definition handler
type CreateDeviceDefinitionHandlerFunc func(CreateDeviceDefinitionParams, *session.Context) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDeviceDefinitionHandlerFunc) Handle(params CreateDeviceDefinitionParams, principal *session.Context) middleware.Responder {
	return fn(params, principal)
}

// CreateDeviceDefinitionHandler interface for that can handle valid create device definition params
type CreateDeviceDefinitionHandler interface {
	Handle(CreateDeviceDefinitionParams, *session.Context) middleware.Responder
}

### configure_api.go

func configureApi...

api.CreateDeviceDefinitionHandler = api.CreateDeviceDefinitionHandlerFunc(func(params api.CreateDeviceDefinitionParams, ctx *session.Context) middleware.Responder {
     if err := db.Create(params.DeviceDefinition); err != nil {
       return NewError(err)
    }
   return iot.NewCreateDeviceDefinitionOK().WithPayload(params.DeviceDefinition)
})

```

This is slightly inflexible, as it forces the use of the `CreateDeviceDefinitionHandlerFunc` which can lead to heavy and unclean coding, especially with dozens of methods. I propose a minor change to support cleaning this up, by renaming the interface method to support better implementation. The name used would be the actual method name or operationId for example:

```
// CreateDeviceDefinitionHandlerFunc turns a function with the right signature into a create device definition handler
type CreateDeviceDefinitionHandlerFunc func(CreateDeviceDefinitionParams, *session.Context) middleware.Responder

// CreateDeviceDefinition executing the request and returning a response
func (fn CreateDeviceDefinitionHandlerFunc) CreateDeviceDefinition(params CreateDeviceDefinitionParams, principal *session.Context) middleware.Responder {
	return fn(params, principal)
}

// CreateDeviceDefinitionHandler interface for that can handle valid create device definition params
type CreateDeviceDefinitionHandler interface {
	CreateDeviceDefinition(CreateDeviceDefinitionParams, *session.Context) middleware.Responder
}
```

This would allow for the creation of a struct or multiple structs to implement all or some of the interfaces, simplifying:

```
api.CreateDeviceDefinitionHandler = myApiHandlerClass
```

This then frees us to implement the responders else where.

**Comment by gregmarr** [comment]
This is what I have in my setup function:

	api.DesignDeleteHandler = operations.DesignDeleteHandlerFunc(routes.DesignDelete)
	api.DesignGetHandler = operations.DesignGetHandlerFunc(routes.DesignGet)
	api.DesignPatchHandler = operations.DesignPatchHandlerFunc(routes.DesignPatch)

and then I have a separate `routes` package that has functions like this:

    func DesignDelete(params operations.DesignDeleteParams, principal interface{}) middleware.Responder {
    func DesignGet(params operations.DesignGetParams, principal interface{}) middleware.Responder {

**Comment by rodriguise** [comment]
@gregmarr awesome suggestion, much cleaner. Though I think my suggestion maybe as simple as using a custom template:

https://goswagger.io/generate/templates.html

I have to investigate and will close this if I come to a conclusion.

**Comment by rodriguise** [comment]
Closing as custom templates worked for this.
