### ISSUE TITLE
go-swagger version depends on git

### ISSUE THREAD

**Issue by reidrac** [go-swagger/go-swagger#1283]
Currently the `version` command shows the version variable that is set on compilation time by using `git describe`.

https://github.com/go-swagger/go-swagger/blob/5d14d17231acaff2e99c9f11d21d8b6b50acf3a9/Makefile.variables#L13

If go-swagger version is managed with `go dep`, for example, using the vendor directory, the directory won't be a git repo and `go-swagger` will always show `dev` as version.

**Comment by reidrac** [comment]
Thanks for your explanation, really appreciated.

I have a requirement of being able to build from software in a reliable and predictable way, so using "dep" helps because I can pin commits on go-swagger dependencies (that are currently floating; so if you build go-swagger 0.12.0 now, you won't get the same binary/features than when it was released).

I downloaded the binary version of 0.12.0 and the git commit reported doesn't match the commit tagged as 0.12.0; plus the floating dependencies, I can't use it because when we hit an issue we don't really know what's going on.

For example, building 0.12.0 recently, out spec didn't work anymore because of this:

https://github.com/go-openapi/spec/commit/5a4a1e94454f878ce1e1fefff23ea10bd5dd5110

So we really need to use "dep" to pin the version of the dependencies.

I think is reasonable to expect the version command to behave correctly when building from source, even if there's no git information available. I understand it's not a priority for the project right now, but I'd love if you considered it for future.

**Comment by casualjim** [comment]
that particular issue is fixed now

**Comment by fredbi** [comment]
Update: so now we have removed makefiles, it is clear that the `go version` command is only relevant for docker images and released binary distributions.

**Comment by fredbi** [comment]
@casualjim  I found somewhere a nice way to improve the versioning, at least for the case when you install with `go get`:
```
// +build go1.12

package main

import (
	"fmt"
	"runtime/debug"
)

//nolint:gochecknoinits
func init() {
	if info, available := debug.ReadBuildInfo(); available {
		if date == "" {
			version = info.Main.Version
			commit = fmt.Sprintf("(unknown, mod sum: %q)", info.Main.Sum)
			date = "(unknown)"
		}
	}
}
```

**Comment by ezk84** [comment]
@fredbi that looks like a promising technique for us `go get` users. Right now I'm having to manage two projects using different and incompatible releases of the swagger tool, and it would make it easier to know which version is currently in my `$GOPATH/bin`

**Comment by fredbi** [comment]
@ezk84 yeah I'll give it a shot before Christmas.
