### ISSUE TITLE
Produces application/pdf ignored

### ISSUE THREAD

**Issue by Xzya** [go-swagger/go-swagger#1284]
## Problem statement
The below swagger definition will generate the ```ProducersFor```:
```go
func (o *SomeAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "text/html":
			result["text/html"] = o.HTMLProducer

		}
	}
	return result

}
```
So the ```application/pdf``` is ignored.
Also there is no producer property:
```go
type SomeAPI struct {
...
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// HTMLProducer registers a producer for a "text/html" mime type
	HTMLProducer runtime.Producer
...
}
```
Reading the source code, this seems intended. Is there any way to add a custom producer? I want the ```application/pdf``` producer to do the same as ```runtime.ByteStreamProducer()```, but I cannot find any way to set it as there is no ApplicationPDFProducer property generated.
I expected this to work the same way as security schemes, where you get a handler which you can override for each scheme.

## Swagger specification
```yml
paths:
  /some/path:
    get:
      operationId: "getPDF"
      produces:
      - "application/pdf"
      - "text/html"
      responses:
        200:
          description: "ok"
          schema:
            type: "string"
            format: "binary"
        default:
          description: "Unexpected error"
          schema:
            type: "object"
```

## Environment
swagger version: 0.13.0 
go version: 1.9
OS:   OSX El Capitan

**Comment by fredbi** [comment]
Supported mimes are currently hardcoded [here](https://github.com/go-swagger/go-swagger/blob/25e637c5028dee7baf8cdf5d172ccb28cb8e5c3e/generator/support.go#L289) in `generator/support.go`.

Refactoring this and making it configurable could be a good PR, not too difficult.

**Comment by RubenGarcia** [comment]
Can application/zip be added as well? 

I got
http: panic serving [::1]:45488: applicationZip producer has not yet been implemented
for
a swagger containing (except):
      produces:
        - application/zip
      responses:
        '200':
          description: zip 
          schema:
            type: file

with the following code:
return a.NewXOK().WithPayload(res.Body)

**Comment by casualjim** [comment]
You can add it yourself: https://github.com/go-openapi/runtime/blob/master/json.go
And then just register it. Those consumers/producers are designed so that you can add your own because it's a near infinte list of posibilities

**Comment by fredbi** [comment]
Not so long ago, I've added a couple common mime to be supported by generated code. `application/pdf` is now in the list:
https://github.com/go-swagger/go-swagger/blob/468a61360689c96f4e1a7350feeadf8eebb44b50/generator/media.go#L38
