### ISSUE TITLE
.security in body must be of type array: "null"

### ISSUE THREAD

**Issue by rcorre** [go-swagger/go-swagger#1286]
## Problem statement

Following the [documented example](https://goswagger.io/generate/spec/meta.html), we have the following in our `meta` section:

```
//     Security:
//     - bearer:
//
//     SecurityDefinitions:
//       bearer:
//         type: apiKey
//         name: Authorization
//         in: header
```

When running the following:
```
swagger generate spec -m --base-path ./server/http -o resources/swagger.json
swagger validate resources/swagger.json
```

I get:
```
- paths./deploy/{Namespace}.post.security in body must be of type array: "null"
- paths./deploy/{Namespace}.get.security in body must be of type array: "null"
... one for every path ...
```

This just started after fetching go-swagger `HEAD` today.

I've tried ` - bearer` and ` - bearer: []` to no avail.

## Environment
swagger version: dev
go version: go1.9.2 linux/amd64
OS: Linux 4.9.65-1-lts x86_64

**Comment by gregmarr** [comment]
Fixed here yesterday: https://github.com/go-openapi/spec/pull/40
