### ISSUE TITLE
Has no field or method

### ISSUE THREAD

**Issue by Somebi** [go-swagger/go-swagger#1291]
after generating server from swagger.json:
`swagger generate server`

After installing dependencies:
`go get -v -u -f ./...`

Getting this kind of errors:
`restapi/configure_myproject_api_integration_documentation.go:39:42: api.GetAPIV1MymethodHandlerFunc undefined (type *operations.MyprojectAPIIntegrationDocumentationAPI has no field or method GetAPIV1MymethodHandlerFunc)`

**Comment by Somebi** [comment]
The problem is in endpoints path names. If any api have paths that starts with /api/ it will fail, because there is contexts/scope conflict in generated go file restapi/configure_ at configureAPI method.

When endpoints are /v1 instead of /api/v1 for example, then everything is working fine.
Because there is no conflict between operations package and api argument in configureAPI method.

api vs v1 not conflicting
api vs api conflicting and throws undefined/not-existing api/spec functions etc.

Hope i have described well.

It should somehow be isolated, to avoid naming conflicts.

**Comment by fredbi** [comment]
As of v0.15, could reproduce name conflict only in the corner case when tag = "api".

See attached spec testcase.
[fixture-1291.yaml.txt](https://github.com/go-swagger/go-swagger/files/2270512/fixture-1291.yaml.txt)

All other cases mentioned in the issue report above work without conflict.

Therefore, move this one as "enhancement".

**Comment by fredbi** [comment]
See #1098
