### ISSUE TITLE
The commit number of command `swagger version` is wrong v0.12.0

### ISSUE THREAD

**Issue by YaoZengzeng** [go-swagger/go-swagger#1297]
## Problem statement
The commit number of swagger 0.12.0 should be :
"68ea41dcf206410c74d397d3bbff42aedff35e4d"

But the output of command `swagger version` is:
version: 0.12.0
commit: 8135eb6728e43b73489e80f94426e6d387809502

And "8135eb6728e43b73489e80f94426e6d387809502" is the commit number of swagger 0.11.0.

And I get the binary as follows:
`curl -o /usr/local/bin/swagger -L'#' https://github.com/go-swagger/go-swagger/releases/download/0.12.0/swagger_$(echo `uname`|tr '[:upper:]' '[:lower:]')_amd64
chmod +x /usr/local/bin/swagger`

It is really confusing.

## Environment
swagger version: 0.12.0
go version: x.x.x  
OS:   CentOS 7

**Comment by fredbi** [comment]
Performed sanity check on this with 0.14 and it is okay
