### ISSUE TITLE
Does the ByteStreamProducer close the io.ReadCloser?

### ISSUE THREAD

**Issue by dreamlover** [go-swagger/go-swagger#1311]
## Problem statement

I'm writing an API that download a file and wrote the specification as recommended as bellow.
In the generated ```OfflineGetInputReturnOK``` responder, an interface of type io.ReadCloser is   required as the type of the data payload.

But in the ```go-openapi/runtime/bytestream.go``` file, I don't see any where calling the ```io.Closer.Close()``` method. So if I passed an ```*os.File``` as the payload, will it be closed after its content was read out and sent to the client? 

## Swagger specification

```
...
  /offlines/{offline_id}/input:
    get:
      tags:
        - term
      summary: get input file associated with the specified offline id
      operationId: offline_get_input
      produces:
        - application/octet-stream
      parameters:
        - name: offline_id
          in: path
          description: offline id
          required: true
          type: integer
      responses:
        200:
          description: input file return
          schema:
            type: string
            format: binary
          headers:
            Content-Disposition:
              description: "attachment; filename=%s"
              type: string
        204:
          description: input file haven't returned from the "subsidi system"
        404:
          description: the specified offline_id doesn't exist
      security:
        - TSign: []
...
```

## Environment
swagger version: 0.12.0  
go version: 1.9.2 
OS:  MacOS

**Comment by casualjim** [comment]
fixed by go-openapi/runtime@55d76b2319213cf30fdb7c4ae3a01541f5404c16

**Comment by casualjim** [comment]
you can now create a bytestream producer or consumer with `runtime.ByteStreamProducer(runtime.ClosesStream)`

**Comment by dreamlover** [comment]
I add a comment to the diff. Should the ```writer``` be closed or the ```data```?

I open  a file as the payload to produce, so the ```data``` parameter is of type 'io.ReadCloser'.
