### ISSUE TITLE
Using go-swagger to generate other artifacts using custom templates not working from 0.12.0

### ISSUE THREAD

**Issue by elakito** [go-swagger/go-swagger#1312]
## Problem statement
Up to go-swagger version 0.11.0, we could use go-swagger's generator to generate other artifacts (not go code) into the path outside of $GOPATH/src using custom templates. The code that rejects such code generation outside of $GOPATH existed before but there was a bug that didn't trigger this check.

But according to the commit logs, this bug seems to have been fixed in August and this change went into 0.12.0. As a result, we can no longer use go-swagger to generate non-go code using custom templates into arbitrary folder.

I am wondering if we could add a parameter to method baseImport (in support.go) so that we could have a configuration option for not triggering this $GOPATH/src check in certain cases.
https://github.com/go-swagger/go-swagger/blob/master/generator/support.go#L253

I would appreciate for your comments.

regards, aki

**Comment by casualjim** [comment]
yeah I think you're right.
We have a concept of language options but this hasn't been added to it yet.
https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L90

Perhaps this check should move there?

**Comment by fredbi** [comment]
As a work around, I believe that setting skip_format = true in the generator's yaml config file should allow to bypass this check.

**Comment by elakito** [comment]
@fredbi I don't think skip_format=true would let you bypass this GOPATH check as the check is done before the result is written.

**Comment by fredbi** [comment]
I am not sure about this specific check.
I have recently modified things so that code not passing format check is written down no matter what, with a warning (intent was to allow template debug).

How about a PR with an additional skip_checks or alike to bypass the unwanted check?

**Comment by elakito** [comment]
@casualjim Yes. If we could change LanguageOpts, we could add the language specific check method there. Is this change allowed in the next 0.x.x? If not, it would be nice if we could at least modify the current check code so that it is only enabled only if GoLangOpts is used or something like that.
thanks.

**Comment by fredbi** [comment]
@elakito Check out https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L553

**Comment by casualjim** [comment]
@elakito you can make the changes in 0.x.x as long as we do it without breaking the go language support we're all good.

**Comment by elakito** [comment]
@fredbi I know where this skip_format has effect. But I don't know why it relates to this GOPATH check. It's not about the format of the generated code but about in which folder the code is generated. 

This GOPATH check happens at the generator client start up (https://github.com/go-swagger/go-swagger/blob/master/generator/client.go#L123) which is much before any writing happens where skip_format can have some effect.

We could add another property like skip_format and call it skip_gopath_check. But I find it ugly and there is some overlap with what we can do with LanguageOpts. So, I think using one of the two approaches that I suggested would be reasonable, no?

**Comment by fredbi** [comment]
OK

**Comment by casualjim** [comment]
the use case for language opts is exactly what you want to do @elakito so I my vote goes to continuing to expand that functionality.
