### ISSUE TITLE
ressource id type array leads to invalid generated code

### ISSUE THREAD

**Issue by paessler-jekeller** [go-swagger/go-swagger#1314]
## Problem statement
Using an array type as ressource id leads to invalid generated code.

func ({{ .ReceiverName }} *{{ pascalize .Name }}URL) Build() (*url.URL, error)
in
\templates\server\urlbuilder.gotmpl

expects that {{ varname .ID }} is a string, but {{ .Formatter }} does not work for arrays.

Please remove the sections that don't apply

## Swagger specification
paths:
  /resource/{resource}/{IDs}:
    get:
...

parameters:
  IDs:
    name: IDs
    in: path
    description: A singele object ID or a comma seperated list of objects IDs.
    type: array
    items:
      type: string
    collectionFormat: csv
    minItems: 1
    uniqueItems: true
    required: true
## Steps to reproduce
generate go code with an array type as ressource id
## Environment
swagger version: commit/278bee9f9204f7941f11df84fe6f09dded3bdb19
go version: 1.9
OS:  any

**Comment by fredbi** [comment]
Should be fixed with PR #1394.
To be tested again.
