### ISSUE TITLE
How to define multiple content-type for one API

### ISSUE THREAD

**Issue by shyr** [go-swagger/go-swagger#1319]
I want to know how to specify multiple `content-type` for one API. The requirement is to respond to both `x-www-form-urlencoded` and `application/json` content-type. So what I did is writing both API specifications for each content-type.
```yaml
/workspaces/{wspname}/tokens/create:
    post:
      summary: "Create a token"
      tags: ["token"]
      operationId: "TokenCreate"
      parameters:
        - name: "wspname"
          in: "path"
          type: "string"
          required: true
        - name: "body"
          in: "body"
          schema:
            $ref: "#/definitions/token"
      responses:
        201:
          description: "Token created successfully"
          schema:
            $ref: "#/definitions/token"
    post:
      summary: "Create a token"
      tags: ["token"]
      operationId: "TokenCreate"
      parameters:
        - name: "wspname"
          in: "path"
          type: "string"
          required: true
        - name: "name"
          format: "string"
          in: "formData"
          type: "string"
          minLength: 1
          maxLength: 256
        - name: "cluster"
          format: "string"
          in: "formData"
          type: "string"
          minLength: 4
          maxLength: 256
      responses:
        201:
          description: "Token created successfully"
          schema:
            $ref: "#/definitions/token"
```
One is for `application/json` request, and another is for `x-www-form-urlencoded` request.
I wonder if this is the right solution. And I found that redoc UI shows only for `x-www-form-urlencoded` API. Is there any better way for that?

## Environment
swagger version: 0.13.0
go version: 1.9.2
OS:  MacOS Darwin Kernel Version 17.2.0

**Comment by casualjim** [comment]
you can use consumes and produces to that end and only define 1 operation.

**Comment by shyr** [comment]
@casualjim Thank you for the response.
When I defined 1 operation with `consumes`, specifying both parameters for multiple `content-type` was invalid.

```yaml
/workspaces/create:
    post:
      summary: "Create a workspace"
      tags: ["workspace"]
      operationId: "WorkspaceCreate"
      consumes:
        - "application/json"
        - "application/x-www-form-urlencoded"
      parameters:
        - name: "body"
          in: "body"
          schema:
            $ref: "#/definitions/workspace"
        - name: "name"
          format: "string"
          in: "formData"
          type: "string"
      responses:
        201:
          description: "Workspace created successfully"
          schema:
            $ref: "#/definitions/workspace"
```

```bash
The swagger spec at "./swagger.yaml" is invalid against swagger specification 2.0. see errors :
- operation "WorkspaceCreate" has both body and formData parameters
```
When I defined parameters only for `json` (`in: 'body'`), I couldn't get proper value from param object(`WorkspaceCreateParams`) for 'formData' request.

**Comment by shyr** [comment]
It seems that it is the limitation of swagger 2.0. According to [this issue](https://github.com/OAI/OpenAPI-Specification/issues/146), swagger 3.0 supports to define multiple responses based on `content-type`. It's not an issue of `go-swagger`, so I close this.
