### ISSUE TITLE
models: missing optional fields must not be rejected by validators and must have a distinguishable zero value

### ISSUE THREAD

**Issue by dolmen** [go-swagger/go-swagger#132]
The model and its `validate` method generated by `swagger generate models` should properly handle optional properties (properties not mentionned as `required`).

Currently optional properties that are not filled are rejected if they do not match a valid value.

Instead, the zero value should be used to detect if the property has not been set. If the zero value of the property is a valid value for the property, the type of the property in the generated model should be a pointer in order to allow `nil`. For example, for a `string` property that has `minLength >= 1`, the empty string ("") can be used to distinguish a case where the property is not set, so a `string` type is ok. If `minLength == 0`, `*string` should be used.

Here is a (failing) test case:
```go
// Dump this in a `models/pet_test.go` file with petstore.json (from Swagger), then:
//   cd models; go generate; go test -v
package models

//go:generate swagger generate model -t .. -m models -n Pet -f ../petstore.json
//go:generate swagger generate model -t .. -m models -n Category -f ../petstore.json
//go:generate swagger generate model -t .. -m models -n Tag -f ../petstore.json

import (
	"encoding/json"
	"github.com/go-swagger/go-swagger/strfmt"
	"testing"
)

func TestValidateOptionalFields(t *testing.T) {
	// Only name and photoUrls are required
	in := []byte(`{"name":"","photoUrls":[]}`)
	var pet Pet
	if err := json.Unmarshal(in, &pet); err != nil {
		t.FailNow()
	}

	validators := strfmt.NewFormats()

	if err := pet.Validate(validators); err != nil {
		t.Log(err)
		t.FailNow()
	}
}
```

Output:
```
=== RUN   TestValidateOptionalFields
--- FAIL: TestValidateOptionalFields (0.00s)
	pet_test.go:24: validation failure list:
		status in body should be one of [available pending sold]
FAIL
exit status 1
FAIL	github.com/dolmen/go-swagger-petstore/models	0.128s
```

The `status` property is not marked as required in petstore.json `Pet`. The empty string is not a valid value for the enum, so the empty string should be accepted as *unset* value.

**Comment by dolmen** [comment]
ae029a7471324faf982064dd0c991e99205cb35b is a workaround for this issue, but not the cleaner solution I proposed (but I understand, more complex to implement).

**Comment by casualjim** [comment]
I would say it implements what you asked for. it has some logic for deciding when to turn a value into  pointer. This is represented by the IsNullable property. it actually looks at the defined validations to make this decision.
So the value of minLength etc affects it.
