### ISSUE TITLE
External References Aren't Expanded for Models

### ISSUE THREAD

**Issue by dmacthedestroyer** [go-swagger/go-swagger#1322]
## Problem statement
When a definition references an external file that in turn has local references, go-swagger doesn't seem to know to expand the local reference and either returns an error or renders unexpected output, depending on the command to run.

## Swagger specification
```
swagger: "2.0"
info:
  version: 1.0.0
  title: Simple Multiple File Example
paths:
  /pets:
    get:
      responses:
        "200":
          description: A paged array of pets
          schema:
            $ref: '#/definitions/Pets'
definitions:
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'
  Pet:
    $ref: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-expanded.yaml#/definitions/Pet'
```
## Steps to reproduce
run `swagger generate server`. You should see the following output:

> `error in model pet while planning definitions: could not generate schema for pet: object has no key "NewPet"`

interestingly enough, running `swagger generate model -n Pet` succeeds, but produces an unexpected result:

```
...
type Pet struct {
	Pet
}
...
```

The expected behavior is that it would expand the definition and build a full model.  For instance, [this swagger parser site](http://bigstickcarpet.com/swagger-parser/www/index.html) resolved the definition to look like this:

```
  Pet:
    allOf:
    - required:
      - name
      properties:
        name:
          type: string
        tag:
          type: string
    - required:
      - id
      properties:
        id:
          type: integer
          format: int64
```
which go-swagger can generate a model for.

## Environment
swagger version: dev
go version: go1.9.2
OS: darwin/amd64

**Comment by casualjim** [comment]
have you tried using `swagger expand`?

**Comment by kreamyx** [comment]
@dmacthedestroyer You are probably on 0.13.0 and not on the recent master because the server generation always succeeds in the recent master. However, your issue hinted at another problem that we have when a local definition has the same name as a remote one which was fixed in go-openapi/analysis. Once go-swagger is updated with the newest vendor, your spec should work without problems

**Comment by dmacthedestroyer** [comment]
Thanks, I'll verify on the most recent master. Any ideas on when go-swagger will be updated with the newest vendor?

**Comment by kreamyx** [comment]
@dmacthedestroyer the vendor has been updated. You should be good to go! I retested your spec and it works as expected.
