### ISSUE TITLE
Additional struct inserted when using allOf and an inline definition compared to 0.9.0

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1323]
## Problem statement

There is an additional struct inserted in a type using `allOf` with an inline definition, as compared to 0.9.0. This is causing a build break, and I would like to know if this is intentional, so I should update my code, or if it's unintentional and should be fixed.

Types with commit hash `6229122` from April 11, just after 0.9.0

    type NamedValue struct {
      ExecuteValues
      // Required: true
      Name *string `json:"Name"`
    }

Types with commit hash `6adc14b` from December 11

    type NamedValue struct {
      ExecuteValues
      NamedValueAllOf1
    }

    type NamedValueAllOf1 struct {
      // Required: true
      Name *string `json:"Name"`
    }

Here is the code which used to be valid is no longer:
    return &models.NamedValue{Name: &name}

## Swagger specification

    NamedValue:
      allOf:
      - $ref: "#/definitions/ExecuteValues"
      - required:
        - Name
        properties:
          Name:
            type: string

## Environment
swagger version: commit hash `6adc14b` from December 11
go version: 1.8
OS: macOS 10.12.6

**Comment by kreamyx** [comment]
@gregmarr yes those changes were introduced since the `swagger flatten` command so they are intentional

**Comment by gregmarr** [comment]
Thanks.
