### ISSUE TITLE
Make generated client take an `io.Reader` for parameters of type `file`

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1325]
## Problem statement

I want to use a generated client to call a route defined like this:

      - in: "formData"
        name: "body"
        required: true
        type: "file"

This results in a type with a member like this:

    /*Body*/
    Body os.File

However, the data I want to send is in memory, not in a file.  Can this be made an `io.Reader` instead?

Please remove the sections that don't apply

## Swagger specification
      - in: "formData"
        name: "body"
        required: true
        type: "file"

## Environment
swagger version: master as of Dec 11, 2017

**Comment by casualjim** [comment]
the fix is not quite an io.Reader but it is an interface and the runtime package got a `NamedReader` method which allows you to turn a reader in the appropriate interface type.
