### ISSUE TITLE
Invalid receiver error for a response of type `file`

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1327]
## Problem statement

A response of type `file` produces this type: 

    // PostDownloadStreamingOKBody post download streaming o k body
    // swagger:model postDownloadStreamingOKBody
    type PostStreamingOKBody *runtime.File

    // Validate validates this post download streaming o k body
    func (m PostStreamingOKBody) Validate(formats strfmt.Registry) error {
        return nil
    }

This is the resulting error:

    invalid receiver type *PostStreamingOKBody (PostStreamingOKBody is a pointer type)

## Swagger specification

    responses:
      streaming:
        description: Streamed file content
        schema:
          type: file
    paths:
      '/streaming':
        post:
          produces:
            - application/octet-stream
          responses:
            '200': { $ref: '#/responses/streaming' }

## Environment
swagger version: master as of Dec 11, 2017

**Comment by akhobov** [comment]
Just stumble on this too. Have to use the --skip-flatten option while generating code as a workaround

**Comment by casualjim** [comment]
so file is not allowed outside of the use in formData.

>  If type is "file", the consumes MUST be either "multipart/form-data", " application/x-www-form-urlencoded" or both and the parameter MUST be in "formData".
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

If you want to have a stream it's:

```yaml
type: string
format: binary
```
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by casualjim** [comment]
I've verifed when I use: 

```yaml
swagger: "2.0"
info:
  title: test for streaming
  version: "0.0.1"
responses:
  streaming:
    description: Streamed file content
    schema:
      type: string
      format: binary

paths:
  '/streaming':
    post:
      produces:
        - application/octet-stream
      responses:
        '200': { $ref: '#/responses/streaming' }
```

then it renders valid code

```go
type PostStreamingOK struct {
	Payload io.Writer
}
```

**Comment by gregmarr** [comment]
@casualjim 

An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject

schema | Schema Object | A definition of the response structure. It can be a primitive, an array or an object. If this field does not exist, it means no content is returned as part of the response. As an extension to the Schema Object, its root type value may also be "file". This SHOULD be accompanied by a relevant produces mime-type.

**Comment by casualjim** [comment]
o man I've read this spec maybe 500 times by now and I still missed that
