### ISSUE TITLE
Temporary files are not deleted on program termination

### ISSUE THREAD

**Issue by sebastien-rosset** [go-swagger/go-swagger#1331]
## Problem statement

The swagger utility creates temporary files and do not delete these files before program termination.

In particular, "swagger validate" calls the ExpandSchema() method from the dependent go-openapi/spec to validate swagger spec files. Every invocation of "swagger validate" may end up creating multiple temporary files in the temp folder (e.g. /tmp for Linux).

The ExpandSchema() method calls ioutil.TempFile(), which creates a temporary file, and the file is not deleted before program termination. As specified in the golang documentation, it is the caller's responsibility to delete temporary files created by ioutil.TempFile()

https://github.com/go-openapi/spec/blob/aa90e7cfc0a78736511f9eeab8f7586d98c8f53a/expander.go#L534

## Steps to reproduce
1) Invoke swagger validate xyz.json
2) After program execution, notice the /tmp directory (in Linux) contains multiple rootXXXX files.

## Environment
swagger version: x.x.x  
go version: 1.9.2
OS:  Linux

## Proposed fix
The tracking issue in go-openapi/spec is https://github.com/go-openapi/spec/issues/47.
Pull Request: https://github.com/go-openapi/spec/pull/48

The proposed fix for go-swagger is to update Gopkg.lock and use https://github.com/go-openapi/spec/pull/48/commits/

**Comment by fredbi** [comment]
@sebastien-rosset 
Do you confirm the issue may be closed now that your PR has been merged?

**Comment by sebastien-rosset** [comment]
Yes, I confirm the issue can be closed. thanks.
