### ISSUE TITLE
Custom validation logic

### ISSUE THREAD

**Issue by sluchznak** [go-swagger/go-swagger#1334]
## Problem statement

Hello! Please explain how to create custom validation logic. For example we need to validate `customer_id` in `body` exists in DB. I see validation logic in generated model, but how to add or replace own logic?

## Environment
swagger version: 0.12.0
go version: 1.9.2
OS:   macos 10.13.2

**Comment by fredbi** [comment]
Hello. 
You should know that models may be generated independantly from server, then reused when generating a new server.

You might build on that: generating a first model, customizing the validation code, then reusing this model (possibly with some others) in your servers.

Another way is to use x-go-type extension, to replace type generation with a custom type.

You might use both, preparing a customized model from an initially generated structure, then reusing type custom type in other declarations by hinting the generator with x-go-type.

Eventually, for repetitive customization, you might be willing to customize the generator's templates.

**Comment by casualjim** [comment]
and lastly there is the opportunity to get go-swagger to reuse a predefined type to satisfy the definition in the swagger spec. https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/existing-model.yml#L84-L88

That example reuses a type provided by a library with an alias and type name. The code generator will respect this.
