### ISSUE TITLE
JSON marshaling and unmarshaling broken for object containing array of polymorphic types.

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1336]
## Problem statement

The top level object in the Schema is `Graph`.  It contains an array of objects of type `Node`, which has a discriminator.

As of April 11, this function was generated in this type:

    // UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
    func (m *Graph) UnmarshalJSON(raw []byte) error {

and the type looked like this:

    type Graph struct {
	Nodes []Node `json:"Nodes"`

Now that function is not generated, and the type looks like this in graph.go:

    type Graph struct {
	Nodes GraphNodes `json:"Nodes"`

and in graph_nodes.go:

    type GraphNodes []GraphNodesItems

Inside `schemaGenContext.makeGenSchema` for `Nodes`, there is a call to `buildItems()`.

    func (sg *schemaGenContext) buildItems() error {
        presentsAsSingle := sg.Schema.Items != nil && sg.Schema.Items.Schema != nil
        if presentsAsSingle && sg.Schema.AdditionalItems != nil { // unsure if htis a valid of invalid schema
            return fmt.Errorf("single schema (%s) can't have additional items", sg.Name)
        }
        if presentsAsSingle {
            return sg.buildArray()
        }
        if sg.Schema.Items == nil {
            return nil
        }

In the older code, `sg.Schema.Items.Schema` is non-`nil`, so `buildArray()` is called, and this is where `IsBaseType` is set to `true`.  In the current code, `sg.Schema.Items` is `nil`, and so nothing happens.  Instead of having `sg.Schema.Items` referencing an array of `Node`, `sg.Schema.Ref.Ref.referencePointer.referenceTokens` references [`definitions`,`graphNodes`].

Using `--skip-flatten` does not change the behavior.

## Swagger specification

    Graph:
      type: object
      properties:
        Nodes:
          type: array
          items:
            $ref: "#/definitions/Node"
    Node:
      type: object
      discriminator: NodeType
      required:
      - NodeType
      properties:
        NodeType:
          type: string
    CodeBlockNode:
      allOf:
      - $ref: "#/definitions/Node"
      - properties:
           Code:
            type: string

## Environment
swagger version: master
go version: 1.9.2

**Comment by gregmarr** [comment]
I can confirm that `specDoc.spec.Definitions["Graph"].Properties["Nodes"].Items.Schema` is valid before the call to `analysis.Flatten()` in `generator.validateAndFlattenSpec()`, and that call is what replaces it.

**Comment by gregmarr** [comment]
I assume you already know this, but it's `analysis.nameInlinedSchemas()` that's doing it.

**Comment by gregmarr** [comment]
I commented out that call and that model generated similarly to what it was before.  

    type Graph struct {
        nodesField []Node
    }

    func (m *Graph) Nodes() []Node {
        return m.nodesField
    }
    func (m *Graph) SetNodes(val []Node) {
        m.nodesField = val
    }

**Comment by gregmarr** [comment]
However, trying to generate a client for this spec without `nameInlinedSchemas()` results in duplicated models.

```
swagger: '2.0'
info:
  title: title
  version: version
responses:
  contents:
    description: description
    schema:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              attributes:
                type: object
  folder_refs:
    description: description
    schema:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              attributes:
                type: object
paths:
  /contents:
    get:
      description: description
      responses:
        200:
          $ref: '#/responses/contents'
  /refs:
    get:
      description: description
      responses:
        200:
          $ref: '#/responses/folder_refs'
```

**Comment by gregmarr** [comment]
Here's my current attempt at fixing this, don't move arrays:

    func nameInlinedSchemas(opts *FlattenOpts) error {
        for _, key := range depthFirst {
            if sch.Schema != nil && sch.Schema.Ref.String() == "" && !sch.TopLevel { // inline schema
                if !asch.IsSimpleSchema && !asch.IsArray { // complex schemas get moved

**Comment by gregmarr** [comment]
@casualjim The tests pass, and my service works properly with the latest code plus the addition of ` && !asch.IsArray` as above.  Would you mind taking a look to see if this is a workable solution?

**Comment by gregmarr** [comment]
I think this one can be closed.  Anyone have anything outstanding here?

**Comment by fredbi** [comment]
Hello @gregmarr  I am now with a model showing similar properties and the marshalling, albeit ugly, works.
I found other issues with validation not bubbling up properly, but this story shall be told elsewhere ...
