### ISSUE TITLE
Extra sections in POST body are ignored ...

### ISSUE THREAD

**Issue by SandyWalsh** [go-swagger/go-swagger#1337]
## Problem statement
If I have a swagger spec that expects

{"foo": 123}

and provide

{"foo": 123, "blah": 345} 

it happily goes on about it's way. 

Two questions:
1. can I make it complain if extra stuff is included
2. can I access these extra sections within the go code/handler?

## Environment
swagger version: 0.12.0
go version: 1.8.3
OS:   ubuntu

**Comment by casualjim** [comment]
use `additionalProperties: false` or `additionalProperties: true` on your definition.
when it's set to true you'll have a `map[string]interface{}` added
