### ISSUE TITLE
Generated client parameter does not set request body for schema type string format binary

### ISSUE THREAD

**Issue by sidh** [go-swagger/go-swagger#1339]
## Problem statement
SetBodyParam call is missing from generated client code when request body is type string format binary.

This issue is very similar to #1309 and #1280.

## Swagger specification
swagger: '2.0'
info:
  title: Test
  version: '1'
paths:
```
  /test:
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: string
            format: binary
      responses:
        200:
          description: success
```

## Environment
swagger version: master

**Comment by fredbi** [comment]
@sidhman : should be fixed by #1508. Could you please confirm?
