### ISSUE TITLE
Improper UnmarshalJSON of polymorphic object contained in another object

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1341]
## Problem statement

Code from April

    // UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
    func (m *ExecuteValues) UnmarshalJSON(raw []byte) error {
	var data struct {
		Array []*ExecuteValues `json:"Array,omitempty"`
		Value json.RawMessage `json:"Value,omitempty"`
	}

	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	value, err := UnmarshalExecuteValue(bytes.NewBuffer(data.Value), runtime.JSONConsumer())
	if err != nil && err != io.EOF {
		return err
	}

Current code

    func (m *ExecuteValues) UnmarshalJSON(raw []byte) error {
	var data struct {
		Array []*ExecuteValues `json:"Array,omitempty"`
	}

	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	value, err := UnmarshalExecuteValue(bytes.NewBuffer(raw), runtime.JSONConsumer())
	if err != nil && err != io.EOF {
		return err
	}

Notice the difference in what is passed to `UnmarshalExecuteValue()`.  It's being passed the data for the entire `ExecuteValues` object, rather than the `ExecuteValue` sub-object.

## Swagger specification

    ExecuteValues:
      type: object
      properties:
        Value:
          $ref: "#/definitions/ExecuteValue"
        Array:
          type: array
          items:
            $ref: "#/definitions/ExecuteValues"

    ExecuteValue:
      type: object
      discriminator: ValueType
      required:
      - ValueType
      properties:
        ValueType:
          type: string

## Environment
swagger version: master 
go version: 1.9.2

**Comment by gregmarr** [comment]
May be related to #1336

**Comment by gregmarr** [comment]
Looks like the change was made here:  https://github.com/go-swagger/go-swagger/commit/eff4c7f8c7ec96ae88a7494a12356041db27fd05

**Comment by gregmarr** [comment]
This issue is essentially the same issue that was fixed in #423 .  The code in #1128 appears to exactly revert the changes done for #423.

@nickrmc83 To get #1128 to pass the tests, you had to change the test added in #423.  I need to have this restored to what was in #423, but I'm not sure what effect that will have on your test cases.  Any thoughts?

**Comment by nickrmc83** [comment]
I'll take a look as soon as I can over the weekend. It's probably a scenario I'd not tested adequately. Mea culpa

**Comment by gregmarr** [comment]
@nickrmc83 Here's the test that failed with your changes: TestGenModel_Issue423

**Comment by nickrmc83** [comment]
I've got a fix (without a unit test at present) [here](https://github.com/ThalesIgnite/go-swagger/commit/1d724056a412c3afc86693a83c75b0cf8b15cc65). Once I've had a chance to write some tests I'll raise a PR. I've had to base the fix on the 0.13.0 release point as the current HEAD has other errors when using the below OpenAPI manifest:
```
swagger: '2.0'
info:
  title: Title
  description: some description
  contact:
    name: John Doe
    url: https://www.acme.com/support
    email: support@acme.com
  version: "1.0.0"
paths:
  /:
    get:
      responses:
        200:
          description: Example path
          schema:
            type: string
        default:
          description: generic error
          schema:
            type: string
definitions:
  ExecuteValues:
    type: object
    properties:
      Value:
        $ref: "#/definitions/ExecuteValue"
  ExecuteValue:
    type: object
    discriminator: ValueType
    required:
    - ValueType
    properties:
      ValueType:
        type: string
  ExecutableValueString:
    allOf:
    - $ref: '#/definitions/ExecuteValue'
    - type: object
      properties:
        something:
          type: string
````
@gregmarr : Is there any chance you can see if the linked fork solves your issues correctly and whether I missed anything?

**Comment by gregmarr** [comment]
Do you know if there was a particular reason that you reversed the changes from #423?  Should we not just revert the changes to that particular template, and then try again to fix whatever issue it was that you were having with it?

**Comment by gregmarr** [comment]
What are the other errors with that schema on HEAD?

**Comment by nickrmc83** [comment]
@gregmarr the changes from my original PR were extensive and designed to address the support for polymorphic types that have polymorphic properties especially arrays. Reverting and re-implementing would probably result in a similar issue appearing in future.

The breakages I though were at HEAD was down to my Dep lock file being behind. With an update it's building with my latest changes.

**Comment by gregmarr** [comment]
I dug deeper into the change that was made in #423, and it was actually much smaller than I thought.  I think what you have now should cover it.  I'm not sure whether or not the larger removal of the array handling is proper.

As far as the unit test for this issue, all you should have to do is revert the change to `TestGenModel_Issue423`.
