### ISSUE TITLE
How to generate a correct struct file name from "#/definitions/IPAM"

### ISSUE THREAD

**Issue by allencloud** [go-swagger/go-swagger#1344]
## Problem statement

Hi, All, 

I ran into one situation that in my swagger.yml, I have defined an object `IPAM` in https://github.com/alibaba/pouch/blob/master/apis/swagger.yml#L1713-L1726:

```
  IPAM:
    type: "object"
    description: "represents IP Address Management"
    properties:
      Driver:
        type: "string"
      Options:
        type: "object"
        additionalProperties:
          type: "string"
      Config:
        type: "array"
        items:
          $ref: '#/definitions/IPAMConfig'
```

When generating a file, a file named `ip_a_m.go` is generated, see https://github.com/alibaba/pouch/blob/master/apis/types/ip_a_m.go.

I do not think the file name `ip_a_m.go` is what I want. 

So, could I customize the file name in some places, like setting something to generate a file named `IPAM.go`?

/cc @rudyfly @CodeJuan 

## Swagger specification
See https://github.com/alibaba/pouch/blob/master/apis/swagger.yml

## Steps to reproduce
NONE

## Environment
swagger version: `version: 0.12.0`
go version: `go version go1.9.1 darwin/amd64`
OS:   `Darwin AllenSundeMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64`

**Comment by casualjim** [comment]
I think we recently updated the way these names are generated. do you still see that same behavior on when you build from master?

**Comment by allencloud** [comment]
So I think we need to first set the customized file name in swagger.yml, right?

Currently I have not get the way to set that file name. Could you share how to add a name in swagger.yml? Thanks a lot. Then I will try master branch.

**Comment by casualjim** [comment]
we added changed the function that generates a file name to keep all uppercase letters grouped.
So the filename would still be lowercase but 1 word: ipam.go

**Comment by fredbi** [comment]
@allencloud : this story is also related in go-openapi/swag#12, go-openapi/swag#11.
Name conversion heavily relies on camel case convention.

The point in your case is to detect correct "initialisms", i.e words that do not follow the regular Camel-casing.

IP is one of them, so the function knows it has to keep it one word. AM is not, so it is broken up in words.
If you had: IPAm, you should get ip_am as expected.

To work around your problem, you may configure the list of such initialisms in https://github.com/go-openapi/swag/blob/master/util.go#L27 and add "AM" as such an "initialism".
