### ISSUE TITLE
Compilation failure from pestore example

### ISSUE THREAD

**Issue by stevef1uk** [go-swagger/go-swagger#1346]
Decided to try this project using the petstore example yaml file: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

When trying to compile the generated code I get the following errors:
go build restapi/server.go 
# petstore/models
models/create_users_with_array_input_params_body.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/create_users_with_list_input_params_body.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/find_pets_by_status_okbody.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/find_pets_by_tags_okbody.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/pet.go:85: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/pet_tags.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)
models/pets.go:35: ve.ValidateName undefined (type *"github.com/go-openapi/errors".Validation has no field or method ValidateName)

## Steps to reproduce
alias swagger='docker run --rm -it -e GOPATH=/Users/stevef1/Source_Code/go -v /Users/stevef1/Source_Code:/Users/stevef1/Source_Code -w /Users/stevef1/Source_Code/go/petstore quay.io/goswagger/swagger'

swagger generate server -f petstore.yaml --target=$GOPATH/src/petstore

Also tried using the brew install approach with same result.

## Environment
swagger version: dev: commit: 7077865cc6012ee95137f25cdf2020ee521f985d
go version: go1.7.1 darwin/amd64
OS:   MacOS Darwin Kernel Version 17.3.0 (High Sierra 10.13.2 (17C88))

**Comment by casualjim** [comment]
you need to download the dependencies it lists at the end of the generation step and regenerate.

**Comment by stevef1uk** [comment]
I had.

**Comment by fredbi** [comment]
build the main.go

**Comment by stevef1uk** [comment]
Thanks, as you can tell I am fairly new to go and it has been a year or so since I last tried writing any.

I have built it! I needed to do a few more go gets for:

https://github.com/go-openapi/strfmt
github.com/go-openapi/analysis
github.com/go-openapi/validate

Then I needed to edit: restapi/operations/user/login_user_responses.go to add an import for "github.com/go-openapi/strfmt"

**Comment by fredbi** [comment]
Congratulations!

**Comment by aliasadidev** [comment]
> Thanks, as you can tell I am fairly new to go and it has been a year or so since I last tried writing any.
> 
> I have built it! I needed to do a few more go gets for:
> 
> https://github.com/go-openapi/strfmt github.com/go-openapi/analysis github.com/go-openapi/validate
> 
> Then I needed to edit: restapi/operations/user/login_user_responses.go to add an import for "github.com/go-openapi/strfmt"

did you see the first line of the file?
`// Code generated by go-swagger; DO NOT EDIT.`
