### ISSUE TITLE
Why not validate not required field even if it has format

### ISSUE THREAD

**Issue by allencloud** [go-swagger/go-swagger#1347]
## Problem statement

Hi, All,

Today I ran into an issue that I have a definition which has a Hostname, and hostname has a format of `hostname` using `strfmt`:

```
definitions:
  ContainerConfig:
    type: "object"
    description: "Configuration for a container that is portable between hosts"
    properties:
      Hostname:
        description: "The hostname to use for the container, as a valid RFC 1123 hostname."
        type: "string"
        format: hostname
```

When when I generate `container_config.go`, I did not find any validation code for field Hostname:
```
// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerConfig Configuration for a container that is portable between hosts
// swagger:model ContainerConfig
type ContainerConfig struct {

	// The hostname to use for the container, as a valid RFC 1123 hostname.
	Hostname strfmt.Hostname `json:"Hostname,omitempty"`
}

// Validate validates this container config
func (m *ContainerConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerConfig) UnmarshalBinary(b []byte) error {
	var res ContainerConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

``` 

**So why does it not validate Hostname if this is a not required field?**

And I tested that if I add Hostname as required, validation code will generated:
```
// Validate validates this container config
func (m *ContainerConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHostname(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerConfig) validateHostname(formats strfmt.Registry) error {

	if err := validate.Required("Hostname", "body", m.Hostname); err != nil {
		return err
	}

	if err := validate.FormatOf("Hostname", "body", "hostname", m.Hostname.String(), formats); err != nil {
		return err
	}

	return nil
}
```

And if I add a pattern for this not required field, validation code will be generated. Is adding pattern the only way to validate format of a not required field?

/cc @CodeJuan

## Environment
swagger version: 
```
 $ swagger version
dev
```
go version: `go version go1.9.1 darwin/amd64`  
OS:

**Comment by fredbi** [comment]
Hello.
I Believe your isssue lays here: https://github.com/go-swagger/go-swagger/blob/7077865cc6012ee95137f25cdf2020ee521f985d/generator/templates/schemavalidator.gotmpl#L289

I just couldn't figure out why the .HasValidation property remains false in your case.

Would you care some more digging based on this information? 
> (you may alter the template - this one may not be overriden: is has to be in ./generator/template then rebuilt with updated binddata.go).

In order to understand the data structure passed to the templater you may run `swagger generate ... --dump-data`.

**Comment by gregmarr** [comment]
It's actually slightly lower down, but same basic idea, with one additional condition that should be satisfied here without a problem.

https://github.com/go-swagger/go-swagger/blob/master/generator/templates/schemavalidator.gotmpl#L330

**Comment by fredbi** [comment]
Intuitively, .HasValidation should be set to true when a format is defined.
However when I look at the setting of this value in model.go, there not much left of my intuition :)

**Comment by gregmarr** [comment]
Oooh, nice tip.

https://github.com/go-swagger/go-swagger/blob/master/generator/model.go#L538

I think here we should add a check for `model.Format` being a value that we know how to validate.

**Comment by fredbi** [comment]
That should be already prepared by the schema.
What I can see here is just some trickery to lift anonymous types. I would need some time to dig it, but right now I just can't.

**Comment by fredbi** [comment]
Yes I think you're right: `|| model.Format != nil`should do the job.
I must admit I am an absolute beginner in that part of the code. How do we check that there is no messing around?

**Comment by gregmarr** [comment]
I'm just as much of a beginner here.  The reason I said "being a value that we know how to validate" is that I have no idea how it will handle a format that it doesn't know how to validate.  Having said that, I realize now that it should be moot, because it will already return true if `isRequired` is true.

**Comment by fredbi** [comment]
@gregmarr I tested our findings and... it's much more complicated than it seems.
These templates are devilish:imp:
