### ISSUE TITLE
The generate server command sorts the Operations but not the Models.

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#1349]
## Problem statement

After the loop creates the array of operations, the array is sorted.  The same is not done for models.  When there are multiple models that fail to generate properly, this results in changes in the reported failures from run to run.

    func (a *appGenerator) makeCodegenApp() (GenApp, error) {

        var genMods []GenDefinitions
        for mn, m := range a.Models {
            genMods = append(genMods, *mod)
        }

        var genOps GenOperations
        for on, opp := range a.Operations {
            genOps = append(genOps, op)
        }
        sort.Sort(genOps)

## Environment
swagger version: master HEAD

**Comment by fredbi** [comment]
@gregmarr  this one should be fixed by now, right?

**Comment by gregmarr** [comment]
Yes, it was fixed by the commit referenced just above.
