### ISSUE TITLE
Newbie needs help with wiring server-side handlers

### ISSUE THREAD

**Issue by stevef1uk** [go-swagger/go-swagger#1351]
Hi,

I am new to using this project but have managed to generate running server side code from a simple swagger specification I created

Where I need some help is how to implement the HTTP handlers. I have googled & read the documentation I can find, but I am afraid it  isn't clear enough for me to understand it.

I was following this out of date blog (http://tdoc.info/en/blog/2016/12/07/go_swagger.html) and adapted it to my generation, but in the configure_simple.go when I remove the:
  return middleware.NotImplemented("operation .GetAccounts has not yet been implemented")
with
  return operations.Search(params operations.GetAccountsParams)

I get a compilation error that don't understand: 'syntax error: unexpected operations, expecting comma or )'

I also read https://goswagger.io/tutorial/custom-server.html but that doesn't right to me either

The handler code I wrote is as follows. This is just scratch code and deliberately made verbose as I had to fight through loads of compilation errors with this to see if I could get something working but I am missing how the handlers are integrated into the middleware:

package operations

import (
    middleware "github.com/go-openapi/runtime/middleware"
    "cassandragenrest/models"
)

func Search(params GetAccountsParams) middleware.Responder {
    payload1 := new(models.GetAccountsOKBodyItems)

    num := int64(1)
    payload1.ID = &num
    name := "me"
    payload1.Name = &name

    var ret  models.GetAccountsOKBody
    ret[0] = payload1

    return NewGetAccountsOK().WithPayload(ret)
  }

**Comment by gregmarr** [comment]
>when I remove the:

    return middleware.NotImplemented("operation .GetAccounts has not yet been implemented")

>with

    return operations.Search(params operations.GetAccountsParams)

>I get a compilation error that don't understand: 'syntax error: unexpected operations, expecting comma or )'

That's because you left the type from the function declaration in the function call, you just want this:

    return operations.Search(params)

**Comment by stevef1uk** [comment]
Ah, the joy of cut & paste and learning something new. A real doh! moment.

Now I am into runtime errors in my code so progress!

**Comment by stevef1uk** [comment]
Thanks for such a fast response. I was going to stop for the night but now I have fixed that pesky run-time error and I'm on a roll.
