### ISSUE TITLE
Why is vendor folder still version controlled?

### ISSUE THREAD

**Issue by diego-fu-hs** [go-swagger/go-swagger#1352]
## Problem statement
This project is using https://github.com/golang/dep so we could theoretically remove vendor folder and use `dep ensure` to construct the vendor folder 

Is there anything I am missing?

**Comment by fredbi** [comment]
Because the repo is used to build binaries for releases (e.g. docker, other binaries)

**Comment by diego-fu-hs** [comment]
Can you point me to the part for building the binaries?

Is it possible to add `dep ensure` as part of the building process?

**Comment by fredbi** [comment]
Makefile for docker. ./hack contains related scripts.
I don't know for the linux packages etc...

**Comment by casualjim** [comment]
why would vendor not be version controlled, imo generated code and vendored code is part of the project there is no benefit besides some disk space that's not there.

the goal is that people can do `go get -u github.com/go-swagger/go-swagger/cmd/swagger`
and it should build with the version that we tested with not with what happens to be on their GOPATH

**Comment by diego-fu-hs** [comment]
There's both vendor and godep to version control the external dependencies, which is a bit redundant imo. Both php and node.js recommend not version control the external dependencies.

I know the topic is controversial, but I just want to put an idea out there since I had to update both Gopkg.lock and the vendor folders to update a dependency

**Comment by casualjim** [comment]
if you can tell me how people can do `go get -u github.com/go-swagger/go-swagger/cmd/swagger` 
and at the same time use a set of libraries that are at the same version as we tested with I"m willing to entertain the discussion. Until then we should leave the subject for what it is.

**Comment by casualjim** [comment]
I know this sounds dismissive but it's not a controversial topic. 
We have tons of actual problems and higher value improvements that can be made instead.

**Comment by diego-fu-hs** [comment]
Fair enough. Thanks @casualjim
