### ISSUE TITLE
`--skip-validator` not work for `swagger generate model`

### ISSUE THREAD

**Issue by archerzz** [go-swagger/go-swagger#1354]
## Problem statement

The help guide given by `swagger generate model -h` says that:
```
--skip-validator   when present will not generate a model validator
```

But actually there is no difference with or without `--skip-validator`

## Swagger specification
Try the example swagger yml: https://github.com/go-swagger/go-swagger/blob/master/examples/task-tracker/swagger.yml

## Steps to reproduce

- run `swagger generate model -f swagger.yml`
- run `swagger generate model -f swagger.yml --skip-validator`
- compare the output go files

## Environment
swagger version: 2.0.0  
go version: 1.9.2  
OS:   macOS
go-swagger: 0.13.0

**Comment by fredbi** [comment]
This flag is indeed not supported. We desupport this option and update the doc. Thanks.

**Comment by fredbi** [comment]
No more flag.
