### ISSUE TITLE
Create definition

### ISSUE THREAD

**Issue by abergmeier** [go-swagger/go-swagger#1355]
## Problem statement

I have multiple `operation`s, which all refer to the same parameter. Now I want these to be reffed but cannot figure out how to add a definition to the json.

I tried

```
// swagger:model foobar
type fooBar struct {
	Name string `json:"f"`
	In string `json:"path"`
	Description string `json:"F1"`
	Required bool `json:"true"`
}
```

but no `foobar` definition is added to the json.

## Swagger specification

```
// swagger:operation GET /foo getFoo
//
// ---
// produces:
// - application/json
// parameters:
// - $ref: "#/definitions/foobar"

```

**Comment by casualjim** [comment]
you have to use the model in a parameters struct,  the parameter struct can be assigned to many operations by listing all the operationId's it pertains to.

**Comment by abergmeier** [comment]
> you have to use the model in a parameters struct, the parameter struct can be assigned to many operations by listing all the operationId's it pertains to.

Thanks for trying to help but I literally did not understand a single thing you said. Can you perhaps try to show with a code sample?

**Comment by abergmeier** [comment]
Ok, I think part of the problem was not generating with `--scan-models`. Adding that adds also the definitions.

**Comment by casualjim** [comment]
yes but also parameters can't refer to definitions because they are distinct things.

A definition is a struct to represent a payload
A parameter is headers, query params, path params and body

for example:
```go
// An OrderBodyParams model.
//
// This is used for operations that want an Order as body of the request
// swagger:parameters updateOrder createOrder
type OrderBodyParams struct {
	// The order to submit.
	//
	// in: body
	// required: true
	Order *models.StoreOrder `json:"order"`
}
```

this defines a parameter that uses the models.StoreOrder (your foobar) as request body. And this parameter is associated with both the operations: updateOrder and createOrder

**Comment by abergmeier** [comment]
> parameters can't refer to definitions because they are distinct things.

Ok, this then means I am forced to copy and paste parameter entries?

**Comment by casualjim** [comment]
I don't know why you'd need to copy paste them? it's 1 type that can be attached to many operations. You can only have 1 body

**Comment by abergmeier** [comment]
> I don't know why you'd need to copy paste them?

If I have 4 operations and all of them want a path parameter of name `foobar`, this means I have to have 4 definitions of `foobar`, right?

```
// swagger:operation GET /{foobar}/foo1 getFoo1
//
// ---
// produces:
// - application/json
// parameters:
// - name: foobar
//   in: path

// swagger:operation GET /{foobar}/foo2 getFoo2
//
// ---
// produces:
// - application/json
// parameters:
// - name: foobar
//   in: path
```

**Comment by casualjim** [comment]
if you use swagger:route you don't need to

```go

// swagger:parameter getFoo1 getFoo2
type fooBarParam struct {
  // in: path
  FooBar string `json:"foobar"`
}

//swagger:route GET /{foobar}/foo1 getFoo1
func getFoo1(res responsewriter, req request) {}

//swagger:route GET /{foobar}/foo2 getFoo2
func getFoo2(res responsewriter, req request) {}

```

**Comment by abergmeier** [comment]
> if you use swagger:route you don't need to

Route is harder to retrofit into already working source code, IMO.
I assumed, that one could refer to a "global" parameter since it is e.g. possible to refer to a "global" security definition. Now I realize, that `security` has special handling.

Also I am not clear what _model_, _route_, _operation_, etc. have as a semantic meaning. It seems the docs assume one is already very versed in these topics (which I am not).

Anyway, thanks a lot for your time.

**Comment by fredbi** [comment]
This thread would be a welcome addition to our FAQ: https://github.com/go-swagger/go-swagger/blob/master/docs/faq/faq_spec.md
