### ISSUE TITLE
--dump-data no longer working

### ISSUE THREAD

**Issue by dmacthedestroyer** [go-swagger/go-swagger#1356]
## Problem statement
issuing the `swagger generate server --dump-data` command results in the following error:

> json: unsupported type: func(string) string

This seems to work on 0.13 (installed via homebrew) but no longer works against dev head. Possibly a regression error?
## Swagger specification
```
consumes:
- application/json
info:
  title: Foo
  version: 0.1.0
paths:
  /foo:
    get:
      summary: foo
      operationId: listFoo
      responses:
        "200":
          description: foos
produces:
- application/json
schemes:
- http
swagger: "2.0"
```

## Steps to reproduce
`swagger init spec`
add the path in the above spec
`swagger generate server --dump-data`

## Environment
swagger version: dev (head)  
go version: 1.9.2
OS:   darwin/amd64

**Comment by fredbi** [comment]
Yes. I tested again and found the regression.
PR #1315 introduced a function BaseImportFunc in generator structure, which cannot be rendered as JSON by dump-data.

**Comment by fredbi** [comment]
We need a custom marshall that excludes unsupported types such as functions, interfaces, ...

**Comment by gregmarr** [comment]
Simple fix:

	BaseImportFunc   func(string) string `json:"-"`
