### ISSUE TITLE
Question about accessing endpoint from external network

### ISSUE THREAD

**Issue by stevef1uk** [go-swagger/go-swagger#1358]
I have generated simple server code from a swagger file and successfully added a handler and testing locally with curl works fine.

I have just deployed this to OpenShift and whilst it works fine on the actual container using curl from the terminal to http://127.0.0.1:8080 I can't access it remotely using the route created. Before I dive into OpenShift/Kubernetes route debugging I wondered if there was anything I needed to do to my go-swagger generation flags /config process to allow external IP address access?

**Comment by stevef1uk** [comment]
I just realised that I specified localhost in the swagger file so that could be why :-)

**Comment by fredbi** [comment]
OP solved issue
