### ISSUE TITLE
Grouping models to produce less files?

### ISSUE THREAD

**Issue by aalexanderr** [go-swagger/go-swagger#1360]
## Problem statement
When generating models, each model is created in separate file. 
Is there a way to group models to produce less files?

## Environment
swagger version: dev 
go version: 1.9.2 linux/amd64 
OS:   Ubuntu 16.04

**Comment by casualjim** [comment]
can you explain me the benefit of this?

**Comment by aalexanderr** [comment]
The benefit isn't big, and I will fully understand if it won't be added. 

It is just a matter of preference/ readability- when having many small defined types, we end up with many, many files that are ~20 lines long. Some projects have coding style guidelines to have fewer files, each with a group of types pertaining to some specific module on the back-end side. It would be nice if there was possibility to configure go-swagger to adhere to the coding style of a specific projects.

**Comment by fredbi** [comment]
I think it's out of our scope to carry on this kind of rules.
There are already so many things to do to adhere to one's specific use-case. 

You may be interested in this to add in your toolchain: https://github.com/naegelejd/gocat
Alternatively, you might be a fan of grunt. There are some go plugins to orchestrate build tasks. This is typically as place we you might insert a source concat plugin;

**Comment by aalexanderr** [comment]
Thank you very much! gocat solves the issue!
