### ISSUE TITLE
match for the market the limit of the new system with esi

### ISSUE THREAD

**Issue by Meio-rayliegh** [go-swagger/go-swagger#1374]
Hello i remark that it is now impossible to ask what is the highest buy order and the lowest sell order and now we have to make a big research to affiliate each item to the number it will tyake many time just to filter that and after we have to filter the sell order and the buy order for finally test if th buy order is bigger than the sell order...is it really that ?the progress?

**Comment by gregmarr** [comment]
@Meio-rayliegh I think you have the wrong project.

**Comment by Meio-rayliegh** [comment]
in fact i search a method to scan all the business world of the new eden
via esi it is really difficult i thought of a python programm but it have
too many problem first it have to search the biggest buy order and the
smallest sell order but all are repertoried by id and in consideration of
the number of ID it is a really big work try to know what objet has which
value after that compared the sell and buy order if it have it it is a
really big problem in fact

2018-01-12 2:42 GMT+01:00 gregmarr <notifications@github.com>:

**Comment by casualjim** [comment]
You are in the wrong place.
You probably want https://github.com/uplink42/etmv2 or some other repo that's not go-swagger.
go-swagger is a repo that implements a specification for api documentation.
