### ISSUE TITLE
How to serve my UI files?

### ISSUE THREAD

**Issue by shyr** [go-swagger/go-swagger#1375]
## Problem statement
I generated server code using go-swagger with my swagger.yaml file like below.
```bash
$ swagger generate server --exclude-main -A myapp -t gen -f ./swagger.yaml
```
And I want to add new handler to serve my own UI files. 
In this case, is middleware only solution to serve UI files? Or can I add new handler to serve files without middleware?
```go
// Handler example which I want to add to swagger server
func pastaWorkspacePage(w http.ResponseWriter, r *http.Request) {
	http.ServeFile(w, r, "./static/workspace.html")
}
```

## Environment
swagger version: 0.13.0  
go version: 1.9.2
OS:  MacOS 17.3.0 Darwin

**Comment by shyr** [comment]
Anyway, I solved the problem using middleware.
```go
func FileServerMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/api") {
			next.ServeHTTP(w, r)
		} else {
			http.FileServer(http.Dir("./static")).ServeHTTP(w, r)
		}
	})
}
```
But I'm not sure it a right and best solution.

**Comment by macrael** [comment]
I am also curious about best practices for hosting endpoints other than the API with this framework. For instance, we'd like to host the swagger UI and also our site's front end javascript, somewhere.

**Comment by casualjim** [comment]
you can use golangs static content middleware to serve static files like it was described in the comment above

**Comment by casualjim** [comment]
more info on using middlewares is found here: https://goswagger.io/use/middleware.html

That page also contains a link to a good explanation on how to create net/http middlewares

**Comment by keith6014** [comment]
i too am curious. what is the best way to achieve this?

**Comment by fredbi** [comment]
Take a look at cmd/swagger/commands/serve.go

**Comment by casualjim** [comment]
Every swagger generated server comes with the redoc UI baked in at /{basepath}/docs

**Comment by zees-dev** [comment]
You can potentially serve your file using multiple handlers for your single multiplexer:
```
mux := http.NewServeMux()
mux.Handle("/", app.APIHandler(nil))
fileserver := http.FileServer(http.Dir("./static"))
mux.Handle("/static/", http.StripPrefix("/static", fileserver))
...
http.ListenAndServe(":8080", mux)
```
