### ISSUE TITLE
Codegen fixture [discriminators] produces code that doesn't compile

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1376]
## Problem statement
Broken codegen on fixture

## Swagger specification
./fixtures/codegen/todolist.discriminators.yml

## Steps to reproduce
```bash
swagger generate server --spec=./fixtures/codegen/todolist.discriminators.yml --name=nrcodegen --target=./gen-todolist.discriminators
cd ./gen-todolist.discriminators/cmd/nrcodegen-server
go build
```

Produces:
```
# github.com/go-swagger/go-swagger/fixtures/bugs/909/gen-todolist.discriminators/models
../../models/kennel.go:45:52: cannot call non-function m.Pets (type KennelPets)
../../models/kennel.go:49:18: cannot call non-function m.Pets (type KennelPets)
```
## Environment
swagger version: [current master]
go version: 1.9.1
OS:   linux ubuntu 14.02

**Comment by fredbi** [comment]
It looks like the troublemaker is located here:
https://github.com/go-swagger/go-swagger/blob/dfe8aa7cd3ac65f8d754cdf9ae285dd52a42e1d3/generator/model.go#L191

**Comment by kmudrick** [comment]
I'm on commit `f552963ac0dfdec0450f6749aeeeeb2d31cd5544` of go-swagger and I still see this broken discriminator behavior

**Comment by fredbi** [comment]
Could you please elaborate and provide a specific example of failure, because the one I provided above does indeed compile.
