### ISSUE TITLE
package and file name contain underscore (after a change in go-swagger)

### ISSUE THREAD

**Issue by pierrre** [go-swagger/go-swagger#1380]
## Problem statement

Since this commit https://github.com/go-swagger/go-swagger/commit/43c39abf79b51c062d8d38345a0b7ecfd72c6b98
the package and file name generation has changed.
Before this commit, the package name is `sms_campaigns`.
After this commit it's like `s_m_s_campaigns`.
(I did a git bisect)

## Swagger specification

https://api.sendinblue.com/v3/swagger_definition.yml

It's used in this project https://github.com/sendinblue/APIv3-go-library

cc @ekta-slit

## Steps to reproduce

`swagger generate client -f build/swagger_definition.yml`

## Environment
swagger version: master  
go version: 1.10beta2

**Comment by fredbi** [comment]
Hello. With this commit you have the possibility to customize the "initialisms" (upper cased words who want to keep in one piece). It should work as it used to with: --additional-initialism=SMS

**Comment by pierrre** [comment]
Thank you !
