### ISSUE TITLE
type: string, format: int64 not respected in generator

### ISSUE THREAD

**Issue by johanbrandhorst** [go-swagger/go-swagger#1381]
## Problem statement
When generating a client from a swagger file with a definition that specifies `type: string` and `format: int64`, the JSON struct tag generated is incorrect.

## Swagger specification

`test.json`:
```json
{
    "consumes": [
        "application/json"
    ],
    "definitions": {
        "Test": {
            "properties": {
                "id": {
                    "format": "int64",
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "paths": {
        "/api/v1/test": {
            "get": {
                "operationId": "test",
                "responses": {
                    "200": {
                        "schema": {
                            "$ref": "#/definitions/Test"
                        },
                        "description": "test"
                    }
                }
            }
        }
    },
    "info": {
        "version": "1",
        "title": "Test"
    },
    "produces": [
        "application/json"
    ],
    "schemes": [
        "https"
    ],
    "swagger": "2.0"
}
```

## Steps to reproduce

```bash
$ swagger generate client -f test.json -t ./test/
```

Produces a model like so:

```go
// Test test
// swagger:model Test
type Test struct {

	// id
	ID int64 `json:"id,omitempty"`
}
```

It should, ideally, be

```go
// Test test
// swagger:model Test
type Test struct {

	// id
	ID int64 `json:"id,omitempty,string"`
}
```
## Environment
swagger version: dev (tip of master as of today)
go version: go version go1.9.1 linux/amd64
OS: Linux

**Comment by casualjim** [comment]
that's an invalid type. The openapi 2.0 spec says the type should be 
```
type: integer
format: int64
```

**Comment by johanbrandhorst** [comment]
Do you have a source for me to reference? This swagger definition is generated by `protoc-gen-swagger` of the `grpc-gateway` project. Protobuf automatically encodes uint64 and int64 as strings because the numeric type would introduce inaccuracies (numeric being a float64).

**Comment by fredbi** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by johanbrandhorst** [comment]
I suppose it's an open question then how OpenAPI deals with integer overflows in JSON numbers? I took a look at the 3.0 spec as well and it says:

```
Note that integer as a type is also supported and is defined as a JSON number without a fraction or exponent part.
```

I don't really understand what that means for integer overflows. I do agree that this appears to be nonstandard behaviour, but all the same this is a problem with the specification that I think the grpc-gateway (and protobuf in general) fixes. Feel free to close this issue as I understand you wouldn't be keen to implement something that's not strictly part of the OpenAPI spec.

**Comment by fredbi** [comment]
I had started some work on the go-openapi/validate package to cleanly deal with overflows and lossy conversions but it's still work in progress (I believe it's related to issue#581).
I don't think we are going to support bignum, but at least we cleanly could detect overflows at validation time.
