### ISSUE TITLE
Add Title generation for info part of spec.

### ISSUE THREAD

**Issue by abondar24** [go-swagger/go-swagger#1382]
## Problem statement
I have noticed that title field isn't added when swagger.json is generated.
I tried to add  like this: Title: SocialTournamentService API but nothing has happened

## Environment
swagger version: 0.13.0  
go version: 1.9  
OS:   Ubuntu 16.04

**Comment by fredbi** [comment]
Does the explanation provided in #1118 help?

**Comment by abondar24** [comment]
A little bit
