### ISSUE TITLE
HTTPS TLS Cipher Suites not supported by AWS Elastic LoadBalancer

### ISSUE THREAD

**Issue by chiragk25** [go-swagger/go-swagger#1383]
Hi,

AWS Elastic LoadBalancer forwards https requests to instances, and their security policy is 'ELBSecurityPolicy-2016-08' However, while running the server on https, the server keeps on logging 

http: TLS handshake error from 192.168.X.X:XXXXX: tls: no cipher suite supported by both client and server. 

If we remove the cipher suites on the generated code, it resolves the issue - 

CipherSuites: []uint16{
  tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
  tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
  tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
  tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
},

The ELB security policy 'ELBSecurityPolicy-2016-08' does include these cipher suites, however all requests sent by the ELB are rejected by the server. I'm using swagger version 2.0.

Thanks
Chirag

**Comment by casualjim** [comment]
you can generate the server with a different compatibility mode for the older generation of ciphers

```
swagger generate server --compatibility-mode=intermediate
```
