### ISSUE TITLE
Generated configure file has confusing directions.

### ISSUE THREAD

**Issue by jcoyne** [go-swagger/go-swagger#1384]
## Problem statement

Line 1 says "don't edit": https://github.com/go-swagger/go-swagger/blob/18337a2ecf1022fa5e6b3b01b3ac4033e1e4955b/generator/templates/server/configureapi.gotmpl#L1

But line 28 says "you should edit this file": https://github.com/go-swagger/go-swagger/blob/18337a2ecf1022fa5e6b3b01b3ac4033e1e4955b/generator/templates/server/configureapi.gotmpl#L28

These messages should be made consistent.

**Comment by gregmarr** [comment]
Yeah, line 1 should not have been added to this template when it was added to the others.  It probably makes sense to move line 28 to line 1.

**Comment by fredbi** [comment]
OK just fixed it in my WIP branch. That would be in the PR#1372 if you don't mind
