### ISSUE TITLE
No validation is called on body of array type parameter.

### ISSUE THREAD

**Issue by zerbitx** [go-swagger/go-swagger#1392]
## Problem statement
When the body parameter is an array type, referencing another type, none of the validation is called.

Its possible I'm just defining it incorrectly (as I'm new to writing swagger specs), but I can't seem to get it to satisfy the criteria around [this line of parameter.gotmpl](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/parameter.gotmpl#L203)

If the validation checking done [around here](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/parameter.gotmpl#L209) is done it works correctly, sending back a 400 any "state" that's not in the enum. But it never gets into this section because it passes the [{{ if .Child }} check](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/parameter.gotmpl#L203)

In the "Generated Code" section below, the Validate method for the `BulkUpdateState` type is created correctly, but never called in `BindRequest`

## Swagger specification
```
swagger: "2.0"
info:
  title: Bug? Demo
  description: Description.
  version: "0.1.0"
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
responses:
  200:
    description: OK
    schema:
      type: string
  400:
    description: Bad Request
paths:
  /someResource/:
    patch:
      consumes:
        - application/json
      summary: Update the state of multiple stuff and things at once.
      parameters:
        - in: body
          name: massUpdate
          schema:
            $ref: '#/definitions/BulkUpdateState'
      responses:
        200:
          $ref: '#/responses/200'
        400:
          $ref: '#/responses/400'
      tags:
        - SomeResource
definitions:
  BulkUpdateState:
    type: array
    items:
      $ref: '#/definitions/UpdateStateRequest'
  UpdateStateRequest:
    type: object
    required:
      - ID
      - state
    properties:
      ID:
        type: string
        x-nullable: false
      state:
        $ref: '#/definitions/StateEnum'
  UpdateRequest:
    type: object
  StateEnum:
    type: string
    enum:
      - todo
      - done
      - blocked
      - skipped
      - unenrolled
      - custom
```
## Steps to reproduce
- Generate the server based on this swagger.
- Add a handler
- Hit the /someResource route with a patch request, containing JSON array with states other than listed in the enum.
- See that requests make it to the handler.

## Generated Code

```
// BulkUpdateState bulk update state
// swagger:model BulkUpdateState
type BulkUpdateState []*UpdateStateRequest

// Validate validates this bulk update state
func (m BulkUpdateState) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```

```
// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PatchSomeResourceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.BulkUpdateState
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("massUpdate", "body", "", err))
		} else {

			if len(res) == 0 {
				o.MassUpdate = body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```

## Environment
swagger version: 0.13.0
go version: 1.9.2
OS:   Mac OS 10.13.2

**Comment by fredbi** [comment]
Looks very much like #1093

**Comment by fredbi** [comment]
Same here: for any body param with simple type, no validation is generated.
It works when forcing a model to be generated (e.g. using $ref: ...)
