### ISSUE TITLE
Required properties are not validated when additionalProperties: true is provided

### ISSUE THREAD

**Issue by jcoyne** [go-swagger/go-swagger#1397]
## Problem statement

When I use this schema:
```json
  "definitions" : {
    "Resource" : {
      "type" : "object",
      "required" : [ "sourceId", "title" ],
      "additionalProperties" : true,
      "properties" : {
        "id" : {
          "type" : "string",
          "example" : "oo000oo0001"
        },
        "title" : {
          "type" : "string",
          "example" : "My work"
        },
        "sourceId" : {
          "type" : "string",
          "example" : "bib12345678"
        }
      }
  }
```

and I don't provide a `sourceId` in the request, then it doesn't return a validation error.  If I remove the `additionalProperties: true` then it does return an error.

## Swagger specification
2.0

## Environment
swagger version: 0.13.0  
go version: 1.9  
OS:  osX

**Comment by fredbi** [comment]
There is a known issue around there. You might try the workaround suggested by #1198.

**Comment by gregmarr** [comment]
Wow, this is ugly.  I'm investigating.

**Comment by jcoyne** [comment]
@fredbi I attempted the workaround, but then it didn't generate `ResourceAdditionalProperties` into the model struct.

**Comment by gregmarr** [comment]
Anyone have a spec with `additionalProperties` that has validation?  I'm not seeing any in the repo and I want to test my fix.

**Comment by fredbi** [comment]
Hi Greg. You may check out in the fixtures from fo-openapi/validate, there some test cases with additionalProps.
You might have the fixture/canary/kubernetes/swagger.json, but I don't see there are validations with additionalProps and anyway, this one has other problems with generation.

**Comment by gregmarr** [comment]
Yeah, I don't see any validations in any of those schemas. I guess I'll have to make one.

**Comment by fredbi** [comment]
Even this one? https://github.com/go-openapi/validate/blob/master/fixtures/validation/valid-referenced-variants.yaml

**Comment by gregmarr** [comment]
I don't see anything there.  Am I missing something?

**Comment by fredbi** [comment]
This spec is not valid (it's for testing validation messages). But you have a section with additionalProperties and patternProperties with different required / format patterns (actually patternProperties are not supported). Well this is probably not a good example. Better to start fresh off

**Comment by gregmarr** [comment]
@jcoyne Can you try out the latest version and see if it fixes your issue?

**Comment by jcoyne** [comment]
@gregmarr Yes! That looks great. Excellent work.

**Comment by fredbi** [comment]
@jcoyne please close your issue if you are satisfied with the fix. Thanks

**Comment by gregmarr** [comment]
Thanks @jcoyne!
