### ISSUE TITLE
Replace graceful with built-in methods (1.8 onwards)

### ISSUE THREAD

**Issue by tortuoise** [go-swagger/go-swagger#1418]
## Problem statement
go-swagger's generate server uses a graceful.Server, the main functionality of which is now built-in to Go 1.8. Perhaps the dependency on graceful can be removed altogether ?

## Environment
swagger version: 2.0 / go-swagger dev
go version: 1.8  
OS:   NA

**Comment by casualjim** [comment]
I like this idea

**Comment by tortuoise** [comment]
I'll work on a pull request. Changing just the commands and templates shouldn't take that much time, but changing all the examples and tutorials will. Do you prefer be done simultaneously ?

**Comment by casualjim** [comment]
the examples can be changed by running ./hack/regen-samples.sh 

so at least the code samples are updated. I think there isn't that much in the docs themselves that needs to be changed. 
Ideally the docs reflect our current code base.

**Comment by tortuoise** [comment]
I've used golang.org/x/net/netutil for its LimitListener to replace graceful.Server.ListenLimit. 
Any ideas how to replace graceful.Server.LogFunc ?

**Comment by casualjim** [comment]
we don't need to support the graceful.Server.LogFunc, it's only used on errors when the listener can't be closed or on shutdown when connections can't be released.
So we'd mostly need to cover those 2 use cases

**Comment by tortuoise** [comment]
Ok. 
One other observation: graceful.Server handles  SIGINT/SIGTERM - not sure http.Server does that.

**Comment by casualjim** [comment]
this has a graceful implementation based with golang support: https://github.com/TV4/graceful

it's based off this example: https://gist.github.com/peterhellberg/38117e546c217960747aacf689af3dc2#gistcomment-1982608

**Comment by tortuoise** [comment]
I had a look at TV4/graceful. Server shutdown is reliant on a syscall which I'm not sure is good - but I get the general idea.

**Comment by tortuoise** [comment]
I've made the changes in [a fork](https://github.com/tortuoise/go-swagger) though still facing some issues so no pr yet. Comments about general approach, obvious errors etc. welcome.

**Comment by fredbi** [comment]
Enhancement merged with PR #1574
