### ISSUE TITLE
Dependency management v/ generated code

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1419]
## Problem statement
I found myself sometimes struggling with dependencies with the packages needed by generated code + the ones needed by the API itself.

I am considering auto-vendoring generated code by pushing the contents of selected package from go-swagger vendor to my generation target.

Of course, I may achieve that with an external script.

Any thought on if this would be a useful feature for the generator and how this could be made useful to others?

## Environment
swagger version: x.x.x  
go version: 1.9
OS:

**Comment by gregmarr** [comment]
Have you tried `dep` yet? I just finished converting my project to it, and it did a great job of vendoring just what I needed to run the generated code. I had to actually mark certain packages as required in my manifest to keep them from being removed so I could still run the generate command from the vendor directory.  If you install go swagger instead of vendoring it, then you won't have to deal with that part.

**Comment by fredbi** [comment]
Thanks 
The point is about locking in the same versions as the generator.
So what you suggest I should just copy go-swagger's lock file and then everything gets vendored with these versions?

**Comment by gregmarr** [comment]
If you have the generator vendored then it should automatically have the same versions. If you're using installed, I'm not sure. You may have to specify the versions in your manifest. I have it vendored and checked in so that I don't have a variable version in my CI system.

**Comment by fredbi** [comment]
So do you think that generating a dep lock file as target with the same requirements as the generator would be a helpful feature? If not, I may well use your hint in my toolchain as external stuff

**Comment by fredbi** [comment]
Thanks for the tip btw

**Comment by gregmarr** [comment]
I don't think that's necessary, dep is working fine on its own for me.

I just needed to add this:

    required = ["github.com/go-swagger/go-swagger/cmd/swagger"]

    [[constraint]]
      name = "github.com/go-swagger/go-swagger"
      revision = "98dcea64a45932ddfdc8911a2488d364e52d27ed"

That's because I'm working with a particular version right now.  I'm tracking down a hang on server generate when I update everything.

**Comment by fredbi** [comment]
@casualjim  : How about tagging go-openapi packages in line with go-swagger?
That would ease quite a bit the pinning process with dep and avoid to vendor go-swagger itself...

**Comment by fredbi** [comment]
thank you @casualjim : you tagged _all_ repos. Now dep recognizes this and stick to these version.
Great!
