### ISSUE TITLE
Possible to have models in Subdirectory?

### ISSUE THREAD

**Issue by chrisabruce** [go-swagger/go-swagger#1428]
## Problem statement

When passing  `-m` argument as below which includes `/`, I was hoping that would allow the models to be in a subdirectory:

`swagger generate server -A Yabber -f ./api/swagger/swagger.yaml --flag-strategy=pflag -m pkg.models.swagger`

However the import statements are snake casing the package name:
...`yabber/restapi/operations/accounts/create_account_parameters.go:15:2: cannot find package "github.com/xxx/yabber/pkg_models_swagger"`

Please remove the sections that don't apply

## Steps to reproduce
- Generate with `-m` option containing `/`

## Environment
swagger version: 0.13.0
go version: 1.9.2  
OS:   OSX

**Comment by gregmarr** [comment]
This has been fixed in `master`.

**Comment by chrisabruce** [comment]
Great thanks!  Just tested and can confirm.
