### ISSUE TITLE
Clarify which files are safe to edit

### ISSUE THREAD

**Issue by thefinn93** [go-swagger/go-swagger#1431]
## Problem statement

I have been trying to understand Go Swagger and have been increasingly noticing a major inconsistency: Some generated are not safe to edit, some are (according to the docs, at least), but they *all* start with this line:

```go
// Code generated by go-swagger; DO NOT EDIT.
```

Which is rather confusing. I noticed this line lower down:

```go
// This file is safe to edit. Once it exists it will not be overwritten
```

But only after looking through the file that the docs explicitly said to edit. Perhaps the `DO NOT EDIT` portion of the top comment should be removed from generated files that can be edited.

Sorry if this is a duplicate, I poked through the issue tracker but it turns out there are 18 pages of issues returned when searching for "DO NOT EDIT" and none of the first few pages seem to describe anything related to this.

**Comment by fredbi** [comment]
Hello
As far as I know, the only generated file which mentions "safe to edit" is configure_api.go.

There used to be an inconsistent comment in this template and this has been solved now with current master.

Duplicate #1384

**Comment by thefinn93** [comment]
Great, thanks!
