### ISSUE TITLE
Generated operations are not including the principal, causing compilation errors

### ISSUE THREAD

**Issue by jcoyne** [go-swagger/go-swagger#1432]
## Problem statement

When I am working in my project `github.com/sul-dlss-labs/permissions_service` and I have created a principal `permissions_service.Agent` which is in `agent.go` and I generate the server by doing:

```
swagger generate server -t generated --exclude-main --principal permissions_service.Agent
```

Then the operations are generated without importing `github.com/sul-dlss-labs/permissions_service` which causes a compile error.  

For example:
```go
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// QueryActionHandlerFunc turns a function with the right signature into a query action handler
type QueryActionHandlerFunc func(QueryActionParams, *permissions_service.Agent) middleware.Responder

...
```

## Swagger specification
2.0

## Environment
swagger version: 2.0 
go version: 1.9
OS:   MacOS 10.13

**Comment by jcoyne** [comment]
Curiously, if I change it to `--principal models.Agent` it does generate the import:

```
	"github.com/sul-dlss-labs/arepa/generated/models"
```

**Comment by fredbi** [comment]
Yes. Principals are assumed to be part of the model package. So you may redefine your principal there.

There must be some assumptions anyway. How would the generator know that your struct is defined in this or that package?

**Comment by jcoyne** [comment]
@fredbi  when change the package to `permissions` and I do `swagger generate server -t generated --exclude-main --principal permissions.Agent` it generates:

```
permissions "github.com/sul-dlss-labs/permissions-service"
```

I'm pretty new to go.  This behavior doesn't make sense to me. There seem to be some package names that are acceptable to it and some that are not.  It would be helpful to me if these assumptions are clearly expressed in documentation or in warnings when running the generator.

**Comment by fredbi** [comment]
Sure documentation would be helpful, but there is nobody around to help... :)

I believe this behavior comes from the name mangling.

**Comment by casualjim** [comment]
is the Agent type mentioned in the spec ? if it isn't, then the x-go-type annotation might solve this issue for you. https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/existing-model.yml#L84-L88

**Comment by casualjim** [comment]
in many go tools, packages are assumed to only exist out 1 word so they want the package to be github.com/sul-dslss-labs/permissions/service
