### ISSUE TITLE
Optional SSN field performs no validation

### ISSUE THREAD

**Issue by macrael** [go-swagger/go-swagger#1434]
## Problem statement

Given a field of type: string and format: ssn, if the field is set to be optional then no validations are performed on the value. 

## Swagger specification
```
paths:
  /form:
    post:
      summary: Create a new form
      operationId: createForm
      tags:
        - issues
      parameters:
        - in: body
          name: createIssuePayload
          required: true
          schema:
            $ref: '#/definitions/CreateFormPayload'
      responses:
        201:
          description: created form
          schema:
            $ref: '#/definitions/FormPayload'
        400:
          description: invalid request
definitions:
  CreateFormPayload:
    properties:
      member_ssn:
        type: string
        format: ssn
```

## Steps to reproduce

Given the above swagger definition, attempt to post a new object to the /form:
```
{
    "member_ssn": "12"
}
```

## Results

I would expect an error to be returned, but instead the handler is called as expected. If member_ssn is marked as required, then the above will return an error as expected. 

## Environment
swagger version: 0.13.0
go version: 1.9.4
OS: MacOS 10.13.3 (17D102)

**Comment by gregmarr** [comment]
Have you tried this on the latest master?  There has been a lot of work on validation since 0.13.0 was released.

**Comment by fredbi** [comment]
Duplicates #1347 and #1348

**Comment by macrael** [comment]
This is fixed on master, feel free to close. When are you planning on cutting a new release?
