### ISSUE TITLE
Support for optional auth?

### ISSUE THREAD

**Issue by dmjones500** [go-swagger/go-swagger#1446]
## Problem statement

I'm trying to support optional authorization for a path, but it seems like go-swagger is requiring authorization each time.

Based on https://github.com/OAI/OpenAPI-Specification/issues/14, I've create a path that includes:

```
      security:
      - {}
      - jwt: []
```

This compiles fine, but when I submit request that doesn't include my API key, I get an immediate 401 response. Is this a supported configuration?

## Environment
swagger version: 

version: 0.13.0
commit: 8135eb6728e43b73489e80f94426e6d387809502

go version: go1.9.3 darwin/amd64  

OS:   Mac OSx

**Comment by fredbi** [comment]
You might be interested with analysis in #1089

**Comment by casualjim** [comment]
Optional auth should now be supported

**Comment by tschaub** [comment]
I'm struggling to come up with a security spec that takes advantage of the new optional auth functionality in https://github.com/go-openapi/runtime/pull/98.  Should the configuration below be supported now?

```yml
security:
  - {}
  - SomeOtherAuthenticationType
```

**Comment by fredbi** [comment]
Have you taken a look at the example [here](https://github.com/go-swagger/go-swagger/tree/master/examples/composed-auth)? Several combinations are examplified there.

**Comment by tschaub** [comment]
I've created go-openapi/runtime#103 in hopes of getting optional authentication support with a spec like the one above.

**Comment by tschaub** [comment]
Thanks @fredbi - I did look through the docs on [composed security requirements](https://github.com/go-swagger/go-swagger/tree/master/examples/composed-auth) - they cover some nice use cases.  Unless I'm misreading, I don't think they consider the "optional authentication" use case.

It looks like the changes in `go-openapi/runtime#98` were intended to support optional authentication.  And there is a test case that covers this (see https://github.com/go-openapi/runtime/pull/98/files#diff-766ab5a2cb406b60ad239ca4c3e484c9R194).  However, the tests passes with a route authenticator that looks like this:

```go
ra := RouteAuthenticator {
	allowAnonymous: true,
}
``

And this is different than the shape of a route authenticator that is built from the spec above (with `security: [{}, ...]`).  This spec generates a route authenticator that looks something like this:

```go
ra := RouteAuthenticator {
	allowAnonymous: true,
	Schemes: []string{""},
	# ...
}
```

**Comment by fredbi** [comment]
How goes your spec example through the other toolkit packages, e.g. spec, analysis an validate?
We should make sure that putting an empty object under security is well supported in all these places.

**Comment by fredbi** [comment]
I can see that in analysis, the case for an empty SecurityRequirement is well there.
Afaik, validate does not check security items at the moment.
So it might be good.

**Comment by tschaub** [comment]
The spec validates using `swagger validate` and https://editor.swagger.io/.  The [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/52286d305c6c742ce9dc12d62529a7e66c80f969/schemas/v2.0/schema.json#L1067-L1076) requires that `security` items are object and has constraints about additional properties - so an empty object validates.

**Comment by etiennedi** [comment]
I'm trying to achieve something similar, as the OP: I want to support "no auth" and "open id connect" auth in parallel. That's working fine so far.

Additionally, I want to make sure that I can dynamically forbid specific auth methods based on environment configuration. (For example "no auth in dev", "basic auth in staging", "oidc in production").

Forbidding oidc or basic is easy. I can simply do something like:
```go
api.OidcAuth = func (token string, scopes []string) (*models.Principal, error) {
  if !environment.OIDCEnabled {
    return nil, errors.New(401, "oidc auth is not configured, please try another auth scheme or set up with OIDC configured")
  }
  // ... handle OIDC
}
```

However, I can't find a middleware or handler that is called whenever the user sets no Auth headers at all. So how do I deal with the case when the environment is configured to forbid anonymous access. I could of course just build a generic middleware, check all headers if any other auth scheme is used and then finally check if my environment allows for anonymous access. However, I'd probably write a lot of code that already exists somewhere on the inside.

So it'd be preferable if there was something like 

```go
api.AnonymousAuth = func () (*models.Principal, error) {
  if !environment.AnonymousAuthEnabled {
    return nil, errors.New(401, "anonymous auth is not configured, please one of the available auth schemes")
  }

  return nil, nil
}
```

Maybe this exists, but I'm missing it? Should we add it?
