### ISSUE TITLE
Invalid code generation with AdditionalProperties

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1453]
## Problem statement

The generated validation code in model for the following JSON schema constructs is invalid.

This testcase is part of the cloudbreak.json spec (see also #910): [here](https://gist.github.com/mhmxs/63060f19ecfbf7c0d375663629701494)

Given the following definition:
``` json
"PlatformGatewaysResponse" : {
      "type" : "object",
      "properties" : {
        "gateways" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "array",
            "uniqueItems" : true,
            "items" : {
              "$ref" : "#/definitions/CloudGatewayJson"
            }
          }
        }
      }
    }
```

The model generation yields:
```golang
// PlatformGatewaysResponseGateways platform gateways response gateways
// swagger:model platformGatewaysResponseGateways
type PlatformGatewaysResponseGateways map[string][]CloudGatewayJSON

// Validate validates this platform gateways response gateways
func (m PlatformGatewaysResponseGateways) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", PlatformGatewaysResponseGateways(m)); err != nil {
		return err
	}

	for k := range m {

		if err := validate.Required(k, "body", m[k]); err != nil {
			return err
		}

		if err := validate.UniqueItems(k, "body", m[k]); err != nil {
			return err
		}

		for i := 0; i < len(m[k]); i++ {

			if swag.IsZero(m[k][i]) { // not required
				continue
			}

			if m[k][i] != nil {

				if err := m[k][i].Validate(formats); err != nil {
					if ve, ok := err.(*errors.Validation); ok {
						return ve.ValidateName(k + "." + strconv.Itoa(i))
					}
					return err
				}

			}

		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
``` 

The `m[k][i] != nil`  is invalid.

With type:
```golang
// CloudGatewayJSON cloud gateway Json
// swagger:model CloudGatewayJson
type CloudGatewayJSON struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// properties

```
## Swagger specification
[cloudbreak.json](https://gist.github.com/mhmxs/63060f19ecfbf7c0d375663629701494)

## Steps to reproduce
```bash
swagger generate server --spec https://gist.github.com/mhmxs/63060f19ecfbf7c0d375663629701494
cd models
go build
``` 
## Environment
swagger version: current master  
go version: 1.9.1
OS:   linux ubuntu 14..04

**Comment by fredbi** [comment]
So the culprit template is [here](https://github.com/go-swagger/go-swagger/blob/e571dca8b0b44eff9dfccf5c2f4299a8f77389b3/generator/templates/schemavalidator.gotmpl#L92).
The problem seems to be that the generator does not know in which order to evaluate this structure which is at the same time a map and an array.
The generator evaluates .IsArray before .IsMap hence the type mismatch here.

**Comment by fredbi** [comment]
@mhmxs  this is what comes out of your spec now that the circular $ref issue is ok

**Comment by fredbi** [comment]
At first glance, I would say that we are checking the the parent type IsNullable and not the type defining .Items.

**Comment by mhmxs** [comment]
@fredbi thanks a lot. We are waiting for new version, because currently we have an in-house tool which does AST transform on the generated source.

**Comment by fredbi** [comment]
> We are waiting for new version

@mhmxs I hinted on where the problem probably lies but I am not going to implement a fix any time soon, since I am priorizing things. 
So to let you know, I am not going to work on issues currently tagged as: "generate spec", "additionalProperties", "discriminator", "additionalItems".  Some other contributors might have different priorities and fix these issues for the benefit of the community. 
Feel free to contribute with PRs...

**Comment by fredbi** [comment]
Found the problem. But this cloudbreak spec full of of additionalProperties is not fully passing yet...

**Comment by fredbi** [comment]
@mhmxs hi there. I tested the full generation with cloudbreak spec, which is now part of our CI tests.
Validation seems ok on the tricky parts with empty objects and additional properties (but the spec is very large, so I might have overlooked some details). Feedback from the field is welcome.

**Comment by mhmxs** [comment]
Hi @fredbi ,

Thanks you so much, we are waiting for the next release.
