### ISSUE TITLE
'$ref' in basePath does not pass validation command

### ISSUE THREAD

**Issue by aleksandr-vin** [go-swagger/go-swagger#1461]
## Problem statement

Using `$ref` is not supported by _validate_ command, while swagger UI works with this spec.

## Swagger specification

_swagger.yml_:
```yaml
swagger: '2.0'
info:
  version: "1.0.0"
basePath:
  $ref: basepath-ref-src.json
paths:
  /foo/:
    get:
      responses:
        "200":
```

_basepath-ref-src.json_:
```json
"/abc"
```

## Steps to reproduce

Place both files in a folder, run this command from bash in the same folder:
```bash
docker run --rm -v $(pwd):/home -w /home quay.io/goswagger/swagger:0.13.0 validate swagger.yml
2018/03/26 15:54:51 json: cannot unmarshal object into Go struct field SwaggerProps.basePath of type string
```

## Environment
swagger version: 0.13.0  
go version: 1.9.4  
OS:   Linux ef5acc98e0b3 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux

**Comment by casualjim** [comment]
yes it's not supported by the spec.
