### ISSUE TITLE
Race on call to Serve() and  _____Listener() functions

### ISSUE THREAD

**Issue by clj** [go-swagger/go-swagger#1465]
## Problem statement

There is a race condition involving calling [`func (s *Server) Serve() (err error)`](https://github.com/go-swagger/go-swagger/blob/2d443fa7eea569af9f20dd6f0302aef6c3b10651/generator/templates/server/server.gotmpl) and any of the [`func (s *Server) _____Listener() (net.Listener, error)`](https://github.com/go-swagger/go-swagger/blob/2d443fa7eea569af9f20dd6f0302aef6c3b10651/generator/templates/server/server.gotmpl#L536-L564) functions. I don't think these functions are generally used in the framework so this race condition won't affect very many people; e.g. I use these functions only to set up integration tests.

## Steps to reproduce

```go
package main

import (
	"log"
	"time"

	"github.com/go-openapi/loads"
	"github.com/go-swagger/go-swagger/examples/todo-list/restapi"
	"github.com/go-swagger/go-swagger/examples/todo-list/restapi/operations"
)

func main() {
	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server
	api := operations.NewTodoListAPI(swaggerSpec)
	server = restapi.NewServer(api)
	server.EnabledListeners = []string{"http"}

	server.ConfigureAPI()
	defer server.Shutdown()

	go func() {
		if err := server.Serve(); err != nil {
			log.Fatalln(err)
		}
	}()

	// Uncomment this to make sure that the server has (probably) definitely started
	// by the time `server.HTTPListener()` is called and the ports will be the same
	// time.Sleep(1 * time.Second)
	listener, err := server.HTTPListener()
	if err != nil {
		panic(err)
	}
	log.Printf("%+v", listener.Addr())

	time.Sleep(1 * time.Second)
}
```

This very consistently outputs stuff like:
```
> go run main.go
Result of server.HTTPListener(): 127.0.0.1:53060
Serving todo list at http://127.0.0.1:53061
> go run main.go
Serving todo list at http://127.0.0.1:53102
Result of server.HTTPListener(): 127.0.0.1:53103
> go run main.go
Serving todo list at http://127.0.0.1:53118
Result of server.HTTPListener(): 127.0.0.1:53119
> go run main.go
Result of server.HTTPListener(): 127.0.0.1:53140
Serving todo list at http://127.0.0.1:53141
```
while with the delay uncommented, the output looks like this:
```
go run main.go
Serving todo list at http://127.0.0.1:55073
Result of server.HTTPListener(): 127.0.0.1:55073
go run main.go
Serving todo list at http://127.0.0.1:55092
Result of server.HTTPListener(): 127.0.0.1:55092
```
Although triggering the race is dependent on the timing of the code execution so results might vary by machine, but if run enough times it should produce a visible race. (In the test suite where I encountered this problem, because the code is quite different the race only occurs about 1 in 1000 runs on my machine.)

## Proposed resolutions

In order of difficulty:

* Delete these functions as they do not seem to be used anywhere in the framework itself
* Spin on the condition variable (`s.hasListeners`) and don't call `s.Listen()` from the `_____Listener()`
  e.g: 
    ```
    func (s *Server) InMemoryListener() (*bufconn.Listener, error) {
        for !s.hasListeners {
            time.Sleep(1 * time.Millisecond)
        }
        return s.inMemoryL, nil
    }
   ```
* Add appropriate locking to ensure that s.Listen() is not called twice

## Environment
swagger version: head (although templates are from an older version, but the code in question looks identical)
go version: go version go1.8.7 darwin/amd64
OS:   macOS High Sierra 10.13.3 (17D47)

**Comment by casualjim** [comment]
we can wrap those in a sync.Once

**Comment by fredbi** [comment]
This particular race condition should no more occur with more recent servers. This mechanism has been largely revisited since.
