### ISSUE TITLE
Tag generated files for code review

### ISSUE THREAD

**Issue by wuqiany2** [go-swagger/go-swagger#1466]
Currently the generated go files are tagged with `// Code generated by go-swagger; DO NOT EDIT` at the beginning.

I want to put the files up along with my changes for code review on Phabricator. It looks like Arcanist only recognizes `@generated` somewhere in the file to fold it in the review.

I am wondering if there is a way that I could put some customized comments at the beginning of each generated file? such as the `@generated` tag.

**Comment by gregmarr** [comment]
That's too bad, as this follows the Go convention for generated files.

**Comment by fredbi** [comment]
You can embed anything you want in the copyright which is rendered as a /* */ comment

**Comment by wuqiany2** [comment]
Awesome, I just found out this trick too, giving it copyright file.
