### ISSUE TITLE
Generated validation method miss some fields

### ISSUE THREAD

**Issue by zhuangqh** [go-swagger/go-swagger#1479]
## Problem statement

Using go-swagger to generate models. However, it miss some fields in `Validate` method. Is this a feature or bug?

Type `ContainerCreateConfig` includes `HostConfig` and `NetworkingConfig`.
```YAML
 ContainerCreateConfig:
    description: | 
      ...
    allOf:
      - $ref: "#/definitions/ContainerConfig"
      - type: "object"
        properties:
          HostConfig:
            $ref: "#/definitions/HostConfig"
          NetworkingConfig:
            $ref: "#/definitions/NetworkingConfig"
```
Generated code
```Go
type ContainerCreateConfig struct {
	ContainerConfig

	// host config
	HostConfig *HostConfig `json:"HostConfig,omitempty"`

	// networking config
	NetworkingConfig *NetworkingConfig `json:"NetworkingConfig,omitempty"`
}
```
```Go
// Validate validates this container create config
func (m *ContainerCreateConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ContainerConfig.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkingConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```
In my expectation, there should be some code like 
```Go
	if err := m.validateHostConfig(formats); err != nil {
		res = append(res, err)
	}
```
in func `Validate` to validate the `HostConfig` field.

## Swagger specification
Detailed files: [swagger.yaml](https://github.com/alibaba/pouch/blob/master/apis/swagger.yml), [generated code](https://github.com/alibaba/pouch/blob/master/apis/types/container_create_config.go)

## Environment
swagger version: 0.12
go version: 1.9.5
OS:   linux

**Comment by fredbi** [comment]
Looks like a bug: for some reason, the generator lost track of the needed validations for your HostConfig.
My guess would be that the nested allOf is the culprit, but we need more analysis on this.

Just to narrow down the case, does it help if you declare HostConfig as a required property?

**Comment by zhuangqh** [comment]
Thanks a lot for your reply. I got the expected code after declare HostConfig as a required property. @fredbi

**Comment by fredbi** [comment]
yes it is a bug. And now we now were it is: generator not bubbling up the HasValidations flag when property is itself a non-required allOf...

**Comment by allencloud** [comment]
We are big fans of swagger, and we met the same issue above.  And to  be honest, we still missing the validation part in our API server. It is indeed a weak place in our software. 
Look forward to a way to fix it out. Thank you, my friend. 🍻

**Comment by fredbi** [comment]
Validation has been much improved since v0.13, but there is still some work to be done.
All contributions are welcome.

**Comment by fredbi** [comment]
@zhuangqh shoud work now with current master (not 0.12...).
Tested it with both flatten and expand mode (the --skip-flatten).

Studying validation with your testcase did uncover a new bug with enums in nested allOf, specifically when one use --skip-flatten. I am taking care of this one for the upcoming work on enums.
