### ISSUE TITLE
Missing strfmt import

### ISSUE THREAD

**Issue by adamflott** [go-swagger/go-swagger#1480]
## Problem statement

Generated responses code has a missing import statement for 

       strfmt "github.com/go-openapi/strfmt"

When used in a type like:

        XRateLimitReset strfmt.DateTime `json:"X-Rate-Limit-Reset"`

## Swagger specification

    swagger: "2.0"

    consumes:
    - application/json
    produces:
    - application/json

    info:
      title: importbug
      description: ...
      version: 0.0.1

    schemes:
    - http

    parameters:
      requestId:
        name: X-Request-Id
        description: A unique UUID for the request
        in: header
        type: string
        required: false
        minLength: 1
      urlPurgeBody:
        name: body
        in: body
        schema:
          $ref: "#/definitions/urlPurgeData"
      tagPurgeBody:
        name: body
        in: body
        schema:
          $ref: "#/definitions/tagPurgeData"
      cpcodePurgeBody:
        name: body
        in: body
        schema:
          $ref: "#/definitions/cpcodePurgeData"
      purgeType:
        name: purgetype
        description: ...
        in: path
        type: string
        required: true
        minLength: 1
        enum:
          - delete
          - invalidate
      purgeClient:
        name: purgeclient
        description: ...
        in: path
        type: string
        required: true
        minLength: 1
        enum:
          - a
          - b
          - c
          - d
      purgeEnvironment:
        name: purgeenvironment
        description: Enumerate supported Purge environments
        in: path
        type: string
        required: true
        minLength: 1
        enum:
          - staging
          - production

    paths:
      /{purgeclient}/v3/{purgetype}/url:
        post:
          tags:
            - Purge
          operationId: v3Url
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/urlPurgeBody"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

      /{purgeclient}/v3/{purgetype}/url/{purgeenvironment}:
        post:
          tags:
            - Purge
          operationId: v3UrlWithEnv
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/urlPurgeBody"
            - $ref: "#/parameters/purgeEnvironment"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

      /{purgeclient}/v3/{purgetype}/tag:
        post:
          tags:
            - Purge
          operationId: v3Tag
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/tagPurgeBody"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

      /{purgeclient}/v3/{purgetype}/tag/{purgeenvironment}:
        post:
          tags:
            - Purge
          operationId: v3TagWithEnv
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/tagPurgeBody"
            - $ref: "#/parameters/purgeEnvironment"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

      /{purgeclient}/v3/{purgetype}/cpcode:
        post:
          tags:
            - Purge
          operationId: v3CPCode
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/cpcodePurgeBody"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

      /{purgeclient}/v3/{purgetype}/cpcode/{purgeenvironment}:
        post:
          tags:
            - Purge
          operationId: v3CPCodeWithEnv
          parameters:
            - $ref: "#/parameters/requestId"
            - $ref: "#/parameters/purgeType"
            - $ref: "#/parameters/purgeClient"
            - $ref: "#/parameters/cpcodePurgeBody"
            - $ref: "#/parameters/purgeEnvironment"
          responses:
            201:
              $ref: '#/responses/Standard201Response'
            403:
              $ref: '#/responses/Standard403Response'
            429:
              $ref: '#/responses/Standard429Response'
            507:
              $ref: '#/responses/Standard507Response'
            default:
              $ref: '#/responses/StandardErrorResponse'

    definitions:
      error:
        description: |
          ...
        type: object
        required:
          - message
          - code
        properties:
          code:
            type: integer
            format: int64
            description: The error code
          message:
            description: The error message
            type: string
          helpUrl:
            description: ...
            type: string
            format: uri
          cause:
            $ref: '#/definitions/error'

      urlPurgeData:
        description: |
         ...
        type: object
        required:
          - objects
        properties:
          objects:
            type: array
            items:
              type: string
              minLength: 1
          hostname:
            type: string
            minLength: 1

      cpcodePurgeData:
        description: |
          ...
        type: object
        required:
          - objects
        properties:
          objects:
            type: array
            items:
              minLength: 1

      tagPurgeData:
        description: |
          ...
        type: object
        required:
          - objects
        properties:
          objects:
            type: array
            items:
              type: string
              minLength: 1

      purgeError:
        type: object
        required:
          - message
        properties:
          code:
            type: integer
            format: int64
          message:
            type: string

      purgeResponse:
        type: object
        required:
          - detail
          - httpStatus
          - supportId
        properties:
          describedBy:
            type: string
            readOnly: true
          detail:
            type: string
            readOnly: true
          estimatedSeconds:
            type: integer
            format: int32
            readOnly: true
          httpStatus:
            type: integer
            format: int32
            readOnly: true
          purgeId:
            type: string
            format: uuid4
            readOnly: true
          supportId:
            type: string
            format: uuid4
            readOnly: true
          title:
            type: string
            readOnly: true

    responses:
      Standard201Response:
        description: Purge Success
        headers:
          X-Rate-Limit-Remaining:
            type: integer
          X-Rate-Limit-Reset:
            type: string
            format: date-time
          X-Request-Id:
            description: The request id this is a response to
            type: string
          X-Support-Id:
            description: The support id this is a response to
            type: string
        schema:
          $ref: "#/definitions/purgeResponse"
      Standard403Response:
        description: Unauthorized
        headers:
          X-Rate-Limit-Remaining:
            type: integer
          X-Rate-Limit-Reset:
            type: string
            format: date-time
          X-Request-Id:
            description: The request id this is a response to
            type: string
          X-Support-Id:
            description: The support id this is a response to
            type: string
        schema:
          $ref: "#/definitions/purgeResponse"
      Standard429Response:
        description: Rate Limited
        headers:
          X-Rate-Limit-Remaining:
            type: integer
          X-Rate-Limit-Reset:
            type: string
            format: date-time
          X-Request-Id:
            description: The request id this is a response to
            type: string
          X-Support-Id:
            description: The support id this is a response to
            type: string
        schema:
          $ref: "#/definitions/purgeResponse"
      Standard507Response:
        description: Queue Full
        headers:
          X-Rate-Limit-Remaining:
            type: integer
          X-Rate-Limit-Reset:
            type: string
            format: date-time
          X-Request-Id:
            description: The request id this is a response to
            type: string
          X-Support-Id:
            description: The support id this is a response to
            type: string
        schema:
          $ref: "#/definitions/purgeResponse"
      StandardErrorResponse:
        description: Error
        headers:
          X-Rate-Limit-Remaining:
            type: integer
          X-Rate-Limit-Reset:
            type: string
            format: date-time
          X-Request-Id:
            description: The request id this is a response to
            type: string
          X-Support-Id:
            description: The support id this is a response to
            type: string
        schema:
          $ref: "#/definitions/error"

## Steps to reproduce

    $ export GOPATH=`pwd`
    $ go get -u github.com/go-swagger/go-swagger/cmd/swagger
    $ mkdir -p src/gen
    $ ./bin/swagger generate server -A gopurge --default-scheme=https -t src/gen swagger.yml
    $ # go get deps..
    $ go run src/gen/cmd/gopurge-server/main.go
    # gen/restapi/operations/purge
    src/gen/restapi/operations/purge/v3_c_p_code_responses.go:32:18: undefined: strfmt

## Environment
swagger version:  acd311c72
go version: go version go1.10.1 linux/amd64
OS:   Ubuntu 16.04.4 LTS

**Comment by casualjim** [comment]
Can you get the dependencies  and then regenerate? We use goimports to find these packages so if they exist on the FS then the imports will be present too. You should be able to get list you need from the message that is printed at the end of the generation step.

**Comment by adamflott** [comment]
Note: there's nothing in my ~/go

I ran:

    $ go get github.com/go-openapi/errors github.com/go-openapi/loads
    $ go get github.com/go-openapi/runtime github.com/go-openapi/runtime/flagext github.com/go-openapi/runtime/middleware github.com/go-openapi/runtime/security github.com/go-openapi/validate github.com/jessevdk/go-flags github.com/tylerb/graceful

If I re-generate it appears to fix the problem:

    $ ./bin/swagger generate server -A gopurge --default-scheme=https -t src/gen swagger.yml
    ...
    $ go run src/gen/cmd/gopurge-server/main.go
    2018/04/16 12:06:49 Serving gopurge at http://127.0.0.1:45421

**Comment by adamflott** [comment]
I guess it's working as intended but caught me by surprise. Maybe a note in the installation instructions would be helpful

**Comment by ssosik** [comment]
Hi @casualjim, @fredbi - here's a simple way to reproduce the problem that Adam reported:

```bash
mkdir test && cd test
mkdir -p src/gen
export GOPATH=`pwd`

# Write swagger.yml based on contents below:
cat swagger.yml
```
```yaml
swagger: "2.0"

consumes:
- application/json
produces:
- application/json

info:
  title: testthing
  description: testthing
  version: 0.0.1

schemes:
- http

paths:
  /foo:
    post:
      tags:
        - Bar
      operationId: fooBar
      responses:
        429:
          $ref: '#/responses/RateLimitedResp'

responses:
  RateLimitedResp:
    description: Rate Limited
    headers:
      X-Rate-Limit-Reset:
        type: string
        format: date-time
    schema:
      $ref: "#/definitions/responseBody"

definitions:
  responseBody:
    type: object
    required:
      - httpStatus
    properties:
      httpStatus:
        type: integer
        format: int32
        readOnly: true
```
```bash
latestv=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | jq -r .tag_name)
curl -o swagger -L'#' https://github.com/go-swagger/go-swagger/releases/download/$latestv/swagger_$(echo `uname`|tr '[:upper:]' '[:lower:]')_amd64
chmod +x swagger

./swagger generate server -A testhing -t src/gen swagger.yml

pushd . && cd src/gen/ && dep init && popd  # Pull down dependencies

go run src/gen/cmd/testhing-server/main.go
# # gen/restapi/operations/bar
# src/gen/restapi/operations/bar/foo_bar_responses.go:27:18: undefined: strfmt
head -n 30 src/gen/restapi/operations/bar/foo_bar_responses.go
```

```golang
// Code generated by go-swagger; DO NOT EDIT.

package bar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gen/models"
)

// FooBarTooManyRequestsCode is the HTTP code returned for type FooBarTooManyRequests
const FooBarTooManyRequestsCode int = 429

/*FooBarTooManyRequests Rate Limited

swagger:response fooBarTooManyRequests
*/
type FooBarTooManyRequests struct {
	/*

	 */
	XRateLimitReset strfmt.DateTime `json:"X-Rate-Limit-Reset"` // <-- strftime used but not imported

	/*
	  In: Body
```

My conclusion: the `date-time` format under the `X-Rate-Limit-Reset` Response header isn't correctly triggering the import of `github.com/go-openapi/strfmt`. This dependency *is* correctly being pulled down by the `dep` invocation.

Please let me know if I'm missing something, or if there's a known work around.

Thanks!

**Comment by casualjim** [comment]
haven't tried this yet, but can you regenerate after you've done `dep init`

**Comment by ssosik** [comment]
Thanks for the prompt reply. I get the same behavior:

```bash
# ...
pushd . && cd src/gen/ && dep init && popd  # Pull down dependencies

./swagger generate server -A testhing -t src/gen swagger.yml

go run src/gen/cmd/testhing-server/main.go

# # gen/restapi/operations/bar
# src/gen/restapi/operations/bar/foo_bar_responses.go:27:18: undefined: strfmt
```

**Comment by ssosik** [comment]
Ah, now I see. Thanks. Kind of curious that goimports cannot find the stuff that `dep` pulled in, but using `go get github.com/go-openapi/strfmt` resolved it.
