### ISSUE TITLE
contributing guidelines lack development instructions

### ISSUE THREAD

**Issue by ags799** [go-swagger/go-swagger#1484]
The [contributing guidelines](https://github.com/go-swagger/go-swagger/blob/master/.github/CONTRIBUTING.md) don't give a lot of guidance for building or testing the project.

I've tried running some make commands on a fresh checkout and get a lot of errors
```bash
$ make generate
make: *** No rule to make target `build/image_build', needed by `generate'.  Stop.

$ make test
...
cmd/swagger/commands/generate/shared.go:61::warning: declaration of "err" shadows declaration at cmd/swagger/commands/generate/shared.go:46 (vetshadow)
cmd/swagger/commands/generate/shared.go:67::warning: declaration of "err" shadows declaration at cmd/swagger/commands/generate/shared.go:46 (vetshadow)
cmd/swagger/swagger.go:133::warning: Expect file permissions to be 0600 or less,MEDIUM,HIGH (gas)
cmd/swagger/commands/generate/model_test.go:37:22:warning: error return value not checked (defer os.RemoveAll(generated)) (errcheck)
cmd/swagger/commands/generate/model_test.go:39:15:warning: error return value not checked (flags.Parse(m)) (errcheck)
cmd/swagger/commands/generate/shared.go:26:2:warning: unused struct field github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.shared.genOpts (structcheck)
cmd/swagger/swagger.go:32:1:warning: Debug is unused (deadcode)
cmd/swagger/commands/generate/shared.go:26:2:warning: field genOpts is unused (U1000) (megacheck)
cmd/swagger/swagger.go:34:2:warning: var Debug is unused (U1000) (megacheck)
```

Some "getting started" section with a few bash commands would help. You could even just link to CI's build instructions.

**Comment by casualjim** [comment]
there is nothing special about the development process. I'll delete the makefiles, because we dont' actually use them.

test everything: ```go test ./...````

**Comment by ags799** [comment]
removing the makefiles is a great idea. you could also just point to the CI config to show what tests must pass. that would be concise & comprehensive. a developer could find their own shortcuts from there.

**Comment by ags799** [comment]
i made progress once i stopped using the makefiles and referred to the CI config instead
