### ISSUE TITLE
Breaking change in Authenticator runtime

### ISSUE THREAD

**Issue by randomjunk** [go-swagger/go-swagger#1488]
## Problem statement

The change made here:
https://github.com/go-openapi/runtime/commit/1c997f7e69df84d5c13222f6491841512b5f45ea#diff-eef43dc654e386051f4d5eb386f3bae4R420

This creates a breaking change in the response from an authenticator response.

### Old behaviour
Previously the error returned from the Authenticator is used to form the response. ie: return an `errors.New(http.StatusUnauthorized, "specific reason")` you get back a 401 with `specific reason`.
We have an authenticator that does this to return error codes.
We also have an authenticator that uses the scopes to give a 403 response instead.

### New behaviour
With the new code absolutely everything returns 401 `invalid credentials` instead.

## Fix

The code should return the error returned from the Authenticator rather than creating a new one

**Comment by fredbi** [comment]
I noticed that during my testing PR #1481 but did not enough attention to it...
