### ISSUE TITLE
Add a diff command

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#151]
Add a diff command that can be used to inspect differences between 2 swagger specs.

https://github.com/civisanalytics/swagger-diff

**Comment by GlenDC** [comment]
Is this still a wish of yours @casualjim ?

**Comment by casualjim** [comment]
yes it is of great interest to me

**Comment by wjase** [comment]
I've got a pull request about to go which implements a diff and a backwards compatability check. I was about to raise an issue when I saw this one.
