### ISSUE TITLE
Spec generation doesn't honour the ",string" JSON struct tag

### ISSUE THREAD

**Issue by neilgarb** [go-swagger/go-swagger#1510]
## Problem statement

I have a field in a response struct which specifies that it's encoded as a string when marshalled to JSON.

```go
// swagger:model
type Foo struct {
    Bar int64 `json:"bar,string"`
}
```

When I generate the spec for Foo, the type of Bar is integer, when it should in fact be string.

## Proposed solution

In parseJSONTag(), also return a boolean indicating that the field has the ",string" directive. When the field's type is determined, override it with type:string and format:<original type> if the directive is present.

## Swagger specification

2.0

## Steps to reproduce

N/A

## Environment
swagger version: 2.0
go version: 1.10.1
OS:  macOS 10.12.6

**Comment by casualjim** [comment]
fixed by #1511
