### ISSUE TITLE
Client parameters don't set body when model is an enum

### ISSUE THREAD

**Issue by stevecookform3** [go-swagger/go-swagger#1513]
## Problem statement

If the client body is an enum, the body doesnt get serialised by WriteToRequest.

## Swagger specification

```yaml
swagger: '2.0'
info:
  version: "1.0.0"
  title: "Test enum serialisation"
paths:

  /example:
    put:
      parameters:
      - name: "something"
        in: "body"
        description: "PUT enum example"
        required: true
        schema:
          $ref: '#/definitions/MyEnum'
      responses:
        202:
          description: "PUT OK"
        500:
          description: "Error"

definitions:

  MyEnum:
    type: "string"
    enum:
    - SOMEVALUE
    - SOMEOTHERVALUE
```

## Steps to reproduce

`swagger generate client -f ./swagger.yaml`

Note that put_example_responses.WriteToRequest() never calls r.SetBodyParam().

## Environment
swagger version: master
go version: 1.10.2 
OS:  osx

## Fix
Looks like the following in the template needs to include enums:
```
  {{ if or .Schema.IsInterface .Schema.IsStream (and .Schema.IsArray .Child) (and .Schema.IsNullable (not .HasDiscriminator)) }}if {{ .ValueExpression }} != nil {
```

**Comment by stevecookform3** [comment]
Looks related to #1490

**Comment by fredbi** [comment]
OK the issue looks like it is [here](https://github.com/go-swagger/go-swagger/blob/dba9799b3ee5a7aeb9f7515449b6f6b4d915d942/generator/templates/client/parameter.gotmpl#L238).

I have not tinkered with the client so far, but it looks to me that it is more a matter of properly nesting the `{{ if ... }}` guarding the null param to `SetBodyParam(...)` than adding more and more stuff there.

Something like this don't you think?
```
{{- if .IsBodyParam}}
  {{- if or .Schema.IsInterface .Schema.IsStream (and .Schema.IsArray .Child) (and .Schema.IsMap .Child) (and .Schema.IsNullable (not .HasDiscriminator)) }}
    if {{ .ValueExpression }} != nil {
  {{- end }}
    if err := r.SetBodyParam({{ .ValueExpression }}); err != nil {
      return err
    }
  {{- if or .Schema.IsInterface .Schema.IsStream (and .Schema.IsArray .Child) (and .Schema.IsMap .Child) (and .Schema.IsNullable (not .HasDiscriminator)) }}
  }
  {{- end }}
}
{{- end }}
```

**Comment by stevecookform3** [comment]
@fredbi great - that seems to fix it for me. PR here: https://github.com/go-swagger/go-swagger/pull/1514
