### ISSUE TITLE
fail to use swagger generate  model  -name

### ISSUE THREAD

**Issue by fwhezfwhez** [go-swagger/go-swagger#1517]
## Problem statement

Hello,I met a problem when I tried to rename the filename of the auto-generated model.
How I use ways below :
1. swagger generate model -m ./models/vo  --name Person
unknown models: Person
2. swagger generate model -m ./models/vo  -name Person
unknown models: ame
3. swagger generate model -m ./models/vo  -name= Person
unknown models: ame=

By the way,here is the source swagger.json:
```json
{
  "swagger": "2.0",
   "info": {
        "version": "1.0.0",
        "title": "Simple API",
        "description": "A simple API to learn how to write OpenAPI Specification"
    },
   "schemes": [
        "http"
    ],
  "paths": {
      "/persons":{
	      "get":{
		      "summary":"获取一些目标person",
			  "description": "Returns a list containing all persons.",
			  "responses": {
                    "200": {
                        "description": "A list of Person",
                        "schema": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "firstName": {
                                        "type": "string"
                                    },
                                    "lastName": {
                                        "type": "string"
                                    },
                                    "username": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
		  }  
	}
  }
}
```json
## Environment
swagger version: 2.0
go version: 1.10
OS:   win10 64

**Comment by casualjim** [comment]
you need to make it available with that name in the definitions section then it will know

**Comment by fwhezfwhez** [comment]
3q,to change the filename and model name through  xxx.yml:

**Comment by fwhezfwhez** [comment]
When adds  new model to existed project above ,I do so:

**Comment by casualjim** [comment]
you can just edit the existing spec and regenerate, it's safe to regenerate, the pre-existing files should be identical

**Comment by fwhezfwhez** [comment]
3q so much!
here when I generate the client for this project,I can't find package 'myproject/client/operation' this ,and thus make 'resp, err := client.Operations.All(operations.AllParams{})'  'Operations'  unresolved,
the auto generating result is like:
-------------------
myproject
-client
  -myproject
     ->myproject_client.go
------------------
To use this,I add a main package  then project becomes
-------------------
myproject
-client
  -main
     ->main.go
  -myproject
     ->myproject_client.go
-------------------
and in main.go 
```
package main

import (
	"os"
	"log"

	"test_swagger/client/operations"
	"github.com/go-openapi/strfmt"
	//"github.com/go-openapi/spec"

	apiclient "test_swagger/client"
	httptransport "github.com/go-openapi/runtime/client"
	"fmt"
)

func main() {

	// create the transport
	transport := httptransport.New(os.Getenv("TODOLIST_HOST"), "", nil)

	// create the API client, with the transport
	client := apiclient.New(transport, strfmt.Default)

	// to override the host for the default client
	// apiclient.Default.SetTransport(transport)

	// make the request to get all items
	resp, err := client.Operations.All(operations.AllParams{})     //**Operations unresolved,how to deal**
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v\n", resp.Payload)

```

**Comment by casualjim** [comment]
is test_swagger in your $GOPATH/src ?

**Comment by fwhezfwhez** [comment]
yes,it is in my gopath
I regenerate it and successfully get its Operations,however method All() and All(operations.AllParams{}) unresolved,is this part designed by ourselves. If it is ,how to design,is there any simple examples?

Another issue is that,Swagger doc [https://goswagger.io/tutorial/custom-server.html] example doesn't include 'import part', some variagble I can't refer its resource .IDE is goland
```go
	// TODO: Set Handle
	api.GetGreetingHandler = operations.GetGreetingHandlerFunc(
		func(params operations.GetGreetingParams) middleware.Responder {
			name := swag.StringValue(params.Name)      //*what this 'swag'' stands for**
			if name == "" {
				name = "World"
			}

			greeting := fmt.Sprintf("Hello, %s!", name)
			return operations.NewGetGreetingOK().WithPayload(greeting)
		})

```

**Comment by fwhezfwhez** [comment]
yes,it is in my gopath
I regenerate it and successfully get its Operations,however method All() and All(operations.AllParams{}) unresolved,is this part designed by ourselves. If it is ,how to design,is there any simple examples?

Another issue is that,Swagger doc [https://goswagger.io/tutorial/custom-server.html] example doesn't include 'import part', some variagble I can't refer its resource .IDE is goland
```go
	// TODO: Set Handle
	api.GetGreetingHandler = operations.GetGreetingHandlerFunc(
		func(params operations.GetGreetingParams) middleware.Responder {
			name := swag.StringValue(params.Name)      //*what this 'swag'' stands for**
			if name == "" {
				name = "World"
			}

			greeting := fmt.Sprintf("Hello, %s!", name)
			return operations.NewGetGreetingOK().WithPayload(greeting)
		})

```

**Comment by casualjim** [comment]
There is a completed example here, which compiles: https://github.com/go-swagger/go-swagger/tree/master/examples/tutorials/custom-server
