### ISSUE TITLE
Validating a Standard spec

### ISSUE THREAD

**Issue by damianoneill** [go-swagger/go-swagger#1522]
## Problem statement
I was using go-swagger to validate the spec defined below.   When I run the validate cmd I get the following problem output, I'm unsure how to identify where in the file the problems exists, is there additional flags that can be passed to see debug output?  

From looking at the standard page below for the swagger definition, the implication is that this has been validated by other tools. 

## Swagger specification
https://raw.githubusercontent.com/OpenNetworkingFoundation/TAPI/develop/SWAGGER/tapi-connectivity%402018-02-16.swagger 

## Steps to reproduce
$ swagger validate ./tapi-connectivity@2018-02-16.swagger
2018/05/10 21:21:59 invalid character '}' after top-level value

## Environment
swagger version: 0.13.0 
go1.10 darwin/amd64

**Comment by fredbi** [comment]
set the SWAGGER_DEBUG variable to get a debug output

**Comment by damianoneill** [comment]
thanks @fredbi but the variable doesnt seem to add anything. 

```
$ env | grep SW
SWAGGER_DEBUG=1

$ swagger validate ./tapi-connectivity@2018-02-16.swagger
2018/05/10 21:41:31 invalid character '}' after top-level value
```

**Comment by casualjim** [comment]
what I do to debug this is, I install the swagger-tools npm package and use that to validate the doc. It will tell you which line number. For us that information is lost in the go stdlib tooling.

**Comment by casualjim** [comment]
in your case that results in:
```
$ swagger-tools validate https://raw.githubusercontent.com/OpenNetworkingFoundation/TAPI/develop/SWAGGER/tapi-connectivity%402018-02-16.swagger

  error: end of the stream or a document separator is expected at line 16987, column 1:
    }
    ^
```

**Comment by casualjim** [comment]
anohter easy trick for seeing json parse errors is:

```
$ curl -sL https://raw.githubusercontent.com/OpenNetworkingFoundation/TAPI/develop/SWAGGER/tapi-connectivity%402018-02-16.swagger | jq
```

**Comment by damianoneill** [comment]
Thanks @casualjim the last suggestion is great.   Guys thanks for the quick responses.   Will followup with the Standard repo.

**Comment by gregmarr** [comment]
Looks like line 16986 is a duplicate of 16985

**Comment by damianoneill** [comment]
@gregmarr thanks.  Removing the line resolves the validation.
