### ISSUE TITLE
Path parameter with request body

### ISSUE THREAD

**Issue by ribice** [go-swagger/go-swagger#1523]
Request body is not shown with following spec. What am I doing wrong?

```yaml
// swagger:operation PATCH /v1/users/{id} users userUpdate
// ---
// summary: Updates user's contact information
// description: Updates user's contact information -> first name, last name, mobile, phone, address.
// parameters:
// - name: id
//   in: path
//   description: id of user
//   type: int
//   required: true
// - name: request
//   in: body
//   description: Request body
//   required: true
//   schema:
//     "$ref": "#/definitions/UserUpdate"
// responses:
//   "200":
//     "$ref": "#/responses/userResp"
```

RequestBody is empty.

![image](https://user-images.githubusercontent.com/5403700/39929483-783e8fa6-5538-11e8-9754-a4e4b8ecc251.png)

Just downloaded go-swagger using go-get.

**Comment by ElMaxo** [comment]
How is your model defined?
This works perfectly:
```
// Create area request
// swagger:model createAreaRequest
type createAreaRequest struct {
	Name string
	ControllerID uint
}
```
```
And annotation to operation:
// swagger:operation POST /areas Areas areas
// ---
// summary: Create new area
// description: Creates new area with specified parameters
// parameters:
// - name: area
//   in: body
//   description: area parameters
//   schema:
//     "$ref": "#/definitions/createAreaRequest"
//   required: true
// responses:
//   "200":
//     "$ref": "#/responses/areaResponse"
//   "400":
//     "$ref": "#/responses/badRequestError"
```
![screenshot from 2018-09-03 15-54-00](https://user-images.githubusercontent.com/5655525/44988036-f926fa00-af91-11e8-9107-6f33f308155d.png)

**Comment by ribice** [comment]
Can you adding another parameter, e.g. `id` from my example?

**Comment by ElMaxo** [comment]
It works too. Just added id from your example
```
// - name: id
//   in: path
//   description: id of user
//   type: int
//   required: true
```
Before pressing Try it out button
![screenshot from 2018-09-03 20-51-33](https://user-images.githubusercontent.com/5655525/44998114-ba0d9e80-afbb-11e8-9041-9bc95aac777b.png)
![screenshot from 2018-09-03 20-51-39](https://user-images.githubusercontent.com/5655525/44998115-ba0d9e80-afbb-11e8-83eb-dc047f53d346.png)
After Try it out button pressed (fields are displayed), example model value is in body field, but changing to model structure view is not available until you press Cancel, it is normal, as far as i know
![screenshot from 2018-09-03 20-52-00](https://user-images.githubusercontent.com/5655525/44998116-ba0d9e80-afbb-11e8-82b2-b49cb019107d.png)

**Comment by ribice** [comment]
Now that I'm looking at it, I think I was using `swagger:parameters` instead of  `swagger:model` for this one.

Works as expected when using `swagger:model`. Thanks!

**Comment by vibhugarg123** [comment]
// swagger:route GET /theatre/{theatre-name} theatre getTheatresByNameRequest
// Get all the theatres with theatre-name
// Responses:
//	200: theatresByNameResponse
//  404: errorResponse
//  500: errorResponse
Here, after the url, theatre is the group and getTheatresByNameRequest is the custom annotation which is given below-
// swagger:parameters getTheatresByNameRequest
type theatresByNameWrapperRequest struct {
	// required: true
	// in: path
	theatreName string `json:"theatre-name"`
}
It works for POST but not GET.

**Comment by casualjim** [comment]
remove the newline between the comment and the type
