### ISSUE TITLE
Question: How to trim all model's strings before validation

### ISSUE THREAD

**Issue by BertrandGouny** [go-swagger/go-swagger#1530]
Hello,
i'm trying to find a way to trim all strings before the server validate the model, so the validation failed if the user set only white spaces in a string.

Any idea how to do that ?

**Comment by gregmarr** [comment]
Seems like you would need to add a pattern on each string, since even an empty string is enough to satisfy the required attribute.

**Comment by fredbi** [comment]
@BertrandGouny I had the very same issue and adopted what Greg is now saying:
` pattern: "^\\S.*\\S$"` 

Before that, I simply trimmed the parameter at the beginning of my operation, with `strings.TrimSpace()` and handled the error manually (e.g. sending back a 40x error etc...).

**Comment by fredbi** [comment]
My case was to avoid leading or trailing blanks, so your regexp would be different. But you see the idea.

**Comment by fredbi** [comment]
Perhaps something like ` '^.*\\S.*$'`  ... (_at least_ one non-blank)

**Comment by BertrandGouny** [comment]
Thanks you @gregmarr and @fredbi 
using a pattern will do the trick indeed  :+1: 

i ended up with something like `^(\S.*\S|\S)*$` to accept only trimmed strings and single non-whitespace char. 

Feel free to close this :)

**Comment by fredbi** [comment]
_you_ close it. That's the policy in this house, man... 👍
