### ISSUE TITLE
Allof with a polymorphic type can have conflicting field names 

### ISSUE THREAD

**Issue by callahanca** [go-swagger/go-swagger#1532]
## Problem statement

It appears that having a polymorphic type containing a field named "data" included in an allOf definition causes an issue in the generated code, specifically in the UnmarshalJSON function:

```
func (m *UpdateObjectAllOf1) UnmarshalJSON(raw []byte) error {
	var data struct { // <-- here, "data" is a struct
		Data json.RawMessage `json:"data,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	data, err := UnmarshalObject(bytes.NewBuffer(data.Data), runtime.JSONConsumer()) // <-- but here, UnmarshalObject returns something satisfying the "Object" interface, which the original "data" does not
```

I think this could be fixed by adding `Field` or something similar to the `{{ camelize .Name }}` here, if I'm understanding the code correctly: https://github.com/go-swagger/go-swagger/blob/master/generator/templates/tupleserializer.gotmpl#L102

## Swagger specification
```
definitions:
  Event:
    type: object
    discriminator: event
    properties:
      event:
        type: "string"
        enum:
          - update_object
          - delete
      id:
        type: string

    required:
      - event
      - id

  update_object:
    type: object
    allOf:
      - $ref: "#/definitions/Event"
      - type: object
        properties:
          data: # <--- This is what produces an issue
            $ref: "#/definitions/Object"

  Object:
    type: object
    discriminator: type
    properties:
      type:
        type: string
        enum:
          - Message
          - User
    required:
      - type

```

## Environment
swagger version: 6bc0267ab287a519ac9db319593ed5c0c32dce10
go version: 1.10
OS:   OS X 10.12

**Comment by fredbi** [comment]
Just to make sure (because I've specically made some recent fixes on the allOf unmarshaller recently): does it work when you remove the "discriminator" property (so the type becomes a regular allOf)?

**Comment by callahanca** [comment]
Correct, the issue does not appear if I remove the discriminator property.

**Comment by fredbi** [comment]
ouf.
I was sure I had fixed this issue for regular allOf...
Well, for discriminators I made sure old issues were fixed, but there certainly are more of them.

**Comment by fredbi** [comment]
There is a special unmarshaller template when we switch to discriminated.

**Comment by fredbi** [comment]
I fixed a similar issue for regular allOfs here: https://github.com/go-swagger/go-swagger/blob/c8a59d30b041b12eeda1e4b821d844ddc0e9ef98/generator/templates/tupleserializer.gotmpl#L220

I don't know why we call a special version of unmarshaller in the subtype case, but you can borrow from this if you want to bring in a fix.

**Comment by casualjim** [comment]
because it's filling up unexported properties and needs to compose a few things together
