### ISSUE TITLE
Body params that are Arrays of Objects generate un-compilable code due to Validate method

### ISSUE THREAD

**Issue by alaqelsplk** [go-swagger/go-swagger#1536]
## Problem statement
One of my API endpoints takes a body that is an array of objects. It looks like the body validation code added in https://github.com/go-swagger/go-swagger/pull/1444 does not arrays of objects, so the generated code tries to run Validate on a interface{}

restapi/operations/insert_records_parameters.go:144:21: recordsI.Validate undefined (type interface {} is interface with no methods)

## Swagger specification

        - name: records
          description: Array of records to insert
          in: body
          required: true
          schema:
            type: array
            items:
              type: object

## Steps to reproduce

Generate code && go run

## Environment
swagger version: latest master
go version: 1.10.2 
OS: mac os 10.13.4

**Comment by fredbi** [comment]
Yep, I thought I had tested this... Will fix this asap

**Comment by alaqelsplk** [comment]
Nope. The size validation gets addition to the method, but it still tries to loop through the array and call validate on the interface.

**Comment by alaqelsplk** [comment]
Here's what the generated code looks like when maxItems is added:

func (o *InsertRecordsParams) validateRecordsBody(formats strfmt.Registry) error {

	recordsSize := int64(len(o.Records))

	// maxItems: 10000
	if err := validate.MaxItems("records", "body", recordsSize, 10000); err != nil {
		return err
	}

	recordsIC := o.Records

	var recordsIR []interface{}
	for i, recordsIV := range recordsIC {
		recordsI := recordsIV
		if err := recordsI.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName(fmt.Sprintf("%s.%v", "records", i))
			}
			return err
		}

		recordsIR = append(recordsIR, recordsI)
	}

	o.Records = recordsIR
	return nil
}

**Comment by fredbi** [comment]
OK. I'll have a fix over the week end.

**Comment by fredbi** [comment]
ok fixed it in dev without visible regression. Now the tedious process of adding more UT for codegen...
I'll do that tomorow.
