### ISSUE TITLE
How to reorder the resources/endpoints ?

### ISSUE THREAD

**Issue by sonasingh46** [go-swagger/go-swagger#1543]
## Problem statement
![image](https://user-images.githubusercontent.com/24835120/40304513-a69d045c-5d14-11e8-9a9c-92f6719d579a.png)
In the above image , is there any way we can reorder , like first 'Volume ' should come and then 'Snapshots'
swagger version:dev
go version: 1.9.2
OS:  Ubuntu 16.04 LTS

**Comment by casualjim** [comment]
not possible, this is something you should solve in the UI client code itself

**Comment by sonasingh46** [comment]
Thanks
