### ISSUE TITLE
swagger:parameters won't generate in spec when inside a function

### ISSUE THREAD

**Issue by josephspurrier** [go-swagger/go-swagger#1545]
## Problem statement

If a swagger:parameters annotation and struct is inside of a function, then it is not picked up by the generator. This would be really helpful because they it would cut down on the naming of the structs and I could use the same `request` struct name in every function.

## Swagger specification

2.1

## Steps to reproduce

Create a function and put the swagger:parameters inside of it. When you perform a `swagger generate spec -o ./swagger.json`, the parameters for the endpoint will not be in the spec. If I move the annotation and the struct out of the function, it works fine.

```go
// Post .
// swagger:route POST /v1/game game GamePost
//
// Add the game to the database.
//
// Responses:
//   201: CreatedResponse
//   400: BadRequestResponse
//   401: UnauthorizedResponse
//   500: InternalServerErrorResponse
func (p *Game) Post(c echo.Context) (err error) {
	// swagger:parameters GamePost
	type request struct {
		// in: body
		Body struct {
			StartAt string   `json:"start_at" form:"start_at" validate:"required"`
			EndAt   string   `json:"end_at" form:"end_at" validate:"required"`
			Winners []string `json:"winners" form:"winners" validate:"required"`
		}
	}
	...        
}
```

## Environment
swagger version: dev
go version: go1.10.1 darwin/amd64
OS:   MacOSX

**Comment by josephspurrier** [comment]
It looks like this is because of parser.ParseFile() in util.go - it looks like the standard Go parser only uses objects in the package scope. Is there a reason why the generation only works when the are on objects in the package scope?

**Comment by casualjim** [comment]
no specific reason, feel free to extend that to your needs. We rarely reject PR's

**Comment by josephspurrier** [comment]
I was wrong, it didn't have anything to do with the standard Go parser, I just had to make changes to the Parse function for the parameters. There are still other cases that could be handled from this function, but for the time being, this should suffice. Thanks! Wonderful tool by the way - really awesome!
