### ISSUE TITLE
Schema rejects default without required properties followup

### ISSUE THREAD

**Issue by johnliu26** [go-swagger/go-swagger#1552]
## Problem statement
The issue related to the issue #1501. If we have the default for the firstName and lastName but we didn't set the username which is required. There will have a error message shown that I have to put the default for the required field "username" as well. The “default” section must contain any “required” properties, which is counterintuitive because the “required” properties should always be provided explicitly and shouldn’t have defaults. 

## Swagger specification
```yaml
paths:
  /person/{id}:
    put:
      summary: Put a person
      description: Put a person.
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of person
          required: true
          type: integer
        - in: body
          name: body
          description: Person
          schema:
            type: object
            required:
              - username
            default:
              firstName: John
              lastName: Smith
            properties:
              firstName:
                type: string
              lastName:
                type: string
              username:
                type: string
      responses:
        200:
          description: successful
```
## Steps to reproduce
**swagger generate model -f person.yaml**
I notice that the error message could be prevented if I use **swagger generate model --skip-validation**. But I think the error message should not show even I just use **swagger generate model -f person.yaml** because “required” properties should always be provided explicitly and shouldn’t have defaults. 

## Environment
swagger version: 0.13.0
go version: go1.10.2
OS: linux/amd64

**Comment by gregmarr** [comment]
Those defaults need to be put on the individual members. The default where you put it is a default for the entire object if it is not provided at all.  Thus it must pass validation of the object schema.

**Comment by fredbi** [comment]
As per swagger, defaults **MUST** validate their schema. This differs fro json-Schema spec.
