### ISSUE TITLE
Deadlock when TLS certificate is missing

### ISSUE THREAD

**Issue by sidh** [go-swagger/go-swagger#1558]
## Problem statement
Server deadlocks when TLS ceretificate is missing. Deadlock happens at this line - https://github.com/go-swagger/go-swagger/blob/25e637c5028dee7baf8cdf5d172ccb28cb8e5c3e/generator/templates/server/server.gotmpl#L391

There is no error check when doing certificate load and parsing - https://github.com/go-swagger/go-swagger/blob/25e637c5028dee7baf8cdf5d172ccb28cb8e5c3e/generator/templates/server/server.gotmpl#L376

Adding error check that returns err solves the problem.

## Steps to reproduce
Run server with --tls-certificate pointing to non-existant file.

**Comment by fredbi** [comment]
Looks very similar to #1473

**Comment by krehl** [comment]
Same issue when the file is password protected.
