### ISSUE TITLE
Broken code is generated with --skip-flatten

### ISSUE THREAD

**Issue by akhobov** [go-swagger/go-swagger#1559]
## Problem statement

It seems swagger version 0.14 has an issue in the server and client code generation if --skip-flatten parameter is used. It generates models but those models are not used in the responses. Instead there is an attempt to refer the models namespace but with a struct name that doesn't exist in there. There is a struct defined under that name in restapi/operations/.../directory.

After code is generated using the spec bellow take a look at the following files:
restapi/operations/object/get_objects_responses.go
restapi/operations/object/get_objects.go

The first file has the following code:
```
/*GetObjectsOK Objects

swagger:response getObjectsOK
*/
type GetObjectsOK struct {

    /*
      In: Body
    */
    Payload []*models.GetObjectsOKBodyItems0 `json:"body,omitempty"`
}
```

The second one has declaration of GetObjectsOKBodyItems0:
```
// GetObjectsOKBodyItems0 get objects o k body items0
// swagger:model GetObjectsOKBodyItems0
type GetObjectsOKBodyItems0 struct {

    // Object description.
    // Required: true
    Description *string `json:"description"`

    // Object ID
    // Read Only: true
    // Format: uuid4
    ID strfmt.UUID4 `json:"id,omitempty"`

    // Object name.
    // Read Only: true
    Name string `json:"name,omitempty"`
}
```

The models/object.go file was also created but I don't see where that package is used in the generated code. The content of the Object struct from that file basically a duplicate of GetObjectsOKBodyItems0:
```
// Object object
// swagger:model Object
type Object struct {

    // Object description.
    // Required: true
    Description *string `json:"description"`

    // Object ID
    // Read Only: true
    // Format: uuid4
    ID strfmt.UUID4 `json:"id,omitempty"`

    // Object name.
    // Read Only: true
    Name string `json:"name,omitempty"`
}
```
 
## Swagger specification
```
swagger: "2.0"
info:
  title: Test API
  description: Proof of bug Test API
  version: 2.0.0
schemes:
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  "/objects":
    get:
      summary: Objects
      description: Returns list of all objects
      operationId: getObjects
      tags:
        - Object
      responses:
        "200":
          description: Objects
          schema:
            type: array
            items:
              $ref: "#/definitions/Object"
        default:
          $ref: "#/responses/default"
  "/objects/{id}":
    parameters:
      - name: id
        description: Object ID.
        in: path
        required: true
        type: string
        format: uuid4
    get:
      summary: Object details
      description: Returns object identified by the provided ID.
      operationId: getObjectById
      tags:
        - Object
      responses:
        "200":
          description: Object details
          schema:
            $ref: "#/definitions/Object"
        default:
          $ref: "#/responses/default"
responses:
  default:
    description: Unexpected error
    schema:
      $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
      moreInfo:
        type: string
  Object:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        format: uuid4
        description: Object ID
        readOnly: true
      name:
        type: string
        description: Object name.
        readOnly: true
        x-nullable: false
      description:
        type: string
        x-nullable: true
        description: Object description.
```

## Steps to reproduce
swagger generate server --target ./ -name test --spec swagger.yaml --skip-flatten

## Environment
swagger version: 0.14.0  
go version: 1.10.2  
OS:   Linux

**Comment by akhobov** [comment]
Thanks for looking into this!

The --skip-flatten is useful if the generated models reflect the definition of models as described in swagger spec. Thus if model composition is used in swagger it would be quite easily mapped to the go structures as the same model can be used in multiple endpoints with different synopsis.

If that option starts to "expand all" that convenience would be lost and developers would have to work with unique structures that cannot be easily converted into each other. Effectively that means that if the --skip-flatten option is used then no models should be generated and all parameter/response structures are defined in restapi/operations/... directory. Does that describe the new logic behind the --skip-flatten option?

**Comment by akhobov** [comment]
I'm sorry if my response sounded to you as a demand to change the code overnight. What I was hopping for is to discuss and hopefully to find a better solution to fix this issue. At this moment, the way I see this is 0.14.0 introduced breaking changes to the code that was developed for 0.13.0. Let me explain what I mean:

0.13.0 was generating models matching definitions from provided swagger specification file(providing there is no external $ref in it). That match also covered model names(So it was relatively easy to find generated model by its name from the swagger). In that version the --skip-flatten was quite handy for exactly that purpose. Those models were used by developers to receive and return data in all endpoints' implementation.

0.14.0 changed the behaviour of that option to "expand all". Thus now both structures content and their names don't match the code that was developed for the previous version. Thus the code that has been developed for 0.13.0 needs to be fixed and there is no guarantee that the next go-swagger version would continue to produce reliable structure content and names.

I can see a point in doing that for external $ref but would also think that "flatten light" solution is a much better option. The way I see it is external definitions' $ref can be imported into models in a similar way the old --skip-flatten option generated internal models(the names of imported models can be mangled to avoid clashes with internal ones). External $ref used in other parts of swagger, like paths, could be handled in a different manner(possibly using "expand all" but again if there is no $ref to definitions).

I don't know the internals of this project good enough to say if that's possible or not. I can look into it and make a PR if you can point me out into the right direction and if we agreed on the principle how that should be addressed.

**Comment by fredbi** [comment]
The expand all option was a bad choice - I don't know why we took this direction ...

Given a bit of time, we want to revert this. "Flatten minimal" would just resolve what is necessary for the codegen to work (external $ref's, indirect $ref's, $ref's to some  arbitrary place in the schema).

Not only this is possible, but this is necessary in order to make the thing usable to an API developer.

There are others itching things with this `go-openapi/analysis/flatten.go`, and we want to improve this as well.

**Comment by casualjim** [comment]
You are absolutely correct that the behavior has changed. I waited this long with releasing 0.14.0 because I was hoping to receive a fix from somebody or to find time to fix it myself.  But neither of these things happened and a lot of other stuff got fixed. If I receive a pr that fixes I'll release a new version that same day.

**Comment by fredbi** [comment]
For this particular issue, I consider my assignment is to fix the inconsistent behavior in expand mode, not to fix the flattening (this is another story).

I would like to first make sure everything works with or without anonymous structures before changing the way we produce anonymous structures vs definitions.

**Comment by akhobov** [comment]
Thanks guys. This sounds like a good start. Is there anything I can help you with to resolve this issue sooner? The 0.14.0 has lots of other very useful fixes in. Mainly around validation. So I wanted to migrate to it asap but this issue blocks us from doing that

**Comment by fredbi** [comment]
Here are some points that I am considering faulty with `go-openapi/analysis/flatten.go`.

1. Too many anonymous OAIGen definitions generated. Indirect references should be resolved. Only $ref to anonymous places in the schema should be left as OAIGen.
2.  Have an option to stop flattening as soon as references are good enough for the generator (this includes the OAIGen definitions above). At this stage it is not necessary to create all $ref's for complex things (this is the _minimal flattening_ discussed above).

Creating $ref on complex things is not necessarily a bad thing, but:

3.  it should consider maps of simple things as simple things (e.g. don't create a definition for map[]{my object}, the definition for {myobject} should be enough)
4.  allow more options/control to avoid systematically breaking simple allOf into "xxxAllOfn" definitions
5.  let as anonymous special allOf use-cases, such as: allOf: [ {empty schema with validation only}, {empty schema with x extensions only}, { possibly some more tbd } ]
6.  propagating x-go-name (as prefix) to newly created definitions: creating new definitions introduces some naming conventions. If a x-go-name has been set in the original structure, new names are no consistent with their container...

**Comment by fredbi** [comment]
ok so now the preparatory work is in the PR pipe to get full support in for both full flatten and full expand (aka "--skip-flatten"). I may start now implementing some more nuanced behavior in flatten.
