### ISSUE TITLE
Add HTTP/2 support

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#156]
Add HTTP/2 support

This probably has several parts to it:

  * ensure that a http 1 style rest API can be served
  * allow the client to use streaming so that connections are shared efficiently
  * extend the spec with the ability to describe a series of possible push messages (see #150)
  * add push strategies

**Comment by drewwells** [comment]
Which client is this referring to, the is the client generated from a swagger spec?

**Comment by casualjim** [comment]
yeah that would be the client generated or at least the runtime for the generated client.

**Comment by drewwells** [comment]
On go1.6, the client will automatically be http2 when the server supports it. In fact, the default behavior of http/2 clients is to identify as http/1.2. That should also take care of any efficiency gains from http2. There's no need to change anything to use streaming etc. Once it's http/2, the `net/http` will optimize the connection opens.

**Comment by casualjim** [comment]
k will close this ticket then :)
Thanks for the info!

**Comment by drewwells** [comment]
No problem, I went down the same train of though a few weeks ago. This is a really good post on the topic: http://rmurphey.com/blog/2015/11/25/building-for-http2
