### ISSUE TITLE
Can I configure the User-Agent header set for requests globally using a generated client?

### ISSUE THREAD

**Issue by marians** [go-swagger/go-swagger#1563]
I'd like to configure an instance of a generated client in a way that with every request a certain `User-Agent` header is set.

To be more specific, the generated client code must not contain this configuration. The package that imports and uses the generated client however will provide the string to use as a user-agent header and I currently can't find a way to pass it to the client.

**Comment by casualjim** [comment]
Add a roundtripper and set it for the transport property of the client when you construct it.
You can also provide a custom http client that does something to the same effect.

This is the property in question: https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L185

here's an example of a custom transport for connection reuse: https://github.com/go-openapi/runtime/blob/master/client/keepalive.go

**Comment by marians** [comment]
Thanks for your reply @casualjim ! I am already using a custom transport to pass TLS and proxy settings. But I don't know how I could use that to set a user-agent header.

**Comment by casualjim** [comment]
essentially it's a function of `func RoundTripper(r *http.Request) (*http.Response, error)`
When you make a wrapper it's basically `func(inner RoundTripper) RoundTripper` , so you have the opportunity to manipulate the request every time right before sending.

```go
func SetUserAgent(inner http.RoundTripper, userAgent string) http.RoundTripper {
	return &addUGA{
		inner: inner,
		Agent: userAgent,
	}
}

type addUGA struct {
	inner http.RoundTripper
	Agent string
}

func (ug *addUGA) RoundTrip(r *http.Request) (*http.Response, error) {
	r.Header.Set("User-Agent", ug.Agent)
	return ug.inner.RoundTrip(r)
}
```

use it:

```go
transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
transport.Transport = SetUserAgent(transport.Transport, "My User Agent")
cl := todolistclient.New(transport, nil)
```

**Comment by marians** [comment]
That worked nicely. Thank you very much @casualjim !

**Comment by maxkarelov** [comment]
@marians you've wrote that you use TransportClient to pass proxy settings. Could you please share a snippet how to do it?

**Comment by mkadin** [comment]
[The docs](https://golang.org/pkg/net/http/#RoundTripper) seem to indicate that the request should not be modified in the roundtripper.  Is this cool?

>RoundTrip should not modify the request, except for consuming and closing the Request's Body. RoundTrip may read 
>fields of the request in a separate goroutine. Callers should not mutate or reuse the request until the Response's Body has 
>been closed.
