### ISSUE TITLE
Deadlock issue in shutdown function under restapi

### ISSUE THREAD

**Issue by johnliu26** [go-swagger/go-swagger#1565]
## Problem statement
I have a issue when I do the test under restapi and when I try to shutdown the sever during the compile. The deadlock happened. I have checked the code under https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/custom-server/gen/restapi/server.go and found that there is no buffer for the channel when the shutdown was defined under NewServer. The buffer may need to be added under NewServer function. The code in the code base now is 
```go
func NewServer(api *operations.GreeterAPI) *Server {
	s := new(Server)

	s.shutdown = make(chan struct{})
	s.api = api
	return s
}
```
## Swagger specification
The code under go-swagger/generator/templates/server/server.gotmpl may need to be updated.
```go
// NewServer creates a new api {{ humanize .Name }} server but does not configure it
func NewServer(api *{{ .Package }}.{{ pascalize .Name }}API) *Server {
	s := new(Server)
  {{ if .UsePFlags }}
        s.EnabledListeners = enabledListeners
	s.CleanupTimeout = cleanupTimout
	s.MaxHeaderSize = maxHeaderSize
	s.SocketPath = socketPath
	s.Host = stringEnvOverride(host, "", "HOST")
	s.Port = intEnvOverride(port, 0, "PORT")
	s.ListenLimit = listenLimit
	s.KeepAlive = keepAlive
	s.ReadTimeout = readTimeout
	s.WriteTimeout = writeTimeout
	s.TLSHost = stringEnvOverride(tlsHost, s.Host, "TLS_HOST", "HOST")
	s.TLSPort = intEnvOverride(tlsPort, 0, "TLS_PORT")
	s.TLSCertificate = stringEnvOverride(tlsCertificate, "", "TLS_CERTIFICATE")
	s.TLSCertificateKey = stringEnvOverride(tlsCertificateKey, "", "TLS_PRIVATE_KEY")
        s.TLSCACertificate = stringEnvOverride(tlsCACertificate, "", "TLS_CA_CERTIFICATE")
	s.TLSListenLimit = tlsListenLimit
	s.TLSKeepAlive = tlsKeepAlive
	s.TLSReadTimeout = tlsReadTimeout
	s.TLSWriteTimeout = tlsWriteTimeout{{ if .ExcludeSpec }}
        s.Spec = specFile
  {{ end }}{{ end }}
	s.shutdown = make(chan struct{})
	s.api = api
	return s
}
```
## Steps to reproduce
Below is a portion of code under my test file in the restapi
```go
        api := operations.NewSwaggerCcmtsAPI(swaggerSpec)
        server := NewServer(api)
        defer server.Shutdown()
        server.ConfigureFlags()
        server.ConfigureAPI()
        handler := server.GetHandler()
```
Then I initialize the tests for restapi. When I run the test, there is always deadlock happened. 

## Environment
swagger version: 0.14.0
go version: 1.10.2
OS: linux/amd64

**Comment by fredbi** [comment]
duplicates #1473

**Comment by johnliu26** [comment]
Thanks @fredbi

**Comment by casualjim** [comment]
not a duplicate, just the same file with an error

**Comment by bvwells** [comment]
I suspect that I am also hitting the same issue. Servers no longer shutdown gracefully when for example panic is called in ConfigureAPI. This issue seems to have been introduced between versions 0.13.0 and 0.14.0. I suspect that this issue was introduced in the PRs to address issue #1316...

**Comment by bvwells** [comment]
When I say servers no longer shutdown gracefully I really mean that the server no longer crashes out! :-)
![image](https://user-images.githubusercontent.com/22873967/40998617-429e0968-6900-11e8-929d-8bd13ed1bcc1.png)

**Comment by fredbi** [comment]
Is this solved with #1569 ?

**Comment by johnliu26** [comment]
I think the change in the generator/templates/server/server.gotmpl in #1569 could fix the issue if it applies to the server.go under restapi but after I run the swagger generate server -f sg.yaml, the change did in the generator/templates/server/server.gotmpl was not applied to the server.go under restapi. So the change in the PR didn't apply to the generated code. So I recommend a further fix.

**Comment by johnliu26** [comment]
Did we have a fix for this issue? Thanks!

**Comment by johnliu26** [comment]
The source code has been tested and the issue fixed. We could close the issue.
