### ISSUE TITLE
Generated code don't pass on go vet

### ISSUE THREAD

**Issue by si-m** [go-swagger/go-swagger#1573]
## Problem statement
I am getting this vet response:
```
service/restapi/server.go:104: can't check non-constant format in call to Printf
service/restapi/server.go:115: can't check non-constant format in call to Fatalf
```
## Steps to reproduce
```sh
go vet -v $(go list ./...)
```
## Environment
swagger version: 0.14.0  
go version: go1.10.1
OS:  macOS High Sierra 10.13.4
#

**Comment by fredbi** [comment]
This is a warning croaked by vet in verbose mode: the vet command return code is still a success.

To remove this check: `go vet -v -printf=false`

Also vet is changing in go, and there are some bugs reported in go 11 vet command, specifically on this "printf" check.

**Comment by fredbi** [comment]
Reminder: should be tested again with go1.13

**Comment by fredbi** [comment]
Closed: go vet has evolved and does not produce this warning any longer. Tested using go1.13
