### ISSUE TITLE
Swagger UI, Try it out

### ISSUE THREAD

**Issue by doggodude** [go-swagger/go-swagger#1575]
## Problem statement
Is it possible to call your endpoints through the docs?

I'm looking for something like this: [swagger petstore](http://petstore.swagger.io/)

If not, is there another tool that enables this for Go?

Thanks!

**Comment by fredbi** [comment]
See also #1477

**Comment by abielikesu** [comment]
I implemented the suggested solution based on the Redoc middleware:

###  Create a swaggerui.go file inside restapi

<pre>
// restapi/swaggerui.go
package restapi

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"
	"path"
)

// SwaggeruiOpts configures the Swaggerui middlewares
type SwaggeruiOpts struct {
	// BasePath for the UI path, defaults to: /
	BasePath string
	// Path combines with BasePath for the full UI path, defaults to: docs
	Path string
	// SpecURL the url to find the spec for
	SpecURL string

	// The three components needed to embed swagger-ui
	SwaggerURL string
	SwaggerPresetURL string
	SwaggerStylesURL string

	// Title for the documentation site, default to: API documentation
	Title string
}

// EnsureDefaults in case some options are missing
func (r *SwaggeruiOpts) EnsureDefaults() {
	if r.BasePath == "" {
		r.BasePath = "/"
	}
	if r.Path == "" {
		r.Path = "swagger-ui"
	}
	if r.SpecURL == "" {
		r.SpecURL = "/swagger.json"
	}
	if r.SwaggerURL == "" {
		r.SwaggerURL = swaggerLatest
	}
	if r.SwaggerPresetURL == "" {
		r.SwaggerPresetURL = swaggerPresetLatest
	}
	if r.SwaggerStylesURL == "" {
		r.SwaggerStylesURL = swaggerStylesLatest
	}
	if r.Title == "" {
		r.Title = "API documentation"
	}
}

// Swaggerui creates a middleware to serve a documentation site for a swagger spec.
// This allows for altering the spec before starting the http listener.
//
func SwaggerUI(opts SwaggeruiOpts, next http.Handler) http.Handler {
	opts.EnsureDefaults()

	pth := path.Join(opts.BasePath, opts.Path)
	tmpl := template.Must(template.New("swaggerui").Parse(swaggeruiTemplate))

	buf := bytes.NewBuffer(nil)
	_ = tmpl.Execute(buf, opts)
	b := buf.Bytes()

	return http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		if r.URL.Path == pth {
			rw.Header().Set("Content-Type", "text/html; charset=utf-8")
			rw.WriteHeader(http.StatusOK)

			_, _ = rw.Write(b)
			return
		}

		if next == nil {
			rw.Header().Set("Content-Type", "text/plain")
			rw.WriteHeader(http.StatusNotFound)
			_, _ = rw.Write([]byte(fmt.Sprintf("%q not found", pth)))
			return
		}
		next.ServeHTTP(rw, r)
	})
}

const (
	swaggerLatest   = "https://unpkg.com/swagger-ui-dist@3.25.0/swagger-ui-bundle.js"
	swaggerPresetLatest   = "https://unpkg.com/swagger-ui-dist@3.25.0/swagger-ui-standalone-preset.js"
	swaggerStylesLatest   = "https://unpkg.com/swagger-ui-dist@3.25.0/swagger-ui.css"
	swaggeruiTemplate = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{{ .Title }}</title>
    <link rel="stylesheet" type="text/css" href="{{ .SwaggerStylesURL }}">
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>
    <script src="{{ .SwaggerURL }}"> </script>
    <script src="{{ .SwaggerPresetURL }}"> </script>
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: '{{ .SpecURL }}',
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      // End Swagger UI call region
      window.ui = ui
    }
  </script>
  </body>
</html>
`
)
</pre>

### Add the middleware

In the file restapi/configure_yourapp_.go

<pre>
// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	swaggerui := SwaggerUI(SwaggeruiOpts{}, handler)
	return swaggerui
}
</pre>

### Voila!
Start your API server and navigate to http://host:port/swagger-ui

**Comment by davix** [comment]
@abielikesu, definitely a good idea. I can't understand why redoc middleware is provided but swagger-ui is not.
I have an issue using the code. Is the `swaggeruiTemplate` efficient for a html page? My browser shows empty.

**Comment by davix** [comment]
Thanks @casualjim for the quick support. 
I've used it and have a quick try here: https://github.com/davix/serve-swagger-ui-in-go-demo
