### ISSUE TITLE
Suggestion: Implement golangci on go-swagger?

### ISSUE THREAD

**Issue by JonKohler** [go-swagger/go-swagger#1576]
Hey go-swagger community,
We've been working on several go related projects, some of them using go-swagger, which has driven us to investigate the current "state of the state" of static code analysis tools to help with code quality, style guidance, and so on.

I've been looking around for the past ~1-2 weeks, trying out things like code climate, codefactor, codacy, hound, scrutinizer, and all of them "do stuff", but none of them take it to the next level like golangci does, specifically for go based code.

As with many online, github integrated tools, golangci is free for open source projects, and hooks right into the repo. It helps with PR's, and seems to catch a lot of really good stuff, not just styling and duplication like most tools, but actual code level issues.

Note: I've got no position/advantage in golangci at all, just have fallen in love with it, and I truly think that it would benefit the terraform project at large.

I'd love to see this become a standard here. Happy to chat more about it and keep the conversation open!

**Comment by casualjim** [comment]
sure what needs to happen?

**Comment by JonKohler** [comment]
hey @casualjim - Thanks! back at my computer, sorry for the delay.

You've found it, all you do is sign in and enable the repos. You can configure the checks with a .golangci.yml

You can see what we ended up doing for the particular go project I've recently worked on, here: 
https://github.com/nutanix/terraform-provider-nutanix/blob/develop/.golangci.yml

I ended up disabling a few of the checks as they didn't really suit my needs, but you can download the CLI for golangci and run it locally to see what sort of things are going to flag in the repository and tune up from there

**Comment by JonKohler** [comment]
I've opened up a very small pull request just now, here: https://github.com/go-swagger/go-swagger/pull/1577

You can see it of course ran, but since i didn't modify go code, it didn't flag anything.

I'll open up a bogus PR to show the difference

**Comment by fredbi** [comment]
ok so now we are on.
