### ISSUE TITLE
Unable to regenerate main API configure file every time

### ISSUE THREAD

**Issue by kamynina** [go-swagger/go-swagger#1583]
## Problem statement

We are using custom templates and want to regenerate main API configure file every time. Could you make options `SkipExists` for this file configurable.

https://github.com/go-swagger/go-swagger/blob/3fd4a9e91d5cbaf817db8711023d05e6525018f7/generator/shared.go#L322

## Environment
swagger version: `version: dev commit: 442132c57cd7d1a394d596d7b8084f6a9cdb37f4` 
go version: `go1.10.2 darwin/amd64`
OS: `Darwin Kernel Version 16.7.0`

**Comment by fredbi** [comment]
It is configurable: 
in go-swagger main config file, you may specify `skip_exists: true` for any generation target.

```yaml
layout:
  application:
    - name: configure
      source: asset:serverConfigureapi
      target: ...
      skip_exists: true
      skip_format: false
...

**Comment by fredbi** [comment]
We have been discussing related improvements you might be interested in at #397

**Comment by kamynina** [comment]
It's great! thanks
