### ISSUE TITLE
no code generated to handle unmarshalling a slice of a generic type

### ISSUE THREAD

**Issue by ecnahc515** [go-swagger/go-swagger#160]
Code to unmarshal a generic type exists when the generic type of a normal property of a model. However, if a property is an array of a generic type, than the code doesn't handle unmarshalling the generic type.

Example:

if “PricingComponent” is generic than this will generate code to unmarshal the property "pricingComponent" on the model it's :
```
"properties": {
  "pricingComponent": {
    "$ref": "#/definitions/PricingComponent"
  }
}
```
This doesn’t generate any code to unmarshal the "pricingComponents" property.
```
"properties": {
  "pricingComponents": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/PricingComponent"
    }
  }
}

**Comment by casualjim** [comment]
is this an issue? because because each `PricingComponent` implementation will have its own MarshalJSON and UnmarshalJSON implementation.
have you seen it actually output bad data?

**Comment by ecnahc515** [comment]
It never calls the generic unmarshal function which switches on the dispatch property in the case of the array of `PricingComponent`'s. You're correct, each implementation has it's own MarshalJSON/UnmarshalJSON implementation, but the function which calls those never gets run in the case of an array. 

Here's an example of the generated code for those (with the extra properties):
