### ISSUE TITLE
Fail to generate model: unhandled type to resolve JSON pointer

### ISSUE THREAD

**Issue by zhuangqh** [go-swagger/go-swagger#1602]
## Problem statement

We are using go-swagger v0.12 to generate types, which works fine. We hope to upgrade go-swagger to the latest version without incompatibility and benefit from other feature. I think #1572 help a lot. However, I fail to generate model with latest version of go-swagger.

run
```bash
swagger generate model -f swagger.yml
```

I got error
```
2018/07/05 14:09:30 validating spec /mnt/hgfs/vmshare/go/src/github.com/alibaba/pouch/hack/../apis/swagger.yml
2018/07/05 14:09:33 preprocessing spec with option:  minimal flattening
unhandled type to resolve JSON pointer: spec.Response
```

debug mode
```
...
analysis:2018/07/05 14:29:08 flatten.go:1401: normalizeRef
analysis:2018/07/05 14:29:08 flatten.go:1222: name pointers
analysis:2018/07/05 14:29:08 flatten.go:1336: deepestRef for #/responses/401ErrorResponse
unhandled type to resolve JSON pointer: spec.Response
```

## Swagger specification
https://github.com/alibaba/pouch/blob/master/apis/swagger.yml

## Environment
swagger version: build from master a6de9fc6ed034d2bc27c0818571f888ec59084eb
go version: 1.9.7  
OS:   ubuntu 18.04

**Comment by fredbi** [comment]
okay I see where the bug is located.
I omitted in test cases the case where the expanded shared response still hold a $ref.
This should be the same problem for #/parameters.
I'll fix this today, it is not a hard one

**Comment by zhuangqh** [comment]
I’m truly grateful for your help. @fredbi

**Comment by fredbi** [comment]
I acknowledge the bug and shall make the code more resilient, but I have to say it comes from an  invalid specification:
line 791, your schema incorrectly points to the response descriptor. That is actually what makes the code to fail: I did not expect a schema to point to a response object.

**Comment by fredbi** [comment]
With this fix and using --withFlatten=verbose, you should get a warning about what is likely to be a wrong $ref. However, the flatten shall recover from this by assuming you mean the underlying response schema.

**Comment by fredbi** [comment]
I was pondering about this. I was not sure I have a valid case for this

**Comment by zhuangqh** [comment]
@casualjim I agree with you. It would be better if go-swagger could tell me what's wrong and how to fix it.

**Comment by fredbi** [comment]
done with error and hopefully more informative error message

**Comment by zhuangqh** [comment]
Hey, I think go-swagger is really awesome currently. Is there any plan to release a new version. 😄 @fredbi

**Comment by casualjim** [comment]
I'll try to release this weekend, but can't promise it. There are a few PR's that still need to get merged. when that's done I'll make a release

**Comment by fredbi** [comment]
@casualjim I promise I am not pushing anything more for the week end 😆 

I'll be around to rebase things when you need it
