### ISSUE TITLE
BUG? Extensions is empty

### ISSUE THREAD

**Issue by liber-takano** [go-swagger/go-swagger#1605]
## Problem statement

I define `x-order` each propaties.

Like...
```
  sessionData:
    type: object
    properties:
      sessionId:
        x-order: 0
        type: string
        description: UUID4
      deviceId:
        x-order: 1
        type: string
        description: UUID4
      uMain:
        $ref: '#/definitions/u_main'
        x-order: 2
        description: UserInfo
```

and Sort by x-order in `github.com/go-swagger/go-swagger/generator/structs.go`

```
func (g GenSchemaList) Less(i, j int) bool {
	a, ok := g[i].Extensions["x-order"].(float64)
	if ok {
		b, ok := g[j].Extensions["x-order"].(float64)
		if ok {
			return a < b
		}
		fmt.Printf("NG ... %v %v\n", g[j].Name, b)
	} else {
		fmt.Printf("NG ... %v %v\n", g[i].Name, a)
	}

	return g[i].Name < g[j].Name
}
```

But, Extensions of `uMain` is empty...

Extensions["x-order"] of `sessionId` is 0
Extensions["x-order"] of `deviceId` is 1

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by fredbi** [comment]
The presence of the $ref supersedes every other sibling attribute. This comes from JSONSchema.

**Comment by liber-takano** [comment]
Thank you!

I will try some.
If it good then I will feedback.

**Comment by liber-takano** [comment]
https://github.com/liber-takano/go-swagger/commit/ba1d8a84020f47292f1480ae3f3122b3b4708ce9
good work for me.

**Comment by casualjim** [comment]
can you submit a PR to this repo and add a test?

**Comment by casualjim** [comment]
o sorry I saw you just did :)
