### ISSUE TITLE
Client generation fails with 0.15.0, works with 0.14.0

### ISSUE THREAD

**Issue by marians** [go-swagger/go-swagger#1621]
## Problem statement

Just tested the `quay.io/goswagger/swagger:0.15.0` docker image as a replacement for 0.14.0 for generating a client.

The error output was:

```
name inlined schema: object has no field /v4/users/%7Bemail%7D/
```

With 0.14.0. the generation works fine based off the identical spec.

## Swagger specification

The spec is in this folder:

https://github.com/giantswarm/api-spec/tree/14d57a701b20135b174e97a7e755e0b49f28c097

The main file is `spec.yaml`, there are three more referenced YAML files in the same folder. The place where the generation broke is likely [line 293 or spec.yaml](https://github.com/giantswarm/api-spec/blob/14d57a701b20135b174e97a7e755e0b49f28c097/spec.yaml#L293):

## Steps to reproduce

1. `git clone https://github.com/giantswarm/gsclientgen.git`
2. Edit `Makefile` to replace `quay.io/goswagger/swagger:0.15.0` with `quay.io/goswagger/swagger:0.15.0`
3. Run `make generate`

This will use the current `master` of the spec linked above. To make sure the exact same version is used, edit `Makefile` once more and change the `BRANCH` variable in the top from `master` to `14d57a701b20135b174e97a7e755e0b49f28c097`.

## Environment

swagger version: The spec uses Swagger 2.0
OS: Linux (official docker image)

**Comment by fredbi** [comment]
This is a bug with the new default "flatten minimal". 
You can work around with `--with-flatten=full`, which gives you the behavior of v0.14

**Comment by marians** [comment]
Thanks! It works for us with `--with-flatten=full`.

**Comment by fredbi** [comment]
The problem is caused here. I don't know yet why it is occurring.
```yaml
  /v4/user/:
    get:
      operationId: getCurrentUser
...
      responses:
#        "200":
#          description: Success
#          schema:
#            $ref: "./definitions.yaml#/definitions/V4UserListItem"
#          examples:
#            application/json:
#             {"email": "andy@example.com", "created": "2017-01-15T12:00:00Z", "expiry": "2019-01-15T00:00:00Z"}
```

If I comment out this response, everything works again... Weird.    
```

**Comment by fredbi** [comment]
ok I found out where the problem  is. It is a bug in go-openapi/analysis flatten.

I'll try to fix it over next week end.

By this time, as a work around your spec works with default mode if you inline the $ref in the above mentioned response.
