### ISSUE TITLE
generate spec: json.RawMessage doesn't represent the intent.

### ISSUE THREAD

**Issue by klauspost** [go-swagger/go-swagger#1622]
## Problem statement

When generating from source, models with a `json.RawMessage`, it is represented as an array of uint8 values (which is the internal representation of course). Just as a `interface{}` generates a `"type": "object"` it would be nice if `json.RawMessage` did the same.

## Swagger specification

The following model is generated:
```
    "RawMessage": {
      "description": "It implements Marshaler and Unmarshaler and can\nbe used to delay JSON decoding or precompute a JSON encoding.",
      "type": "array",
      "title": "RawMessage is a raw encoded JSON value.",
      "items": {
        "type": "integer",
        "format": "uint8"
      },
      "x-go-package": "encoding/json"
    }
```
## Steps to reproduce

Generate a model with a `json.RawMessage` field.

Command used here: `swagger generate spec -m -i swagger.yaml -o ./swagger.json`

## Environment
swagger version: SHA-1: 8914a0f9bc4c11970552f133f8c9af106c1ac511 (latest master)
go version: 1.10.3
OS: windows/amd64

**Comment by mhr3** [comment]
+1, this would be really useful for our use case as well

**Comment by marcusyip** [comment]
+1

**Comment by zhilinstas** [comment]
+1

**Comment by fredbi** [comment]
How about RawMessage being actually an array, and not an object?

**Comment by mhr3** [comment]
`interface{}` can also be an array, yet go-swagger uses `object` for it... and json.RawMessage is pretty much the same thing, no?

Plus there's always `[]json.RawMessage`

**Comment by casualjim** [comment]
yes agreed it should be treated as 
```
type: string
format: binary
```

**Comment by aeneasr** [comment]
I've hit this issue and tried to work around it using:

```
struct T {
	// type: string
	// format: binary
	Traits          json.RawMessage `json:"traits" form:"traits" faker:"-" db:"traits"`
}
```

without success, it still generates:

```
    "RawMessage": {
      "description": "It implements Marshaler and Unmarshaler and can\nbe used to delay JSON decoding or precompute a JSON encoding.",
      "type": "array",
      "title": "RawMessage is a raw encoded JSON value.",
      "items": {
        "type": "integer",
        "format": "uint8"
      },
      "x-go-package": "encoding/json"
    },
```

```
type T struct {
struct {
	// traits
	Traits RawMessage `json:"traits,omitempty"`
}
```

with

```
// RawMessage RawMessage is a raw encoded JSON value.
//
// It implements Marshaler and Unmarshaler and can
// be used to delay JSON decoding or precompute a JSON encoding.
// swagger:model RawMessage
type RawMessage []uint8

// Validate validates this raw message
func (m RawMessage) Validate(formats strfmt.Registry) error {
	return nil
}
```
