### ISSUE TITLE
Can't have server code in subdirectory

### ISSUE THREAD

**Issue by maqdev** [go-swagger/go-swagger#1624]
## Problem statement

When passing -s argument as below which includes /, I was hoping that would allow the server code to be in a subdirectory:

`swagger generate server -f ./api/swagger/swagger.yaml -s pkg/srv`

However the import statements, for example in `configure_srv.go` are snake casing the package name:

`"github.com/xxx/app/pkg_srv/operations"`

## Swagger specification
2.0

## Environment
swagger version: 0.15.0
go version: 1.10.3
OS:  OS-X

**Comment by fredbi** [comment]
The generated code is put in a hierarchy of packages which may be customized with the
following options:
```sh
      -a, --api-package=                                                          the package to save the operations (default: operations)
      -m, --model-package=                                                        the package to save the models (default: models)
      -s, --server-package=                                                       the package to save the server specific code (default: restapi)
      -c, --client-package=                                                       the package to save the client specific code (default: client)
      -t, --target=                                                               the base directory for generating the files (default: ./)
```

The organization is determined as follows:
```
-- {target}
    -- {client-package:-client}
    -- {model-package:-models}
    -- {server-package:-restapi}
       -- {api-package:-operations}
          -- {tags}
```

You may customize the folder names, but can't specify sub-packages as package names.

**Comment by gregmarr** [comment]
We fixed this issue for models in December: https://github.com/go-swagger/go-swagger/issues/1326

**Comment by gregmarr** [comment]
Commit is here https://github.com/go-swagger/go-swagger/pull/1329/commits/ae57fbc6faae9e97310ca7d96f7d8a45d861e48b

**Comment by maqdev** [comment]
@fredbi actually you can specify sub-package for the models as mentioned by @gregmarr.
A workaround is to create a sub-directory, then run swagger inside it and it generates correct package names.
