### ISSUE TITLE
Redirect sometimes fails in the go-swagger generated code

### ISSUE THREAD

**Issue by huikang** [go-swagger/go-swagger#1629]
## Problem statement

I used go swagger to generate the http handler code. One of the handler needs to call the http.Redirect(...) to redirect the request to another web page.

```go
http.Redirect(wG, r, redirectURL, http.StatusFound)
```

In order to get the writer, I added the following code in the go swagger middleware part

```
var wG http.ResponseWriter

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	ourFunc := func(w http.ResponseWriter, r *http.Request) {
		wG = w
		handler.ServeHTTP(w, r)
	}
	return http.HandlerFunc(ourFunc)
}
```

However, sometimes the redirect fails to redirect the client browser to the redirect URL. Instead, the browser stays on the same page. It occurs occasionally. In addition, I saw the following log in the API server

```
2018/07/20 17:03:46 http: multiple response.WriteHeader calls
2018/07/20 17:03:46 http: multiple response.WriteHeader calls

```

Could anyone help look at this issue? Thanks.

## Swagger specification

version: 0.13.0
commit: 8135eb6728e43b73489e80f94426e6d387809502

**Comment by fredbi** [comment]
I have hit this one too.

It is a warning issued by the http package.
It is because we always send a response in the end, even though the redirect status has already been set.
One should check for possible already redirected response before forcing a response.

**Comment by huikang** [comment]
@fredbi , thanks for your explanation. Do you have any code snippet that fixes the redirect issue? Thanks in advance.

**Comment by fredbi** [comment]
not yet

**Comment by huikang** [comment]
The problem is that the http.Redirect method in Go does not provide any return value.

Also is it confirmed that the "http: multiple response.WriteHeader calls" causes the redirect failure?

**Comment by casualjim** [comment]
do you have wg outside of the middleware like that?

**Comment by huikang** [comment]
In the above code snippet, ``wG`` is a global variable and the only one. Because I need to use ``wG`` in the http.Redirect method.

**Comment by casualjim** [comment]
yeah but how does that work with 2 concurrent requests?

**Comment by huikang** [comment]
I thought the go-swagger generated code handles concurrent requests. For example, user 1 hits the redirect path of the server, which calls the redirect method to redirect to an external page.
Meanwhile, user 2 can access the same path.

Do you mean I need to handle concurrent access to the redirect write response?

**Comment by casualjim** [comment]
yes but not when you store the response writer in a global variable. if you need to share in between functions for the same request you can put something on the context

**Comment by huikang** [comment]
@casualjim , could you provide some sample code ? Thanks.

**Comment by huikang** [comment]
I think I found some solution using the context library.

```
In the middleware part, I set the response writer value in the context. And then in the handler function, I can get that value and use it in the redirect call.
```

**Comment by casualjim** [comment]
also if you just want to redirect, add the 301 or 302 response to your swagger spec
generate the server and when you want to redirect just use that response instead of what you're doing now

or return a responder from your go-swagger handler: https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L55-L67

**Comment by fredbi** [comment]
@huikang here some sample code with a responder saved in context:
https://github.com/go-swagger/go-swagger/blob/f9da9f1f9bb42571cfcc6c6a4a6323a5e1d0e115/examples/oauth2/restapi/implementation.go#L54

**Comment by huikang** [comment]
@casualjim @fredbi , thanks for your responses. The problem is solved by setting the correct response writer.
