### ISSUE TITLE
How to Close a file

### ISSUE THREAD

**Issue by mbresson** [go-swagger/go-swagger#1649]
## Problem statement

Hi! I have a swagger API that sends files (specification below)

I have generated the server code with go-swagger and I'm trying to implement the handler to return a file. However, I don't know how to Close it in the handler:

```go
	func(params operations.GetFileParams, principal interface{}) middleware.Responder {
		file, fileErr := os.Open("/data/" + params.File)
		if fileErr != nil {
			if os.IsNotExist(fileErr) {
				return operations.NewGetFileNotFound()
			} else if os.IsPermission(fileErr) {
				return operations.NewGetFileForbidden()
			}

			return operations.NewGetFileInternalServerError()
		}

		// defer file.Close()

		return operations.NewGetFileOK().WithPayload(file)
```

I have tried defer but it doesn't work because the file is closed before being read, which provokes an error. And I'd rather not load the whole file in memory.

I have seen a similar question: https://github.com/go-swagger/go-swagger/issues/515
But to be honest I don't understand the answer.

I know that I could just modify the code generated by swagger but I'd rather find a cleaner way that would not involve changing it each time I update the specification.

## Swagger specification

```yaml
responses:
  200:
    description: The markdown file that was requested.
    schema:
      type: file
  403:
    description: Unauthorized.
  404:
    description: Not found.
  500:
    description: Internal error.
```

## Environment
swagger version: master
go version: 1.10
OS: Fedora 28 (Linux)

Thank you!

**Comment by casualjim** [comment]
you can make a responder and use that instead of the default OK one that you're using now

https://github.com/go-swagger/go-swagger/issues/748#issuecomment-261646983

**Comment by mbresson** [comment]
Thanks a lot! Problem solved :).
