### ISSUE TITLE
use of closed network connection error on shutdown in 0.15

### ISSUE THREAD

**Issue by greensombrero** [go-swagger/go-swagger#1650]
## Problem statement

I recently started a new project using version 0.15 instead of 0.13.  After setting up a really basic service I noticed every time I shutdown the server by pressing Ctrl+C I would get an error "accept tcp 127.0.0.1:8080: use of closed network connection".  I was trying to figure out what caused it as I haven't had the issue in prior go-swagger projects.  I realized that in 
0.15 tylerb/graceful is removed per [1574](https://github.com/go-swagger/go-swagger/pull/1574).  

When I rolled my code back to 0.13 (the version I was previously using) the problem resolved itself.  It appears that the shutdown code without tylerb/graceful has some sort of issue with it or I need to do something differently in servers built using 0.15.  Anyone else observed a similar issue?
## Environment
swagger version: 0.15
go version: go1.10.2
OS:  OSX

**Comment by casualjim** [comment]
This is fixed on master, but not yet released.

**Comment by casualjim** [comment]
this is the pr #1627

**Comment by greensombrero** [comment]
Thanks for the response!
