### ISSUE TITLE
Server hangs given a panic in configure_

### ISSUE THREAD

**Issue by andreib1** [go-swagger/go-swagger#1655]
The defer statement attempts to send a struct{} to the server control channel to gracefully shut down.  

The server has not been started yet, and therefore has no receiver, so sending to the channel hangs.

**Steps to reproduce:**
Panic in configure_

**Expected**
Panic message

**Actual**
Server hangs with no panic message

**Potential Fix**
Move the defer behaviour to after the configure call has been executed.

**Comment by amitech** [comment]
Is this bug still exists? If yes, I would like to contribute.

**Comment by Sasaki1994** [comment]
I think this issue was resolved by commit 31f5066e4d63762285db384db3b623d8d9b24188 .
I tried following the steps to reproduce, but it did not reproduce.
