### ISSUE TITLE
go-swagger generation is pretty chatty on logs

### ISSUE THREAD

**Issue by JonKohler** [go-swagger/go-swagger#1658]
## Problem statement
generate server/client is pretty "chatty" on the console logs. We have this integrated into a large jenkins build deployment, and there is just a lot of "noise" that feels like it is more "debug" than "normal" statements.

Meaning, if you just grep around for things like "log.Println" and "log.Printf", you'll see that chattiness.

We were noodling with the idea of wrapping debug statements around (many) of these, but wanted to see what the crowd thinks, or if anyone is already working on this.

We need to upgrade from 0.13 to 0.15 anyways, which is going to take us a minute, so I figured I'd ask early.

## Swagger specification
OAI 2.0 compliant, passes validation 

## Steps to reproduce
generate server, generate client

## Environment
swagger version: 0.13.0
go version: 1.9.2
OS: Linux el6.9

**Comment by fredbi** [comment]
you have a quiet option to mute the logs

**Comment by JonKohler** [comment]
ah ok, thank you. ill go look at that

**Comment by fredbi** [comment]
```sh
Application Options:
  -q, --quiet                                                   silence logs
  -o, --output=LOG-FILE                              redirect logs to file
```
