### ISSUE TITLE
Could not get payload or file content from request

### ISSUE THREAD

**Issue by AlexInGitHub** [go-swagger/go-swagger#1666]
## Problem statement
I defined a custom Auth function. But the Auth function need the payload info. However, I cannot get the payload info from the request. 
The relates code is in "github.com/go-openapi/runtime/client_request.go" and "github.com/go-openapi/runtime/request.go"
`
type ClientRequest interface {

	SetHeaderParam(string, ...string) error

	SetQueryParam(string, ...string) error

	SetFormParam(string, ...string) error

	SetPathParam(string, string) error

	GetQueryParams() url.Values

	SetFileParam(string, ...NamedReadCloser) error

	SetBodyParam(interface{}) error

	SetTimeout(time.Duration) error

	GetMethod() string

	GetPath() string

	GetBody() []byte
}

if auth != nil {
		if err := auth.AuthenticateRequest(r, registry); err != nil {
			return nil, err
		}
	}
`

So, could you add another two method to retrieve payload info? For example
`GetBodyParam() interface{}

GetFileParam() map[string][]NamedReadCloser`

Please remove the sections that don't apply

## Swagger specification

Swagger 2.0

## Environment
swagger version: 0.15.0
go version: 1.10.3
OS:   Mac OS

**Comment by fredbi** [comment]
See #1668

**Comment by AlexInGitHub** [comment]
Hi @fredbi @casualjim 
I looked at #1668, but not sure it could give any helps to my requirement, since the APIs requires 'ClientAuthInfoWriter'. 
I'm new to golang, so could you give me more examples how could I define a customised ClientAuthInfoWriter which could get payload info. Thank you very much

**Comment by casualjim** [comment]
Why do you need the request body, you're about to send, for the authentication? 
Don't you have the information that goes into it already before you're writing it?

**Comment by AlexInGitHub** [comment]
Yes, for the authentication. 
I saw the every generated operation accept an argument authInfo runtime.ClientAuthInfoWriter. e.g.
`func (a *Client) GetReportList(params *GetReportListParams, authInfo runtime.ClientAuthInfoWriter) (*GetReportListOK, error) `

So I define an auth function
`func MyAuth(accessId, accessKey string) ClientAuthInfoWriter {
	return ClientAuthInfoWriterFunc(func(r ClientRequest, _ strfmt.Registry) error {
                  //The auth need payload info, but I cannot get the payload info from ClientRequest.
        }
}
`

**Comment by casualjim** [comment]
On the client for oauth you just want to pass this in:
https://github.com/go-openapi/runtime/blob/master/client/auth_info.go#L56

why does this need payload info? I still don't understand your use case. Does it need to sign the payload with the headers or something like that?

**Comment by AlexInGitHub** [comment]
Since we have an algorithm to generate a signature,  payload info is an argument for the algorithm. Then we will put the signature into the header. 
r.SetHeaderParam("Authorization", fmt.Sprintf("MyAuth %s:%s:%s", accessId, signature, epoch))

**Comment by casualjim** [comment]
There a

**Comment by casualjim** [comment]
There are 2 solutions to this. 

If you have to do this for every request, you could make a RoundTripper implementation and use that in the transport. This roundtripper has access to both the request and response and is the last thing that sees the request before it's sent over the wire.

The other solution would be adding the necessary methods to the ClientRequest interface. At the moment the auth request is written very early on in the process, before the body is even considered.  So this is more work but it would give more granularity

**Comment by AlexInGitHub** [comment]
@casualjim  Thanks for your solutions. 
I will take a look into RoundTripper, but if you could give me an example that would be perfect.
I also considered the second solution, but I think it needs you guys to help to commit the code.

**Comment by AlexInGitHub** [comment]
Hi @casualjim I think the second solution is better. Is it possible adding the necessary methods to the ClientRequest interface? Or, Could I contribute it?

**Comment by casualjim** [comment]
You can send a PR with the changes to the [runtime](https://github.com/go-openapi/runtime) repository.

**Comment by AlexInGitHub** [comment]
Hi @casualjim I create a PR https://github.com/go-openapi/runtime/pull/116. But it requires me add some test cases for the methods. I notice there aren't test cases for other Get methods. And also the Get methods are quiet simple, so, do you think it's necessary to add the test cases?
Also, please help to review the code, thanks.

**Comment by casualjim** [comment]
I already merged it.

**Comment by AlexInGitHub** [comment]
@casualjim Thank you very much.

**Comment by nitin302** [comment]
@casualjim Just a question on a similar question. Do I have do add those security params to define a auth logic?

My use-case is, we use both headers and path params and query params to add authentication. Can I write generic function (which addes these headers/params) which will be called at the end of every request?

Can you show how?
