### ISSUE TITLE
Move from x/net/context to just context

### ISSUE THREAD

**Issue by MStoykov** [go-swagger/go-swagger#1676]
Given that context is in golang since 1.7 I think it's time to just move to it :)

This is ticket is mostly about all the open-api dependencies but I guest here will be the place to start the discussion :). 

I would gladly do the grunt work trough out the projects if there are no objections

**Comment by casualjim** [comment]
go for it :)

**Comment by fredbi** [comment]
Could you please remind here where we still have a dependency to `x/net/context`?
Some work has been done to replace this by `context` quite some time ago and I fail to see any remaining import to this (I looked in runtime and generated code)

**Comment by MStoykov** [comment]
I might've jumped the gun a little bit - have being going trough internal projects and moving them to go modules and looking in to what depedencies there are. 
Apparently only runtime's client code still has net/context like in [here](https://github.com/go-openapi/runtime/blob/9a3091f566c0811ef4d54b535179bc0fc484a11f/client/runtime.go) . But I also goimports all the generated files so it creeps into the 'client' generated code

**Comment by etsangsplk** [comment]
A quick grab, it either tells user they have to have the old context package or directly refering it.
./vendor/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:93:	* golang.org/x/net/context

./vendor/github.com/go-openapi/runtime/client_operation.go:20:	"golang.org/x/net/context"
./vendor/github.com/go-openapi/runtime/.travis.yml:12:- go get -u golang.org/x/net/context
./vendor/github.com/go-openapi/runtime/client/runtime.go:33:	"golang.org/x/net/context"

**Comment by fredbi** [comment]
Done with go-openapi/runtime#113 and #1691
