### ISSUE TITLE
Generate spec does not work with Go Modules

### ISSUE THREAD

**Issue by JeremyLoy** [go-swagger/go-swagger#1681]
## Problem statement

the `swagger` CLI tool does not work correctly when the target repository is a Go 1.11 Module. The tool should not use `GOPATH/src` to resolve dependencies, and instead use the `GOPATH/pkg/mod` The possible failure cases I have discovered are as follows:

1. required dependency is not in GOPATH
    1. results in the CLI tool saying it cannot find dependency
1. dependency in GOPATH is not the same as declared in MODULE
    1. individual types/functions/packages fail, rather than the dependency as a whole

**Comment by kostiamol** [comment]
Guys, is there any progress with modules?

**Comment by casualjim** [comment]
no progress but we welcome PR's

**Comment by rayjlinden** [comment]
I just converted my project from Godep to go mod.  I now get this error with swagger gen spec:
unable to determine package for /Users/rayj/dev/go/pkg/mod/github.com/lindenlab/extraction-utils-go@v0.0.0-20180806163638-9e283eb62bd2/response/response.go

Is this related to this thread?  Any idea how I work around this?

**Comment by casualjim** [comment]
we have to change the way we introspect code, but this is go 1.11 specific we can't do that for 1.10.

Anyway haven't been able to get into how go does this internally yet.

**Comment by rayjlinden** [comment]
The very odd thing is I rerun the swagger command and changed nothing and
it works.  It doesn’t happen all the time and so far rerunning has fixed it
each time...

Ray

**Comment by arfo90** [comment]
just got the latest version yesterday and seems it works fine generating module base Go project. maybe the issue can be closed ?

**Comment by rayjlinden** [comment]
I don't think so.  It will work if the project you are running on is in the
GOPATH and you have GO111MODULE=off.  However, if you have GO111MODULE=on
or your project is not in the GOPATH it will fail.  It will continue to
fail until they use a different library for parsing go code.

**Comment by bserdar** [comment]
Ugly workaround: I have my source tree outside GOPATH, and a symlink to it under GOPATH. I use the version under GOPATH to build swagger specs, and the original for real work.

**Comment by zgramana** [comment]
I had success in my module-based project by doing what @bserdar did and adding the following twist:
```sh
# Go inside my module-based project's repo (which is now also inside GOPATH)
cd $GOPATH/src/path/to/my/symbolic/link/project-repo

go mod vendor # gets all the go.mod dependencies

# The `vendor` folder will now satisfy our unfilled deps... no more errors! \o/
swagger generate spec -o spec.yaml
```

**Comment by bserdar** [comment]
More ugliness: spec generation with the symlink under GOPATH broke with kubernetes deps, so I hacked it up even more, with a separate main.go that only includes my models, and I use that main to generate swagger spec. No vendors though...

**Comment by zgramana** [comment]
I use a couple of `go.mod` `replace`s so I ended up using `vendor` and a separate docs-only `main` as well.

**Comment by pingdai** [comment]
this has been resolved,see here:
https://github.com/go-swagger/go-swagger/issues/1906

**Comment by JeremyChase** [comment]
@pingdai Do we know what commit resolved this? Issue #1906 says it was fixed, but doesn't referenced when/where.

**Comment by s-kostyaev** [comment]
Looks like it works with modules now but not with incompatible modules:
```
%  swagger generate spec -b ./cmd/api -m -o ./docs/swagger/swagger.json
/Users/username/go/pkg/mod/github.com/rs/zerolog@v1.9.1/encoder_json.go:9:2: could not import github.com/rs/zerolog/internal/json (go/build: importGo github.com/rs/zerolog/internal/json: exit status 1
error writing go.mod: open /Users/username/go/pkg/mod/github.com/rs/zerolog@v1.9.1/go.mod263249228.tmp: permission denied

)
...
```

**Comment by JeremyChase** [comment]
@s-kostyaev I ran into the same issue and worked around it by doing a chmod:
```
cd $GOPATH/pkg/mod
chmod -R u+w *
```

That worked in that I no longer get permission denied errors, but running `swagger generate` results in new errors:

```verifying github.com/karrick/godirwalk@v1.7.5: checksum mismatch
        downloaded: h1:VbzFqwXwNbAZoA6W5odrLr+hKK197CcENcPh6E/gJ0M=
        go.sum:     h1:JQFiMR65pT543bkWP46+k194gS999qo/OYccos9cOXg=

)
```

I am still trying to generate the spec while using modules...

**Comment by kaisawind** [comment]
@JeremyChase 
Maybe you can see this issue about go. [#30978](https://github.com/golang/go/issues/30978) 
You can fixed it by delete all file in /gopath/pkg/mod
