### ISSUE TITLE
swagger generation with --with-context result in compiles error

### ISSUE THREAD

**Issue by etsangsplk** [go-swagger/go-swagger#1684]
## Problem statement
RE generate the code for example custom-server with context results in compilation error.
There is missing returned http.Request for generated code and missing Authorizer method.

Compilation Error:
# github.com/go-swagger/go-swagger/examples/tutorials/custom-server/gen/restapi/operations
examples/tutorials/custom-server/gen/restapi/operations/get_greeting.go:43:12: assignment mismatch: 2 variables but 3 values
examples/tutorials/custom-server/gen/restapi/operations/greeter_api.go:190:46: cannot use o (type *GreeterAPI) as type middleware.RoutableAPI in argument to middleware.NewRoutableContext:
	*GreeterAPI does not implement middleware.RoutableAPI (missing Authorizer method)
Please remove the sections that don't apply

Even after manually fixing that, following error
examples/tutorials/custom-server/cmd/greeter/main.go:39:60: cannot convert func literal (type func(operations.GetGreetingParams) middleware.Responder) to type operations.GetGreetingHandlerFunc

## Swagger specification
Just using the custom-server in example
https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/custom-server/swagger/swagger.yml

## Steps to reproduce
server:
rm -rf gen && swagger generate server --exclude-main -A greeter -t gen -f ./swagger/swagger.yml --with-context
client:
swagger generate client -A greeter -t gen -f ./swagger/swagger.yml

## Environment
swagger version: dev
go version: go1.10.2 darwin/amd64
OS:   
macOS

**Comment by etsangsplk** [comment]
@ huikang dep ensure was run and vendor dir was deleted

**Comment by casualjim** [comment]
--with-context has no actual effect we should remove the option
