### ISSUE TITLE
Trouble using 'y' as a path parameter

### ISSUE THREAD

**Issue by tschaub** [go-swagger/go-swagger#1685]
## Problem statement

Using a path parameter named `y` causes spec validation to fail.

## Swagger specification

```yml
swagger: '2.0'

info:
  version: 1.0.0
  title: Go Swagger Test

paths:

  /letters/{y}:
    parameters:
      - name: y
        type: integer
        format: uint64
        description: Column id.
        in: path
        required: true
    get:
      summary: Get letter.
      description: Get a letter.
      produces:
        - text/plain
      responses:
        200:
          description: A letter.
          schema:
            type: string
```

## Steps to reproduce

Save the above spec as `spec/test.yml` and run the following:
```
docker run --rm --volume "$(pwd)":/data quay.io/goswagger/swagger:0.16.0 validate /data/spec/test.yml
```

The result is `json: cannot unmarshal bool into Go struct field SwaggerProps.paths of type string`.  This is unexpected.

If you change the parameter name from `y` to `z` (or lots of other letters, I didn't try them all), validation succeeds (as expected).

## Environment
swagger version: 0.16.0
go version: 1.11
OS:  macOS 10.13

**Comment by tschaub** [comment]
I just noticed that if I quote the letter `y`, things work again.  Curious why this is required with `y` and not other letters.

**Comment by fredbi** [comment]
this is due to yaml: 'y' unmarshals as boolean true

**Comment by gregmarr** [comment]
Full list here: https://github.com/go-swagger/go-swagger/issues/1209#issuecomment-336571529

**Comment by casualjim** [comment]
http://yaml.org/type/bool.html

**Comment by tschaub** [comment]
Thanks for the responses.  I'll file away this bit of new yaml knowledge.
