### ISSUE TITLE
Generate spec in yml format

### ISSUE THREAD

**Issue by chenziliang** [go-swagger/go-swagger#1686]
## Problem statement
1. May i ask if there is a way to generate a spec in yml format directly by using go-swagger ?
2. May i ask if i can optionally "not generate" "x-go-name" by using go-swagger as i don't wanna the spec file go specific ?

**Comment by chenziliang** [comment]
There are 2 PRs merged for these requirements. Use the latest swagger command
1. To generate yml format spec, simply specify a output file name with `.yml` or `yaml` extension. For example, `swagger generate spec -o openapi.yml`
2. To avoid generate go extension, do `SWAGGER_GENERATE_EXTENSION=false && swagger generate spec -o openapi.yml`

**Comment by fredbi** [comment]
@chenziliang could you be so kind as to add the above to the documentation? It is here:
https://github.com/go-swagger/go-swagger/blob/master/docs/use/spec.md
