### ISSUE TITLE
How to receive the shutdown signal from generated server?

### ISSUE THREAD

**Issue by huikang** [go-swagger/go-swagger#1695]
I have a go routine that needs to receive the shutdown or stop signal from the generated server code.

To achieve this, I add a channel in the generated `server.go` file. When the swagger server is being shutdown (e.g., ctrl-C), it closes the channel. Following is a code snippet. 

```go
// gen/restapi/server.go

// Server for the auth API
type Server struct {
    MonitorDone chan struct{}
}

func (s *Server) handleShutdown(wg *sync.WaitGroup, server *graceful.Server) {
	defer wg.Done()
	for {
		select {
		case <-s.shutdown:
			if atomic.LoadInt32(&s.shuttingDown) == 0 {
				close(s.MonitorDone)
			}

....

```

However, this change is overridden every time the code is regenerated. My question is that is there any other way to do so? Thanks in advance.

**Comment by casualjim** [comment]
https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/restapi/operations/todo_list_api.go#L34

Every generated API allows you to provide that function, which will be called at shutdown

**Comment by huikang** [comment]
Hi, @casualjim , thanks for your response. This looks nice!

With this function, I think I can define the following to close the channel on shutdowning the server. Is my understanding correct?

```
// create new service API
api := operations.ToDoAPI(swaggerSpec)

api.ServerShutdown = func() {
    close(MonitorDone)
}
```

**Comment by casualjim** [comment]
that is correct
