### ISSUE TITLE
un-graceful shutdown after 15 seconds on generated restapi/server.go#handleShutdown

### ISSUE THREAD

**Issue by dehoust** [go-swagger/go-swagger#1714]
In handleShutdown a context with a constant timeout of 15 seconds is passed on to server.Shutdown

https://github.com/go-swagger/go-swagger/blob/32f94c7110162041004c3c54a2f3cba41c6d205c/generator/templates/server/server.gotmpl#L541
...
https://github.com/go-swagger/go-swagger/blob/32f94c7110162041004c3c54a2f3cba41c6d205c/generator/templates/server/server.gotmpl#L552

which leads to an un-graceful shutdown after 15 seconds with "context deadline exceeded", closing also active connections.

We have to deal with longer living active connections. Please make that timeout a parameter that can be set in configureServer on restapi/configure_.

**Comment by fredbi** [comment]
Fixed with #1730, #1732
