### ISSUE TITLE
Validate returns different output in console and logs

### ISSUE THREAD

**Issue by jputrino** [go-swagger/go-swagger#1722]
## Problem statement
`swagger -o output.txt validate <foo>` displays different output in the console than it writes to the log file.

## Swagger specification
2.0

## Steps to reproduce
Run `swagger -o output.txt validate <somefile.swagger.json>`

```
$ swagger -o output.txt validate somefile.swagger.json

The swagger spec at "somefile.swagger.json" is invalid against swagger specification 2.0.
See errors below:
- path param "name" is not present in path "/api/foo/v1/{name=bar/*/paths/*}"
- path param "parent" is not present in path "/api/foo/v1/{parent=bar/*}/paths"

$ cat output.txt
2018/09/21 15:52:25 
The swagger spec at "somefile.swagger.json" showed up some valid but possibly unwanted constructs.
2018/09/21 15:52:25 See warnings below:
2018/09/21 15:52:25 - WARNING: path stripped from path parameters /api/foo/v1/{name=bar/*/paths/*} contains {,} or white space. This is probably no what you want.
2018/09/21 15:52:25 - WARNING: path stripped from path parameters /api/foo/v1/{parent=bar/*}/paths contains {,} or white space. This is probably no what you want.
```

(Filenames/pathnames have been changed, but everything else is actual output.)

## Environment
swagger version: 0.15.0 
go version: go1.10.2 darwin/amd64
OS:   macOS High Sierra 10.13.6

**Comment by fredbi** [comment]
Oh that's probably because of this:
https://github.com/go-swagger/go-swagger/blob/e13f8554b4e77901403d8b9444eb2fa92a50c04c/cmd/swagger/commands/validate.go#L79

cmd returns errors and does not output them to "log".

**Comment by jputrino** [comment]
Thanks @fredbi!

**Comment by casualjim** [comment]
if you want to capture both, just run it differently, we should just drop the output flag it's confusing.

```
swagger validate <somefile.swagger.json>  &> output.txt
```
