### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#1724]
Supporting go modules will require a number of changes. Some are mechanical and can be scripted, others mean changing the way our code works.  

## Tagging changes

The first one is fairly easy. On the next release we tag versions with the *v* prefix. And we add a go.mod and go.sum file in every package under the go-openapi organization as well as in this go-swagger/go-swagger repository.

* [x] **Done**

## Turn on go vet during tests

Currently our generator package is doing a cute thing in the debugLog and debugLogAsJSON methods.
go vet is unhappy about it, so we've turned it off until we can address the format string issues.

https://github.com/search?l=&q=debugLog+repo%3Ago-swagger%2Fgo-swagger+extension%3Ago+path%3Agenerator&type=Code

* [x] **Done**

## Package refactoring

For our current version we don't need to rewrite packages or import paths, it's only if/once we decide to do v2 then we need to use different import paths. 

## Generated code changes

The generator should optionally add go.mod or edit the go.mod file with the required dependencies. Although the tooling should pick up on that too the first time the code gets run. But if people want to pin to older versions etc then this can help them out with that.

Initial work has done some of this: https://github.com/search?q=%22go.mod%22+repo%3Ago-swagger%2Fgo-swagger+extension%3Ago+path%3Agenerator&type=Code

## Generator support

We do lookups in the go path for guessing imports and so on. These will need to be made compatible with go modules. Currently we basically strip off or join with `${GOPATH-"$HOME/go"}/src` 

We would need to change this logic to be aware of modules and look up with that tool.

https://github.com/search?utf8=%E2%9C%93&q=GOPATH+repo%3Ago-swagger%2Fgo-swagger+extension%3Ago+extension%3Ago+path%3Agenerator%2F&type=Code&ref=advsearch&l=&l=

## Scanner support

The scanner uses `go/build` from the go compiler infrastructure, to discover the files and packages that need to be introspected.
This needs to move to the newer library: https://godoc.org/golang.org/x/tools/go/packages so that it's module aware.

https://github.com/search?utf8=%E2%9C%93&q=GOPATH+repo%3Ago-swagger%2Fgo-swagger+extension%3Ago+path%3Ascan&type=Code&ref=advsearch&l=&l=

related #1677

**Comment by fredbi** [comment]
RE:

> Turn on go vet during tests

also affects generated code, see also #1573. This was actually introduced by go1.10.

I am not sure this go vet behavior is going to remain as it basically precludes from implementing any generic logger with format string of some sort...

**Comment by fredbi** [comment]
> Again RE: go vet 

The go vet change with 1.10 & 1.11 breaks a lot of well known packages just like ours.

I don't think this is going to stand for long. See golang issue https://github.com/golang/go/issues/26555.

go master has already changed the behavior of go vet.

What we _could_ do is to help go vet detecting this is a printf wrapper by renaming debugLog and debugLogAsJSON as debugLogf and debugLogAsJSONf. I'll give this a try and figure out #1573 as well.

**Comment by casualjim** [comment]
for converting our repos after v1 this tool might be  of help: https://github.com/marwan-at-work/mod

**Comment by stevef1uk** [comment]
Please could I request that the generated code also works with go modules? I have created a service proxy project by generating in the same folder both the client and server sides using two almost identical swagger.yaml files (basically just changed ports) and writing a very simple a server handler to use the client API. I had to ditch one of the models directories but basically it worked ok and faily easily. However, when trying to build using go modules I get some strange errors such as 'cannot find module for path goproxy/client/client'

**Comment by sidh** [comment]
Right now `go get github.com/go-swagger/go-swagger` doesn't work with modules since it tries to bring incorrect versions of dependencies. It needs go.mod to resolve those correctly.

**Comment by casualjim** [comment]
I don't know if this project will actually be migrating to modules, it's not meant to be used in that way.

**Comment by sidh** [comment]
It has support for dep which is basically has the same purpose as modules (in terms of managing dependencies). Its dependencies have support for modules.

What is the correct way to add go-swagger as dependency to your project?

**Comment by casualjim** [comment]
it's used as a build tool so the expectation is that you use this as a binary tool.
The runtime components of go-swagger are in the go-openapi repos, and those do have go.mod files defined

**Comment by sidh** [comment]
That workflow forces you to manage separately manage versions of go-swagger (as a tool) and its dependencies (as build dependecies for generated code). And for dependencies you actually have to match their versions with go-swagger by hand. It would be much better if you could do it all in one go and modules allow you to do it.

Besides since there is a dep support already why not just move to modules altogether?

**Comment by sidh** [comment]
If that is fine I'll do just that. :) But what to do with dep (Gopkg files)? I'd prefer removing it since supporting 2 dependency managers won't work in the long run.

**Comment by casualjim** [comment]
yes the would need to get removed.

My main issue with go modules is that support for it is half-baked, and working outside the gopath has a number of issues that are not obvious, like tooling failing silently.

Our own tool doesn't actually work with go modules outside of the gopath because go imports doesnt' work with well outside of it and our scanning for doc comments uses go/build as well so it is not aware of go modules either.

**Comment by sidh** [comment]
Yes, I've came to the same conclusion about modules replacing GOPATH. But for dependency management they are quite adequate.

I have high hopes for 1.12.

**Comment by FryDay** [comment]
Yeah, it appears spec generation is impossible outside of GOPATH. This is a major issue.

**Comment by casualjim** [comment]
let's not call not supporting experimental features  a major issue.

I use a script like this for tools that don't support running in the gopath.

```sh
#!/usr/bin/env bash

set -eu

dir=$(git rev-parse --show-toplevel)
cd "$dir"
echo "Syncing vendor..."
go mod vendor
trap "rm -rf vendor" EXIT

docker run \
  --rm \
  -i \
  -v "$dir":/go/src/github.com/casualjim/someapp \
  -w /go/src/github.com/casualjim/someapp \
  casualjim/someapp-gqlbuilder "$@"
```

**Comment by soupdiver** [comment]
ok, thanks for clarification 👍

**Comment by mdiesen** [comment]
> let's not call not supporting experimental features a major issue.
With all respect I think it should be considered a major issue since it is a feature that is in the roadmap of Go and more and more projects are using it. Not supporting it will be a good reason to not use go-swagger and choose another tool instead.

**Comment by casualjim** [comment]
feel free to add it. This is not a company sponsored project, so if you feel strongly about something send a PR. In the 4 years this project has existed, I've rejected 5 PR's.
Good luck.

**Comment by bcomnes** [comment]
I found a really cool pattern for go-swagger and go modules: versioning the go-swagger CLI with your mod file!
- https://github.com/netlify/open-api/blob/master/go.mod#L23 The pinned version of go-swagger
- https://github.com/netlify/open-api/blob/master/tools.go The stub tools.go that causes the bin to be tracked in go.mod
- https://github.com/netlify/open-api/blob/master/generate.go A generate directive so `go generate` generates the swagger types and plumbing files
- https://github.com/netlify/open-api/blob/master/Makefile A make file for a common entry-point to the project
- https://github.com/go-modules-by-example/index/tree/master/010_tools the tools.go pattern explained
- https://github.com/go-modules-by-example/index/tree/master/017_using_gobin the gobin helper tool which lets you easily run a specific version of tools locally (sort of like npm devDependecies)

**Comment by karthikraobr** [comment]
Can someone please tell me if they got this working or any known workarounds?

**Comment by joseluisq** [comment]
@karthikraobr for mw works this one https://github.com/swaggo/swag

**Comment by casualjim** [comment]
Version on master works fine with go modules

**Comment by fredbi** [comment]
Let's close this now: all go-swagger features are now supporting go modules.
A known limitation remains regarding generating code outside GOPATH, which is due to our reliance on goimports. This is followed up in dedicated issues.
