### ISSUE TITLE
Don't set query params if they are nil

### ISSUE THREAD

**Issue by jawspeak** [go-swagger/go-swagger#174]
currently (just fetched latest and re-generated my client), all query params are sent to the server if they are in the swagger spec, even if they are marked `allowEmptyValue`.

See `<sample>_parameters.go`:
```
	// query param role.1
	var qrRole1 string
	if o.Role1 != nil {
		qrRole1 = *o.Role1
	}
	qRole1 := qrRole1
	if err := r.SetQueryParam("role.1", qRole1); err != nil {
		return err
	}
```

Reason this is useful:
- some servers will break if you send up a param without a value, because they do validation on the value.
- today as it is implemented, it will *always* send the query param up. we'd rather not send it if it is null.

Looks like the relevant generator code is: `go-swagger/generator/templates/client/parameter.gotmpl`:
```
  {{ if .IsQueryParam }}
  // query param {{ .Name }}
  {{ if .IsNullable }}var qr{{ pascalize .Name }} {{ .GoType }}
  if {{ .ValueExpression }} != nil {
    qr{{ pascalize .Name }} = *{{ .ValueExpression }}
  }{{ else }}qr{{ pascalize .Name }} := {{ .ValueExpression }}{{ end}}
  q{{ pascalize .Name}} := {{ if .Formatter }}{{ .Formatter }}(qr{{ pascalize .Name }}){{ else }}qr{{ pascalize .Name }}{{end}}{{ if not .AllowEmptyValue }}
  if q{{ pascalize .Name }} != "" { {{ end }}
  if err := r.SetQueryParam({{ printf "%q" .Name }}, q{{ pascalize .Name }}); err != nil {
    return err
  }
  {{ if not .AllowEmptyValue }}}{{ end }}
```

Fixed code for my query param "username.2" in the `<sample>_parameters.go` generated code:
```
	// query param username.2
	var qrUsername2 string
	if o.Username2 != nil {
		qrUsername2 = *o.Username2
	}
	qUsername2 := qrUsername2
	if (o.Username2 != nil) {
		if err := r.SetQueryParam("username.2", qUsername2); err != nil {
			return err
		}
	}
```

**Comment by casualjim** [comment]
when a value is marked allowEmptyValue then the key should be sent. It is a hint for nullability, for some applications the absence of a key is treated different from the absence of a value.  

So is the issue you're describing here with an allowEmptyValue of true or false?

**Comment by jawspeak** [comment]
Thanks - Here the value of allowEmptyValue is true.

**Comment by casualjim** [comment]
then I'm the code that is generated is the code that it should generate. If you don't want it to add the key to the request, the spec should be defined with not required and   allowEmptyValue of false.

**Comment by casualjim** [comment]
can this be closed?

**Comment by casualjim** [comment]
going with yes because of crickets
