### ISSUE TITLE
question about authentication tutorial 

### ISSUE THREAD

**Issue by greenpau** [go-swagger/go-swagger#1741]
## Problem statement

Initially, the tutorial in [here](https://github.com/go-swagger/go-swagger/tree/master/examples/authentication) was not working for me.

I am generating the code in the following way:

```
APP_NAME=app
PKG_DIR=internal/pkg/app
swagger generate server -A $APP_NAME -P models.Principal -f ./swagger.yml --target=$PKG_DIR --exclude-main
```

My relevant spec lines looked like this:

```
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token

definitions:
  Principal:
    type: string
```
After generating the server, I don't see any function with `models.Principal` parameters being generated.

Next, realized that I need [this](
https://github.com/go-swagger/go-swagger/blob/master/examples/authentication/swagger.yml#L19-L20). 

```
security:
- key: []
```

Question: How is that `security` section working? what is that `key` list?

Additionally, per the tutorial, I don't think `api.KeyAuth` applies anymore, because it changed to `APIKeyAuthenticator` 🤔

## Swagger specification

N/A

## Steps to reproduce

Run:

N/A

## Environment

N/A

**Comment by greenpau** [comment]
By default, when employing `apiKey`, the request without a token would fail, i.e.:

```json
{"code":401,"message":"unauthenticated for invalid credentials"}
```

However, it would be nice if a request without the token would be treated as anonymous, i.e. some default token would be attached to it.

**Comment by fredbi** [comment]
Top level `security` object is the swagger specification for default security requirements for endpoints.
This is not mandatory and you may define or override this at the operation level.

`key`here refer to the definition given in the spec for a security scheme. In this spec, this is api keys.

See also https://swagger.io/docs/specification/2-0/authentication/api-keys/

We generate operations with a principal params only for those with a security requirement.

`APIKeyAuthenticator` is the generated name for the authentication function, which you have to supply.

For optional authentication, have you tried this?
```yaml
security:
- key: []
- {}
```

**Comment by casualjim** [comment]
There should be a KeyAuth method which is shorthand

https://github.com/go-swagger/go-swagger/blob/master/examples/authentication/restapi/operations/auth_sample_api.go#L89-L91

**Comment by greenpau** [comment]
For the reference, I did some research here. 

The "invalid credentials" comes from https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L425.

Here, there is something that deals with anonymous https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L421.

**Comment by greenpau** [comment]
@fredbi , I did what you said.

```
security:
- key: []
- {}
```

However, when a token is not being passed, the server does not have Principal. It bypassed it. I was thinking more along the lines of having a principal, but let that principal be anonymous.

```
package general

import (
	errors "github.com/go-openapi/errors"
	models "github.com/greenpau/ipdistro/internal/pkg/ipdistro/models"
)

// APIKeyAuthHandler handles token-based authentication.
func APIKeyAuthHandler(token string) (*models.Principal, error) {
	if token == "xyz" {
		prin := models.Principal(token)
		return &prin, nil
	}
	return nil, errors.New(401, "invalid api token '"+token+"'")
	//prin := models.Principal("anonymous")
	//return &prin, nil
}
```

Here, the above code will not be triggered if token does not exist.

**Comment by greenpau** [comment]
[Here](https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L420), we perform authentication.

When, no token is being passed, `usr` is:

```
(interface {}) <nil>
```

When it is being passed, then `usr` is a pointer to `models.Principal`.

```
(*models.Principal)(0xc4201e6330)((len=3) "xyz")
```

Perhaps, [`route.Authenticators.Authenticate`](https://github.com/go-openapi/runtime/blob/master/middleware/router.go#L254-L281) can return `anonymous` principal when authenticating without a key. Specifically, 

Perhaps, having it [here](https://github.com/go-openapi/runtime/blob/master/middleware/router.go#L278) as:

```
prin := models.Principal("anonymous")
return true, &prin, lastError
```

instead of:

```
return true, nil, lastError
```

be better?

**Comment by greenpau** [comment]
but then `models` are unavailable there...

**Comment by greenpau** [comment]
Perhaps, having something like this for anonymous access would work 🤔 🤔 💭 :

```golang
	api.AnonymousAuth = func() (*models.Principal, error) {
		prin := models.Principal("anonymous")
		return &prin, nil
	}
```

**Comment by greenpau** [comment]
the issue is https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject does not have Security Scheme Object `type` of `anonymous`.

**Comment by greenpau** [comment]
At the end, I decided to simply check whether `usr` is `nil`. If a function can be invoked anonymously, I omit `usr == nil`, else I throw an error.

```golang
// GetAPIInfoHandler handles request for API information.
func GetAPIInfoHandler(usr *models.Principal, appVersion, appContact, appDocumentation string) middleware.Responder {
	if usr == nil {
		return &GetUnauthorized{
			Payload: &models.Error{
				Code:    "401",
				Message: "Unauthorized. Authentication Required.",
			},
		}
	}
	response := NewGetOK()
	response.Payload = &models.APIInformation{
		Contact:       appContact,
		Version:       appVersion,
		Documentation: appDocumentation,
	}
	return response
}
```

**Comment by casualjim** [comment]
you can rewrite errors in the ServeError callback it's available in the configure_xxx.go file

By default we use this implementation: https://github.com/go-openapi/errors/blob/master/api.go#L121
you can augment it by wrapping the function and adding your own rewrites

**Comment by greenpau** [comment]
> you can rewrite errors in the ServeError callback it's available in the configure_xxx.go file

@casualjim , how does it help in my use case? My apologies for not able to connect the dots. I tried, but don't see it yet.

By, `configure_xxx.go`, do you mean this?

```golang
    // configure the api here
    api.ServeError = errors.ServeError
```

**Comment by casualjim** [comment]
it seems you just want to return errors for non authenticated users, but weren't happy with the error message.
in that case you shouldn't allow for optional authentication but you can let our framework handle the rejection and customize the error message

**Comment by greenpau** [comment]
@casualjim , I was thinking about what you said above. The use case I was thinking about is that I want some of GET request (informational stuff) be anonymous, i.e. no authentication, and the rest be authenticated via token based mechanism. Also, let's say I want service static content, i.e. through middleware, like https://github.com/go-swagger/go-swagger/issues/1375. I want it also without authentication.

**Comment by casualjim** [comment]
O sure the use cases for it are plentiful. I was just responding to the examples in this thread and offering some more options.
