### ISSUE TITLE
skipping -A/--name option in generate server generates corrupt code

### ISSUE THREAD

**Issue by remster** [go-swagger/go-swagger#1746]
## Steps to reproduce
```
swagger generate server -f ./swagger.yaml ./generated --exclude-main 
go generate ./...
...
expected argument for flag `-A, --name', but got option `--spec'
restapi/configure_example_swagger_server.go:16: running "swagger": exit status 1
```
This is due to corrupt `go generate` line in restapi/configure_example_swagger_server.go:
`//go:generate swagger generate server --target .. --name  --spec ../swagger.yaml --exclude-main`

## Environment
swagger version: 
dev 
```
commit 44342aefb3ce6216edd146bcf4e6ab63d5a15eca (HEAD -> master, origin/master, origin/HEAD)
Author: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
Date:   Sun Oct 7 14:18:32 2018 +0200

    Handle relative path when using Go modules
    
    Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>

```
go version: 
go version go1.11 linux/amd64

**Comment by fredbi** [comment]
Just curious about the swagger spec you provided the generator with.

Name is taken;
- either from the spec Title
- or the --name CLI param
- or defaults to swagger

**BUT**

suffixes like 'API', 'Test' are trimmed.

so my guess is that you put in a title like 'test' or 'api' and end up with an empty name.

**Comment by remster** [comment]
here's the start of the spec:
```
swagger: "2.0"
info:
    description: "Documentation for Example Swagger Server."
    version: "1.0.0"
    title: "Example Swagger Server"
schemes:
- "http"
paths:
  /{snippetID}/{left}/{right}:
    get:
      summary: Get Snippet with snippetID between left and right
      operationId: getSnippet
      produces:
      - "application/octet-stream"
      parameters:
      - name: snippetID
        in: path
        description: "Snippet ID"
```

**Comment by fredbi** [comment]
Weird. Is it possible that the `configure_xxx` comes from a previous generation with different settings?
How about removing it and generating again? 

Empty Genopts.Name can also be figured out with --dump-data option.

**Comment by fredbi** [comment]
Yes. Reproduced.

**Comment by fredbi** [comment]
this is indeed a bug. 
I think that forcing `opts.Name` somewhere around https://github.com/go-swagger/go-swagger/blob/44342aefb3ce6216edd146bcf4e6ab63d5a15eca/generator/support.go#L123

would solve the issue

Something like:
```go
    opts.Name = appNameOrDefault(specDoc, name, "swagger")
```

**Comment by fredbi** [comment]
I could fix it. Note that the go generate commands also fails when `--target` != "" (not fixed)

**Comment by akhobov** [comment]
The proposed fix changes the value of the name if it is provided.

Example:
`swagger generate server --target server --name example-name --spec server/swagger.yaml`

Will lead to Name being set to "ExampleName":
`//go:generate swagger generate server --target ../server --name ExampleName --spec ../server/swagger.yaml`

Not sure that is intended behaviour to change a value explicitly provided via the tool parameters.
Should it be changed to something like the following?
```
if opts.Name == "" {
    opts.Name = appNameOrDefault(specDoc, name, "swagger")
}
```

**Comment by fredbi** [comment]
The value is altered as follows:
```go
return strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(swag.ToGoName(name), "Test"), "API"), "Test")
```
