### ISSUE TITLE
question: in-memory data store

### ISSUE THREAD

**Issue by greenpau** [go-swagger/go-swagger#1747]
## Problem statement

I want to store objects in memory, as opposed externally, e.g. database, and have them available in handlers. The object store should have some locking capability, e.g. `sync.Mutex`.

What is the recommended way of implementing this?

**Comment by greenpau** [comment]
For example, one type of objects are user-token mappings. Let's say prior to starting a server, I load token-to-principal mapping in in-memory data store and then, using the tokens I authenticate/authorize requests. The user-token mappings would not be in the database, but only in-memory.

**Comment by fredbi** [comment]
have you looked at the KV store example ?
https://github.com/go-openapi/kvstore
By and large this is the same idea, just not using memory but a KV store instead.

**Comment by greenpau** [comment]
@fredbi , I did consider that. I can do it externally with Consul and libkv, but I want in-memory 😃 It is almost the same as storing credentials in mongodb.

**Comment by casualjim** [comment]
take a look here: https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go

it does that for todo's

You can also use go's sync.Map instead, it will be more performant in high contention scenarios

**Comment by greenpau** [comment]
@casualjim , @fredbi , thank you for the pointers! 👍
