### ISSUE TITLE
Deb installation is broken with the new version with the "v" prefix

### ISSUE THREAD

**Issue by vkuptcov** [go-swagger/go-swagger#1760]
## Problem statement
I have go-swagger installed from the debian package according to the instruction https://goswagger.io/install.html
I'm trying to update it and receive the next error:
```
$ sudo apt-get install swagger 
...
The following packages will be upgraded:
  swagger
1 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
...
dpkg: error processing archive /var/cache/apt/archives/swagger_v0.17.0_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'swagger':
 error in 'Version' field string 'v0.17.0': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/swagger_v0.17.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
It happens because the new version has the `v` prefix `v0.17.0`, and the previous does not: `0.16.0`

## Environment
swagger version: v.0.17.0
OS:   Ubuntu 18.04

**Comment by AgrimPrasad** [comment]
Saw this issue too on our build. Should change the new version name to 0.17.0

**Comment by gregmarr** [comment]
The `v` was added for compatibility with the new Go modules.

**Comment by casualjim** [comment]
I'll update our build script so the debs end up with the expected format

**Comment by AgrimPrasad** [comment]
@casualjim Thanks, please let us know when it's fixed. We just re-tried the build and saw the same error again.

```
dpkg: error processing archive /tmp/apt-dpkg-install-7BKFfX/7-swagger_v0.17.0_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'swagger':
 error in 'Version' field string 'v0.17.0': version number does not start with digit
```

**Comment by fredbi** [comment]
Look for the latest release: on bintray, I can see the package name is now `swagger_0.17.2_amd64.deb`

**Comment by AgrimPrasad** [comment]
To clarify the comment above, I mean can we remove swagger_v0.17.0_amd64.deb from bintray?

**Comment by casualjim** [comment]
I think i've done that now

**Comment by AgrimPrasad** [comment]
Thanks! Works great. I believe we can close this issue now.

**Comment by vkuptcov** [comment]
I've just checked the new package `0.17.2` and it doesn't contain binary. And the package size a bit smaller  than it should be:
```
/var/cache/apt/archives# ls -lah swagger_*
-rw-r--r-- 1 root root  996 окт 25 05:04 swagger_0.17.2_amd64.deb
-rw-r--r-- 1 root root 5,2M окт  7 06:34 swagger_v0.17.0_amd64.deb
```

**Comment by AgrimPrasad** [comment]
Yes sorry, I didn't check the new package earlier. It indeed doesn't contain the binary. Could it be checked again please?

**Comment by AgrimPrasad** [comment]
Any updates on the missing binary issue? Or should I create a separate issue for that?

**Comment by vkuptcov** [comment]
I've just checked the package
https://dl.bintray.com/go-swagger/goswagger-debian/:swagger_0.17.2_amd64.deb
The binary is still missed.

**Comment by AgrimPrasad** [comment]
Created https://github.com/go-swagger/go-swagger/issues/1793 for the missing binary issue, as that's different from the issue title here, and the original issue mentioned here has indeed been fixed.

**Comment by casualjim** [comment]
i've just updated the deb file
