### ISSUE TITLE
Logger and traceId in swagger

### ISSUE THREAD

**Issue by gianarb** [go-swagger/go-swagger#1768]
Question:

I am doing some work to integrate tracing in my applications. Everything is working not too bad, I created a middleware that uses opentracing and it adds the `X-Trace-Id` in the response.

I am using `zap` as logger and I would like to get a configured logger for every handler that has the trace_id injected as default field.

With zap or logrus you can create logger with fixed fields that are printed as key=value every time you use that logger. 

Do you have an idea about the best approach for that? Thanks

**Comment by fredbi** [comment]
Have you looked at #1752 ?

**Comment by gianarb** [comment]
I think it is not what I am looking for. I can write a middleware to log all the requests printing the traceId, but what I would like to have is a configured logger inside my handle function.

So probably the easy fix is to write a middleware that takes the trace_id and it writes it inside the `context` request, in this way I can get it back in the handle.

**Comment by gianarb** [comment]
I fixed the issue using the context and a middleware, I passed the trace_id in the context and I got it back in the handle func

**Comment by fredbi** [comment]
Well done. This kind of question is recurring among go-swagger users.
Feel free to push a PR with a working example of your findings.
