### ISSUE TITLE
It can not stop with recursive struct

### ISSUE THREAD

**Issue by dailygoing** [go-swagger/go-swagger#1773]
It can not stop with it comes to recursive struct.

## Environment
swagger version: 1.4.0 
go version:1.11
OS:   mac

**Comment by casualjim** [comment]
more info is required. like your spec

**Comment by fredbi** [comment]
Closing because stalled without any info.

All known hanging issues with circular references are now fixed.
@dailygoing feel free to reopen if you are still facing issues.
