### ISSUE TITLE
Are external references supported?

### ISSUE THREAD

**Issue by ok11** [go-swagger/go-swagger#1774]
It may have some relation to #1767, but since the diagnostic is a bit different, I opened a new issue.

## Problem statement

When one tries to use `$ref`, pointing to another file (residing locally) as shown in the [gist](https://gist.github.com/ok11/6366b620192278b677cba169fc4c6db2) (everything is in a `def` directory, api.yaml, Data.yaml, ...), go-openapi calls a panic at runtime:

```
ok11@home:~/workspace/bb-go/userservice/cmd/service$ go run main.go
panic: Invalid schema provided to SchemaValidator: open /home/ok11/workspace/bb-go/userservice/cmd/service/Data.yaml: no such file or directory

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc0001a6d80, 0x8cbe40, 0xc0001d0100, 0xc000311b68, 0x7, 0x9d6b00, 0xc0001f8db0, 0xc000313e00)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/validate@v0.17.0/schema.go:71 +0xf42
github.com/go-openapi/runtime/middleware.newUntypedParamBinder(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/parameter.go:46 +0x18c
github.com/go-openapi/runtime/middleware.newUntypedRequestBinder(0xc000313e00, 0xc0001d0100, 0x9d6b00, 0xc0001f8db0, 0xc0001cc060)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/request.go:39 +0x196
github.com/go-openapi/runtime/middleware.(*defaultRouteBuilder).AddRoute(0xc000313da0, 0x935b9a, 0x3, 0xc000556bc0, 0x20, 0xc0001a4380)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/router.go:432 +0x4cc
github.com/go-openapi/runtime/middleware.DefaultRouter(0xc0000ca140, 0x9d7880, 0xc00009e580, 0x8c8360, 0xc000168970)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/router.go:139 +0x14c
github.com/go-openapi/runtime/middleware.NewRouter(0xc000313830, 0x9d1a20, 0xc000168970, 0xc000168970, 0xc000518340)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/router.go:71 +0xe2
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler(0xc000313830, 0x964488, 0xc000518320, 0xc0000ca320)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/context.go:581 +0x7c
github.com/go-openapi/runtime/middleware.(*Context).APIHandler(0xc000313830, 0x0, 0xc000313201, 0xc0000ca410)
        /home/ok11/workspace/go/pkg/mod/github.com/go-openapi/runtime@v0.17.0/middleware/context.go:572 +0xfa
github.wdf.sap.corp/bb-go/userservice/pkg/api/rest/gen/restapi/operations.(*UserServiceAPI).Serve(0xc00009e580, 0x0, 0x27e5, 0x0)
        /home/ok11/workspace/bb-go/userservice/pkg/api/rest/gen/restapi/operations/user_service_api.go:389 +0x80
github.wdf.sap.corp/bb-go/userservice/pkg/api/rest/gen/restapi.Handler(0x9d0820, 0xc000416f80, 0x9d66e0, 0xc000416f80, 0x964808, 0x0, 0x0, 0xc000416fc0, 0x964558, 0xc830d44fc000b480, ...)
        /home/ok11/workspace/bb-go/userservice/pkg/api/rest/gen/restapi/configure_user_service.go:134 +0x71a
main.main()
        /home/ok11/workspace/bb-go/userservice/cmd/service/main.go:15 +0x1a6
exit status 2
```
The panic message prints out a wrong path (it must be not at the path where `main.go` resides and which basically represents the `pwd`, but rather `pkg/api/rest/def`). But even if it were the right path, it is still weird. What I usually distribute, is an executable, not the entire design-time stuff. And YAML API definitions are rather design time, aren't they? How a compiled executable should find them after the distribution?

So, my question is, do you (go-swagger and/or go-openapi) support this scenario at all? I have not found any tests that verify that.

After having put all references inside the file (`#/definitions` etc) everything works just fine.

## Swagger specification

See [gist](https://gist.github.com/ok11/6366b620192278b677cba169fc4c6db2). It is a collection of files, all residing in a `def` directory

## Steps to reproduce

`swagger generate server --spec=pkg/api/rest/def/api.yaml --model-package=dto --template=stratoscale --template-dir=pkg/api/rest/templates --name=UserService --target=pkg/api/rest/gen --exclude-main --with-flatten=full`
Yes, it is custom templates. If you want me to redo it with default templates, please let me know.

## Environment
swagger version: 0.17.0  
go version: 1.11  
OS:  Windows 10 (Linux Subsystem/Ubuntu 18.04)

**Comment by fredbi** [comment]
This is a different kind of issue. Specs served with `swagger serve` should be self-contained. Preprocess them with the `flatten` command if needed.

**Comment by seblegall** [comment]
Oh ! thx for the tips !
