### ISSUE TITLE
Allow empty string for authorizationUrl in security definition

### ISSUE THREAD

**Issue by surajbarkale** [go-swagger/go-swagger#1775]
## Problem statement

Google Cloud Endpoints [requires `authorizationUrl` to be empty](https://cloud.google.com/endpoints/docs/openapi/authenticating-users#configuring_esp_to_support_client_authentication) in the specified swagger document.

According to the [swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-15) `authorizationUrl` value SHOULD be in the form of a URL. 

In the v0.17.2 release, `swagger validate` fails if authorizationUrl is empty. I am creating this issue to allow exception for empty value in authorizationUrl.

## Swagger specification

https://github.com/GoogleCloudPlatform/golang-samples/blob/master/endpoints/getting-started/openapi.yaml

## Steps to reproduce

Execute `swagger validate` on the provided schema.

## Environment
swagger version: 0.17.2

**Comment by fredbi** [comment]
This field is required by Swagger. In the  spec model, this attribute is not represented as a pointer, so required means non empty string.

Since this is just a documentary field for go-swagger, it is possible to fix this field from your original spec using `swagger mixin`, specifying a non empty string.

**Comment by fredbi** [comment]
I think we have had the very same kind of issue some time ago with empty response descriptions.

So there is a "spec fixer" just for go in go-openapi/analysis. Unfortunately, this does not fix security schemes attributes at the moment.

**Comment by cyu521** [comment]
any update on this? running into the same issue. thanks!

**Comment by fredbi** [comment]
@casualjim we could make the required attribute a point in go-openapi/spec, but I am wondering how much breakage this would lead us into. Similar reasoning applies for Reponse.Description. All-in such changes would allow us to deprecate the "spec fixer" in go-openapi/analysis.

**Comment by casualjim** [comment]
we can remove omitempty, that should be fine. It would solve this issue and shouldn't break anything

**Comment by nishatdhillon** [comment]
Guys any movement on this issue ?

**Comment by nishatdhillon** [comment]
@fredbi @casualjim Is this pull request going to be merged ?

**Comment by fredbi** [comment]
@nishatdhillon merged in go-openapi/spec

**Comment by kenjones-cisco** [comment]
> we can remove omitempty, that should be fine. It would solve this issue and shouldn't break anything
This change is now causing an issue, where `"authorizationUrl": ""` is now being added by `swagger mixin` even though the original API spec is of type `apiKey` and did not originally include it.

This has now broken all of my code generations.

**Comment by fredbi** [comment]
@kenjones-cisco thanks for reporting. I am going to patch the mixin. I've already repatched spec to avoid invalid specs to be marshalled as json (not merged yet...).
