### ISSUE TITLE
non-compiling code if an API method contains a parameter named 'result'

### ISSUE THREAD

**Issue by mtfelian** [go-swagger/go-swagger#1778]
## Problem statement

Compilation of generated code fails if an API method contains a parameter named 'result'.

## Swagger specification

```
  /some/api/path:
    get:
      description: "Something"
      operationId: SomeOperation
      tags: ['sometag']
      produces:
      - application/json
      parameters:
      - {$ref: '#/parameters/page'}
      - {$ref: '#/parameters/pagesize'}
      - name: type
        in: query
        description: some description of type parameter
        type: array
        items:
          type: string
        collectionFormat: csv
      - name: result
        in: query
        description: some description of result parameter
        type: array
        items:
          type: boolean
        collectionFormat: csv
```

## Steps to reproduce

Generate the spec and try to compile the code.

## Environment
swagger version: 0.17.2  
go version: 1.11.1  
OS:   Windows 10, Ubuntu 14

## Additional
Problem lies in method Build() :
```
result.Path = golangswaggerpaths.Join(_basePath, _path)
...
result := swag.JoinByFormat(resultIR, "")

	if len(result) > 0 {
		qsv := result[0]
		if qsv != "" {
			qs.Set("result", qsv)
		}
	}
```

**Comment by fredbi** [comment]
The cause of this issue can be found (and repaired) here: https://github.com/go-swagger/go-swagger/blob/800a3052f0305ab54980f961bd4f1e8b3e5599fe/generator/templates/server/urlbuilder.gotmpl#L142

**Comment by mtfelian** [comment]
@fredbi what is the right way in this repo to cover things like this with tests? Fast view on it have not bring understanding.

**Comment by casualjim** [comment]
For this use case we normally add a s spec under fixtures/bugs/[issue-number] and then we make a test that verifies it generates the expected code.
