### ISSUE TITLE
Howto disable go-openapi/runtime Redoc middleware

### ISSUE THREAD

**Issue by riaan53** [go-swagger/go-swagger#1779]
## Problem statement
Hi, is there a way to disable redoc documentation UI (currently at `baseURL/docs`) with the default included middleware. My API server is in a security sensitive environment which does not allow resources to be pulled (or try to as it will be blocked) from the open internet (the JS file from github included in the template).

## Steps to reproduce
Normal `swagger generate server -f swagger.yml` and browse to baseUrl/docs

## Environment
swagger version: v0.17.1 
go version: go1.11.1 darwin/amd64
OS:   macOS High Sierra

**Comment by casualjim** [comment]
You can change the Middleware property on the api context.

https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/restapi/operations/todo_list_api.go#L75

This property is used here:
https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/restapi/operations/todo_list_api.go#L326

By default we run this middleware stack: 
https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L555-L573

But all the methods are exported so you can recompose it however you need

**Comment by riaan53** [comment]
@casualjim Thank you! :)
