### ISSUE TITLE
Invalid paths in go generate directive

### ISSUE THREAD

**Issue by blez** [go-swagger/go-swagger#1789]
## Problem statement
Invalid path in go generate directive in `generated/restapi/configure*.go` file

## Steps to reproduce
1. Run swagger generate
`swagger generate server -f ./swagger.yaml -t ./generated --exclude-main`
2. Go to `generated/restapi/configure*.go`
There I have comment
```
//go:generate swagger generate server --target ../generated --name ExampleSwaggerServer --spec ../swagger.yaml --exclude-main
```
Which is not right, because `swagger.yaml` and `generated` directory are 2 levels up, but not one.
If you try to run go generate you will get an error `couldn't find a swagger spec`
So comment should be
```
//go:generate swagger generate server --target ../../generated --name ExampleSwaggerServer --spec ../../swagger.yaml --exclude-main
```

## Environment
swagger version: v0.17.2
commit: 800a3052f0305ab54980f961bd4f1e8b3e5599fe
go version: 1.10.3
OS:   Ubuntu

**Comment by fredbi** [comment]
That's right.
This statement is defined here in templates: 
https://github.com/go-swagger/go-swagger/blob/be966a22e91309b7ed8d57d20e737ab5b3861cbd/generator/templates/server/configureapi.gotmpl#L28

The `generate_xxx.go` is actually put in {{ ServerPackage }} relative to {{ TargetPath }}
