### ISSUE TITLE
Deb version 0.17.2 doesn't contain the binary on bintray

### ISSUE THREAD

**Issue by AgrimPrasad** [go-swagger/go-swagger#1793]
## Problem statement

Follow-up from https://github.com/go-swagger/go-swagger/issues/1760#issuecomment-434374229

The newest package 0.17.2 at https://dl.bintray.com/go-swagger/goswagger-debian/ doesn't contain the binary and the package size is much smaller than it should be.

```
/var/cache/apt/archives# ls -lah swagger_*
-rw-r--r-- 1 root root  996 окт 25 05:04 swagger_0.17.2_amd64.deb
-rw-r--r-- 1 root root 5,2M окт  7 06:34 swagger_v0.17.0_amd64.deb
```

## Environment
swagger version: 0.17.2
OS: Ubuntu 18.04

**Comment by casualjim** [comment]
I've uploaded a new deb package and verified I can install it
