### ISSUE TITLE
[Question] Debugging spec generation

### ISSUE THREAD

**Issue by ok11** [go-swagger/go-swagger#1797]
## Problem statement

According to https://github.com/go-swagger/go-swagger/blob/master/generator/debug.go, the generator shall start put out debug output if DEBUG or SWAGGER_DEBUG env variables are set to something non blank. I'm trying to debug generation of spec out of source code:
`
SWAGGER_DEBUG=1 swagger generate spec -m -o ./def/api.yaml
`
but getting no additional output. Is there anything else to be configured?

## Environment
swagger version: 0.17.1  
go version: 1.11  
OS:  Ubuntu 18.04

**Comment by fredbi** [comment]
`SWAGGER_DEBUG` works for code generation (i.e. generator package).
For spec generation, the scan package is used. Only `DEBUG` is supported here (see https://github.com/go-swagger/go-swagger/blob/5ef69e2ba5ecda3b7317a94ee570f6aea83d5939/scan/scanner.go#L173).

As you may see, it is an almost entirely independent package, and debug routines have not been factorized.

**Comment by ok11** [comment]
Thanks! Apparently I overlooked that in scanner.
