### ISSUE TITLE
Cannot download from deb

### ISSUE THREAD

**Issue by egroj97** [go-swagger/go-swagger#1798]
## Problem statement

Added repository to the list but could not finish `apt update` because of the repository, it gives the error: `E: The repository 'https://dl.bintray.com/go-swagger/goswagger-debian ubuntu Release' is not signed.`

## Steps to reproduce
```
echo "deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main" | sudo tee -a /etc/apt/sources.list
sudo apt update
```

## Environment
OS:   Ubuntu 18.04

**Comment by yiting-wang33** [comment]
Hi, I got the same issue. Did you solve it?

**Comment by rohith-vallabhaneni** [comment]
Hi, I got the same issue if I add the debian path to my /et/apt/sources.list.
When I do apt update, I encounter the following error: 

E: The repository 'https://dl.bintray.com/go-swagger/goswagger-debian ubuntu Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

There should be a way to sign the debian package, which is missing!

**Comment by fredbi** [comment]
Duplicates #1812
