### ISSUE TITLE
Random model properties

### ISSUE THREAD

**Issue by mephux** [go-swagger/go-swagger#180]
Every time I generate a client from a 2.0 swagger spec it get random properties for models. Here is the spec.json file i'm using (https://gist.github.com/mephux/474d9512cbe54411900f). Is this a model gen logic error or is my spec wrong in some fashion?

If it's a logic issue can you point me in the right direction (in the code) and i'll fix and submit a pull request.

**Comment by casualjim** [comment]
The spec you linked doesn't actually validate:

```
git:(master) ✗ !? » swagger validate https://gist.githubusercontent.com/mephux/474d9512cbe54411900f/raw/126932f41177b76df44bbd1199f22ad6a28ff2a8/kube.json
The swagger spec at "https://gist.githubusercontent.com/mephux/474d9512cbe54411900f/raw/126932f41177b76df44bbd1199f22ad6a28ff2a8/kube.json" is invalid against swagger specification 2.0. see errors :
- object has no key "integer"
```

**Comment by mephux** [comment]
@casualjim was wondering if that would be your reply.. hehe so, that would cause random property selection? Can you point me to the code for that? if proper model generation is dependent on validation.. why not just exit out completely on failure? I am using this spec now (https://gist.github.com/mephux/9181100f0cc2711cd628). I susspect the validation logic may be incorrect as well as this one returns different validation messages than what is returned from the swagger site.

**Comment by casualjim** [comment]
Currently my validator isn't super fast but you're right I should make it validate before generating and let people opt-out by specifying --skip-validation

The main reason for a spec needing to be valid is that there are a some rules that have to be followed and having a valid spec.
So in terms of figuring out what is wrong I'd say it starts with a valid spec doc :).

**Comment by mephux** [comment]
Closing - issues was a validation 2.0 inconsistency.

`"$ref": "#/definitions/integer"` VS. `"type": "integer"
