### ISSUE TITLE
Add an option for placing the docs/docs.go file

### ISSUE THREAD

**Issue by j0hnwhyte** [go-swagger/go-swagger#1811]
## Problem statement
When generating the documentation with `swag init`, there is no option to place the generated `docs` folder differently. I'm trying to separate the documentation generation code from the application code.

At the moment the folder is always placed in the directory specified with the `d` flag, which is the analysed one. I'm aiming to have a `src/` folder with the program code and a `docs/` folder with the documentation and swagger code.

Please tell me if more explanations are needed, thanks

## Environment
swagger version: 1.4.0

**Comment by fredbi** [comment]
Could you please mention your full command line?

**Comment by fredbi** [comment]
You are probably referring to the swaggo/swag CLI tool. In this case, this is not the right place to report errors.

**Comment by j0hnwhyte** [comment]
I'm sorry, I'll delete this
