### ISSUE TITLE
Please add GPG Public Key to deb repo

### ISSUE THREAD

**Issue by jidckii** [go-swagger/go-swagger#1812]
## Problem statement

Please add GPG Public Key to deb repo    
apt does not allow installing packages according to apt-secure policy
#### 
[example](http://i.imgur.com/mJCaS97.png)
[go-swagger repo](http://i.imgur.com/eKmL2ae.png)

**Comment by goldyfruit** [comment]
Any update about this ?

**Comment by casualjim** [comment]
Our artifacts are not signed. I've enabled the default bintray signing functionality. So with the next release  I think this will be fixed

**Comment by jleaders** [comment]
Thanks that, should fix this error
```
$ echo "deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main" | sudo tee -a /etc/apt/sources.list
$ sudo apt update
Reading package lists... Done        
E: The repository 'https://dl.bintray.com/go-swagger/goswagger-debian ubuntu Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by Emixam23-FCMS** [comment]
Hello,

Just got it today, any new error that might came up?
Thanks

**Comment by rdockterjr** [comment]
I also just encountered this error again today. Any idea whats causing it now?

**Comment by youyuanwu** [comment]
See https://github.com/go-swagger/go-swagger/issues/2558 for workaround.
There is some problem with the debian package source.
