### ISSUE TITLE
[Question] How to change 422 as a response code for invalid payload

### ISSUE THREAD

**Issue by ok11** [go-swagger/go-swagger#1820]
## Problem statement

In case if parameter validation fails (in my case a missing required JSON field), the validation returns HTTP response code `422 Unprocessable Entity`. Response code `422 `is not something I model in my Open API spec, but apparently a framework decision.
In fact, `422` does not belong to the basic response codes as defined by RFC7231 (not listed there), but rather it is specific to RFC4918, which describes WebDAV. WebDAV is a very specific extension to HTTP and basically clients that expect a pure HTTP protocol are normally unaware about extended methods and response codes. So I would stick to RFC7231 semantics and return here `400 Bad Request` instead.
Is it possible to configure the response code for a payload validation scenario?

## Environment
swagger version: 0.17.2 
go version: 1.11 
OS:  Ubuntu 18.04

**Comment by fredbi** [comment]
code 422 is set in go-openapi/errors.
You can change the behavior of this package

**Comment by fredbi** [comment]
That was what I had in mind, yes.
