### ISSUE TITLE
Regression with gob encoder optimization

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1824]
## Problem statement

Since go-openapi/loads adopted gob to deep clone specs (commit: https://github.com/go-openapi/loads/pull/19/commits/0d17535daa37578ec3b60494288bd3164cb9a36b), some regressions occurred on spec objects which have custom json marshalling.

A first regression on "$ref" (bug: #1816) has been fixed with #1818.

Another one on "security" object has been found when analyzing #1817.

We need to add some more GobEncode/GobDecode in go-openapi/spec to ensure this optimization causes no more regression.

## Swagger specification
https://github.com/go-swagger/go-swagger/blob/master/examples/generated/swagger.json

## Steps to reproduce
Regenerate examples, observe diff.
Observe that:
```yaml
security: 
  api_key: []
```

becomes:
```yaml
security: 
  api_key: null
```
## Environment
swagger version:  current master
go version: 1.11
OS:   ubuntu

**Comment by fredbi** [comment]
Also fails with custom extensions in spec....

**Comment by fredbi** [comment]
@orisano this fixes some issues with your optimization. However I am not quite familiar with gob encoding shenanigans and I found out I had to write much code to wok around those issues (see go-openapi/spec#88). If you have a better idea on how to implement this, you're more than welcome.

**Comment by orisano** [comment]
sorry... my optimization was too wrong.
Try use https://github.com/mohae/deepcopy.
sorry
