### ISSUE TITLE
Question: Read Response Body

### ISSUE THREAD

**Issue by KnutAtteslander** [go-swagger/go-swagger#1825]
## Problem statement

I have the case, that some times i get a 204 from the API but the customer claims he didn't receive anything.
Now i'd like to log the response body

My send functions look like this:

	// Post feedback.
	respOK, respNC, err := c.PostErrorUsingPOST(params, bearertoken)
	if err != nil {
		return err
	}

**Comment by fredbi** [comment]
could you please elaborate on your use case?

**Comment by casualjim** [comment]
You can implement a logger that supports this interface:

https://github.com/go-openapi/runtime/blob/master/logger/logger.go#L5:6

then set it on the runtime, and turn debug logging on.

https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L425-L437

That logger can write to a file or to multiple writers with `io.MultiWriter`

**Comment by KnutAtteslander** [comment]
Nice thx! I'll try this.

**Comment by casualjim** [comment]
if you need it to be more low-level, you can use a custom RoundTripper. 

The http.RoundTripper sees the requests after we're done processing them, right before sending and it sees the responses before anything else has touched them.

**Comment by KnutAtteslander** [comment]
OK, i'll see into this if needed.
But if i can just log the debug messages for every post (idealy in a separate file per post -> new logger per post) that should suffice.
I just don't want one huge logfile -> a post can be up to 1mb and there are 3k-6k post per day
