### ISSUE TITLE
body parameter of type string results in code that doesn't compile

### ISSUE THREAD

**Issue by cswank** [go-swagger/go-swagger#1832]
## Problem statement
if you have a body parameter of type string then the settings argument in the go client code will have no type and so will not compile:

`func example(i int, settings )`

Please remove the sections that don't apply

## Swagger specification
`"parameters: [{
            "name": "a",
            "in": "path",
            "required": true,
            "type": "int"
},
{
            "name": "settings",
            "in": "body",
            "required": true,
            "type": "string"
}]`

## Environment
swagger version: 2.3.1
go version: 1.11.2
OS:   macOS

**Comment by casualjim** [comment]
body requires a schema

```yaml
- in: body
   name: settings
   schema:
      type: string
```

but if you're trying to do a form post, you should use `in: formData` instead

**Comment by cswank** [comment]
Indeed that fixed it.  Thanks!
