### ISSUE TITLE
dep ensure -v report models is missing

### ISSUE THREAD

**Issue by alydnh** [go-swagger/go-swagger#1835]
## Problem statement

Hello All

I was clone this repository from tags 0.17.2

when I run command "dep ensure -v" on windows 10

some error reported as following:

(25)            github.com/go-swagger/go-swagger/fixtures/bugs/1232/gen-fixture-1232/models is missing; required by (root).     github.com/go-swagger/go-swagger/fixtures/bugs/1548/gen-fixture-1548/models is missing; required by (root).  github.com/go-swagger/go-swagger/fixtures/bugs/1571/gen-fixture-simple-tuple-minimal/models is missing; required by (root).  github.com/go-swagger/go-swagger/fixtures/bugs/910/gen-fixture-910/models is missing; required by (root).

## Environment
swagger version:  0.17.2
go version:  go1.10.3
OS:   windows/amd64 win10

**Comment by fredbi** [comment]
Weird. This works well on UNIX: these sources for test program should be excluded because they have a +build integration tag. I am investigating further how it works on windows

**Comment by alydnh** [comment]
Dear friend,
well noted with thanks.
I will have another try and keep in touch with you if any further questions.

thank you very much again.

**Comment by fredbi** [comment]
This is now no more relevant: this repo has fully moved to go modules
