### ISSUE TITLE
Client File Upload 0 Bytes

### ISSUE THREAD

**Issue by sachnk** [go-swagger/go-swagger#1838]
## Problem statement

The generated client doesn't seem to properly upload files. When I try uploading a file via the client, the server receives 0 bytes when I try access the body.

## Swagger specification

```
swagger: "2.0"
basePath: /
schemes: 
  - http
consumes: 
  - application/json
produces: 
  - application/json

paths:
  /upload:
    post:
      tags:
      - uploads
      summary: uploads
      operationId: upload#File
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
        required: true
      responses:
        "200":
          description: OK
```

## Steps to reproduce

Generate the client from the above swagger, then try using it upload files:

```
file := ... // populate some file
client.Uploads.UploadFile(context.Background(), uploads.NewUploadFileParams().WithFile(file))
```

On my server, I do:

```
func (a *API) UploadFile(ctx context.Context, in ops.UploadFileParams) middleware.Responder {
	mybuffer := make([]byte, 1024*10)
	w, err := in.File.Read(mybuffer)
	if err != nil {
		panic(err)
	}
	fmt.Println(w)
```

This will always print `0` when I try submitting the file via the client. However, if I use Postman to submit the file, it works correctly -- it prints non-zero.

## Environment
swagger version: 0.17.2 
go version: go1.11.2 darwin/amd64
OS:  macOS

**Comment by fredbi** [comment]
This works fine now. Added an example to demonstrate this.
