### ISSUE TITLE
Duplicated parentheses

### ISSUE THREAD

**Issue by danikarik** [go-swagger/go-swagger#1839]
## Problem statement

Generated code duplicates parentheses on method call. After generation I got errors like:

```go
if swag.IsZero(m.Attachments()()) { // not required
    return nil
}
```

m.Attachments()**()** <---- duplicated

## Swagger specification

[spec](https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/swagger.yaml)

## Steps to reproduce

```sh
swagger generate client \
    --additional-initialism=SMS \
    --additional-initialism=MMS \
    --additional-initialism=FAX \
    --name=clicksend \
    --spec=https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/swagger.yaml
```

## Environment
swagger version: 0.17.2 
go version: 1.11.3 
OS: MacOS Mojave

**Comment by fredbi** [comment]
This is indeed a bug I could reproduce. It occurs with polymorphic types.

**Comment by fredbi** [comment]
Here is a fix you can fetch right away. This should be soon merged into next release.
