### ISSUE TITLE
Response unmarshalling error

### ISSUE THREAD

**Issue by danikarik** [go-swagger/go-swagger#1845]
## Problem statement

Returned response cannot be casted to type. I have similar error with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) and I opened [this issue](https://github.com/OpenAPITools/openapi-generator/issues/1500). Can you check is this same error?

## Swagger specification

[spec](https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/swagger.yaml)

## Steps to reproduce

1. Get SDK:
```sh
go get github.com/danikarik/clicksend-go
 ```
2. Register at [service](https://dashboard.clicksend.com/#/signup/step0)
3. Create [API Key](https://dashboard.clicksend.com/#/account/subaccount)
4. Call service with your credentials:
```go
package main

import (
	"log"

	"github.com/danikarik/clicksend-go/client"
	apiclient "github.com/go-openapi/runtime/client"
)

func main() {
	auth := apiclient.BasicAuth("<username>", "<API KEY>")
	srv := client.Default
	ok, err := srv.Account.AccountGet(nil, auth)
	if err != nil {
		log.Fatal(err)
	}
	log.Print(ok)
}
```
5. You will get error: **json: cannot unmarshal object into Go value of type string**
## Environment
swagger version: 0.18.0  
go version: 1.11.3
OS: MacOS Mojave

**Comment by casualjim** [comment]
The schema says the return value will be of type string, but in reality it's an object.
If you don't define the schema you should still change the type to be object instead of string.

```yaml
responses:
  200:
    description: "SUCCESS"
    schema:
      type: "string"
```

needs to become

```yaml
responses:
  200:
    description: "SUCCESS"
    schema:
      type: object
```

preferably that object actually has the properties that describe the object you're returning

You can see the output of responses by running with the env var DEBUG=1

**Comment by danikarik** [comment]
@casualjim thank you, it helped!
