### ISSUE TITLE
[Go] Client Generated Code: Type is incorrect

### ISSUE THREAD

**Issue by priyamalart** [go-swagger/go-swagger#1850]
## Problem statement

Downloaded the Go Client Code from https://forge.etsi.org/swagger/editor/?url=https://forge.etsi.org/gitlab/mec/gs011-app-enablement-api/raw/master/Mp1.yaml

Example: Types of below listed attributes should be string, but it is empty structure in the generated code.
```golang
type ServiceInfoSerName struct {
}
type ServiceInfoTransportId struct {
}
// Service version
type ServiceInfoVersion struct {
}
```
Type should be like this:
```golang
type ServiceInfoSerName string
type ServiceInfoTransportId string
type ServiceInfoVersion string:   
```

**Comment by fredbi** [comment]
Cannot reproduce this on current master, generating models for client or server from this spec.

Please provide more info about the go-swagger version you are using, your generation options etc.

**Comment by fredbi** [comment]
It is no longer possible to reproduce this, the original example API has been removed
