### ISSUE TITLE
Duplicate constants when referencing definitions with enums in another files

### ISSUE THREAD

**Issue by Napas** [go-swagger/go-swagger#1851]
## Problem statement

With given specification constants `ServerStatusOK` and `ServerStatusNotOK` are generated in the `server.go` and `server_status.go` files.

On top of that constants in `server.go` has incorrect constant types `string` instead `ServerStatus`.

## Swagger specification
swagger.yaml:
```
swagger: '2.0'

info:
  title: 'Title'
  version: '1.0'

paths:
  '/':
    get:
      responses:
        200:
          description: OK response
          schema:
            $ref: '#/definitions/Response'
    post:
      parameters:
        - in: body
          schema:
            $ref: '#/definitions/Request'
          name: filter
      responses:
        200:
          description: OK response
          schema:
            $ref: '#/definitions/Response'

definitions:
  Response:
    type: object
    properties:
      Server:
        type: array
        items:
          $ref: 'definitions.yaml#/definitions/Server'
  Request:
    type: object
    properties:
      ServerStatus:
        $ref: 'definitions.yaml#/definitions/ServerStatus'
```
definitions.yaml
```
definitions:
  ServerStatus:
    type: string
    enum: [OK, Not OK]

  Server:
    type: object
    properties:
      Name:
        type: string
      Status:
        $ref: '#/definitions/ServerStatus'
```

## Environment
swagger version: 0.18.0
go version: 1.11.1
OS:   darwin/amd64

**Comment by fredbi** [comment]
The fix is on the ways and experimental fix works not so bad. This is a delicate part, i’ll probably be done with this over the week end

**Comment by rdxmaor** [comment]
@fredbi when will it be released? any workaround to this issue meanwhile? it happens also with definitions references.

**Comment by fredbi** [comment]
@Napas @rdxmaor you may experiment with this WIP PR. Any feedback is welcome.

I have yet to figure out more testing before merging that one, since this is changing quite a bit the $ref processing in flatten.
