### ISSUE TITLE
How to use go-swagger with easyjson?

### ISSUE THREAD

**Issue by mtfelian** [go-swagger/go-swagger#1868]
## Problem statement

I want to replace the usage of standard "encoding/json" with easyjson for marshal/unmarshal operations of swagger generated models. 
We have a very big swagger.yaml. 

What should i write in a swagger schema YAML or what should i do to achieve this? 
I did not found any instruction on go-swagger website. But it seems obvious that swagger should generate slightly different files in order to enable this.

**Comment by casualjim** [comment]
easyjson is not easy

But if you want faster json you should look at https://github.com/json-iterator/go

it's faster than easyjson and works without changes

**Comment by mtfelian** [comment]
Thank you. But how to make go-swagger to generate models using either json-iterator imports instead of standard lib?

**Comment by casualjim** [comment]
just make a consumer and producer with the jsoniter marshal/unmarshal

https://github.com/go-openapi/runtime/blob/master/json.go

**Comment by mtfelian** [comment]
Oh yes thanks i just forgot about this can be easily interchanged.
