### ISSUE TITLE
Can't docker pull the latest versions by tag

### ISSUE THREAD

**Issue by drorg-stratoscale** [go-swagger/go-swagger#1871]
Can't docker pull the latest versions by tag.

For tags v0.17.0, v0.17.1, v0.17.2, v0.18.0 getting following error:

$  docker pull quay.io/goswagger/swagger:0.17.0
Error response from daemon: manifest for quay.io/goswagger/swagger:0.17.0 not found
$  docker pull quay.io/goswagger/swagger:0.17.1
Error response from daemon: manifest for quay.io/goswagger/swagger:0.17.1 not found
$  docker pull quay.io/goswagger/swagger:0.17.2
Error response from daemon: manifest for quay.io/goswagger/swagger:0.17.2 not found
$  docker pull quay.io/goswagger/swagger:0.18.0
Error response from daemon: manifest for quay.io/goswagger/swagger:0.18.0 not found

Thanks,
Dror

**Comment by gregmarr** [comment]
You're missing the `v` in the tag names in your pull.

**Comment by drorg-stratoscale** [comment]
I see... all tags before 17 are without 'v', and all tags from 17 with 'v' :-)
Thanks.

**Comment by casualjim** [comment]
yeah so people can use us with go modules
