### ISSUE TITLE
Why is docker image "latest" NOT aligned with the latest tag?

### ISSUE THREAD

**Issue by drorg-stratoscale** [go-swagger/go-swagger#1873]
Hi, 
As for now, on https://quay.io/repository/goswagger/swagger?tab=tags docker image "latest" is aligned with v0.17.0 even though there are newer tags (v0.18.0 for example). Why is it not aligned with latest tag?
Thanks,
Dror

**Comment by marians** [comment]
I'd add my plus one here for making `latest` point to the most recent release.

**Comment by fredbi** [comment]
This is a regression caused by the following change [here](https://github.com/go-swagger/go-swagger/blob/60799a064e145861c874624944e9668d0aa47dd5/hack/deploy.sh#L73):
> docker push quay.io/goswagger/swagger
became:
>docker push quay.io/goswagger/swagger:$CIRCLE_TAG
