### ISSUE TITLE
swagger mixin sends all output to stderr

### ISSUE THREAD

**Issue by xadcoh** [go-swagger/go-swagger#1878]
## Problem statement

`swagger mixin` sends all output to stderr

## Steps to reproduce

run `swagger mixin` and send output to file `swagger mixin -o blablabla some.swagger.json other.swagger.json > output`

`output` will be empty

run `swagger mixin` and send stderr to file `swagger mixin -o blablabla some.swagger.json other.swagger.json 2> output`

`output` will have all of command output

## Environment
swagger version: dev/0.18.0
go version: go1.10.8 linux/amd64
OS: alpine linux docker container

**Comment by fredbi** [comment]
Yes the `-o` flag is conflicting. We plan to remove this flag.
