### ISSUE TITLE
Spec generation - Multiple File Upload with multipart form

### ISSUE THREAD

**Issue by pkosiec** [go-swagger/go-swagger#1884]
## Problem statement

Hello,
I want to generate spec from existing sources. I have an endpoint for uploading multiple files as multipart form data. The endpoint handles multiple files sent within the same field. In other words - one field is an array of files.

It's possible to define this kind of field in Swagger spec (https://swagger.io/docs/specification/describing-request-body/file-upload/ - see the section "Multiple File Upload"). However, I cannot achieve that using this tool.

I found this issue: https://github.com/go-swagger/go-swagger/issues/253
The undocumented (correct me if I'm wrong) annotation `swagger:file` works, but only for single file:

```go
    // uploadReq contains all params for upload operation
    //
    // swagger:parameters uploadReq
    type uploadReq struct {
    
    	// Files, which should be uploaded to public system bucket.
    	// Required: false
    	// In: formData
    	// swagger:file
    	Public []os.File
    }
```

How can I specify a definition of a field, which is an array of files to upload?
Thanks in advance!

**Comment by casualjim** [comment]
the docs you've linked to are for openapi 3.0

In 2.0 there was no support for multiple file upload
https://swagger.io/docs/specification/2-0/file-upload/

**Comment by pkosiec** [comment]
You're right, my bad. Thanks for response!

**Comment by eshanchawla0403** [comment]
@casualjim 
I am looking for some example client side code which invokes an api that takes consumes multipart formdata and takes in a file. Preferably a go-swagger based example would be really helpful
