### ISSUE TITLE
Generating uncompilable code when response code >= 512

### ISSUE THREAD

**Issue by apuigsech** [go-swagger/go-swagger#1893]
## Problem statement

If response code is 512 or higher the generated code is not valid and do not compile.

This is the error;

```
$ go build cmd/hello-world-app-server/main.go
# test/api/restapi/operations
restapi/operations/hello.go:29:16: unknown field 'Context' in struct literal of type Hello
restapi/operations/hello.go:29:30: unknown field 'Handler' in struct literal of type Hello
restapi/operations/hello_responses.go:21:6: Hello redeclared in this block
	previous declaration at restapi/operations/hello.go:37:6
restapi/operations/hello_responses.go:25:6: NewHello redeclared in this block
	previous declaration at restapi/operations/hello.go:28:63
restapi/operations/hello_world_app_api.go:244:30: cannot use NewHello(o.context, o.HelloHandler) (type *Hello) as type http.Handler in assignment:
	*Hello does not implement http.Handler (missing ServeHTTP method)
restapi/operations/hello_world_app_api.go:244:40: too many arguments in call to NewHello
	have (*middleware.Context, HelloHandler)
	want ()
```

## Swagger specification

```
swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
paths:
  /hello:
    get:
      operationId: hello
      responses:
        "512":
          description: Success
```

## Steps to reproduce

```
$ swagger generate server
(...)
$ go build cmd/hello-world-app-server/main.go
```

## Environment
swagger version: dev (github.com/go-swagger/go-swagger/cmd/swagger)
go version: 1.11.5 
OS:   OSX

**Comment by fredbi** [comment]
Such value is not a valid http status code which is required by swagger

**Comment by casualjim** [comment]
actually the status codes are not an exhaustive list, the numbers that are not well-known just don't have a default message. I got sidetracked with work, but this is definitely a piece of missing functionality because we should be able to deal with this.

**Comment by apuigsech** [comment]
There are some Unofficial Status code that are up to 512; https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors

For instance the ones used by Cloudflare; https://support.cloudflare.com/hc/en-us/sections/200820298-Error-Pages

I would recommend to do not limit that value to strict specifications.

**Comment by fredbi** [comment]
Yeah, @casualjim is right. Bug acknowledged

**Comment by gregmarr** [comment]
The HTTP specification just says that it's a 3 digit number that starts with 1, 2, 3, 4, or 5.  Thus, the valid range is 100 to 599.

https://tools.ietf.org/html/rfc7231 section 6
