### ISSUE TITLE
Models not importing x-go-type for one of properties

### ISSUE THREAD

**Issue by coopercc** [go-swagger/go-swagger#1897]
## Problem statement

Currently I have a model that is not adding the import for the reference added in x-go-type. It does add the alias before the struct, but not the import. Curiously, it does work for all of the operations, just not this model. It is referencing the Error struct in a separate repo. Thanks in advance for the help

## Swagger specification

swagger.json
```
"Partial": {
      "type": "object",
      "required":[
        "a",
        "errors"
      ],
      "properties":{
        "a":{
          "type": "object",
          "$ref": "#/definitions/A"
        },
        "errors":{
          "type":"object",
          "properties": {
            "errors": {
              "type": "object",
              "$ref": "#/definitions/Error"
            },
            "errorAs": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
...
// The error model. This gets imported correctly in the operations. But not in the model

"Error": {
      "description": "Standard error response object",
      "type": "object",
      "required": [
        "code"
      ],
      "properties": {
       //...
      },
      "x-go-type": {
        "import": {
          "package": "path/to/model",
          "alias": "swaggermodels"
        },
        "type": "Error"
      }
    },
```

The Partial model file
```
import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)
...
type PartialErrors struct {

	// error domains
	ErrorAs []string `json:"errorAs"`

	// errors
	Errors *swaggermodels.Error `json:"errors,omitempty"`
}
```
## Environment
swagger version: master
go version: 1.11.2

**Comment by fredbi** [comment]
Interesting... Does it work when you specify a fully qualified package path (e.g. relative to GOPATH/src), not just relative?

**Comment by coopercc** [comment]
Currently I have it referencing `github.secureserver.net/...` which from my understanding is a full package path

**Comment by coopercc** [comment]
To clarify what is happening a bit, one of the models that gets built in this api references a definition that imports it's model. That model, when built, uses the correct alias but does not add the import statement properly.

**Comment by fredbi** [comment]
I need to test that further.  I am pretty sure that an import statement is at first generated, but then discarded by go import because it can't find this. The target path that is generated is probably wrong. To make sure of this one has to generate with a config file disabling the source formatting on generated code.

**Comment by coopercc** [comment]
Huh. Do the import statements get added or discarded differently for the models and the operations? The import statement and alias are added correctly to all the operations just not this model that uses it.

**Comment by casualjim** [comment]
goimports runs after every created file, and the generation happens by iterating over the models who are stored in a map. Golang randomizes map keys so it's a kind of luck of the draw. One possible fix could be to introduce generation sessions where generation and imports optimization happen in different phases

**Comment by fredbi** [comment]
I made some changes recently on this and I might have overlooked a bug here.
I'll reproduce this with formatting disabled to figure out

**Comment by coopercc** [comment]
Have y'all found anything that would cause this?
