### ISSUE TITLE
swagger generate error

### ISSUE THREAD

**Issue by huangxiaoye** [go-swagger/go-swagger#1906]
$swagger generate spec -o ./swagger.json
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:16:6: sysAlloc redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:14:6: 	other declaration of sysAlloc
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:25:6: sysUnused redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:32:6: 	other declaration of sysUnused
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:29:6: sysUsed redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:36:6: 	other declaration of sysUsed
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:35:6: sysFree redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:42:6: 	other declaration of sysFree
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:40:6: sysFault redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:48:6: 	other declaration of sysFault
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:44:6: sysReserve redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:52:6: 	other declaration of sysReserve
/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:67:6: sysMap redeclared in this block
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:60:6: 	other declaration of sysMap
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:17:6: netpollinit redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:55:6: 	other declaration of netpollinit
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:26:6: netpolldescriptor redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:90:6: 	other declaration of netpolldescriptor
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:30:6: netpollopen redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:110:6: 	other declaration of netpollopen
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:50:6: netpollclose redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:127:6: 	other declaration of netpollclose
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:56:6: netpollarm redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:152:6: 	other declaration of netpollarm
/usr/local/opt/go/libexec/src/runtime/netpoll_kqueue.go:62:6: netpoll redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:172:6: 	other declaration of netpoll
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:260:6: osyield redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:541:6: 	other declaration of osyield
/usr/local/opt/go/libexec/src/runtime/sigtab_aix.go:7:5: sigtable redeclared in this block
/usr/local/opt/go/libexec/src/runtime/signal_darwin.go:7:5: 	other declaration of sigtable
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:79:6: syscall6 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:345:6: 	other declaration of syscall6
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:113:6: pthread_attr_init redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:577:6: 	other declaration of pthread_attr_init
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:120:6: pthread_attr_setstacksize redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:601:6: 	other declaration of pthread_attr_setstacksize
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:127:6: pthread_attr_setdetachstate redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:583:6: 	other declaration of pthread_attr_setdetachstate
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:134:6: pthread_create redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:607:6: 	other declaration of pthread_create
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:141:6: raise redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:519:6: 	other declaration of raise
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:154:6: mmap redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:417:6: 	other declaration of mmap
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:170:6: munmap redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:423:6: 	other declaration of munmap
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:177:6: madvise redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:432:6: 	other declaration of madvise
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:184:6: read redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:388:6: 	other declaration of read
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:191:6: closefd redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:400:6: 	other declaration of closefd
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:198:6: exit redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:376:6: 	other declaration of exit
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:205:6: usleep redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:465:6: 	other declaration of usleep
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:212:6: write redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:381:6: 	other declaration of write
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:219:6: open redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:394:6: 	other declaration of open
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:257:6: sigaction redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:441:6: 	other declaration of sigaction
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:264:6: sigprocmask redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:615:6: 	other declaration of sigprocmask
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:271:6: sigaltstack redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:450:6: 	other declaration of sigaltstack
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:285:6: raiseproc redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:528:6: 	other declaration of raiseproc
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:292:6: setitimer redeclared in this block
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:480:6: 	other declaration of setitimer
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:306:6: fcntl redeclared in this block
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:25:6: 	other declaration of fcntl
/usr/local/opt/go/libexec/src/runtime/syscall_aix.go:72:6: syscall_syscall6 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:73:6: 	other declaration of syscall_syscall6
/usr/local/opt/go/libexec/src/runtime/syscall_aix.go:85:6: syscall_rawSyscall6 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:103:6: 	other declaration of syscall_rawSyscall6
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:495:20: undeclared name: semt
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:501:20: undeclared name: semt
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:507:20: undeclared name: semt
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:513:25: undeclared name: semt
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:571:33: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:577:30: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:583:40: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:589:38: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:595:38: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:601:38: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:607:41: undeclared name: pthread_attr
/usr/local/opt/go/libexec/src/runtime/os2_aix.go:607:59: undeclared name: funcDescriptor
/usr/local/opt/go/libexec/src/runtime/sigtab_aix.go:38:2: undeclared name: _SIGPWR
/usr/local/opt/go/libexec/src/runtime/sigtab_aix.go:40:2: undeclared name: _SIGWAITING
/usr/local/opt/go/libexec/src/runtime/sigtab_aix.go:41:2: duplicate index 26 in array or slice literal
/usr/local/opt/go/libexec/src/runtime/sigtab_aix.go:42:2: duplicate index 27 in array or slice literal
/usr/local/opt/go/libexec/src/runtime/syscall_aix.go:62:15: undeclared name: _EINVAL
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:321:12: cannot use i (variable of type uint32) as uintptr value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:321:20: cannot use &sa (value of type *usigactiont) as *sigactiont value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:305:12: cannot use i (variable of type uint32) as uintptr value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:305:20: cannot use &osa (value of type *usigactiont) as *sigactiont value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:314:12: cannot use i (variable of type uint32) as uintptr value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:314:15: cannot use &sa (value of type *usigactiont) as *sigactiont value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:293:12: cannot use i (variable of type uint32) as uintptr value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:293:15: cannot use &sa (value of type *usigactiont) as *sigactiont value in argument to sigaction
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:195:38: cannot use stacksize (variable of type uintptr) as uint64 value in argument to pthread_attr_setstacksize
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:211:23: cannot use &attr (value of type *pthreadattr) as *pthread value in argument to pthread_create
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:211:37: too few arguments in call to pthread_create
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:167:23: cannot use &attr (value of type *pthreadattr) as *pthread value in argument to pthread_create
/usr/local/opt/go/libexec/src/runtime/os_darwin.go:167:69: too few arguments in call to pthread_create
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:65:30: undeclared name: _F_GETFL
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:66:16: undeclared name: _F_SETFL
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:69:29: undeclared name: _F_GETFL
/usr/local/opt/go/libexec/src/runtime/netpoll_aix.go:70:16: undeclared name: _F_SETFL
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:66:47: undeclared name: _MAP_ANONYMOUS
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:53:35: undeclared name: _MAP_ANONYMOUS
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:49:25: undeclared name: _MAP_ANONYMOUS
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:15:49: undeclared name: _MAP_ANONYMOUS
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:17:13: undeclared name: _EACCES
/usr/local/opt/go/libexec/src/runtime/mem_aix.go:21:13: undeclared name: _EAGAIN
/usr/local/opt/go/libexec/src/syscall/flock_darwin.go:10:6: FcntlFlock redeclared in this block
/usr/local/opt/go/libexec/src/syscall/flock_aix.go:12:6: 	other declaration of FcntlFlock
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:27:6: Getgroups redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:118:6: 	other declaration of Getgroups
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:53:6: Setgroups redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:144:6: 	other declaration of Setgroups
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:65:6: ReadDirent redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:183:6: 	other declaration of ReadDirent
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:80:6: WaitStatus redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:441:6: 	other declaration of WaitStatus
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:127:6: Wait4 redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:188:6: 	other declaration of Wait4
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:208:6: anyToSockaddr redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:401:6: 	other declaration of anyToSockaddr
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:273:6: Accept redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:286:6: 	other declaration of Accept
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:296:6: Getsockname redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:276:6: 	other declaration of Getsockname
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:358:6: Recvmsg redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:301:6: 	other declaration of Recvmsg
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:394:6: Sendmsg redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:340:6: 	other declaration of Sendmsg
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:399:6: SendmsgN redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:345:6: 	other declaration of SendmsgN
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:500:6: Utimes redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:62:6: 	other declaration of Utimes
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:507:6: UtimesNano redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:70:6: 	other declaration of UtimesNano
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:540:5: mapper redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:636:5: 	other declaration of mapper
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:546:6: Mmap redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:645:6: 	other declaration of Mmap
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:550:6: Munmap redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:649:6: 	other declaration of Munmap
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:20:7: ImplementsGetwd redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:84:7: 	other declaration of ImplementsGetwd
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:22:6: Getwd redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:86:6: 	other declaration of Getwd
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:78:6: direntIno redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:156:6: 	other declaration of direntIno
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:82:6: direntReclen redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:160:6: 	other declaration of direntReclen
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:86:6: direntNamlen redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:164:6: 	other declaration of direntNamlen
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:91:6: PtraceAttach redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:550:6: 	other declaration of PtraceAttach
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:92:6: PtraceDetach redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:552:6: 	other declaration of PtraceDetach
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:173:6: Pipe redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:44:6: 	other declaration of Pipe
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:348:6: readlen redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:623:6: 	other declaration of readlen
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:368:6: syscall6 redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:20:6: 	other declaration of syscall6
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:371:6: rawSyscall6 redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:19:6: 	other declaration of rawSyscall6
/usr/local/opt/go/libexec/src/syscall/syscall_darwin_amd64.go:9:6: setTimespec redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:615:6: 	other declaration of setTimespec
/usr/local/opt/go/libexec/src/syscall/syscall_darwin_amd64.go:13:6: setTimeval redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:619:6: 	other declaration of setTimeval
/usr/local/opt/go/libexec/src/syscall/syscall_darwin_amd64.go:44:6: sendfile redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:178:6: 	other declaration of sendfile
/usr/local/opt/go/libexec/src/syscall/zerrors_darwin_amd64.go:235:2: F_DUPFD_CLOEXEC redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:26:2: 	other declaration of F_DUPFD_CLOEXEC
/usr/local/opt/go/libexec/src/syscall/zerrors_darwin_amd64.go:1086:2: TIOCSCTTY redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:25:2: 	other declaration of TIOCSCTTY
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1183:6: Readlink redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:56:6: 	other declaration of Readlink
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1871:6: Gettimeofday redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:172:6: 	other declaration of Gettimeofday
/usr/local/opt/go/libexec/src/syscall/zsysnum_darwin_amd64.go:59:2: SYS_EXECVE redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:27:2: 	other declaration of SYS_EXECVE
/usr/local/opt/go/libexec/src/syscall/zsysnum_darwin_amd64.go:77:2: SYS_FCNTL redeclared in this block
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:28:2: 	other declaration of SYS_FCNTL
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:91:21: method Exited already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:451:21: 	other declaration of Exited
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:93:21: method ExitStatus already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:452:21: 	other declaration of ExitStatus
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:100:21: method Signaled already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:459:21: 	other declaration of Signaled
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:102:21: method Signal already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:460:21: 	other declaration of Signal
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:110:21: method CoreDump already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:469:21: 	other declaration of CoreDump
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:112:21: method Stopped already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:443:21: 	other declaration of Stopped
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:114:21: method Continued already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:467:21: 	other declaration of Continued
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:116:21: method StopSignal already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:444:21: 	other declaration of StopSignal
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:123:21: method TrapCause already declared for type WaitStatus uint32
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:471:21: 	other declaration of TrapCause
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:146:26: method sockaddr already declared for type SockaddrInet4 struct{Port int; Addr [4]byte; raw RawSockaddrInet4}
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:223:26: 	other declaration of sockaddr
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:161:26: method sockaddr already declared for type SockaddrInet6 struct{Port int; ZoneId uint32; Addr [16]byte; raw RawSockaddrInet6}
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:237:26: 	other declaration of sockaddr
/usr/local/opt/go/libexec/src/syscall/syscall_bsd.go:177:25: method sockaddr already declared for type SockaddrUnix struct{Name string; raw RawSockaddrUnix}
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:256:25: 	other declaration of sockaddr
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1948:152: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1857:149: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1808:134: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1759:196: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1287:186: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1148:121: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:1127:120: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:333:121: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:270:169: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:226:145: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:205:181: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:185:142: too few arguments in call to rawSyscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:129:134: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:115:150: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/zsyscall_darwin_amd64.go:42:158: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/syscall_darwin_amd64.go:47:144: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:225:2: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/syscall_darwin.go:131:2: too few arguments in call to syscall6
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:624:48: undeclared name: libc_read
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:552:49: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:550:49: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:548:53: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:545:9: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:525:9: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:525:18: undeclared name: PT_WRITE_BLOCK
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:499:9: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:499:18: undeclared name: PT_READ_BLOCK
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:483:10: undeclared name: ptrace64
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:265:20: cannot use uint8(name[i]) (value of type uint8) as int8 value in assignment
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:190:8: undeclared name: _Pid_t
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:191:8: undeclared name: ERESTART
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:194:13: undeclared name: ERESTART
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:195:18: undeclared name: _Pid_t
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:184:9: undeclared name: getdirent
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:173:8: undeclared name: gettimeofday
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:104:8: undeclared name: getcwd
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:89:10: undeclared name: getcwd
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:58:9: undeclared name: readlink
/usr/local/opt/go/libexec/src/syscall/syscall_aix.go:49:13: cannot use &pp (value of type *[2]_C_int) as *[2]int32 value in argument to pipe
/usr/local/opt/go/libexec/src/syscall/flock_aix.go:13:47: undeclared name: libc_fcntl
/usr/local/opt/go/libexec/src/internal/syscall/unix/at_sysnum_darwin.go:11:7: AT_REMOVEDIR redeclared in this block
/usr/local/opt/go/libexec/src/internal/syscall/unix/at_aix.go:12:2: 	other declaration of AT_REMOVEDIR
/usr/local/opt/go/libexec/src/internal/syscall/unix/at_sysnum_darwin.go:12:7: AT_SYMLINK_NOFOLLOW redeclared in this block
/usr/local/opt/go/libexec/src/internal/syscall/unix/at_aix.go:13:2: 	other declaration of AT_SYMLINK_NOFOLLOW
/usr/local/opt/go/libexec/src/os/stat_darwin.go:12:6: fillFileStatFromSys redeclared in this block
/usr/local/opt/go/libexec/src/os/stat_aix.go:12:6: 	other declaration of fillFileStatFromSys
/usr/local/opt/go/libexec/src/os/stat_darwin.go:49:6: atime redeclared in this block
/usr/local/opt/go/libexec/src/os/stat_aix.go:49:6: 	other declaration of atime
/usr/local/opt/go/libexec/src/os/sys_bsd.go:11:6: hostname redeclared in this block
/usr/local/opt/go/libexec/src/os/sys_aix.go:12:6: 	other declaration of hostname
/usr/local/opt/go/libexec/src/os/stat_aix.go:44:34: StTimespec_t not declared by package syscall
/usr/local/opt/go/libexec/src/os/sys_aix.go:13:16: Utsname not declared by package syscall
/usr/local/opt/go/libexec/src/os/sys_aix.go:14:22: Uname not declared by package syscall
/usr/local/opt/go/libexec/src/os/stat_aix.go:50:53: invalid operation: fi.Sys().(*syscall.Stat_t) (comma, ok expression of type *syscall.Stat_t) has no field or method Atim
/usr/local/opt/go/libexec/src/os/stat_aix.go:15:39: invalid operation: fs.sys (variable of type syscall.Stat_t) has no field or method Mtim
/usr/local/opt/go/libexec/src/net/interface_bsd.go:18:6: interfaceTable redeclared in this block
/usr/local/opt/go/libexec/src/net/interface_aix.go:51:6: 	other declaration of interfaceTable
/usr/local/opt/go/libexec/src/net/interface_bsd.go:57:6: linkFlags redeclared in this block
/usr/local/opt/go/libexec/src/net/interface_aix.go:96:6: 	other declaration of linkFlags
/usr/local/opt/go/libexec/src/net/interface_bsd.go:80:6: interfaceAddrTable redeclared in this block
/usr/local/opt/go/libexec/src/net/interface_aix.go:119:6: 	other declaration of interfaceAddrTable
/usr/local/opt/go/libexec/src/net/interface_darwin.go:23:6: interfaceMulticastAddrTable redeclared in this block
/usr/local/opt/go/libexec/src/net/interface_aix.go:181:6: 	other declaration of interfaceMulticastAddrTable
/usr/local/opt/go/libexec/src/net/sockopt_bsd.go:15:6: setDefaultSockopts redeclared in this block
/usr/local/opt/go/libexec/src/net/sockopt_aix.go:12:6: 	other declaration of setDefaultSockopts
/usr/local/opt/go/libexec/src/net/sockopt_bsd.go:38:6: setDefaultListenerSockopts redeclared in this block
/usr/local/opt/go/libexec/src/net/sockopt_aix.go:23:6: 	other declaration of setDefaultListenerSockopts
/usr/local/opt/go/libexec/src/net/sockopt_bsd.go:43:6: setDefaultMulticastSockopts redeclared in this block
/usr/local/opt/go/libexec/src/net/sockopt_aix.go:28:6: 	other declaration of setDefaultMulticastSockopts
/usr/local/opt/go/libexec/src/net/interface_bsd.go:37:29: cannot use m.Flags (variable of type int) as int32 value in argument to linkFlags
/usr/local/opt/go/libexec/src/net/interface_aix.go:127:20: IfMsgHdr not declared by package syscall
/usr/local/opt/go/libexec/src/net/interface_aix.go:59:20: IfMsgHdr not declared by package syscall
/usr/local/opt/go/libexec/src/net/interface_aix.go:36:25: Getkerninfo not declared by package syscall
/usr/local/opt/go/libexec/src/net/interface_aix.go:41:19: Getkerninfo not declared by package syscall
couldn't load packages due to errors: syscall, net, os and 2 more

## Environment
swagger version: 0.18.0  
go version: 1.12.0  
OS:   MacOS Mojave

**Comment by casualjim** [comment]
your go version has updated, to work around this you can build go-swagger from source.

```
go get -u github.com/go-swagger/go-swagger/cmd/swagger
````
