### ISSUE TITLE
Response struct goes under headers

### ISSUE THREAD

**Issue by nitin302** [go-swagger/go-swagger#1908]
swagger version:  v0.18.0
go version:  go1.11.2 darwin/amd64

When using // swagger:response exampleResponse for a struct, the params under this struct become header fields in the auto-generated code.

The response does not come under body. Not sure if what issue this relates to

**Comment by casualjim** [comment]
yes that's the way it should be. A request is method + path + headers + body
A response is status code + headers + body.

```go 
// swagger:response
type SomeResponse struct {
   // in: body
   Body SomeModel 
}
```
