### ISSUE TITLE
POSTing to API that returns a 201 with a location header produces: (*interface {}) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface"

### ISSUE THREAD

**Issue by jeffreydwalter** [go-swagger/go-swagger#1917]
## Problem statement
I'm getting the following error doing a POST to an endpoint that's returning a 201 with a location.

Response headers:
```
HTTP/1.1 201 Created
Content-Length: 0
Cache-Control: no-cache
Content-Type: text/plain
Date: Wed, 10 Apr 2019 14:33:59 GMT
Expires: -1
Feature-Policy: geolocation 'none'; vr 'none'; payment 'none'; midi 'none'; microphone 'none'; fullscreen 'none'; encrypted-media 'none'; camera 'none'; autoplay 'none';
Ipp-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
Location: https://integration.visma.net/API/controller/api/v1/salesorder/000050
Pragma: no-cache
Referrer-Policy: origin-when-cross-origin
Set-Cookie: LegacyUI=0; path=/; secure; HttpOnly,UserBranch=13; path=/; secure; HttpOnly,Locale=TimeZone=GMTE0000U&Culture=en-GB; path=/; secure; HttpOnly,LicenseRoles=; expires=Tue, 09-Apr-2019 14:33:52 GMT; path=/; secure; HttpOnly,UserDisplayName=; expires=Tue, 09-Apr-2019 14:33:52 GMT; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security: value="max-age=31536000; includeSubDomains"
Vnfinstanceid: financials_3860
X-Handled-By: Acumatica-PX.Export/AuthenticationManagerModule
X-Xss-Protection: 1;mode=block
```
Error that follows:
```
(*interface {}) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface"
```

Please remove the sections that don't apply

## Swagger specification

[swagger.json.zip](https://github.com/go-swagger/go-swagger/files/3064406/swagger.json.zip)

## Steps to reproduce
Unfortunately, this API is restricted, so I can't give a reproducible example, but here's the general idea:
```
vismaOrder := new(clientmodels.SalesOrderUpdateDto)
vismaOrder.OrderType = &clientmodels.SalesOrderUpdateDtoOrderType{"SO"} 
vismaOrder.Customer = &clientmodels.SalesOrderUpdateDtoCustomer{"10000"}
vismaOrder.Currency = &clientmodels.SalesOrderUpdateDtoCurrency{"NOK"}
vismaOrder.Description = &clientmodels.SalesOrderUpdateDtoDescription{"Test Order"}
vismaOrder.Hold = &clientmodels.SalesOrderUpdateDtoHold{false}
vismaOrder.RecalculateShipment = true

for _, li := range order.LineItems {
	l := new(clientmodels.SalesOrderLineUpdateDto)
	l.Operation = "Insert"
	l.InventoryNumber = &clientmodels.SalesOrderLineUpdateDtoInventoryNumber{1}
	l.Quantity = &clientmodels.SalesOrderLineUpdateDtoQuantity{10.0}
	vismaOrder.Lines = append(vismaOrder.Lines, l)
}

params := sales_order.NewSalesOrderPostParams()
params.SetSaleOrderUpdateDto(vismaOrder)

transport := httptransport.New(host, basePath, []string{"https"})
client := apiclient.New(transport, strfmt.Default),
token := httptransport.BearerToken(token)
_, err := client.SalesOrder.SalesOrderPost(params, token)
if err != nil {
	logrus.Errorf("%s: Error creating order: %+v", trace.Getfl(), err)
	return err
}
return nil
```

## Environment
$ ./swagger version
version: v0.19.0
commit: 312366608bbf17dd219190b66ab63bdc8b4d0db0

$ go version
go version go1.12.2 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="~/Desktop/"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3540"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3540/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build217717785=/tmp/go-build -gno-record-gcc-switches"

**Comment by jeffreydwalter** [comment]
The problem seems to be in this code:
```
// Code generated by go-swagger; DO NOT EDIT.

package sales_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SalesOrderPostReader is a Reader for the SalesOrderPost structure.
type SalesOrderPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SalesOrderPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewSalesOrderPostCreated()
// readResponse() is failing with the error I reported. I haven't traced it all the way yet, but I'm wondering if it's because the response.Body is nil and the code isn't checking for that before trying to unmarshal it?
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSalesOrderPostCreated creates a SalesOrderPostCreated with default headers values
func NewSalesOrderPostCreated() *SalesOrderPostCreated {
	return &SalesOrderPostCreated{}
}

/*SalesOrderPostCreated handles this case with default header values.

Created
*/
type SalesOrderPostCreated struct {
	Payload interface{}
}

func (o *SalesOrderPostCreated) Error() string {
	return fmt.Sprintf("[POST /controller/api/v1/salesorder][%d] salesOrderPostCreated  %+v", 201, o.Payload)
}

func (o *SalesOrderPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
```

`readResponse()` in `ReadResponse()` is failing with the error I reported. I haven't traced it all the way yet, but I'm wondering if it's because the response.Body is nil and the code isn't checking for that before trying to unmarshal it?

**Comment by jeffreydwalter** [comment]
FYI: The API call that's returning a `{}` response is the `SalesOrder``POST /controller/api/v1/salesorder` here: https://integration.visma.net/API-index/

The spec defines the response body to be `{}`, so I would expect that go-swagger would generate valid code to handle this case.

**Comment by casualjim** [comment]
yeah it should have no problem with this.  

the text consumer is kind of weird, it would be interesting to see which consumer it's using
The body property returns a stream, so it should never be nil.

the json consumer looks at the text marshaller interface, but when the object is empty I don't think those code paths are hit.
The text consumer and binary consumer however do stuff with the text marshaller

**Comment by jeffreydwalter** [comment]
Looks like the problem is that the content-type is `text/plain` and the body is empty. Why is that not supported?

**Comment by casualjim** [comment]
here is fine, that makes this a part of the changelog

the bug is in here then: https://github.com/go-openapi/runtime/blob/master/text.go#L29-L63

**Comment by casualjim** [comment]
o it functions as designed, but it can be taught to be happy with your case

**Comment by jeffreydwalter** [comment]
> here is fine, that makes this a part of the changelog
> 
> the bug is in here then: https://github.com/go-openapi/runtime/blob/master/text.go#L29-L63

Yep, looking at it now. I'm wondering if it would be enough to do something like:
```
if b == nil || len(b) == 0 {
    data = ""
    return nil
}
```
and just skip the rest of that code: https://github.com/go-openapi/runtime/blob/master/text.go#L42-L62

The above code does fix the problem.

**Comment by casualjim** [comment]
yep, please send :)

**Comment by jeffreydwalter** [comment]
@casualjim here it is https://github.com/go-openapi/runtime/pull/135

**Comment by jeffreydwalter** [comment]
@casualjim Thanks again for your quick response and help!

**Comment by jeffreydwalter** [comment]
@casualjim forgot to signoff, done now.
