### ISSUE TITLE
How do I access the response headers?

### ISSUE THREAD

**Issue by jeffreydwalter** [go-swagger/go-swagger#1918]
## Problem statement
When making an HTTP POST request, I expect back a `201` status with a `Location` header. The Swagger API client I generated doesn't provide access to that.

Is there a way to access the response headers? I see that the go-openapi library handles the request and doesn't seem to pass the headers back. Am I missing something?

$ ./swagger version
version: v0.19.0
commit: 3123666

$ go version
go version go1.12.2 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/Desktop/"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3540"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3540/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build217717785=/tmp/go-build -gno-record-gcc-switches"

**Comment by casualjim** [comment]
specify it on the response in the spec, and the field will be generated

**Comment by jeffreydwalter** [comment]
@casualjim thanks again for your help! Would you mind providing an example? I'm pretty new to swagger specs.

Here's the relevant post spec:
```
     "post": {
        "tags": [
          "SalesOrder"
        ],
        "summary": "Create a Sale Order",
        "description": "Response Message has StatusCode Created if POST operation succeed",
        "operationId": "SalesOrder_Post",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "saleOrderUpdateDto",
            "in": "body",
            "description": "Defines the data for the Sale Order to create",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SalesOrderUpdateDto"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object"
            }
          }
        },
        "security": [
          {
            "vna_oauth": [
              "financialstasks"
            ]
          },
          {
            "ipp-company-id": []
          },
          {
            "ipp-application-type": []
          }
        ]
      }
```

**Comment by jeffreydwalter** [comment]
@casualjim nevermind... Google is my friend! :) Thanks for the pointer.

**Comment by jeffreydwalter** [comment]
Just in case anyone else runs into this, I fixed the issue by adding the `headers` section to the 201 response in the spec like so:
```
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
                "Location":
                    "schema": {
                        "type": "string",
                        "description": "Location on newly created Sale Order."
                    }
            },
            "schema": {
              "type": "object"
            }
          }
        },
```

**Comment by javerisagar** [comment]
@jeffreydwalter Hi i am using swagger 2.0 and i am to willing to get the location header in Response Headers can you please help me out with this 

---
swagger: "2.0"
info:
  version: "2019-10-21T06:52:36Z"
  title: "datalake-dev-application"
basePath: "/v1"
schemes:
- "https"
paths:
  /files/ids/{id}:
    get:
      tags:
      - Files
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        

      
      responses:
        200:
          description: "200 response"
          headers:
            location:
              type: "string"
     
      security:
      - ldsauthorizer: []

  
securityDefinitions:
  ldsauthorizer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"

i am using this ymal

**Comment by jeffreydwalter** [comment]
@javerisagar 200 responses cannot (will not) contain a location header... The location header is generally included as part of a 20 sent in response to a PUT request.

**Comment by Javirln** [comment]
Hello,

I'm facing a similar issue. In my case the field it's created but I cannot access it since there is no response object from the method due to it's a `302` response

```json
"responses": {
  "302": {
    "description": "random description",
    "headers": {
      "Location": {
        "type": "string"
      }
    }
   }
  }
}
```
The goal of this method is to return an URL that can be consumed by the generated client in order to follow the redirection either manually or automatically.

Thanks

**Comment by Piocky** [comment]
> Hello,
> 
> I'm facing a similar issue. In my case the field it's created but I cannot access it since there is no response object from the method due to it's a `302` response
> 
> ```json
> "responses": {
>   "302": {
>     "description": "random description",
>     "headers": {
>       "Location": {
>         "type": "string"
>       }
>     }
>    }
>   }
> }
> ```
> 
> The goal of this method is to return an URL that can be consumed by the generated client in order to follow the redirection either manually or automatically.
> 
> Thanks

I'm facing the same issue here, tried diffrent things on 302 response definition, but still the same result with Swagger loading but ending with "TypeError: Failed to fetch". Did you find a solution to this @Javirln?

**Comment by casualjim** [comment]
You can typeswitch on the error to get the type for that response code, and then you can access the location property

**Comment by Piocky** [comment]
The weird thing is, if I keep the status code to 302 (or even 300), I never get the response from either Swagger interface or Postman. If I change it for 200 I get it instanly. Do you have any idea what could cause that? Are 30x responses not supported?

**Comment by casualjim** [comment]
The http client might be configured to follow redirects automatically
