### ISSUE TITLE
Can't configure content type in generated client

### ISSUE THREAD

**Issue by nlsun** [go-swagger/go-swagger#1924]
## Problem statement

The generated client only allows you to set `params` and there isn't a way to override the content type used if the endpoint accepts multiple content types. The runtime library itself just uses the first content type in the list of `ConsumesMediaTypes` https://github.com/go-openapi/runtime/blob/3d6572c5a80826d5e7f6362d4c681875207c3ef6/client/runtime.go#L333-L341.

## Suggestion

Instead of hardcoding the `ClientOperation` https://github.com/go-swagger/go-swagger/blob/312366608bbf17dd219190b66ab63bdc8b4d0db0/examples/todo-list/client/todos/todos_client.go#L36-L48 we could have some kind of function that produces the `DefaultAddOneOperation` and in addition to `AddOne` have an `AddOneWithOperation` that takes in a `ClientOperation` as an argument.

That way, a user can create a default operation, modify it, and then pass it in to the client. What do you think?

Or, since it's generated code, the existing `AddOne` can remain unmodified, and we can just generate the additional helper functions.

## Environment
swagger version: 0.18.0

**Comment by casualjim** [comment]
but you have a way to control what goes in there, by the order of the spec. That way the server can tell you what they prefer. You can also use ;q= values in the consumes and it will use that to prioritize

**Comment by nlsun** [comment]
> You can also use ;q= values in the consumes and it will use that to prioritize
Is this something in the swagger spec or in the runtime lib? This might be what I'm looking for.

I figure my use case might be a little obscure, but I actually want to use the non-preferred content type in the client in order to test that accepting that particular input works on the server side

**Comment by casualjim** [comment]
You can also just call the submit operation directly on the runtime. That way you can present your own client operation.

yeah you'd have to make that change in the swagger spec.

**Comment by nlsun** [comment]
Yeah calling the `Submit` allows me to do anything, but then I'd have to build the entire `ClientOperation` by hand which would lose the benefits of swagger generating the request (namely the `ID` and `Method`) that the default generated functions have within them. Calling `Submit` might not be so bad if there were a `DefaultAddOneOperation()` or something that would create a filled-in operation that I could modify and pass to `Submit` though

**Comment by fredbi** [comment]
@nlsun here is my 2 cents on how we could enhance the client code to achieve this goal:
```go
type ClientOption func(*runtime.ClientOperation)

func (a *Client) WithConsumes(media []string) ClientOption {
    return func(c *runtime.ClientOperation) {
        c.ConsumesMediaTypes = append(media, c.ConsumesMediaTypes ...)
    }
}

func (a *Client) WithProduces(media []string) ClientOption {
    return func(c *runtime.ClientOperation) {
        c.ProducesMediaTypes= append(media, c.ProducesMediaTypes ...)
    }
}

func (a *Client) WithSchemes(schemes []string) ClientOption {
    return func(c *runtime.ClientOperation) {
        c.Schemes= append(schemes, c.Schemes...)
    }
}

// operation
func (a *Client) AddOne(params *AddOneParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddOneCreated, error) {
&runtime.ClientOperation{
		ID:                 "addOne",
		Method:             "POST",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/io.swagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.swagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddOneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, apply := range opts {
	    apply(
	}
        result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	return result.(*AddOneCreated), nil
}
```
