### ISSUE TITLE
Generate Server Code

### ISSUE THREAD

**Issue by waytoharish** [go-swagger/go-swagger#1933]
Hi Team ,
I am getting error when trying to generate server specifiction using attached swagger file-

[swagger.zip](https://github.com/go-swagger/go-swagger/files/3120327/swagger.zip)

C:\Harish\Go\workspace\timeofday>swagger generate server -f swagger.yml
2019/04/26 13:34:28 validating spec C:\Harish\Go\workspace\timeofday\swagger.yml
2019/04/26 13:34:29 preprocessing spec with option:  minimal flattening
2019/04/26 13:34:29 building a plan for generation
2019/04/26 13:34:29 FindFirstFile go: The system cannot find the file specified.

**Comment by fredbi** [comment]
Could you please provide us with your spec, so we may attempt to reproduce your issue? Thank you.

**Comment by fredbi** [comment]
Tried to reproduce this with the attached spec on both linux and windows. 

go 12.5.1, go-swagger: master

Cannot reproduce: generates server just fine.

Maybe are you trying to generate outside GOPATH?

**Comment by waytoharish** [comment]
Hi team,
This is working fine for me too. Original issue was for GOPATH only.
