### ISSUE TITLE
Swagger generates and uses different models in case of definition name starts with Digit

### ISSUE THREAD

**Issue by sabir012** [go-swagger/go-swagger#1937]
In swagger.yml file my definitions named like "400Schema", "404Schema" and etc. When I generate source from swagger, it was created models in the form "NR404Schema" but restapi code was used it as "X404Schema". Hence restapi could not find proper model objects. 
It is happening only in case when definitons' name starts with digit.

**Comment by fredbi** [comment]
It looks like the "camelize" func has been changed with https://github.com/go-openapi/swag/pull/31
and introduce his "X" prefix...
Could you confirm it works as expected when we don't have this update in swag package?
