### ISSUE TITLE
Data Race between Serve() and Shutdown()

### ISSUE THREAD

**Issue by amuttsch** [go-swagger/go-swagger#1943]
## Problem statement

Between the functions `Serve()` and  `Shutdown()` is a data race on the variable `servers`. This occurs because the goroutine that starts the server writes into `servers` on [this line](https://github.com/amuttsch/goswagger-race/blob/master/restapi/server.go#L190). Before it starts a goroutine to handle shutdowns [here](https://github.com/amuttsch/goswagger-race/blob/master/restapi/server.go#L178). In the `handleShutdown()` method `servers` is accessed again which causes a data race:

```
==================
WARNING: DATA RACE
Read at 0x00c0000ac180 by goroutine 27:
  goswagger-race/restapi.(*Server).handleShutdown()
      .../goswagger-race/restapi/server.go:418 +0xba

Previous write at 0x00c0000ac180 by main goroutine:
  goswagger-race/restapi.(*Server).Serve()
      .../goswagger-race/restapi/server.go:220 +0x1b5a
  main.main()
      .../goswagger-race/cmd/example-server/main.go:60 +0x64a

Goroutine 27 (running) created at:
  goswagger-race/restapi.(*Server).Serve()
      .../goswagger-race/restapi/server.go:178 +0x26e
  main.main()
      .../goswagger-race/cmd/example-server/main.go:60 +0x64a
==================
==================
WARNING: DATA RACE
Read at 0x00c0004ce010 by goroutine 27:
  goswagger-race/restapi.(*Server).handleShutdown()
      .../goswagger-race/restapi/server.go:425 +0x1a6

Previous write at 0x00c0004ce010 by main goroutine:
  goswagger-race/restapi.(*Server).Serve()
      .../goswagger-race/restapi/server.go:220 +0x1b20
  main.main()
      .../goswagger-race/cmd/example-server/main.go:60 +0x64a

Goroutine 27 (running) created at:
  goswagger-race/restapi.(*Server).Serve()
      .../goswagger-race/restapi/server.go:178 +0x26e
  main.main()
      .../goswagger-race/cmd/example-server/main.go:60 +0x64a
==================
```

## Swagger specification

https://github.com/amuttsch/goswagger-race/blob/master/swagger.yaml

## Steps to reproduce

To reproduce clone my repo https://github.com/amuttsch/goswagger-race , run `go run -race cmd/example-server/main.go` and wait a few seconds.

## Environment
swagger version: 0.19.0
go version: 1.12
OS: Linux

Related to #1781

**Comment by amuttsch** [comment]
This was quite an easy fix, I moved the goroutine creation for the shutdown at the end of the method.

**Comment by amuttsch** [comment]
I'd like to add a testcase for this, can someone guide me how to write a test that generates a server, provides a `main.go` and runs `go test`?

**Comment by casualjim** [comment]
this one, does something similar: https://github.com/go-swagger/go-swagger/blob/master/generator/build_test.go

**Comment by amuttsch** [comment]
Thanks, I'll have a look

**Comment by amuttsch** [comment]
I'm at the point where I can run `go run test -race` for my test fixture. But the output of the `GenerateServer` function in the `generator` package differs from the `swagger generate` command, e.g. `swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)` is missing from the generated main file.

```
			opts := testGenOpts()

			opts.Target = filepath.Dir(spec)
			_ = os.Mkdir(opts.Target, 0755)
			opts.Spec = spec
			opts.IncludeMain = true

			fmt.Println(opts.Target)

			err := GenerateServer("", nil, nil, &opts)
```

See https://github.com/amuttsch/go-swagger/blob/testing/generator/test_test.go and https://github.com/amuttsch/go-swagger/blob/testing/fixtures/bugs/1943/datarace_test.go

**Comment by amuttsch** [comment]
I think I found the missing flag: `opts.ExcludeSpec = false`
