### ISSUE TITLE
Query parameter can't be named 'append' when enum appearing also

### ISSUE THREAD

**Issue by jimturnquist** [go-swagger/go-swagger#1948]
## Problem statement

When a query parameter is named named 'append', AND there is an enumeration in a different query parameter, a portion of the generated code won't build because a variable named 'append' is created.

## Swagger specification

```
{
  "swagger": "2.0",
  "info": {
    "description": "Simple API",
    "version": "2.0.0",
    "title": "Simple API"
  },
  "tags": [
    {
      "name": "general",
      "description": "General settings and information"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/api/stuff": {
      "get": {
        "tags": [
          "general"
        ],
        "summary": "Retrieves stuff",
        "operationId": "getStuff",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "append",
            "in": "query",
            "required": false,
            "default": false,
            "type": "boolean"
          },
          {
            "name": "results",
            "in": "query",
            "required": false,
            "type": "array",
            "minItems": 1,
            "maxItems": 5,
            "uniqueItems": true,
            "items": {
              "type": "string",
              "enum": [
                "Counts",
                "IDs",
                "Amounts",
                "Indexes",
                "rawIndexes"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success, stuff returned"
          }
        }
      }
    }
  }
}
```
## Steps to reproduce

```
swagger generate server -f sample.json
```

```
go build cmd/simple-server/main.go
# myproj/restapi/operations/general
restapi/operations/general/get_stuff_urlbuilder.go:64:22: cannot call non-function append (type string)
```

The code being produced by the generator produces the following unbuildable code:

from generated file: get_version_urlbuilder.go, the line in bold is line 64.
<pre>
// Build a url path and query string
func (o *GetStuffURL) Build() (*url.URL, error) {
        var _result url.URL

        var _path = "/api/stuff"

        _basePath := o._basePath
        _result.Path = golangswaggerpaths.Join(_basePath, _path)

        qs := make(url.Values)

        var append string
        if o.Append != nil {
                append = swag.FormatBool(*o.Append)
        }
        if append != "" {
                qs.Set("append", append)
        }

        var resultsIR []string
        for _, resultsI := range o.Results {
                resultsIS := resultsI
                if resultsIS != "" {
                        <b>resultsIR = append(resultsIR, resultsIS)</b>
                }
        }

        results := swag.JoinByFormat(resultsIR, "")

        if len(results) > 0 {
                qsv := results[0]
                if qsv != "" {
                        qs.Set("results", qsv)
                }
        }

        _result.RawQuery = qs.Encode()

        return &_result, nil
}
</pre>

## Environment
swagger version: v0.19.0 
go version: go1.12.1 darwin/amd64 
OS:   MacOS

**Comment by jimturnquist** [comment]
I believe if the variable name 'append' was mangled, the problem might be fixed.

Is this the right idea?  This is not a complete change.  Just wondering if the style of change below is heading in the right direction.

```
diff --git a/generator/templates/server/urlbuilder.gotmpl b/generator/templates/server/urlbuilder.gotmpl
index 1607fff8..55b5c5fe 100644
--- a/generator/templates/server/urlbuilder.gotmpl
+++ b/generator/templates/server/urlbuilder.gotmpl
@@ -3,14 +3,14 @@
 {{- end }}
 {{ define "simplequeryparambuilder" }}
 {{ if .IsNullable -}}
-var {{ varname .ID }} string
+var {{ varname .ID }}Q string
 if {{ .ReceiverName }}.{{ pascalize .ID }} != nil {
   {{ varname .ID }} = {{ if .Formatter }}{{ .Formatter }}(*{{ .ReceiverName }}.{{ pascalize .ID }}){{ else }}{{ if not .IsCustomFormatter }}*{{ end }}{{ .ReceiverName }}.{{ pascalize .ID }}{{ if .IsCustomFormatter }}.String(){{end}}{{end}}
 }
 {{ else }}{{ varname .ID }} := {{ if .Formatter }}{{ .Formatter }}({{ .ReceiverName }}.{{ pascalize .ID }}){{ else }}{{ .ReceiverName }}.{{ pascalize .ID }}{{ if .IsCustomFormatter }}.String(){{end}}{{end}}
 {{ end -}}
-if {{ varname .ID }} != "" {
-  qs.Set({{ printf "%q" .Name }}, {{ varname .ID }})
+if {{ varname .ID }}Q != "" {
+  qs.Set({{ printf "%q" .Name }}, {{ varname .ID }}Q)
 }
 {{ end }}
 {{ define "sliceitemqueryparambuilder" }}
```

**Comment by fredbi** [comment]
@jimturnquist yes you are correct.
