### ISSUE TITLE
parameter integers are always send

### ISSUE THREAD

**Issue by MStoykov** [go-swagger/go-swagger#195]
I expect that the following spec: 
```json
{
  "consumes": [
    "application/json",
    "application/x-www-form-urlencoded"
  ],
  "paths": {
    "/testing": {
      "get": {
        "parameters": [
          {
            "allowEmptyValue": false,
            "in": "query",
            "name": "testingThis",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Success message"
          }
        }
      }
    }
  },
  "produces": [
    "application/json",
    "application/json; charset=utf-8"
  ],
  "swagger": "2.0"
}
```

means that I can send a request without the query param 'testingThis'. 

The relevant generated code, below, will always set the param:
```go
qrTestingThis := o.TestingThis
qTestingThis := swag.FormatInt64(qrTestingThis)
if qTestingThis != "" {
       if err := r.SetQueryParam("testingThis", qTestingThis); err != nil {
             return err
       }
}
```
The `qTestingThis != ""` is always true and the whole check can be omitted in this case.

I don't know how to implement this, without breaking backwards compatibility, with previously generated code. 

Breaking compatibility proposition:
If all the fields that are not required are actually pointers to the values, a pointer of `nil` can mean that they are not set. This will definitely break code that use direct field setting of the param struct:
```go
&GetTestingParams{
     TestingThis: 12, 
}
```
instead of the functions. 

p.s. My workaround (especially because I never actually set the field) is to change it's type to string before generating the code.

**Comment by casualjim** [comment]
Take a look here for easily turning builtin literals to pointer values:

https://github.com/go-swagger/go-swagger/blob/master/swag/convert_types.

In the spec you shared `application/json` and `application/json; charset=utf-8` are the same thing. In fact when a mime type starts with application it's kind of expected that the content it describes is unicode. So you should be able to safely drop the charset=utf-8 from the media type.

**Comment by MStoykov** [comment]
Thank you.
