### ISSUE TITLE
Two different parameter names derived from specification

### ISSUE THREAD

**Issue by mrekucci** [go-swagger/go-swagger#1952]
Swagger derives two different field names (`PSUIPAddress` and `PSUipAddress`) from the `PSU-IP-Address` handler parameter name found on line 78 of the following specification: https://developer.tatrabanka.sk/resources/download/tb_accounts_v1.0.0.yaml

Command used to generate the code: `swagger generate client --spec=tb_accounts_v1.0.0.yaml`.

swagger version: v0.19.0; commit: 312366608bbf17dd219190b66ab63bdc8b4d0db0
go version: 1.12.4 darwin/amd64
OS: macOS Mojave 10.14.5

**Comment by fredbi** [comment]
Looks like an issue with name mangling. Some changes in the way initialisms are resolved have been submitted to go-openapi/swag some time ago. Needs to be verified

**Comment by fredbi** [comment]
@mrekucci tested this with newest master (and updated dependencies for name mangling).
Looks like it is correct now.

Can you please confirm?

**Comment by fredbi** [comment]
As far as I could test this is working on current master.

@mrekucci feel free to reopen if you disagree

**Comment by mrekucci** [comment]
LGTM!

**Comment by fredbi** [comment]
Thanks @mrekucci
