### ISSUE TITLE
Generated and customized go-swagger server compiles, executes and initializes correctly, but does not handle any requests

### ISSUE THREAD

**Issue by pauluzee** [go-swagger/go-swagger#1953]
## Problem statement

My Swagger spec seems correct, and the code it generates compiles error-free, even after making modifications to the configure_xxxx.go file that connected the API to my own handler functions.  I also added "basic" authentication to the program, and have a simple function that checks for user and password which writes to the log whenever it's called.  The compiled program ran as it should and produced the initialization logging messages I expected.  However, that's all the server does: while it continues to run, it doesn't actually service any requests.  In fact, it doesn't seem to even "see" any requests at all; there's no logging produced after the init, and in particular I've not seen any messages coming from the authentication function at all, which means it's not being called.

Here are a couple of the curl calls I made **from the the same box where the server is running:**

curl -i -H 'Accept:application/json' -H 'Authorization:Basic cmVhZG9ubHk6cmVhZG9ubHk=' 'http://127.0.0.1:4704/hostmap/hosts/bldd269.bhdc.att.com'

and...

curl -i --basic -u "readanly:readonly" 'http://127.0.0.1:4704/hostmap/hosts/bldd269.bhdc.att.com'

Both commands produce the same output, a glob of HTML with an error message embedded in it.  Here's a typical one:

ylpd942// ~ $ curl -i --basic -u "readanly:readonly" 'http://127.0.0.1:4704/hostmap/hosts/bldd269.bhdc.att.com'         HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NTLM
Proxy-Authenticate: BASIC realm="NTLMTest"
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Set-Cookie: BCSI-CS-cdc9fed863f38d82=2; Path=/
Connection: close
Content-Length: 799

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
**Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.**
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>

</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

Note: there is a proxy server set up for this host and both the _http_proxy_ and _https_proxy_ environmental variables are set to it before I started the server and made any curls requests to it.  Also, I ran several versions of the curl commands--mostly with parts of the path removed--and they all produced the same output.

I did also try running the curl commands from a separate box (which also had the proxy set), and got a similar error:

[eu9195@zldv3698 ~]$ curl -i -H 'Accept:application/json' -H 'Authorization:Basic cmVhZG9ubHk6cmVhZG9ubHk=' 'http://ylpd942.kmdc.att.com:4704/hostmap/hosts/bldd269.bhdc.att.com'
HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Content-Length: 736
...

## Swagger specification

I don't know what's relevant, so here's the whole spec:

swagger: "2.0"
info:
  description: A Simple Hostmap API
  title: SimpleHostMapAPI
  version: 0.1.0
basePath: /hostmap
consumes:
- application/json
produces:
- application/json
schemes:
- http
definitions:
  TimeStamp:
    description: A moment in time, in an ISO 8601-compliant format
    type: string
    format: 'date-time'
  Environment:
    example: TEST
    type: string
    enum: &ENVIRONMENT
      - SANDBOX
      - LAB
      - DEV
      - TEST
      - NONPROD
      - PROD
      - DR
  Cluster:
    type: object
    properties:
      timeStamp:
        $ref: '#/definitions/TimeStamp'
      id:
        type: string
        example: 'COREITKGMTNC20PROD01'
      name:
        type: string
        example: 'KM'
      desc:
        type: string
        example: "Kings Mountain PROD 01"
      env:
        enum: *ENVIRONMENT
      subGroup:
        type: string
        example: "01"
    required:
      - id
  Clusters:
    type: array
    uniqueItems: true
    items:
      $ref: '#/definitions/Cluster'
  HostName:
    description: The unique, full name of the host
    type: string
    format: 'hostname'
    example: 'ylpd268.kmdc.att.com'
  Role:
    type: string
    example: ADMIN
    enum: &ROLE
      - ADMIN
      - MASTER
      - NAME
      - EDGE
      - STAGE
      - DATA
      - COE
      - NIFI
      - LOAD_BALANCER
      - ELASTICSEARCH
      - LOGSTASH
      - KAFKA_BROKER
      - ZOOKEEPER
      - UNKNOWN
  Roles:
    type: array
    uniqueItems: true
    items:
      type: string
      enum: *ROLE
  Host:
    type: object
    properties:
      timeStamp:
        $ref: '#/definitions/TimeStamp'
      host:
        $ref: '#/definitions/HostName'
      clusters:
        $ref: '#/definitions/Clusters'
      roles:
        $ref: '#/definitions/Roles'
    required:
      - host
  Hosts:
    type: array
    uniqueItems: true
    items:
      $ref: '#/definitions/Host'
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  Principal:
    type: object
    properties:
      name:
        type: string
      roles:
        type: array
        items:
          type: string

securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /clusters:
    get:
      summary: Returns a list of clusters
      operationId: findClusters
      parameters:
        - in: query
          name: id
          description: Filter by the cluster id
          required: false
          type: string
        - in: query
          name: name
          description: Filter by the cluster name
          required: false
          type: string
        - in: query
          name: env
          description: Filter by the cluster environment
          required: false
          type: string
          enum: *ENVIRONMENT
        - in: query
          name: subGroup
          description: Filter by the cluster sub-group
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Clusters"
        '400':
          description: The specified cluster ID is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '401':
          description: Unauthorized access for a lack of authentication
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified ID was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /clusters/{id}:
    get:
      summary: Returns a cluster by ID
      operationId: findCluster
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: The ID of the cluster to return
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Cluster"
        '400':
          description: The specified cluster ID is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '401':
          description: Unauthorized access for a lack of authentication
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified ID was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /hosts:
    get:
      summary: Returns a list of one or more hosts
      operationId: findHosts
      parameters:
        - in: query
          name: clusterId
          description: Filter by the cluster id
          required: false
          type: string
        - in: query
          name: clusterName
          description: Filter by the cluster name
          required: false
          type: string
        - in: query
          name: clusterEnv
          description: Filter by the cluster environment
          required: false
          type: string
          enum: *ENVIRONMENT
        - in: query
          name: clusterSubGroup
          description: Filter by the cluster sub-group
          required: false
          type: string
        - in: query
          name: hostName
          description: Filter by the full host name
          required: false
          type: string
        - in: query
          name: roles
          description: Filter by one or more roles
          required: false
          type: array
          uniqueItems: true
          items:
            type: string
            enum: *ROLE
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Hosts"
        '400':
          description: One or more of the specified cluster query fields are invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster or host with the specified ID or name was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /hosts/{hostName}:
    get:
      summary: Returns a host object by hostName
      operationId: findHost
      parameters:
        - in: path
          name: hostName
          required: true
          type: string
          description: The name of the host to return
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Host"
        '400':
          description: The specified name name is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified name was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

## Steps to reproduce
1. Compile API code to a executable named _shm_
2. Run the server on a Linux host, listening on port 4704
(i.e., shm --port 4704)
3, From the same box, send curl requests that look like this:
curl -i -H 'Accept:application/json' -H 'Authorization:Basic cmVhZG9ubHk6cmVhZG9ubHk=' 'http://127.0.0.1:4704/hostmap/hosts/bldd269.bhdc.att.com'
or...
curl -i --basic -u "readanly:readonly" 'http://127.0.0.1:4704/hostmap/hosts/bldd269.bhdc.att.com'
4. I also ran the same commands from a different box
e.g.:
 curl -i --basic -u "readanly:readonly" 'http://ylpd942.kmdc.att.com:4704/hostmap/hosts/bldd269.bhdc.att.com'

## Environment
swagger version: dev  
go version: 1.12.5  
OS:   Windows 7

**Comment by pauluzee** [comment]
Better formatted Swagger spec:

```
swagger: "2.0"
info:
  description: A Simple Hostmap API
  title: SimpleHostMapAPI
  version: 0.1.0
basePath: /hostmap
consumes:
- application/json
produces:
- application/json
schemes:
- http
definitions:
  TimeStamp:
    description: A moment in time, in an ISO 8601-compliant format
    type: string
    format: 'date-time'
  Environment:
    example: TEST
    type: string
    enum: &ENVIRONMENT
      - SANDBOX
      - LAB
      - DEV
      - TEST
      - NONPROD
      - PROD
      - DR
  Cluster:
    type: object
    properties:
      timeStamp:
        $ref: '#/definitions/TimeStamp'
      id:
        type: string
        example: 'COREITKGMTNC20PROD01'
      name:
        type: string
        example: 'KM'
      desc:
        type: string
        example: "Kings Mountain PROD 01"
      env:
        enum: *ENVIRONMENT
      subGroup:
        type: string
        example: "01"
    required:
      - id
  Clusters:
    type: array
    uniqueItems: true
    items:
      $ref: '#/definitions/Cluster'
  HostName:
    description: The unique, full name of the host
    type: string
    format: 'hostname'
    example: 'ylpd268.kmdc.att.com'
  Role:
    type: string
    example: ADMIN
    enum: &ROLE
      - ADMIN
      - MASTER
      - NAME
      - EDGE
      - STAGE
      - DATA
      - COE
      - NIFI
      - LOAD_BALANCER
      - ELASTICSEARCH
      - LOGSTASH
      - KAFKA_BROKER
      - ZOOKEEPER
      - UNKNOWN
  Roles:
    type: array
    uniqueItems: true
    items:
      type: string
      enum: *ROLE
  Host:
    type: object
    properties:
      timeStamp:
        $ref: '#/definitions/TimeStamp'
      host:
        $ref: '#/definitions/HostName'
      clusters:
        $ref: '#/definitions/Clusters'
      roles:
        $ref: '#/definitions/Roles'
    required:
      - host
  Hosts:
    type: array
    uniqueItems: true
    items:
      $ref: '#/definitions/Host'
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  Principal:
    type: object
    properties:
      name:
        type: string
      roles:
        type: array
        items:
          type: string

securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /clusters:
    get:
      summary: Returns a list of clusters
      operationId: findClusters
      parameters:
        - in: query
          name: id
          description: Filter by the cluster id
          required: false
          type: string
        - in: query
          name: name
          description: Filter by the cluster name
          required: false
          type: string
        - in: query
          name: env
          description: Filter by the cluster environment
          required: false
          type: string
          enum: *ENVIRONMENT
        - in: query
          name: subGroup
          description: Filter by the cluster sub-group
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Clusters"
        '400':
          description: The specified cluster ID is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '401':
          description: Unauthorized access for a lack of authentication
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified ID was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /clusters/{id}:
    get:
      summary: Returns a cluster by ID
      operationId: findCluster
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: The ID of the cluster to return
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Cluster"
        '400':
          description: The specified cluster ID is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '401':
          description: Unauthorized access for a lack of authentication
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified ID was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /hosts:
    get:
      summary: Returns a list of one or more hosts
      operationId: findHosts
      parameters:
        - in: query
          name: clusterId
          description: Filter by the cluster id
          required: false
          type: string
        - in: query
          name: clusterName
          description: Filter by the cluster name
          required: false
          type: string
        - in: query
          name: clusterEnv
          description: Filter by the cluster environment
          required: false
          type: string
          enum: *ENVIRONMENT
        - in: query
          name: clusterSubGroup
          description: Filter by the cluster sub-group
          required: false
          type: string
        - in: query
          name: hostName
          description: Filter by the full host name
          required: false
          type: string
        - in: query
          name: roles
          description: Filter by one or more roles
          required: false
          type: array
          uniqueItems: true
          items:
            type: string
            enum: *ROLE
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Hosts"
        '400':
          description: One or more of the specified cluster query fields are invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster or host with the specified ID or name was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /hosts/{hostName}:
    get:
      summary: Returns a host object by hostName
      operationId: findHost
      parameters:
        - in: path
          name: hostName
          required: true
          type: string
          description: The name of the host to return
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Host"
        '400':
          description: The specified name name is invalid (e.g., an empty string)
          schema:
            $ref: "#/definitions/Error"
        '404':
          description: A cluster with the specified name was not found
          schema:
            $ref: "#/definitions/Error"
        '503':
          description: The backend server is temporarily unavailable
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
```

**Comment by pauluzee** [comment]
Here's the configure API file:

```
// This file is safe to edit. Once it exists it will not be overwritten
// go:generate swagger generate server --target ..\..\simpleHostmap --name SimpleHostMap --spec ..\swagger.yml

package restapi

import (
	"crypto/tls"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/security"
	log "github.com/sirupsen/logrus"

	"simpleHostmap/data"
	"simpleHostmap/restapi/operations"
)

func configureFlags(api *operations.SimpleHostMapAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{
}

func configureAPI(api *operations.SimpleHostMapAPI) http.Handler {
	data.ConfigureData()
	data.Connect()

	api.ServeError = errors.ServeError
	api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()
	api.JSONProducer = runtime.JSONProducer()

	// Applies when the Authorization header is set with the Basic scheme
	api.BasicAuthAuth = func(user string, pass string) (interface{}, error) {
		log.WithFields(log.Fields{
			"user":     user,
			"password": pass,
		}).Info("BasicAuthAuth")
		return data.IsAuthorized(user, pass)
	}

	// Set your custom authorizer if needed. Default one is security.Authorized()
	// Expected interface runtime.Authorizer
	//
	// Example:
	api.APIAuthorizer = security.Authorized()

	api.FindClusterHandler  = operations.FindClusterHandlerFunc(data.FindCluster)
	api.FindClustersHandler = operations.FindClustersHandlerFunc(data.FindClusters)
	api.FindHostHandler     = operations.FindHostHandlerFunc(data.FindHost)
	api.FindHostsHandler    = operations.FindHostsHandlerFunc(data.FindHosts)

	api.ServerShutdown = ShutdownAPI

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *http.Server, scheme, addr string) {}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}

func ShutdownAPI() {}

```

**Comment by casualjim** [comment]
This does look an issue with the proxy not so much with go-swagger

**Comment by pauluzee** [comment]
I (finally!) figured out what the issue is.  The proxy access has to be disabled for requests made locally.
Setting this environmental variable did the trick:
export no_proxy="127.0.0.1,localhost"
Now all of my requests are going though and working as they should.
Thanks for taking a look at this!
