### ISSUE TITLE
Mixin host issue

### ISSUE THREAD

**Issue by feodor-shi** [go-swagger/go-swagger#1965]
## Problem statement
INPUT

swagger-basic.yaml
```
swagger: '2.0'
host: localhost:9000
```
swagger-qa.yaml
`host: host.com`

ACTUAL OUTPUT

```
swagger: "2.0"
host: localhost:9000
paths: {}
```
EXPECTED OUTPUT
```
swagger: "2.0"
host: host.com
paths:
```

## Swagger specification
2.0
## Steps to reproduce
`swagger mixin --compact --format yaml --output ./api/swagger.yaml ./api/swagger-basic.yaml ./api/swagger-qa.yaml`
## Environment
swagger version:  
```
$ bin/swagger version
dev

```
go version: 
```
go version 
go version go1.12.5 darwin/amd64 
```
OS:  macos sierra 10.13.6

**Comment by fredbi** [comment]
There is indeed a bug here but it's no what you'd expect.
Your expectations do not match the way mixin works, that is it always prioritize the primary spec.
In other words, mixin operates as "first is right" when you might have expect "last is right".

In your example, mixin is not expected to replace the primary host with the value from the next spec.

The bug I concede here is the case when primary spec has an empty host: in that case, it is legit to expect that the first non empty host specification is used.
