### ISSUE TITLE
There are always many error when my go version is 1.12.5 and not  in GOPATH.

### ISSUE THREAD

**Issue by l-xue-yu** [go-swagger/go-swagger#1970]
## Problem statement
I can not generate a spec from source.There is always a problem.I think that is because my project not in GOPATH but I update my go to 1.12.5.And my project can run.I have gomod,and vendor.

## Steps to reproduce
![image](https://user-images.githubusercontent.com/42016055/59572084-4289a580-90dd-11e9-910a-14c4a48bcc14.png)

## Environment
swagger version: dev
go version: 1.12.5
OS:   windows

**Comment by fredbi** [comment]
Duplicates #1681
