### ISSUE TITLE
Issue generating servers which have 'api' in their name

### ISSUE THREAD

**Issue by bvwells** [go-swagger/go-swagger#1971]
## Problem statement

There seems to be an issue when generating servers which have the text 'api' in their name. When generating a server with 'api' in the name the api part is stripped from the directory name in which the servers main.go is located. For example, running the generator with the following command

```
swagger generate server -f swagger.yaml --name custom-server-api
```

I would expect the main.go to be generated in the folder structure './cmd/custom-server-api-server/', however the main.go is actually generated in the folder './cmd/custom-server-server/'. 

I had a quick look through past issues and couldn't find anything reported similar to this issue. My apologies if this has been reported before.

## Swagger specification

Used example swagger spec defined [here](https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/custom-server/swagger/swagger.yml)

## Steps to reproduce

Run the command:

```
swagger generate server -f swagger.yaml --name custom-server-api
```

Notice that main.go is generated in the folder 'custom-server-server' instead of the expected folder 'custom-server-api-server'.

## Environment
swagger version: v0.19.0 
go version: go1.11.5 windows/amd64
OS: Windows

**Comment by fredbi** [comment]
Yes this done [here](https://github.com/go-swagger/go-swagger/blob/d6301135e5ee4fb723d7880192d45e94b6956fe4/generator/shared.go#L1010).
The appName is reused in some other places where a trailing API in name sucks. We should have a dedicated variable for the main package.

**Comment by mikegleasonjr** [comment]
Also letting the choice of using any directory name, without appending '-server' would be great. Dissociating this directory with other usage elsewhere else would be good!
