### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by pdrum** [go-swagger/go-swagger#1989]
I used this library for documenting a web service and really liked your approach to generating the specs from code. However the docs did not have kind of a getting started guide that looks like a tutorial. I think such a thing eases onboarding of new users and let's the library be used by even more people. Therefore I wrote an article addressing that issue. 

What do you think of sharing a link to that article in the README? [Here's a link to the post](https://medium.com/@pedram.esmaeeli/generate-swagger-specification-from-go-source-code-648615f7b9d9). It will help with issues like https://github.com/go-swagger/go-swagger/issues/1053

**Comment by casualjim** [comment]
Nice article!

Feel free to send a PR with the link.

In the most ideal world, maybe you can cross post this article to our [docs](https://github.com/go-swagger/go-swagger/blob/master/docs/generate/spec.md)? Or add it to our [menu](https://github.com/go-swagger/go-swagger/blob/master/docs/SUMMARY.md).

**Comment by pdrum** [comment]
Sure. 

Is it ok if I add a new segment called `Generating Spec` under tutorials section of the summary, containing a short summary and a link to the post?

**Comment by casualjim** [comment]
of course

**Comment by pdrum** [comment]
@casualjim Will you please take a look at [this PR](https://github.com/go-swagger/go-swagger/pull/1990)?

**Comment by casualjim** [comment]
PR #1990 fixed this
