### ISSUE TITLE
swagger:ignore not working

### ISSUE THREAD

**Issue by tywkeene-ardan** [go-swagger/go-swagger#1994]
## Problem statement

I am unable to remove a struct field from being included in the spec with `// swagger:ignore`

## Steps to reproduce

Define a struct with the `swagger:ignore` argument

```
// swagger:response TestObject
type TestObject struct {
     Data string `json:"data"`
     // swagger:ignore
     Test  int    
}                                                                                                                                     
```

Swagger command:

`swagger generate spec -o swagger.yml`

## Environment
swagger version: v0.19.0
go version: go version go1.11.5 linux/amd64
OS:  Ubuntu 18.04.2

**Comment by casualjim** [comment]
You can use

```go
// swagger:response TestObject
type TestObject struct {
     Data string `json:"data"`
     Test  int   `json:"-"`
} 
```

**Comment by tywkeene-ardan** [comment]
`json:"-"` causes the json marshaller to ignore that field, correct?

Is there a way to make this work while keeping the json field?

**Comment by HURUIZHE** [comment]
I had the same problem. How to make it work.
