### ISSUE TITLE
Swagger generate spec has broken on Gitea

### ISSUE THREAD

**Issue by zeripath** [go-swagger/go-swagger#2001]
## Problem statement

Since commit abb699c1305f28328fdb644d6e08556efefc13cf `swagger generate spec` has failed on Gitea (go-gitea/gitea#7356) and this has broken our continuous integration.

Unfortunately the error reported is not particularly clear as to what the problem is, and in fact on running `swagger generate` multiple times reveals different errors:

* `unhandled type (*types.Basic): string`
* `unhandled type (*types.Slice): []*code.gitea.io/gitea/modules/structs.AccessToken`

Running with `DEBUG=1` prepended doesn't appear to reveal any more useful information.

Any ideas how to fix would be very much appreciated.

## Steps to reproduce

```bash
git clone https://github.com/go-gitea/gitea
cd gitea
swagger generate spec
```

## Environment
swagger version: master  
go version: 1.12  
OS:   linux

**Comment by casualjim** [comment]
I've made it return the following response defintions now, which I think is more correct than the previous behavior

```
swagger generate spec | jq .responses.AccessTokenList
```
```json
{
  "description": "AccessTokenList represents a list of API access token.",
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/AccessToken"
    }
  }
}
```

```
swagger generate spec | jq .responses.MarkdownRender 
```
```json
{
  "description": "MarkdownRender is a rendered markdown document",
  "schema": {
    "type": "string"
  }
}
```

**Comment by zeripath** [comment]
Thanks @casualjim!
