### ISSUE TITLE
unknown type for field interface{}: *types.Interface

### ISSUE THREAD

**Issue by teresa-recursion** [go-swagger/go-swagger#2011]
## Problem statement

I was originally having the issue described here https://github.com/go-swagger/go-swagger/issues/2007 (not generating for a map field).  With the fix for 2007, I was able to get past that issue but am now seeing another similar problem.

Swagger isn't able to generate for a field of type Interface.

## Steps to reproduce

Put the following code in a file:

```
// swagger:response
type numPlatesResp struct {
	// in: body
	NumPlates interface{} `json:"num_plates"`
}
```

And then run:

```
swagger generate spec
```

It will display the error:

```
unknown type for field NumPlates interface{}: *types.Interface
```

A map within a response struct used to work before the recent merge on July 3.

## Environment
swagger version: 0.19.0 (master branch at commit d7bdf7cb)
go version: go1.11
OS: macOS 10.13.6

**Comment by casualjim** [comment]
your app is not public by any chance?

**Comment by teresa-recursion** [comment]
No, it is a private repo, unfortunately...

**Comment by casualjim** [comment]
k gimme a few, fixing this shouldn't take long

**Comment by casualjim** [comment]
Fix is in branch `issue-2011` I need to wait for the code to be reviewed before it can get merged

**Comment by teresa-recursion** [comment]
Thank you so much for the fast response and fix!  :+1:
