### ISSUE TITLE
Add `Payload() *models.TheError` to error types

### ISSUE THREAD

**Issue by aeneasr** [go-swagger/go-swagger#2018]
## Problem statement

Client code generated by go-swagger includes structs for transporting error responses like 404, 409, etc:

```go
// NewCreateOAuth2ClientBadRequest creates a CreateOAuth2ClientBadRequest with default headers values
func NewCreateOAuth2ClientBadRequest() *CreateOAuth2ClientBadRequest {
	return &CreateOAuth2ClientBadRequest{}
}

/*CreateOAuth2ClientBadRequest handles this case with default header values.

genericError
*/
type CreateOAuth2ClientBadRequest struct {
	Payload *models.GenericError
}

func (o *CreateOAuth2ClientBadRequest) Error() string {
	return fmt.Sprintf("[POST /clients][%d] createOAuth2ClientBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOAuth2ClientBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
```

For each error code, a new struct is being generated. This makes getting the payload for these errors very cumbersome, as one has to do multiple type assertions.

Instead, it would be super useful if these errors expose a method `Payload` that simply returns `o.Payload`:

```go
func (o *CreateOAuth2ClientBadRequest) Payload() *ThePayloadType {
	return o.Payload
}
```

That way, we could simply create an interface and type assert against that, if the inner payload is required!

## Swagger specification

Not relevant.

## Steps to reproduce

Generate a client using any swagger definitions that has HTTP Error Response Codes.

## Environment
swagger version: 0.19.0  
go version: 11.12.5
OS: irrelevant

**Comment by fredbi** [comment]
hi @aeneasr. I think this is good idea to have this interface. People are struggling with getting payload through type assertion.  PR welcome (that is not a hard one).

**Comment by aeneasr** [comment]
Would

```


{{ if .Schema }}
func ({{ .ReceiverName }} *{{ pascalize .Name }}) Payload() {{ if and (not .Schema.IsBaseType) (not .Schema.IsInterface) .Schema.IsComplexObject (not .Schema.IsStream) }}*{{ end }}{{ if (not .Schema.IsStream) }}{{ .Schema.GoType }}{{ else }}io.Writer{{end}} {
	return o.Payload
}
{{ end }}
```

in `templates/client/response.gotmpl` do the job here?
