### ISSUE TITLE
swagger flatten assumes incorrect base-path

### ISSUE THREAD

**Issue by pwmcintyre** [go-swagger/go-swagger#2021]
## Problem statement

assume I have a collection of lots of nested spec files like so: (totally fictitious)
- api/petStore.yaml
- models/pet.yaml
- models/error.yaml

where `api/petStore.yaml` includes `$ref: models/error.yaml#/error`

then run:
`swagger flatten ./api/petStore.yaml`

the flatten command assumes a basePath of `./api`, which in this case is incorrect and makes all the references not resolve correctly

error:
`open /Users/pwmcintyre/git/example/api/models/error.yaml: no such file or directory`

offending line:
https://github.com/go-swagger/go-swagger/blob/2f32a5a852851b98aa1ed3d0d3d2aab4dcf27c6b/cmd/swagger/commands/flatten.go#L41

I'm wondering if we can make this value parameterized -- example:
`swagger --basePath . flatten ./api/petStore.yaml`

... or if there are other workarounds?

## Environment
swagger version: v0.19.0
go version: go1.12.7 darwin/amd64
OS: macos

**Comment by pwmcintyre** [comment]
I found one workaround was to make all reference to the current file:
`$ref: ../models/error.yaml#/error`

this works but I don't think it's as elegant as specifying the basePath. In my real use-case it looks more like `../../../models/v1.0.0.yaml` (which gets a bit confusing when looking at it with human eyes)

**Comment by fredbi** [comment]
@pwmcintyre `$ref`is following the jsonschema way of finding items relative to basePath. If you store a thing in `./api` every ref inside this thing is relative to `./api`. So yes in your case, `$ref: ../model/...` is the correct way of specifying things.

**Comment by pwmcintyre** [comment]
@fredbi - reviewing the spec, i can see see where I went wrong here.

however ... 

> $ref is following the jsonschema way of finding items relative to basePath

I'm not sure this is quite true, I've just come into a new issue with second-degree nesting where the second nest uses basePath where it should use "the current base"

> The value of the "$ref" property MUST be a URI Reference. Resolved against the current URI base ...

https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.3

i'll close this issue and raise a new issue for the above

**Comment by pwmcintyre** [comment]
^ regarding my previous comment -- I can see go-swagger uses go-openapi/analysis where you've added [test-cases for nested specs](https://github.com/go-openapi/analysis/pull/39) ... so maybe it's me again doing something bad 🤔
