### ISSUE TITLE
Can go-swagger support this json tag? Id int64 "json:id,string"?

### ISSUE THREAD

**Issue by Han-Ya-Jun** [go-swagger/go-swagger#2029]
## Problem statement

Please remove the sections that don't apply

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by casualjim** [comment]
It should already support it yes

**Comment by Han-Ya-Jun** [comment]
Ok, I will try again, thank you very much.

**Comment by mail2fish** [comment]
how to support this ',string' directive in spec yml?
