### ISSUE TITLE
swagger:strfmt annotation incompatible with slice type

### ISSUE THREAD

**Issue by Vervious** [go-swagger/go-swagger#2030]
## Problem statement

Given an annotation such as:

```
// ...
// swagger:model EnclosingType
type EnclosingType struct {
        // Note is a free form data in base64
	//
	// swagger:strfmt binary
	Note []byte `json:"noteb64,omitempty"`
}
```

Running `swagger generate spec` generates the following (excerpt):

```
        "noteb64": {
          "description": "Note is a free form data",
          "type": "string",
          "format": "byte",
          "items": {
            "type": "integer",
            "format": "uint8"
          },
          "x-go-name": "Note"
        },
```
with an unexpected items field. This is invalid according to `swagger validate ../swagger.json --stop-on-error`:

```
The swagger spec at "../swagger.json" is invalid against swagger specification 2.0.
See errors below:
- definitions.EnclosingType.properties.noteb64 in body must be of type array
```

## Expected
A valid swagger spec without an `items` property.

## Environment
swagger version: master (2f32a5)
go version: go1.12 darwin/amd64
OS:  Mac OS 10.14.5

**Comment by casualjim** [comment]
It's a bug, for which I pushed a PR. But your annotation is the one for streaming data not base64 encoded data. The right definition for what you're trying to achieve is:

```go
// ...
// swagger:model EnclosingType
type EnclosingType struct {
        // Note is a free form data in base64
	//
	// swagger:strfmt byte
	Note []byte `json:"noteb64,omitempty"`
}
```

**Comment by Vervious** [comment]
Thank you for the very fast PR, I was about to start working on one! Very appreciated.

Looks like `format: byte` is the way to go. I remember explicitly using `format:binary` back in January, but forgot why, but yes base64 encoding is what we want.

**Comment by Vervious** [comment]
Another odd thing (but minor) that I noticed is that if I add a `required: true` annotation, the order seems to matter. That is:

```
// Note
//
// required: true
// swagger:strfmt byte
```

adds it to the required property list, but

```
// Note
//
// swagger:strfmt byte
// required: true
```
does not.

I'm not sure if this is expected behavior, but thought it was worth mentioning. I can open another issue if relevant.
