### ISSUE TITLE
No useful documentation exists for spec generation

### ISSUE THREAD

**Issue by tsal** [go-swagger/go-swagger#2032]
## Problem statement

As an end-user, I'd expect documentation to cover why and how, not just list examples without any real annotation as to why they're used and how.  The swagger definition is confusing enough without a lack of documentation in this regard - the point is to generate useful documentation, which is impossible with the current state of the "book".

## Swagger specification

Any

## Steps to reproduce

Try to create specs around an already existing application, but have it generate the following spec no matter what you change / add to the command-line:

```
{
  "swagger": "2.0",
  "paths": {}
}
```

If you specify a file, you get useless errors about parsing:

```
analyzed: yaml: line 5: mapping values are not allowed in this context
```

## Environment
swagger version: v0.19.0
go version: go1.12.5
OS:   darwin/amd64

## Notes

If this sounds angry, I urge you to read everything again, carefully.  At worst, this is disappointment with tooling designed to improve documentation; disappointment that the "documentation" for said tooling is lacking, out of date, or simply does not address examples in a complete manner.  For example, the book mentions all kinds of variants of how to document a `swagger:model`, but doesn't actually show them in the examples, leaving it up to the reader to guess.

That's not documentation.

**Comment by tsal** [comment]
Closing this as a lot of it is opinion; I still contest this isn't very well-documented, but I can't offer any suggestions how to fix that.  There's a lot of "do it this way" assumptions in here, and I don't mean in godoc usage.  I can get this to work, but only if I write my code a very specific way, using a very specific set of methodologies, which does not always equate to the most efficient code. This is frustrating, especially considering it appears _some_ effort was made to document spec generation, but there are some not-so-subtle nuances were left out for no apparent reason.

**Comment by KantarBruceAdams** [comment]
I have a specific example which reproduces this issue https://github.com/go-swagger/go-swagger/issues/2101
