### ISSUE TITLE
How To mark route deprecated?

### ISSUE THREAD

**Issue by MetalRex101** [go-swagger/go-swagger#2042]
Didn't find in Documentation a way to mark route as deprecated. Is that implemented now? Thank you!

**Comment by fredbi** [comment]
No this tag is not supported at the moment, as you may verify here: https://github.com/go-swagger/go-swagger/blob/e5e8a114b82fcc3e0390020e1e36449ca922f99f/codescan/routes.go#L66

Feel free to send a PR and help us improving this project.
