### ISSUE TITLE
0.20.0 - invalid enum constants for "+" and "-" values

### ISSUE THREAD

**Issue by alexanderthurn** [go-swagger/go-swagger#2050]
## Problem statement

* In version 0.20.0 invalid code is generated using enum values like "+" or "-". 
* The generator does not add postfixes to the generated constants, thus the variable names are not distinct anymore. 
* In v.0.19.0 an enum value like "+" added "Plus" and "-" added "Minus" to the constant name, but in 0.20.0 they add nothing, resulting in two constants with the same name.

## Swagger specification

```
kennzeichenZuAbschlag:
    type: "string"
    example: "+"
    enum:
    - "+"
    - "-"
```

## Generated golang code

```
// v0.19.0
const (

	// BestellungKonditionKennzeichenZuAbschlagPlus captures enum value "+"
	BestellungKonditionKennzeichenZuAbschlagPlus string = "+"

	// BestellungKonditionKennzeichenZuAbschlagMinus captures enum value "-"
	BestellungKonditionKennzeichenZuAbschlagMinus string = "-"
)

```

```
// v0.20.0
const (

	// BestellungKonditionKennzeichenZuAbschlag captures enum value "+"
	BestellungKonditionKennzeichenZuAbschlag string = "+"

	// BestellungKonditionKennzeichenZuAbschlag captures enum value "-"
	BestellungKonditionKennzeichenZuAbschlag string = "-"
)
```

## Environment
go-swagger: 0.20.0
OS:  Docker  quay.io/goswagger/swagger

**Comment by fredbi** [comment]
Yes I can see this is a regression introduced by [this commit](https://github.com/go-openapi/swag/commit/f4f55805b6a13374dfbbe2490310247e1e0eb0b9) in go-openapi/swag, here https://github.com/go-openapi/swag/blob/de649ffb9e02183a414820c5b1b4582f7b009792/util.go#L298

Could reproduce easily. Now looking for some wokaround

**Comment by ravi198715** [comment]
I am having same problem with special character  '*' and '?', no postfixs  are not
 generated
