### ISSUE TITLE
custom generator / export generation data

### ISSUE THREAD

**Issue by iamnande** [go-swagger/go-swagger#2055]
## Problem statement

I would like to be able to generate custom applications (CLIs, Terraform Providers, etc.). Basically I'd like to generate custom items that don't fall into the classic "client" or "server" realm. 

We've tossed about the idea of writing a tool to do it leveraging this project but it seems most juicy (useful) parts of the swagger file are not gathered in an exportable fashion where callers could access the data. I could be mistaken and just haven't found the right functions to call.

My question here is are there options to have agnostically custom templates to generate pretty much anything, based on the data that's gathered as a part of the generate process, or is there currently a way to get access to that data? I'm thinking mainly about the Models, Operations, etc. so that way downstream services could call them.

If these things don't exist would there be an appetite to a PR to expose some of this data either through an added function or modification to existing functions?

cheers,

-- nande

**Comment by casualjim** [comment]
Have you seen this page? https://goswagger.io/use/template_layout.html

It shows you how to replace all the templates, or reuse them etc.

**Comment by iamnande** [comment]
hey @casualjim - i've seen that section but it seems, to me at least, like it's somewhat limited to HTTP Client/server ideas. For instance, one of the things we'd like to build would use a generated SDK (which is awesome btw), but it wouldn't do any HTTP operations.

I didn't gather that was possible using the templates, am I mistaken?

**Comment by casualjim** [comment]
You can generate whatever you want with the object model presented there. There are essentially 4 types you can provide templates for. Of course our main use case is API server/client generation for http apis so our templates contain all the content to do that.

However AFAIK it would be possible to generate just the application part which would probably be useful for making a CLI etc.

You will get access to the structs defined here: https://github.com/go-swagger/go-swagger/blob/master/generator/structs.go

That should give you all the access required to build custom generators of different types. All the code is generated from templates so you can change that to not be HTTP API's etc.  They would fit the use case of generating code in other languages too. 

So I think it fits your use case

**Comment by iamnande** [comment]
Hi @casualjim -- i'm a bit closer but it seems like this functionality is only available using the `swagger` CLI. Essentially what I'm looking for is the equivalent to the `--dump-data` flag but rather than printing out the data i'd like the data back in struct form.

Is there an appetite to a PR to enable such an action?

**Comment by casualjim** [comment]
PR's are always welcome :)
