### ISSUE TITLE
Swagger Tags interfere with imported packages

### ISSUE THREAD

**Issue by mitinarseny** [go-swagger/go-swagger#2057]
## Problem statement
Some tags in swagger specification may interfere with other imported packages. For example, if I specify tag `sync` then it interferes with Go `sync` package in import in `configure_....go` file. Current solution for me is not to use tag names that can interfere with other packages. But it would be better to fix this.

## Swagger specification
```
...
paths:
  /sync:
    post:
      operationId: SyncUser
      tags:
        - sync
...
```

## Environment
swagger version: 2.0 
go version: 1.12.7

**Comment by fredbi** [comment]
Related: #1291
