### ISSUE TITLE
How to respond with a custom model for Auth errors

### ISSUE THREAD

**Issue by andresperezl** [go-swagger/go-swagger#2060]
## Problem statement
I have this in my configure file:
```go
api.APIKeyHeaderAuth = func(token string) (interface{}, error) {
		if strings.HasPrefix(token, "API") {
			return token, nil
		}
		return token, errors.New(http.StatusForbidden, "Invalid api key")
	}
```
And I'm getting the following response as expected:
```json
{"code":403,"message":"Invalid api key"}
```

But instead I would like to respond with:
```json
{
  "status": {
    "statusCode": 403,
    "message": "Invalid api key"
  }
}
```

Is it possible to do so?

And also, how would I do it for when the api key is absent (401). All my endpoints required authentication.

## Swagger specification
2.0
## Environment
swagger version: 0.20.1
go version: 1.13  
OS:  Linux

**Comment by casualjim** [comment]
I think you can define the model as a schema for the status code you want to return and then just return an instance of that generated model in your code.

```yaml
responses:
  401:
    description: Unauthenticated
    schema:
       $ref: "#/definitions/errorModel"
```

Or you make an struct that implements this interface: https://github.com/go-openapi/errors/blob/master/api.go#L28-L32 and return that

**Comment by andresperezl** [comment]
Neither of those options provided what I wanted.

Doing some more digging I think I need to provide a new `api.ServerError` which seems to be the handler for errors

**Comment by andresperezl** [comment]
This is what I did, I wrote my own implementation of the `ServeError ` function and assigned to the `api.ServerError` in the `configureApi` function:

```go
package errors

import (
	"fmt"
	"github.com/andresperezl/gol/models"
	"github.com/go-openapi/errors"
	"net/http"
	"reflect"
)

type Error interface {
	error
	Code() int32
}

type riotError struct {
	status riotStatus
}

type riotStatus struct {
	statusCode int32
	message    string
}

func (r *riotError) Error() string {
	return r.status.message
}

func (r *riotError) Code() int32 {
	return r.status.statusCode
}

func New(code int32, message string, args ...interface{}) errors.Error {
	if len(args) > 0 {
		return &riotError{
			status: riotStatus{
				statusCode: code,
				message:    fmt.Sprintf(message, args...),
			},
		}
	}
	return &riotError{
		status: riotStatus{
			statusCode: code,
			message:    message,
		},
	}
}

// ServeError the error handler interface implementation
func ServeError(rw http.ResponseWriter, r *http.Request, err error) {
	rw.Header().Set("Content-Type", "application/json")
	switch e := err.(type) {
	case Error:
		value := reflect.ValueOf(e)
		if value.Kind() == reflect.Ptr && value.IsNil() {
			errors.ServeError(rw, r, err)
			return
		}
		rw.WriteHeader(asHTTPCode(int(e.Code())))
		if r == nil || r.Method != http.MethodHead {
			_, _ = rw.Write(errorAsJSON(e))
		}
	default:
		errors.ServeError(rw, r, err)
	}
}

func errorAsJSON(err Error) []byte {
	mError := &models.Error{
		Status: &models.Status{
			StatusCode: err.Code(),
			Message:    err.Error(),
		},
	}
	b, _ := mError.MarshalBinary()
	return b
}

func asHTTPCode(input int) int {
	if input >= 600 {
		return errors.DefaultHTTPCode
	}
	return input
}
```
I mostly took everything from it and replace with my own model where I'm interested and pass everything else to the original function. This is for a small test server, so I don't need anything too complicated. @casualjim Takes for pointing me to the right direction. Closing this question :)
