### ISSUE TITLE
panic: Invalid schema provided to SchemaValidator: object has no key "default"

### ISSUE THREAD

**Issue by pal-saurabh** [go-swagger/go-swagger#2063]
## Problem statement
swagger validate returning following error.

panic: Invalid schema provided to SchemaValidator: object has no key "default"

## Steps to reproduce
cd /var/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.1/examples/tutorials/custom-server/swagger
swagger validate swagger.yml

panic: Invalid schema provided to SchemaValidator: object has no key "default"

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc000470000, 0xd08480, 0xc000470000, 0x0, 0x0, 0xea98a0, 0xc000387ce0, 0x0, 0x0, 0x0, ...)
        /var/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/schema.go:72 +0x1039
github.com/go-openapi/validate.(*SpecValidator).Validate(0xc000226c00, 0xcbbc60, 0xc000616000, 0xc0003f36b0, 0xc0003f3760)
        /var/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/spec.go:92 +0x216
github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute(0xc0004171a0, 0xc000261e60, 0x1, 0x2, 0xc0004171a0, 0x1)
        /var/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.1/cmd/swagger/commands/validate.go:60 +0x14e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000620d20, 0xc000020190, 0x2, 0x2, 0x0, 0xd57a88, 0x2a, 0xbd59a0, 0xc000265bf0)
        /var/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8dc
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /var/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
        /var/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.1/cmd/swagger/swagger.go:145 +0xc2c

## Environment
swagger version: v0.20.1  
go version: go version go1.13 linux/amd64
OS:   CentOS-7 (Linux 63-19-173-133 3.10.0-957.21.3.el7.x86_64)

**Comment by casualjim** [comment]
can you try updating your go.mod for the go-openapi projects we have newer versions which I think fixes this issue

**Comment by pal-saurabh** [comment]
updated go-openapi projects in github.com/go-swagger/go-swagger@v0.20.1/go.mod.  analysis, spec and strfmt have newer version now. Somehow it didn't solve the problem.

-- before --
github.com/go-openapi/analysis v0.19.4
github.com/go-openapi/errors v0.19.2
github.com/go-openapi/inflect v0.19.0
github.com/go-openapi/loads v0.19.2
github.com/go-openapi/runtime v0.19.4
github.com/go-openapi/spec v0.19.2
github.com/go-openapi/strfmt v0.19.2
github.com/go-openapi/swag v0.19.5
github.com/go-openapi/validate v0.19.2

-- after --
github.com/go-openapi/analysis v0.19.5
github.com/go-openapi/errors v0.19.2
github.com/go-openapi/inflect v0.19.0
github.com/go-openapi/loads v0.19.2
github.com/go-openapi/runtime v0.19.4
github.com/go-openapi/spec v0.19.3
github.com/go-openapi/strfmt v0.19.3
github.com/go-openapi/swag v0.19.5
github.com/go-openapi/validate v0.19.2

installed go-swagger again.

#go install ./cmd/swagger/
go: downloading github.com/go-openapi/loads v0.19.2
go: downloading github.com/go-openapi/validate v0.19.2
go: downloading github.com/go-openapi/analysis v0.19.5
go: downloading github.com/go-openapi/runtime v0.19.4
go: downloading github.com/go-openapi/strfmt v0.19.3
go: downloading github.com/go-openapi/swag v0.19.5
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/toqueteos/webbrowser v1.2.0
go: downloading github.com/go-openapi/spec v0.19.3
go: extracting github.com/go-openapi/strfmt v0.19.3
go: downloading go.mongodb.org/mongo-driver v1.1.1
go: extracting github.com/go-openapi/swag v0.19.5
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/toqueteos/webbrowser v1.2.0
go: downloading golang.org/x/tools v0.0.0-20190820033707-85edb9ef3283
go: extracting github.com/jessevdk/go-flags v1.4.0
go: extracting github.com/go-openapi/spec v0.19.3
go: extracting github.com/go-openapi/runtime v0.19.4
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/kr/pretty v0.1.0
go: extracting github.com/go-openapi/loads v0.19.2
go: extracting github.com/go-openapi/analysis v0.19.5
go: downloading github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
go: downloading github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
go: downloading github.com/go-openapi/inflect v0.19.0
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/go-openapi/validate v0.19.2
go: downloading github.com/spf13/viper v1.4.0
go: extracting github.com/go-openapi/inflect v0.19.0
go: extracting github.com/kr/pretty v0.1.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
go: extracting github.com/spf13/viper v1.4.0
go: extracting github.com/gorilla/handlers v1.4.2
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/go-openapi/errors v0.19.2
go: extracting github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: extracting go.mongodb.org/mongo-driver v1.1.1
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: extracting gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/spf13/afero v1.2.2
go: downloading github.com/spf13/cast v1.3.0
go: extracting github.com/hashicorp/hcl v1.0.0
go: extracting github.com/go-openapi/errors v0.19.2
go: downloading github.com/kr/text v0.1.0
go: downloading github.com/pelletier/go-toml v1.4.0
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: extracting github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/spf13/pflag v1.0.3
go: extracting golang.org/x/tools v0.0.0-20190820033707-85edb9ef3283
go: extracting github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/go-openapi/jsonreference v0.19.2
go: extracting github.com/go-openapi/jsonpointer v0.19.3
go: downloading golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
go: extracting github.com/kr/text v0.1.0
go: downloading golang.org/x/text v0.3.2
go: extracting github.com/pelletier/go-toml v1.4.0
go: downloading github.com/go-stack/stack v1.8.0
go: extracting github.com/spf13/jwalterweatherman v1.1.0
go: extracting github.com/spf13/pflag v1.0.3
go: extracting github.com/go-openapi/jsonreference v0.19.2
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: extracting github.com/go-stack/stack v1.8.0
go: extracting github.com/PuerkitoBio/purell v1.1.1
go: downloading golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: extracting github.com/magiconair/properties v1.8.1
go: extracting golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
go: extracting github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: extracting golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: extracting golang.org/x/text v0.3.2
go: finding github.com/go-openapi/loads v0.19.2
go: finding github.com/go-openapi/swag v0.19.5
go: finding github.com/jessevdk/go-flags v1.4.0
go: finding github.com/go-openapi/analysis v0.19.5
go: finding github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
go: finding github.com/go-openapi/jsonpointer v0.19.3
go: finding github.com/go-openapi/runtime v0.19.4
go: finding github.com/go-openapi/spec v0.19.3
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/go-openapi/strfmt v0.19.3
go: finding github.com/go-openapi/jsonreference v0.19.2
go: finding github.com/go-openapi/validate v0.19.2
go: finding github.com/go-openapi/errors v0.19.2
go: finding github.com/gorilla/handlers v1.4.2
go: finding github.com/PuerkitoBio/purell v1.1.1
go: finding github.com/toqueteos/webbrowser v1.2.0
go: finding github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding go.mongodb.org/mongo-driver v1.1.1
go: finding golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: finding github.com/spf13/viper v1.4.0
go: finding github.com/pkg/errors v0.8.1
go: finding golang.org/x/text v0.3.2
go: finding golang.org/x/tools v0.0.0-20190820033707-85edb9ef3283
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/go-openapi/inflect v0.19.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/pelletier/go-toml v1.4.0
go: finding github.com/kr/text v0.1.0
go: finding golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/spf13/jwalterweatherman v1.1.0
go: finding github.com/spf13/pflag v1.0.3

cd examples/tutorials/custom-server/swagger
swagger validate swagger.yml
panic: Invalid schema provided to SchemaValidator: object has no key "default"

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc000474fc0, 0xd08480, 0xc000474fc0, 0x0, 0x0, 0xea98a0, 0xc000389d40, 0x0, 0x0, 0x0, ...)
        /var/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/schema.go:72 +0x1039
github.com/go-openapi/validate.(*SpecValidator).Validate(0xc0002108c0, 0xcbbc60, 0xc0004f8000, 0xc000560370, 0xc000560420)
        /var/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/spec.go:92 +0x216
github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute(0xc000415cc8, 0xc00036fe20, 0x1, 0x2, 0xc000415cc8, 0x1)
        /var/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.1/cmd/swagger/commands/validate.go:60 +0x14e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000502f60, 0xc000020190, 0x2, 0x2, 0x0, 0xd57a88, 0x2a, 0xbd59a0, 0xc000264090)
        /var/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8dc
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /var/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
        /var/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.1/cmd/swagger/swagger.go:145 +0xc2c

**Comment by fredbi** [comment]
FYI I just made sure it works well on current master with go 1.12.6 on linux.

**Comment by fredbi** [comment]
Follow-up: just updated my linux box to go1.13, rebuilt from latest master: works fine
Checking out v0.20.1: reproduced the issue

@casualjim IMHO, just tagging current master to v0.20.2 should do the trick

**Comment by fredbi** [comment]
@pal-saurabh  @zreigz new release v0.21.0, with updated dependencies, should no more exhibit this problem. Could you please confirm?

**Comment by fredbi** [comment]
Tested again with v0.21.0, go1.13, ubuntu 18: works fine
