### ISSUE TITLE
Go v0.20.0: checksum mismatch when using GOPROXY=direct

### ISSUE THREAD

**Issue by iwittkau** [go-swagger/go-swagger#2065]
## Problem statement

Because I have private dependencies I can't use a go proxy like https://proxy.golang.org, so I'm using `GOPROXY=direct`.
Go still tries to verify modules via sum.golang.org (except my private modules because of `GONOSUMDB=git.my-company.com/*/*`).

Which results in

```
go: finding github.com/go-swagger/go-swagger v0.20.0
go: finding github.com/go-swagger/go-swagger v0.20.1
verifying github.com/go-swagger/go-swagger@v0.20.0: checksum mismatch
	downloaded: h1:nYaNsHAGa+r5u6JlcN1Zh6X7zNoOo36Shs8PHU1+G2M=
	sum.golang.org: h1:4ejFC3gnhLTI6S/j+S+7GfEaVBV3BBI2IEcFVHUteIQ=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

This does not happen when using `GOPROXY=https://proxy.golang.org`. 
So I guess the cached version of `github.com/go-swagger/go-swagger` differs from the tagged version on github?

## Steps to reproduce

Using a docker container

```
docker run -i --tty --rm golang:1.13
```

```
root@b70fd0ea2376:/go# GOPROXY=direct go mod download -json github.com/go-swagger/go-swagger@v0.20.0
```
## Environment

swagger version: 0.20.0
go version: go1.13
OS:    linux/amd64

**Comment by casualjim** [comment]
Please use go-swagger 0.20.1. I have no influence on what the cache does from golang.
From their docs (https://sum.golang.org/):

> ### I removed a bad release from my repository but it still appears in the mirror, what should I do?
> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

**Comment by iwittkau** [comment]
Ok, thanks for clarifying!

**Comment by MrVermond** [comment]
The same problem now occurs with the version 0.31.0
