### ISSUE TITLE
Allow addition of custom command line options to generated server code

### ISSUE THREAD

**Issue by Tobi042** [go-swagger/go-swagger#207]
If I am correct, there is currently no way to add custom command line options to the generated server code without modifying the ephemeral main.go. The go-flags package seems to conflict with the flag package (both packages fail upon finding unknown flags) and unlike the flag package, go-flags is object-oriented, so we can not simply define the necessary flags in every file's init() function as could be done with the built-in flag package.
As go-flags, however, is IMHO (and apparently also in the authors') much nicer than the builtin package, I propose the following solution to integrate user-defined flags with the generated parsing step.

Solution sketch:
xxx_api.go: Add a map[string]interface{} to the XxxAPI struct
configure_xxx.go: configureAPI(...): Add an example on how to populate the map with own flag groups
main.go: Call configureAPI before parser.Parse but after creating parser. After calling configureAPI, iterate over flags map from api object and call parser.AddGroup(key, "", value) for each key-value pair.

What do you think? The only downside I currently see, is that iterating over a map is unordered and so might result in help texts with differing order with each execution.
I am currently working on a pull request.

**Comment by casualjim** [comment]
if you make map a slice I'm all for it. That retains ordering

**Comment by Tobi042** [comment]
The problem I see with that is that a []interface{} slice only takes the object, but go-parser also wants a description (short appears to suffice). I think adding an extra type for that might help:

type CommandLineOptionsGroup struct {
  ShortDescription string
  LongDescription string
  Options interface{}
}

How does that sound? Where would you recommend putting such a type?

**Comment by casualjim** [comment]
yeah that's great. 
You I have a package called swag where I put everything I don't have a proper home for. Perhaps it could go in there?
