### ISSUE TITLE
JSON tags are not honored in case of allOf.

### ISSUE THREAD

**Issue by jupudibhaskar967** [go-swagger/go-swagger#2071]
## Problem statement

JSON tags in generated models are different than strings specified in the swagger yaml spec. We are using allOf functionality of the swagger 2.0 spec. Noticed when using allOf, there are UnmarshalJSON() and MarshalJSON() methods are implemented for generated structs are having the JSON tag starting with capital letter instead of what is defined in yaml.

**Swagger spec:**
```yaml
definitions:
    Pet:
        type: object
        properties:
            name:
                type: string
                x-go-name: Name
                x-nullable: true
    Cat:
        allOf:
            - $ref: "#/definitions/Pet"
            - type: "object"
              properties:
                ability:
                    type: string
                    x-go-name: Ability
                    x-nullable: true
```
Now the Cat.go file in models directory has this UnmarshalJSON() method:

```go
// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Cat) UnmarshalJSON(raw []byte) error {
        // AO0
        var aO0 Pet
        if err := swag.ReadJSON(raw, &aO0); err != nil {
                return err
        }
        m.Pet = aO0

        // AO1
        var dataAO1 struct {
                Ability *string `json:"Ability,omitempty"`
        }
        if err := swag.ReadJSON(raw, &dataAO1); err != nil {
                return err
        }

        m.Ability = dataAO1.Ability

        return nil
}
```
Is there a way to suppress this marshaller interface overriding methods from getting generated? We are using these models somewhere else in the implementation and we need "Ability" in the json tag in UnmarshalJSON() method starting with lower case 'a'.

## Environment
swagger version: 0.18
go version: 1.11
OS: Ubuntu

**Comment by fredbi** [comment]
duplicates #1276

**Comment by jupudibhaskar967** [comment]
Hey @fredbi ..
The other post which talks about this issue is giving custom tags for entire struct. Here, in this case, individual fields (properties) even with x-go-custom-tag in derived models are also capitalized. Struct that is getting generated is fine. The final unmarshalJSON() and marshaljson() methods that are generated has an private struct defined with different json tags. Is there a way we can override this behavior? Would it help to have custom templates here or is there any way not to generate those methods?

**Comment by fredbi** [comment]
@jupudibhaskar967  You specified the upper case yourself by forcing `x-go-name`.
If you let this unspecified, or specify `x-go-name: ability` you get a tag with lower case.

**Comment by casualjim** [comment]
Is that right? The x-go-name is normally to change the name of the go property but not the json property name. That should use the version that's defined in the json spec. 
The way the issue is worded, it is a bug in go-swagger

**Comment by jupudibhaskar967** [comment]
@fredbi Thanks for the quick reply. It worked.

**Comment by fredbi** [comment]
@casualjim yes i just tested it. There is some unwanted side effect of the x-go-name here.

**Comment by fredbi** [comment]
Speaking of x-go-name there are a number of existing side issues with this (eg with nested additional properties etc). Unrolling this yarn completely might lead to quite significant work.

**Comment by fredbi** [comment]
Specifically for allof serializer the bug is here and similar lines below:

https://github.com/go-swagger/go-swagger/blob/5499abf2a8c86a57f3a8112aca47a624f609689e/generator/templates/tupleserializer.gotmpl#L259

If I am following the struct template, this should be .OriginalName not .Name. Of course this is just a quick întuitiô
