### ISSUE TITLE
Flatten before serve

### ISSUE THREAD

**Issue by seblegall** [go-swagger/go-swagger#2078]
Hi,

This is more a feature proposal than a bug/issue.

What do you think of adding a flag to the serve command in order to flatten a spec file before serving it ? This could be useful when trying to serve a swagger spec file containing `$ref` to an external file. Right now, when redoc try to reach the file, it result (obviously) in a 404.

The developper UX could be : 
```bash
swagger serve --flatten swagger.json
```

I can do a PR if you judge this feature useful.

**Comment by casualjim** [comment]
PR's are always welcome
