### ISSUE TITLE
Required object value without type produces broken validator

### ISSUE THREAD

**Issue by RepentantGopher** [go-swagger/go-swagger#2081]
## Problem statement

Required object value without type produces broken validator.

## Swagger specification

```yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Another bug"
host: "localhost"
basePath: "/"
tags:
  - name: "events"
schemes:
  - "http"
paths:
  /events:
    post:
      tags:
        - "events"
      summary: "Add event"
      operationId: "addEvent"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Event object."
          required: true
          schema:
            type: object
            required:
              - "value"
            properties:
              value:
                description: Problem property
                example: 1
      responses:
        200:
          description: "OK"
```

## Steps to reproduce

Generate models or entire server from this specification.

Models validator will be like this:
```go
type Object struct {
	// Value of the tag
	// Required: true
	Value interface{} `json:"value"`
}

func (m *Object) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Object) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}
```

Function `validateValue` calls `openapi.validate.Required` function https://github.com/go-openapi/validate/blob/master/values.go#L113-L122 with given value type of `interface`.

Since given value is not pointer  `openapi.validate.Required` will return error on any incomming default value, for example, `false` for `boolean` type or `0` for `integer`.

If we add type to our field then `openapi.validate.Required` will recieve pointer and validation will successed.

Simple example https://repl.it/repls/HonorableUnevenFact

## Environment
swagger version: latest master  
go version: 1.12.7
OS: darwin/amd64

## Possible sollution

Codegen should produce required fields without type as `*interface{}` instead of `interface{}`.

**Comment by fredbi** [comment]
The `*interface{}` pattern looks unnatural to me. `*map[string]interface{}` would be better suited for that case. Problem is that brings quite some breaking change (see also https://github.com/go-swagger/go-swagger/issues/1450)
