### ISSUE TITLE
How to register a handler for the server?

### ISSUE THREAD

**Issue by Wuzi** [go-swagger/go-swagger#2083]
I'm trying to serve a chat websocket within my go-swagger API. I'm using this example: https://github.com/gorilla/websocket/tree/master/examples/chat

I tried attaching it to the http when the server starts, but after further reading I see that this can't work:

```go
func configureServer(s *http.Server, scheme, addr string) {
  hub := chat.NewHub()

  go hub.Run()
  http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
    chat.ServeWs(hub, w, r)
  })
}
```

Then I tried using a custom server and changing server.Serve() to:

```go
hub := chat.NewHub()
go hub.Run()

http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
  chat.ServeWs(hub, w, r)
})

if err := http.ListenAndServe(":8080", api.Serve(nil)); err != nil {
  log.Fatalln(err)
}
```

But also realized why this won't work.

> Error during WebSocket handshake: Unexpected response code: 404

After some reading I'm starting to understand why the /ws was never found:

```go
hub := chat.NewHub()
go hub.Run()

mux := http.NewServeMux()
mux.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
  chat.ServeWs(hub, w, r)
})

server.SetHandler(mux)
if err := server.Serve(); err != nil {
  log.Fatalln(err)
}
```

Now the websockets works but the rest api doesn't, I can see why but I don't how to make both of them work.
I'm fairly new to golang so i'm struggling with this.

How could I do that?

Thanks.

**Comment by casualjim** [comment]
You can put it in a middleware and hook it up in configure_XXX

```go
func mountWebSockets(next http.Handler) http.HandlerFunc {
   return func(w http.ResponseWriter, r *http.Request) {
       if r.URL.Path == "/ws" {
            chat.ServeWs(hub, w, r)
           return
       }
       next.ServeHTTP(w, r)
   }
}
```

**Comment by Wuzi** [comment]
Thank you! It worked.

**Comment by NeradabilliSridhar** [comment]
I am having similar issue with my project. can you please help me understanding what is middleware.

I had handled code in configure_XXX.go which is mainly handlers to swagger generated server code.
when i try accessing that API, 404 page not found error coming. But compiled code successfully. Not sure what else is missing as part of new API endpoint registry.

**Comment by NeradabilliSridhar** [comment]
Example: 
release_server_api.go:

o.handlers["GET"]["/accesscontrol/family/{family}/product/{product}/stream/{stream}/getreleasesaccess"] = accesscontrol.NewAccessBulkReleases(o.context, o.AccesscontrolAccessBulkReleasesHandler)

Configure_XXX.go:

api.AccesscontrolAccessBulkReleasesHandler = accesscontrol.AccessBulkReleasesHandlerFunc(func(params accesscontrol.AccessBulkReleasesParams, principal interface{}) middleware.Responder {
		fmt.Println("sridhar printing here...")
		fmt.Println(params)

		u := principal.(user.Model)
		if !featureOpts.Software {
			audit.AccessControl(http.StatusNotFound, params.HTTPRequest, u, "get-bulk-release-access")
			return accesscontrol.NewAccessBulkReleasesDefault(http.StatusNotFound).WithPayload(statusNotFound)
		}
		if !u.Permissions().CanGrantAccess() {
			audit.AccessControl(http.StatusForbidden, params.HTTPRequest, u, "get-bulk-release-access")
			return accesscontrol.NewAccessBulkReleasesDefault(http.StatusForbidden).WithPayload(statusForbidden)
		}
		// accounts, err := access.GetAccessRelease(access.AccessDB(), params.Product, params.Release)
		accounts, err := access.GetAccessBulkReleases(access.AccessDB(), params.Product, "18.02.02")
		if err != nil {
			audit.AccessControl(http.StatusInternalServerError, params.HTTPRequest, u, "get-bulk-release-access", err.Error())
			return accesscontrol.NewAccessBulkReleasesDefault(http.StatusInternalServerError).WithPayload(statusError)
		}
		return accesscontrol.NewAccessBulkReleasesOK().WithPayload(accounts)
	})

now compiled code and trying to access that API from Postman client.
https://wtl-c7filestest-1:8443/software/family/Protocols/product/Protocols/stream/18.02/getreleasesaccess/

result: 404 page not found
