### ISSUE TITLE
Flatten (and generate) fails intermittently

### ISSUE THREAD

**Issue by HexHacks** [go-swagger/go-swagger#2092]
## Problem statement

We use definitions referenced from different files and the flatten step sometimes fails with a message (or similar): 
> at #/definitions/user, object has no key "teamupdateOAIGen"`

I've attached a [zip file](https://github.com/go-swagger/go-swagger/files/3771429/oaigen_bug.zip) with a minimal setup that reproduces this error. The script `gen.sh` can be used, but that uses the `generate` sub-command and it's probably easier to debug this with `swagger flatten -f swagger.yaml`, as per the reproducing steps.

## Swagger specification

See attached zip file.

## Steps to reproduce

1) Extract zip file [oaigen_bug.zip](https://github.com/go-swagger/go-swagger/files/3771429/oaigen_bug.zip)
2) Navigate to `oaigen_bug` in console
3) `swagger flatten -f swagger.yaml`
4) You might have to repeat step 3 a couple of times.

## Environment
swagger version: 0.21.0
go version: N/A
OS: GNU/Linux (tested on Fedora and Ubuntu)

**Comment by fredbi** [comment]
Yep could reproduce your problem

**Comment by fredbi** [comment]
@HexHacks working on a fix to go-openapi/analysis

**Comment by fredbi** [comment]
@HexHacks your feedback is welcome. I believe it works better now:
https://github.com/go-openapi/analysis/pull/50

**Comment by HexHacks** [comment]
Sorry for late answer, but I've tested this with our more elaborate setup and it seems to work! Thank you!
