### ISSUE TITLE
swagger version always displays "dev"

### ISSUE THREAD

**Issue by KantarBruceAdams** [go-swagger/go-swagger#2100]
## Problem statement

swagger version does not report the actual version installed.
I would expect an option to report the version of the tool installed
and also the version of the openAPI/swagger spec used.

## Steps to reproduce

I downloaded swagger using: 

   go install github.com/go-swagger/go-swagger/cmd/swagger

It reports the version as "dev"

> swagger version
dev

This is okay I think as it the latest version. The project may not be using a workflow where the tip of master branch indicates the latest release.

So I try downloading some specific versions e.g.

   go get github.com/go-swagger/go-swagger/cmd/swagger@0.21

They also report the version as "dev"

## Environment
swagger version: dev 0.21.1
go version: 1.11.5
OS:   linux/amd64

**Comment by fredbi** [comment]
Duplicates #1283 (at this moment, a "won't fix": you have released versions with version built, building from source always yields "dev")

**Comment by casualjim** [comment]
if you want the version info you need to download the binaries we build.
The dev version means you built from source without setting the proper ldflags.
