### ISSUE TITLE
Unable to generate specification for "hello world"

### ISSUE THREAD

**Issue by KantarBruceAdams** [go-swagger/go-swagger#2101]
## Problem statement

I am trying to generate a swagger.json specification from annotations in the code.
The simplest hello world project results in a cryptic error:

   analyzed: yaml: line 12: mapping values are not allowed in this context

## Swagger specification

unknown

## Steps to reproduce

Run:

   swagger generate spec -i ./hello.o 

On the folllowing example:

```go
package main

import (
	"github.com/labstack/echo"
	"net/http"
)

// route_hello swagger:route GET /hello
//
// Say hello.
//
// Deprecated: false
// Responses:
// 		default: genericError
// 		    200: []hello//
func route_hello(c echo.Context) error {
	return c.String(http.StatusOK, "hello world")
}

// Package main hello world API.
//
// the purpose of this application is to learn how to use
// swapper generate spec
// that are available to turn go code into a fully compliant swagger 2.0 spec
//
// Terms Of Service:
//
// There are no TOS.
//
//     Schemes: http, https
//     Host: localhost
//     BasePath: /
//     Version: 0.0.1
//     License: MIT http://opensource.org/licenses/MIT
//     Contact: John Doe<john.doe@example.com> http://john.doe.com
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
// swagger:meta
func main() {
	e := echo.New() // Middleware

	e.GET("hello", route_hello)

	e.Start("127.0.0.1:8080")
}
```
## Environment
swagger version: dev , 0.21.1 
go version: 1.11.5
OS:   linux/amd64  Debian GNU/Linux 9.9

**Comment by KantarBruceAdams** [comment]
This is very similar to issue https://github.com/go-swagger/go-swagger/issues/2032 which was closed as it talked about the quality of the documentation rather than giving a specific example that doesn't work.

**Comment by KantarBruceAdams** [comment]
If I remove all comments I get a different cryptic error:

analyzed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `package...` into map[interface {}]interface {}

**Comment by casualjim** [comment]
this is not a valid construct: 200: []hello//

**Comment by KantarBruceAdams** [comment]
I copied it off one of the examples. Removing the line does not remove the problem.
The problem with the error is "analyzed: yaml: line 12: " does not mean anything to me.
Where is the generated yaml file for which I can try to find line 12?
The line number doesn't match an obviously faulty line in my go program.

**Comment by KantarBruceAdams** [comment]
There must be some simple rules to follow that make this work. What are they?
For example I tried a project with two files:

doc.go (copied from https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing/petstore)
```
// Package hello Petstore API.
//
// the purpose of this application is to provide an application
// that is using plain go code to define an API
//
// This should demonstrate all the possible comment annotations
// that are available to turn go code into a fully compliant swagger 2.0 spec
//
// Terms Of Service:
//
// there are no TOS at this moment, use at your own risk we take no responsibility
//
//     Schemes: http, https
//     Host: localhost
//     BasePath: /v2
//     Version: 0.0.1
//     License: MIT http://opensource.org/licenses/MIT
//     Contact: John Doe<john.doe@example.com> http://john.doe.com
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
// swagger:meta
package petstore

// APIVersion shows this API's current version
var APIVersion string

```

and main.go

```
package petstore

import (
        "github.com/labstack/echo"
        "net/http"
        //      "tools/src/hello/docs"
)

func route_hello(c echo.Context) error {
        return c.String(http.StatusOK, "hello world")
}

var (
        // Version is a compile time constant, injected at build time
        Version string
)

func main() {
        e := echo.New() // Middleware

        // this has no real purpose besides making the import present in this main package.
        // without this line the meta info for the swagger doc wouldn't be discovered
        APIVersion = Version

        e.GET("hello", route_hello)

        e.Start("127.0.0.1:8080")
}
```

Even this gives me errors:

$swagger generate spec -w . -i doc.go -o swagger.json
analyzed: yaml: line 9: mapping values are not allowed in this context
$swagger generate spec -w . -i main.go -o swagger.json
analyzed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `package...` into map[interface {}]interface {}

But I can get a swagger.json for the petstore project verbatum or with just the doc.go on its own.

What on earth is going on here?

**Comment by casualjim** [comment]
have you seen this:

* https://goswagger.io/use/spec.html
* https://medium.com/@pedram.esmaeeli/generate-swagger-specification-from-go-source-code-648615f7b9d9

**Comment by KantarBruceAdams** [comment]
I have read them several times now but I've clearly missed something. Regardless of my failing there is at least one defect here.

* Errors should be reported with line numbers against the file being parsed not some intermediate file.

* Adding a source file with no go-swagger comments in it at all should not prevent swagger file being generated (unless there is something special I should know here).

**Comment by casualjim** [comment]
you don't need the -i 

```$ swagger generate spec``` 

even without args in your case it should work
The `-i` flag is for when you want to merge the results into an existing json or yaml spec document

**Comment by KantarBruceAdams** [comment]
That seems to be it. I looked for a reference and found one buried in the manual

"If an annotation is not yet supported or you want to merge with a pre-existing spec, you can use the -i parameter."

So that is a clear RTFM.
However, the help text could mention this.
i.e. instead of:

    -i, --input=             the file to use as input

something like:

     -i, --input=             an input swagger file to merge with

I found a reference somewhere that suggested -i was the file containing the overview (i.e. swagger:meta). This is probably for a different tool altogether.

I can now see that "analyzed: yaml: " is referring to a swagger .yaml 
I would still argue that the error message format is wrong. For a start it could be a JSON file.
"analyzed: swagger:" would be a little better.

I'm not sure what JSON parser is used internally here. I am surprised it did not take one look at my source and report "not a valid JSON file". The first open curly is miles away.

The unix convention is "location: level: message"
If you were following that my message could be:

     `main.go: line ?: error: your message here`

Either of those would have instantly shown my mistake.

**Comment by casualjim** [comment]
You're right, that's a good suggestion
