### ISSUE TITLE
File type in form-data 

### ISSUE THREAD

**Issue by ankit307** [go-swagger/go-swagger#2105]
## Problem statement
While defining the specs from code. I am not able to define an API signature that takes file in input from form data.

## Swagger specification
Go code comment to generate secification =>

//swagger:parameters BatchSMSLink
type BatchSMSRequest struct {
	// File which should be uploaded having array of SMS events
	// in: formData
	// type: file
       // format: binary
	file string
}

Swagger.json file not get update with same parameters.

Expected Result  =>
 "parameters": [
          {
            "type": "file",
            "description": "File which should be uploaded having array of SMS events",
            "name": "file",
            "in": "formData",
            "format": "binary"
          }
        ] 

Generated Result =>

"parameters": [
          {
            "type": "object",
            "description": "File which should be uploaded having array of SMS events",
            "name": "file",
            "in": "formData"
          }
        ] 

## Environment
swagger version: 0.20.1
go version: 1.13  
OS:   Ubuntu 18.04.3

**Comment by casualjim** [comment]
see here: https://github.com/go-swagger/go-swagger/blob/master/fixtures/goparsing/classification/operations/noparams.go#L28-L33

**Comment by ankit307** [comment]
> see here: https://github.com/go-swagger/go-swagger/blob/master/fixtures/goparsing/classification/operations/noparams.go#L28-L33

Thanks , It was helpful
