### ISSUE TITLE
Add ability for server pre-shutdown hook

### ISSUE THREAD

**Issue by keperry** [go-swagger/go-swagger#2108]
## Problem statement
It would be awesome to be able to allow consumers of this library to add a pre-shutdown hook to the server that gets generated by go-swagger.  This would allow consumers to handle any tasks that are required before stopping accepting new connections (before shutting down the http(s) server).
In our particular case, we want to signal to the readiness probe (kube) that we are shutting down (return 500) so no traffic gets routed to this pod.  There is a small window of time when we still need to accept new connections (it is not deregistered from kube yet). When the SIGINT/SIGTERM signals are sent, we need to wait a period of time before shutting down the actual http server.

## Area to add this feature
This should be a small change that we should be able to add this to the templates pretty easily.   I can create a PR for this.

## Environment
swagger version: 2.x  
go version: 1.12.7
OS:   Mac/Darwin

**Comment by keperry** [comment]
This issue can be closed.  I will leave it open for maintainers because I am not sure of the workflow here.

**Comment by casualjim** [comment]
we tend to close with the PR. Thanks for your contribution!
