### ISSUE TITLE
Unmarshal error with apipie generated swagger

### ISSUE THREAD

**Issue by lhw** [go-swagger/go-swagger#2115]
## Problem statement
Parsing the apipie-rails generated swagger docs causes the following error:
`json: cannot unmarshal array into Go struct field SwaggerProps.paths of type string`
I already tested a few other tools including Postman, Insomnia and swagger2openapi which seemed to process the file just fine.
Sadly the error is not very descriptive but I assume that one of the paths could not be parsed. But I cant find anything suspicious when I parse the object with `jq < schema_swagger.json ".paths | keys | unique[]"`

## Swagger specification
https://gist.github.com/lhw/5d000428a314f300c78445fcc4e4ec61

## Steps to reproduce
`$ swagger validate schema_swagger.json`

## Environment
swagger version: v0.21.0
go version: 1.13
OS: debian unstable

**Comment by casualjim** [comment]
that json doc is not complete

**Comment by lhw** [comment]
Weird. There might be cutoff on my xclip. I'll fix it tomorrow

**Comment by lhw** [comment]
Alright. The Gist now contains the full spec

**Comment by fredbi** [comment]
@lhw you spec is invalid. Here is the diff with a slightly modified valid one:
```
1957,1959c1957
<             "in": [
<               "parameters"
<             ],
---
>             "in": "query",
2163,2165c2161
<             "in": [
<               "parameters"
<             ],
---
>             "in": "query",
2231,2233c2227
<             "in": [
<               "parameters"
<             ],
---
>             "in": "query",
2299,2301c2293
<             "in": [
<               "parameters"
<             ],
---
>             "in": "query",
3797c3789
<                       "type": "any_type",
---
>                       "type": "object",
4138c4130
<                       "type": "any_type",
---
>                       "type": "object",
8334c8326
<                       "type": "any_type",
---
>                       "type": "object",
19094c19086
<                       "type": "any_type",
---
>                       "type": "object",
19209c19201
<                       "type": "any_type",
---
>                       "type": "object",
19324c19316
<                       "type": "any_type",
---
>                       "type": "object",
19479c19471
<                       "type": "any_type",
---
>                       "type": "object",
```

**Comment by lhw** [comment]
Thank you for your work. I guess apiepie generates the swagger code based on wrong spec. Might have to open the issue there instead. By the way how did you generate the diff or did you do that manually?
