### ISSUE TITLE
Endless loop in `swagger generate spec`

### ISSUE THREAD

**Issue by israel-hdez** [go-swagger/go-swagger#2122]
## Problem statement

The title says mostly all. Running `swagger generate spec -o ./swagger.json` on [Kiali project](https://github.com/kiali/kiali) never finishes when using go-swagger v0.20.0 or v0.21.0. Version 0.19.0 works fine.

Sorry to be vague. I cannot think what else to explain. Feel free to ask.

## Steps to reproduce

1. Clone the https://github.com/kiali/kiali repository of the Kiali project.
2. `cd` into the cloned repo.
3. Run `swagger generate spec -o ./swagger.json`
  * Using go-swagger v0.19.0 the spec is generated in a few seconds. 
  * Using go-swagger v0.20.0 or v0.21.0, I left it running for about 5 minutes and it didn't finish. I interrupted the process. This is why I assume there is an endless loop.

I know I could stick to version 0.19.0, but I would like to move to using Go1.13. When doing the move, 0.19.0 no longer works correctly.

The issue seems unrelated to the go version, because I tried go-swagger v0.20.0 while in go1.11 and it also won't generate the spec.

## Environment
swagger version: 0.20.0 and 0.21.0
go version: 1.13.4 and 1.11.13
OS: Fedora 29

**Comment by mfranczy** [comment]
Yesterday when I tried to generate a new spec it happened to me too, I think I found the issue (the fix worked locally). This piece of code is the reason of endless loop:
https://github.com/go-swagger/go-swagger/blob/master/codescan/application.go#L520-L524

there is a check if pkg already exists in `a.AllPackages` map, however the assigned key (`k` var)  is not always equal to `pk.PkgPath`. The loop should look like that:
```
for k, v := range pkg.Imports {
		if _, known := a.AllPackages[v.PkgPath]; known {
			continue
		}
		a.AllPackages[v.PkgPath] = v
		if err := a.processPackage(v); err != nil {
			return err
		}
		if err := a.walkImports(v); err != nil {
			return err
		}
	}
```

I am going to prepare a PR to fix the issue.
