### ISSUE TITLE
why `generate operation` is required name option?

### ISSUE THREAD

**Issue by Mitu217** [go-swagger/go-swagger#2123]
## Problem statement

I want to create all operations to code. but it will be failed.
the reason is `generate operation` is required name option.
I want to know why name option is mandatory 🙇

## Swagger specification
nothing

## Steps to reproduce
run `swagger generate operation`

## Environment
swagger version: dev
go version: go1.13 
OS:  darwin/amd64

**Comment by casualjim** [comment]
You can just use `generate sever` it will do all operations.

**Comment by Mitu217** [comment]
thanks for answer 🙏 

I was able to derive the desired result by using the following options such as `--skip-models` and `--skip-support`

```
swagger generate server --skip-models --skip-support
```
