### ISSUE TITLE
Is there an example to generate a swagger spec document from the code?

### ISSUE THREAD

**Issue by netsharec** [go-swagger/go-swagger#213]
I have read the [swagger.json generation](https://goswagger.io/generate/spec.html) and feel confused. Could you please give an example for it :)

**Comment by casualjim** [comment]
This folder uses most of the annotations

https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing/petstore

**Comment by bklau** [comment]
@casualjim 3 questions : 
Q1: Does a struct for Parameter model have to be declared in the SAME .go file where the swagger:route is declared for a router function?
Q2: Assume that I have a route "/services/{serviceName}", how would I named the field associated with the path "{serviceName}" above in a struct wrapper for path params?
i.e. type  ServiceNameParam struct {
  ServiceName string <== is this named as "serviceName" or "ServiceName" or "SERVICENAME"?
}
Q3: Is the annotations casesenstive like "Required" vs "required"?. I see mixed examples about this.

**Comment by casualjim** [comment]
Q1: nope it needs to be declared in the same app and it needs to be imported so that goswagger can find it by following imports starting at the main package.

Q2: you would add all of them in the parameter struct at this moment, in the case of parameters you would add a doc comment: `// in: path`. Take a look at some of the generated code examples because they contain all the known annotations as well.

Q3: not case sensitive, didn't want to have debates over casing. Whatever looks good to you in docs is what you can use.

**Comment by bklau** [comment]
@casualjim Thx for the answers. One more question: Can methods in an interface be annotated?

**Comment by casualjim** [comment]
only when it's used in a discriminator IIRC. There is code in the scan package that treats nullary methods as properties if certain conditions are met.

**Comment by bklau** [comment]
@casualjim : My generated spec is now working but seems to be missing a parameter "description"  to indicate to end user of the API URL endpoint of what's its doing. Example below, I wanted the line "Disable/enable a compute node EC2 machine with a given IP address" to show up as some sorta of description for the parameter... Am I missing something?

// v2PutXXX disable/enable a compute node EC2 machine with a given IP address
//
// swagger:route PUT /compute/nodes/{nodeIPAddress} v2PutXXX
//
// 	Disable/enable a compute node machine with a given IP address
//
//     Produces:
//     - application/json
//
//	   Consumes:
//	   - application/json
//
//     Schemes: http
//
//     Responses:
//       default: errorResp
//       200: okResp
//
func v2PutXXX(....)

**Comment by casualjim** [comment]
you still need to add enlist a struct as parameters for the operation.
https://goswagger.io/generate/spec/params.html

**Comment by tstrg** [comment]
Is there an example how to generate example values from the code?

**Comment by casualjim** [comment]
I don't think that is supported at the moment

**Comment by tstrg** [comment]
Thank you for the answer.

**Comment by maerd7** [comment]
@casualjim   i have a question in readme example ,can you help ? 
https://stackoverflow.com/questions/61998661/how-to-construct-a-struct-or-a-map-dynamically-from-a-preset-openapi-schema-in-g

**Comment by DougTea** [comment]
> only when it's used in a discriminator IIRC. There is code in the scan package that treats nullary methods as properties if certain conditions are met.

What is discriminator IIRC?
