### ISSUE TITLE
server generated code does not compile

### ISSUE THREAD

**Issue by MStoykov** [go-swagger/go-swagger#215]
```shell
$ swagger generate server -f test.json
$ cd cmd/test-server
$ go build 
./main.go:39: undefined: configureAPI
$ mv configure_test.go configure.go
$ go build 
$ echo $?
0
```

**Comment by MStoykov** [comment]
after reporting it and trying rereport #216 I found out that the file is name `configure_test.go`  because my api was called 'test' which makes this issue no problem and explains why I only found out about it while reporting ... 

I suppose it will be better if it was names test_configure.go but it isn't a problem at all.

**Comment by Xe** [comment]
where's a copy of the API?

**Comment by casualjim** [comment]
so we should make sure that our file naming doesn't end with _test I suppose?

**Comment by MStoykov** [comment]
@Xe I have since deleted it but the title has to start with the word 'test': 

```json
{
  "consumes": [
    "application/json",
    "application/x-www-form-urlencoded"
  ],
  "info": {
    "title": "Test api",
    "version": "0.1"
  },
  "paths": {
    "/a": {
      "get": {
        "responses": {
          "200": {
            "description": "Success message"
          },
          "500": {
            "description": "Fail message"
          }
        }
      }
    }
  },
  "produces": [
    "application/json"
  ],
  "swagger": "2.0"
}
```
@casualjim It will be a good idea, but given the case in which it happens, it's mostly so people who report bugs and name their test api's 'test api' to not be unpleasantly surprised. If you decide to fix this I propose to not append user generate strings but to prepend them.
In this case this means that the file will be called `test_configuration.go` which will work fine.
