### ISSUE TITLE
generate client library: definition "" contains duplicate properties: [] (or crash when --skip-validation)

### ISSUE THREAD

**Issue by iafilius** [go-swagger/go-swagger#2156]
## Problem statement
Hi,
When converting the swagger.json from:
`https://vdc-download.vmware.com/vmwb-repository/dcr-public/6faa975e-68ee-4c6c-944a-5e9e664b2475/50c61a14-cc14-4adb-b936-b5411ccdd1a5/swagger-3.3.2-dist.json`.
Which is latest 3.3.2 version from `https://code.vmware.com/apis/784/velocloud-sdwan-vco-api`
I get duplicate errors, (and thus no library) as shown below:

`go-swagger/t$ ../cmd/swagger/swagger generate client -f ./swagger-3.3.2-dist.json
2019/12/28 10:48:12 validating spec ./swagger-3.3.2-dist.json
The swagger spec at "./swagger-3.3.2-dist.json" is invalid against swagger specification 2.0. see errors :
- definition "network_segment" contains duplicate properties: [network_segment.data]
- definition "enterprise_insert_enterprise" contains duplicate properties: [#/definitions/enterprise_object.name]
- definition "edge_vnf" contains duplicate properties: [edge_vnf.data]
- definition "metaData" contains duplicate properties: [metaData.data]
- definition "enterprise_object" contains duplicate properties: [enterprise_object.name]
- definition "cloud_security_service_site" contains duplicate properties: [cloud_security_service_site.data]
- definition "netflow_filter" contains duplicate properties: [netflow_filter.data]
- definition "security_vnf_service" contains duplicate properties: [security_vnf_service.data]
- definition "QOS" contains duplicate properties: [QOS.data QOS.refs]
- definition "deviceSettings" contains duplicate properties: [deviceSettings.data deviceSettings.refs]
- definition "security_vnf_license" contains duplicate properties: [security_vnf_license.data]
- definition "managementPlane" contains duplicate properties: [managementPlane.data]
- definition "enterprise_service_network" contains duplicate properties: [enterprise_service_network.data]
- definition "netflow_collector" contains duplicate properties: [netflow_collector.data]
- definition "firewall" contains duplicate properties: [firewall.data]
- definition "WAN" contains duplicate properties: [WAN.data WAN.refs]
- definition "security_vnf_image" contains duplicate properties: [security_vnf_image.data]
- definition "enterprise_proxy_insert_enterprise_proxy_enterprise" contains duplicate properties: [#/definitions/enterprise_object.name]
- definition "dns" contains duplicate properties: [dns.data]
- definition "edgeDeviceSettings" contains duplicate properties: [edgeDeviceSettings.data edgeDeviceSettings.refs]
- definition "imageUpdate" contains duplicate properties: [imageUpdate.data]
- definition "enterprise_update_enterprise" contains duplicate properties: [enterprise_update_enterprise.name]
- definition "monitoring_get_enterprise_edge_vnf_status_result_item" contains duplicate properties: [monitoring_get_enterprise_edge_vnf_status_result_item.data]
- definition "controlPlane" contains duplicate properties: [controlPlane.data]
- definition "operator_user_insert_operator_user" contains duplicate properties: [operator_user_insert_operator_user.password operator_user_insert_operator_user.username]
- definition "gateway_site" contains duplicate properties: [gateway_site.modified gateway_site.timezone gateway_site.shippingCity gateway_site.shippingState gateway_site.id gateway_site.created gateway_site.locale gateway_site.shippingSameAsLocation gateway_site.shippingContactName gateway_site.shippingAddress gateway_site.shippingAddress2 gateway_site.shippingPostalCode gateway_site.shippingCountry]
- definition "enterprise_get_enterprise_network_segments_result_item" contains duplicate properties: [#/definitions/network_segment.data]
- definition "cloud_security_service" contains duplicate properties: [cloud_security_service.data]
- definition "segmentBasedDeviceSettings" contains duplicate properties: [segmentBasedDeviceSettings.data segmentBasedDeviceSettings.refs]
- "metaData" is present in required but not defined as property in definition "configuration_get_identifiable_applications_result"
`

When running go-swagger without the validation, it crashes:
`
go-swagger/t$ ../cmd/swagger/swagger generate client -f ./swagger-3.3.2-dist.json  --skip-validation 
2019/12/29 09:21:30 preprocessing spec with option:  minimal flattening
2019/12/29 09:21:31 building a plan for generation
2019/12/29 09:21:31 planning definitions
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc002592440, 0x33, 0xc002717656, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/model.go:306 +0x1b1b
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc002592440, 0x33, 0xc002717656, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/model.go:146 +0xbf
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc0041a5b88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/support.go:410 +0x609
github.com/go-swagger/go-swagger/generator.(*clientGenerator).Generate(0xc0041a5b88, 0xc520fe, 0x6)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/client.go:125 +0x9a
github.com/go-swagger/go-swagger/generator.GenerateClient(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000372200, 0xcbbd40, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/client.go:117 +0x75c
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).generate(0xc000489380, 0xc000372200, 0x0, 0x0)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:73 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0xe967e0, 0xc000489380, 0x8a3f01, 0x7f1df4157230)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:158 +0x1b2
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).Execute(0xc000489380, 0xc0003d8eb0, 0x0, 0x5, 0xc000489380, 0x1)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:92 +0x37
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000021980, 0xc0000201f0, 0x5, 0x5, 0x0, 0xd43e85, 0x2a, 0xbced20, 0xc0002971a0)
	/home/arjan/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8ce
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/home/arjan/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/swagger.go:145 +0xc2c

`

The maven swagger just runs fine with this swagger, and also on editor.wagger.io i get no errors, and generates the client library. I could not find any suspicious issue with the swagger file itself.
So i think it is an go-swagger issue.
I'm actually really curious which code go-swagger would produce, and compare if it is even more useful then the mvn (maven) version

I hope someone can help me out on this.
Thanks,

Regards

Please remove the sections that don't apply

## Swagger specification
2.0
## Steps to reproduce
See above:

## Environment
Ubuntu 19.10

swagger version: (cloned go-swagger git recently)
go version: go version go1.12.10 linux/amd64
OS:   
Linux

**Comment by fredbi** [comment]
OK, so the cause is the problem is that the same property is defined several times when using `allOf` composition. Besides, these definitions are conflicting, that is the same property name is defined with different types.

The crash is expected when skipping validations.

**Comment by iafilius** [comment]
# feedback /issues/2156

Hello Fredbi,

Thanks for your feedback, i found now what you referred to.
Renamed the duplicated objects in the referred objects, succeeded the validate now, but go-swagger crashed.

Thinking and looking at mv generated library it it looks like i start to understand how it is working now.

let's start from the initial errors, and focus on first one :
"enterprise_service_network" contains duplicate properties: [enterprise_service_network.data]


all errors
```
The swagger spec at "swagger-3.3.2-dist-manualfixes3.json" is invalid against swagger specification 2.0.
See errors below:
- definition "enterprise_service_network" contains duplicate properties: [enterprise_service_network.data]
- definition "firewall" contains duplicate properties: [firewall.data]
- definition "WAN" contains duplicate properties: [WAN.data WAN.refs]
- definition "network_segment" contains duplicate properties: [network_segment.data]
- definition "imageUpdate" contains duplicate properties: [imageUpdate.data]
- definition "operator_user_insert_operator_user" contains duplicate properties: [operator_user_insert_operator_user.username operator_user_insert_operator_user.password]
- definition "enterprise_insert_enterprise" contains duplicate properties: [#/definitions/enterprise_object.name]
- definition "segmentBasedDeviceSettings" contains duplicate properties: [segmentBasedDeviceSettings.data segmentBasedDeviceSettings.refs]
- definition "QOS" contains duplicate properties: [QOS.data QOS.refs]
- definition "controlPlane" contains duplicate properties: [controlPlane.data]
- definition "metaData" contains duplicate properties: [metaData.data]
- definition "deviceSettings" contains duplicate properties: [deviceSettings.data deviceSettings.refs]
- definition "managementPlane" contains duplicate properties: [managementPlane.data]
- definition "netflow_filter" contains duplicate properties: [netflow_filter.data]
- definition "cloud_security_service" contains duplicate properties: [cloud_security_service.data]
- definition "enterprise_get_enterprise_network_segments_result_item" contains duplicate properties: [#/definitions/network_segment.data]
- definition "security_vnf_license" contains duplicate properties: [security_vnf_license.data]
- definition "enterprise_object" contains duplicate properties: [enterprise_object.name]
- definition "edgeDeviceSettings" contains duplicate properties: [edgeDeviceSettings.data edgeDeviceSettings.refs]
- definition "gateway_site" contains duplicate properties: [gateway_site.shippingSameAsLocation gateway_site.shippingContactName gateway_site.shippingAddress2 gateway_site.shippingCountry gateway_site.id gateway_site.created gateway_site.modified gateway_site.timezone gateway_site.locale gateway_site.shippingAddress gateway_site.shippingCity gateway_site.shippingState gateway_site.shippingPostalCode]
- definition "cloud_security_service_site" contains duplicate properties: [cloud_security_service_site.data]
- definition "monitoring_get_enterprise_edge_vnf_status_result_item" contains duplicate properties: [monitoring_get_enterprise_edge_vnf_status_result_item.data]
- definition "edge_vnf" contains duplicate properties: [edge_vnf.data]
- definition "enterprise_proxy_insert_enterprise_proxy_enterprise" contains duplicate properties: [#/definitions/enterprise_object.name]
- definition "dns" contains duplicate properties: [dns.data]
- definition "enterprise_update_enterprise" contains duplicate properties: [enterprise_update_enterprise.name]
- definition "security_vnf_image" contains duplicate properties: [security_vnf_image.data]
- definition "security_vnf_service" contains duplicate properties: [security_vnf_service.data]
- definition "netflow_collector" contains duplicate properties: [netflow_collector.data]
- "metaData" is present in required but not defined as property in definition "configuration_get_identifiable_applications_result"
```


In the swagger file, the definition enterprise_service_network includes basically a template of the general object, and defines some more specific properties as i read it:

```
    "enterprise_service_network": {
      "allOf": [
        {
          "$ref": "#/definitions/enterprise_service"    <<<<<
        },
        {
          "type": "object",
          "properties": {
            "data": {           <<<<<<
              "$ref": "#/definitions/enterprise_service_network_data"
            }
          }
        }
      ]
    },
```

The generic template/parent in swagger:

```
    "enterprise_service": {
      "type": "object",
      "discriminator": "type",
      "properties": {
        "id": {
          "type": "integer"
        },
        "enterpriseObjectId": {
          "type": "integer"
        },
        "configurationId": {
          "type": "integer"
        },
        "moduleId": {
          "type": "integer"
        },
        "ref": {
          "type": "string"
        },
        "data": {                   <<<<<<
          "type": "object"
        },
        "version": {
          "type": "string"
        },
        "object": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "logicalId": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
```


And the more specific to specify the more specific data:
```
    "enterprise_service_network_data": {
      "type": "object",
      "properties": {
        "zone": {
          "type": "string"
        },
        "spaces": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "cidrIp": {
                "type": "string"
              },
              "cidrPrefix": {
                "type": "integer"
              },
              "maxVlans": {
                "type": "integer"
              },
              "mode": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "branchCidrPrefix": {
                "type": "integer"
              },
              "guest": {
                "type": "boolean"
              },
              "vlans": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "vlanId": {
                      "type": "integer"
                    },
                    "advertise": {
                      "type": "boolean"
                    },
                    "cost": {
                      "type": "integer"
                    },
                    "staticReserved": {
                      "type": "integer"
                    },
                    "dhcp": {
                      "type": "object",
                      "properties": {
                        "enabled": {
                          "type": "boolean"
                        },
                        "leaseTimeSeconds": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
```



The mvn swagger 2.4.10 genererates the general (template/parent) object:

```
type EnterpriseService struct {
        Id int32 `json:"id,omitempty"`
        EnterpriseObjectId int32 `json:"enterpriseObjectId,omitempty"`
        ConfigurationId int32 `json:"configurationId,omitempty"`
        ModuleId int32 `json:"moduleId,omitempty"`
        Ref string `json:"ref,omitempty"`
        Data *interface{} `json:"data,omitempty"`       <<<<<<<<
        Version string `json:"version,omitempty"`
        Object string `json:"object,omitempty"`
        Name string `json:"name,omitempty"`
        Type_ string `json:"type"`
        LogicalId string `json:"logicalId,omitempty"`
}
```

The derived enterprise services network:
```
type EnterpriseServiceNetwork struct {
        Id int32 `json:"id,omitempty"`
        EnterpriseObjectId int32 `json:"enterpriseObjectId,omitempty"`
        ConfigurationId int32 `json:"configurationId,omitempty"`
        ModuleId int32 `json:"moduleId,omitempty"`
        Ref string `json:"ref,omitempty"`
        Data *EnterpriseServiceNetworkData `json:"data,omitempty"`      <<<<<
        Version string `json:"version,omitempty"`
        Object string `json:"object,omitempty"`
        Name string `json:"name,omitempty"`
        Type_ string `json:"type"`
        LogicalId string `json:"logicalId,omitempty"`
}
```



The Data *interface{}  (in EnterpriseService) may point to a data type struct as below (or any other Enterprise Service data object)
```
type EnterpriseServiceNetworkData struct {
        Zone string `json:"zone,omitempty"`
        Spaces []EnterpriseServiceNetworkDataSpaces `json:"spaces,omitempty"`
}
```


For example another Enterprise Service to demo the template/inheritance:
```
    "dns": {
      "allOf": [
        {
          "$ref": "#/definitions/enterprise_service"
        },
        {
          "type": "object",
          "properties": {
            "data": {
              "$ref": "#/definitions/dns_data"
            }
          }
        }
      ]
    },

```

The inheritted more specific data type:
```
type Dns struct {
        Id int32 `json:"id,omitempty"`
        EnterpriseObjectId int32 `json:"enterpriseObjectId,omitempty"`
        ConfigurationId int32 `json:"configurationId,omitempty"`
        ModuleId int32 `json:"moduleId,omitempty"`
        Ref string `json:"ref,omitempty"`
        Data *DnsData `json:"data,omitempty"`
        Version string `json:"version,omitempty"`
        Object string `json:"object,omitempty"`
        Name string `json:"name,omitempty"`
        Type_ string `json:"type"`
        LogicalId string `json:"logicalId,omitempty"`
}
```

And the actual data type:
```
type DnsData struct {
        Primary string `json:"primary,omitempty"`
        Secondary string `json:"secondary,omitempty"`
        IsPrivate bool `json:"isPrivate,omitempty"`
        Domains []DnsDataDomains `json:"domains,omitempty"`
}
```

I guess the idea behind this to have a more easy (less errors/higher quality)to maintained swagger object, instead multiple seperate loose but near identical objects.

So it looks mvn swagger (and the online editor.swagger.io) is more relaxed on this topic and to implement inheritance instead throwing an error.


As i'm still verry interested in the coded generated by go-swagger i might 'flatten'  the model/swager myself once, but i do not oversee the complete model (it is not mine), i'm not sure i'm able to finish this.
It would be nice, such construction would be possible in go-swagger as well.


Regards,

Arjan

**Comment by casualjim** [comment]
normally I'd expect to see a discriminator field mentioned, that triggers our inheritance.
I do see that the generated code is also faulty because it has got a pointer to an interface{} type

**Comment by iafilius** [comment]
Hello Casualjim,

I'm not sure what you mean with "normally I'd expect to see a discriminator field mentioned, that triggers our inheritance." I guess i will find it somewhere, or perhaps you can point me to it.

The generated go code (by maven swagger 2.4.10) does indeed generate a pointer to structures as opposed to the previous versions, which did just include the structure. 
This is not an error, this is actually a feature, allowing to not send (json marshalling) an empty (not allocated)  structure .
In my case, really like that, as the API(json) we talk to is kinda picky on receiving empty structures and forces us to set all kinds (think of 1000ths lines of useless dummy/config) of dummy data (to prevent 'a disaster'. 

Regards,

Arjan

**Comment by fredbi** [comment]
@casualjim ok I'll investigate the problem with the `*interface{}` you reported.

@iafilius  the validation from swagger UI works because it just expands the structures and takes the latest key in order of appearance. There is no attempt here to make an _actually_ serializable struct.
Inheritance in swagger (not only go-swagger) is carried out by the means of a `discriminator`  field which defines subtypes based on a parent type.

**Comment by iafilius** [comment]
Hi Fredbi ea,

Focussing on the most basic sample, "enterprise_service" template and its more specific dns (enterprise_service_dns)

Started reading at:
[Swagger V2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) and compared it, which looked ok to me.


In the provided swagger (2.0) I see the dicriminator there, and i just gave it another datatype name to make it more readable:

Slightly modified, to make it beter readable:
```
    "enterprise_service": {
      "type": "object",
      "discriminator": "enterprise_service_type",       <<<<<<<<<<<<<<<<<<<<<<<<<<
      "properties": {
        "id": {
          "type": "integer"
        },
        "enterpriseObjectId": {
          "type": "integer"
        },
        "configurationId": {
          "type": "integer"
        },
        "moduleId": {
          "type": "integer"
        },
        "ref": {
          "type": "string"
        },
        "data": {
          "type": "object"                    <<<<<<<<duplicate>>>>>>>>
        },
        "version": {
          "type": "string"
        },
        "object": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "enterprise_service_type": {              <<<<<<<<<<<<<<<<<<<<<<<
          "type": "string"
        },
        "logicalId": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "enterprise_service_type"                 <<<<<<<<<<<<<<<<<<<<<<<<<
      ]
    },

    "enterprise_service_dns": {
      "allOf": [
        {
          "$ref": "#/definitions/enterprise_service"
        },
        {
          "type": "object",
          "properties": {
            "data": {                            <<<<<duplicate>>>>>
              "$ref": "#/definitions/dns_data"
            }
          }
        }
      ]
    },
```



Orignal (maybe confusing by using reused "type"):
```
    "enterprise_service": {
      "type": "object",
      "discriminator": "type",
      "properties": {
        "id": {
          "type": "integer"
        },
        "enterpriseObjectId": {
          "type": "integer"
        },
        "configurationId": {
          "type": "integer"
        },
        "moduleId": {
          "type": "integer"
        },
        "ref": {
          "type": "string"
        },
        "data": {
          "type": "object"            <<<<<<<<duplicate>>>>>>>>
        },
        "version": {
          "type": "string"
        },
        "object": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "logicalId": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
    "dns": {
      "allOf": [
        {
          "$ref": "#/definitions/enterprise_service"
        },
        {
          "type": "object",
          "properties": {
            "data": {           <<<<<<<<<duplicate>>>>>>>>>
              "$ref": "#/definitions/dns_data"
            }
          }
        }
      ]
    },
```


But still go-swagger validate <swagger> throws an error:
```
- definition "dns" contains duplicate properties: [dns.data]
```

Maybe redefinition is just not allowed, even using a schema with right synatax. (and it works by accident in swagger UI??) 

Is the right way to solve this to remove the "data" from the "enterprise_service" parent/schema, and make sure it's not used anywhere (as the generated datatyepe would be incomplete without "data")

Or what should be the right way

Thanks in advance,


Arjan

**Comment by fredbi** [comment]
Your base type (the one with discriminator) should only specify common attributes to be inherited. In this case, the `data` field should be defined by each subtype inheriting from this base type, with the adequate type for `data`.

**Comment by iafilius** [comment]
Hi Fredbi, thanks for your feedback

based on that processed all errors by hand: 
-removed the different but duplicate types (data) from base type.
-removed all dpulicates from derived type , which was actually a type match with base type.

Most likely a few more things to do, as the basetype was used in generic definitions (which do not contain the data now), which i should define a new dereived object for.
Good enough for a test i thought, validate succeeds, but later on a crash follows.



```
 ../cmd/swagger/swagger generate client -f ./swagger-3.3.2-dist-manualfixes5.json  -A "goswagger_veolcoud3.3.2_clientlib-manualfixes5"
2019/12/31 13:37:43 validating spec ./swagger-3.3.2-dist-manualfixes5.json
2019/12/31 13:38:17 preprocessing spec with option:  minimal flattening
2019/12/31 13:38:18 building a plan for generation
2019/12/31 13:38:19 planning definitions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3 pc=0xaebf24]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.shallowValidationLookup(0x1000100000000, 0x100, 0xc003cab4e0, 0xd, 0x0, 0x0, 0x0, 0x0, 0xd087ec, 0x6, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/model.go:199 +0x2e4
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc0150448a0, 0x11, 0xc000bb3386, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/model.go:158 +0x17d
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc0058f3b88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/support.go:410 +0x609
github.com/go-swagger/go-swagger/generator.(*clientGenerator).Generate(0xc0058f3b88, 0xc520fe, 0x6)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/client.go:125 +0x9a
github.com/go-swagger/go-swagger/generator.GenerateClient(0x7ffc7ff55164, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000e7200, 0xe659bb, ...)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/generator/client.go:117 +0x75c
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).generate(0xc000205200, 0xc0000e7200, 0x0, 0x0)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:73 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0xe967e0, 0xc000205200, 0x8a3f01, 0x7fe55ca3cb40)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:158 +0x1b2
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).Execute(0xc000205200, 0xc00006b140, 0x0, 0x6, 0xc000205200, 0x1)
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:92 +0x37
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00006b0e0, 0xc000020080, 0x6, 0x6, 0x0, 0xd43e85, 0x2a, 0xbced20, 0xc0004c4db0)
	/home/arjan/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8ce
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/home/arjan/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/home/arjan/work/velocloud/git/go-swagger/go-swagger/cmd/swagger/swagger.go:145 +0xc2c
```



i'll see if loading it into a debugger makes sense to me.

i'd put the modified swagger on:
[modified swagger](https://iafilius.home.xs4all.nl/swagger-3.3.2-dist-manualfixes5.json)
in case some want to have a look.

Regards,

Arjan

**Comment by iafilius** [comment]
Hi all, i was today able to make a workaround for the crashes I observed after removing the duplicates in the swagger source.

Added a few testcases/(if statement)  to prevent working with structures pointing to nil at 2 locations.
Most likely it is better to find and solve the root cause (either swagger definition, or go-swagger), but for me _now_ this is good enough, library is generated and i can have a look at it.

The diff between master and my workarounds:
```
diff --git a/generator/model.go b/generator/model.go
index 9b6bd198..88a40dc0 100644
--- a/generator/model.go
+++ b/generator/model.go
@@ -196,11 +196,15 @@ func shallowValidationLookup(sch GenSchema) bool {
        if sch.IsTuple && (sch.AdditionalItems != nil && (sch.AdditionalItems.HasValidations || sch.AdditionalItems.Required)) {
                return true
        }
-       if sch.HasAdditionalProperties && (sch.AdditionalProperties.IsInterface || sch.AdditionalProperties.IsStream) {
+
+       if sch.HasAdditionalProperties && (sch.AdditionalProperties == nil) {
+               log.Printf("WARNING workaround for nil ptr -- sch.HasAdditionalProperties = true && sch.AdditionalProperties == nil), This schould not happen, and will crash, perhaps an empty propery container somewhere??")
+       }
+       if sch.HasAdditionalProperties && (sch.AdditionalProperties != nil) && (sch.AdditionalProperties.IsInterface || sch.AdditionalProperties.IsStream) {
                return false
        }
 
-       if sch.HasAdditionalProperties && (sch.AdditionalProperties.HasValidations || sch.AdditionalProperties.Required || sch.AdditionalProperties.IsAliased && !(sch.AdditionalProperties.IsInterface || sch.AdditionalProperties.IsStream)) {
+       if sch.HasAdditionalProperties && (sch.AdditionalProperties != nil) && (sch.AdditionalProperties.HasValidations || sch.AdditionalProperties.Required || sch.AdditionalProperties.IsAliased && !(sch.AdditionalProperties.IsInterface || sch.AdditionalProperties.IsStream)) {
                return true
        }
 
@@ -242,6 +246,7 @@ func makeGenDefinitionHierarchy(name, pkg, container string, schema spec.Schema,
                IncludeModel:               opts.IncludeModel,
                StrictAdditionalProperties: opts.StrictAdditionalProperties,
        }
+
        if err := pg.makeGenSchema(); err != nil {
                return nil, fmt.Errorf("could not generate schema for %s: %v", name, err)
        }
@@ -296,6 +301,7 @@ func makeGenDefinitionHierarchy(name, pkg, container string, schema spec.Schema,
                                        continue
                                }
                                ref = spec.Ref{}
+
                                if rsch != nil && rsch.Discriminator != "" {
                                        gs, err := makeGenDefinitionHierarchy(strings.TrimPrefix(ss.Ref.String(), "#/definitions/"), pkg, pg.GenSchema.Name, *rsch, specDoc, opts)
                                        if err != nil {
@@ -303,17 +309,21 @@ func makeGenDefinitionHierarchy(name, pkg, container string, schema spec.Schema,
                                        }
                                        gs.GenSchema.IsBaseType = true
                                        gs.GenSchema.IsExported = true
-                                       pg.GenSchema.AllOf[i] = gs.GenSchema
-                                       schPtr := &(pg.GenSchema.AllOf[i])
-                                       if schPtr.AdditionalItems != nil {
-                                               schPtr.AdditionalItems.IsBaseType = true
-                                       }
-                                       if schPtr.AdditionalProperties != nil {
-                                               schPtr.AdditionalProperties.IsBaseType = true
-                                       }
-                                       for j := range schPtr.Properties {
-                                               schPtr.Properties[j].IsBaseType = true
-                                               knownProperties[schPtr.Properties[j].Name] = struct{}{}
+                                       if pg.GenSchema.AllOf != nil {
+                                               pg.GenSchema.AllOf[i] = gs.GenSchema
+                                               schPtr := &(pg.GenSchema.AllOf[i])
+                                               if schPtr.AdditionalItems != nil {
+                                                       schPtr.AdditionalItems.IsBaseType = true
+                                               }
+                                               if schPtr.AdditionalProperties != nil {
+                                                       schPtr.AdditionalProperties.IsBaseType = true
+                                               }
+                                               for j := range schPtr.Properties {
+                                                       schPtr.Properties[j].IsBaseType = true
+                                                       knownProperties[schPtr.Properties[j].Name] = struct{}{}
+                                               }
+                                       } else {
+                                               log.Printf("WARNING WORKAROND for nil ptr,  - Assign gs.Genschema into pg.GenSchema.AllOf[%d] name:%s, pkg:%s pg.GenSchema.AllOf=%p", i, name, pkg, pg.GenSchema.AllOf)
                                        }
                                }
                        }

```
Did not make a merge request for it, as it most likely just masks the root cause, not solves it.

Regards,

Arjan

**Comment by fredbi** [comment]
Interesting use case...

I could spot that the type "id_map_one_to_one" is invalid: it specifies "type: string" and "additionalProperties".  This is definitely a shortcoming of our validator. This eliminates the first cause for panicking.

The other issue is caused by the use of "validation only" allOf's which do not define any properties, just the "required" clause: `get_configuration_result` and `get_configuration_modules_result_item`.
Unfortunately this valid use case for `AllOf`  is not supported by go-swagger a this moment. Removing the `required` validations in these 2 definitions is enough to address the second cause for panicking.

**Comment by iafilius** [comment]
Hi Fredbi, thanks for your help.
Indeed fixing the items you mentioned generated the libary. (the custom added WARNING messages are no longer showed). So i have a library now, but still get an error, i guess beyond the scope of this "issue".
Current compile error is:
```
go-swagger-velocloud_demo$ go build
# my-proj.com/go-swagger-velocloud-sdk-raw/client/configuration
/home/arjan/go/src/my-proj.com/go-swagger-velocloud-sdk-raw/client/configuration/configuration_update_configuration_module_responses.go:199:17: undefined: ModelsConfigurationModuleBaseType
/home/arjan/go/src/my-proj.com/go-swagger-velocloud-sdk-raw/client/configuration/configuration_update_configuration_module_responses.go:201:18: undefined: UnmarshalModelsConfigurationModuleBaseType
/home/arjan/go/src/my-proj.com/go-swagger-velocloud-sdk-raw/client/configuration/configuration_update_configuration_module_responses.go:284:23: o.Update().Validate undefined (type *models.ConfigurationModuleBaseType 
```
By just disabling the offending code in the generated libary, I  just made my first succesfull api (login) call. Now i need to find out which object holds the raw response header, to read the authentication cookie from (to insert it into a contect for folow-up api call's).
Again this might be out of scope for this "issue" (but help is appreciated)

Regards,

Arjan

**Comment by iafilius** [comment]
quick update: removing the "discriminator" on "configuration_module_base_type" is a quick "solution" to get the base type generated, i now see it was one of my leftovers to create a derived object for it.
removing the discriminator is just a quick hack to get the object generated again. 
and then my demo compiles just fine.

**Comment by fredbi** [comment]
ok. I'll patch the panic issues very soon, but the limitations in our implementation for `allOf` are a hard line to break.

**Comment by iafilius** [comment]
Thanks Fredbi, that will help.

For the allOf implementation issue, most important is knowing how to workaround it, so i can continue.
Thanks.

<issue can be closed>

**Comment by iafilius** [comment]
all clear, thanks
