### ISSUE TITLE
Go swagger does not support plain values in bodies.

### ISSUE THREAD

**Issue by cozmo** [go-swagger/go-swagger#217]
The following `swagger.yml` creates invalid server code when using `swagger generate server`. From what I can tell this is a valid spec according to the swagger spec and tested using both the online swagger editor/viewer as well as the provided go-swagger `validate` command. 

```yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'string-body-api'
paths:
  /echo:
    post:
      summary: Post a string, get the same string back.
      parameters:
        - name: body
          in: body
          description: this argument is a string
          schema:
            type: string
      responses:
        '200':
          description: this return value is a string
          schema:
            type: string
```
When running the generated code (no changes) the following error occurs:
```
$ go run cmd/string-body-server/*.go
# ./restapi/operations
restapi/operations/post_echo_parameters.go:40: body.Validate undefined (type string has no field or method Validate)
```

Looking at that file the error becomes apparent

```go
var body string
if err := route.Consumer.Consume(r.Body, &body); err != nil {
  res = append(res, errors.NewParseError("body", "body", "", err))
} else {
  if err := body.Validate(route.Formats); err != nil { // <- Calling validate without defining it
    res = append(res, err)
  }

  if len(res) == 0 {
    o.Body = &body
  }
}
```

Not sure what the best fix is here. We could define a custom type and add a Validate method, but that may make it painful to deal with non string types being passed around. Alternatively we could possibly turn off validation for plain types like strings and numbers. 

_Note that the above example uses `string`, but `number` and `boolean` have the same issue._

**Comment by casualjim** [comment]
fwiw if this is a for a JSON API then you shouldn't send or receive primitives. Only [] and {} are valid JSON values.

I'll look into fixing this issue though

**Comment by cozmo** [comment]
@casualjim That's a good point about non array/object values being invalid JSON. I think it's reasonable to disallow those as long as you think that's inline with the swagger spec (but should probably fail `validate` or something then).

That said, I was playing around some more and this also fails

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'string-body-api'
paths:
  /echo:
    post:
      summary: Post an object
      parameters:
        - name: body
          in: body
          description: this argument is a string
          schema:
            type: object
      responses:
        '200':
          description: All is good
```
(notice the object type in the body param)

```
go run cmd/string-body-server/*.go
# ./restapi/operations
restapi/operations/post_echo_parameters.go:40: body.Validate undefined (type interface {} is interface with no methods)
```

Unless I'm missing something I think this is almost certainly a valid spec.

**Comment by casualjim** [comment]
it's accepted as bug already ;)
I will try to get to it this week. the template should not render the validate method unless it's a named type or a complex object.

The fix will have to go here somewhere: https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/parameter.gotmpl#L162-L183
