### ISSUE TITLE
how can i declare a byte arrary as hex string 

### ISSUE THREAD

**Issue by hunjixin** [go-swagger/go-swagger#2170]
swagger generator use number array as byte array but i want to use hex string replaced ,and what can i do to solve?

**Comment by fredbi** [comment]
@hunjixin could you tell us which swagger type you are using?

I am guessing you are talking about
```yaml
type string
format byte
```
which is mapped with `go-openapi/strfmt.Base64` type. This one is unmarshalled as a base64-decoded string (not `[]byte`)

Number arrays are mapped as `[]float64` by default.
Formatted numbers could also form arrays:
```
type: array
items:
  type: number
  format: int8
```
would render as `[]int8`

In either case, we do not provide hexadecimal string rendering. You could use:
```go
fmt.Printf("%x", myField.String())
```
