### ISSUE TITLE
Client generation using definition x-go-type in Body

### ISSUE THREAD

**Issue by boubech** [go-swagger/go-swagger#2174]
## Problem statement
When I generate client including a definition with x-go-type in Body, the code doesn't compile at 
https://github.com/kathra-project/kathra-resourcemanager-client-go/blob/238c2673ed03f0a60b148daf0abd592980483fdc/client/users/add_user_parameters.go#L129
The message : cannot convert nil to type models.User

Because structs generated for parameters contain body properties as value, not a pointer.
https://github.com/kathra-project/kathra-resourcemanager-client-go/blob/238c2673ed03f0a60b148daf0abd592980483fdc/client/users/add_user_parameters.go#L70

## Swagger specification
Specs for client : https://gitlab.com/kathra/specifications/raw/feature/catalogManager/Services/catalogmanager/swagger.yaml
Specs for model : https://gitlab.com/kathra/specifications/raw/feature/catalogManager/Services/core/swagger.yaml

## Environment
swagger version: 0.21.0
go version: 1.13.3
OS: Ubuntu 19.06

**Comment by fredbi** [comment]
@boubech it is very difficult to reproduce your issue given the fair amount of cross dependencies with your repos. A minimal repro would be welcome to pinpoint the problem.

Further, you provided links on specs which are probably updated by now, so I cannot see any reference the `User` package...

My guess is that providing a package alias which precisely matches the name of the struct `User` is causing some conflict.

I am currently working on improving our package alias name mangling to avoid such conflicts.

**Comment by boubech** [comment]
Thank you for your reply.

I found the simpliest use case generating this issue.
If the object's definition doesn't contains any property, the struct generated for the client use a value variable instead of pointer.
```
swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      parameters:
        - name: pet
          in: body
          description: Object to be created
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        "201":
          description: Null response
definitions:
  Pet:
    type: "object"
```

Regards,

**Comment by fredbi** [comment]
@boubech ok this sample spec leads us to the situation described in #2081 
I provided a work around for this. I am not sure this was your initial problem, though.

**Comment by boubech** [comment]
For my case, I not found a workaround.

**Comment by fredbi** [comment]
@boubech

I know this is a bit old now. I could eventually find a couple of hours to scan over all open go-swagger bugs.

So #2081  is definitely not related.

I've been able to investigate the same issue thanks to a smaller repro case provided by  @eitanb #2224 
There I provide some ways to get a proper generation.
I think your problem is really the same. You may take a look at my solution and check if this works for you.
