### ISSUE TITLE
Client exits with "context deadline exceeded" when debugging server

### ISSUE THREAD

**Issue by ToJen** [go-swagger/go-swagger#2186]
## Problem statement
I have a go-swagger generated client and server. I put a break point somewhere in my server code and at some point, the client calls an endpoint which will hit that breakpoint. While stepping through the server code, the client closes and returns *context deadline exceeded*. How do I prevent the client from timing out?

## Swagger specification
2.0

## Environment
swagger version: 0.19.0
go version: 1.12.7
OS: darwin/amd64

**Comment by casualjim** [comment]
Set the timeout for the client request in the test to something really large

**Comment by ToJen** [comment]
Hey @casualjim, I already tried that

**Comment by casualjim** [comment]
The server also has configurations around timeouts. So you may also have to adjust those.

**Comment by dolanor** [comment]
I've been bitten by this, because the default request params need to be initialized by a constructor 
```diff
- 	req := &pkg.PostAPIXParams{}
+	req := pkg.NewPostAPIXParams()
```
Otherwise, the request itself has a zero-ed out timeout that will make the request fail. It was kind of bad to debug.
