### ISSUE TITLE
Is there any tag available to add Sample API Call in go-swagger? or can we create custom tags in go-swagger?

### ISSUE THREAD

**Issue by aasikraja** [go-swagger/go-swagger#2191]
## Problem statement

I would like to add Sample API call URL with full basepath and parameters such as content types through annotations as below. 
For example:

paths:
  /pet:
    post:
      description: |
        create new pet.
      Sample API Call:
        url: https://<host>/pet -H "accept: application/json" -d "{ "name" : "xxx" }"

## Swagger specification
2.0

## Environment
swagger version: 2.0 OpenAPI Spec  
go version: 1.12.12  
OS:  RHEL

**Comment by fredbi** [comment]
@aasikraja I am assuming your use case is spec generation from source, correct?

**Comment by aasikraja** [comment]
yes I am generating spec by annotating go swagger annotations. I want to know how to add sample api call through annotations. Is there any existing tag available for that or can we create any custom tags ?

**Comment by fredbi** [comment]
As far as I remember, there is an `Extensions` annotation to add `x-...` extended tags from your code.

**Comment by fredbi** [comment]
Does this example suits your need? https://github.com/go-swagger/go-swagger/blob/c5c6cdaa4093c2cec800e495cd607a2194c6af5e/fixtures/goparsing/classification/doc.go#L42

**Comment by aasikraja** [comment]
@fredbi Thank u for reply. It solved the issue.
