### ISSUE TITLE
Update README with a new section about OpenAPI 3.0 to avoid more questions 

### ISSUE THREAD

**Issue by timbunce** [go-swagger/go-swagger#2192]
## Problem statement

It's not easy to find out if the maintainers of this project intend to support OpenAPI 3.0.

That leads to issues like #2180 and #1122, and repeated questions in Slack and elsewhere.

## Proposed Solution

Add a new section to the README that explains the situation (e.g. based on @casualjim's [comment](https://github.com/go-swagger/go-swagger/issues/1122#issuecomment-575968499) on #1122) and offers suggestions for alternative approaches.

**Comment by fredbi** [comment]
Eventually added that #3095
