### ISSUE TITLE
Incompatible naming convention for a path starting with one letter word

### ISSUE THREAD

**Issue by dplusic** [go-swagger/go-swagger#2213]
## Problem statement
For a path like `/a-foo` (starts with one letter word), I got incompatible naming convention.
* expected (0.19.0, 0.18.0 or maybe earlier)
  * file `restapi/operations/get_a_foo.go` generated
  * struct `GetAFoo` generated
* actual (from 0.20.0)
  * file `restapi/operations/geta_foo.go` generated
  * struct `GetaFoo` generated

## Swagger specification
```yaml
swagger: "2.0"
info:
  version: "1"
  title: a-foo
paths:
  /a-foo:
    get:
      responses:
        200:
          description: a-foo
```

## Steps to reproduce
`$ swagger generate server -f ./swagger.yaml`

## Environment
swagger version: 0.20.0 or later
go version: 1.13.7
OS: Windows 10 Build 19551.1005

**Comment by fredbi** [comment]
That one is one my plate. I addressed several shortcomings with naming conventions with latest release and that one has probably slipped through.

**Comment by fredbi** [comment]
mmh. On second thought, this looks like it has been here for quite a while and is not related to my recent refactoring.
The funny behavior actually comes from `swag.ToGoName`... I can work around this in goswagger, though
