### ISSUE TITLE
Code generation is broken due to stricter template syntax checks in Go 1.14

### ISSUE THREAD

**Issue by misha-ridge** [go-swagger/go-swagger#2215]
## Problem statement

`schematype.gotmpl` and probably other templates are no longer syntactically valid under Go 1.14.

## Swagger specification

https://petstore.swagger.io/v2/swagger.json

## Steps to reproduce

1. Build `go-swagger` using Go 1.14rc1
2. `swagger generate client -f https://petstore.swagger.io/v2/swagger.json`

You'll get:

```
2020/02/05 23:10:43 creating generated file "api_response.go" in "models" as definition
failed rendering template data for definition: template execution failed for template definition: template: schematype:2:18: executing "schemaType" at <(len .AllOf) gt 0>: can't give argument to non-function len .AllOf
```

## Environment
swagger version: x.x.x  
go version: 1.14rc1
OS:   

See https://github.com/golang/go/issues/37066

**Comment by fredbi** [comment]
It looks like this bug is only present in `schematype.gotmpl`

**Comment by fredbi** [comment]
@misha-ridge thanks for digging that out.
I can't currently test with go1.14rc1, but I provided a tentative fix here #2221 (this is basically a refactoring PR - I took the opportunity to fix this syntax error).

Would you mind giving it a shot with your version?

**Comment by misha-ridge** [comment]
Thanks, it solves the syntax error.

**Comment by fredbi** [comment]
Thanks for this confirmation.

**Comment by aeneasr** [comment]
Would it be possible to release this? :)

**Comment by mjstevens777** [comment]
https://github.com/go-swagger/go-swagger/releases/tag/v0.23.0
From one of the linked issues

**Comment by adamluzsi** [comment]
thank you for fixing this issue!
