### ISSUE TITLE
support not embedding the schema into the server generated code

### ISSUE THREAD

**Issue by MStoykov** [go-swagger/go-swagger#222]
The same as #190 but for the server generated code.

**Comment by casualjim** [comment]
On the server this is done for serving the spec up at /swagger.json 

Are you saying you want to optionally exclude a spec and make sure you deploy one with your generated server?

**Comment by casualjim** [comment]
oops wrong issue number in commit message

**Comment by MStoykov** [comment]
I certainly won't need that feature in my current project. 

It's a good idea and I like it. But it could be optional I suppose. 

Maybe change the behavior in such a way that I could give nil instead of the spec and still have a way to provide whatever else it gets from it.
