### ISSUE TITLE
Failed to load template schemabody

### ISSUE THREAD

**Issue by kenjones-cisco** [go-swagger/go-swagger#2223]
## Problem statement

When attempting to generate server, I'm getting the following error:
```
failed to load template schemabody: template: schemabody:28: illegal number syntax: "-"
```

## Swagger specification

https://gist.github.com/kenjones-cisco/8c7766470ebe67706d672997e7bf0244

## Steps to reproduce

```
swagger generate server --exclude-main -A gcp-svc -a ops -t gen -f tmp/api.yml --flag-strategy=pflag --principal models.User
```

## Environment
swagger version: master
go version: 1.11.13
OS: debian 10 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux

**Comment by danielsmithdevelopment** [comment]
Also getting this error. First time seeing this as build was still working a couple days ago. Can't seem to find what has changed that caused this. Installing with `go get go get -u github.com/go-swagger/go-swagger/cmd/swagger` results in a binary with the problem above when calling swagger generate.

**Comment by casualjim** [comment]
I think it's due to this PR: https://github.com/go-swagger/go-swagger/pull/2221

**Comment by casualjim** [comment]
I created this branch with that PR reverted: https://github.com/go-swagger/go-swagger/tree/revert-2221-refact-model-templates 
Does that sort the issue out?

**Comment by kenjones-cisco** [comment]
Yes, I can confirm, after building a binary from the specified branch, I was able to take the same API spec and same command, and it ran successfully just as it has before.

**Comment by fredbi** [comment]
ok thanks for the feedback. I'll get that sorted out
