### ISSUE TITLE
generated server arguments not working

### ISSUE THREAD

**Issue by redecs** [go-swagger/go-swagger#2227]
I'm new to go-swagger and stumbled into a problem.

## Problem statement

When trying to run a generated server on a specific port, as instructed in the [documentation](https://goswagger.io/generate/server.html#build-a-server), I get the following error:

```
$ go run cmd/account-management-api-server/main.go --port=8000

flag provided but not defined: -port
Usage of /var/folders/vr/wsrcn49x0y989qjh3d23bkk00000gn/T/go-build097543076/b001/exe/main:
  -c string
    	config file
  -v	print version information
exit status 2
```

The generate command I used: `swagger generate server -A account-management-api -f ./spec/v1-flattened.json`

## Steps to reproduce

1. Generate a server
2. Try to run it with command line arguments, like `--port`

## Environment
swagger version: 0.22.0  
go version: 1.13.7
OS:  MacOS

As an workaround, I've started the application on the specific port I wanted using environment variables: `PORT=8000 go run cmd/account-management-api-server/main.go`

Thank you!

**Comment by fredbi** [comment]
That is strange. I've just tried the very same command after a generation with all defaults and it works fine. Perhaps you should provide us with some details about the generation options you did use.

```
go version
go version go1.13.5 linux/amd64
```
```
swagger: current master
OS: linux ubuntu
```
 go run gen3/cmd/fixture-for-issue909-server/main.go --port 1234
2020/02/13 08:40:56 Serving fixture for issue909 at http://127.0.0.1:1234
 ```
or
```
go run gen3/cmd/fixture-for-issue909-server/main.go --port 1234
2020/02/13 08:42:22 Serving fixture for issue909 at http://127.0.0.1:1234
```

**Comment by redecs** [comment]
Thanks @fredbi!
You are right, the flags work as expected and stated by docs.
The problems were caused by an import I missed on our side that was resetting flags.
