### ISSUE TITLE
swagger:type override is not working

### ISSUE THREAD

**Issue by KevinJCross** [go-swagger/go-swagger#2229]
## Problem statement
in our code we have  this:
```
//swagger:type float64
type Decimal{
   D decimal.Decimal
}
```
This causes some interesting problems 
1. It does not override the struct type to float64 as the documentation suggests

2. it creates the following self referencing type. This causes an infinite loop in the swagger diff which is sub optimal.
```
"Decimal": {
      "type": "object",
      "properties": {
        "D": {
          "$ref": "#/definitions/Decimal"
        }
      },
      "x-go-package": "github.com/SomeGit/package"
    },
```
Having a look at the code myself I go a bit lost as to where to implement it it seems the rxType exists but no rxTypeFmt and its not put into the parser.
Either can someone have a crack at fixing it or point me in the right directions to create a fix to override the struct parsing.

Upon further investigation it seems this commit has been forgotten/merged out ... 
No doubt because it did not have any tests.
https://github.com/go-swagger/go-swagger/commit/ca670fa045fe0e494f21aab278482f994ee80905

Ive had a crack at it myself and got muddled up with the old +1.11 code and the codescan package.  Also where do I write the tests?

**Comment by risentveber** [comment]
the same problem - `swagger:type` - is just ignored

**Comment by ondi** [comment]
up!
swagger:type not working

**Comment by jamesog** [comment]
I think I've found where this is failing.

The `swagger:type` feature added in #1183 added this code: https://github.com/go-swagger/go-swagger/blob/b554e5362c5325728630ab94bb877bea64298433/codescan/schema.go#L325-L328

which is in `func (s *schemaBuilder) buildFromType(tpe types.Type, tgt swaggerTypable) error`.

Given code like this:

```go
// swagger:type string
type NullString struct {
    // swagger:ignore
    sql.NullString
}
```

the `types` package sees this as a struct and not a named type (which makes sense, given [the docs](https://github.com/golang/example/tree/master/gotypes#named-types)), so the added code is never matched because it only happens in the branch for `*types.Named`.

It's not obvious to me how to fix this and there are no unit tests for this feature so I can't be sure I won't break anything by attempting to fix it.

**Comment by matancev** [comment]
> I think I've found where this is failing.
> 
> The `swagger:type` feature added in #1183 added this code:
> 
> https://github.com/go-swagger/go-swagger/blob/b554e5362c5325728630ab94bb877bea64298433/codescan/schema.go#L325-L328
> 
> which is in `func (s *schemaBuilder) buildFromType(tpe types.Type, tgt swaggerTypable) error`.
> 
> Given code like this:
> 
> ```go
> // swagger:type string
> type NullString struct {
>     // swagger:ignore
>     sql.NullString
> }
> ```
> 
> the `types` package sees this as a struct and not a named type (which makes sense, given [the docs](https://github.com/golang/example/tree/master/gotypes#named-types)), so the added code is never matched because it only happens in the branch for `*types.Named`.
> 
> It's not obvious to me how to fix this and there are no unit tests for this feature so I can't be sure I won't break anything by attempting to fix it.

Faced the same issue.

Tried to add the same `typeName` check at `*types.Struct` branch and this resolved the problem.
Also I have noticed some inaccuracies in go-swagger docs. According to [swagger:type docs page](https://github.com/go-swagger/go-swagger/blob/8831a62b593f7994d887ac61bc9e10bbaacc51a9/docs/use/spec/type.md) supported types are:
- string (this includes dates and files)
- number
- integer
- boolean
- array
- object

But actually, `swaggerSchemaForType` works with golang types. Moreover returned error is ignored and we never know if swagger annotations are malformed.

**Comment by PaulForgey-Discovery** [comment]
Are there any plans or updates on this issue?

**Comment by rr-justin-hanselman** [comment]
Adding this here as a hack fix for now.

Apparently if you use swagger:strfmt, this will stop the scan of the struct.  It's not perfect, but it saves my documentation for now until this gets fixed.

```
type MyStruct struct {
    // swagger:strfmt decimal
   Amount decimal.Decimal

}
```

**Comment by glahdou** [comment]
Also facing that issue. Wondering what is the difference between having the type in a struct versus simply doing type aliasing / type definition ?

Trying to use @rr-justin-hanselman 's workaround.

This made me appreciate a lot how open source projects evolve.

**Comment by jt-voyager** [comment]
I'm also hitting this and @rr-justin-hanselman's workaround is not working on string types.
