### ISSUE TITLE
Add generic support

### ISSUE THREAD

**Issue by buffge** [go-swagger/go-swagger#2231]
My web response type is
```go
type Resp struct {
    Code int
    Msg  string
    Data interface{}
}
```
My Api comment is
```go
// @Success 200 {object} Resp
```
l hope do like this set Data actual type
```go
// @Success 200 {object} Resp<Data:UserDetail>
```

**Comment by casualjim** [comment]
I think this is for the wrong project because we don't have annotations that start with an `@`.
