### ISSUE TITLE
Add middleware router or a kind of path matching

### ISSUE THREAD

**Issue by ilyakaznacheev** [go-swagger/go-swagger#2234]
## Problem statement

The generated server is nice, but internal routing is hidden. Without any routing or way to interact with a path, it becomes painful to deal with middleware which should apply to only one path or a group of paths by a prefix.

It would be really great to add the out-of-the-box feature to add HTTP middleware to certain routes or groups, which will make it much easier for everyday use.

It also would be nice to make it available not inside `configure_***.go`, but also outside the package using global methods `restapi.Server`.

**Comment by ilyakaznacheev** [comment]
It would be even more useful if it can use swagger tags as an alternative to the path.

**Comment by fredbi** [comment]
closed with #2236
