### ISSUE TITLE
Client generation failed: panic: object has no key "Map"

### ISSUE THREAD

**Issue by e88z4** [go-swagger/go-swagger#2237]
## Problem statement
Client generation failed with error message panic: object has no key "Map"

## Swagger specification
https://gist.github.com/e88z4/41e2667f7fe6072671a32150c5190662

## Steps to reproduce
swagger generate client -f ./swagger.json --skip-validation

## Environment
swagger version: 
 version: v0.22.0
commit: 5773cbe63c3f459b23ed73ad8b482389ddf46cb4
go version: 1.13.8
OS: linux/amd64

Error message:
020/02/28 00:15:49 preprocessing spec with option:  minimal flattening
2020/02/28 00:15:49 building a plan for generation
2020/02/28 00:15:49 generation target ./
2020/02/28 00:15:49 planning definitions
panic: object has no key "Map"

goroutine 1 [running]:
github.com/go-openapi/spec.ResolveRef(0xca7d00, 0xc0006d2800, 0xc000bc8918, 0x3, 0x3, 0xc0019e82b0)
	/go/pkg/mod/github.com/go-openapi/spec@v0.19.6/expander.go:55 +0x381
github.com/go-swagger/go-swagger/generator.(*typeResolver).resolveSchemaRef(0xc00190eff0, 0xc000bc8900, 0xd45c00, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/types.go:234 +0x190
github.com/go-swagger/go-swagger/generator.(*typeResolver).ResolveSchema(0xc00190eff0, 0xc000bc8900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/types.go:630 +0x1bc
github.com/go-swagger/go-swagger/generator.(*typeResolver).resolveObject(0xc00190eff0, 0xc0005718a8, 0xd46000, 0x0, 0x0, 0x0, 0xc001ab2800, 0x17, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/types.go:453 +0x480
github.com/go-swagger/go-swagger/generator.(*typeResolver).ResolveSchema(0xc00190eff0, 0xc0005718a8, 0x0, 0x0, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/types.go:697 +0xc0d
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc000571800, 0xc000571800, 0xc0019eb598)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:1877 +0x1371
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc0000b3d70, 0x21, 0xc00188c2f6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:231 +0x269
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc0000b3d70, 0x21, 0xc00188c2f6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:132 +0xbf
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc0019efac8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:231 +0x61f
github.com/go-swagger/go-swagger/generator.(*clientGenerator).Generate(0xc0019efac8, 0xc7e3ee, 0x6)
	/go/src/github.com/go-swagger/go-swagger/generator/client.go:77 +0x80
github.com/go-swagger/go-swagger/generator.GenerateClient(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003c6240, 0xc0003c6240, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/client.go:69 +0x621
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).generate(0xc0001ced00, 0xc0003c6240, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:67 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0xed29c0, 0xc0001ced00, 0x8b6901, 0x7f43fda63ca8)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:175 +0x22a
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).Execute(0xc0001ced00, 0xc0000bfe50, 0x0, 0x5, 0xc0001ced00, 0x1)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:86 +0x37
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000315c0, 0xc0000ba130, 0x5, 0x5, 0x0, 0xd8285e, 0x2a, 0xbf6dc0, 0xc000463cb0)
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8dc
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:145 +0xc2c

**Comment by casualjim** [comment]
That spec is invalid. It uses generic type names, has refs pointing to nowhere; I think it assumes swagger is only a documentation tool

**Comment by e88z4** [comment]
Thank you. Let's close this ticket.
