### ISSUE TITLE
How to get matched route in a middleware ?

### ISSUE THREAD

**Issue by eddycharly** [go-swagger/go-swagger#2238]
Is this possible to retrieve the matched route inside a middleware ?
Something using the request context maybe ?

Thanks.

**Comment by eddycharly** [comment]
Found it, there’s a MarchedRouteFrom in go-openapi. 
Closing.

**Comment by michaelfinkvbb** [comment]
For those who stumble upon this in the future, it is in `github.com/go-openapi/runtime/middleware` and it looks like `func MatchedRouteFrom(req *http.Request) *MatchedRoute`. It contains, for example `PathPattern`, which has the pattern matched for the path, which is what I was looking for.
