### ISSUE TITLE
Please make a new release for Go 1.14

### ISSUE THREAD

**Issue by johanbrandhorst** [go-swagger/go-swagger#2239]
## Problem statement

https://github.com/go-swagger/go-swagger/issues/2215 showed that go-swagger is broken for users of Go 1.14. There has not been a release since this was fixed. Any Go 1.14 users are forced to pin to a commit until a release is made.

Thanks!

**Comment by casualjim** [comment]
https://github.com/go-swagger/go-swagger/releases/tag/v0.23.0
