### ISSUE TITLE
Example for generating spec with securityDefinitions?

### ISSUE THREAD

**Issue by spiffyjr** [go-swagger/go-swagger#225]
I'm failing to find any examples of how to generate the following:

```json
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
```

Any help would be appreciated, thanks!

**Comment by casualjim** [comment]
you can start with an input file. 
I think there is no parser support for the security schemes yet in the comment parser. But you can start with a partial swagger file and then have it merge the discovered (from code) data into the final swagger document.

**Comment by spiffyjr** [comment]
Okay, thanks.
