### ISSUE TITLE
Redirecting links in the docs

### ISSUE THREAD

**Issue by carriecarrieee** [go-swagger/go-swagger#2253]
I understand that there is support for deprecating endpoints, but what if I want to deprecate then redirect, or add another url tag for a different endpoint?  Is there a way to do that?

**Comment by casualjim** [comment]
add a 3xx response and set the location header

**Comment by carriecarrieee** [comment]
Thanks for the quick reply! Do you also happen to have an example for how to add it?  My code is similar to this: https://goswagger.io/use/spec/route.html#example

**Comment by casualjim** [comment]
You would do this here in the response: https://goswagger.io/use/spec/response.html

```go
// swagger:response deprecatedError
type DeprecatedResponse struct {
  // in: header
  Location string 
  // ...
}
```

then for https://goswagger.io/use/spec/route.html

```go
// ServeAPI serves the API for this record store
func ServeAPI(host, basePath string, schemes []string) error {

    // swagger:route GET /pets pets users listPets
    //
    // Lists pets filtered by some parameters.
    //
    // This will show all available pets by default.
    // You can get the pets that are out of stock
    //
    //     Consumes:
    //     - application/json
    //     - application/x-protobuf
    //
    //     Produces:
    //     - application/json
    //     - application/x-protobuf
    //
    //     Schemes: http, https, ws, wss
    //
    //     Deprecated: true
    //
    //     Security:
    //       api_key:
    //       oauth: read, write
    //
    //     Responses:
    //       default: genericError
    //       200: someResponse
    //       301: deprecatedResponse
    //       422: validationError
    mountItem("GET", basePath+"/pets", nil)
}
```

**Comment by carriecarrieee** [comment]
Thanks! This is very helpful as I am super new at this.  Can you tell me where  I would set the value of Location?  Let's say I want to redirect to "www.google.com".  Do I set this in the route?

**Comment by casualjim** [comment]
In this case you would set it in the code that serves that endpoint. If your intent is to just use this for documentation purposes then I wouldn't know how to do that.

```go
func handler(rw http.ResponseWriter, req *http.Request) {
  http.Redirect(rw, req, "https://www.google.com", http.StatusPermanentRedirect)
}
```

```go
mountItem("GET", basePath+"/pets", http.HandlerFunc(handler))
```

**Comment by carriecarrieee** [comment]
Thanks so much!
