### ISSUE TITLE
How can I get requester client IP in my controller ?

### ISSUE THREAD

**Issue by amackiewicz** [go-swagger/go-swagger#2260]
## Problem statement
I need to utilise requester client real IP in my controllers. Normally its accessible by net/http.Request.RemoteAddr. How can I get that value with code generated by go-swagger ? Of course I really don't want to edit files whom will be replaced after next code generation

**Comment by casualjim** [comment]
On the struct that captures the input there is the .HTTPRequest property. The information lives in there.
```go
func SomeHandler(params *SomeHandlerParams) middleware.Responder {
   remoteIP := GetIP(params.HTTPRequest)
   ...
}

// GetIP gets a requests IP address by reading off the forwarded-for
// header (for proxies) and falls back to use the remote address.
func GetIP(r *http.Request) string {
	forwarded := r.Header.Get("X-FORWARDED-FOR")
	if forwarded != "" {
		return forwarded
	}
	return r.RemoteAddr
}
```

**Comment by amackiewicz** [comment]
@casualjim  thanks 🍻
