### ISSUE TITLE
Generated client is receiving 422 error, but I can't see the body to figure out what is missing

### ISSUE THREAD

**Issue by mdelvecchio-wasabi** [go-swagger/go-swagger#2261]
## Problem statement

My generated client submits a request:

```
		params := operations.NewPostSubmitParams()
		resp, err := clientlient.Operations.PostSubmit (params)
```

I have omitted a required parameter, so resp is nil, and err is non-nil.  But I can't figure out how to see the body of the error, wherein lies the information about which parameter is missing.

When I print the err with "%v", it says:

```
unknown error (status 422): {resp:0xc00064a000}
```

So I know it's a 422.  But I can't get access to the response.  The type of err is *runtime.APIError, which has a known structure.  But when I walk the properties of that struct and print their values and types, I see:

```
OperationName:  unknown error (string)
     Response:  {0xc0001463f0} (client.response)
         Code:  422 (int)
```

The Response, which I need to see, is of a non-public type (client.response), and I cannot figure out how to display the details.

Please remove the sections that don't apply

## Steps to reproduce

Use the generated client to submit a request that lacks a required parameter.

## Environment
swagger version: v0.23.0 
go version: go1.11.5
OS:   Ubuntu Linux 16

**Comment by mdelvecchio-wasabi** [comment]
In addition, I can't see it on the server side either.  When I run with DEBUG=1 and SWAGGER_DEBUG=1, I get this:

```
looking up route for POST /cdr/v1/ingest/submit
got a router for POST
found a route for POST /cdr/v1/ingest/submit with 1 parameters
validating content type for "application/json" against [application/json]
responding to POST /cdr/v1/ingest/submit with produces: [application/json]
offers: [application/json]
[POST /cdr/v1/ingest/submit] set response format "application/json" in context
[POST /cdr/v1/ingest/submit] negotiated response format "application/json"
```

I have spent some time trying to get logging middleware to work, but the only example I found that logs after the response is set (https://notes.elmiko.dev/2016/07/11/go-swagger-logging.html) only has access to the response code, and not to the body.

**Comment by mdelvecchio-wasabi** [comment]
Running into another problem that I can't diagnose because of this problem.

Any suggestions on how I can see what is missing?

Thanks.

**Comment by casualjim** [comment]
Run the client with env var `DEBUG=1`

if you want to log response bodies you have to make a response writer that captures the response in a buffer as well as write it out to the original response. Then you can also capture the body along with the status code.

I haven't tested this code but it should show the general idea. For better reuse and avoiding annoying issues, I recommend using https://github.com/felixge/httpsnoop
 
```go
func LogRequests(lg *log.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			statusWritten := int32(-1)
			start := time.Now()
			buf := bytes.NewBuffer(nil)
			w = httpsnoop.Wrap(w, httpsnoop.Hooks{
				WriteHeader: func(headerFunc httpsnoop.WriteHeaderFunc) httpsnoop.WriteHeaderFunc {
					return func(code int) {
						if atomic.CompareAndSwapInt32(&statusWritten, -1, int32(code)) {
							headerFunc(code)
						}

					}
				},
				Write: func(writeFunc httpsnoop.WriteFunc) httpsnoop.WriteFunc {
					return func(b []byte) (int, error) {
						buf.Write(b)
						return writeFunc(b)
					}
				},
			})


			next.ServeHTTP(w, r)
			lg.Printf("request completed in %s method=%s uri=%s status=%d body=%s",
				time.Since(start),
				r.Method,
				r.RequestURI,
				statusWritten,
				buf.Bytes())
		})
	}
}

```

**Comment by mdelvecchio-wasabi** [comment]
As I stated in my follow-up comment, running with DEBUG=1 and SWAGGER_DEBUG=1 produced no useful information, just:

```
looking up route for POST /cdr/v1/ingest/submit
got a router for POST
found a route for POST /cdr/v1/ingest/submit with 1 parameters
validating content type for "application/json" against [application/json]
responding to POST /cdr/v1/ingest/submit with produces: [application/json]
offers: [application/json]
[POST /cdr/v1/ingest/submit] set response format "application/json" in context
[POST /cdr/v1/ingest/submit] negotiated response format "application/json"
```

I will take a look at the code you posted, but it pains me to dig this deep into the server code.

Why can't I just see the error message in the generated client?

Thanks.

**Comment by casualjim** [comment]
The logs you are posting are from the server. 
If you run the client with DEBUG=1 it will print out both the requests and responses with body to the console.

**Comment by mdelvecchio-wasabi** [comment]
I JUST FIGURED THAT OUT AND WAS RACING BACK TO APOLOGIZE!

That's all I needed; thank you for your patience and help.

And sorry for not getting it.

**Comment by mdelvecchio-wasabi** [comment]
PS  It would be nice if the error were exposed to the client Go code.  

In my debugging, I found that the error is of type runtime.APIError, and has this structure:

```
OperationName:  unknown error (string)
     Response:  {0xc0001463f0} (client.response)
         Code:  422 (int)
```

The Response is of type `client.response`, which is not public.  Is this the type defined in github.com/go-openapi/runtime/client/response.go?

Thanks.
