### ISSUE TITLE
client middleware?

### ISSUE THREAD

**Issue by toonsevrin** [go-swagger/go-swagger#2277]
How can we add middleware to the generated client?

**Comment by casualjim** [comment]
Set a different transport:

https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L224

which you can pass in here:

https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todo_list_client.go#L50

**Comment by toonsevrin** [comment]
Awesome, I've added my (retry and logging) middleware to the RoundTripper, which is against the spec but it works perfectly!
