### ISSUE TITLE
Operations import is missing from generated foo_client.go

### ISSUE THREAD

**Issue by keymone** [go-swagger/go-swagger#2278]
## Problem statement

Generated `client/foo_client.go` doesn't contain import for operations package.

## Swagger specification

```yaml
---
swagger: "2.0"
info:
  title: foo api
  version: "1.0.0"
paths:
  /version:
    get:
      responses:
        "200":
          description: foo version
          schema:
            type: string
      summary: foo version
      operationId: showVersion
```

## Steps to reproduce

Put the above yaml into `swagger.yaml` and run

    rm -rf ./pkg/foo_api && \
    mkdir -p ./pkg/foo_api && \
    docker run \
      --rm -it \
      --user "$(id -u):$(id -g)" \
      -e GOPATH=$HOME/go:/go \
      -v $HOME:$HOME \
      -w $(pwd) quay.io/goswagger/swagger \
      generate client -f ./swagger.yaml -t ./pkg/foo_api

Observe go failing to build the package:

```
$ go build ./pkg/foo_api/client/foo_client.go 
go: finding github.com/go-openapi/strfmt v0.19.5
go: finding github.com/go-openapi/runtime v0.19.15
go: finding github.com/go-openapi/runtime/client latest
go: downloading github.com/go-openapi/runtime v0.19.15
go: extracting github.com/go-openapi/runtime v0.19.15
go: downloading github.com/go-openapi/strfmt v0.19.5
go: extracting github.com/go-openapi/strfmt v0.19.5
# command-line-arguments
pkg/foo_api/client/foo_client.go:101:13: undefined: operations
```

## Environment
swagger version: v0.23.0 commit: 3596b40bedd4f06cc918767098568456d2ec2370
go version: go1.12.7 linux/amd64
OS: Ubuntu 16.04.5

**Comment by ToJen** [comment]
Getting something similar here, explained on #2283.

**Comment by fredbi** [comment]
Yeah definitely a bug when there is the trailing "api" string in the  name.

**Comment by fredbi** [comment]
Duplicates #2293, which root causes the issue

**Comment by filinvadim** [comment]
I don't have 'api' name but 'operations' import is still missing. Version 0.30.5
