### ISSUE TITLE
Is there any way swagger.json can be served from the basePath instead of from the server root?

### ISSUE THREAD

**Issue by ajramos** [go-swagger/go-swagger#2284]
## Problem statement
The go-swagger generated server, when launched serves the documentation of the service from /basepath/docs, however in the load page it fetches the swagger.json from the rootPath of the server. Hence when we place the service behind a reverse proxy the api documentation gets unavailable.

For example, when running in local if I go to "http://localhost/service/docs" I can see the documentation GUI loads properly, as the file "http://localhost/swagger.json" is available, however when I deploy this on the server and I go to "http://myserver.com/service/docs" it cannot fetch the file "http://myserver.com/swagger.json" as the reverse proxy is not configured to do so, hence I was wondering whether there is any manner to serve this file from "http://myserver.com/service/swagger.json"

I was looking at the documentation and the FAQs, but I couldn't find anything, or maybe my golang level of understanding doesn't help either.

Thank you very much in advance.

## Environment
swagger version: 0.23.0  
go version: 1.13.4
OS:   macOs - Mojave @ local

**Comment by casualjim** [comment]
You can setup a global middleware on a different path

```go
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return middleware.Spec("/the/basePath", SwaggerJSON, handler)
}
```

**Comment by ajramos** [comment]
Thank you so much for your quick response, I finally added the following snippet for the GUI to point as well the /service/swagger.json

`func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return docMiddleware(handler)
}

func docMiddleware(handler http.Handler) http.Handler {

	basePath := "/service"
	swaggerJson := "swagger.json"
	specURL := fmt.Sprintf("%s/%s", basePath, swaggerJson)

	redocOpts := middleware.RedocOpts{
		BasePath: basePath,
		SpecURL:  specURL,
	}

	return middleware.Redoc(redocOpts, middleware.Spec(basePath, SwaggerJSON, handler))

}`
