### ISSUE TITLE
websocket: response does not implement http.Hijacker

### ISSUE THREAD

**Issue by mtfelian** [go-swagger/go-swagger#2288]
Hello. 

I am trying to create a WS endpoint. Go 1.13.8, swagger 0.22.0

I read this issue: https://github.com/go-swagger/go-swagger/issues/2083 and this: https://github.com/go-swagger/go-swagger/issues/877 but ultimately getting the following error message: `websocket: response does not implement http.Hijacker` from `Upgrade()` call. 

I attached it as a middleware through `setupGlobalMiddleware`. 

Middleware itself is as follows: 
```
package middleware

import (
	"net/http"
	"strings"

	"github.com/gorilla/websocket"
	"github.com/sirupsen/logrus"
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:    1024,
	WriteBufferSize:   1024,
	EnableCompression: true,
}

const wsPrefix = "/ws"

// serveWS handles websocket requests from the peer.
func serveWS(w http.ResponseWriter, r *http.Request) {
	wsConnection, err := upgrader.Upgrade(w, r, nil)
	if err != nil { //  <---------  ERROR IS HERE
		logrus.Errorf(">>>> HTTP middleware -> serveWS -> Upgrade(): %v", err)
		return
	}

	// some code follows
}

// WebSocketServer handles the websocket connection
func WebSocketServer(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case strings.HasPrefix(r.URL.Path, wsPrefix): // websocket path
			serveWS(w, r)
		default:
			next.ServeHTTP(w, r)
		}
	})
}
```

This comes from the following code inside `Upgrade` method: 
```
	h, ok := w.(http.Hijacker)
	if !ok {
		return u.returnError(w, r, http.StatusInternalServerError, "websocket: response does not implement http.Hijacker")
	}
```

Please suggest, how to fix this?

**Comment by mtfelian** [comment]
Sorry, i close this. The problem was in GZIP middleware which fired prior to this middleware and made connection unusable for upgrading.

**Comment by casualjim** [comment]
I use this: https://github.com/felixge/httpsnoop/ to avoid such cases

This is the compress middleware I use, also supports deflate in addition to gzip
https://github.com/casualjim/go-appserver/blob/master/middleware/compress.go#L126
