### ISSUE TITLE
Server generation with --name api produces empty strings

### ISSUE THREAD

**Issue by rokf** [go-swagger/go-swagger#2293]
## Problem statement

Generating a server from a specification with `--name` flag set to `api` results in the name being an empty string in templates. This produces some incorrect/different strings and identifier names.

https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L762

The code where this is implemented ☝️ warns that the name shouldn’t be `api` or `test` (in a comment) but it’s not mentioned anywhere in the documentation or treated as an error.

## Steps to reproduce

Try to generate a server from whatever spec using `--name api` and `--name somethingelse`. Observe the difference in the filenames and the identifiers/strings in the code.

## Environment

go-swagger version: latest master (c1166eb277856e9f1e0ea50d989b12df78e02b18)
OS: macOS Mojave

## Feedback from Slack (goswagger.slack.com)

@fredbi pointed out that an improvement could be made which would make sure that the expression never returns an empty string.

The `test` suffix is removed in the implementation because of the special meaning of files ending with it in Go.

`api` suffix is also trimmed to avoid package name conflicts in the generated code - `api` is used in many places.

The proposed solution was to return `defaultName` in case that the expression produces an empty string.

**Comment by fredbi** [comment]
@rokf I am getting at it now. I realize that the filter on the trailing "API" is no more blocking now, so I am testing this without this filtering. Well the downside of it is just that some generated names stutter, like "fooAPIAPI". But looks ok otherwise.
