### ISSUE TITLE
feat: `swagger mixin -c all`

### ISSUE THREAD

**Issue by alexec** [go-swagger/go-swagger#2297]
We always completely ignore conflicts. Rather than hack around this, it would be good to have an option to ignore any number of conflicts.

**Comment by kop** [comment]
A little hack for those who need this:

```bash
COLLISIONS_COUNT=$( \
  go run github.com/go-swagger/go-swagger/cmd/swagger mixin \
    --quiet \
    --output ./api/openapi/openapi.json \
    ${INPUT_FILES[@]} 2>&1 | awk '{print $NF}' \
)

go run github.com/go-swagger/go-swagger/cmd/swagger mixin \
  -c "${COLLISIONS_COUNT}" \
  --quiet \
  --output ./api/openapi/openapi.json \
  ${INPUT_FILES[@]}
```

**Comment by fredbi** [comment]
Yes that could be a nice addition. Having collision count as an exit code value has always been flaky.
Feel free to push a PR improving the CLI this way (e.g. `--ignore-conflicts` or something of the like)

**Comment by stijndehaes** [comment]
I made a pr for this: https://github.com/go-swagger/go-swagger/pull/2375

**Comment by crenshaw-dev** [comment]
The flag is `--ignore-conflicts`.
