### ISSUE TITLE
Generated Go code fails to transform multiline descriptions

### ISSUE THREAD

**Issue by midoblgsm** [go-swagger/go-swagger#23]
I have a sample description of an API 
```json
{
    "swagger": "2.0",
 ...
                "description": "Checks for VM presence.\n",
                "parameters": [
                    {
                        "name": "vm_cid",
                        "in": "query",
                        "description": "cloud ID of the VM created disk will most likely be attached; \nit could be used to optimize disk placement so that disk is located near the VM\n",
                        "required": true,
                        "type": "string"
  ...
}
```

The generated code fails to compile because the "description" element is transformed to multiple lines where the comment covers just the first line.
Here is the code for parameters.go:
```go
type Params struct {
  // cloud ID of the VM created disk will most likely be attached; 
it could be used to optimize disk placement so that disk is located near the VM
  VMCid string
}
```

It seems that the "\n" in the description is causing this issue and when I removed it the generation went through. I tried to resolve the issue but unfortunately I didn't find the right code to modify. Any hints to help?
/cc @maximilien

**Comment by casualjim** [comment]
it will be fixed when I'm able to merge my branch back in. I'm no longer using // for comments :)

**Comment by casualjim** [comment]
this should be fixed now on master
