### ISSUE TITLE
Required, Non Nil map[string]interface{}

### ISSUE THREAD

**Issue by andrewpmartinez** [go-swagger/go-swagger#2300]
I'm not sure if this a problem or a question...I read through a few discussions on nullable vs required in the issue log. I didn't read them all in-depth, but the ones I did, did not directly state a workaround for my case. Sorry if this is a repeat, I know the topic is trying. 

## Problem statement
It doesn't seem possible to have a `map[string]interface{}` dictionary property be 1) required (i.e. the field is provided in the content body) and 2) the field is validated as a non-nil value.

The spec below makes sure the field `data` is in the content payload, but it doesn't seem to care if it is `null` (for JSON) and maps to Go's `nil`.

## Swagger specification
See the `data` property below.
```
  configCreate:
    type: object
    required:
      - name
      - type
      - data
    properties:
      tags:
        $ref: '#/definitions/tags'
      name:
        type: string
      type:
        type: string
      data:
        type: object
        x-nullable: false
        additionalProperties:
          type: object
```
I tried throwing `x-nullable: false` in which doesn't appear to work. I can always add my own logic, but before I do I want to make sure there is isn't something in-spec that I can do.

## Environment
swagger version: dev, built from master, c1166eb2
go version: 1.14.3
OS:   Windows 10

**Comment by andrewpmartinez** [comment]
Looking through the source it would appear that this is the validation logic that is generated:

```func (m *ConfigCreate) validateData(formats strfmt.Registry) error {

	for k := range m.Data {

		if err := validate.Required("data"+"."+k, "body", m.Data[k]); err != nil {
			return err
		}

		if err := validate.Required("data"+"."+k, "body", m.Data[k]); err != nil {
			return err
		}

	}

	return nil
}```


...which is weird because the two `if` statements are the same check. Secondly, it appears that if any of the property values in the map are the zero value (i.e. a bool property set to false) it causes the required check to fail.

**Comment by andrewpmartinez** [comment]
Changing the definition to `additionalProperties: true` provides an easier situation to deal with (i.e. the validation logic generated does nothing and I can do my own additional validation as a work around)

Example:

```
  configCreate:
    type: object
    description: A config create object
    required:
      - name
      - typeId
      - data
    properties:
      tags:
        $ref: '#/definitions/tags'
      name:
        type: string
      typeId:
        type: string
      data:
        type: object
        x-nullable: false
        additionalProperties: true
```

`x-nullable` still does nothing. 

Work around validation logic to check for a nil `data` property:

```
	if params.Body.Data == nil {
		ctx := middleware.MatchedRouteFrom(r) //where r is a *http.Request
		api.ServeErrorFor(ctx.Operation.ID)(rc.ResponseWriter, rc.Request, errors.Required("data", "body")) //where api is a reference to the generated api type
		return
	}
``

**Comment by andrewpmartinez** [comment]
The same behavior appears in v0.24.0

**Comment by casualjim** [comment]
I think there is a minProperties you can use to this end.
https://swagger.io/docs/specification/data-models/data-types/

**Comment by andrewpmartinez** [comment]
Looking at the go-swagger doc: https://goswagger.io/use/models/schemas.html

It says 

> minProperties, maxProperties are not supported

**Comment by andrewpmartinez** [comment]
Just tried `minProperties` `maxProperties` have no effect.

**Comment by casualjim** [comment]
yeah sorry If forgot it's not implemented
