### ISSUE TITLE
Creating custom urls using UrlBuilder

### ISSUE THREAD

**Issue by aditya520** [go-swagger/go-swagger#2314]
## How can we set custom urls with the paths specified in Swagger spec.

Like I can't use this function generated by go-swagger in another file

```
func (o *LoginUserURL) WithBasePath(bp string) *LoginUserURL {
	o.SetBasePath(bp)
	return o
}
```
because `_basepath` is not exposed
```
type LoginUserURL struct {
	_basePath string
}
```

swagger version: x.x.x  
go version: v0.23.0
OS:   Ubuntu 18.04

**Comment by fredbi** [comment]
@aditya520 it is unclear why you shouldn't be able to use it. What exactly is the problem with building an URL here?

**Comment by aditya520** [comment]
@fredbi Can you show me an example of creating an instance of `LoginUserURL` and creating a url! Thaw would be very helpful!
