### ISSUE TITLE
Wrong generation for required object parameters

### ISSUE THREAD

**Issue by bobrovka** [go-swagger/go-swagger#2330]
I've got the definition:
``` 
  LoginInput:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
```
I'm using it in my paths section like this:
```
  /login:
    post:
      operationId: login
      parameters:
        - in: body
          required: true
          name: body
          schema:
            $ref: '#/definitions/LoginInput'
      responses:
        200:
          description: ''
          schema:
            properties:
              token:
                type: string
        400:
          $ref: '#/responses/GenericError'
        401:
          $ref: '#/responses/GenericError'
        500:
          $ref: '#/responses/GenericError'
```
this produces me the next result in `login_parameters.go`:
```
		var body models.LoginInput
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
```
but the `errors.Required` signature is `Required(name, in string, value interface{}) *Validation` so it's not possible to compile.
Researching this problem I found that this is actual for `github.com/go-openapi/errors` v.0.19.6, while in v.0.19.4 this function declared as `func Required(name, in string) *Validation`

it looks some kind of weird against semver that package breaks compatibility within patching update.

**Comment by casualjim** [comment]
update your dependencies specifically the `github.com/go-openapi/...` ones

**Comment by casualjim** [comment]
You're right I will bump the tags next time to be minor version updates
