### ISSUE TITLE
Flatten changes case on definitions

### ISSUE THREAD

**Issue by rodriguise** [go-swagger/go-swagger#2334]
## Problem statement

When using `swagger flatten` to resolve remote specs into a single output, the resolved type names are changed to lowercase. 

The case should be preserved.

## Swagger specification
2.0

## Steps to reproduce
1. Create a spec (foo.yaml)

```yaml
paths: 
   /bar:
      get:
         responses:
            200:
                 description: OK
                 schema:
                      $ref: "./bar.yaml#/definitions/Bar"
```
2. Create a second spec (bar.yaml)

```yaml
paths: {}

definitions:
   Bar:
      type: object
      properties:
         Baz:
            type: string
```

3. Flatten

swagger flatten \
	-o flat.yaml --format=yaml  foo.yaml

4. Check flat.yaml

```yaml
paths: 
   /bar:
      get:
         responses:
            200:
                 description: OK
                 schema:
                      $ref:: "#/definitions/bar
definitions:
   bar:  <---- why the case change????
      type: object
      properties:
         Baz:
            type: string
``` 

## Environment
swagger version: v0.24.0
go version: 1.14.1
OS:  Ubuntu

**Comment by fredbi** [comment]
@rodriguise  Yes. I can see that the flatten code uses the name mangler `swag.ToJSONName()` to rewrite imported definitions, and this is altering the case. Maybe we shouldn't do that.

**Comment by guobinzhao** [comment]
when the fix can be included in the formal release? thanks @fredbi
