### ISSUE TITLE
Add warning to documentation for swagger:meta

### ISSUE THREAD

**Issue by AymanArif** [go-swagger/go-swagger#2335]
## Problem statement
Empty line between swagger comments and package results in empty `swagger.yaml`

## Steps to reproduce

If there is whitespace line, swagger will generate empty spec.

Example code:

```
// Package classification of Doc API.
//
// Documenting for Doc API
//
//
//
// Schemes: http, https
// BasePath: /
// Version: 0.0.1
//
// Consumes:
// - application/json
//
// Produces:
// - application/json
//
// swagger:meta

package docs
```

Resultant swagger spec:

```
{
  "swagger": "2.0",
  "info": {},
  "paths": {}
}
``` 

## Environment
swagger version: 2.0  
go version: 1.14
OS:  Ubuntu

## Resolution

Add a warning in [swagger:meta](https://goswagger.io/use/spec/meta.html) documentation stating the godoc requirement for swagger comments.

## Reason for change

For new Golang programmers or developers who do not know that Godoc requires there to be no empty line between the comment and type, package, .etc.; there is a need to update documentation [here](https://goswagger.io/use/spec/meta.html).

**Comment by fredbi** [comment]
fixed with #2338 . Thanks @AymanArif
