### ISSUE TITLE
swagger:meta - $ref on description

### ISSUE THREAD

**Issue by lcfumes** [go-swagger/go-swagger#2349]
## Problem statement
To generate description, is possible to use $ref instead of plain text?

## Swagger specification
```
info:
  description:
     $ref: intro.md
```
## Steps to reproduce

Actual
```
// Here goes the Title
//
// Here goes the description
//
// swagger:meta
```

Question:
```
// Here goes the Title
//
// $ref: intro.md
//
// swagger:meta
```

**Comment by casualjim** [comment]
This is not supported by the swagger specification. If you want to to do that you can always write a little bit of code to achieve much of the same result.
