### ISSUE TITLE
Make generated client use `consumes` in schema for Accept headers, rather than transport consumers

### ISSUE THREAD

**Issue by chancez** [go-swagger/go-swagger#235]
Currently Accept headers are gathered from the registered consumers on a client's `httpkit/client/(*Runtime).Consumers` map. Instead the MIME types in the operation's `consumes` field should be used.

This looks like it would be a matter of updating the template https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/client.gotmpl, the operation struct https://github.com/go-swagger/go-swagger/blob/master/client/client.go#L18, and the client submit method https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/runtime.go#L117-L122

**Comment by casualjim** [comment]
i think this can be closed
