### ISSUE TITLE
Duplicate struct field generated

### ISSUE THREAD

**Issue by MicahParks** [go-swagger/go-swagger#2352]
## Problem statement
A duplicate struct field is generated in the models if the swagger spec has keys named in the fashion below.
```json
"searchAfter": {
  "type": "string",
  "description": "Use this in future searches to get the next page of data"
},
"search_after": {
  "type": "integer",
  "format": "int64",
  "description": "deprecated"
}
```

This results in the struct for the associated model having two `SearchAfter` fields:
```go
// Use this in future searches to get the next page of data
SearchAfter string `json:"searchAfter,omitempty"`

// deprecated
SearchAfter int64 `json:"search_after,omitempty"`
```
Which means the generated code does not compile. Ideally, I'd control the `swagger.json` source and change it, but that is defined elsewhere. I could change the generated client code, but it's not best practice to edit it.

## Swagger specification
The WiGLE 2.0 API. Can be found [here](https://api.wigle.net/swagger.json).

## Steps to reproduce
```bash
curl https://api.wigle.net/swagger.json -o swagger.json
swagger generate client
go get -u -f ./...
```

## Environment
swagger version: v0.24.0
go version: 1.14.4
OS: Ubuntu 20.04

**Comment by casualjim** [comment]
like this should work

```
curl https://api.wigle.net/swagger.json -o swagger.json
sed -i 's/search_after/search_after_deprecated/' swagger.json
swagger generate client
go get -u -f ./...
```

we also have a swagger mixin command or you can make a small script that rewrites the spec. There is also the `x-go-name` extension you could add to override the go name that would get generated

**Comment by MicahParks** [comment]
The `sed` command will result in non-duplicate struct field names, but the JSON struct tag for the renamed one will not map to the original field, it'll map to the renamed field.

I wasn't able to find how swagger mixin would help, but I was able to use `x-go-name` to solve the problem perfectly. Here is [a link to the docs](https://goswagger.io/use/spec.html#known-vendor-extensions) relating to these vendor extensions.

This means the spec on my local machine looks slightly different:
```json
"searchAfter": {
  "type": "string",
  "description": "Use this in future searches to get the next page of data"
},
"search_after": {
  "type": "integer",
  "x-go-name": "SearchAfterDeprecated",
  "format": "int64",
  "description": "deprecated"
}
```

But the underlying swagger spec remains unchanged. A non-duplicate struct field generated with `swagger generate client` after this edit:
```go
// deprecated
SearchAfterDeprecated int64 `json:"search_after,omitempty"`
```
