### ISSUE TITLE
Comitting generated code to version control

### ISSUE THREAD

**Issue by MicahParks** [go-swagger/go-swagger#2360]
## Problem statement

Does this project have a recommendation of committing/not committing the generated Go source code to version control?

This is in the case of the `go-swagger` user having an existing swagger spec and using that spec to generate Go source code. Then using that generated Go source code in addition to human written code to make a fully functional client/server.

**Comment by casualjim** [comment]
https://goswagger.io/tutorial/todo-list.html
https://github.com/go-swagger/go-swagger/tree/master/examples/tutorials/todo-list/server-complete

**Comment by casualjim** [comment]
We commit generated code, it's the same as code written by a human.
