### ISSUE TITLE
Can't set custom PORT

### ISSUE THREAD

**Issue by nnqq** [go-swagger/go-swagger#2363]
## Problem statement

Hi. I can't set `host` and `port` via `configureServer`. It always random (as default). Is there an option to set host:port via code, not flag / env (or redeclared env with code)?

## Swagger specification

From readme

https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-expanded.json

## Steps to reproduce

```
swagger generate server -f https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-expanded.json -A issue_test
```
```
go mod init
```
```
go mod tidy
```
```
func configureServer(s *http.Server, scheme, addr string) {
	s.Addr = "0.0.0.0"+":1234"
}
```
```
go run cmd/issue-server/main.go
```
```
2020/07/22 21:02:06 Serving issue at http://127.0.0.1:61557
```

## Environment
swagger version: 0.25.0  
go version: 1.14 
OS: macOS 10.15.6

**Comment by casualjim** [comment]
make your own main (--skip-main) if you want to set it from code. There is a command line flag for passing the port.

You can configure the port here:
https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/cmd/todo-list-server/main.go#L47

Anywhere after `NewServer` and before `Serve` allows you to explicitly set the port property etc.

**Comment by nnqq** [comment]
Cool, thank you
