### ISSUE TITLE
allOf is always pointer using inheritance

### ISSUE THREAD

**Issue by HarlamovBuldog** [go-swagger/go-swagger#2364]
## Problem statement

Can't make allOf object to be not nullable. It's always pointer. `x-nullable:false` doesn't help. 

## Swagger specification
```
BundleAttributesResponse:
    properties:
      type:
        $ref: "#/definitions/BundleType"
      items:
        description: Array of bundle items in the root of the bundle.
        type: array
        items:
          $ref: "#/definitions/BundleItemResponse"
      sections:
        description: Array of bundle section in the root of the bundle.
        type: array
        items:
          $ref: "#/definitions/ItemBundleSectionResponse"
BundleSectionResponse:
    type: object
    x-omitempty: false
    properties:
      id:
        type: string
        x-omitempty: false
        example: 5dfb977429ec145dd6f9c307
     ...
  ItemBundleSectionResponse:
    allOf:
      - $ref: "#/definitions/BundleSectionResponse"
      - type: object
        x-omitempty: false
        properties:
          items:
            description: Array of bundle items inside a section of the bundle
            type: array
            items:
              $ref: "#/definitions/BundleItemResponse"
```
### Actual
```
// BundleAttributesResponse bundle attributes response
//
// swagger:model BundleAttributesResponse
type BundleAttributesResponse struct {

	// Array of bundle items in the root of the bundle.
	Items []BundleItemResponse `json:"items"`

	// Array of bundle section in the root of the bundle.
	Sections []*ItemBundleSectionResponse `json:"sections"`

	// type
	Type BundleType `json:"type,omitempty"`
}
```
### Expected
```
// BundleAttributesResponse bundle attributes response
//
// swagger:model BundleAttributesResponse
type BundleAttributesResponse struct {

	// Array of bundle items in the root of the bundle.
	Items []BundleItemResponse `json:"items"`

	// Array of bundle section in the root of the bundle.
	Sections []ItemBundleSectionResponse `json:"sections"`

	// type
	Type BundleType `json:"type,omitempty"`
}
```
I need `Sections []ItemBundleSectionResponse` to be without pointer. Is it known issue or am i missing smth?
## Steps to reproduce
Run `swagger generate model --spec=swagger.yml`
## Environment
swagger version: v0.25.0  
go version:  go1.13.5 linux/amd64
OS:  linux/amd64

**Comment by fredbi** [comment]
Yes. This commit added this explicitly a long time ago: https://github.com/go-swagger/go-swagger/commit/0df6cf44896e6fcf88aa2d1f57da3afeb3981766
It remains unclear to me why we wanted this and above all why we wanted to override any `x-nullable` setting.
@casualjim do you perchance recall why we specifically wanted all `allOf` structs to be forced as nullable?

**Comment by HarlamovBuldog** [comment]
Yeah, i mean it's really strange. Because this inheritance is really cool feature when it comes to making `swagger.yml` file less and reuse as much objects as possible. But because of this nullable override everything got broken in the code and you still need to duplicate stuff...

**Comment by fredbi** [comment]
How about I allow x-nullable to be able to override (like for the other object in your definition)? Would that help?

**Comment by fredbi** [comment]
@HarlamovBuldog something like that https://github.com/go-swagger/go-swagger/pull/2365
I am just allowing here the x-nullable hint to work in that case: a rather simple fix, not breaking other expectations.

**Comment by HarlamovBuldog** [comment]
@fredbi so basically you mean that if I will specify `x-nullable:false` in `ItemBundleSectionResponse` it will override it's base `BundleSectionResponse`, right?

**Comment by fredbi** [comment]
Yeah. Have a look at the fixture I've added to my PR. It does the job, but yes, it requires some extra hint in the specification.
I did that because deciding whether to have `[]*MyType` or `[]MyType` is a headache... and changing this behavior is difficult. Both are somehow valid and correspond to different use cases.

**Comment by HarlamovBuldog** [comment]
> Yeah. Have a look at the fixture I've added to my PR. It does the job, but yes, it requires some extra hint in the specification.
> I did that because deciding whether to have `[]*MyType` or `[]MyType` is a headache... and changing this behavior is difficult. Both are somehow valid and correspond to different use cases.

Okay, cool, thx.

**Comment by HarlamovBuldog** [comment]
@fredbi could you tell plz when will be the next release?
