### ISSUE TITLE
Streaming client appears to buffer all data before calling io.Writer with any data

### ISSUE THREAD

**Issue by mdelvecchio-wasabi** [go-swagger/go-swagger#2368]
## Problem statement

I am trying to implement a server that streams CSV records.  The server side appears to be working as expected, but the generated client seems to be buffering all data until the server is done, then calling the specified io.Writer repeatedly with the buffered data.

With the large data sets I am working with, this memory usage does not work.  My client needs to get the data as it arrives, process it, then discard it, so that the memory usage is not too high.

Please remove the sections that don't apply

## Swagger specification

```
swagger: '2.0'
info:
  title: Test
  contact:
    name: me
    url: http://wherever.com
    email: me@wherever.com
  description: Test API
  version: v1
host: billing
schemes:
  - https
  - http
basePath: /test
produces:
  - application/json

paths:
  /csv:
    get:
      summary: Get events streamed in CSV format
      operationId: getEventsCsv

      responses:
        200:
          description: CSV file to download
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: A header specifying the file name
```

## Steps to reproduce

On the server side, my handler returns a middleware.ResponderFunc() that returns a 200 OK response with Content-Disposition header:

```
			rw.Header().Set ("Content-Type", "text/csv")
			rw.Header().Set ("Content-Disposition", fmt.Sprintf ("attachment; filename=\"%s\"", fileName))
			rw.WriteHeader(200)
```

Then creates a csv.Writer from the http.ResponseWriter, and writes CSV records to it. 

This code performs as expected, and a curl command indicates that the CSV records are streamed immediately and consistently throughout the operation.  One test data set comprises about 1 million records totaling about 100 MB; it takes 10 seconds to stream that data to the client.

On the client side:

```
	params := client.NewGetEventsCsvParams()

	resp, err := clientOperations.GetEventsCsv(params, &myWriter)
```

Where myWriter is a struct instance with the io.Writer method implemented:

```
type MyCSVWriter struct {

	start       time.Time
	byteCount	int
}

func (w *MyCSVWriter) Write (p []byte) (n int, err error) {
	if flags.Debug() {
		fmt.Printf ("Got %d bytes at %v:\n%s\n", len (p), time.Since (w.start), string (p))
	}
	// Just keep count
	w.byteCount += len (p)

	return len (p), nil
}
```

As stated above, it takes about 10 seconds for my call to GetEventsCsv() to return, and it does return the expected 200 OK response.  Further, the writer's byteCount indicates that all 100MB are received.

However, the writer's Write() method does not get called until _all_ of the server's data is received.  So it does not get called for the full 10 seconds it takes for the 100MB to arrive, then gets called repeatedly with 4096-byte chunks of data.

This of course implies that the 100MB of data is being buffered, and a call to runtime.ReadMemStats() afterwards indicates that the client program is using 609 MB of memory.  This of course will not scale to the tens of millions of records I need to process.

How can I get the generated client to call my Write() method as the server's data arrives?  Then I can process it and it can be discarded, without the huge buffering that is occurring now.

## Environment
swagger version: v0.23.0
go version: go1.11.5
OS:   Ubuntu 18

**Comment by mdelvecchio-wasabi** [comment]
I also hacked up a manual client with the generated URL builder and http.Get().  It works as expected; data starts streaming as soon as the server sends it.

**Comment by casualjim** [comment]
I took this spec:

```yaml
swagger: '2.0'
info:
  title: Test
  contact:
    name: me
    url: http://wherever.com
    email: me@wherever.com
  description: Test API
  version: v1
host: "localhost:42567"
schemes:
  - http
basePath: /test
produces:
  - application/json

paths:
  /csv:
    get:
      summary: Get events streamed in CSV format
      operationId: getEventsCsv
      consumes:
        - text/csv
      produces:
        - text/csv
      responses:
        200:
          description: CSV file to download
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: A header specifying the file name
```

And I generated a client and server with the default settings.

 ```sh
swagger generate server
swagger generate client
```

I changed `./restapi/configure_swagger.go` to contain:

```go
api.GetEventsCsvHandler = operations.GetEventsCsvHandlerFunc(func(params operations.GetEventsCsvParams) middleware.Responder {
	return middleware.ResponderFunc(func(rw http.ResponseWriter, _ runtime.Producer) {
		f, ferr := os.Open("data/hw_25000.csv")
		if ferr != nil {
			http.Error(rw, ferr.Error(), http.StatusInternalServerError)
			return
		}
		defer f.Close()

		rw.Header().Set("Content-Type", "text/csv")
		rw.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"", "elements.csv"))
		rw.WriteHeader(200)

		io.Copy(rw, f)
	})
})
```

And I use a client like this:

```go
package main

import (
	"github.com/go-openapi/runtime"
	"log"
	"os"

	"github.com/go-openapi/wasabiswag/client"
	"github.com/go-openapi/wasabiswag/client/operations"
	httptransport "github.com/go-openapi/runtime/client"
)

func main() {
	transp := httptransport.New("localhost:42567", "/test", []string{"http"})
	transp.Consumers["text/csv"] = runtime.ByteStreamConsumer()
	transp.Producers["text/csv"] = runtime.ByteStreamProducer()

	cl := client.New(transp, nil)
	_, err := cl.Operations.GetEventsCsv(operations.NewGetEventsCsvParams(), os.Stdout)
	if err != nil {
		log.Fatalln(err)
	}
}

```

This seems to work. I tried to see if it is buffering the entire response by introducing a slow writer, on the server

```go
func configureAPI(api *operations.SwaggerAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.UseSwaggerUI()
	// To continue using redoc as your UI, uncomment the following line
	// api.UseRedoc()

	api.CsvConsumer = runtime.CSVConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.GetEventsCsvHandler = operations.GetEventsCsvHandlerFunc(func(params operations.GetEventsCsvParams) middleware.Responder {
		return middleware.ResponderFunc(func(rw http.ResponseWriter, _ runtime.Producer) {
			f, ferr := os.Open("data/hw_25000.csv")
			if ferr != nil {
				http.Error(rw, ferr.Error(), http.StatusInternalServerError)
				return
			}
			defer f.Close()

			rw.Header().Set("Content-Type", "text/csv")
			rw.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"", "elements.csv"))
			rw.WriteHeader(200)

			io.Copy(rw, &slowReader{f})
		})
	})

	api.PreServerShutdown = func() {}

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

type slowReader struct {
	under io.Reader
}

func (s *slowReader) Read(p []byte) (n int, err error) {
	n, err = s.under.Read(p)
	time.Sleep(500*time.Millisecond)
	return n, err
}
```

For me both curl and the client presented here do the same thing. They pause at the same times.
One thing to keep in mind is if your file is smile, it's likely buffered somewhere. The csv consumer that is selected for the text/csv mime tries to parse the document. That's why I overwrote them so they are passthrough

**Comment by mdelvecchio-wasabi** [comment]
I finally got a chance to circle back to this and test it.  The client changes are _exactly_ what I needed.  My Write() method now gets called back as the events arrive.

Thank you so much for your help on this!  And thank you for all of your work on this wonderful tool.  I have used several other packages at previous jobs, and go-swagger is the one that works the best.

Thanks!!!

**Comment by mdelvecchio-wasabi** [comment]
For future users, here is now I hooked up the io.Writer used for callbacks with a csv.Reader:

1. 1. Create a pipe reader/writer pair with io.Pipe()
2. 2. Create a CSV reader with the pipe reader
3. 3. Spin up a goroutine that reads from the CSV reader in the standard loop
4. When the io.Writer's Write() method is called, just write the data to the pipe writer.
5. When the API operation returns, call the pipe writer's Close() method

Note that the API operation can return before all records have been read by the CSV reader thread.  So that thread needs some sort of synchronization (channel, sync.WaitGroup, etc.) so that it can signal that it has reached EOF.  After the API operation returns success, it should wait for that synchronization.

**Comment by mdelvecchio-wasabi** [comment]
I just ran into a new issue with this server/client combination.

It works great when I return a 200 OK response with `Content-Type: text/csv` and one or more CSV records. 

It does not work great when I return a 500 Internal Server error.  I want that to return my standard APIError struct, which is a code and a message, in JSON format.  But it doesn't; the client just gets an empty reply and an EOF error.

I tried specifying that the operation produces two types, but because this is Swagger 2.0, I can't specify which response returns which type.  Here is what I have:

```
  /stuff/csv:

    get:

      summary: Get stuff streamed in CSV format

      produces:
        - text/csv
        - application/json

      responses:
        200:
          description: CSV file to download
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: A header specifying the file name
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/APIError'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/APIError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/APIError'
```

And in my server handler:

```
		// We need to return an error
		error := models.APIError{
			Code:       responseCode,
			Message:    err.Error(),
		}

		// Which object?
		switch responseCode {
		case 400:
			return billing.NewGetStuffBadRequest().WithPayload(&error)
		case 404:
			return billing.NewGetStuffNotFound().WithPayload(&error)
		default:
			return billing.NewGetStuffInternalServerError().WithPayload(&error)
		}
```

Is it possible for one operation to return text/csv for a 200, and application/json for other operations?

Thanks.

**Comment by mdelvecchio-wasabi** [comment]
I just remembered that you have already answered this question for me:

https://github.com/go-swagger/go-swagger/issues/2290

Thanks!
