### ISSUE TITLE
principal alias imports bug in v0.25.0

### ISSUE THREAD

**Issue by vikstrous** [go-swagger/go-swagger#2372]
## Problem statement

After upgrading from 0.24.0 to 0.25.0, aliased principal types are now being replaced by the types that they are aliases of. This breaks the generated code because it leads to importing /internal/ packages.

This is the diff in our generated code that resulted from the upgrade:
```
import (
        "net/http"

-       "<redacted>/lib/auth"
        "github.com/go-openapi/runtime/middleware"
+
+       "<redacted>/service/<redacted>/internal/<redacted>/auth"
 )
```

## Swagger specification
hopefully not relevant

## Steps to reproduce

Upgrade from 0.24.0 to 0.25.0.
Command run:
```
go run github.com/go-swagger/go-swagger/cmd/swagger generate server --target ./generated --name <redacted> --spec ./<redacted>.yaml --exclude-main -q --principal=auth.<redacted>
```

## Environment
swagger version: 0.25.0
go version: go1.14.4
OS:  linux/amd64

**Comment by vikstrous** [comment]
Sorry, looks like I completely misunderstood the problem. It seems like the issue is with the interpretation of the principal's path. There's no alias involved. I'll close this for now while I investigate this properly.

**Comment by vikstrous** [comment]
ok, we were using only the name of the package without a full path in the --principal parameter, which seems to have worked before for some mysterious reason (goimports?) and now it doesn't work any more. The --principal parameter needs a full package path

**Comment by fredbi** [comment]
@vikstrous  yes with v0.0.25 I've changed the way the path to principal is resolved. This had unintended consequences (see #2362). It works by specifying a fully qualified package path. I think I'll try to enhance this a bit to avoid breaking old habits of providing a _relative_ path. The problem I wanted to fix is when the principal resides outside the generated models.

**Comment by vikstrous** [comment]
I prefer the new behaviour. It makes sense to use an absolute path. The old behaviour seems to have been to guess the path based on the package name, which can be ambiguous.

**Comment by fredbi** [comment]
Yeah, the "new" behavior was actually motivated by some bugs to be fixed when importing a principal from outside.
I am still thinking it would be nice to honor things like `model.Principal` the way we used to, but yes you're right this is a guess and guessing things right is not always easy to code... If you have a nice way in mind, feel free to push a PR
