### ISSUE TITLE
Option to overwrite buffer size on upload file api 

### ISSUE THREAD

**Issue by tsorya** [go-swagger/go-swagger#2373]
## Problem statement
We need to have an option to set smaller buffer size while generating of upload file api
Right now it is hardcoded 32mb `ParseMultipartForm(32 << 20)` will be very helpful to have an option to overwrite it.

## Environment
swagger version: 2.0

**Comment by fredbi** [comment]
Why not. You can bring in a PR with that kind of extra setting set on the CLI (most likely an option to the generate server command only)

**Comment by fredbi** [comment]
The setting is here: https://github.com/go-swagger/go-swagger/blob/b8298e06c71243ef46bf553e3c18ed91d8539b8d/generator/templates/server/parameter.gotmpl#L393
