### ISSUE TITLE
x-go-type for a custom type in models/

### ISSUE THREAD

**Issue by maxatome** [go-swagger/go-swagger#2385]
## Problem statement

Before #2340 I was able to declare a type in my spec that was already present in `models/` (= not auto-generated). Here `MyType` used in a `Zzz` object type:

```
type Zzz struct {
        // meta
        Meta MyType `json:"meta,omitempty"`
}
```

Now it generates bad go code as the "import.package" is empty (then gofmt glues field name and the type together):

```
type Zzz struct {
        // meta
        Meta.MyType `json:"meta,omitempty"`
}
```

Is there a way to overcome this behavior? (excluding the move of custom types outside models/, of course)

## Swagger specification

```
---
swagger: "2.0"
info:
  version: "1.0"
  title: "Test API"
paths:
  /test:
    get:
      responses:
        default:
          description: xxx
          schema:
            $ref: "#/definitions/Zzz"

definitions:
  Zzz:
    type: object
    properties:
      meta:
        $ref: '#/definitions/MyType'

  MyType:
    type: object
    x-go-type:
      type: MyType
```

## Steps to reproduce

Using v0.25.0:
```
swagger generate server -f api.yaml
```

## Environment
swagger version: 0.25.0  
go version: 1.15
OS:   Linux x86_64

**Comment by fredbi** [comment]
Yes I should probably imply that if there is no package it is located alongside the generated models.
Good catch
