### ISSUE TITLE
Why is version always dev?

### ISSUE THREAD

**Issue by fgblomqvist** [go-swagger/go-swagger#2395]
## Problem statement

Why does the command `swagger version` always just return "dev"? I have tried a couple of different versions (including 0.25.0) but it doesn't output the actual version number. It would be really helpful to know the version for debugging purposes.

**Comment by mtfelian** [comment]
Same issue if to compile swagger from sources. This is very annoying.. Keeping in mind that newer versions of swagger almost always have breaking changes. 

But in docker it works well:
![image](https://user-images.githubusercontent.com/15889474/92454800-98a6a500-f1c9-11ea-8bd7-a0511767f7a9.png)

**Comment by a2800276** [comment]
The Version information is written into the executable by the linker along with the commit hash. If you are building the executable yourself, you inject the version and commit info using the `-ldflags` of the `go build` command (see .circleci/config.yml concerning what the linker flags looks like). It looks like the binaries in the releases page are built this way, so if you need a proper version, you can use one of those...
