### ISSUE TITLE
How to define properties of an object (that are referenced to definitions) as required ?

### ISSUE THREAD

**Issue by farshadahmadi** [go-swagger/go-swagger#2400]
## Problem statement

The expected behaviour is that go-swagger defines required fields as pointers. For example,

```
SignupRequest:
    properties:
      email:
        type: string
    required:
      - email
```

will be

```
type SignupRequest struct {
	// email
	// Required: true
	Email *string `json:"email"`
}
```

However, required properties of an object that are referenced to definitions  are not pointers by default. For example:

```
SignupRequest:
    properties:
      email:
        $ref: "#/definitions/Email"
    required:
      - email
definitions:
  Email:
    type: string
```
wille be:

```
type SignupRequest struct {
	// email
	// Required: true
	Email Email `json:"email"`
}
```

Should Email field be of *Email type?

Now to get the email as pointer, we can use `x-nullable`. However the following does not work:

```
SignupRequest:
    properties:
      email:
        $ref: "#/definitions/Email"
        x-nullable: true
    required:
      - email
definitions:
  Email:
    type: string
```

But If we put `x-nullable` in the definition as following, it works, but I do not want to do it in the common definitions!

```
SignupRequest:
    properties:
      email:
        $ref: "#/definitions/Email"
    required:
      - email
definitions:
  Email:
    type: string
    x-nullable: true
```

The other workaround is to use `allOf` as following. Which is weird!

```
SignupRequest:
    properties:
      email:
        allOf:
          - $ref: "#/definitions/Email"
          - x-nullable: true
    required:
      - email
definitions:
  Email:
    type: string
```

## Environment
swagger version: 2.0
go version: go1.14.6

**Comment by gregmarr** [comment]
"The expected behaviour is that go-swagger defines required fields as pointers."

So that we're on the same page, why do you expect that behavior?  Are you expecting it based on some go-swagger documentation or previous behavior, or just that's what you'd expect a framework like go-swagger to produce?

The normal behavior for go-swagger is that optional things are pointers (so they can be null) and that required things are not (so they can't be null).

**Comment by farshadahmadi** [comment]
Based on how swagger works now! How normal behaviour is like so when (as I explained), the following

```
SignupRequest:
    properties:
      email:
        type: string
    required:
      - email
```

generates

```
type SignupRequest struct {
	// email
	// Required: true
	Email *string `json:"email"`
}
```

But if I remove `required`, the email will be of type `string`. And that makes sense. Since, as you yourself also already mentioned [here](https://github.com/go-swagger/go-swagger/issues/1707#issuecomment-455565948):

> If you absolutely must know if it's provided or not, then use x-nullable as described above.

pointers are a way to check if a property is actually provided or not. Otherwise while unmarshalling, unprovided properties will get their zero values! For example in the above case, email will be empty string though the request body does not provide email!

**Comment by casualjim** [comment]
So to summarize. When you don't use a type alias it correctly turns the string into pointer for a required field, but when you use a type alias this is no longer the case, is that correct?

**Comment by gregmarr** [comment]
@farshadahmadi Sorry, I had it backwards in my brain for some reason.  Probably because that's the way that I always thought it should work,

**Comment by farshadahmadi** [comment]
@casualjim That's right.
Also I noticed that if the type alias is itself an object (not a primitive value like string as the above case), it is always a pointer, no matter being required or not!
@gregmarr NP!
