### ISSUE TITLE
Shadowing api var in generated main.go

### ISSUE THREAD

**Issue by igorlysak** [go-swagger/go-swagger#2405]
## Problem statement
Shadowing `api` var in generated `main.go` if `go-swagger` was run with `--server-package=api`. This leads to failed compilation when call `go get -u -f ./...`.

```
# test/cmd/a-todo-list-application-server
cmd/a-todo-list-application-server/main.go:27:15: api.NewServer undefined (type *operations.ATodoListApplicationAPI has no field or method NewServer)
```

## Swagger specification
Any. I check spec from [Simple Server tutorial](https://goswagger.io/tutorial/todo-list.html)

## Steps to reproduce
1. Take swagger specification from [Simple Server tutorial](https://goswagger.io/tutorial/todo-list.html) as `swagger.yaml`
2. Call `go module init test` in same dir where `swagger.yaml` was placed
3. Call `swagger generate server --server-package=api`
3. Call `go get -u -f ./...`

## Environment
swagger version: 
```
version: v0.25.0
commit: f032690aab0634d97e2861a708d8fd9365ba77d2
```
go version: `go version go1.14.2 darwin/amd64`
OS: `macOS Catalina 10.15.6`

**Comment by fredbi** [comment]
@igorlysak  Yes, there are known issues with the special name "api". This means that the import package realiasing failed to detect the conflicting situation. This is a bug.
