### ISSUE TITLE
generated model property uses type rather than format with v0.25.0 

### ISSUE THREAD

**Issue by bodenr** [go-swagger/go-swagger#2420]
## Problem statement
go-swagger 0.25.0 generates server models that are incompatible with 0.23.0 when using properties with custom `format`. Specifically object properties are generated using the custom `format` type in 0.23.0, but with 0.25.0 they are generated using the `type`. Obviously the impl can be fixed by updating to convert to the custom format, but this incompatibility seems less than optimal.

## Swagger specification
Using the following spec definition:
```yaml
type: object
properties:
  sha256:
    description: The SHA256 sum of the archive.
    type: string
    format: sha256
```

## Steps to reproduce
1. Use go-swagger 0.23.0 to generate the server model for the above object. The resulting model contains the following:
```go
Sha256 formats.SHA256 `json:"sha256,omitempty"`
```
2. Now use go-swagger 0.25.0 to generate the server model from above. The resulting model contains:
```go
Sha256 string `json:"sha256,omitempty"`
```
Notice the generated model code is not compatible and the impl must now explicitly handle converting to/from string/formats.SHA256

## Environment
swagger version: 0.25.0  
go version: 1.14.0  
OS: Ubuntu 18.x

**Comment by bodenr** [comment]
Before undertaking the significant effort of handling format conversion in our API impl (as described in the bug report herein), can someone please confirm that in fact recent versions of go-swagger will no longer define models using `format` and handle such conversion (as was done in 0.23.0 and earlier)?

I searched the go-swagger `generate server` options hoping there was an option to enable this (for backwards compatibility), but didn't find anything.

Thank you

**Comment by casualjim** [comment]
You can try to use x-go-type and specify the typename there. I think this is a side-effect of supporting embedded types more thoroughly.

https://github.com/go-swagger/go-swagger/blob/master/generator/types.go#L166-L186

https://github.com/go-swagger/go-swagger/blob/cab6b91dde1b2508762f758c89fa42adea52ec50/fixtures/enhancements/2224/fixture-2224.yaml#L53-L59

**Comment by bodenr** [comment]
Thanks for the tip.

I'm not familiar with the usage of `x-go-type` so I'll have to dig deeper.
Based on what I see initially it doesn't seem this would support handling format conversion automatically with existing format definitions so may require just as much work -- however, I could be totally wrong since I haven't munked with it.

**Comment by casualjim** [comment]
Another option is to make your own CLI or fork strfmt so you can add your string format to that registry. That way it would be picked up too. 

The behavior you saw and were relying on was very suprising to me. I don't even know how that would have worked in the past, because those string formats are all looked up in a hardcoded dictionary.

**Comment by bodenr** [comment]
Thanks for the info; I appreciate it.

I'll just update our impl to do the conversion between string/sha256; hopefully this will set us up for easier updates for future versions of go-swagger. It would take some digging for me to understand why/how things were working previously W/R/T to the format conversion as I wasn't the original author of our API. However, it sounds like we should probably revisit how our go-swagger build/config is setup to ensure we are up to par.

Thanks again,

**Comment by fredbi** [comment]
@bodenr 
You can use external types with a `Validate(...) error` method by a declaration like so:
```yaml
  myModel:
    type: object
    x-go-type:
      type: MyCustomModel
      import:
        package: github.com/example/models
```
Using the `format` in the specifier could be useful for documentation purposes, but ignored by the generator.

**Comment by bodenr** [comment]
Thanks for the input.
After further investigation it appears the version of go-swagger previously used has customized logic resulting in the format usage in the data model. My apologies for the confusion.
As far as I'm concerned this defect can be closed.
