### ISSUE TITLE
Update generation doc regarding Terms of Services

### ISSUE THREAD

**Issue by burgesQ** [go-swagger/go-swagger#2421]
## Problem statement

When generating swagger from code, the documentation wrongly describe the `Terms Of Service` requirements.

I've tried (without success) : 
```
//
//  TermsOfService: https://www.youtube.com/watch?v=DLzxrzFCyOs
//  TermsOfService:
//   https://www.youtube.com/watch?v=DLzxrzFCyOs
//
//  Terms Of Service: https://www.youtube.com/watch?v=DLzxrzFCyOs
//  Terms Of Service: 
//   https://www.youtube.com/watch?v=DLzxrzFCyOs
```

After checking at the code (`scan/meta.go`), I realize that the expected key was `TOS` **and** that the value must be a multiline one  

Working case :
```
//
//  TOS:
//   https://www.youtube.com/watch?v=DLzxrzFCyOs
```

## Steps to reproduce

Generating swagger from those annotations result in no TOS field in the swagger.json (`swagger generate spec -o swagger.json ; grep -i "terms\|tos" swagger.json`)  : 
```
//
//  TermsOfService: https://www.youtube.com/watch?v=DLzxrzFCyOs
//  TermsOfService:
//   https://www.youtube.com/watch?v=DLzxrzFCyOs
//
//  Terms Of Service: https://www.youtube.com/watch?v=DLzxrzFCyOs
//  Terms Of Service: 
//   https://www.youtube.com/watch?v=DLzxrzFCyOs
```

## Environment
swagger version: 0.25.0 f032690aab0634d97e2861a708d8fd9365ba77d2  
go version: 1.13.15
OS: linux mint 20

**Comment by fredbi** [comment]
Yes we could definitely support `TermsOfService` as a valid key. I wasn't aware of this abreviation. A welcome enhancement.

**Comment by fredbi** [comment]
@burgesQ 

I could not reproduce your issue, using (like you), the go1.11+ version of the scanner (codescan package).

The only statement that I could assert is that TermsOfService is a multi-line entry, and thus annotations like this don't work:
```
//  TermsOfService: https://www.youtube.com/watch?v=DLzxrzFCyOs
```

I could test the following work:
```
//
// Terms Of Service:
// there are no TOS at this moment, use at your own risk we take no responsibility
//
```

```
//
// TermsOfService:
// there are no TOS at this moment, use at your own risk we take no responsibility
//
```

```
//
// TOS:
// there are no TOS at this moment, use at your own risk we take no responsibility
//
```
Without blank lines:
```
// Package meta Petstore API.
//
// the purpose of this application is to provide an application
// that is using plain go code to define an API
//
// This should demonstrate all the possible comment annotations
// that are available to turn go code into a fully compliant swagger 2.0 spec
//     TermsOfService:
//        there are no TOS at this moment, use at your own risk we take no responsibility
//     Schemes: http, https
//     Host: localhost
```

**Comment by burgesQ** [comment]
@fredbi hi, hum I cannot reproduce the issue anymore :shrug: even worst: when I remove the `TOS` annotation from my `docs` package, the field still appear in the generated swagger doc ! 

Anyway, I'll come back here with some example next time I face this issue
