### ISSUE TITLE
swagger validate fails on responses with description field

### ISSUE THREAD

**Issue by eimlav** [go-swagger/go-swagger#2429]
## Problem statement

Recent updates to go-swagger dependencies mean that the `description` field of responses is no longer omitted when empty.

The validator needs to be updated to accommodate this change.

## Swagger specification

```
...
"/api/test": {
      "get": {
        "description": "test description",
        "consumes": [
          "text/json"
        ],
        "produces": [
          "text/json",
          "text/yaml"
        ],
        "tags": [
          "core"
        ],
        "summary": "api/test",
        "operationId": "apiTest",
        "parameters": [
          {
            "enum": [
              "yaml",
              "json"
            ],
            "type": "string",
            "x-go-name": "Encoding",
            "description": "\"yaml\" or \"json\" to be returned",
            "name": "encoding",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "$ref": "#/responses/TestResponse"
          },
          "400": {
            "description": "",
            "$ref": "#/responses/InputError"
          },
          "500": {
            "description": "",
            "$ref": "#/responses/ServerError"
          }
        }
      }
...
```

## Steps to reproduce

```
swagger generate spec -o ./swagger.json --scan-models -x swagger-automation

swagger validate ./swagger.json
```

## Environment
swagger version: master ([d7d6b60](https://github.com/go-swagger/go-swagger/tree/d7d6b609c5c2926b3ea759f3f6f1099d74503f05))
go version: 1.14
OS:  MacOS 10.15 + Github Actions ubuntu-latest

**Comment by fredbi** [comment]
Yes this is an unexpected consequence of fixing another bug...
I believe that the proper fix should be with  a custom json marshalling in go-openapi/spec: the problem here is to display "description" when there is a "$ref".

**Comment by fredbi** [comment]
@eimlav just attempted a quick fix https://github.com/go-openapi/spec/pull/127
Now I need some more time to test the other go-openapi repos. But you may give it a shot.

**Comment by eimlav** [comment]
@fredbi I checked out go-swagger master, pinned your branch https://github.com/fredbi/spec/tree/fix-2429 and rebuilt the go-swagger binary. It is now omitting the empty descriptions and passing validation.

**Comment by fredbi** [comment]
@eimlav thanks. This helps me a lot.

**Comment by eimlav** [comment]
@fredbi I completely missed this as I changed it when testing out your fix, but you need to remove the replace directive in go.mod too https://github.com/go-swagger/go-swagger/blob/master/go.mod#L3 or else the updated version of go-openapi/spec is never used.

**Comment by fredbi** [comment]
@eimlav  ah crap I forgot to remove it. Thanks for letting me know. I am going to fix this up ASAP

**Comment by eimlav** [comment]
@fredbi Just tested master and everything is working 100% now. Thanks for all your help in addressing this :)
