### ISSUE TITLE
authorizationUrl empty breaking mixin and validation

### ISSUE THREAD

**Issue by kenjones-cisco** [go-swagger/go-swagger#2430]
we can remove omitempty, that should be fine. It would solve this issue and shouldn't break anything

_Originally posted by @casualjim in https://github.com/go-swagger/go-swagger/issues/1775#issuecomment-544210653_

After the change was made, when using `swagger mixin` to build a complete API spec, it adds the empty `"authorizationUrl": ""` to the securityDefinition even when the `type` is `apiKey` and that is invalid.

**Comment by kenjones-cisco** [comment]
#2427 where change was applied

**Comment by fredbi** [comment]
@kenjones-cisco  
I've added a fix to go-openapi/spec to have a better control over the json marshalling:

https://github.com/go-openapi/spec/pull/127

I believe that should address the regression you have pointed out, without changing anything to the mixin logic.
Could you please confirm this fixes your problem?

**Comment by kenjones-cisco** [comment]
@fredbi It is working as expected now. Thanks!
