### ISSUE TITLE
Can model composition in go-swagger?

### ISSUE THREAD

**Issue by shengwudiyi** [go-swagger/go-swagger#2436]
## Problem statement

like this 

> @success 200 {object} rest.RspProto{data=rest.PaginationResult}

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by fredbi** [comment]
Hello @shengwudiyi. Could you elaborate a bit, please?

**Comment by shengwudiyi** [comment]
Hello @fredbi  😊

i want to reply with a common structure
```golang
RspProto struct {
 Code    int         `json:"code"`
 Message string      `json:"msg"`
 Data    interface{} `json:"data,omitempty"`
}
```
but `Data` s are different among requests, how do I describe responses

**Comment by fredbi** [comment]
@shengwudiyi 
Like so:
```yaml
  ....
  response:
    description: "generic"
      schema:
        $ref: '#/definitions/rspProto'

definitions:
  rspProto:
    type:
      object
   properties:
     codeinteger:
       type: integer
    message:
       type: string
    data:
      type: object
```
