### ISSUE TITLE
Support default value in parameters scanner

### ISSUE THREAD

**Issue by jerbob92** [go-swagger/go-swagger#244]
It would be great to support default values in the annotations of swagger:paramaters.
I'll try to work on this soon.

Possibly something like:

```
    // The direction of the sort. Can be "DESC" or "ASC".
    //
    // in: query
    // default: "DESC"
    SortOrder string `json:"sortorder"`
```

**Comment by casualjim** [comment]
Cool, perhaps default values, enums and examples can be defined as functions or vars with a naming convention? 

Then the tool can generate json and yaml for them.

It also makes it so that people can use code to express them and take advantage of the compiler

**Comment by jerbob92** [comment]
Functions with naming conventions sound overly complicated to me, but that might be because I have only used the spec generator from go-swagger. What if we implement a new swagger type?

Might be something like:
```
// swagger:defaultvalue
var defaultSortOrder = "DESC"

// swagger:enum
var allowedSorts = []string{
	"DESC",
	"ASC",
}
```

Which results in the following paramater definition:
```
    // The direction of the sort. Can be "DESC" or "ASC".
    //
    // in: query
    // default: defaultSortOrder
    // enum: allowedSorts
    SortOrder string `json:"sortorder"`
```

Then it kind of works the same as with route Responses codes/struct mapping.

**Comment by casualjim** [comment]
yes a var works as well, I like this :+1:

**Comment by jerbob92** [comment]
Great, I'll see what I can do tomorrow. Makes it more complicated than my initial plan so I might not get that far.

**Comment by casualjim** [comment]
I'll accept any progress so you can do the simpler plan if you prefer, I was just making a suggestion. I don't want to make it a hurdle to contributing, we can always make it better later

**Comment by jerbob92** [comment]
Nah, it's no problem. I rather do it correctly right away.
I'll report my progress here and maybe someone else can pick up the work when I'm out of time.

**Comment by jerbob92** [comment]
See my work in progress here:
https://github.com/go-swagger/go-swagger/compare/master...jerbob92:feature/244-245-enums-defaults-for-parameters?expand=1

**Comment by casualjim** [comment]
perhaps this could be useful for this: https://github.com/japm/goScript

There are a few other ones out there that allow string eval of go code.

**Comment by McSwitch** [comment]
@jerbob92 Do you mind if I pickup this issue? May I use the progress you have made thus far?

**Comment by jerbob92** [comment]
@McSwitch sure! I'm not working on it anymore

**Comment by McSwitch** [comment]
@casualjim Instead of going the whole nine yards here, could I simply add `enum` and `default` options into the swagger:parameters annotation, this will at least give us a starting point to work from?

## Usage

```go
// swagger:parameters operation
type Example struct {
    // enum: foo,bar,none
    // default: bar
    // in: query
    Category string `json:"category"`
}
```

This should output the following into the category parameter section:
```json
            "type": "string",
            "enum": [
              "foo",
              "bar",
              "none"
            ],
            "default": "bar",
            "x-go-name": "Category",
            "name": "category",
            "in": "query"
```

**Comment by casualjim** [comment]
@McSwitch there are people actively working on enum support so you can leave that. Default value support is still not implemented through.
