### ISSUE TITLE
Can't easily tell which version of swagger i'm running

### ISSUE THREAD

**Issue by ezk84** [go-swagger/go-swagger#2454]
## Problem statement

Running `swagger version` always returns `dev`, and this makes it hard to know which one is installed in my system. 

## Steps to reproduce

```
$ go mod init example.com/swaggerversiontest
$ go get github.com/go-swagger/go-swagger/cmd/swagger@v0.25.0
$ swagger version
dev 
```

If I try `@latest` the same is the case, as using a commit hash.

## Environment
swagger version: v0.25.0
go version: 1.15
OS:  Win10

**Comment by fredbi** [comment]
duplicates #1283
