### ISSUE TITLE
Petstore example does not work

### ISSUE THREAD

**Issue by gmazzotta** [go-swagger/go-swagger#2459]
## Problem statement

Petstore example does not work. It is either reporting the wrong URL or something is wrong in the code.

## Steps to reproduce

If I build the Petstore example and run it, the URL http://127.0.0.1:8344/swagger-ui/ does not work

1. `go build examples/2.0/petstore/server/petstore.go`
2. `./petstore`
```
2020/12/16 13:27:56 Serving petstore api on http://127.0.0.1:8344/swagger-ui/
```

From another terminal:
1. `curl  http://127.0.0.1:8344/swagger-ui/`
```
{"code":404,"message":"path /swagger-ui/ was not found"}
```

## Environment
swagger version: current master, c36f768

go version: 1.15.3
OS:   Linux

**Comment by fredbi** [comment]
Indeed there is a type in the server message.
The correct URL is:
```
curl http://127.0.0.1:8344/api/pets/
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]
```

**Comment by gmazzotta** [comment]
@fredbi OK, so it was not supposed to serve the Swagger UI as well? e.g. there is no example for a service that has both the API and the docs exposed? (just checking)
