### ISSUE TITLE
provide a version command

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#246]
Provide a version command for go-swagger

**Comment by Xe** [comment]
This is a nontrivial thing to do in Go due to the lack of compile-time code execution.

**Comment by casualjim** [comment]
I figured since I'm signing tags, I'd add a pre-commit hook which generates a go file with a version string in there that I can get from git describe. 

```shellsession
git:(master) ✗ !? » git describe
v0.2.0-163-g11157eb
```
