### ISSUE TITLE
x-omitempty doesn't work with a $ref'ed object

### ISSUE THREAD

**Issue by mpokryva** [go-swagger/go-swagger#2473]
## Problem statement

The `x-omitempty` property doesn't generate the corresponding `omitempty` struct stag with a `$ref`'ed `object`.

I tried inlining the `$ref` and that solved the problem.

I apologize in advance if this is a repeat issue, as this seems like a common enough problem. I tried to find an existing issue, but couldn't.

## Swagger specification

```
swagger: "2.0"
info:
  description: >
    Example
  title: Example
  version: "1.0"

paths:
  /example:
    get:
      operationId: "exampleOp"
      produces:
        - "application/json"
      responses:
        200:
          description: "An example"
          schema:
            type: string

definitions:
  testDef:
    type: object
    properties:
      end:
        type: integer
        x-omitempty: false
        $ref: "#/definitions/testRef"

  testRef:
    type: integer
```

## Steps to reproduce

`swagger generate model -f test_swagger.yaml -m=test_swagger`

## Expected output
```
// TestDef test def
//
// swagger:model testDef
type TestDef struct {

	// end
	End TestRef `json:"end"`
}
```

## Actual output
```
// TestDef test def
//
// swagger:model testDef
type TestDef struct {

	// end
	End TestRef `json:"end,omitempty"`
}
```

## Environment
swagger version: `v0.25.0` (also tried `dev`)
go version: `1.15.5`
OS: ` darwin/amd64 (Mac 10.15.6)`

**Comment by gregmarr** [comment]
The Swagger Schema spec doesn't allow a `$ref` entry to have any siblings, and so they're ignored.

**Comment by mpokryva** [comment]
I looked at that issue but I saw some commits that "fixed it" so I thought this was different. I understand now, thank you!
