### ISSUE TITLE
Pointer convertors for enum types are not generated.

### ISSUE THREAD

**Issue by iamtakingiteasy** [go-swagger/go-swagger#2482]
No methods converting enum literal to a pointer value of same type are generated by current CLI.

**Comment by roberth1988** [comment]
We are having the same problems. So with latest CLI it breaks a current working version.

**Comment by iamtakingiteasy** [comment]
@roberth1988 I doubt they were generated before (but correct me if i'm wrong).
This was intended as a feature request to avoid writing your own tedious literal-to-pointer converters, however simple should probably be automated by API stub generator.

**Comment by fredbi** [comment]
@iamtakingiteasy no this has never been the case. Looks like this is a request for enhancement.

**Comment by roberth1988** [comment]
Hmm, maybe I understand it wrongly. My current code is working properly with 0.25.
Once I try to Regenerate all things with 0.25 based on the same swagger I got these changes:


`        // environment
        // Required: true
-       Environment EnvironmentName `json:"environment"`
+       Environment *EnvironmentName `json:"environment"`
`

Happens on all my Enum fields currently...

`
const (

	// EnvironmentNameDev captures enum value "dev"
	EnvironmentNameDev EnvironmentName = "dev"

	// EnvironmentNameTest captures enum value "test"
	EnvironmentNameTest EnvironmentName = "test"

	// EnvironmentNameQas captures enum value "qas"
	EnvironmentNameQas EnvironmentName = "qas"

	// EnvironmentNameProd captures enum value "prod"
	EnvironmentNameProd EnvironmentName = "prod"

	// EnvironmentNameMock captures enum value "mock"
	EnvironmentNameMock EnvironmentName = "mock"
)
`

so before I used to use: 

`apimodel.EnvironmentName(c.EnvironmentName)`

So the code is broken when I use 0.26 - what's the best practice here?

**Comment by fredbi** [comment]
@roberth1988 you are converting incompatible types (pointer vs non-pointer).

What is interesting here is that it seems that you used to get a non-pointer value for a required property and no this field is generated as a pointer. Could you share the spec that generates this model. I'd be interested to figure out why it used to be non-pointer and the target generated type has changed with v0.26.

**Comment by fredbi** [comment]
ok so there are different mixed issues here:
- @roberth1988 's actual problem is that for some reason, the codegen moved some fields to pointers when they were not.
- @iamtakingiteasy  's point is indeed an enhancement. I am showing a proposal below.

@roberth1988 your issue is different, even though it shares the same symptoms. Could you please open a separate issue with your spec and excerpts of generated code before/after v0.26.0, so we can help you out more efficiently?

**Comment by fredbi** [comment]
@iamtakingiteasy regarding your request, how about a help factory like this one?
I am sticking to the string case only, since that the only case now for which we generate `const`.

```go
// SodaBrand Some top level description
//
// swagger:model SodaBrand
type SodaBrand string

func NewSodaBrand(value SodaBrand) *SodaBrand {
	v := value
	return &v
}

const (

	// SodaBrandOTHERBRAND captures enum value "OTHER_BRAND"
	SodaBrandOTHERBRAND SodaBrand = "OTHER_BRAND"

	// SodaBrandPEPSI captures enum value "PEPSI"
	SodaBrandPEPSI SodaBrand = "PEPSI"

	// SodaBrandCOKE captures enum value "COKE"
	SodaBrandCOKE SodaBrand = "COKE"

	// SodaBrandCACTUSCOOLER captures enum value "CACTUS_COOLER"
	SodaBrandCACTUSCOOLER SodaBrand = "CACTUS_COOLER"

	// SodaBrandJOLT captures enum value "JOLT"
	SodaBrandJOLT SodaBrand = "JOLT"
)
```

**Comment by fredbi** [comment]
or maybe more flexible:
```go

func NewSodaBrand(value ...SodaBrand) *SodaBrand {
	var v *SodaBrand
        for _, w := range value {
            *v = w
        }
	return v
}
```

**Comment by iamtakingiteasy** [comment]
> ```go
> func NewSodaBrand(value SodaBrand) *SodaBrand {
> 	v := value
> 	return &v
> }
> ```

This looks fine, but thanks to go's type system and GC you don't even need any other variable than argument itself:
```go
func NewSodaBrand(value SodaBrand) *SodaBrand {
	return &value
}
```

Regarding your follow-up:

> ```go
> func NewSodaBrand(value ...SodaBrand) *SodaBrand {
> 	var v *SodaBrand
>         for _, w := range value {
>             *v = w
>         }
> 	return v
> }
> ```

This should produce nil-pointer dereference and I don't see a point assigning same local variable over and over again from list of arguments.

Maybe you meant array version of same function (I'm using make instead of append to reduce number of possible reallocations):

```go
func NewSodaBrandArray(values ...SodaBrand) (arr []*SodaBrand) {
	arr = make([]*SodaBrand, len(values))

	for i := range values {
		arr[i] = &values[i]
	}

	return
}
```

**Comment by fredbi** [comment]
@iamtakingiteasy yeah you're right, return a nil pointer is not a good idea.
The vararg version just came on top of my mind as I know of some other issue (#1393) for which the obvious solution
would be to generalize factory functions (i.e. `New{{ model }}`) for all generated models. This shouldn't conflict with a specific factory for enumerated types...
