### ISSUE TITLE
Could not resolve reference: invalid character looking for beginning of value

### ISSUE THREAD

**Issue by aliakseiz** [go-swagger/go-swagger#2492]
## Problem statement
Simple schema provided below doesn't validate according to swagger specification 2.0:
```
The swagger spec at "./rest/swagger.yaml" is invalid against swagger specification 2.0.
See errors below:
- could not resolve reference in /_version to $ref : invalid character 's' looking for beginning of value
```

## Swagger specification
```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Project
host: '127.0.0.1:8080'
basePath: '/api/v1'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /_version:
    get:
      operationId: getBuildInfo
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/BuildInfo'

definitions:
  BuildInfo:
    properties:
      Version:
        type: string
      CommitHash:
        type: string
      BuildTime:
        type: string
```

But when `BuildInfo` definition is declared inline in 200-response schema, validation succeeds.

## Steps to reproduce

Execute command `swagger validate ./swagger.yaml`

## Environment
swagger version: 0.26.0  
go version: 1.15
OS: Windows 10 Pro 1909

**Comment by ajinkyan83** [comment]
Facing similar issues! 
`$ swagger version
version: v0.26.0`
`
$ go version
go version go1.15.2 windows/amd64`

OS: Windows 10 Pro

**Comment by fredbi** [comment]
With this release, a lot has changed in the underlying libraries.

On linux everything works fine (see below).

I know that $ref are broken with Windows, but it used to be only some edge case, not the simple case like this.

I've tried to reproduce on linux, and this works fine in my environment. So the problem is really specific to $ref resolution on Windows.

## build from source @v0.26.0
```bash
go mod download
go install github.com/go-swagger/go-swagger/cmd/swagger

swagger validate fixture-2492.yaml
2021/01/20 09:45:05 
The swagger spec at "fixture-2492.yaml" is valid against swagger specification 2.0

swagger validate fixture-2493.yaml
2021/01/20 09:45:43 
The swagger spec at "fixture-2493.yaml" is valid against swagger specification 2.0

mkdir gen-2492

swagger generate server -f fixture-2492.yaml --target gen-2492 --quiet && (cd gen-2492/cmd/project-server && go build)
ls gen-2492/cmd/project-server
main.go  project-server

mkdir gen-2493

swagger generate server -f fixture-2493.yaml --target gen-2493 --quiet && (cd gen-2492/cmd/project-server && go build)

ls gen-2493/cmd/server
main.go  server
```

## build from docker @v0.26.0

```bash
mkdir gen-docker-2492

docker run -u $(id -u)\
  -v ${PWD}:/var/input \
 -v ${PWD}/gen-docker-2492:${PWD}/gen-docker-2492  \
 -e GOPATH=${GOPATH} \
 quay.io/goswagger/swagger:v0.26.0 \
 generate server -f /var/input/fixture-2492.yaml --target ${PWD}/gen-docker-2492

(cd gen-docker-2492/cmd/project-server && go build)

ls gen-docker-2492/cmd/project-server
main.go  project-server

mkdir gen-docker-2493

docker run -u $(id -u)\
  -v ${PWD}:/var/input \
 -v ${PWD}/gen-docker-2493:${PWD}/gen-docker-2493  \
 -e GOPATH=${GOPATH} \
 quay.io/goswagger/swagger:v0.26.0 \
 generate server -f /var/input/fixture-2493.yaml --target ${PWD}/gen-docker-2493

(cd gen-docker-2493/cmd/server && go build)

ls gen-docker-2493/cmd/server
main.go  server
```

### build from binary release @v0.26.0
On ubuntu:
```
apt install swagger  # removed configuration step of apt repository etc, for brevity
...
Preparing to unpack .../swagger_0.26.0_amd64.deb ...
Unpacking swagger (0.26.0) ...
Setting up swagger (0.26.0) ...

/usr/bin/swagger version
version: v0.26.0
commit: 640fa2f19f215cda0b815a4bb9a26aae2bd477d2

 /usr/bin/swagger validate fixture-2492.yaml
2021/01/20 10:01:12 
The swagger spec at "fixture-2492.yaml" is valid against swagger specification 2.0

/usr/bin/swagger validate fixture-2493.yaml
2021/01/20 10:01:24 
The swagger spec at "fixture-2493.yaml" is valid against swagger specification 2.0

mkdir gen-binary-2492

/usr/bin/swagger generate server -f fixture-2492.yaml --target gen-binary-2492 --quiet

(cd gen-binary-2492/cmd/project-server && go build)

ls gen-binary-2492/cmd/project-server
main.go  project-server

mkdir gen-binary-2493

/usr/bin/swagger generate server -f fixture-2493.yaml --target gen-binary-2493 --quiet

(cd gen-binary-2493/cmd/server && go build)

ls gen-binary-2493/cmd/server
main.go  server
```

**Comment by ajinkyan83** [comment]
@fredbi Yes, bug seems specific to windows.

**Comment by andskur** [comment]
the same bug on macOS

**Comment by fredbi** [comment]
I've identified the root cause of this. The problem is a subtle race with various package level init() that set the spec loader.
The symptom you see is a yaml spec incorrectly loaded as json.

The work around pending the fix (probably over next week) is to convert your spec to json.

**Comment by koron** [comment]
Are you planning on creating a new release to publishing this fix?

v0.26.0 is last/latest release and it includes this problem.
It can't handle YAML files which include `$ref`.

I think that it doesn't seem healthy.

**Comment by aliakseiz** [comment]
> Are you planning on creating a new release to publishing this fix?
> 
> v0.26.0 is last/latest release and it includes this problem.
> It can't handle YAML files which include `$ref`.
> 
> I think that it doesn't seem healthy.

Can't you rollback to v0.25.0, until new release?

**Comment by koron** [comment]
I did rollback for my works already.

But I don't think it's good for go-swagger to leave a broken release.

**Comment by fredbi** [comment]
The issue affects windows and mac. That's why he  passed under the CI radar.
It is fixed now. We should proceed with a v0.26.1 indeed.

**Comment by casualjim** [comment]
I published the 0.26.1 version, you may need to run `go get -u ./...` in your own project to pick up the latest dependency versions for things like `go-openapi/loads`

**Comment by muir** [comment]
I've just installed from source:

```sh
git clone --branch v0.27.0 --depth 1 https://github.com/go-swagger/go-swagger.git
cd go-swagger
go get -u ./...
cd cmd/swagger
go install
```

Running the resulting binary on the example swagger in this ticket produces the same buggy output.

Is there some other step required to produce a working swagger binary?

**Comment by muir** [comment]
This is reproducible with the distributed docker:

```
$ docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$GOPATH -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger version
version: v0.27.0
commit: 43c2774170504d87b104e3e4d68626aac2cd447d
$ docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$GOPATH -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger validate x.api

The swagger spec at "x.api" is invalid against swagger specification 2.0.
See errors below:
- some references could not be resolved in spec. First found: invalid character 's' looking for beginning of value
- could not resolve reference in /_version to $ref : invalid character 's' looking for beginning of value
```
