### ISSUE TITLE
upgrade to version 0.26.0 introduces error `undefined: validate.WithOperationRequest` in generated code

### ISSUE THREAD

**Issue by argarner** [go-swagger/go-swagger#2498]
## Problem statement
upgrading version from 0.25.0 to 0.26.0 has introduced auto-generated code which throws an error into most operations/... /...parameters.go files

The error is generated by the addition of `validate.WithOperationRequest` into `BindRequest`, which does not appear to exist.

![image](https://user-images.githubusercontent.com/11073597/105656363-2505fa00-5f16-11eb-9f5f-4fce4942a0fc.png)

## Swagger specification
private repo and unchanged from previous versions which did not generate this erroring code

## Steps to reproduce
upgrade from v 0.25.0 to 0.26.0 and run `swagger generate server`

## Environment
swagger version: '2.0' 
go version: 1.14.4
OS: macOS Mojave 10.14.6 (18G7016)

**Comment by fredbi** [comment]
The generated code builds against a newer version of `github.com/go-openapi/validate`.
Before generating, update your libraries:
```
go get -u github.com/go-openapi/validate
```

**Comment by argarner** [comment]
Ah perfect. Thank you!
