### ISSUE TITLE
Request for more examples of code comments -> generated swagger json

### ISSUE THREAD

**Issue by serussell** [go-swagger/go-swagger#250]
@casualjim I'm having difficulty with `swagger:route` and `swagger generate spec`.  Can we get a full example where the json is generated from embedded comments, or clarification of rules on where `swagger:route` can appear?  I've tried putting it:

- outside of methods that are then added with `http.HandleFunc`
- inside methods handled by `http.HandleFunc`
- inside `main()`, above `http.HandleFunc()` calls

In no case can I get the paths & documentation to appear in generated json.  I may be missing tags, I may be putting the documentation in the wrong place; it isn't clear to me how this is supposed to work.

Thanks!

**Comment by serussell** [comment]
Sorry... this may be a duplicate of #213 .  @casualjim  I'm fine if you close this as a duplicate.

**Comment by casualjim** [comment]
I'll count this as a very strong +1 :)
