### ISSUE TITLE
Creating models crash when using $ref on an array

### ISSUE THREAD

**Issue by sonalys** [go-swagger/go-swagger#2511]
## Problem statement

When defining a response model
```
      modelName:
        type: array
        items:
          type: string
        $ref: '#/definitions/someDefinition'
```

the swagger is considered valid but the generator crashes

## Swagger specification

described above

## Steps to reproduce

1. Create the swagger.yml with the model above
2. Try create the models with `swagger generate model --spec=swagger.yml -m=./models`
3. Crash

## Environment
swagger version: v0.26.0
go version: v1.15.6
OS: Manjaro

**Comment by fredbi** [comment]
Cannot reproduce on master, using a similar env (Linux ubuntu, go1.15.7).
Tried the same command, with the specs below that reuse the model defined by the OP and a variant.
The spec provided is not formally invalid, but probably unintended. The use of `$ref` in a json schema predates all other sibling keys.
Command used:
```sh
swagger generate model --spec ${spec} --target ${target} -m="models" 
```

1. Repro attempt #1
```yaml
---
swagger: "2.0"
info:
  title: "repro issue #2511"
  version: "0.0.1"
  description: "repro issue 1537"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
definitions:
  modelName:
    type: array
    items:
      type: string
    $ref: '#/definitions/someDefinition'

  someDefinition:
    type: string
paths:
  /getRecords:
    get:
      parameters:
        - name: records
          in: body
          required: true
          schema:
            $ref: '#/definitions/modelName'
      responses:
        200:
          description: "OK"
```
Generated models:
```go
// ModelName model name
//
// swagger:model ModelName
type ModelName = SomeDefinition
...
// SomeDefinition some definition
//
// swagger:model someDefinition
type SomeDefinition string
```
2. Repro attempt #2 
```yaml
---
swagger: "2.0"
info:
  title: "repro issue #2511"
  version: "0.0.1"
  description: "repro issue 1537"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
definitions:
  modelName:
    type: array
    items:
      type: string
      $ref: '#/definitions/someDefinition'

  someDefinition:
    type: string
paths:
  /getRecords:
    get:
      parameters:
        - name: records
          in: body
          required: true
          schema:
            $ref: '#/definitions/modelName'
      responses:
        200:
          description: "OK"
```
Models generated:
```go
// ModelName model name
//
// swagger:model modelName
type ModelName []SomeDefinition
...
// SomeDefinition some definition
//
// swagger:model someDefinition
type SomeDefinition string
```

**Comment by fredbi** [comment]
@sonalys there is something else that you didn't disclose about the conditions you are running this.

Could you please disclose the full spec you are building against as well as the crash stack?
If you don't want to disclose too much information on the public github issue, you can PM this on our slack channel.

**Comment by fredbi** [comment]
OK could reproduce the panic with the full spec. This is indeed a bug in codegen
