### ISSUE TITLE
Unknown command 'markdown'

### ISSUE THREAD

**Issue by rishablal** [go-swagger/go-swagger#2517]
## Problem statement

When running the following command: `swagger generate markdown -f swagger.json --output swagger.mode`
I get the following error: `Unknown command 'markdown'. Please specify one command of: client, model, operation, server, spec or support`

## Swagger specification

any spec works to reproduce this error

## Steps to reproduce

Attempt to generate markdown by running the following command: `swagger generate markdown -f swagger.json --output swagger.mode`

## Environment
swagger version: v0.26.1
go version: v1.15.6
OS: Catalina 10.15.5

**Comment by fredbi** [comment]
The command works from v0.26.0 onwards. Are you sure you are actually running a v0.26.1 as this is mentioned above?

**Comment by rishablal** [comment]
seems like i had an older version downloaded somewhere - deleting all aliases and reinstalling go-swagger fixed this for me
