### ISSUE TITLE
Documention translate

### ISSUE THREAD

**Issue by Jeyrce** [go-swagger/go-swagger#2526]
## About i18n

Is therer any plane for i18n? I am a programmer for China and try to translate documention into Chineses these days. So  is there some team Ican join?

**Comment by casualjim** [comment]
We don't have any specific plan for this, but I think we can add this to our gitbook:

https://www.npmjs.com/package/gitbook-plugin-i18n

Then you can just fork this repository and add translations to https://github.com/go-swagger/go-swagger/tree/master/docs

**Comment by Jeyrce** [comment]
Thanks
