### ISSUE TITLE
Panic: interface is spec.Schema, not spec.Parameter for formField file

### ISSUE THREAD

**Issue by jonathaningram** [go-swagger/go-swagger#253]
First up, thanks for the great tool :)

I'm trying to figure out how to use annotations for generating my client SDK for the case when the API call expects a form file. I've tried a few things, and this particular case gives me a panic:

```
panic: interface conversion: interface is spec.Schema, not spec.Parameter
```

Note: I'm not sure if the panic is just expected behaviour, but it goes unchecked in the code so I expect not. I guess I'd like it to tell me what I'm doing wrong.

Here's the full main.go to replicate this:

```go
//go:generate swagger generate spec -o ./swagger.json

// Package main MyCompany API.
//
//     Schemes: https
//     Host: localhost
//     BasePath: /
//     Version: 0.0.1
//     License: MIT http://opensource.org/licenses/MIT
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//
// swagger:meta
package main

import (
	"bytes"
	"net/http"
)

// swagger:parameters myOperation
type MyStruct struct {
	// MyFormFile desc.
	//
	// name: file
	// in: formData
	// type: file
	MyFormFile *bytes.Buffer `json:"myFormFile"`
}

func main() {
	// swagger:route POST /api/my-op/ myOperation
	//
	//     Consumes:
	//     - multipart/form-data
	//
	//     Produces:
	//     - application/json
	//
	//     Security:
	//       api_key:
	http.HandleFunc("/api/my-op/", func(w http.ResponseWriter, r *http.Request) {

	})
}
```

And obviously just run this

```
go generate
swagger generate client
```

Instead of the `*bytes.Buffer` I've tried `*os.File` and I get this:

```
unable to resolve embedded struct for: &{280192 file}
```

and `httpkit.File` and I get this:

```
unknown primitive "File"
```

Edit: I've also tried `multipart.File` and get

```
unknown primitive "File"
```

If it helps (and if you have any thoughts on if this is possible with go-swagger!), essentially I'm trying to use annotations to replicate my call that allows *both* a JSON-encoded `body` and also a `file` form fields, equivalent of this CURL request:

```curl
curl http://localhost/api/my-op/ \
  -F file=@myfile.txt \
  -F body='{"someKey":"someVal"}'
```

**Comment by casualjim** [comment]
forthe file you can use: httpkit.File
https://github.com/go-swagger/go-swagger/blob/master/httpkit/interfaces.go#L24-L28

**Comment by jonathaningram** [comment]
@casualjim thanks for the reply. I did already try `httpkit.File` previously and just tried it again and it returns the error:

```
unknown primitive "File"
```

Would this be a bug?

I did check out the test at https://github.com/go-swagger/go-swagger/blob/328dc1bb22db726edd68fcd101220ca7813539cb/examples/generated/restapi/operations/pet/upload_file_parameters.go#L27 but if I'm correct it looks like that file is generated from the swagger.json, opposed to what I'm trying to do which is generate it from code annotations/comments.

**Comment by jonathaningram** [comment]
For the record, here's the complete running program to replicate the error when using `httpkit.File`:

```go
//go:generate swagger generate spec -o ./swagger.json

// Package main MyCompany API.
//
//     Schemes: https
//     Host: localhost
//     BasePath: /
//     Version: 0.0.1
//     License: MIT http://opensource.org/licenses/MIT
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//
// swagger:meta
package main

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

// swagger:parameters myOperation
type MyStruct struct {
	// MyFormFile desc.
	//
	// name: file
	// in: formData
	// type: file
	MyFormFile httpkit.File `json:"myFormFile"`
}

func main() {
	// swagger:route POST /api/my-op/ myOperation
	//
	//     Consumes:
	//     - multipart/form-data
	//
	//     Produces:
	//     - application/json
	//
	//     Security:
	//       api_key:
	http.HandleFunc("/api/my-op/", func(w http.ResponseWriter, r *http.Request) {

	})
}
```

**Comment by jonathaningram** [comment]
Hi @casualjim thanks for the fix. However, I have run `go get -u` and added the annotation `swagger:file` and when generating I get the error `classifier: unknown swagger annotation "file"`. Here's the full file (I copied the `MyFileParams` struct directly from your recent commit so figured it should work). Any thoughts?

```go
//go:generate swagger generate spec -o ./swagger.json

// Package main MyCompany API.
//
//     Schemes: https
//     Host: localhost
//     BasePath: /
//     Version: 0.0.1
//     License: MIT http://opensource.org/licenses/MIT
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//
// swagger:meta
package main

import (
	"bytes"
	"net/http"
)

// MyFileParams contains the uploaded file data
// swagger:parameters myOperation
type MyFileParams struct {
	// MyFormFile desc.
	//
	// in: formData
	//
	// swagger:file
	MyFormFile *bytes.Buffer `json:"myFormFile"`
}

func main() {
	// swagger:route POST /api/my-op/ myOperation
	//
	//     Consumes:
	//     - multipart/form-data
	//
	//     Produces:
	//     - application/json
	//
	//     Security:
	//       api_key:
	http.HandleFunc("/api/my-op/", func(w http.ResponseWriter, r *http.Request) {

	})
}
```

**Comment by casualjim** [comment]
when you say you did `go get -u` do you mean you did `go get -u github.com/go-swagger/go-swagger/cmd/...`

Another thing I can offer to try is to rebuild with the '-a' flag so that it rebuilds all packages in use.

**Comment by jonathaningram** [comment]
@casualjim ah thanks, my bad, rookie mistake. I forgot that this was using a `swagger` command opposed to just `import`ing it in my own code so I needed to make sure the swagger command was rebuilt. Sorry for the noise and thanks again for the fix.
