### ISSUE TITLE
Nested references in definitions cause failure

### ISSUE THREAD

**Issue by jchenry** [go-swagger/go-swagger#254]
when you specify nested references in definitions, example: https://gist.github.com/jchenry/cfe3ae069dfeb5a8155d

swagger errors with the following message: 

> The swagger spec at "parent-child.yml" is invalid against swagger specification 2.0. see errors :
> - object has no field "definitions"

this documents validated properly in other swagger/OpenAPI validators like: 
http://bigstickcarpet.com/swagger-parser/www/index.html

**Comment by jchenry** [comment]
This manifests itself on go1.6rc2

**Comment by casualjim** [comment]
I still have a bunch of serialization errors when I try against the latest 1.6 container.

I did update my loader tool which was missing some method for version 1.6
