### ISSUE TITLE
missing import: model not compiling

### ISSUE THREAD

**Issue by baracoder** [go-swagger/go-swagger#255]
Hello,

I have generated code from a spec.
While compiling i get an error
```
go install ./cmd/ini-goapi-server                                                                                   :(
# ini-goapi/models
models/file.go:34: undefined: strfmt
models/hit.go:26: undefined: strfmt
models/member.go:18: undefined: strfmt
```

Example model file content:
```
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*File File file

swagger:model File
*/
type File struct {

	/* text content of the file, if availible
	 */
	Content *string `json:"content,omitempty"`

	/* DownloadLink download link
	 */
	DownloadLink *string `json:"downloadLink,omitempty"`

	/* Mime mime
	 */
	Mime *string `json:"mime,omitempty"`

	/* Name name
	 */
	Name *string `json:"name,omitempty"`

	/* size in bytes
	 */
	Size *string `json:"size,omitempty"`
}

// Validate validates this file
func (m *File) Validate(formats strfmt.Registry) error {
	return nil
}

```

go version go1.4.2 linux/amd64

**Comment by casualjim** [comment]
Would it be possible for you to try with go1.5? 

swagger uses GO15VENDOREXPERIMENT and I think it might not be able to find strfmt which is why it's not

**Comment by BlueDragonX** [comment]
I'm having the same issue with the static 0.3.0 binary. The generated files which have this error simply doesn't have an import statement for strfmt.

**Comment by casualjim** [comment]
I'll publish new binaries tonight but you do need go-swagger in your GOPATH for this to work out.

**Comment by BlueDragonX** [comment]
Meaning you should go get go-swagger prior to calling swagger generate?

How is it that this affects swagger's ability to generate the correct import statement? Other models are generated with the correct imports.

**Comment by casualjim** [comment]
@BlueDragonX go-swagger makes use of goimports to reformat and get the imports for the generated files.  Part of that is optimizing the imports and to discover them properly it wants for them to be in the $GOPATH so goimports can discover them.

Anyway for strfmt in particular I've aliased them now which will hopefully keep them

**Comment by BlueDragonX** [comment]
Thanks, I appreciate the explanation!
