### ISSUE TITLE
Installing go-swagger as Debian packages fails

### ISSUE THREAD

**Issue by reiman2222** [go-swagger/go-swagger#2558]
## Problem statement

Installing go-swagger as Debian packages fails

## Steps to reproduce

install go-swagger with:
```
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
echo "deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main" | tee /etc/apt/sources.list.d/goswagger.list
apt update
apt-get install swagger
```

Fails with error: 
```
E: Failed to fetch https://dl.bintray.com/go-swagger/goswagger-debian/dists/ubuntu/InRelease  403  Forbidden
E: The repository 'https://dl.bintray.com/go-swagger/goswagger-debian ubuntu InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by dmlyons** [comment]
Bintray is deprecated and has gone away: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by casualjim** [comment]
we'll publish the next release to github packages

This should be this weekend

**Comment by reiman2222** [comment]
For anyone else facing this issue I worked around it by installing the binary directly from `https://github.com/go-swagger/go-swagger/releases/download/v0.27.0/swagger_linux_amd64`

**Comment by vidhill** [comment]
> we'll publish the next release to github packages
> 
> This should be this weekend

Having the same issue, did this get published to github packages, 

if so what is the new install process?

**Comment by DylanSpOddball** [comment]
Ran into the same issue. Can the installation instructions please be updated?

**Comment by casualjim** [comment]
This is fixed now:

https://github.com/go-swagger/go-swagger/blob/master/docs/install.md#debian-packages-

**Comment by swaingotnochill** [comment]
Hi Team,
It seems the debian package again fails to install swagger.

```
W: GPG error: https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F8CB673971B5C9E
E: The repository 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease' is not signed.

```

System : Ubuntu 22.04 LTS
Codename: jammy

**Comment by ariefsn** [comment]
hi @swaingotnochill 
any updates?
happened to me too

**Comment by overoneio** [comment]
Hi! Got same error: 
```
Err:8 https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F8CB673971B5C9E
Hit:14 https://repo.radeon.com/rocm/apt/4.5.1 ubuntu InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'
W: GPG error: https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F8CB673971B5C9E
E: The repository 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease' is not signed.
```

**Comment by Parthiba-Hazra** [comment]
try download debian package directly and install it. It works for me.

**Comment by pablolagosm** [comment]
This works:
````````` curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/cfg/setup/bash.deb.sh' |  sudo distro=debian codename=any-version bash````

**Comment by pablolagosm** [comment]
This command works:

```
curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/cfg/setup/bash.deb.sh' |  sudo distro=debian codename=any-version bash
```
