### ISSUE TITLE
Cannot install directly from github

### ISSUE THREAD

**Issue by chamini2** [go-swagger/go-swagger#2560]
## Problem statement

It seems that the github installation is not working. I have tried other method of installation but since this installs INSIDE a docker container, I do not know how to get it.

## Steps to reproduce

```
$ go get -u github.com/go-swagger/go-swagger/cmd/swagger
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/Users/redacted/.go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```

## Environment
swagger version: x.x.x  
go version: 
```
go version
go version go1.13.4 darwin/amd64
```
OS: macOS 11.1

**Comment by youyuanwu** [comment]
I ran this `$ go get -u github.com/go-swagger/go-swagger/cmd/swagger` and it successfully installed it. 
Can you show output of `go env` command?
The other way to install is to download from release. See: https://github.com/go-swagger/go-swagger/issues/2558#issuecomment-817949595

**Comment by chamini2** [comment]
some time ago there was a `hcl` dir in the hashicorp/hcl repo: https://github.com/hashicorp/hcl/tree/819a65acc453ba35681e287fa31f5f0bb084ddb9/hcl
but it's not there anymore.

**Comment by casualjim** [comment]
you can install easier like this: ```go get github.com/go-swagger/go-swagger/cmd/swagger@latest```

It makes use of go modules and so will use the dependency versions we built and tested against

**Comment by youyuanwu** [comment]
In your go env output there is no:
```
GO111MODULE="on"
```
You should export it in your environment.
Try
```
$ GO111MODULE="on" go get -u github.com/go-swagger/go-swagger/cmd/swagger
```
Or as suggested above
```
$ GO111MODULE="on" go get github.com/go-swagger/go-swagger/cmd/swagger@latest
```
Or to get latest release
```
$ GO111MODULE="on" go get github.com/go-swagger/go-swagger/cmd/swagger@v0.27.0
```

**Comment by chamini2** [comment]
Thanks for the possible solutions. I am no longer working on this but did not want to leave the issue open. It's probably the `GO111MODULE` variable.
