### ISSUE TITLE
Integration with viper

### ISSUE THREAD

**Issue by robotoer** [go-swagger/go-swagger#2572]
## Problem statement

Hi go-swagger team! We're trying to use `go-swagger` with `viper` to write a command line tool and api server but we can't figure out how to pass custom data (such as a `viper` object) into a generated `go-swagger` server. Ideally we would be able to pass additional custom parameters into the `configureAPI` function. Is there some other mechanism for threading data through to `configureAPI(...)` from the program's main entry point?

More specifically we want to be able to use the result of calling:
```
someCustomConfig := &config.MyConfig{}
myViperInstance.Unmarshal(someCustomConfig)
```
inside of `configureAPI` where `myViperInstance` must be constructed in our main.

**Comment by youyuanwu** [comment]
viper instance can be a pkg level variable, and can be used in configureAPI().
Or create viper instance inside configureAPI() function.

I don't think you can pass additional params to configureAPI().
Note generated code has better integration with https://github.com/jessevdk/go-flags, see https://github.com/go-swagger/go-swagger/blob/b49f50b58d021e303ce819ab8310add9bad3a99d/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go#L29

**Comment by robotoer** [comment]
Ah, I see. Thanks for the help!
