### ISSUE TITLE
Is there good to way to omit readonly key

### ISSUE THREAD

**Issue by zhsj** [go-swagger/go-swagger#2581]
## Problem statement

Since go-swagger can validate readonly key, API calls with readonly key will fail. However I want to make the frontend life much easier. So I want the server to just omit readonly key when receive POST/PUT request, instead of modify our swagger definition to drop the readonly key.

Is there easy way to achieve this?

## Swagger specification

2. 0 

## Environment
swagger version: 0.26.0
go version: 1.16
OS:  linux

**Comment by youyuanwu** [comment]
If you want to erase readonly field in request payload, there is no easy way.

If you want to ignore readonly validation, you need to remove the context here:
https://github.com/go-swagger/go-swagger/blob/b49f50b58d021e303ce819ab8310add9bad3a99d/examples/auto-configure/restapi/operations/todos/add_one_parameters.go#L63

You can use custom template to do so for all endpoints.

**Comment by zhsj** [comment]
> If you want to erase readonly field in request payload, there is no easy way.

Yeah, that's my intention. And thanks for confirming what I have tried :cry:
