### ISSUE TITLE
Try it out problem with scheme http behind nginx-ingress with tls

### ISSUE THREAD

**Issue by beorereleverion** [go-swagger/go-swagger#2585]
## Problem statement
cannot use http scheme behind nginx-ingress with tls
## Swagger specification
---
swagger: "2.0"
info:
  description: test service
  title: Service
  version: 0.1.1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
...
## Steps to reproduce
1. setup swagger to use http scheme
2. Create deployment.service and ingres for this
3. in ingress i point tls secrets for host
4. when i push try it out i have "http" curl request with 308 code
## Environment
kubernetes 1.20

**Comment by beorereleverion** [comment]
ADD: With https scheme go-swagger want to create tls connection with key,cert. But this does not needed behind nginx-ingress

**Comment by fredbi** [comment]
This issue is totally unrelated to go-swagger.
And without any k8s manifest to see how the ingress is configured, there is no way to figure out what's wrong with your configuration.
