### ISSUE TITLE
Generated client code prints a pointer in Error() func

### ISSUE THREAD

**Issue by sergerad** [go-swagger/go-swagger#2590]
## Problem statement

Generated code tries to print a pointer instead of printing the value pointed to.

Client code generated via:
```
docker run --rm -it -u $(shell id -u):$(shell id -u) -e GOPATH=$(GOPATH):/go -v $(HOME):$(HOME) -w $(shell pwd) quay.io/goswagger/swagger:v0.27.0 generate client --name abc -f ./api/swagger.yaml
```
Example of generated client code in `*_responses.go`:
```
type CreateConflict struct {
	Payload *models.Error
}

func (o *CreateConflict) Error() string {
	return fmt.Sprintf("[POST /abc][%d] createConflict  %+v", 409, o.Payload)
}
```

## Swagger specification

Relevant sections:
```
swagger: "2.0"
...
paths:
  /abc:
    post:
      tags:
        - "abc"
      summary: "Create a new ABC"
      description: ""
      operationId: "create"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "abc"
          required: true
          schema:
            $ref: "#/definitions/abc"
      responses:
        202:
          description: "Accepted"
          schema:
            $ref: '#/definitions/abc'
        400:
          $ref: '#/responses/BadRequest'
        404:
          $ref: '#/responses/NotFound'
        409:
          $ref: '#/responses/Conflict'
        500:
          $ref: '#/responses/InternalError'
...
definitions:
  Error:
    type: "object"
    properties:
      message:
        type: string
        x-nullable: false
        minLength: 1
    required:
      - message
responses:
  Unauthorized:
    description: "Unauthorized"
    schema:
      $ref: '#/definitions/Error'
  NotFound:
    description: "Not found"
    schema:
      $ref: '#/definitions/Error'
  InternalError:
    description: "Inernal Server Error"
    schema:
      $ref: '#/definitions/Error'
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: '#/definitions/Error'
  Conflict:
    description: "Conflict"
    schema:
      $ref: '#/definitions/Error'
```

## Environment
swagger version: quay.io/goswagger/swagger:v0.27.0 and 0.24.0 tested
go version: 1.15
OS: MacOS 11.3

**Comment by youyuanwu** [comment]
I have encountered this before. 
One way to fix this is to check when o.Payload is not nil, then dereference it in the error string fprint.
But if the error struct has field of pointer type, dereferencing will still render some fields as addresses. 
The other way is to do a json dump.

**Comment by stephenpmurray** [comment]
Noticing the same issue; Errors returned by my client code are formatted as a hex address. For example:
```
error [POST /render][500] Render default &{Code:500 Message:0xc0000320d0}
```
Since this makes any errors returned by my client code unusable without editing the autogenerated code, can we consider this a bug?

**Comment by youyuanwu** [comment]
Std fprintf does not support recursively print struct. There are many ways to go:
* fprint struct after dereference, but it will only give one level of more information.
* print struct after using json marshal. Then there are quotes around all strings.
* Implement custom printing functions or using third party lib.
 
Maybe json marshal is the right way?

**Comment by stephenpmurray** [comment]
In both our cases it's straightforward to just dereference the pointers, since the struct has a depth of 2. However, this could be otherwise.

I think marshalling is the way to go. Shall I open a PR?

**Comment by youyuanwu** [comment]
Yes, PR is welcomed. You also need to think about if payload is not json: it can be bytes, string or int ,etc.

**Comment by marmiha** [comment]
I have the same problem. Is the pointer always present or does this occur only with the supplied example?

**Comment by fredbi** [comment]
@youyuanwu here is a proposal to achieve what is suggested above: #3019
