### ISSUE TITLE
How can I get rid of the extra information when a yaml file is uploaded

### ISSUE THREAD

**Issue by sayantan1413** [go-swagger/go-swagger#2615]
## Problem statement

I am trying to upload a yaml file but I get some unwanted data 
<img width="1440" alt="Screenshot 2021-07-31 at 12 30 11 AM" src="https://user-images.githubusercontent.com/64970095/127700183-9a37bbea-ecc4-470e-bae8-980c8db650d3.png">
I want to remove the highlighted part and only want to get the content of the yaml file so how can do this?

In my doc.go I have 
<pre>
//     Consumes:
//     - multipart/form-data
//     - application/json
</pre>
<pre>
// Parameters for uploading a yaml file
// swagger:parameters idPostDeployApplicationFile idPostDeployPattern
type applicationFileParamsWrapper struct {
	//The uploaded file data
	// in: formData
	//
	// swagger:file
	FormFile *bytes.Buffer `json:"Upload File"`
}
</pre>

## Swagger specification
Swagger 2.0

**Comment by fredbi** [comment]
The OP uses go-swagger to generate the spec. The issue lies with the implementation of the upload handler in this API, not in  upload code generated by go-swagger. Closing as (mostly) unrelated to what we do and what we may help with.
