### ISSUE TITLE
"github.com/go-openapi/errors".CompositeError has no field or method ValidateName

### ISSUE THREAD

**Issue by dimovnike** [go-swagger/go-swagger#2623]
After upgrading to the new feature "support nested body params for CompositeError" from master (166b85358) the generated code produces the following error:

"github.com/go-openapi/errors".CompositeError has no field or method ValidateName

I have run `go get -u -f ./...` and also checked that github.com/go-openapi/errors is the latest version.

The problematic code is the following:

```
        if m.Field != nil {
		if err := m.Field.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("field")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("field") // <- ERROR HERE
			}
			return err
		}
	}
```

The type `*errors.CompositeError` has no `ValidateName()` method.

**Comment by dimovnike** [comment]
NOTE: this happens when an existing project is regenerated with the new swagger.

**Comment by youyuanwu** [comment]
Seems like this PR is not merged in errors pkg: https://github.com/go-openapi/errors/pull/32
@casualjim 

If we do not merge the above PR, this https://github.com/go-swagger/go-swagger/pull/2595 needs to be reverted?

**Comment by casualjim** [comment]
I merged in the other repo now and added a tag for it

**Comment by dimovnike** [comment]
It works now. Thanks.

**Comment by dimovnike** [comment]
one related question:

I see that these composite errors are stripped down to the first error in response:

```golang
case *CompositeError:
		er := flattenComposite(e)
		// strips composite errors to first element only
		if len(er.Errors) > 0 {
			ServeError(rw, r, er.Errors[0])
		} else {
			// guard against empty CompositeError (invalid construct)
			ServeError(rw, r, nil)
		}
```

What is the correct way to have all errors in the response? Is there a better way than using a custom api.ServeError func?

**Comment by chrisharrisonkiwi** [comment]
Still seeing the error, is that tagged version going to be making it into master anytime soon?

**Comment by youyuanwu** [comment]
Change errors pkg dependency to "github.com/go-openapi/errors v0.20.1" or above should resolve the compiler error.
