### ISSUE TITLE
Log-output is not working for validate command

### ISSUE THREAD

**Issue by katexochen** [go-swagger/go-swagger#2631]
## Problem statement

I am trying to get the output of a validation written into a log file.

The [documentation of `validate` states](https://goswagger.io/usage/serve_ui.html#usage):

> Application Options:
>   -q, --quiet                 silence logs
>       --output=LOG-FILE       redirect logs to file

But this does not seem to be a valid flag anymore:

```
$ swagger --output=logfile validate swagger.json
unknown flag `output'
```
The flag name seem to have changed to [`--log-output`](https://github.com/go-swagger/go-swagger/blob/v0.27.0/cmd/swagger/swagger.go#L29)

So I've tried to use this option, and while a file with the right name is created, it is always empty, and the output is still printed out on the console.

```
$ swagger --log-output=logfile validate swagger.json

The swagger spec at "swagger.json" is invalid against swagger specification 2.0.
See errors below:
- some references could not be resolved in spec. First found: object has no key "UserSecret"
- could not resolve reference in "/secrets".POST to $ref : object has no key "UserSecret"

$ cat logfile
$ 
```
How can I get the output written to a file?

## Environment
swagger version: 0.27.0
go version: 1.15.15
OS: Ubuntu 20.04

**Comment by casualjim** [comment]
you can use the regular shell redirection.

```bash
$ swagger validate swagger.json 2>./logfile
```

**Comment by katexochen** [comment]
Thanks, this does the job. :+1:
