### ISSUE TITLE
DELETE method without body

### ISSUE THREAD

**Issue by manell** [go-swagger/go-swagger#264]
Hi, 

I'm having some problems trying to use the DELETE operation without a body (DELETE /item/{id}).
First of all, let me say that I'm not sure if requests like DELETE /item/{id} without a body must have their header Content-Type set or not. So in the end, I found myself trying both cases.

##### Without Content-Type
If I decide not to define a content type, the swagger spec will be something like this:
```yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'Test'
schemes:
  - http
paths:
  /key/{id}:
    delete:
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: OK
```
I created the server and executed:
```curl -X "DELETE" http://127.0.0.1:36128/key/1```

Which gave me the following error: 
``` {"code":415,"message":"unsupported media type \"application/octet-stream\", only [] are allowed"} ```
Digging into the code I've found that if no content type is set, it defaults to "application/octet-stream". [https://github.com/go-swagger/go-swagger/blob/master/httpkit/headers.go#L29](https://github.com/go-swagger/go-swagger/blob/master/httpkit/headers.go#L29)
So it seems that the Content-Type is required.

##### With Content-Type
The swagger looks like: 
```yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'Test'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /key/{id}:
    delete:
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: OK
```

The curl command :
```
curl -X "DELETE" -H "Content-Type: application/json" http://127.0.0.1:36128/key/1
```
Works well.

But when I try to use the generated client I fall back to the previous case when no content type is set.
I feel that this is relateded with [https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/request.go#L152](https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/request.go#L152), where the content type only is being sent if there is a payload. 
Maybe this is related to #238.

Probably I missed something, but if someone can help me on this.

Thanks.

**Comment by casualjim** [comment]
closed by linked PR with bad comment
