### ISSUE TITLE
The CLI should return a JSON output rather than objects

### ISSUE THREAD

**Issue by bharatmicrosystems** [go-swagger/go-swagger#2640]
## Problem statement
Currently, when we hit an endpoint using the tool, complex types are displayed as maps or lists (based on what is returned), and when they are printed it is not parsable. I

For example, if the server returns `{"foo": "bar"}` the following output is displayed
`map[foo:bar]`

It is possible to add a command-line flag to change the outputs to custom formats such as JSON and/or YAML. The default output should ideally be tabular, but we can live with the current one if we have the JSON/YAML option in place.

**Comment by youyuanwu** [comment]
CLI should print json by default. Can you give a sample spec for us to reproduce?

**Comment by bharatmicrosystems** [comment]
The issue was with the older release. I built from master and the issue is
no longer there. Thanks
