### ISSUE TITLE
Is it possible to the order in which the APIs are shown in swagger

### ISSUE THREAD

**Issue by ArulJeyananth** [go-swagger/go-swagger#2646]
## Problem statement
Is it possible to the order in which the APIs are shown in swagger?
seems currently it is shown in ascending order . (
assume I have 2 APIs as below
   user/domagic
   user/buy

Currently it appears in swagger as the following order
   user/buy
   user/domagic
I changed the order in which it appears in docs.go,swagger.json & swagger.yaml
still it is shown in ascending order
Please remove the sections that don't apply

	github.com/swaggo/gin-swagger v1.3.2
	github.com/swaggo/swag v1.7.3 

swagger version: x.x.x  
go version:  1.16
OS:

**Comment by casualjim** [comment]
you probably want to submit this at https://github.com/swaggo/swag
