### ISSUE TITLE
Generate client code call a NOT exist method

### ISSUE THREAD

**Issue by ymping** [go-swagger/go-swagger#2648]
## Problem statement

Generate golang client for [Harbor](https://github.com/goharbor/harbor), call a not exist method on struct.

The output log show a warning message : `warning: schema for additional properties in schema "ResourceList" is empty. skipped` .

Short example, `Used` / `Hard` member of struct `ProjectSummaryQuota` has no method named `ContextValidate` called in function `contextValidateUsed `:
```golang
package models

import (
	"context"
	"github.com/go-openapi/strfmt"
	"github.com/goharbor/harbor/src/pkg/quota/types"
)

type ProjectSummaryQuota struct {

	// The hard limits of the quota
	Hard types.ResourceList `json:"hard,omitempty"`

	// The used status of the quota
	Used types.ResourceList `json:"used,omitempty"`
}

func (m *ProjectSummaryQuota) contextValidateUsed(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Used.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("used")
		}
		return err
	}

	return nil
}
```

## Steps to reproduce
```bash
~$  mkdir debug && cd debug
~$  go mod init harbor
~$  wget https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml
~$  swagger generate client -f ./swagger.yaml
```
problem can be found in file `./models/project_summary_quota.go`

## Environment
swagger version: v0.27.0
go version: go1.16.4 darwin/amd64
OS:   macOS Big Sur 11.6

**Comment by mykter** [comment]
What should ContextValidate actually do? What should it be checking that is different to Validate?

**Comment by casualjim** [comment]
it has an extra argument `context.Context` in the method signature which can be handy for some things

**Comment by youyuanwu** [comment]
ContextValidate is intended to implement checking for swagger properties marked as ReadOnly. See this for details: https://github.com/go-swagger/go-swagger/pull/2369

**Comment by mykter** [comment]
OK, so if we have no additional validation to do beyond what Validate is doing, we should just return nil? Or will only one of Validate or ContextValidate be called, so ContextValidate should itself call Validate?

**Comment by casualjim** [comment]
if you have no read only properties in your model you can just return nil afaict

See this model definition: https://github.com/go-swagger/go-swagger/blob/master/examples/task-tracker/swagger.yml#L457-L525
And this generated code: https://github.com/go-swagger/go-swagger/blob/master/examples/task-tracker/models/task.go#L450-L551
