### ISSUE TITLE
Installation instructions are not up-to-date

### ISSUE THREAD

**Issue by henrikac** [go-swagger/go-swagger#2664]
I was installing `go-swagger` today and I used the following instructions from [goswagger.io](https://goswagger.io/install.html#installing-from-source)
```
dir=$(mktemp -d)
git clone https://github.com/go-swagger/go-swagger "$dir" 
cd "$dir"
go checkout v0.25.0
go install -ldflags "-X github.com/go-swagger/go-swagger/cmd/swagger/commands.Version=$(git describe --tags) -X github.com/go-swagger/go-swagger/cmd/swagger/commands.Commit=$(git rev-parse HEAD)" ./cmd/swagger
```
I noticed it says `go checkout v0.25.0` instead of `git checkout ...`. This typo has already been fixed in `docs/install.md` ~8 months ago but for some reason the fix has not reached the website.

**Comment by fredbi** [comment]
Install instructions have been updated and this is now published.
#3088
