### ISSUE TITLE
How to read body in handler? (using params cause fields to be re-ordered)

### ISSUE THREAD

**Issue by khanzadimahdi** [go-swagger/go-swagger#2665]
## Problem statement
I have an endpoint in my API which will be called using a webhook.
webhook **signs** the request and then my API must verify at first. but **go-swagger converts the body to object and it can cause
request json fields re-ordered**, so the verification of sign will be failed because the received request is not equal to actual one.

**how can I read the raw body of request in my handler?** I have tried to access `params.HTTPRequest.Body` , however it says body is closed and panics.

## Environment
swagger version: v0.27.0
go version: 1.17.01
OS:  ubuntu20.04

**Comment by youyuanwu** [comment]
For go-swagger generated server you can potentially process the body in middleware layer, before serialization happends: https://github.com/go-swagger/go-swagger/blob/92bf85b294bd1331b09753d7f5a1c47bb6449ddc/examples/todo-list/restapi/configure_todo_list.go#L105

**Comment by khanzadimahdi** [comment]
It would be great if there were an option in the swagger file to let us transfer the whole request body to our handlers.
