### ISSUE TITLE
"Equivalent paths are not allowed" error not detected using swagger validate

### ISSUE THREAD

**Issue by craigpastro** [go-swagger/go-swagger#2694]
## Problem statement

If I paste the following spec in https://editor.swagger.io/:

```
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
basePath: "/v2"
paths:
  /pet/{pet_Id}:
    post:
      tags:
      - "pet"
      operationId: "getPetById"
      parameters:
      - in: "path"
        name: "pet_Id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
  /pet/{petId}:
    get:
      tags:
      - "pet"
      operationId: "getPetByAnId"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
```
I get an error:
```
Semantic error at paths./pet/{petId}
Equivalent paths are not allowed.
Jump to line 20
```
However, if I try to validate it using `swaager` I get
```
$ swagger validate broken.yaml
2022/01/12 17:25:42
The swagger spec at "broken.yaml" is valid against swagger specification 2.0
```

Should I expect to get the same error? Thank you!

## Steps to reproduce

As above

## Environment
swagger version: 2.0
go version: go1.17.5 darwin/amd64  
OS: mac

**Comment by casualjim** [comment]
it's an error we can't really detect because we use a map to represent this spec. given that the methods are different we wouldn't even notice that this

**Comment by craigpastro** [comment]
Hi @casualjim, and thanks for the response! I am sure I fully understand the details, but there it is. For what it is worth sending the same spec to validator.swagger.io also doesn't report the error, although editor.swagger.io does. 🤷 

Thanks again!
