### ISSUE TITLE
import package issue

### ISSUE THREAD

**Issue by midoblgsm** [go-swagger/go-swagger#27]
The generated code is still referring to casualjim repository:
 ```go
   "github.com/casualjim/go-swagger"
    "github.com/casualjim/go-swagger/middleware"
    "github.com/casualjim/go-swagger/spec"
    "github.com/casualjim/go-swagger/strfmt"
```

Moreover, the middleware package is actually under github.com/casualjim/go-swagger/middleware/httpkit/middleware.

In some other imports there is a reference to validation package
```go
"github.com/casualjim/go-swagger/validation"
```
I guess that it should refer to validate package?

Could you please point me to the right place in the code so I can update it. I would be happy to contribute and help.

**Comment by casualjim** [comment]
I thnk they moved here: https://github.com/go-swagger/go-swagger/tree/master/httpkit/validate

**Comment by casualjim** [comment]
you could also try to pull in the templates for this from the gen-client branch. i fixed those things on there and the templates for the server shouldn't have changed.

**Comment by midoblgsm** [comment]
Having the same issues even by modifying the templates. Could it be that the generator is referring to external templates? Because even when I removed the templates completely, the server was generated with the wrong package paths.

**Comment by casualjim** [comment]
try running `go generate ./generator`  that should update the embedded templates.
Sorry don't have any docs about this stuff yet

**Comment by midoblgsm** [comment]
Thanks, this was helpful!

**Comment by chakrit** [comment]
@casualjim ^ did that for you : )

**Comment by chakrit** [comment]
Tagged operations still have `casualjim` in there tho. I am not sure where that came from.
