### ISSUE TITLE
New lines in description create incorrect markdown

### ISSUE THREAD

**Issue by alexec** [go-swagger/go-swagger#2700]
## Problem statement

Converting a swagger.yaml file to swagger.md create incorrect markdown, because the new lines are not remove/escaped (or what ever is needed).

https://github.com/argoproj/argo-workflows/issues/7615

## Environment
swagger version: v0.29.0
go version: 1.17
OS:   MacOS

**Comment by fredbi** [comment]
Rewriting new lines with </br> seems to be a popular markdown tip:

Filesystem type of the volume that you want to mount.</br></br>Tip: Ensure that the filesystem type is supported by the host operating system.</br>Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.</br>More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore

Using block quote alters the rendering, so this is probably not what we want.

> Filesystem type of the volume that you want to mount.
Tip: Ensure that the filesystem type is supported by the host operating system.
Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore

**Comment by fredbi** [comment]
Provided example would render like so:

**Properties**

| Name | Type | Go type | Required | Default | Description | Example |
|------|------|---------|:--------:| ------- |-------------|---------|
| fsType | [interface{}](#interface)| `interface{}` |  | | Filesystem type of the volume that you want to mount.</br>Tip: Ensure that the filesystem type is supported by the host operating system.</br>Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.</br>More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore</br></br>TODO: how do we prevent errors in the filesystem from compromising the machine |  |
