### ISSUE TITLE
Call for transparent HTTP status codes in generated struct

### ISSUE THREAD

**Issue by au-phiware** [go-swagger/go-swagger#2706]
## Problem statement

Seeking guidance.  Say various responses are modelled by the swagger spec (see below) and there are many such endpoints and all I want do to is to categorise them by server errors or client errors.  The HTTP spec makes this easy: server errors have status codes 500-599; and client errors have status codes 400-499.  The generated response structs (e.g. GetBadRequest, GetTooManyRequests, GetInternalServerError, etc.) hide or obfuscate the HTTP status code and I am reduced to using a priori knowledge to compute the distinction.  E.g.

```
func IsClientError(err error) bool {
	switch err := p.cause.(type) {
	case
		*operations.GetBadRequest,
		*operations.GetTooManyRequests,
		*operations.PostBadRequest,
		*operations.PostTooManyRequests,
		*operations.EtcBadRequest,
		*operations.EtcTooManyRequests:
		return true
	case *runtime.APIError:
		return err.Code >= 400 && err.Code < 500
	}
	return false
}
```

I'm aware that [APIError](https://pkg.go.dev/github.com/go-openapi/runtime#APIError) has a Code field.  But what I'm seeking is a common interface across all HTTP error values that might be produced by generated client operation interfaces.  E.g.

```
type HTTPResponse interface {
	StatusMessage() string
	StatusCode()    int
}
```

I realise this may be a can of worms... but it's very difficult to maintain functions such as the above IsClientError.  I wasn't able to find anything that converts, say, *operations.GetBadRequest to *runtime.APIError.  I do see that a const is generated:

```
// GetBadRequestCode is the HTTP code returned for type GetBadRequest
const GetBadRequestCode int = 400
```

But I don't see how that improves the situation.

Is this a common scenario?  Am I missing a trick?

## Swagger specification

```
paths:
  /:
    get:
      operationId: Get
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
```

## Environment
swagger version: v0.25.0
go version: 1.17.5

**Comment by pwmcintyre** [comment]
To add a tangible example ...

If I want to distinguish between "retryable" responses and "non-retryable" responses, a simple way to do that is:
- 4xx : non-retryable
- 5xx : retryable

And this is a future-proof implementation since I don't have to react to any API changes

But there's no trivial way to do that when the underlying HTTP code is obscured

**Comment by casualjim** [comment]
I think this a valid ask.

**Comment by casualjim** [comment]
I've added the same method sets to runtime.APIError and the generated responses. There is also a convenience interface `runtime.ClientResponseStatus` to runtime 

```go

// IsSuccess returns true when this elapse o k response returns a 2xx status code
func (o *APIError) IsSuccess() bool {
	return o.Code/100 == 2
}

// IsRedirect returns true when this elapse o k response returns a 3xx status code
func (o *APIError) IsRedirect() bool {
	return o.Code/100 == 3
}

// IsClientError returns true when this elapse o k response returns a 4xx status code
func (o *APIError) IsClientError() bool {
	return o.Code/100 == 4
}

// IsServerError returns true when this elapse o k response returns a 5xx status code
func (o *APIError) IsServerError() bool {
	return o.Code/100 == 5
}

// IsCode returns true when this elapse o k response returns a 4xx status code
func (o *APIError) IsCode(code int) bool {
	return o.Code == code
}

```

So you should be able to use it as:

```go
func IsClientError(err error) bool {
	if rerr, ok := err.(runtime.ClientResponseStatus); ok {
            return rerr.IsClientError() 
        }
	return false
}
```

**Comment by pwmcintyre** [comment]
Thanks @casualjim , this should be very useful ... I look forward to trying it out

FYI, maybe a comment typo here
https://github.com/go-swagger/go-swagger/pull/2708#discussion_r800114993
