### ISSUE TITLE
Documentation missing for parameters section in swagger:route

### ISSUE THREAD

**Issue by NANASHI0X74** [go-swagger/go-swagger#2719]
## Problem statement

Seemingly it's possible to specify parameters in a swagger:route annotation, the feature was added in this PR: https://github.com/go-swagger/go-swagger/pull/1405/files

The documentation makes no mention that this is possible though. Could you document this feature?

**Comment by casualjim** [comment]
If you want to go that way, you're better off using swagger:route and putting the yaml directly in there. 

https://goswagger.io/use/spec/route.html

**Comment by rodrigc** [comment]
I submitted a patch for the documentation here: https://github.com/go-swagger/go-swagger.github.io/pull/13

**Comment by fredbi** [comment]
Made sure the aforementioned patch is indeed published.
