### ISSUE TITLE
@Failure, @Success Response Type Usage Error

### ISSUE THREAD

**Issue by RyanBreathings** [go-swagger/go-swagger#2722]
I am going to use the structure type for the private module as the response type for @Sucess, @Failure.
However, ParseCommentError in... A cannot find type definition error message occurs.

Can't I use the structure type for the private module as a response type?
Please tell me the solution.

**Comment by casualjim** [comment]
I think this is for a different project. This method does not exist and we don't use @- syntax for our attributes
