### ISSUE TITLE
How can I import from a yaml file

### ISSUE THREAD

**Issue by delgec** [go-swagger/go-swagger#2729]
Hello everyone

I just want to import a yaml file for UI. I tryed but I got an error.

How can I make it?

Thanks

```
	e := echo.New()
	e.Use(middleware.Static("/static"))
	url := echoSwagger.URL("static/openapi.yaml")
	e.GET("/swagger/*", echoSwagger.EchoWrapHandler(url))
```

**Output Screenshot:**

![Screenshot from 2022-02-23 12-28-21](https://user-images.githubusercontent.com/61455673/155292220-72debeb9-d40e-4756-a953-79b3606c5119.png)

**Comment by casualjim** [comment]
I think this is a question for https://github.com/labstack/echo
