### ISSUE TITLE
swagger generate client returns `info.title in body is required`

### ISSUE THREAD

**Issue by oleksiivelychko** [go-swagger/go-swagger#2739]
I've successfully generated swagger.yaml as:
`swagger generate spec -o ./swagger.yaml --scan-models`

... and then I tried to generate client using:
`swagger generate client`

where I got next error:
```
2022/03/14 18:46:03 validating spec /Users/alex/GitHub/go-microservice/swagger.yaml
The swagger spec at "/Users/alex/GitHub/go-microservice/swagger.yaml" is invalid against swagger specification 2.0. see errors :
- info.title in body is required
```

How can I investigate that error? or what kind of that error? or where I did mistake?

## Environment
swagger version: v0.29.0
go version: go1.17.6 darwin/arm64
OS:  MacOS 12.2.1

**Comment by casualjim** [comment]
your swagger.yaml is missing a title for the api: https://github.com/go-swagger/go-swagger/blob/688294197b11d1ca70ffaabc161636497ab5c944/examples/todo-list/swagger.yml#L6

**Comment by oleksiivelychko** [comment]
> your swagger.yaml is missing a title for the api:
> 
> https://github.com/go-swagger/go-swagger/blob/688294197b11d1ca70ffaabc161636497ab5c944/examples/todo-list/swagger.yml#L6

Thank you. I looked up examples and compared with my code.  I've changed it and now title is generating successfully.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/94033630/158311022-4385098c-cc83-402b-a776-adfa25733db3.png">
