### ISSUE TITLE
generate: YAML parse error in meta doc when using tabs

### ISSUE THREAD

**Issue by Kangaroux** [go-swagger/go-swagger#2756]
## Problem statement
If you use tabs in the `Extensions` or `SecurityDefinitions` fields you will get the following error when trying to generate a spec:

```
yaml: found character that cannot start any token
```

This only seems to affect mapping types. For example, `Security` is a list, and it doesn't seem to matter if you use spaces or tabs.

As an aside, it would be helpful to know where exactly the error is occurring.

## Steps to reproduce
Create a file named `main.go`.

Generate a spec with:
```
swagger generate spec -o ./swagger.json
```

This uses tabs and will fail:

```go
//	Security:
//	- api_key:
//
//	SecurityDefinitions:
//	api_key:
//		type: apiKey
//		name: KEY
//		in: header
//
//	Extensions:
//	x-meta-value: value
//
// swagger:meta
package main

func main() {}
```

This uses spaces and should work:
```go
//  Security:
//  - api_key:
//
//  SecurityDefinitions:
//  api_key:
//      type: apiKey
//      name: KEY
//      in: header
//
//  Extensions:
//  x-meta-value: value
//
// swagger:meta
package main

func main() {}
```

## Environment
swagger version: v0.29.0
go version: go1.18 linux/amd64
OS: Pop!_OS 21.04

**Comment by tsmethurst** [comment]
I've noticed it works if you do it like this (go 1.19.1, go swagger 0.30.2)

![Screenshot from 2022-09-14 12-18-11](https://user-images.githubusercontent.com/31960611/190128494-17805df3-e86e-4473-a285-b0a21ada3033.png)

Note the tabs and whitespaces

**Comment by casualjim** [comment]
this should be fixed in the latest release of go-swagger, we now know how to deal with tabs

**Comment by earthaYan** [comment]
hello, I met this problem in latest version,is it fixed now? @casualjim

**Comment by ed-randall-blk** [comment]
We have this since updating to go 1.19 - using 0.30.4
```
swagger generate spec --scan-models --output=swagger-ui/swagger.json.new
yaml: line 2: found character that cannot start any token
```
If only it would tell me which file it's currently looking at, would be a great help, there are many (and line 2 is obviously its preprocessed yaml).   I don't see any "verbose" option.   Any tips for diagnosing where the error might be?
