### ISSUE TITLE
Go 1.19 change breaks swagger

### ISSUE THREAD

**Issue by stgraber** [go-swagger/go-swagger#2759]
There's this upstream change https://github.com/golang/go/issues/51082 that's meant to improve godoc by allowing for additional syntax in Go comments. Unfortunately it means that running `gofmt` as many projects do automatically ends up breaking the Swagger comments leading to a broken schema.

Here is the result on a single file in our codebase:
```shellsession
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ gofmt -s -w lxd/instance_delete.go
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ make update-api
(cd / ; go install -v -x github.com/go-swagger/go-swagger/cmd/swagger@latest)
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/cmd/swagger/@v/list
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/@v/list
# get https://proxy.golang.org/github.com/go-swagger/@v/list
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/cmd/@v/list
# get https://proxy.golang.org/github.com/@v/list: 410 Gone (0.255s)
# get https://proxy.golang.org/github.com/go-swagger/@v/list: 410 Gone (0.402s)
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/cmd/@v/list: 410 Gone (0.408s)
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/cmd/swagger/@v/list: 410 Gone (0.409s)
# get https://proxy.golang.org/github.com/go-swagger/go-swagger/@v/list: 200 OK (0.422s)
WORK=/tmp/go-build2036726384
swagger generate spec -o doc/rest-api.yaml -w ./lxd -m

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ git diff lxd/instance_delete.go
diff --git a/lxd/instance_delete.go b/lxd/instance_delete.go
index d28248b89..1a457eace 100644
--- a/lxd/instance_delete.go
+++ b/lxd/instance_delete.go
@@ -14,7 +14,7 @@ import (
 
 // swagger:operation DELETE /1.0/instances/{name} instances instance_delete
 //
-// Delete an instance
+// # Delete an instance
 //
 // Deletes a specific instance.
 //
@@ -23,21 +23,24 @@ import (
 // ---
 // produces:
 //   - application/json
+//
 // parameters:
 //   - in: query
 //     name: project
 //     description: Project name
 //     type: string
 //     example: default
+//
 // responses:
-//   "202":
-//     $ref: "#/responses/Operation"
-//   "400":
-//     $ref: "#/responses/BadRequest"
-//   "403":
-//     $ref: "#/responses/Forbidden"
-//   "500":
-//     $ref: "#/responses/InternalServerError"
+//
+//     "202":
+//       $ref: "#/responses/Operation"
+//     "400":
+//       $ref: "#/responses/BadRequest"
+//     "403":
+//       $ref: "#/responses/Forbidden"
+//     "500":
+//       $ref: "#/responses/InternalServerError"
 func instanceDelete(d *Daemon, r *http.Request) response.Response {
        instanceType, err := urlInstanceTypeDetect(r)
        if err != nil {

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ git diff HEAD doc/rest-api.yaml 
diff --git a/doc/rest-api.yaml b/doc/rest-api.yaml
index b8d69f0e2..7d9c1dd0c 100644
--- a/doc/rest-api.yaml
+++ b/doc/rest-api.yaml
@@ -7678,16 +7678,7 @@ paths:
         type: string
       produces:
       - application/json
-      responses:
-        "202":
-          $ref: '#/responses/Operation'
-        "400":
-          $ref: '#/responses/BadRequest'
-        "403":
-          $ref: '#/responses/Forbidden'
-        "500":
-          $ref: '#/responses/InternalServerError'
-      summary: Delete an instance
+      summary: '# Delete an instance'
       tags:
       - instances
     get:
```

I don't know if it's something that needs addressing in upstream `gofmt` or something that the parser in go-swagger needs to just learn to deal with, but as it stands, Go 1.19 is going to cause a whole bunch of breakage.

**Comment by casualjim** [comment]
I think for this case it's go-swagger that will need to adapt.  The headings one in particular fills a gap 

So maybe there will be some items that need to be addressed in gofmt but I think for the most part the changes will be in go-swagger with a build tag

**Comment by stgraber** [comment]
Yeah, their changes make sense when considering comments from the point of view of godoc.

It's a bit odd having things like summaries turned into headings and the schema data be turned into code examples but it's something we can get used to I guess :)

**Comment by xrstf** [comment]
Now that Go 1.19 is released, we ran into the same issue. Maybe this ticket could be pinned and its title renamed to include "Go 1.19", so others can find it quickly.

**Comment by stgraber** [comment]
I've updated the title now

**Comment by rodrigc** [comment]
I ran into this problem and asked about it here: https://groups.google.com/g/golang-nuts/c/sY7QFzfSMT4

**Comment by casualjim** [comment]
It would be helpful if you try the branch: go1.19

If you're using the yaml spec, you may have to indent it like a code block to retain formatting.

If things still break, please link your problematic code, or better yet send me a PR to the go1.19 branch with your code in the fixtures/goparsing/go119 folder. I'll try work through the problems

One cause of issues will be mixed use of tabs and spaces, you'll get the best result if you use tabs for indentation.

Here's an example of a comment that is converted to make the yaml block a code block and I had to configure vscode to display whitespace characters  to make sure that the yaml block was not using mixed indentation: https://github.com/go-swagger/go-swagger/blob/330b790661f4d1dcd1636781c4824e43bb42c4ec/fixtures/goparsing/go119/golangnuts.go

**Comment by casualjim** [comment]
It also works if you use spaces for indentation within the code block. In that case the only tab that appears is the first character on the comment line, the whitespace after that just needs to be consistent for a yaml doc.

**Comment by casualjim** [comment]
I installed this chrome extension to display whitespace github: https://chrome.google.com/webstore/detail/render-whitespace-on-gith/ifdbipohclgnokjgpejhnbjdlgjkkhom/related?hl=en
