### ISSUE TITLE
Add http/unix socket transport

### ISSUE THREAD

**Issue by hickeng** [go-swagger/go-swagger#278]
The matter of additional transports has come up several times, and is now getting discussed in https://github.com/vmware/vic/issues/69 ([here](https://github.com/vmware/vic/issues/69#issuecomment-183457021)).

**Comment by fdawg4l** [comment]
Lets move that discussion here.  If we're going to go with a micro-services architecture, then we'll need a lighter transport than http over tcp.  The first thing that comes to mind is some sort of RPC over unix://.  Maybe http over unix:// a.la. docker.
