### ISSUE TITLE
Upload of large files permanently leaves files in TEMPDIR

### ISSUE THREAD

**Issue by thejan2009** [go-swagger/go-swagger#2789]
## Problem statement

See this comment https://github.com/golang/go/issues/20253#issuecomment-606971843 and the parent issue.

After handling a request, the temporary files created when parsing multipart form should be removed.

## Steps to reproduce

Upload files larger than 32 MB and see how `$TMPDIR/multipart-*` files will multiply.

## Environment
swagger version: 0.28.0  
go version: 1.18.3
OS:

**Comment by fredbi** [comment]
This bug in go stdlib http2 has been fixed with go1.20. Closing this.
