### ISSUE TITLE
Add direct call transport

### ISSUE THREAD

**Issue by hickeng** [go-swagger/go-swagger#279]
The matter of additional transports has come up several times, and is now getting discussed in https://github.com/vmware/vic/issues/69 ([here](https://github.com/vmware/vic/issues/69#issuecomment-183457021)).

This is for a direct in-memory call so that we can spec out components that live within the same process, allowing us to easily migrate components from initial in-process implementation to distributed.

**Comment by fdawg4l** [comment]
@hickeng you mean using shmem based rpc in-process?  Sounds like a lot of work unless there's a library that does this already.

**Comment by sflxn** [comment]
The question is whether Swagger wants to be this type of technology or just public APIs for systems like webservices and EDI.

**Comment by casualjim** [comment]
you can do that today already by just building up the http.Request object and then passing ti to the the middleware. Perhaps use the httptest.Recorder to gather the response data

**Comment by fredbi** [comment]
See also #444

**Comment by fredbi** [comment]
Closed as marked duplicate
