### ISSUE TITLE
Question: how to make snakize to ignore some abbreviation?

### ISSUE THREAD

**Issue by Sczlog** [go-swagger/go-swagger#2794]
## Problem statement
I have an operation which name is `UpdateClusterEnableISCSISetting`, ISCSI is an abbreviation so it should be uppercase, but snakize will convert it to `i_s_c_s_i`, so `UpdateClusterEnableISCSISetting` is convert to `update_cluster_enable_i_s_c_s_i_setting` which looked so weird. How can I tell go swagger not to snakize some abbreviatiojn like ISCSI or other things?
I read the code and find a `LanguageOpts` will determine how snakize work, but I don't find how to modify it.

## Environment
swagger version: latest
go version: 1.17
OS:   win10

**Comment by youyuanwu** [comment]
Maybe try: generate cli option `--additional-initialism=ISCSI`

See https://github.com/go-swagger/go-swagger/issues/1380

**Comment by Sczlog** [comment]
@youyuanwu thanks
