### ISSUE TITLE
packages order

### ISSUE THREAD

**Issue by midoblgsm** [go-swagger/go-swagger#28]
I used the petstore example provided in (https://github.com/go-swagger/go-swagger/tree/master/examples) to test the server generation.
The generated code differs from the one existing in the example folder where the generated code is composed of 3 packages:
* cmd
* models
* restapi
      * operations
         * pet
         * store
        * user

my generated code is:
* cmd
* models
* restapi
   * operations
* operations
   * restapi
      * pet
      * store
      * user

I think that somewhere in the code generation there is an "operations/restapi" instead of "restapi/operations".

/cc @maximilien

**Comment by casualjim** [comment]
I think somebody fixed that in #25
