### ISSUE TITLE
Unable to locate package swagger

### ISSUE THREAD

**Issue by emaborsa** [go-swagger/go-swagger#2800]
As written [here ](https://goswagger.io/install.html#debian-packages-), I am trying to install swagger using the following command:

```sudo apt update
sudo apt install -y apt-transport-https gnupg curl
curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/gpg.2F8CB673971B5C9E.key' | sudo apt-key add -
curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/config.deb.txt?distro=debian&codename=any-version' | sudo tee /etc/apt/sources.list.d/go-swagger-go-swagger.list
sudo apt update 
sudo apt install swagger
```
What I get is `Unable to locate package swagger`, maybe because of:
```W: GPG error: https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F8CB673971B5C9E
E: The repository 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/deb/debian any-version InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I am working on Ubuntu 20.04LTS on Windows WSL.

**Comment by tina-hello** [comment]
Try 

sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https

curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/gpg.2F8CB673971B5C9E.key' | sudo gpg --dearmor -o /usr/share/keyrings/go-swagger-go-swagger-archive-keyring.gpg

to import the key

**Comment by PMohanJ** [comment]
Thanks @tina-hello, it worked!

**Comment by Lesliefans0-0** [comment]
> Try
> 
> ```
> sudo apt install -y debian-keyring debian-archive-keyring
> 
> curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/gpg.2F8CB673971B5C9E.key' | sudo gpg --dearmor -o /usr/share/keyrings/go-swagger-go-swagger-archive-keyring.gpg
> ```
> 
> to import the key

Thank you so much!!
