### ISSUE TITLE
any type (generics)

### ISSUE THREAD

**Issue by 53jk1** [go-swagger/go-swagger#2809]
Does swagger will support `any` type from generics?

**Comment by youyuanwu** [comment]
For what use case? example?

**Comment by 53jk1** [comment]
If, for example, we can get a variety of data from a response, a wrapper that can wrap all such data would be useful. This can replace `interface{}`, for example, and work better.

Example:
```go
// swagger:model transportErr
type transportErr struct {
   // Message is a human-readable description of the error.
   // Required: true
   Message string `json:"message"`
   // Data is additional data about the error.
   Data any `json:"data,omitempty"` // <- for this use case. Unsupported type "invalid type"
}
```

**Comment by youyuanwu** [comment]
I thought `any` is an alias for `interface{}`. Are you asking us to replace interface{} by any in all code and the generated code?

**Comment by casualjim** [comment]
I think what is being asked is to support `any` in the `codescan` package, to recognize it the same way we recognize `interface{}` today

**Comment by amit-mahendrakar** [comment]
The v0.29.0 generator does not understand `any` type.

If we try to use fields of type `any` in query or body, the generator gives error

`unsupported type "invalid type"`

because it sees `any` as `invalid type`

I think this is what @casualjim  is asking.

@youyuanwu  is there a plan to support it ?

**Comment by amit-mahendrakar** [comment]
whereas if we just change the type of parameter from `any` to `interface{}`, generation is successful.

**Comment by jesse-schneider** [comment]
Also would like to know if there are plans to include this in the future?

**Comment by casualjim** [comment]
I added some tests for where we have the type `interface{}`, all the tests we have for the `codescan` package pass. 
I've also added the `transportErr` type from this issue. https://github.com/go-swagger/go-swagger/blob/8edb8ee718461ce941a04a235689f1b83431e0f0/fixtures/goparsing/go118/nomodel.go

I think you may get it to work with previous versions of go swagger by building from source with a newer golang like go 1.18.
