### ISSUE TITLE
v0.30.0 causes build comment error in go install

### ISSUE THREAD

**Issue by npeters-novetta** [go-swagger/go-swagger#2815]
## Problem statement

```shell
$ GO111MODULE=on go install github.com/go-swagger/go-swagger/cmd/swagger@latest
gocode/pkg/mod/github.com/go-swagger/go-swagger@v0.30.0/cmd/swagger/commands/generate/spec_go111.go:12:2: //go:build comment without // +build comment
gocode/pkg/mod/github.com/go-swagger/go-swagger@v0.30.0/cmd/swagger/commands/generate/cli.go:3:8: //go:build comment without // +build comment
```
Please remove the sections that don't apply

## Steps to reproduce

Try to install the latest version of go-swagger:
```shell
GO111MODULE=on go install github.com/go-swagger/go-swagger/cmd/swagger@latest
```

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by casualjim** [comment]
Which go version are you using? I don't get that for go 1.18 and go 1.19

**Comment by uesteibar** [comment]
@casualjim we're getting this on Go 1.16 as well

**Comment by npeters-novetta** [comment]
> Which go version are you using? I don't get that for go 1.18 and go 1.19

Go 1.16.

**Comment by casualjim** [comment]
I fixed it, but for future reference: we only support the 2 latest versions of golang for this binary and we provide compiled binaries for many architectures and operating systems.
