### ISSUE TITLE
v0.30.0 won't install on golang(1.18/1.19)-alpine container

### ISSUE THREAD

**Issue by martinianodl** [go-swagger/go-swagger#2816]
## Problem statement
Up to version v0.29.0 I had no issues installing `go-swagger` in my Dockerfile.
Now I'm getting the error:
```
# github.com/go-swagger/go-swagger/cmd/swagger
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```

## Steps to reproduce
1. Create a Dockerfile.test:
```
FROM golang:1.18-alpine

RUN go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.0
```
2. Run: `docker build -f Dockerfile.test .`

## Environment
swagger version: 0.30.0
go version: [1.18-alpine](https://hub.docker.com/layers/golang/library/golang/1.18-alpine/images/sha256-5f764dacf0f5430271346709cfb28272ac013e30b0b2f9d23cf8ee12bfa98dbc?context=explore) and [1.19-alpine](https://hub.docker.com/layers/golang/library/golang/1.19-alpine/images/sha256-70df3b8f9f099da7f60f0b32480015165e3d0b51bfacf9e255b59f3dd6bd2828?context=explore)
OS: alpine-linux

**Comment by casualjim** [comment]
This Dockerfile works for me:

```dockerfile
FROM golang:1.18-alpine

RUN CGO_ENABLED=0 go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.0
```

**Comment by casualjim** [comment]
if you are set on  building an image with CGO enabled

```dockerfile
FROM golang:1.18-alpine

RUN apk add -U --no-cache build-base binutils-gold &&\
  go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.0
```

**Comment by martinianodl** [comment]
That works! 
Thanks for the quick response @casualjim
