### ISSUE TITLE
JSON Schema in swagger API response

### ISSUE THREAD

**Issue by rupinder10** [go-swagger/go-swagger#2821]
I have an API that returns a body that corresponds to a JSON Schema, The JSON schema structure is included in the API spec file. But when I try to generate the client I get the following error:

name field ArraySchema
package field models
creating generated file "array_schema.go" in "models" as definition
executed template asset:model
source formatting failed on template-generated source ("models\\array_schema.go" for definition). Check that your template produces valid code
unformatted generated source "array_schema.go" has been dumped for template debugging purposes. DO NOT build on this source!
source formatting on generated source "definition" failed: models\array_schema.go:118:34: expected ';', found string (and 10 more errors)

## Swagger specification

[ServiceManagementBody.zip](https://github.com/go-swagger/go-swagger/files/9485408/ServiceManagementBody.zip)

## Steps to reproduce

run 
swagger genereate client -f ServiceManagementBody.json -A client

## Environment
swagger version: 2.0
go version:  1.18.4
OS:   Windows 11

**Comment by fredbi** [comment]
@rupinder10 
The "get$ref" identifier is causing the problem.
Adding "x-go-name": "GetRef" to override the faulty auto-naming resolution results in models that build correctly.

**Comment by fredbi** [comment]
Fixing name mangling so we get a correct name (in this case this would be "getDollarRef")
