### ISSUE TITLE
Error parsing time with format "Y-m-d H:i:s" into time object

### ISSUE THREAD

**Issue by melodyabikhalil** [go-swagger/go-swagger#2855]
## Problem statement

I keep getting error `parsing time "2022-10-11 10:29:16" as "2006-01-02T15:04:05Z07:00"` when trying to fill the model after calling an API
![313931130_656216879425024_8040270276904435990_n](https://user-images.githubusercontent.com/41291710/199657413-e39b97e1-ac84-4b95-8642-6dd78e670a72.png)![313278347_653761633051714_414523623287948515_n](https://user-images.githubusercontent.com/41291710/199657403-069ea5bf-dff2-4858-aa1c-f7adb1e42fc4.png)

In the initial project, the annotation set for this field is 
`* @OA\Property(property="purchase_date",type="string", format="date-time")`

In the generated go client by swagger, the field is
`PurchaseDate time.Time `json:"purchase_date,omitempty"``

Command used to generate go client:
`swagger-codegen generate -i api-docs.json -l go --api-package SubscriptionsClient -o ./client-go`

## Environment
swagger version: 3.0.34
go version: 1.18

**Comment by youyuanwu** [comment]
You are using swagger codegen tool and its repo is here: https://github.com/swagger-api/swagger-codegen
Please file the issue in that repo.
