### ISSUE TITLE
Swagger Generate Server Generates `go` Code With Cycles

### ISSUE THREAD

**Issue by mehoggan** [go-swagger/go-swagger#2866]
## Problem statement
`swagger generate server -A go-planting -f swagger.yml` fails on Transformed Spec. After a preliminary review of the spec, it is not seen why the resulting `go` code has cycles in them.

## Swagger specification
2.0

## Steps to reproduce
First some background. I am porting an old `clojure` application over to `golang`. I took the swagger.json from that service and then did the following to transform it to an OpenAPI v2.0 specification. the `swagger.json` was tranformed to YAML using
the following online [tool](http://editor.swagger.io/#/). Further processing was required because the `swagger.io` tool produced an OpenAPI v3.0 spec. To convert the OpenAPI v3.0 spec to a OpenAPI v2.0 (swagger) spec, an account was created at [APIMATIC](https://www.apimatic.io/dashboard) and the spec was "transformed" using the `Transform API` button.

After the OpenAPI v2.0 (swagger) spec was generated and validated. The following command was run:
```
swagger generate server -A go-planting -f swagger.yml
```

Subsequently, the following commands were run to build the server:
```
go mod tidy && \
   cd cmd/go-planting-server && \
   go build
```

This resulted in a build error. Somehow the spec or swagger generates `go` code with cycles in them. The errors are as follows:
```
package git.tcc.li/climate/pipelines/reg/go-planting/cmd/go-planting-server
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/core
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/v1
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/v1: import cycle not allowed
package git.tcc.li/climate/pipelines/reg/go-planting/cmd/go-planting-server
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/core
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/v1
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/v3
	imports git.tcc.li/climate/pipelines/reg/go-planting/restapi/operations/v3: import cycle not allowed
```
## Environment
swagger version: 0.30.3 
go version: 1.18.3
OS: macOS Monterey Version 12.6

[swagger.yml.zip](https://github.com/go-swagger/go-swagger/files/10168042/swagger.yml.zip)

**Comment by mehoggan** [comment]
I have created a smaller reproducible example. Attached is a zip with a spec that reproduces the error which is now simplified to:

```
package bug/cmd/go-planting-server
	imports bug/restapi
	imports bug/restapi/operations
	imports bug/restapi/operations/v1
	imports bug/restapi/operations/v1: import cycle not allowed
```

To reproduce
```
$ tar -xvf bug.tar.gz
$ make run-server
```

Still using the same versions as above except for I upgraded `golang`:

```
matthew.hoggan in ~/Documents/go-planting
⚡ go version
go version go1.19.3 darwin/amd64
```

[bug.tar.gz](https://github.com/go-swagger/go-swagger/files/10169774/bug.tar.gz)

**Comment by mehoggan** [comment]
Running:

```
golangci-lint run --fix ./...
```

Unfortunately, does not fix the issue but does show better diagnostic output on where the issues are. All the fixes to cycles entailed removing unused import added by the code generator. Unfortunately, in the real code there are 121 endpoints and each has 3 files that need to be touched up, so manually modifying the files is not sustainable. Any suggestions on automated tooling to cleanup after the swagger generate server command?

In my Makefile I have added the following target.

```
  swagger-touchup:
    # We run find -- goimports twice because of cycles.
    find . -name "*.go" -exec goimports -w {} \; && \
      find . -name "*.go" -exec goimports -w {} \; && \
      find . -name "*.go" -exec gofmt -w {} \; && \
      find . -name "*.go" -exec gofmt -w {} \;
  .PHONY: swagger-touchup
```

This seems remove most of the cycles which are just unused imports anyways. Seems like to me we are just blindly adding imports. Unfortunately, server.go and main.go still have unused imports. It would be nice if go-swagger validated auto generated code and fixed issues before the program exited.

**Comment by casualjim** [comment]
we do add a bunch of imports as hints and then expect goimports to clean them up.

I've confirmed that this behavior exists on my machine too. 
This is definitely not supposed to happen

**Comment by mehoggan** [comment]
Thank you @casualjim for the support. I will keep my eye on this thread for any updates. I am in the process of drafting a proposal for my employer (Bayer) on how to migrate existing `clojure` services over to `golang`. Services are deployed in docker containers using `debian`. However, local debugging and developing on our Macs is key. So generation of server and client code on our development machines will be a very important aspect of the migration. If I can be of any assistance please let me know.

**Comment by mehoggan** [comment]
Another observation one can make is that this only occurs for v1 and v3 endpoints. The legacy and v2 endpoints do not seem to exhibit this bug.

**Comment by fredbi** [comment]
@mehoggan  it is a package mangling issue: the v[n] suffix has a special meaning for go imports and the codegen doesn't guard against that (yet). It is indeed a bug.

A quick fix is to alter the go naming of your tags like so:
```yaml
tags:
- name: core
  description: ''
- name: legacy nitro
  description: ''
- name: legacy umber
  description: ''
- name: v1
  description: ''
  x-go-name: version1
- name: v2-validations
  description: ''
- name: v3-validations
  description: ''
- name: v3
  description: ''
  x-go-name: version3
- name: v3-planned
  description: ''
- name: v3-actual
  description: ''
```
