### ISSUE TITLE
Docs not updated for 0.30.4

### ISSUE THREAD

**Issue by brackendawson** [go-swagger/go-swagger#2883]
## Problem statement
The documentation at https://goswagger.io/ hasn't updated for the most recent release.

## Steps to reproduce
Visit https://goswagger.io/ and check for the new additions to the docs. One such expected addition is in [ignore](https://goswagger.io/use/spec/ignore.html) which talks about its use in struct fields.

## Environment
OS: macos 13.1
Browser: Google chrome 109.0.5414.87 (Official Build) (arm64)

**Comment by fredbi** [comment]
Since #3088 doc now reflects the current master. Working on further improvements to publish docs for released versions.
