### ISSUE TITLE
httpkit/client/runtime strips trailing slash from request path causing 301

### ISSUE THREAD

**Issue by jonathaningram** [go-swagger/go-swagger#289]
At https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/runtime.go#L138

It uses `path.Join` which strips the trailing slash from my path, e.g. https://play.golang.org/p/qIVI8ANGZt

My server 301s, but the redirect is not followed. Apparently 10 redirects are followed per https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/runtime.go#L153 so not sure if this is a bug or not, but ideally I feel that the redirects should not be necessary in this case because the runtime should not change the given path - at least so far as not changing the trailing slash choice that the server makes.

**Comment by casualjim** [comment]
I want to write a test for this, is this scenario correct:
Your server sends 301's for items that come in without a trailing slash? 

Nitpick: according to the spec on URI's the 2 are equivalent, so why not just catch it with routing logic? That being said, I've seen many go based APIs not handle calls with a trailing slash. (eg. https://ci.vmware.run/go-swagger/go-swagger vs https://ci.vmware.run/go-swagger/go-swagger/)  which makes me even more confused.

I doubt that I will be able to remove the usage of path.Join but I'll try to preserve a trailing slash should it exist.

**Comment by jonathaningram** [comment]
For me, I think not having the server handle both was because of the std libs behaviour of `http.Handle` and whether the path arg is a prefix - I can't recall exactly, but without the slash I think the server would not treat the given path as a prefix so the handler would not get matched for nested routes.

Re why not just catch it:

I guess the server is catching it, and (possibly?) doing the "right" thing by doing a 301 to the canonical resource.

Re your test:

Correct, so here's an example call:


```
$ curl -D - https://example.com/api/my-op
HTTP/1.1 301 Moved Permanently
Location: /api/my-op/
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Date: Mon, 15 Feb 2016 01:56:54 GMT
Server: Google Frontend
Cache-Control: private
Alt-Svc: quic=":443"; ma=604800; v="30,29,28,27,26,25"
Accept-Ranges: none
Transfer-Encoding: chunked

<a href="/api/my-op/">Moved Permanently</a>.
```

I'm sure you'll figure out the ideal solution (if you choose to implement this), but I just did this locally and it achieved what I needed:

```diff
diff --git a/httpkit/client/runtime.go b/httpkit/client/runtime.go
index f3a957a..da6d6bc 100644
--- a/httpkit/client/runtime.go
+++ b/httpkit/client/runtime.go
@@ -135,7 +135,14 @@ func (r *Runtime) Submit(operation *client.Operation) (interface{}, error) {
        }
        req.URL.Scheme = r.pickScheme(operation.Schemes)
        req.URL.Host = r.Host
+       var reinstateSlash bool
+       if req.URL.Path[len(req.URL.Path)-1] == '/' {
+               reinstateSlash = true
+       }
        req.URL.Path = path.Join(r.BasePath, req.URL.Path)
+       if reinstateSlash {
+               req.URL.Path = req.URL.Path + "/"
+       }
 
        r.clientOnce.Do(func() {
                r.client = &http.Client{
```

**Comment by casualjim** [comment]
If you add a test for that code you have a PR I'd gladly accept :)

**Comment by jonathaningram** [comment]
No probs, happy to help :)
