### ISSUE TITLE
Swagger docs validate failed when enums_as_ints=true

### ISSUE THREAD

**Issue by hnlq715** [go-swagger/go-swagger#2890]
## Problem statement

Here is the 
https://github.com/hnlq715/proto/actions/runs/4052643492/jobs/6972309198#step:5:41

Please remove the sections that don't apply

## Swagger specification
https://github.com/hnlq715/proto/blob/main/gen/go/api/helloworld/v1/helloworld.swagger.json

## Steps to reproduce
Details can be found in this repo https://github.com/hnlq715/proto

## Environment
swagger version:   v0.30.4
go version: v1.19.5
OS:   macos

**Comment by hnlq715** [comment]
```
The swagger spec at "gen/go/api/helloworld/v1/helloworld.swagger.json" is invalid against swagger specification 2.0.
See errors below:
- in operation "GreeterService_SayHello", default value in response 200 does not validate its schema
- 200.data.sex.default in body must be of type integer: "string"
- 200.data.sex.default in body should be one of [1 2]
- in operation "GreeterService_SayHello2", default value in response 200 does not validate its schema
- definitions.v1Sex.default in body must be of type integer: "string"
- definitions.v1Sex.default in body should be one of [1 2]
```

**Comment by hnlq715** [comment]
Everything works fine when generating swagger doc with enums_as_ints=false

https://github.com/hnlq715/proto/actions/runs/4052618200/jobs/6972254556

**Comment by hnlq715** [comment]
Here is the PR details: https://github.com/hnlq715/proto/pull/3/files

**Comment by hnlq715** [comment]
Emm, seems like this issue should be moved to https://github.com/grpc-ecosystem/grpc-gateway

**Comment by fredbi** [comment]
Closing as unrelated to this project
