### ISSUE TITLE
Support for OpenAPI 3.x

### ISSUE THREAD

**Issue by gabrielhelix** [go-swagger/go-swagger#2900]
## Problem statement

Hi, right now it appears that this library only supports generating Swagger 2.0. I was wondering if it'd be possible to add support for Swagger/OpenAPI 3.x? I would be very interested in this. Thank you! 

## Swagger specification

https://spec.openapis.org/oas/v3.0.0
https://spec.openapis.org/oas/v3.1.0

**Comment by youyuanwu** [comment]
See #1122 
No support planned from current maintainers.

**Comment by asv** [comment]
@gabrielhelix look at [github.com/ogen](https://github.com/ogen-go/ogen)

**Comment by fredbi** [comment]
Ok so this is now written on the front door. Just too much work to be contemplated without sponsorship.
