### ISSUE TITLE
is support for generic structures？

### ISSUE THREAD

**Issue by 371873574** [go-swagger/go-swagger#2920]
gin-swagger 
type PageData[T any] struct {
	Total int `json:"total"`
	List  []T `json:"list"`
}

type Response[T any] struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data T      `json:"data"`
}
Can nested generic types be implemented？

**Comment by 371873574** [comment]
// @Success 200 {object} app.Response[PageData[response]]

**Comment by 371873574** [comment]
error in gin  // @Success 200 {object} app.Response[PageData[response]]

**Comment by 371873574** [comment]
type response struct {
	Name       string
	Status     string
	Namespace  string
	Images     string
	CreateTime string
}
error in gin swagger  // @Success 200 {object} app.Response[PageData[response]]

**Comment by hunjixin** [comment]
got error 
```
panic: WARNING: can't determine refined type T (*types.TypeParam)
```

**Comment by fredbi** [comment]
This issue report relates to swaggo and gin-swagger, which are not go-swagger.
