### ISSUE TITLE
[Proposal] Introducing new compatibility level "Warning" for changes which are technically non-breaking but can cause unforeseen behavior change for client

### ISSUE THREAD

**Issue by schafle** [go-swagger/go-swagger#2932]
## Introducing compatibility level "Warning"
There are certain changes diff tool reports which are technically non-breaking but can cause unforeseen behavior changes in client and should be reported differently. Cases where this is applicable:
- Default value is added/removed/changed
- Extension is added/removed
- An enum value is added

**Comment by schafle** [comment]
I will hold off merging my PR https://github.com/go-swagger/go-swagger/pull/2931 if this proposal is accepted.

**Comment by casualjim** [comment]
I think it's a good idea, you can consider it accepted :+1:

**Comment by schafle** [comment]
Done with #2933. Closing.
