### ISSUE TITLE
go-swagger install error

### ISSUE THREAD

**Issue by Anjali-Saha** [go-swagger/go-swagger#2934]
## Problem statement
when running $ GO111MODULE=off go get -u github.com/go-swagger/go-swagger/cmd/swagger

I get the following errors:
package embed: unrecognized import path "embed" (import path does not begin with hostname)
package io/fs: unrecognized import path "io/fs" (import path does not begin with hostname)
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:

I have ${GOPATH}/bin in my path

Please remove the sections that don't apply

## Steps to reproduce
$ GO111MODULE=off go get -u github.com/go-swagger/go-swagger/cmd/swagger

## Environment
swagger version:  v1.30.4 
go version: 1.13.0 
OS:   OSX 12.6.3

**Comment by asv** [comment]
Too old go version.

**Comment by Anjali-Saha** [comment]
ok thank you i was able to run $ go install github.com/go-swagger/go-swagger/cmd/swagger@latest and that resolved the issue thank you
