### ISSUE TITLE
Add diff support for extensions

### ISSUE THREAD

**Issue by zmay2030** [go-swagger/go-swagger#2935]
## Problem statement

As of now, the `diff` tool does not check for any additions or removals of extensions. Extensions are custom properties defined by the service and any addition or removal  of an extension could have a significant meaning depending on its use. 

And in terms of compatibility level, since extensions can easily result in a breaking change (as is the case in our organization), it might be worth assigning the warning level to it #2933

**Comment by fredbi** [comment]
Closed with #2936 merged
