### ISSUE TITLE
API Client Generation - Strange naming of folder inside of client folder

### ISSUE THREAD

**Issue by LukasDeco** [go-swagger/go-swagger#2974]
This isn't necessarily a bug, just a behavior I can't quite understand and I find it annoying.

Here is the command I am running: swagger generate client -f "swagger.json" -A "docreq" -c "docrequesterclient" -m "docrequestermodels"

And the swagger.json file has this info:
 "info": {
        "description": "****",
        "title": "Swagger docrequester API",
        "contact": {},
        "version": "1.0"
    }
    
I find that the `docrequesterclient` folder contains a folder named "doc_requester" which includes the functions to call the API. But why is it named "doc_requester" ??? I never specified this spelling with the "_" in the command or in the swagger documentation. What kind of strange parsing is going on here?

**Comment by casualjim** [comment]
do you have a tag or something on your operations?

**Comment by LukasDeco** [comment]
I've done a find all for that tag and nothing. Maybe I will check again...

**Comment by LukasDeco** [comment]
I have tags that are pascal case like this: 

```
"tags": [
                    "DocRequester"
                ],
```

**Comment by LukasDeco** [comment]
Okay, I took out tags and that fixed it. That's what it was. Would be good to document this more specifically I don't think it's documented a lot. I now use the `-a` CLI param to specify the name of the operations package so I would recommend that to future people having trouble with this. You may also have to delete the tags.
