### ISSUE TITLE
API client generation without requiring go-openapi modules

### ISSUE THREAD

**Issue by LukasDeco** [go-swagger/go-swagger#2976]
Can we modify the generation command so that it doesn't require go-openapi modules for our project? We have many different services and if a service needs to install multiple API clients, but those API clients rely on different versions of go-openapi packages (because maybe they clients were generated with different versions of go-swagger over time) this creates an issue with dependency management.

**Comment by LukasDeco** [comment]
Maybe I could open an MR where I added some new constructors that can be used without go-openapi structs?

**Comment by LukasDeco** [comment]
Any thoughts on this? Would an MR be welcome?

**Comment by casualjim** [comment]
You can make a PR, but please don't modify the public interface besides net additions. So, without breakage :)

**Comment by LukasDeco** [comment]
@casualjim here it is: https://github.com/go-swagger/go-swagger/pull/2979 let me know your thoughts and I can adjust as needed.

**Comment by LukasDeco** [comment]
@casualjim made an update now I need the workflow re-approved: https://github.com/go-swagger/go-swagger/pull/2979

**Comment by fredbi** [comment]
Fixed with #2979 merged
