### ISSUE TITLE
Handle missing Accept: from request header

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#298]
The docker CLI leaves out the Accept: header in some requests.  The current go-swagger middleware does not handle this well.  It currently returns,

{"code":406,"message":"unsupported media type requested, only [application/json] are available"}

**Comment by casualjim** [comment]
what is the method it uses where it leaves out Accept?

**Comment by sflxn** [comment]
NegotiateContentType() in negotiate.go.

**Comment by casualjim** [comment]
HTTP method :) GET/POST/PUT/DELETE
Anyway it's a bug in swagger where it should use */* as default I guess

**Comment by sflxn** [comment]
So... you're saying, you're going to add it, right?
