### ISSUE TITLE
Diff should detect extension value changes

### ISSUE THREAD

**Issue by zmay2030** [go-swagger/go-swagger#2984]
## Problem statement
PR #2935 added diff support for extensions, but it only covers when an extension key is added or removed. We should also report on changes in the extension value.

i.e: the following should be reported on in the diff output
Before
```
{
...
"x-ext-foo": "A"
...
}
```

After
```
{
...
"x-ext-foo": "B"
...
}
```

**Comment by fredbi** [comment]
Fixed with #2986 merged. Closing.
