### ISSUE TITLE
feat: provide SwaggerUI middleware to serve spec file

### ISSUE THREAD

**Issue by jtuchel** [go-swagger/go-swagger#2988]
## Problem statement

I wasn't able to find a middleware to serve the generated spec file via SwaggerUI. 

Swaggo looks similiar and provides an additional package for this https://github.com/swaggo/http-swagger

It would be nice to have this too.

## Environment
swagger version: latest
go version: latest
OS: all

**Comment by casualjim** [comment]
We have 3 of them:

* https://github.com/go-openapi/runtime/blob/master/middleware/swaggerui.go
* https://github.com/go-openapi/runtime/blob/master/middleware/redoc.go
* https://github.com/go-openapi/runtime/blob/master/middleware/rapidoc.go
