### ISSUE TITLE
Create a gh-pages ,

### ISSUE THREAD

**Issue by RobertJGabriel** [go-swagger/go-swagger#299]
So people can update the website docs with pull requests :) Make it eaiser going forword

**Comment by casualjim** [comment]
thanks for the suggestion

There is this folder:
https://github.com/go-swagger/go-swagger/tree/master/docs/content

And that is a hugo site that gets pushed to
https://github.com/go-swagger/go-swagger.github.io

I can make it all work from the go-swagger.github.io repo in a gh-pages model though if that is preferred

**Comment by RobertJGabriel** [comment]
Ah That's perfect :) Up to you man , great work :) I might throw up a pull request :)

**Comment by RobertJGabriel** [comment]
Also did some work on the https://github.com/yvasiyarov/swagger before, great to see some doing a better job :D

**Comment by casualjim** [comment]
I've moved the sources of the documentation to the website repository.

https://github.com/go-swagger/go-swagger.github.io/tree/source

You can send pull requests there should you want to edit the website
