### ISSUE TITLE
option for case insensitivity for enum query params

### ISSUE THREAD

**Issue by jawspeak** [go-swagger/go-swagger#303]
Our swagger API is case sensitive for enums. E.g. "DESC" is ok but "desc" or "deSC" will cause 400s. This is needlessly strict and we should support case insensitive enums. We'd like to allow it to be case insensitive (these are get params). Since the validation code is deep in go-swagger generated code, have you considered this as a go-swagger feature?

thanks!

**Comment by casualjim** [comment]
We could add an extension like: x-strict and that would then make the string comparison use equalfold. 

I do think both options should be supported because I think that typically enums are an exhaustive list of strict values; but at the same time I think you have a valid use case.

**Comment by fredbi** [comment]
Interested by this. However this only applies to string values. Enum is more general than that.
Will do, for models:
-x-go-enum-ci : CI validation on this specific enum (ignored if values not string)
--with-enum-ci : CLI option to apply x-go-enum-ci as a default for the whole model

Future generalization to params remain possible.

**Comment by jawspeak** [comment]
https://stackoverflow.com/questions/60772786/case-insensitive-string-parameter-in-schema-of-openapi

**Comment by fredbi** [comment]
Closed with #2264
