### ISSUE TITLE
Support streaming responds

### ISSUE THREAD

**Issue by caglar10ur** [go-swagger/go-swagger#305]
Docker client expects a stream of JSON structs from daemon to show a progress bar. Attached file is a dump of following command

> curl -i -X POST http://IP:PORT/images/create?fromImage=alpine&tag=latest

[Dump](https://files.zenhub.io/56c7a77ef5b278b53b8dcd2b)

**Comment by casualjim** [comment]
operations in the generated server are expected to return a responder.

This interface is defined as:

```go
// Responder is an interface for types to implement
// when they want to be considered for writing HTTP responses
type Responder interface {
	WriteResponse(http.ResponseWriter, httpkit.Producer)
}
```

With 83807e5 I've added a `middleware.ResponderFunc` helper construct so you can just write a `func(http.ResponseWriter, httpkit.Producer)` where you want a streaming response.

I hope this is sufficient; I've toyed with a channel based stream where you send struct objects to a channel which then gets streamed to the browser. I decided against this because it seemed to just add complexity for little benefit. I can be persuaded to implement such a responder though, and should somebody send a PR like that I would not say no to it.

**Comment by mdelvecchio-wasabi** [comment]
I have a use case for a streaming responder with JSON.  I am reading records from a DB and sending them back to the client.  There could be 0, 1, 1 million, or 10 million records.  I don't want to implement the response as an array of objects, as that would require too much memory on both the server and the client, and the client would not read the first record until all records are read from the DB.

It seems like the Responder interface could be used on the server side, similar to the way I stream CSV records in a similar API.  My responder creates a csv.Writer from the http.ResponseWriter, then writes CSV records to it as they arrive from the DB.  Presumably this new API would have a writer that streams JSON structs to the client as they come in, thus avoiding the memory overhead.

What would the streaming client look like?  It looks to me like it would have to wait for the final record to be written, and the final "]" to end the JSON array, before it would return.

Is such an API possible with the current generated server and client?

Thanks.

**Comment by casualjim** [comment]
In short it is possible to write such an API with go-swagger and the client. We built docker event streams and log streaming with it when I was at vmware and working with their vic team. https://github.com/vmware/vic

You can also just have the server close the stream, the io.eof should be enough. There are a few ndjson projects in golang around the web, they should take care of that kind of book keeping.

**Comment by casualjim** [comment]
here's an example where I use a responder on the server end to emit SSE 

```
package definitions

import (
	"bytes"
	"encoding/json"
	"net/http"
	"sync"

	"github.com/go-openapi/swag"
	"stash.corp.netflix.com/pne/groot/gen/apiserver/models"

	"github.com/rs/zerolog/hlog"

	"stash.corp.netflix.com/pne/groot/pkg/event"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"stash.corp.netflix.com/nflxgo/nfkit/application"
	"stash.corp.netflix.com/pne/groot/gen/apiserver/restapi/operations"
)

func emsg(msg string) *models.Error {
	return &models.Error{
		Message: swag.String(msg),
	}
}

var (
	ssePrefix = []byte("data: ")
	sseSuffix = []byte("\n")
)

const (
	hdrContentType      = "Content-Type"
	mimeTextEventSTream = "text/event-stream"
)

func NewDefinitionChangesHandler(appCtx application.Context, broker *event.Broker) operations.SubscribeToResourceChangesHandler {

	return &definitionChangesHandler{
		appCtx: appCtx,
		broker: broker,
	}
}

var bufPool = sync.Pool{New: func() interface{} { return bytes.NewBuffer(nil) }}

func getBuffer() *bytes.Buffer {
	return bufPool.Get().(*bytes.Buffer)
}
func putBuffer(buf *bytes.Buffer) {
	buf.Reset()
	bufPool.Put(buf)
}

type definitionChangesHandler struct {
	appCtx application.Context
	broker *event.Broker
}

func (d definitionChangesHandler) Handle(params operations.SubscribeToResourceChangesParams) middleware.Responder {
	var (
		r   = params.HTTPRequest
		ctx = r.Context()
		log = hlog.FromRequest(r)
	)

	var (
		sub         = make(chan event.ResourceChangedEvent, 5)
		unsubscribe = d.broker.Subscribe(sub)
	)

	return middleware.ResponderFunc(func(rw http.ResponseWriter, producer runtime.Producer) {
		h := rw.Header()
		h.Set(hdrContentType, mimeTextEventSTream)
	GetOut:
		for {
			select {
			case <-ctx.Done():
				unsubscribe()
				break GetOut
			case evt, running := <-sub:
				if !running {
					unsubscribe()
					break GetOut
				}

				buf := getBuffer() // buffer first, so it fails as an atomic unit
				if _, err := buf.Write(ssePrefix); err != nil {
					log.Err(err).Msg("generating prefix part of sse event")
					putBuffer(buf)
					continue
				}
				if err := json.NewEncoder(buf).Encode(&evt); err != nil {
					log.Err(err).Msg("generating payload part of sse event")
					putBuffer(buf)
					continue
				}
				if _, err := buf.Write(sseSuffix); err != nil {
					log.Err(err).Msg("generating suffix part of sse event")
					putBuffer(buf)
					continue
				}

				if _, err := buf.WriteTo(rw); err != nil {
					log.Err(err).Msg("writing sse event to client")
					putBuffer(buf)
					continue
				}
				putBuffer(buf)
				rw.(http.Flusher).Flush()
			}
		}
	})
}
```

**Comment by mdelvecchio-wasabi** [comment]
Thank you for the example.  I have some questions.

1. The Content-Type is "text/event-stream".  How would this work for streaming JSON encoding of an object modeled in Swagger?  My current API returns an array of MyObject.  How would I define the response in Swagger so that it returns a stream of MyObject?  Or would it still have to be an array of MyObject?

2. If it returns an array of MyObject, then how does the generated client process JSON records as they arrive?  My understanding is that the client operation would wait until the array is closed (with the trailing "]"), then return all objects in a Go slice.  This won't work for me, as it would require millions of objects to be buffered in memory.

Thanks again.

**Comment by casualjim** [comment]
Each of these things depend on how you process the message on the client. For a generated client you can specify:

```
type: string
format: binary
```

That will render a stream you can then use any of the standards to do streaming json. One is Server-Sent-Events, that's the example linked above.
Another way is to use a newline delimiter for the frames on the stream: http://ndjson.org/
You can use a library like this: https://github.com/bcicen/jstream 
Or you can use the golang json stdlib to process the json as a stream.

**Comment by mdelvecchio-wasabi** [comment]
Sorry, I am having a really hard time getting the generated client to behave as I want it to.  

I have implemented a streaming CSV API, and I have it working well on the server side.  Some curl commands show that the data is being streamed back consistently.  But the generated client seems to buffer up all of the records, then give them to me.  This of course occupies huge amounts of memory on large data sets.

Here is what my Swagger file says for the 200 response:

```
      responses:
        200:
          description: CSV file to download
          schema:
            type: file
          headers:
            Content-Disposition:
              type: string
              description: A header specifying the file name
```

On the server side, I query my DB 10,000 rows at a time, and place the results on a channel.  My middleware.ResponderFunc() creates a csv.Writer from the responder's http.ResponseWriter parameter, reads objects from the channel, and writes them as CSV.

Again, a curl command shows that when this server streams millions of CSV records back, they are definitely streaming; they start arriving after the first DB query, and continue steadily until they are done.

Here is what my client side looks like:

```
	// Create a transport config
	transportConfig := client.DefaultTransportConfig()
	transportConfig.Host = serverAddress
	transportConfig.Schemes = []string{"http"}

	// Parameters
	params := billing.NewGetStreamingCsvParams()

	// Execute it
	s := time.Now()
	resp, err := billingClient.Billing.GetStreamingCsv(params, &myWriter)
	elapsed := time.Since (s)
	fmt.Printf ("Returned %v, %v in %v\n", resp, err, elapsed)
```

Where myWriter is a struct with a single method to satisfy the interface:

```
type MyCSVWriter struct {

	start       time.Time
	byteCount	int
}

func (w *MyCSVWriter) Write (p []byte) (n int, err error) {
	if flags.Debug() {
		fmt.Printf ("Got %d bytes at %v:\n%s\n", len (p), time.Since (w.start), string (p))
	}

	// Just keep count
	w.byteCount += len (p)

	return len (p), nil
}
```

My debugging indicates that I am receiving all 1,389,029 records (comprising ~100MB) sent by the server.  But my Write() method does not get called back at all until the server is _done_ sending events.  It takes 10 seconds to send all events, and that method does not get called back until 10 seconds after I execute the query.

I added a runtime.MemStats report at the end of my client program, and it reports that the Sys value is 609MB, indicating that all of the data is being buffered.

How can I convince the generated client to call my Write() method as the data arrives?

Thanks again for all of your help.

**Comment by mdelvecchio-wasabi** [comment]
Note:  I neglected to mention that my middleware.ResponderFunc() is writing the 200 OK HTTP header before it starts writing any CSV records:

```
			rw.Header().Set ("Content-Type", "text/csv")
			rw.Header().Set ("Content-Disposition", fmt.Sprintf ("attachment; filename=\"%s\"", fileName))
			rw.WriteHeader(200)
```

**Comment by casualjim** [comment]
can you open a new issue and put a spec in there? We can continue the discussion on that new issue

**Comment by mdelvecchio-wasabi** [comment]
I will.  Thanks.

**Comment by mdelvecchio-wasabi** [comment]
https://github.com/go-swagger/go-swagger/issues/2368
