### ISSUE TITLE
Generated server is misinterpreting request type as application/octet-stream

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#306]
When I do the following against a server that only supports application/json and text/plain at the moment, I get odd behavior.

Request:

curl -X POST -i http://127.0.0.1:49000/v1.21/images/create?fromImage=golang\&tag=latest

What the server sees:

POST /v1.21/images/create?fromImage=golang&tag=latest HTTP/1.1
Host: 127.0.0.1:49000
User-Agent: curl/7.43.0
Accept: */*

What the server responds:

HTTP/1.1 415 Unsupported Media Type
Content-Type: application/json
Date: Sat, 20 Feb 2016 00:00:55 GMT
Content-Length: 124

{"code":415,"message":"unsupported media type \"application/octet-stream\", only [application/json text/plain] are allowed"}

The handler for the operation never gets called.  This interpretation of the request is happening much earlier.

**Comment by casualjim** [comment]
I think this is the expected behavior:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

So I think the swagger specification should have a consumer for application octet-stream for those routes.

I added support for using io.Reader and io.Writer interfaces to produce bytestreams.

https://github.com/go-swagger/go-swagger/commit/2e4ece7ef6e618f2566bfa7c67e932097f449365

**Comment by sflxn** [comment]
@casualjim You should reopen this based on our recent conversation.  go-swagger currently ignores octet-stream as a consumes so there is no way for me to generate code that can handle this case.  Adding "application/octet-stream" to either global or operation-local has no effect during regeneration.

**Comment by frosenberg** [comment]
I think I'm still seeing this issue too. I have the following swagger.json:

```
/trained-models/{id}:   
    get:
      summary: Get the iteam as application/zip
      description: |
        Downloads a item as zip file.
      produces:
        - application/octet-stream
      parameters:
        - name: id
          description: The `id` of the item.
          in: path
          required: true
          type: string
          format: string
   
      responses:
        200:
          description: Downloads a zip file
          schema:
            type: string
            format: binary     
```

On the client I'm always seeing the following error:
`no consumer: "application/octet-stream"`

If I change the content type to `application/zip`, I'm seeing the same error with the respective content type. I'm on the latest git master@head.

**Comment by frosenberg** [comment]
Is there a working example somewhere?

**Comment by frosenberg** [comment]
I hacked the following statement into my client and it seems to work now:

```go
// [...]
transport := client.New(host, path, schemes)
// FIXME this should not be there and a bug in go-swagger - without this the zip download fails
transport.Consumers["application/octet-stream"] = runtime.ByteStreamConsumer()
return restClient.New(transport, strfmt.Default), nil
```
