### ISSUE TITLE
Install swagger server failed!

### ISSUE THREAD

**Issue by yuluo-yx** [go-swagger/go-swagger#3067]
## Problem statement

Install swagger server failed in ubuntu 22.04.

## Steps to reproduce

```
apt install -y apt-transport-https gnupg curl
curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/gpg.2F8CB673971B5C9E.key' | apt-key add -
curl -1sLf 'https://dl.cloudsmith.io/public/go-swagger/go-swagger/config.deb.txt?distro=debian&codename=any-version' > /etc/apt/sources.list.d/go-swagger-go-swagger.list
apt update 
apt install swagger
```

## Environment
swagger version: 0.30.5  
go version: 1.21.4
OS:   ubuntu 22.04

<img width="1422" alt="image" src="https://github.com/go-swagger/go-swagger/assets/77964041/051edd37-8491-4d35-87cb-929b4c367034">

> **Main error message: `Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`**

**Comment by fredbi** [comment]
Updated install instructions for debian/ubuntu no longer include the use of the deprecated apt-key.
