### ISSUE TITLE
Validator treats parameter references as errors

### ISSUE THREAD

**Issue by elgris** [go-swagger/go-swagger#321]
Looks like validator treats references as validation errors. For instance, let's put a reference to parameter list:
```
  /foo:
    get:
      summary: Some endpoint
      parameters:
        - name: some_id
          in: query
          description: some ID
          required: true
          type: integer
        - $ref: '#/parameters/some_shared_param'
          required: false
```

Validator output for such case is:
```
- paths./foo.get.parameters.$ref in body is a forbidden property
- paths./foo.get.parameters.name in body is required
- paths./foo.get.parameters.in in body is required
- paths./foo.get.parameters.type in body is required
```

As specification says, using references in parameter list is valid: http://swagger.io/specification/#operationObject (`parameters` is expected to hold an array `[Parameter Object | Reference Object]`)

**Comment by elgris** [comment]
False alarm.
This happens when one tries to override reference's parameter with some other value. Like this:
```
        - $ref: '#/parameters/some_shared_param'
          required: false
```

Swagger specs does not allow this, hence the ticket can be closed.

**Comment by normana400** [comment]
This validation causes false positives and the issue should be reopened.
In our case, we use urls with hashtags as a way to make our level 0 system apis have unique endpoints and thus become swagger compatible. 
example paths:

- our.rest/endpoint#Action1
- our.rest/endpoint#Action2

the go swagger validation treats these as validation errors: 
- paths.#Action1 in body is a forbidden property
- paths.#Action2 in body is a forbidden property

these aren't references to schema. The actual value of the path has a valid html symbol "#" in it. The go-swagger validation needs to be updated to flag schema reference matches by just matching "#" values in a property value.

swagger codegen does not have an issue with this

**Comment by fredbi** [comment]
Could you please post a YAML or JSON example illustrating your point?

**Comment by casualjim** [comment]
you use fragments on the server?

**Comment by normana400** [comment]
here's a sample. Again, this wouldn't be how you'd define the API from scratch, but this is a tool to describe an RPC level 0 endpoint in swagger. The fragments aren't actually used as we have an internal preexisting way to route the action. They fragments just make every path unique (which is a requirement for swagger). Swagger allows the use of a defined operationId parameter, but every path must be a unique path.

{
  "swagger" : "2.0",
  "info" : {
...
  },
  "host" : "myhost.net",
  "basePath" : "/api/myrpcendpoint",
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "#GetAcct" : {
      "post" : {
        "summary" : "get_acc",
        "operationId" : "GetAcct",
        "parameters" : [ {
          "name" : "body",
          "in" : "body",
          "required" : "true",
          "schema" : {
            "$ref" : "#/definitions/GetAcct"
          }
        } ],
        "tags" : [ "GetAcct" ],
        "responses" : {
          "default" : {
            "schema" : {
              "$ref" : "#/definitions/GetAcctResponse"
            }
          }
        }
      }
    },
    "#CalcCredit" : {
      "post" : {
...
    },
    "#GetPaypal" : {
      "post" : {
...
}
..

**Comment by casualjim** [comment]
it would work if you were to use query string syntax. fragments in uri's are a client only construct and as such we don't support those in our path syntax currently. So with ? instead of # it should work

**Comment by normana400** [comment]
we've instructed our client to use swagger-codegen and it works in that environment as is. We have clients that use swagger for many different languages so thats really our recommended platform.

That said, your option would probably work as a workaround for a small system. In our case its a 500+ api system.
