### ISSUE TITLE
The generated import path has incorrect prefix

### ISSUE THREAD

**Issue by easeway** [go-swagger/go-swagger#323]
Here's the environment:

```
mkdir -p ~/dev/go/src/mylib
export GOPATH=$HOME/dev/go
export PATH=$GOPATH/bin:$PATH
cd ~/dev/go/src/mylib
mkdir cmd spec pkg vendor
vi glide.yaml
glide install
vi spec/api.yml
```

My Go is Go 1.6, and when I generate the server code using 

```
swagger generate server -f spec/api.yml -t pkg
```

the generated file `pkg/restapi/operations/mylib_api.go` has wrong prefix on the import package path: `mylib/vendor/github.com/go-swagger/go-swagger/swag`

The prefix `mylib/vendor/` should not be there.

**Comment by casualjim** [comment]
this was fixed by: https://github.com/go-swagger/go-swagger/pull/324
