### ISSUE TITLE
Boolean parameters are generated into strings

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#346]
If I define a boolean parameter in an operation, the generated code converts the boolean to a string.

Take for instance,

        }, {
          "name": "stream",
          "in": "query",
          "description": "1/True/true or 0/False/false, return stream. Default false",
          "type": "string",
          "default": "false"
        }, {

Generated code,

	Stream *string

I wasn't sure whether I am suppose to expect a bool or a string in the generated code.

**Comment by casualjim** [comment]
the spec here says that it's a string. the type says string
