### ISSUE TITLE
`strfmt` types should implement database marshaling methods.

### ISSUE THREAD

**Issue by chakrit** [go-swagger/go-swagger#35]
Personally I think this should be a package separate from go-swagger. Validations and creations of the value types implemented here could be re-used in a lot of other projects.

My issue however, is to request that the values implement basic [`sql.Scanner`](http://golang.org/pkg/database/sql/#Scanner) and [`database/sql/driver.Valuer`](http://godoc.org/database/sql/driver#Valuer) so that text-based types such as `strfmt.Email` and `strfmt.UUID` on the structs can be marshalled to-and-fro the database without having to define a new type.

The implementation is quite trivial since most string types are just straight type renames so the implementation of those interfaces is just converting them back to the base `string` type.

Here's an example of how I define a `UUID` type (before go-swagger):

```go
type ID string                                                 
                                                               
var __id = ID("asdf")                                          
var _ sql.Scanner = &__id                                      
var _ driver.Valuer = __id                                     
                                                               
func NewID() ID {                                              
  raw := uuid.NewV4().String()                                 
  raw = raw[1 : len(raw)-1]                                    
  raw = strings.ToLower(raw)                                   
  return ID(raw)                                               
}                                                              
                                                               
func (id *ID) Scan(raw interface{}) error {                    
  switch v := raw.(type) {                                     
  case []byte:                                                 
    *id = ID(string(v))                                        
  case string:                                                 
    *id = ID(v)                                                
  default:                                                     
    fmt.Errorf("cannot sql.Scanner.Scan() to `ID` from: %#v", v)
  }                                                            
                                                               
  return nil                                                   
}                                                              
                                                               
func (id ID) Value() (driver.Value, error) {                   
  return driver.Value(string(id)), nil                         
}                                                              
```

As you can see, pretty trivial conversion. With this I can use this type inside any structs `type User struct{ id ID }` and all it'd marshal to-and-fro the db without a hitch.

This is esp. important when using `go-swagger` with [`jmoiron/sqlx`](https://github.com/jmoiron/sqlx) or any database mapping library in general.

**Comment by chakrit** [comment]
Also I think the list of types might benefits from `go generate` in some way or another. Those `MarshalText()` calls could just be generated.

**Comment by chakrit** [comment]
@casualjim would you accept a PR for this? Code should be pretty trivial.

**Comment by casualjim** [comment]
can you give me a few days to get my client branch integrated. I'm not worried about this particular feature as much as with how this can be done without having to change go-swagger for each thing people might find useful.
I have resorted to annotations and scanning in template-refactor and gen-client branches.

While sql might seem appropriate I don't know if I want go-swagger to have support for sql in the core of the project because not everybody uses sql at all and one goal is to keep dependencies of go-swagger very limited.

I hope this makes sense? So if you take a look at where I'm going with this stuff in the template-refactor branch, and you can come up with a proposal that would play nice with those annotations and such. I would gladly merge it in.

**Comment by midoblgsm** [comment]
I agree with you @casualjim, I think it is better to keep any specific support (like sql one) out of go-swagger. Otherwise, things will be unmanageable.

**Comment by chakrit** [comment]
Closing since #39 has been merged.
