### ISSUE TITLE
Generated models annotated with json when the media type is application/xml

### ISSUE THREAD

**Issue by stoyanr** [go-swagger/go-swagger#353]
We are using a swagger model in which the produced and consumed media type for all operations is "application/xml". However, in all generated model structs, fields are still annotated with `json:`, while in this case they should be annotated with `xml:` instead (or in addition). Simply replacing `json:` with `xml:` results in an (almost) usable model.

This is related to #183. Currently, by default there are no also XML consumers and producers in the transport, but they are also rather trivial to add.

**Comment by fredbi** [comment]
parent: #183

**Comment by fredbi** [comment]
Resolved with #2241
