### ISSUE TITLE
Support for generating clients for more than one APIs within the same project

### ISSUE THREAD

**Issue by stoyanr** [go-swagger/go-swagger#357]
We need to be able to generate clients for more than one APIs within the same project. Note that these are really different APIs served by different endpoints, so they can't be combined. Some definitions are shared among these APIs, so we want all of them to use the same generated `models/*.go`. I couldn't find a way to do this without renaming files and types after each generation, even though I was careful to use different operation names.

The main points of collision are `client/operations/operations_client.go` and `client/<app>_client.go`, since some of the generated filenames (e.g. `operations_client.go`), type names (e.g. `Client`), and function names (e.g. `New`) are too generic and don't contain the application name. This issue could be addressed by ensuring that all such names contain the application name, e.g. `slmp_operations_client.go`, `SlmpClient`, `NewSlmp`, etc. Alternatively, a different directory / package structure could be used by the generator, e.g. `client/<app>/` instead of just `client/`

To address this issue, we currently do the following after each API generation:

* Move `client/operations/operations_client.go` to its own file, e.g. `mv client/operations/operations_client.go client/operations/slmp_operations_client.go`
* In `client/operations/slmp_operations_client.go`, rename the type `Client` to `SlmpClient`, and the function `NewClient` to `NewSlmpClient`.
* In `client/slmp_client.go`, rename the variable `Default` to `DefaultSlmp`, and the functions `NewHTTPClient` and `New` to `NewSlmpHTTPClient` and `NewSlmp`.

**Comment by casualjim** [comment]
I think you can use '-c slmpclient' to this effect. That would generate each client in their own package but the models would still be shared

**Comment by stoyanr** [comment]
Thanks, this works perfectly! Sorry, I didn't know about this argument, as I didn't find it in the documentation. Only now I thought about running `swagger generate client --help` and saw the various options available there.
