### ISSUE TITLE
Not possible to put the definitions in a separate YAML file

### ISSUE THREAD

**Issue by stoyanr** [go-swagger/go-swagger#358]
We need to be able to generate clients for more than one APIs within the same project. Some definitions are shared among these APIs, so we would like to put them in a separate YAML file, e.g. `definitions.yaml` and refer to them from the main swagger files using JSON references such as `definitions.yml#/definitions/Task`. However, this is currently not possible with go-swagger. For some reason, the definitions are not found in this case and no models are generated.

**Comment by casualjim** [comment]
related #331
