### ISSUE TITLE
Please export common embedded structs as public

### ISSUE THREAD

**Issue by ceram1** [go-swagger/go-swagger#36]
Some structs like [simpleSchema](https://github.com/go-swagger/go-swagger/blob/master/spec/items.go#L9-L15) should be exported.

Example usecase: (pseudo code)
```
func setType(p spec.SimpleSchema, t SourceType) {
	if t.IsRef() {
		p.Ref = spec.MustCreateRef("#/definitions/" + t.GetName())
	} else {
		p.Type = toSwaggerType(t)
		p.Format = toSwaggerFormat(t)
	}
}
```

**Comment by ceram1** [comment]
I'm working on it. But I'm not sure if struct can be exported directly.
Do I need to do it in this way?
```
type simpleSchemaProp {
    // ...
}

type SimpleSchema{
    simpleSchemaProp
}


```

**Comment by casualjim** [comment]
is this still an issue? what is the thing you're trying to achieve?

**Comment by ceram1** [comment]
I can't remember, but I think I created this issue because I need to write several functions which does same thing.

I wanted to create a function with this signature, but I couldn't. Instead, I just wrote several functions, and this is not an issue for me. Closing..
```
func setType(p spec.SimpleSchema, t SourceType) {
    if t.IsRef() {
        p.Ref = spec.MustCreateRef("#/definitions/" + t.GetName())
    } else {
        p.Type = toSwaggerType(t)
        p.Format = toSwaggerFormat(t)
    }
}
```

**Comment by casualjim** [comment]
This was for the grpc gateway project?
Does that work, does it require more work?

**Comment by ceram1** [comment]
Multiple functions like
```
func setItemsType(p spec.Items, t SourceType) {
// same code
}
```
works
