### ISSUE TITLE
Adding consumes "application/octet-streaming" to individual path causes panic

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#365]
I added the following to a swagger spec path operation:

        "consumes": [
          "application/json",
          "application/octet-stream"
        ],

Result: panic

        "consumes": [
          "application/json"
        ],

Result: no panic

================================

In the panic scenario, the code generation doesn't always create code that panics.  With the same spec, two different code generation may result in different results.  I have captured the file diff between two generations where one succeeds and the other fails.[docker_api-panic.go](https://files.zenhub.io/56d9e17bae23ad603d73432b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[docker_api-nopanic.go](https://files.zenhub.io/56d9e19cae23ad603d73432d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by casualjim** [comment]
this only panics when there is no body correct?

**Comment by sflxn** [comment]
I believe that is the case.  The request I'm making has no body.

**Comment by sflxn** [comment]
I tracked down the problem to docker_api.go in the following area:

		defaultConsumes: "application/json",
		defaultProduces: "application/json",

if those defaults to application/octet-streaming during a generation, it panics.

**Comment by casualjim** [comment]
Would it be possible to give me steps to reproduce? When does the panic occur?
I would like to see the stack trace of the panic. 
if possible also a minimal version of the spec.

**Comment by sflxn** [comment]
1) Get VIC sources
2) $> make dockerapi
3) run the server
4) curl -X GET http://.../v1.22/_ping

As in the comments above, it depends on what is generated in docker_api.go file.  If the defaults are not application/json, you will get a panic.  From one generation to another, the defaults are changed.  Our swagger specs have numerous mime types for consumers/producers.  How do you chose which mime are defaults?  Is it just random?

==================

curl -i -X GET -H 'Accept: */*' http://127.0.0.1:49000/_ping
2016/03/08 09:05:42 http: panic serving 127.0.0.1:32934: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc820249580)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x8e20e0, 0xc82000e140)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/vmware/vic/apiservers/docker/restapi/operations/misc.(*PingOK).WriteResponse(0xc82042aa60, 0x7f790ffd0220, 0xc8203580d0, 0x0, 0x0)
	/home/loc/work/go/src/github.com/vmware/vic/apiservers/docker/restapi/operations/misc/ping_responses.go:37 +0xd8
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc8201d9c40, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180, 0xc820329600, 0x1, 0x1, 0xc8202c3260, 0x8e3c00, 0xc82042aa60)
	/home/loc/work/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:384 +0x674
github.com/vmware/vic/apiservers/docker/restapi/operations/misc.(*Ping).ServeHTTP(0xc82034a700, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/home/loc/work/go/src/github.com/vmware/vic/apiservers/docker/restapi/operations/misc/ping.go:52 +0x20b
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/home/loc/work/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8203295e0, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/casualjim/curler.New.func1(0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/home/loc/work/go/src/github.com/vmware/vic/vendor/github.com/casualjim/curler/curler.go:43 +0xaaa
net/http.HandlerFunc.ServeHTTP(0xc820167a70, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/home/loc/work/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:85 +0x663
net/http.HandlerFunc.ServeHTTP(0xc82040ddc0, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/home/loc/work/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x1d1
net/http.HandlerFunc.ServeHTTP(0xc8202a6580, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820248e80, 0x7f790ffd0220, 0xc8203580d0, 0xc8202c3180)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820249580)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by sflxn** [comment]
I think I may know what this is.  I'm trying something.

**Comment by sflxn** [comment]
Ok, this isn't a bug.  This is noob Swagger user error.  I forgot to add producer/consumers for the new members in api in configure_api.go.  I tried it, and I'm no longer getting any panics.
