### ISSUE TITLE
Tagging an in "body" parameter with "required" has no effect

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#366]
We're trying to detect an empty body in a request.  I added "required" to the body parameter, but it doesn't seem to make a difference.  If we make a request with no body, our handler gets called and the param object has an empty body generated.

`          "name": "container",
          "in": "body",
          "description": "Container to create",
          "schema": {
            "$ref": "#/definitions/ContainerConfig"
          },
          "required": true
`

generates

`type CreateParams struct {
	/*Container to create
	  Required: true
	  In: body
	*/
	Container *models.ContainerConfig
`

The expected response is a 500 error with EOF or any type of message.  It's also expected that the middleware handles this and our handler doesn't get called.  The actual result is our handler gets called and Container is filled with an empty models.ContainerConfig.  We need a way to detect an empty body and respond to user requests appropriately.  Even if it isn't handled in the middleware, when it gets to our handler and CreateParams.Container == nil for cases where the body is missing, that would work for us.

**Comment by casualjim** [comment]
fwiw and for other people reading this bug. 
An error resulting from user error (in this case because the user has not supplied the body) should always be in the 4xx range. 
5xx range is reserved for errors where the system is to blame.

Please next time provide clear steps/data to reproduce, it helps a lot. Things that help are the swagger spec or a minimal swagger spec to reproduce the issue. And perhaps the request you sent it, it's hard to read minds.

**Comment by sflxn** [comment]
[swagger.json.zip](https://github.com/go-swagger/go-swagger/files/164056/swagger.json.zip)

Attached is a file you can use to test against.  It has one simple POST operation.

Example Run:

$> curl -X POST http://127.0.0.1:49000/create
"operation .Create has not yet been implemented"

==========
Comments:

Our handler was reached, which is fine.  However, the params.Config is not nil.  It's the same result we had prior to the change.  What I see when I debug this is that in BindRequest,

`	if err := route.Consumer.Consume(r.Body, &body); err != nil {`

The result is err == nil so the check for required is never performed.
