### ISSUE TITLE
Serving swagger-ui with the API Server

### ISSUE THREAD

**Issue by phedoreanu** [go-swagger/go-swagger#370]
I was trying to serve swagger-ui from the generated API Server and I didn't find a straightforward enough way in the docs, so I've created my own swagger-ui middleware:

``` go
func setupGlobalMiddleware(handler http.Handler) http.Handler {
    return uiMiddleware(handler)
}

func uiMiddleware(handler http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Shortcut helpers for swagger-ui
        if r.URL.Path == "/swagger-ui" || r.URL.Path == "/api/help" {
            http.Redirect(w, r, "/swagger-ui/", http.StatusFound)
            return
        }
        // Serving ./swagger-ui/
        if strings.Index(r.URL.Path, "/swagger-ui/") == 0 {
            http.StripPrefix("/swagger-ui/", http.FileServer(http.Dir("swagger-ui"))).ServeHTTP(w, r)
            return
        }
        handler.ServeHTTP(w, r)
    })
}
```

Can this be achieved any easier?

Thank you

**Comment by casualjim** [comment]
I think that's the way to do it.

 At some point I included an embedded version of the swagger-ui in this toolkit but it became annoying to keep up to date and severely bloated the size of my binary.

**Comment by phedoreanu** [comment]
What do you say if we add swagger-ui as git submodule, include this middleware in your binary and update the docs?

**Comment by casualjim** [comment]
I'm reluctant to do so at this point in time because a git submodule break go-gettability.
I've had it included at one point but it's so much of a moving target that it would always be outdated. On top of it it are a lot of javascript and html files and people haven't been over the moon when go-swagger gets vendored and they see all of that.

Now after a refactor #420 is complete I think there might be a way to bring this functionality back because it becomes opt-in

**Comment by joeblew99** [comment]
awesome stuff. 

@casualjim Could you let me know the status.

I noticed the architecture is staying very close to the golang way. For example using .gotmpl, etc.


Here my tasks list:
Developers UI
- Would be great to use golang templates to run it. Prefer not to pollute with other stuff, just lean and easy to refactor as needs change.

Proxy JS
- Golang based generators for the Javascript
- Try out use fetch API, as its the react approach and has full polyfil now for all browser too.
