### ISSUE TITLE
DELETE operation with no body and Accept: */* does not reach handler

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#371]
A DELETE operation that is sent no body and has Accept: */* in the header never reaches our handler.

====
Request:

    curl -i -X DELETE -H 'Accept: */*' http://127.0.0.1:49000/containers/123

====
Result:

HTTP/1.1 415 Unsupported Media Type
Content-Type: application/json
Date: Sat, 05 Mar 2016 00:07:52 GMT
Content-Length: 100

{"code":415,"message":"unsupported media type \"\", only [application/json text/plain] are allowed"}

====
Comments:

About 2-3 weeks ago, we had a similar problem but the request was GET.  You added octet-streaming consumer support to fix it.  Can it be similar?

**Comment by jakedsouza** [comment]
Facing the same issue for DELETE requests with no Payload

```yml
 delete:
      description: "kill foo "
      operationId: kill
      tags:
        - foos
      responses:
        '204':
          $ref: "#/responses/noContentResponse"
        '404':
          description: foo not found
          schema:
            $ref: "#/definitions/error"
        '412':
          description: foo is in a state not for deletion
          schema:
            $ref: "#/definitions/error"
        default:
          $ref: "#/responses/errorResponse"```
