### ISSUE TITLE
Generating spec cannot import dependencies

### ISSUE THREAD

**Issue by morenoh149** [go-swagger/go-swagger#400]
## Problem statement

I'm unable to run the spec generator on my app. What am I doing wrong?
https://gist.github.com/morenoh149/e44be6819bde86f52e7e

I get many errors of the form `... .go:10:2: could not import github.com/facebookgo/stackerr (cannot find package "github.com/ ...`
## Steps to reproduce

execute `$ swagger generate spec -o ./swagger.json` in project folder

**Comment by casualjim** [comment]
which go version are you using?
Are you using vendoring?

**Comment by morenoh149** [comment]
go version go1.5.3 darwin/amd64

I believe I have vendoring enabled yes. (Not sure I'm new).

**Comment by casualjim** [comment]
for this you require `export GO15VENDOREXPERIMENT=1`

**Comment by casualjim** [comment]
and also does your application compile? because go-swagger makes use of the same code the go compiler/imports/... etc use to discover all the involved packages. So I think it requires your code to be mostly compilable to be able to discover everything.

However the errors seem to be related to it not being able to discover the dependencies

**Comment by morenoh149** [comment]
I have `GO15VENDOREXPERIMENT=1` set in my environment and my application compiles and runs without complaints. It must be having issues finding the dependencies

**Comment by casualjim** [comment]
are you running the swagger command in the package that contains your main function?

**Comment by casualjim** [comment]
would it be possible to share your code in some way, it can be done privately if you're concerned about making it public. I just want to understand this issue better

I have a slack team (https://slackin.goswagger.io) and I'm Ivan Porto Carrero in the gobridge slack team

**Comment by morenoh149** [comment]
I execute the command from the api dir. I'll join.

**Comment by gsquire** [comment]
I am running into this issue when trying to generate a swagger spec as well. I believe it is because I installed go with home brew on a mac so my library paths are different.

Command I am running: `swagger generate spec`
File I am trying to generate with: https://gist.github.com/gsquire/cce277b4bd10ba283f4522e896dc91d6

Error trace:
```sh
/Users/gsquire/scratch/test-swagger.go:14:2: could not import fmt (cannot find package "fmt" in any of:
	/usr/local/go/src/fmt (from $GOROOT)
	/Users/gsquire/gopath/src/fmt (from $GOPATH))
/Users/gsquire/scratch/test-swagger.go:15:2: could not import net/http (cannot find package "net/http" in any of:
	/usr/local/go/src/net/http (from $GOROOT)
	/Users/gsquire/gopath/src/net/http (from $GOPATH))
/Users/gsquire/scratch/test-swagger.go:18:14: undeclared name: http
/Users/gsquire/scratch/test-swagger.go:18:38: undeclared name: http
/Users/gsquire/scratch/test-swagger.go:19:2: undeclared name: fmt
/Users/gsquire/scratch/test-swagger.go:23:2: undeclared name: http
/Users/gsquire/scratch/test-swagger.go:24:2: undeclared name: http
```

**Comment by casualjim** [comment]
@gsquire  do you have a gopath set up? Does that code compile?

**Comment by gsquire** [comment]
Yes, it compiles and my $GOPATH is set up as well. Does my gist not work?

**Comment by casualjim** [comment]
I have problems getting this reproduced:

```shellsession
± ivan@paradox:~  
 » md /tmp/genbug    
± ivan@paradox:~  
 » cd /tmp/genbug 
± ivan@paradox:/tmp/genbug  
 » curl -OL'#' https://gist.githubusercontent.com/gsquire/cce277b4bd10ba283f4522e896dc91d6/raw/200e1e295574766ad8566af86bb562f15bc33cdf/test-swagger.go
######################################################################## 100.0%
± ivan@paradox:/tmp/genbug  
 » ls
test-swagger.go
± ivan@paradox:/tmp/genbug  
 » swagger generate spec -o swagger.json 
± ivan@paradox:/tmp/genbug  
 » ls
swagger.json  test-swagger.go
± ivan@paradox:/tmp/genbug  
 » cat swagger.json 
{"produces":["application/text"],"schemes":["http"],"swagger":"2.0","info":{"description":"The purpose is to demonstrate swagger docs for a test app."},"host":"localhost","paths":{},"definitions":{}}%    
```

**Comment by gsquire** [comment]
Are you on a Linux box? Like I said, I think it's a path issue since home brew installs it in a different location based on my output. I'll have to try on something that isn't mac.

**Comment by casualjim** [comment]
That was linux, here's my mac. My go is also installed through homebrew

```shellsession
± ivan@aether:~
 » md /tmp/gendebug
± ivan@aether:~
 » cd /tmp/gendebug
± ivan@aether:/tmp/gendebug
 » uname -a
Darwin aether.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
± ivan@aether:/tmp/gendebug
 » go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ivan/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.1/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
± ivan@aether:/tmp/gendebug
 » curl -OL'#' https://gist.githubusercontent.com/gsquire/cce277b4bd10ba283f4522e896dc91d6/raw/200e1e295574766ad8566af86bb562f15bc33cdf/test-swagger.go
######################################################################## 100.0%
± ivan@aether:/tmp/gendebug
 » ls
test-swagger.go
± ivan@aether:/tmp/gendebug
 » swagger generate spec
{"produces":["application/text"],"schemes":["http"],"swagger":"2.0","info":{"description":"The purpose is to demonstrate swagger docs for a test app."},"host":"localhost","paths":{},"definitions":{}}
± ivan@aether:/tmp/gendebug
 »
```

**Comment by gsquire** [comment]
Ok then...I'm stumped. Thanks for proving me wrong, I guess I need to try some other things.

**Comment by casualjim** [comment]
did you install your go from source perhaps? because your goroot seems different from mine

**Comment by gsquire** [comment]
I uninstalled go-swagger from brew, installed it from source and it worked. So strange. And no, I installed it through brew:

```sh
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gsquire/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.1/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
