### ISSUE TITLE
vendor extensions not respected

### ISSUE THREAD

**Issue by easeway** [go-swagger/go-swagger#402]
## Problem statement

The following vendor extensions are not respected when generating code:

- x-go-name
- x-go-package

In my situation, I generate commonly used data models in one package, and some other specs are referencing these common models. The server/client code is generated in a different package. When I'm using `$ref: "./common.yml#/definitions/Model"`, in the generated server/client code, no package name or package imports are generated, something like:

```
type ...Params struct {
    Data Model `json:...`
```

It should generate something like:

```
import (
...
    "mypkg"
)

...
type ...Params struct {
    Data mypkg.Model `json:...`
```

**Comment by danieljy** [comment]
@easeway I'm running into exactly your problem, but from a commit sha from only a few days ago.

Did you ever get this working?
Where are you inserting `x-go-name` and `x-go-package` so that your generated code properly imports and namespaces the types that are referenced?
