### ISSUE TITLE
No way to hook code after flags are parsed but before request handling starts

### ISSUE THREAD

**Issue by landofz** [go-swagger/go-swagger#403]
## Problem statement

I'm generating server stubs and basically need to hook some code to run after all the flags have been parsed but before server starts serving requests. I think this is a standard use case where you want to connect to storage (redis, postgres, ...) or load some configuration file but you want to get the info about the location of storage or file from command line flags.

In go-swagger 0.2.17. the `main.go` file was not overwritten after the initial generation unless you specifically asked for that so we could just add our own hook there. In swagger 0.4.0. the only file never overwritten is `config_xxx.go`. Its `configureAPI` function is called before flags are parsed so this can not be used.

The only option is to lazily connect/initialize in a request handler but I would rather not do that. Now I am using my own `main.go` and removing the go-swagger generated one.

Is there a way to do this that I haven't thought of or is this use case not supported at the moment?

**Comment by krasi-georgiev** [comment]
I need the same to initialize a db conneciton once and not on every request , but when I put some code inside the `configureFlags` that relies on the some custom flags it failes.

here is the gist
https://gist.github.com/krasi-georgiev/af1709549e58768c3b57150a26c8df67

by the way the file says `// Code generated by go-swagger; DO NOT EDIT.
` and than in the middle `// This file is safe to edit. Once it exists it will not be overwritten`

which exclude each other :)
