### ISSUE TITLE
mTLS with custom roots known to work?

### ISSUE THREAD

**Issue by ontucker** [go-swagger/go-swagger#409]
Has anybody used go-swagger to do end-to-end mutual TLS connections with client and server certificates issued from a custom CA?  I am having quite some difficulty, although I haven't exhaustively debugged it yet.  Just thought I'd ask here to see if it's known whether or not it will work.

The basic approach is to modify server.go to set `httpsServer.TLSConfig.ClientAuth = tls.RequestClientCert` and to override the client Transport's `TLSClientConfig` to have a `RootCAs` certpool which I've added my CA root cert to.  The client is reporting "x509: certificate signed by unknown authority."

I *am* able to get this to work with a simple no-swagger client using net/http directly to issue an HTTPS request with the same certs, so I don't think it's something wrong with the certs themselves.

**Comment by casualjim** [comment]
Getting this to work on on the client should be supported today.  But the server is missing the bits for the client auth to be validated.

for the client part:
https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todo_list_client.go#L23

that transport that gets created has a Transport property which is a http.RoundTripper. This should not be very hard to add to go-swagger.

https://github.com/go-swagger/go-swagger/blob/master/httpkit/client/runtime.go#L47

**Comment by ontucker** [comment]
This turned out to be me flubbing the path to the root cert file, so it's working now.  Regarding the server, I've worked around it temporarily by modifying my XyzHandler to pass the http.Request in along with the XyzParams:

```
type GetTestHandlerFunc func(GetTestParams, *http.Request) middleware.Responder
```
This lets the handler grab the TLS context and examine the certs to do client validation.

I'm not too enthused about this solution but it is working at the moment.  Perhaps I'll think of something better.  I could also do the client validation in some middleware but I need a way for middleware to set some app-specific context that the method handlers can see, because ultimately I want my method handlers to make some decisions based on the client's certificate.  If you have any suggestions I'm all ears.

**Comment by casualjim** [comment]
I think this might be fixed by 53c4f85

**Comment by vburenin** [comment]
yes, it fixes it. However, one thing I don't like it is a configuration options for HTTPS. I am forced to add them into different group of CLI parameters, which means --ca-cert option is teared apart from private key and cert config.

**Comment by ontucker** [comment]
This has veered off from having anything to do with custom root certs, of course.  It looks like some of the recent changes address the ability to see the TLS context in the request handlers, but I'm not sure 53c4f85 is the one I'd cite.  I have yet to try it out, but I saw a change go by that allowed access to the http.Request in the handlers, which would be perfect, as not only does it enable looking at the connection directly in the handlers, but it also allows one to use something like gorilla/context to pass arbitrary info between middleware and handlers.

**Comment by casualjim** [comment]
yes that went in as well. generated code now has access to *http.Request and gorilla context is already in use by go-swagger itself.

**Comment by ontucker** [comment]
I'm going to go ahead and close this even though I haven't tried it out.  If it doesn't work when I finally do, a new bug will make more sense anyway.
