### ISSUE TITLE
Add a configuration layer for TLS.

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#430]
This topic has already came up. It would be nice to be able to set own TLS config options like client cert validation, etc.
It seems like it is possible to just add an additional configuration hook into configure_xxx.go to set custom TLS options.

```diff
diff --git a/generator/templates/server/configureapi.gotmpl b/generator/templates/server/configureapi.gotmpl
index 33dd0ce..d74e269 100644
--- a/generator/templates/server/configureapi.gotmpl
+++ b/generator/templates/server/configureapi.gotmpl
@@ -2,6 +2,7 @@ package {{ .APIPackage }}

 import (
   "net/http"
+  "crypto/tls"

   errors "github.com/go-swagger/go-swagger/errors"
   httpkit "github.com/go-swagger/go-swagger/httpkit"
@@ -56,6 +57,11 @@ func configureAPI(api *{{.Package}}.{{ pascalize .Name }}API) http.Handler {
   return setupGlobalMiddleware(api.Serve(setupMiddlewares))
 }

+// The TLS configuration before HTTPS server starts.
+func configureTLS(tlsConfig *tls.Config) {
+  // Make all necessary changes to the TLS configuration here.
+}
+
 // The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
 // The middleware executes after routing but before authentication, binding and validation
 func setupMiddlewares(handler http.Handler) http.Handler {
diff --git a/generator/templates/server/server.gotmpl b/generator/templates/server/server.gotmpl
index bba5ad3..65b9134 100644
--- a/generator/templates/server/server.gotmpl
+++ b/generator/templates/server/server.gotmpl
@@ -110,6 +110,9 @@ func (s *Server) Serve() (err error) {
        httpsServer.TLSConfig.MinVersion = tls.VersionTLS11
        httpsServer.TLSConfig.Certificates = make([]tls.Certificate, 1)
        httpsServer.TLSConfig.Certificates[0], err = tls.LoadX509KeyPair(string(s.TLSCertificate), string(s.TLSCertificateKey))
+
+       configureTLS(httpsServer.TLSConfig)
+
        if err != nil {
                return err
        }
```

**Comment by casualjim** [comment]
feel free to send this as  a PR

**Comment by casualjim** [comment]
closed by #432

**Comment by tingxin** [comment]
Hi, I used swagger to build a simple go server, got this issue:
**the required flags `--tls-certificate` and `--tls-key` were not specified**
so how can i set the -tls-certificate and tls-key

**Comment by casualjim** [comment]
When you start the process you can specify them as arguments of environment variables.
You can also override the scheme by specifying `--scheme http`

**Comment by dominictracey** [comment]
I also ended up here coming from the [todo list tutorial](https://github.com/go-swagger/go-swagger/blob/master/docs/tutorial/todo-list.md) . Would you take a PR to add in the --scheme http to that doc?

**Comment by casualjim** [comment]
I just added a readme doc, but I'm running through the rest of the tutorial to see if it all still works.
It will be fixed today

**Comment by dominictracey** [comment]
FWIW, I'm getting a 404 rather than the expected 501 when I run the generated server.

**Comment by casualjim** [comment]
that is correct, which is why I haven't pushed my updates yet. Stay tuned will take a little while to get his back in shape

**Comment by casualjim** [comment]
once #1015 is merged the tutorial will work again
