### ISSUE TITLE
go-swagger v0.5.0 - cannot find package "golang.org/x/tools/go/buildutil"

### ISSUE THREAD

**Issue by Dr-Terrible** [go-swagger/go-swagger#434]
When compiling go-swagger v0.5.0 (the tarball from https://github.com/go-swagger/go-swagger/releases, git snapshot ff42df2), I got this error:

> agger/cmd/swagger
vendor/golang.org/x/tools/go/loader/util.go:17:2: cannot find package "golang.org/x/tools/go/buildutil" in any of:
	/var/tmp/portage/dev-util/go-swagger-0.5.0/work/gopath/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/buildutil (vendor tree)
	/usr/lib/go/src/golang.org/x/tools/go/buildutil (from $GOROOT)
	/var/tmp/portage/dev-util/go-swagger-0.5.0/work/gopath/src/golang.org/x/tools/go/buildutil (from $GOPATH)

The Go lang toolchain is right, there isn't a `golang.org/x/tools/go/buildutil` inside the vendor path of the  git snapshot [ff42df2](https://github.com/go-swagger/go-swagger/tree/ff42df2bf231f6a12383b36332f8364254ea86d6/vendor/golang.org/x/tools/go) (v0.5.0). This scenario makes impossible to properly package go-swagger for GNU/Linux source-based distributions such as Arch, and Gentoo due to missing bundled dependencies.

I am the maintainer of the Gentoo `ebuild` for go-swagger (you can find it [here](https://github.com/Dr-Terrible/go-overlay/tree/master/dev-util/go-swagger)), so I can easily circumvent the issue by manually update the missing dependency. Unfortunately, it will not be so easy to fix for other distributions, so I think it's worth fixing by upstream with an updated tarball (or a new version bump, whatever suits you better).

**Comment by casualjim** [comment]
is there something that can be worked out to gentoo support included in the release process?

**Comment by Dr-Terrible** [comment]
> is there something that can be worked out to get gentoo support included in the release process?

Sure, when there are new releases ready to be rolled out just warn me and I'll test a live git snapshot on x86_64, x86_32, and arm7+ (complete with Unit Testing). Then I'll report a success or whatever is amiss before the official release.

I do it regularly for several official packages; as a reference, take Asciinema work-flow as an example: https://github.com/asciinema/asciinema/issues/116  They use a specific issue with which new releases are signalled and then every GNU/Linux distribution maintainers report their feedbacks.

It works quite well as a solution, but in case I'm open to other suggestions too.
