### ISSUE TITLE
Generating spec for response without nested struct

### ISSUE THREAD

**Issue by mchaffie** [go-swagger/go-swagger#446]
I have an app that generates a JSON response body declared as follows:

// swagger:response Response
type Response struct {
	ResultCode string `json:"code"`
	Message string `json:"message"`
	ScanId string `json:"scan_id"`
	Filesize string `json:"filesize"`
	ContentType string `json:"content_type"`
	ScanResultUrl string `json:"scanresult_url"`
}

When I generate a Swagger spec from the go-swagger response markup the spec shows the response struct members as response headers:

<...>
responses:
  ScanResponse:
    headers:
      content_type:
        type: string
      filesize:
        type: string
      message:
        type: string
      scan_id:
        type: string
      scanresult_url:
        type: string

Questions: 
- is this expected behaviour?
- is there markup to express that my response is a simple JSON response body?

**Comment by casualjim** [comment]
Wrap it in another struct and decorate the property with `in: body`

**Comment by mchaffie** [comment]
Sure, could do that, but it means a nested layer in the JSON serialized to the client. Is that the only way?

**Comment by casualjim** [comment]
you can marshal instance.Body instead can't you? 
In fact you don't even have to instantiate the response wrapper. You can think of it as type checked documentation perhaps?

**Comment by mchaffie** [comment]
yup I can pass back the nested Body struct thanks. Not sure I love the idea of nesting my structs to support generation tho, for example, initializing with nesting seems a little awkward. Any interest in supporting spec generation with non-nested types?

**Comment by casualjim** [comment]
interest I have, it's often requested. I just don't have enough time to do all the things. so I'm not opposed to a pull request that makes this work.

perhaps with an annotation like `swagger:responseBody`

The main thing is the response stuff needs to exist, but we can create extra syntax to support unwrapped bodies. A swagger response is headers + body so that's why there is the requirement for wrapping at this moment.

What I mostly want to avoid is duplicating type information in doc comments, seems a waste of a perfectly good compiler.

**Comment by kojustin** [comment]
@casualjim, I would like this as well. If you could please point out where in the "swagger generate spec" code would be a good place to start exploring I could take a stab at this.

**Comment by casualjim** [comment]
this is the code that governs the response parsing:
https://github.com/go-swagger/go-swagger/blob/master/scan/responses.go#L122

perhaps an easy way to do this is to check for both in: Body and swagger:response annotations to be present. If they are then the type should be wrapped in a response without headers.

**Comment by bfirsh** [comment]
This is a blocker for us adopting go-swagger for Docker. I quite like the idea of `responseBody`.

Is anybody working on this? If I find some time I might dig into this.

**Comment by casualjim** [comment]
Somebody sent a PR for this last week, so on master this feature should be available.

https://github.com/go-swagger/go-swagger/commit/2f75b5703263c3565dc9aea4e15e0346471d35e2

**Comment by bfirsh** [comment]
Oh – _nice_! I'll give it a try.

Thanks!

**Comment by casualjim** [comment]
@bfirsh the issue is that when you don't have those structs, you're not documenting headers in your contract. A very common case for this is something like request id.

**Comment by bfirsh** [comment]
@casualjim I think all of our responses don't have any special headers, and adding Swagger annotations is much more palatable when there aren't hundreds of useless wrapper structs. ;)

**Comment by rcorre** [comment]
Does that PR actually allow you to avoid using wrapper structs? From the [docs](https://goswagger.io/generate/spec/model.html):

> Definitions only appear in the generated spec when they are actually used somewhere in the application (eg. on a params or response struct)

so ... do I need a wrapper struct anyways? Can a `swagger:route` directly refer to a `swagger:model` in the `Responses` section? It doesn't look like it ...

**Comment by casualjim** [comment]
you can if you use `200: body:ModelName`
we also since have added swagger:operation which gives you the ability to just write the yaml for the operation you're describing

**Comment by casualjim** [comment]
you will also need to add -m to generate spec `swagger generate spec -m ...`

**Comment by rcorre** [comment]
Yes, that seems to work. Thanks!
