### ISSUE TITLE
Support for JSON schema cross-file references.

### ISSUE THREAD

**Issue by chakrit** [go-swagger/go-swagger#45]
AFAIK This is valid JSON schema references:

```yaml
definitions: { '$ref': 'another-file.json#/definitions' }
```

This should be supported in `go-swagger`. Not sure how much effort is needed tho. This allows multiple schema to share definitions or for splitting large schema into smaller files, for example.

**Comment by casualjim** [comment]
I can't find it here as being supported: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#definitionsObject

I'll ask though and see if perhaps it should be.

**Comment by chakrit** [comment]
Its part of JSON Schema, which I think is what the swagger spec defers to. Not sure if the extent is specified in the schema, I'll dig up something. It does enable a lot of interesting use cases for the specs that we want to use, though.

**Comment by chakrit** [comment]
![image](https://cloud.githubusercontent.com/assets/45545/9090118/d6ca6104-3bc2-11e5-9352-19928bc22c59.jpg)

This is from the spec on the swagger.io site. So, yeah it is officially recommended :-)

**Comment by chakrit** [comment]
I'll see if I can help you with a PR

**Comment by casualjim** [comment]
There has been a bunch of discussion on these things in the swagger-spec repo. But as things stand, while json schema supports it, it's not supported for swagger at this point.
The markdown document linked to earlier is the source of truth for the swagger 2.0 spec definition.
it wouldn't be hard to support it, but swagger currently doesn't allow for it.

@webron  can you confirm that what I wrote here is the actual state of affairs

**Comment by webron** [comment]
People tend to confuse the structure of the Swagger spec with JSON Schema, because there are similarities between the two. That said, just because we have `definitions` in the Swagger spec, doesn't mean it's the same `definitions` as defined by JSON Schema. We use the same name, but it's not exactly the same thing. Right now, we do not allow referencing the entire `definitions` to an external source.

**Comment by chakrit** [comment]
@casualjim @webron the markdown you linked contained the exact same text. https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#file-structure

> However, parts of the definitions can be split into separate files, at the discretion of the user. This is applicable for $ref fields in the specification as follows from the JSON Schema definitions.

I'm not confusing swagger with JSON Schema, but this is in the spec. So if this shouldn't be supported, why is it still in the spec? Should it be removed?

**Comment by chakrit** [comment]
As I stated earlier though, the spec files gets large pretty quickly as we're adding features. The ability to compose them up from smaller files will be a very crucial feature for us soon.

**Comment by casualjim** [comment]
But you can reference to URL's not just to local files wherever you would reference the definition.
Things don't need to be defined in 1 file, but you also don't strictly need to import global definitions. You can just reference remote entities

```json
{ "$ref":  "http://someurl.somewhere.example/#definitions/Person" }
```

**Comment by chakrit** [comment]
So re-posting from the chat, in case anyone else's searching for this issue: Per-model reference works. Referencing the whole `definitions` key does not.

**WORKS:**

```yaml
definitions:
    User: { '$ref': 'another-file.json#/definitions/User' }
```

**ALSO WORKS:***

```yaml
definitions:
    User: { '$ref': 'http://example.com/swagger.json#/definitions/User' }
```

**DOES NOT WORKS**

```yaml
definitions: { '$ref': 'http://example.com/swagger.json#/definitions' }
```
