### ISSUE TITLE
x-nullable: false doesn't affect required values

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#458]
## Problem statement
With the recent change all required values are now pointers. Even though it is a valid and reasonable change from some points of view, it makes life much harder for me, GC and makes code ugly to work with generated models when required property can not be nullable and even zero value by design.

The similar problem affected not required values, many of them turned to be not nullable. However, I like this, because I have a control via "x-nullable: true" to turn them to be nullable when I want to. On the other hand, there is no way to use the same way to turn required properties to be not nullable.

So, the request is to make "x-nullable: false" to work with the required property.

**Comment by casualjim** [comment]
The trade-off that will be made with that is that you can't really validate requiredness on builtins without turning them into pointer values.

**Comment by vburenin** [comment]
I think, it is true if a value can get in to the range of a zero value. Otherwise, a zero value can be used as "nil/null".  For a "required validation error message" it can say "value is required and can not be nil or zero/empty".

**Comment by vburenin** [comment]
Here is a solution pull request that satisfies default behavior as well as user defined behavior: https://github.com/go-swagger/go-swagger/pull/459

**Comment by galaxie** [comment]
Now I am confused. I tested this commit from master [7f2565c](https://github.com/go-swagger/go-swagger/commit/7f2565cca6067d3bac6d2b666475ff1b0b5b2dad)
Assume that I have a definition:
```
    "newProfile": {
        "type": "object",
        "required": [
            "id"
        ],
        "properties": {
            "id":{
                "type": "integer",
                "x-nullable": true
            }
        }
    }
```

That was generated in models:
```
type NewProfile struct {

    /* id

    Required: true
    */
    ID *int64 `json:"id"`
}

func (m *NewProfile) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", int64(*m.ID)); err != nil {
		return err
	}
	return nil
}
```
So  `{"id": 0}`  is invalid by current version of `validate.Required`. And `{}` leads to a runtime panic `invalid memory address or nil pointer dereference`, because of this `int64(*m.ID)`
Desired behaviour is `{"id": 0}` - valid, `{}` - invalid, but no panic.
Am I correct?
Can you give some clarifications please?

**Comment by casualjim** [comment]
yes you're right, it's not supposed to generate code that looks like that because it's nullable. 
You can still go back to the tagged release though right?

**Comment by casualjim** [comment]
I get different code generated when I try this. For me there is no dereferencing and it considers nil.  This makes me wonder if the templates need to be regenerated for you.

the spec: https://github.com/go-swagger/go-swagger/blob/fa3e773f7ab6ec88bc3a6d9a3cd7bea8b0ef7b76/fixtures/codegen/todolist.models.yml#L28-L35
the test:
https://github.com/go-swagger/go-swagger/blob/fa3e773f7ab6ec88bc3a6d9a3cd7bea8b0ef7b76/generator/model_test.go#L1616-L1637

```go
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  strfmt "github.com/go-swagger/go-swagger/strfmt"

  "github.com/go-swagger/go-swagger/errors"
  "github.com/go-swagger/go-swagger/httpkit/validate"
)

/*NewProfile new profile

swagger:model newProfile
*/
type NewProfile struct {

  /* id

  Required: true
  */
  ID *int64 `json:"id"`
}

// Validate validates this new profile
func (m *NewProfile) Validate(formats strfmt.Registry) error {
  var res []error

  if err := m.validateID(formats); err != nil {
    // prop
    res = append(res, err)
  }

  if len(res) > 0 {
    return errors.CompositeValidationError(res...)
  }
  return nil
}

func (m *NewProfile) validateID(formats strfmt.Registry) error {

  if err := validate.Required("id", "body", m.ID); err != nil {
    return err
  }

  return nil
}
```

**Comment by dolmen** [comment]
If _all required values are now pointers_, this is a regression.
Why would a pointer be necessary if the value is required?

**Comment by dolmen** [comment]
If the pointer was added because the standard JSON unmarshaler does not allow to distinguish when a property is missing, this is the JSON parsing that must be fixed (for example by providing a custom `UnmarshalJSON` method that check for missing properties).

**Comment by casualjim** [comment]
please consider the opposite case, where you want to validate the struct not the json.  This use case is real on generated clients.

How do you distinguish between value-set and value-unset?

**Comment by vburenin** [comment]
I think there many opinions around this, I also tend to agree with Ivan. So, the same day I added an ability to enforce pointer/non-pointer value for required properties using x-nullable:true/false.

**Comment by galaxie** [comment]
@casualjim Yes, you are correct. I somehow messed the environment and stuck in previous version of the templates. Starting the server in a clean docker environment shows no issues with required fields. Shame on me.

**Comment by dolmen** [comment]
> please consider the opposite case, where you want to validate the struct not the json. This use case is real on generated clients.

It seems we have now a case where the model generation could be improved if it knew if the model is used for client or for server. 

> How do you distinguish between value-set and value-unset?

As I stated in #132 we should distinguish the case where the Go zero value is a valid value or not. A pointer is not needed if the Go zero value is not a valid value for the schema.

**Comment by casualjim** [comment]
@dolmen that behavior invalidates the required bit of the contract because if something isn't present but required then you don't get that error message. So why have the requirement there at all, if you want to catch it with another validation.

I'm not very happy with the way this is currently working. And it still is an issue for patching objects because with pointers we don't know if it was actually a value that was set or if it was a value that's nil.
So i think this will have to change one more time to use nullable types where set/unset is a property on the type. 
That keeps GC pressure lower, but I think that might create a need for 2 structs. 
One is the binding/validating struct and the second one is the one the user actually uses because a nullable type would kind of look like

```go
type NullableBool struct {
  value bool
  IsNull bool
  WasSet bool
}

func (n *NullableBool) Value() *bool  {
  if nIsNull {
    return nil
  } 
  return &n.value
}
```

The biggest benefit we derive from this is the ability to do patches on objects

**Comment by vburenin** [comment]
@dolmen You now can instruct swagger using x-nullable: false/true to generate a value or a pointer, it is totally up to. I am with you since I understand the problem, but I am also with Ivan since there some cases when such behavior is not desired. So, the best approach to me will be the usage of x-nullable where you wish to have a specific behavior.

**Comment by vburenin** [comment]
Closing as it is not longer the case.
