### ISSUE TITLE
generate spec doesn't add "swagger":2.0 at the beginning of the spec, but it's needed by swagger-ui

### ISSUE THREAD

**Issue by defcronyke** [go-swagger/go-swagger#46]
When trying to run swagger-ui with a swagger.json generated from your included petstore example, swagger-ui errors out with TypeError: spec is null

I compared the generated spec with the offical petstore swagger.json, and noticed "swagger":2.0 was missing from the beginning of the generated one, and after manually adding it, the generated spec then worked with swagger-ui.

Please fix the generator so that generated specs work with swagger-ui.

**Comment by casualjim** [comment]
the work around is simple: just start with a swagger.json file that has the missing bits.

**Comment by defcronyke** [comment]
My workaround was to use a bash script to inject the "swagger":2.0 at the beginning, after generating the spec, but I guess that works too. I hope you'll fix this though, since swagger 2.0 spec says the swagger field is required.

**Comment by defcronyke** [comment]
Just a quick followup to mention that the -o flag isn't working, so to save the spec to a swagger.json file, it was needed to use file redirection ( swagger generate spec > swagger.json ). Because of this, the workaround you mentioned won't work.

**Comment by defcronyke** [comment]
Upon further investigation, the field should be "swagger":"2.0" (the 2.0 must be a string), and also the "$schema" field must now be removed otherwise swagger-ui shows the swagger to be invalid.

**Comment by casualjim** [comment]
fixed by 00053a5aa
