### ISSUE TITLE
running on google app engine

### ISSUE THREAD

**Issue by defcronyke** [go-swagger/go-swagger#47]
App engine apps use some package imports which don't resolve when run with go build: "appengine", "appengine/datastore", etc. But it seems like "swagger generate spec" fails if it can't first build my app. To support app engine you'd need to remove that requirement. I would like to use go-swagger with my app engine project, so please make it parse the comments without first needing to build the app.

**Comment by defcronyke** [comment]
I tried adding the appengine build constraint, and it didn't error out, but it generated an empty spec.

**Comment by casualjim** [comment]
at this point we make use of the go loader package. This allows us to discover your application and which files to scan for the doc comments. 

This application needs to read composed structs and so on, and it's a lot easier to interrogate the application if you know where all the files are and not just the ones you created in this particular folder.
Unfortunately it does require to be able to read   

How about a main class that doesn't require appengine imports? 
I've personally never used appening so I don't really know what is involved.

**Comment by defcronyke** [comment]
For an app engine app, typically the main.go doesn't require any of the special appengine imports... however it uses an init() function instead of a main() function, and in there is where you instantiate the router and bind all the routes to handlers. It is the handlers (usually in their own separate files) which need the appengine imports.

I don't know if that's what you are asking about, but I know app engine fairly well so I can answer more questions if you have any.

**Comment by casualjim** [comment]
I guess what I mean is if your code doesn't compile, how are you running it?
And what I also meant is; if this is important to you, you could look at forking and submitting a pull request.
I, personally, still have a bunch of other things that need fixing in here before I want to look at a niche like appengine.

**Comment by defcronyke** [comment]
Fair enough, if you're not interested in supporting app engine that's fine. I did try forking to fix that other bug that I filed, but the code was a bit over my head so I wasn't able to fix it.

To answer your question, app engine apps don't get compiled with "go build", instead they are run on a dev server provided by the app engine SDK, and then they are deployed to app engine and run on the Google Cloud Platform infrastructure. The only reason they don't compile is because some of the packages ("appengine", "appengine/datastore", etc.) are only available in this SDK environment, they are not found in $GOPATH.

Maybe app engine could improve this situation in the future, and then go-swagger wouldn't have to change to support it, but as it stands now this will not work with any app engine apps that use any of the appengine-specific imports.

I will go back to using github.com/yvasiyarov/swagger for now, which doesn't require the app to build to generate the spec, but it is also not generating swagger 2.0, so I hope I can use your package sometime in the future.

**Comment by casualjim** [comment]
but the custom sdk they use also includes a custom go command doesn't it?
I think the problem you're having is related to your GOPATH content and can be fixed there.

afaik go always needs to compile your stuff, whether that's in the SDK env or not, have you tried installing go-swagger in the SDK provided GOPATH? 

I'll leave this open so i can track this

**Comment by defcronyke** [comment]
Hmm that is an interesting thought. I will experiment more on this today. The app engine SDK definitely uses the regular system GOPATH to resolve most of the includes, but it maybe has another internal GOPATH also, I'm not sure. Will post my findings a bit later.

**Comment by defcronyke** [comment]
Wow! You're right man! All that was needed to make generate spec work, was to add this to GOPATH:
<go_appengine_sdk_location>/goroot

The appengine includes are in there. It's working now, thanks for the insight!

**Comment by alanma** [comment]
@defcronyke @casualjim this thread is an awesome reading. I'm glad that I could use go+appengine+swagger with your validation. Thanks again for the discussion!
