### ISSUE TITLE
Fail and log on errors adding user-defined CLI flags

### ISSUE THREAD

**Issue by jad-b** [go-swagger/go-swagger#470]
## Problem statement
The current Go template for the generated server code in 'main.go' ignores the return values from `parser.AddGroup`, including possible errors. This results in a buggy `go-flags`-formatted struct quietly failing, making it confusing to the developer why their flags aren't showing up.

## Steps to reproduce
Define an invalid `go-flags` options struct. Add your flags in `configure_{api}.go:configureFlags`:

```go
type MyFlags struct {
    Verbose bool `short:"v"`
    Verbosity int   `short:"v"`
}

func configureFlags(api *operations.SwishAPI) {
    api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroups{
        {"verbosity", "verbosity levels", &MyFlags{}}
    }
}
```

Build and run your server: `go run cmd/api-server/main.go -h`. The user-defined flags don't appear.

## Solution
Update the loop that processes the CommandLineOptionsGroups to log and exit the start-up process:

```go
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatal(err)
		}
	}
```
Exiting the process is reasonable here, because the CLI flags are statically configured inside the code, and we want to alert the developer as soon as possible that they've made a mistake.
I have this, and a small comment inside `configureFlags` explaining how to add custom flags, ready to go in a PR.

**Comment by casualjim** [comment]
cool! look forward to it
