### ISSUE TITLE
Is there a way to set the "reason" or "response model" fields for a response?

### ISSUE THREAD

**Issue by defcronyke** [go-swagger/go-swagger#48]
I could not find a way to put a message or structure next to each response for an api route. In swagger-ui the response area just lists the response codes, but no description next to them. Is there a way to populate these fields using code comments (with generate spec)?

**Comment by casualjim** [comment]
the server generator on master now supports the response model part of this issue.
Still no way to set the reason

**Comment by casualjim** [comment]
Looks like there won't be a way to set the response reason for the go http server.

Closing this now:
https://github.com/golang/go/issues/8990

**Comment by mehdy** [comment]
but I think it still would be nice to implement the feature. I really want to set some custom reason because it really makes sense in swagger-ui.
something like this maybe:
```
/*
...
        409: 
          ref: UserResponse
      	  reason: username already exists
...
*/
```
any idea?
