### ISSUE TITLE
Can access original request object in handlers

### ISSUE THREAD

**Issue by Brian-McM** [go-swagger/go-swagger#491]
I'm trying to add functionality add trace headers to logs and I want this trace header to be available everywhere. I looked into using gorilla context but it requires that I have access to the original request object in the handler, but I only have access to the params object generated by go swagger. How can I get the original request object in my handler, that is, the http.Request object?

**Comment by casualjim** [comment]
what we did was make a middleware that sets the X-Request-ID field when it's empty on the front router.
Then we described a header on every params object. Each handler has access to the request id in this case.

That being said in the next version of swagger there is also a Request object that's available on every params struct.

**Comment by Brian-McM** [comment]
ok sweet thanks. When's the next swagger version coming out?

**Comment by Brian-McM** [comment]
Actually, I'm not seeing a way to get the header from the params object. What version is this in? Besides the request values, I only have BindRequest available to me.

**Comment by casualjim** [comment]
you can define your spec like this (clients also need to pass it through if it exists so it is part of the contract)

```yaml
parameters:
  requestId:
    name: X-Request-Id
    in: header
    type: string

paths:
  /:
    parameters:
      - $ref: "#/parameters/requestId"
```

**Comment by Brian-McM** [comment]
So the X-Request-Id isn't isn't being set after I add this. Here's my swagger:

/score:
    post:
      parameters:
        - name: X-Request-Id
          in: header
          type: string
        - name: recipients
          in: body
          description: A list of recipient emails to score
          required: true
          schema: 
            $ref: '#/definitions/PostScoreRequest'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/RecipientListScore'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'

**Comment by casualjim** [comment]
in configure_xxx.go

```
import "github.com/satori/go.uuid"

func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return addRequestID(handler)
}


func addRequestID(handler http.Handler) http.Handler {
	var reqIDKey = http.CanonicalHeaderKey("x-request-id")

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get(reqIDKey) == "" {
			r.Header.Set(reqIDKey, uuid.NewV4().String())
		}
	})
}
```

**Comment by casualjim** [comment]
please don't close this ticket, I think this required for more people. I like to leave questions like this open so they are easier to find.

**Comment by Brian-McM** [comment]
I won't, I'll try this out. Thanks for the quick responses!

**Comment by casualjim** [comment]
I assume things worked after adding this last step?

**Comment by Brian-McM** [comment]
Yes and no. I still couldn't get a map to the request object, because that id is a randomly generated one (remember, I need the http.Request object to get a request context using gorilla libraries). However, I made my own request context map that uses that id as the key and I pass that id through to the parameters in the request.

As great as I think go swagger is, I think it's not great that you get ride of the original request object and feed in your own. That potentially makes a lot of great http golang libraries, like the one mentioned, useless as the require items from that requests object, or the request object itself as it's used to map values. It would be great to have this in the future so that I don't have to make my swagger spec include a request ID just so I can pass through a context ID to my handlers.

**Comment by casualjim** [comment]
you can install go-swagger with go get, if you then regenerate you should have access to the request object.

There is one more change I want to make inside go-swagger to use pointers for builtins.

**Comment by casualjim** [comment]
this is now available as a part of the parameter struct
