### ISSUE TITLE
How to use context.Context from middleware

### ISSUE THREAD

**Issue by shirou** [go-swagger/go-swagger#492]
Thank you for developing very useful tool!

## Problem statement

I generated a source code with `--with-context` and I want to use `context.Context` on a middleware.
But, it seems context is created after middleware are invoked like [here](https://github.com/go-swagger/go-swagger/blob/4b4f832be2b3869d0ecfd5baa9fda046696d9712/generator/templates/server/operation.gotmpl#L69).

Could you tell me how to set something on a middleware and use it from HandlerFuncs?

refs. #96

Thanks!

## Swagger specification

nil

## Steps to reproduce

nil

**Comment by frosenberg** [comment]
I have the same problem right now. I would like the middleware to inject some value in the context that I can later re-use in my actual http handlers. Any way to do this?

**Comment by ontucker** [comment]
Here's an example of middleware setting a "clientCert" value in the context to pass the client TLS certificate along to the handlers.
```
// SetupMiddlewares - configure the higher-level middleware
func (s *MyServer) SetupMiddlewares(handler http.Handler) http.Handler {
	ourFunc := func(w http.ResponseWriter, r *http.Request) {

		if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
			context.Set(r, "clientCert", r.TLS.PeerCertificates[0])
		}

		handler.ServeHTTP(w, r)
	}
	return http.HandlerFunc(ourFunc)
}
```

And in the handler, you can get the cert like this (since you have the HTTP.Request object):
```
	clientCertIntf, ok := context.GetOk(req, "clientCert")
	if !ok {
		fmt.Printf("This request has no client cert.\n")
		return nil
	}
	clientCert, ok := clientCertIntf.(*x509.Certificate)
	if !ok {
		return nil
	}
```

**Comment by frosenberg** [comment]
Thanks for your fast response. I see that the context object you are using is from `github.com/gorilla/context`. I was actually looking at the `golang.org/x/net/context` one b/c that is what I have available in my handler (I called `swagger generate` with `--with-context`). I'm not sure these two contexts are compatible...

**Comment by ontucker** [comment]
Ah, sorry, I missed that.  Never mind. :)

**Comment by casualjim** [comment]
yeah that integration is not fully baked as there is no opportunity to provide your own.
In the handler you get a fresh context that is request scoped. Perhaps a good approach would be to allow people to override the context with a value at well-known key in the gorilla context dictionary.

I have a branch where it's all net.context but I did run into some issues with it so I never merged that.

**Comment by frosenberg** [comment]
@ontucker thanks anyway, so I learned about the gorilla context :).

@casualjim yeah that might work too. What were the problem you ran into? I would really like to see net.context available in handlers any time soon :)

**Comment by casualjim** [comment]
they are now in handlers because we expose the Request in Params and on 1.7 you have a context.
