### ISSUE TITLE
generator: handling embedded interfaces

### ISSUE THREAD

**Issue by fsouza** [go-swagger/go-swagger#493]
I'm using an embedded interface as part of a response struct, and it fails with the error message "unable to resolve embedded struct for: Resulter".

Part of the code:

``` go
type Resulter interface {
    Result() (int, interface{}, error)
}

type jobResponse struct {
    // in: body
    Payload *partialJob

    Resulter
}
```

I can provide more details if that's desired. Should go-swagger ignore embedded interfaces?

**Comment by casualjim** [comment]
yeah I think go-swagger should ignore embedded interfaces, at the very least we could add an annotation to make it be ignored

**Comment by zasran** [comment]
Seems like embedded interface does not cause error anymore, maybe this fixed it https://github.com/go-swagger/go-swagger/commit/6a060045f0c71475b6932bfd327387af081adcec

It seems the embedded interface is ignored (don't see it in generated json) but there is a function in scan/schema.go parseInterfaceType that parses interface. Given that the interface in Go can only have functions which will never be part of Rest API, why is interface parsed?

**Comment by casualjim** [comment]
we have a pattern for discriminators. For those it parses the 0-arity methods as properties.
