### ISSUE TITLE
Negotiated content type producer uses DefaultProduces even when matched route does not have a "produces" for that type.

### ISSUE THREAD

**Issue by ontucker** [go-swagger/go-swagger#499]
When I create a method which produces only a non-default content-type, the `Respond()` code in package `middleware` context.go always uses the DefaultProduces content-type instead of the type specified by the spec.  This is because it initializes the `offers` array with the DefaultProduces value and then appends the passed-in `produces` values to it, and NegotiateContentType ends up choosing the first item in the array. 

The method's "produces" specification should override the default, shouldn't it?  Further, I don't see any way to specify a method which doesn't produce the API's default content type at all.

Given the spec below in an API which has a default content-type of application/json, the only way I can get the method to return text/plain is to explicitly specify that in an Accept header.

## Swagger specification
```
            "get": {
                "produces": [
                    "text/plain"
                ],
                "responses": {
                    "200": {
                        "description": "blah blah"
                    }
                }
            }
```

**Comment by ontucker** [comment]
Just moving `c.api.DefaultProduces()` to the _end_ of the `offers` array in `Respond()` (making it a fallback in case of non-matching) produces the result that seems correct to me, although it still doesn't address the issue of making a method which _doesn't_ produce the default content-type.

**Comment by casualjim** [comment]
is it possible that you are using a released version and aren't tracking master? These issues existed but I thought they were fixed. I misinterpreted how to deal with produces and consumes at an operation level, but I think that got fixed.

**Comment by Vadskye** [comment]
I think this was fixed in https://github.com/go-openapi/runtime/pull/4.

**Comment by casualjim** [comment]
I agree
