### ISSUE TITLE
APIs.guru: test on 200+ Swagger files for real-life APIs

### ISSUE THREAD

**Issue by IvanGoncharov** [go-swagger/go-swagger#501]
In #416 you included one of the Swagger files from my [catalog](https://github.com/APIs-guru/api-models).  Maybe you interested in testing against rest of 200+ Swagger files.
This can be done through [REST API](https://github.com/APIs-guru/api-models) to my catalog.

**Comment by casualjim** [comment]
http://i.imgur.com/3DJIFSC.gifv

**Comment by IvanGoncharov** [comment]
@casualjim Maybe I can help you to chew this cucumber :smile: 
If you have some question or feature requests, please [open an issue](https://github.com/APIs-guru/api-models/issues/new).
We can also chat in Gitter: https://gitter.im/APIs-guru/api-models
