### ISSUE TITLE
generate spec doesn't fill in the description field for responses, which is required.

### ISSUE THREAD

**Issue by defcronyke** [go-swagger/go-swagger#51]
I tried a few kinds of comments and none of them got the description filled:

// swagger:response photoResponse [description here]
This one caused the response to not get added to the generated spec at all.

// swagger:response photoResponse
//
// [description here]
This one did not get the description filled in, but the response was added to the spec.

// [description here]
// swagger:response photoResponse
This one got the description filled as the "title" field for that particular object, but not as a description for the response.

**Comment by casualjim** [comment]
Would the following solution work better (not yet implemented though)

```
responses:
default:errorResponse:Generic Error
200:photoResponse:multi word description
```

**Comment by defcronyke** [comment]
Sure that looks good to me.

**Comment by casualjim** [comment]
In the end it was easier to just reuse the documentation on the response struct. So that's what it is doing. It's not using the syntax proposed earlier.
