### ISSUE TITLE
Swagger generate spec paths

### ISSUE THREAD

**Issue by gsquire** [go-swagger/go-swagger#510]
When trying to generate a swagger spec from my Go code annotations it will fail sometimes saying it cannot find an external package in `$GOPATH`, `$GOROOT`, etc.

I use [gb](https://getgb.io) to build my app and it uses a folder called `vendor/src` to store third-party dependencies. I would prefer not to have to also add these dependencies to my `$GOPATH` just to generate docs.

Can this be added as a path to search like the `vendor` directory was added for Go 1.6 and above?

**Comment by casualjim** [comment]
We use the regular go infrastructure to discover these items. I'm not sure what is required to support gb seamlessly. I wouldn't be opposed to a PR or more discussion here so that we know what needs to happen and an interesting party could pick it up easily.

**Comment by gsquire** [comment]
I can dig into the code today and see. It makes sense to not want to support every third party tool for dependency management since they are a dime a dozen, but if it's trivial to add then that would be awesome.

**Comment by gsquire** [comment]
So I think the line that generates the error I am seeing is [here](https://github.com/go-swagger/go-swagger/blob/dccba1c40fcbec15a1926b5742e23291a0ebaab2/vendor/golang.org/x/tools/imports/fix.go#L290). Since this uses the Go standard library parser, I can see not wanting to patch this. You can go ahead and close this if you agree.

**Comment by casualjim** [comment]
I think an easy solution to this could be to look if a vendor dir exists and if it has a src folder and then just manipulate the gopath in the swagger scan process

**Comment by casualjim** [comment]
and I think it can be done by manipulating this method: https://github.com/go-swagger/go-swagger/blob/master/scan/scanner.go#L165

**Comment by gsquire** [comment]
Yeah I think adding a slice of "extra" paths to the options struct and then calling `Import` could be an option.

**Comment by gsquire** [comment]
I ended up moving to another build tool so I will close this issue. Thanks again.
