### ISSUE TITLE
File downloads

### ISSUE THREAD

**Issue by fiorix** [go-swagger/go-swagger#515]
## Problem statement
If the response type of one of your endpoints is type=file, the generated Go code returns a runtime.File, which is meant for uploads. My case is an API that returns mostly JSON, but some of the endpoints return files associated to users.

## Swagger specification

Here's my spec, without the actual API, only the file download endpoint:

```
swagger: "2.0"
info:
  description: API + File download
  title: Test
  version: 1.0.0
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /some/file.txt:
    get:
      operationId: someFile
      produces:
      - application/octet-stream
      responses:
        200:
          description: download file
          schema:
            type: file
```

## Steps to reproduce

Generate the code, look at restpi/operations/some_file_response.go:

```
type SomeFileOK struct {                                                        
                                                                                
        // In: body                                                             
        Payload runtime.File `json:"body,omitempty"`                            
}                                                                               
```

That is definitely not what I want. I started looking around in the swagger package and go-openapi for a middleware.Responder for octet streams and couldn't find one. I'm currently using this as a workaround in my handlers:

```
func NewOctetStream(f *os.File) middleware.Responder {
        return middleware.ResponderFunc(func(w http.ResponseWriter, _ runtime.Producer) {
                fn := filepath.Base(f.Name())
                w.Header().Set("Content-Type", "application/octet-stream")
                w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%q", fn))
                io.Copy(w, f)
                f.Close()
        })
}
```

There are many downsides to this despite solving my problem. For one, looks very hack-ish because the producer is ignored. Also, you cannot `defer f.Close()` in the handler, because the middleware executes after you return. That forces me to take ownership of the file in the mw and close it there.

Is this a gap in the current implementation or am I completely off?

**Comment by casualjim** [comment]
you could use, I know it's a bit counter intuitive:
 
type: string
format: binary

but I believe that will get you an io.Reader/io.Writer which in turn is a bit more appropriate.
You'd still need the responder you wrote though

**Comment by frosenberg** [comment]
I tried using string and format `binary`. Why do I get an `io.Writer` as a results on the client?

**Comment by casualjim** [comment]
the body of the request is a reader that you're presumably going to write somewhere.

There is a fix I made for this but I put it in a wip branch, I'll put it on master this weekend. 
You will still get a writer back though because presumably you want to save the files somewhere and don't want to hold the entire thing in memory. The generated code takes care of draining the response body reader with the writer

**Comment by frosenberg** [comment]
I'm not sure I follow. Maybe you have a sample of can point me to the code.

**Comment by casualjim** [comment]
I'll get you a sample after I've added the fix to master is that ok?

**Comment by frosenberg** [comment]
@casualjim has the fix gone into master yet?

**Comment by casualjim** [comment]
not yet, but this weekend I'll have time to do it. Some rush work thing came in on friday morning that took me until sunday to do

**Comment by fiorix** [comment]
What does the API look like with this change? I'm curious.

**Comment by casualjim** [comment]
you pass in the writer for receiving the response body to the method on the client.

```go
client.GetSomethingWithAStream(new(some.Params), bytes.NewBuffer(nil))
```

you have control over the writer, creating and closing is up to you, the generated client ensures bytes are written to it when they appear on the stream.

**Comment by frosenberg** [comment]
Works for me! Thanks
