### ISSUE TITLE
Generate models for internal use only

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#516]
## Idea
Sometimes it is just useful to have a model that I could use internally (config, etc). Of course, I could use a protobuf or something similar to generate them, but it feels a little redundant if swagger can already generate models from the spec even with validators - which is really good for things like config.

So, it would be awesome to add some separate model generator to just generate models without any APIs, etc.

Thoughts?

**Comment by casualjim** [comment]
you can use `swagger generate models` for this

**Comment by vburenin** [comment]
It is already in! Yay!
