### ISSUE TITLE
Skip parameter fields with json tag `json:"-"`

### ISSUE THREAD

**Issue by jlburkhead** [go-swagger/go-swagger#520]
## Problem statement

From the generation docs:
```
Annotation syntax

If you want to exclude something from the spec generation process you can try with the struct tag: json:"-"
```

I'm not sure which generation parsing rules follow that, but `swagger:parameters` do not skip fields with that json tag. Would be nice to be able to hide fields from swagger without making them unexported. 

## Steps to reproduce

```go
// Params struct
//
// swagger:parameters someOperation
type Params struct {
        // The value
        Value string `json:"-"`
        // Some other value
        // in: query
        OtherValue string `json:"other_value"`
}
```

running `$ swagger generate spec ...` will still include Value in the generated `swagger.json`

**Comment by jlburkhead** [comment]
closing since the pr for this was merged

**Comment by Hectorhammett** [comment]
Is it possible to add to Swagger an json:"-" field? Basically the other way around of this post.

**Comment by fredbi** [comment]
@Hectorhammett try extension x-go-custom-tag (applies to schema object properties)

**Comment by Hectorhammett** [comment]
@fredbi  Thanks for the response! I will try it on the next days and will response the results. Thanks!
