### ISSUE TITLE
where is the spec validator tested

### ISSUE THREAD

**Issue by haroldcarr** [go-swagger/go-swagger#525]
go-swagger/vendor/github.com/go-openapi/validate/* (especially spec.go)

has code that performs "semantic" validation of a swagger document.

In the past I found

    go-swagger/validate/

for running tests, and

    go-swagger/fixtures/validation

as json input to the tests.

Where is the validator test code and input files?

**Comment by casualjim** [comment]
https://github.com/go-openapi/validate

**Comment by haroldcarr** [comment]
thanks
