### ISSUE TITLE
Validation:"swagger" field must validate against schema

### ISSUE THREAD

**Issue by itgirlalice** [go-swagger/go-swagger#53]
When missing "swagger" field, the validation passed. But the "swagger" field is required in schema， so it should validate against schema.

BTY, there are three required filed "swagger", "info" and "paths", but the validation result is different.
1. Missing "swagger" field, validation pass.
2. Missing "info", validation failure failed, get error message ".info in body is required".
3. Missing "paths", get "nil pointer dereference" error, the related issue #52.

So hope the 1 and 3 could be fixed.

**Comment by itgirlalice** [comment]
@casualjim 
Hi casualjim, do we have any plan on this issue?

Thanks,
Alice

**Comment by casualjim** [comment]
Yes I'll try to fix some this weekend.
The swagger version fix is relatively easy, haven't really looked into the other one yetj
