### ISSUE TITLE
Code generation error for binary stream producer, consumer

### ISSUE THREAD

**Issue by sflxn** [go-swagger/go-swagger#533]
We've found a scenario on our project where the code generated response correctly assumes the payload is an io.reader but tries to reflate the response as a consumer (from client side) and incorrectly assumes an io.writer.  @casualjim and I have realized that is incorrect.

If you specify a binary stream is your response like the following example,

``` yaml
'200':
  schema:
    format: binary
```

It generates client code that correctly creates an io.Reader payload.  However, the reflation code eventually dives into ByteStream.go, and the following code tries to interpret it as an io.Writer:

``` go
func ByteStreamConsumer() Consumer {
  return ConsumerFunc(func(r io.Reader, v interface{}) error {
    wrtr, ok := v.(io.Writer)
    if !ok {
      return errors.New("ByteStreamConsumer can only deal with io.Writer")
    }

    _, err := io.Copy(wrtr, r)
    return err
  })
}
```

**Comment by frosenberg** [comment]
I don't think the client code seems to be correctly generated. I see a `io.Writer` on the client side.

**Comment by baronfel** [comment]
Ditto here!  If you have a response type of file, the `response.Payload` is of type `*multipart.File` which doesn't implement `io.Writer` and so the ByteStreamConsumer blows up there when I try to use it in an io.Copy similar to the above.

**Comment by keithballdotnet** [comment]
I am also encountering this issue.

**Comment by keithballdotnet** [comment]
how about just replacing the string / binary with []byte ?
