### ISSUE TITLE
todolist example fails to compile. Also the generated and the example code has different imports, which is strange

### ISSUE THREAD

**Issue by joeblew99** [go-swagger/go-swagger#538]
## Problem statement

When i do the todo list tutorial and generate the code,  the todo-list/restapi/configure_todo_list.go has: 
import errors "github.com/go-swagger/go-swagger/errors", and refuses to compile.

But when i look at the example in the go-swagger repo, the todo-list/restapi/configure_todo_list.go has:
errors "github.com/go-openapi/errors"

Please remove the sections that don't apply

## Steps to reproduce
I have latest golang, and am using the latest binary of swagger to do my generation from.

**Comment by casualjim** [comment]
is it possible that you have a stale go-swagger checkout on your system?

Does the following fix your issue?

```
rm -rf $GOPATH/src/github.com/go-swagger/go-swagger
go get -u github.com./go-swagger/go-swagger/cmd/swagger
```

**Comment by joeblew99** [comment]
ok that fixed it.

all the build errors are gone
I use gvt for vendoring and had to just bring in 2 or 3 libs from the openAPI account:
https://github.com/go-openapi/

But i have one line that will not compile and not sure if its your code or a lib:

From /cmd/todo-list-server:
````
x-MacBook-Pro:todo-list-server apple$ go build
# github.com/test/go-gedw99/go-service/restapi/operations/todos
../../restapi/operations/todos/get_parameters.go:49: undefined: middleware in middleware.MatchedRoute

```

**Comment by casualjim** [comment]
you may still need to get

```
gvt fetch github.com/go-openapi/runtime/middleware
```

**Comment by joeblew99** [comment]
no its not that. gvt already brought it in via the 
````
gvt fetch  github.com/go-openapi/runtime
`````
Still hunting for what it might be.

**Comment by joeblew99** [comment]
I got the todo-list  & task-tracker working off yml and json files.
BTW i used a generic YAML --> JSON tool to make JSON and it works perfectly.
It also can convert the other way. Might be useful for you , because you can automate it in the core CI / testing if you want.

I am not even sure what i did to get it working. I know its weird.
