### ISSUE TITLE
Fix "Use" section tutorials on goswagger.io

### ISSUE THREAD

**Issue by manisenkov** [go-swagger/go-swagger#539]
## Problem statement

There's supposed to be two tutorials in the "Use" section on [goswagger.io](https://goswagger.io) web site - https://goswagger.io/tutorial/dynamic/ and https://goswagger.io/untyped/server/. Pages look incomplete and abandoned, so I'd propose to remove or complete them to avoid confusion.

**Comment by kayla90** [comment]
I'm also trying to access the dynamic API definition page and it is not finished. Is that dynamic API definition still a feature?

**Comment by casualjim** [comment]
dynamic API is definitely a working use case. 
Unfortunately I haven't been able to document its usage properly.

Here's a petstore with the dynamic usage

https://github.com/go-openapi/runtime/blob/master/internal/testing/simplepetstore/api.go
https://github.com/go-openapi/runtime/blob/master/internal/testing/simplepetstore/api_test.go

Here's an example of a petstore that uses structs as types:

https://github.com/go-openapi/runtime/blob/master/internal/testing/petstore/api.go#L32-L68

**Comment by manisenkov** [comment]
Since new documentation website is released, I think this issue could be closed.
