### ISSUE TITLE
Generated imports for models are incorrect

### ISSUE THREAD

**Issue by darkcrux** [go-swagger/go-swagger#54]
When using `swagger generate server -f swagger.yml -A myApp`, the imports for the model in the code inside `restapi/operations` are incorrect. 

The import statement looks like this:

```
import (
	"net/http"

	"github.com/myRepo/myApp/operations/models"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
)
```

The models are in `github.com/myRepo/myApp/models` and not in `github.com/myRepo/myApp/operations/models`.

This causes compile errors.

**Comment by casualjim** [comment]
I botched a merge this weekend and I'm catching up. Please keep submitting issues as you find them though.

If it's critical to what you're trying to do, the latest working version of the server generator was: 797d4ba62b1
