### ISSUE TITLE
Override struct type in json struct tag?

### ISSUE THREAD

**Issue by lukeautry** [go-swagger/go-swagger#543]
Hey all - thanks for all the work done on this great library, I'm currently looking at it to generate API clients/docs for an API.

As an example, I have a struct:

`
type User struct {
     Id int64`json:"id"`
     Name sql.NullString`json:"name"`
}
`

sql.NullString, of course, looks like this:

`type NullString struct {
    String string
    Valid  bool
}`

Based on the way we process data as it comes out of the database and write the request. we don't actually return a type NullString, we just return a regular string value. I was hoping that maybe I'd be able to add the primitive type to the struct tag like so:

`
type User struct {
     Id int64`json:"id"`
     Name sql.NullString`json:"name,string"`
}
`

Unfortunately, that doesn't seem to do the trick. Is there an "idiomatic" way to accomplish what I'm going for here? To put it simply: my goal is to be able to override the generated type for a struct field.

**Comment by nathanwilk7** [comment]
I have precisely the same issue. @lukeautry, could I ask if you ever found a workaround?

**Comment by nathanwilk7** [comment]
Also, I'm not familiar with how go-swagger works, but could the spec generator use MarshalJSON to generate the response schema?

**Comment by casualjim** [comment]
It can't because it needs to describe the types. 
I think a PR was submitted in the last 2 months that allows for specifying a type. 
`swagger:type typename`

added by: ca670fa
