### ISSUE TITLE
Build failure when using principal flag.

### ISSUE THREAD

**Issue by williambailey** [go-swagger/go-swagger#544]
## Problem statement

If i try to use the `--principal` flag during server generation the resulting code fails to compile.

`swagger version` returns `0.5.0-118-gfffb4b0`

### Swagger specification

The specification needs to include a security definition. e.g.

```yaml
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
```

### Steps to reproduce

```bash
swagger generate server --principal=my.Principal
```

```bash
go build
...
my_api.go:174: cannot use o.BearerAuth (type func(string) (*my.Principal, error))
as type security.TokenAuthentication in argument to security.APIKeyAuth
```

To resolve the issue all I had to do was alter 2 of the generated files.

*example_api.go*
```diff
- BearerAuth func(string) (*my.Principal, error)
+ BearerAuth func(string) (interface{}, error)
```

*configure_example.go*
```diff
- api.BearerAuth = func(token string) (*my.Principal, error) {
+ api.BearerAuth = func(token string) (interface{}, error) {
```

I was then successfully able to `return &my.Principal{...}, nil` from `configure_example.go` and have it passed into the api handler with the correct type. 

*configure_example.go*
```
api.ExampleOpHandler = example.OpHandlerFunc(func(ctx context.Context, params example.OpGetParams, principal *my.Principal) middleware.Responder {
    foo := principal.Foo
    // ...
}
```

**Comment by aocole** [comment]
I have seen this as well

**Comment by casualjim** [comment]
Does the principal exist as a struct? is it described in the swagger specification?

**Comment by williambailey** [comment]
I must admit that I only ever tried a struct and not an interface. However the outcome is the same if its a struct created from a definition in the swagger specification file or if its a standalone struct defined in another library.

**Comment by casualjim** [comment]
oic, yes this would be an issue

**Comment by frosenberg** [comment]
I see the same thing after updating to the latest go-swagger. My principle is a custom struct too.

**Comment by klaasn** [comment]
For what I see the bug was introduced in the oauth2 merge here:

https://github.com/go-swagger/go-swagger/commit/8ed1d59afc9a52f05f035c7ff299cd1757a1b799

Line 150 has been "simplified" and the bug was introduced. The footprint of the API key function is not
func(string) ({}interface, error) when a custom principal is used, so a type error appears.

**Comment by klaasn** [comment]
Works for me now.
