### ISSUE TITLE
go-swagger v0.5.9 - cannot find package "golang.org/x/tools/go/loader"

### ISSUE THREAD

**Issue by Dr-Terrible** [go-swagger/go-swagger#549]
When compiling go-swagger v0.5.9 (the tarball from https://github.com/go-swagger/go-swagger/releases, git snapshot fade7c6), I got this error:

> go-swagger/cmd/swagger
scan/classifier.go:21:2: cannot find package "golang.org/x/tools/go/loader" in any of:
	/var/tmp/portage/dev-util/go-swagger-0.5.9/work/gopath/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/go/loader (vendor tree)
	/usr/lib/go/src/golang.org/x/tools/go/loader (from $GOROOT)
	/var/tmp/portage/dev-util/go-swagger-0.5.9/work/gopath/src/golang.org/x/tools/go/loader (from $GOPATH)
generator/shared.go:30:2: cannot find package "golang.org/x/tools/imports" in any of:
	/var/tmp/portage/dev-util/go-swagger-0.5.9/work/gopath/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports (vendor tree)
	/usr/lib/go/src/golang.org/x/tools/imports (from $GOROOT)
	/var/tmp/portage/dev-util/go-swagger-0.5.9/work/gopath/src/golang.org/x/tools/imports (from $GOPATH)

It's the same issue from #434, but on a different `golang.org/x/tools` subpackage.

**Comment by casualjim** [comment]
What is the go version you're using?
that release never got published though so perhaps in this case it's not too bad. 
However I want to find out what is causing this build failure and why none of my ci envs pick it up.

**Comment by Dr-Terrible** [comment]
> What is the go version you're using?

go-1.6.1, and go-1.6.2

> However I want to find out what is causing this build failure and why none of my ci envs pick it up.

I can only guess: your CI environments have a copy of the missing subpackes somewhere inside your GOPATH or GOROOT, leading to a successful compilation even if those subpackages are not present in the `vendor` directory.  When I package go-swagger for Gentoo/Linux I use a GOROOT/GOPATH workspace where there is nothing inside except for the go standard library (usually in `/usr/lib/go`), making easy to detect missing vendored dependencies.

I would check for copies of the `golang.org/x/tools` package with `find` on all yours CI envs; in case, make sure that you are not reusing old precompiled go-objects by removing all the `pkg` subdirectory every time you run a test on the CI envs.

**Comment by casualjim** [comment]
i tagged a new release, I hope this makes it all work

https://github.com/go-swagger/go-swagger/releases/tag/0.6.0

**Comment by Dr-Terrible** [comment]
Thank you @casualjim. v0.6.0 successfully packaged for [Gentoo/Linux](https://github.com/Dr-Terrible/go-overlay/tree/master/dev-util/go-swagger) without any problems. :+1: 

Everything compiles as expected, and go-swagger seems to work correctly :)

**Comment by casualjim** [comment]
Great! I'm doing a 0.7.0 soonish, one doc to write and then migrating the release build to circleci.
