### ISSUE TITLE
bind{Param} function may need casting for UUID

### ISSUE THREAD

**Issue by darkcrux** [go-swagger/go-swagger#55]
compiling a generated server with path parameters defined as `type: string` and `format: uuid` throws this error: `cannot use raw (type string) as type strfmt.UUID in assignment`

The raw parameter for bind{Param}() function may need to be casted strfmt.UUID (or any other custom types defined?).

**Comment by casualjim** [comment]
I botched a merge this weekend and I'm catching up. Please keep submitting issues as you find them though.

If it's critical to what you're trying to do, the latest working version of the server generator was: 797d4ba

**Comment by darkcrux** [comment]
Thanks @casualjim, I'll use 797d4ba for now. Will post issues as I find them. I'll put in some PRs when I got the time too.
