### ISSUE TITLE
All Go builtin types should be supported

### ISSUE THREAD

**Issue by zasran** [go-swagger/go-swagger#560]
## Problem statement

scan/scanner.go function swaggerSchemaForType maps primitive Go types to swagger type/format. It's missing some of Go builtin types.

Error generated when unsupported type is used:

`package reflect, error is: unknown primitive "uintptr"`

## Steps to reproduce

One of the missing types is uintptr which is used in e.g. Go reflect package, error would be triggered by following example.

Example code that triggers the error:

```go
import "reflect"
// User
//
// Use documentation here...
//
// swagger:model
type User struct {
	// reflect type for testing reflect
	//
	// required: false
	Rt reflect.Type `json:"rt"`
	// the id for this user
	//
	// required: true
	Id int64 `json:"id"`
	Name string `json:"name"`
}
```

Swagger invocation:

```bash
$ swagger generate spec -m
package reflect, error is: unknown primitive "uintptr"
```

Seems like a good solution would be to support all Go builtin types as listed at [https://golang.org/pkg/builtin/](https://golang.org/pkg/builtin/) (except for the *Type types which are there for documentation purposes only).

I am not sure what the swagger type/format should be for the missing Go builtin types, seems like some of them are not trivial to handle (e.g. byte, complex).

**Comment by zasran** [comment]
After further investigation we figured out that based on Go builtin doc https://golang.org/pkg/builtin/ the following changes in swaggerSchemaForType might make sense:

- ADD byte: prop.Typed("integer", "uint8")
- ADD complex128, complex64 should cause error, no default JSON marshaller
- CHANGE error
  - OLD: prop.Typed("string", "")
  - NEW: error, it's an interface with no default JSON marshaller
- CHANGE rune
  - OLD: prop.Typed("string", "")
  - NEW: prop.Typed("integer", "int32"), doc says rune is alias for int32, it's encoded as a number
- ADD uintptr: prop.Typed("integer", "uint64")

Note about the error: some implementations of error interface might be JSON encoded as a string however it seems to be dangerous to assume that it's always the case, e.g. errors.New creates error that is encoded as JSON empty object {}.

If anybody wants to play with this https://play.golang.org/p/4l2AKRz4LO demostrates how Go builtin types are encoded to JSON.

Please let me know what you think about these suggestions.

**Comment by casualjim** [comment]
I've started answering here several times. But I keep getting stuck. would it be possible for you to join the slack team?  
I want to do the right thing for both go and swagger but typing and convenience for swagger trumps the go type system. 

For example I see that error is an interface but I know how to represent error as a string, always.
So I went with the type string instead of type object. I wonder how that can be done for when error actually implements a the json marshaller/unmarshaller pair because then it would become an object.

**Comment by zasran** [comment]
Can join slack team, which one?

Error - yes, that's tricky, string makes sense lot of times. In general it's the same problem as other objects with JSON marshaller. They all show up as object in swagger model but might be actually something else in JSON representation (which is the opne that is relevant to Rest API). E.g. using guregu null makes swagger docs misleading (that was another issue I planned to file, how to deal with these types of objects)

**Comment by casualjim** [comment]
slack team: https://slackin.goswagger.io/

guregu comes up once in awhile. So it would probably be a good idea to come up some kind of extension mechanism.

Some things that come to mind immediately are:

* look for interface methods that returns a swagger schema/parameter/header definition
* look for a well-known dictionary in the local package that a name like oaiSchemaMap
* look for a new annotation in the comments that has the json representation of the swagger definition so we can just merge it in

**Comment by casualjim** [comment]
fixed by linked pr

**Comment by craSH** [comment]
While this was fixed in code, the specification document was not updated to reflect that. Could someone do so?

http://swagger.io/specification/ - does not list unsigned types (uint32, uint64, complex128, etc.)

**Comment by casualjim** [comment]
we extend the behavior of the spec here, in the cases of an unknown format it will fall back to either integer or number.
But I doubt that that will be added to the spec because that spec is for many languages not just the golang

So long story short, it should work regardless of the format value but languages that support the types will hopefully make use of it

**Comment by craSH** [comment]
I see - sorry, I'm coming in to this as an outsider :) I'm working on a project that uses Swagger (it is not Golang based) and uses both the int64 and uint64 types. I came to the spec to try and verify that uint64 was a valid type, which per the spec I found, is not. It's just confusing, I am trying to find a definitive list of types that are valid within the Swagger IDL, or documentation of mapping those to their individual languages/implementations.

Thanks, and sorry if this isn't exactly the right venue for this conversation!

**Comment by casualjim** [comment]
The spec is the source of truth, that's guaranteed to be implemented because that's what makes it swagger compliant.
So this would be the canonical list: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
