### ISSUE TITLE
Basic usage of 'swagger generate spec'

### ISSUE THREAD

**Issue by Starli0n** [go-swagger/go-swagger#57]
Hi,

I tried to generate a swagger.json file with some annotations in my Go code but I do not find any concrete examples and I have always this result

```
> swagger generate spec -o ./swagger.json
{"swagger":"2.0","paths":null}
```

I tried those annotations from this document but it is not working properly or I do not know how to use them. 

http://godoc.org/github.com/go-swagger/go-swagger/scan

Does an exemple of swagger generate spec exist ?

**Comment by casualjim** [comment]
You can take a look here:

https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing/petstore

there are a few more issues to work out with the generation of a server and client before I can work on the docs and provide proper examples.

**Comment by Starli0n** [comment]
I will take a look. Thanks !

**Comment by casualjim** [comment]
http://go-swagger.github.io/generate/spec/
