### ISSUE TITLE
swagger validate swgger.yml fail when I follow Todo-List tutorial

### ISSUE THREAD

**Issue by wangweihong** [go-swagger/go-swagger#571]
I install go-swagger by running `go get -u github.com/go-swagger/go-swagger/cmd/swagger`. After install is done, I follow [http://goswagger.io/tutorial/todo-list/](url) to learn how to use go-swagger.After I create swagger.yml by following this command
![image](https://cloud.githubusercontent.com/assets/18753267/16223363/7b230cca-37cf-11e6-8f27-8e83ef0a8997.png), 
I run `swagger validate ./swagger.yml` file, it fails.
![image](https://cloud.githubusercontent.com/assets/18753267/16223429/c3375822-37cf-11e6-975c-3f1f011fd344.png)
![image](https://cloud.githubusercontent.com/assets/18753267/16223438/ca6ada56-37cf-11e6-9f10-d858a5b42ef7.png).
Why it happen?

**Comment by vburenin** [comment]
It works just fine for me. I guess you have some locale specific troubles.

```
~/tttttt » swagger init spec \
  --title "A To Do list application" \
  --description "The product of a tutorial on goswagger.io" \
  --version 1.0.0 \
  --scheme http \
  --consumes application/io.goswagger.examples.todo-list.v1+json \
  --produces application/io.goswagger.examples.todo-list.v1+json
2016/06/21 14:30:19 creating specification document in Users/vlad/tttttt/swagger.yml
~/tttttt » swagger validate swagger.yml
The swagger spec at "swagger.yml" is valid against swagger specification 2.0
~/tttttt » cat swagger.yml
consumes:
- application/io.goswagger.examples.todo-list.v1+json
definitions: {}
info:
  description: The product of a tutorial on goswagger.io
  title: A To Do list application
  version: 1.0.0
paths: {}
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
swagger: "2.0"
```


It also would be good if you post a plain text code instead of screenshots.

**Comment by wangweihong** [comment]
@vburenin  
Thanks for your help . It works fine now. I don' know why. I just restart my machine, and re-setup swagger command.

**Comment by sheepbao** [comment]
I have the same problem!
$ cat swagger.yml

`consumes:`
`- application/io.goswagger.examples.todo-list.v1+json`
`definitions: {}`
`info:`
`  description: The product of a tutorial on goswagger.io`
`  title: A To Do list application`
`  version: 1.0.0`
`paths: {}`
`produces:`
`- application/io.goswagger.examples.todo-list.v1+json`
`schemes:`
`- http`
`swagger: "2.0"`
$ swagger validate swagger.yml 
`2016/07/15 14:37:54 invalid character 'c' looking for beginning of value`

Why?Please help.
$ go env:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lstbao/work/listomego:/home/lstbao/gowork"
GORACE=""
GOROOT="/home/lstbao/software/go"
GOTOOLDIR="/home/lstbao/software/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
