### ISSUE TITLE
When generating validations struct pkg references needs to be preserved

### ISSUE THREAD

**Issue by runcom** [go-swagger/go-swagger#578]
## Problem statement

if I generate the structs into `./specs-go` and validations in `./specs-go/validation` then types in the validation directory aren't referencing types in specs-go and I get not declared errors

**Comment by runcom** [comment]
or put it another way - there could be a way to name the validation only files with a `_validation` suffix, does it work?

**Comment by casualjim** [comment]
I went with the fie suffix for now, the packages require a bit more work

**Comment by runcom** [comment]
Thanks a lot!

**Comment by runcom** [comment]
Can we leave this  open for the pkg work which could be done in the future?

**Comment by fredbi** [comment]
@casualjim  I believe that this refers to a time before I was born with this project, and codegen structure has changed much since that time.

It does not look relevant any longer, does it?

**Comment by fredbi** [comment]
Closed as no longer applicable
