### ISSUE TITLE
Validation failed for json swagger if the response schema defined type=array

### ISSUE THREAD

**Issue by weching** [go-swagger/go-swagger#58]
Defined a response, in it the schema specify array type. The validation failed with message "response body for 'operationxx' is a collection without an element type"
 
```
...
"responses": { 
             "200": {
                        "description": "Successful operation",
                        "schema": {
                            "type": "array",
                            "$ref": "#/definitions/DeleteResponse"
                        }
                    }
             }
....
```

**Comment by casualjim** [comment]
```json
{ 
  "responses": {
     "200": {
       "description": "Success",
      "schema": {
          "type": "array",
          "items": {
             "$ref": "#/definitions/DeleteResponse"
          }
       }
    }
  }
}
```

**Comment by wfuertes** [comment]
I'm having a similar problem, for a response like:
        "children" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/NodeTree"
          }
        }
it works fine as expected. But when we have the follow:
        "children" : {
          "type" : "array",
        }
It is failing, so the $ref is being 'undefined' because that. Do you have any hit about how to solve this problem? 

Thanks in advance.

**Comment by wfuertes** [comment]
@casualjim I found another issue related https://github.com/kongchen/swagger-maven-plugin/issues/224

**Comment by casualjim** [comment]
could you get me the entire spec? it would be helpful to see the context around the children thing.

**Comment by wfuertes** [comment]
```
public class NodeTree {
    private Long id;
    private String name;
    private List<NodeTree> children;
	
	// GETTERS AND SETTERS
}
```

My documentated REST end-point.

```
@POST
@Path("/{treeId}/nodes")
@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@ApiOperation(value = "Create node tree.")
@ApiImplicitParams(value = {
	@ApiImplicitParam(name = "nodeTree", value = "", required = true, dataType = "NodeTree",
					  paramType = "data")})
@ApiResponses(value = { @ApiResponse(code = 200, message = "Succees", response = NodeTree.class)})
public Response createNodeTree(@ApiParam(value = "Tree id", required = true) @PathParam("treeId") Long treeId, NodeTree nodeTree) {

	// IMPLEMENTATION OMITED 
}
```

So the swagger-maven-plugin is generating the follow swagger.json:
```
"NodeTree" : {
  "type" : "object",
  "required" : [ "name" ],
  "properties" : {
	"id" : {
	  "type" : "integer",
	  "format" : "int64"
	},
	"name" : {
	  "type" : "string"
	},
	"children" : {
	  "type" : "array"
	  /* Here missing the follow part: 
		  "items" : {
			"$ref" : "#/definitions/NodeTree"
		  }
	  */
	}
  }
}
```

Because this the "swagger-client.js" is breaking in the follow function:
```
Resolver.prototype.resolveTo = function (property, objs) {
  
  // it is breaking here, because we don't have 
  // $ref in the property to the type = array.
  var ref = property.$ref;
  
  if(ref) {
    if(ref.indexOf('http') === 0) {
      if(Array.isArray(objs[ref])) {
        objs[ref].push({obj: property, resolveAs: '$ref'});
      }
      else {
        objs[ref] = [{obj: property, resolveAs: '$ref'}];
      }
    }
  }
  else if(property.type === 'array') {
    var items = property.items;
    this.resolveTo(items, objs);
  }
}; 
```

I hope this can be useful in order to solve the problem.
Regards.
Willian.

**Comment by casualjim** [comment]
Hi thanks for the context, I think this is a bug related to the java implementation of swagger, which is another project under another organization.
I think you'll find that the people (@fehguy) from the swagger-core project might be able to help you better, I'm not familiar with the java implementation and its frameworks.  https://github.com/swagger-api/swagger-core
