### ISSUE TITLE
missing swag import

### ISSUE THREAD

**Issue by runcom** [go-swagger/go-swagger#580]
## Problem statement

the `github.com/go-openapi/swag` import is missing in validation files which need it.
```
go test -race ./...
# github.com/opencontainers/image-spec/specsgo
specsgo/array_of_hooks_validator.go:18: undefined: swag in swag.IsZero
specsgo/id_mapping_validator.go:39: undefined: swag in swag.IsZero
specsgo/id_mapping_validator.go:52: undefined: swag in swag.IsZero
specsgo/id_mapping_validator.go:65: undefined: swag in swag.IsZero
```
Looking at those files, the import is missing.
The command I used:
```
swagger generate model -f schema/defs.json --skip-struct -m specsgo
```
in the `opencontainers/image-spec` repository. You can see there are some usages of `swag\.IsZero` but the import is missing

**Comment by runcom** [comment]
I can't reproduce it anymore - not sure what's happened

**Comment by casualjim** [comment]
my guess is that you have them on your file system now, before you hadn't.
We use goimports to optimize and discover imports following a file generation step.

**Comment by runcom** [comment]
I see thx I think I can close this

**Comment by vikstrous** [comment]
I can reproduce this every time by just running goswagger in a container. I used the following command: let me know if I'm doing something wrong.

```
docker run --rm -e GOPATH=/go -v /home/me/project:/go/src/github.com/org/project -w /go/src/github.com/org/project -u 1000:1000 quay.io/goswagger/swagger:0.6.0 generate client -f swagger2.json -t pkg/api-client
```

**Comment by casualjim** [comment]
if you can do a go get -u github.com/go-openapi/runtime you should get the swag package too, afterwards it should just work

**Comment by vikstrous** [comment]
I'm just running the docker image. It doesn't have access to what's on my system.

**Comment by casualjim** [comment]
does this image fix your issue? quay.io/goswagger/swagger:gen-layout-configfile

**Comment by vikstrous** [comment]
It works! Thanks!
