### ISSUE TITLE
CLI options to define HTTP/HTTPS protocol schema in generated server code.

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#587]
There is a need to run a server in HTTP mode only behind nginx that adds TLS layer.
Because of that, the provided schema contains HTTP mode only, however server is HTTPS only. That results in the situation that clients like 'bravado' can't not work with this server.

So, It would be good If user could just define which schemas (http or https) to provide in a swagger spec.

ps. I will add all needed changes some time soon.

**Comment by dhoelle** [comment]
@vburenin Anything I can do to help?

**Comment by vburenin** [comment]
I haven't invest any time into this yet. Maybe soon.

**Comment by vburenin** [comment]
Using --force-schema should override whatever default is.

--force-schema=http -> ["http"]
--force-schema=https -> ["https"]
--force-schema=http --force-schema=https -> ["http", "https"]

I am also thinking that server should not really have a different code to run HTTP and HTTPS server, both modes should be optional for any schema definitions.

Let say:
--http - enables HTTP
--https - enables HTTPS requiring TLS key/cert/ca.

@casualjim Do you have any opinion around it?

**Comment by casualjim** [comment]
i would call it scheme and i prefer the --force-scheme over the --http so that we can add transports like grpc, amqp etc

**Comment by vburenin** [comment]
Implemented in https://github.com/go-swagger/go-swagger/pull/612

Panic! It should break all scripts that are running a swagger application.
