### ISSUE TITLE
support redirection for Oauth2.0 

### ISSUE THREAD

**Issue by smothiki** [go-swagger/go-swagger#588]
## Go-swagger doesn't support any redirection while using Oauth2.0 for authorization.

Please refer to the following google groups thread for more [info](https://groups.google.com/forum/#!topic/swagger-swaggersocket/wR3ZViHvoCI)
## Swagger specification

```
swagger: "2.0"
info:
  title: Workflow Manager
  version: 2.0.0
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
securityDefinitions:
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=ID&redirect_uri=URL&scope=URL!&state=state-token'
    tokenUrl: 'https://www.googleapis.com/oauth2/v4/token'
    scopes:
        basic: "nothing here"
security:
  - oauth:
     - basic
paths:
  /ping:
    get:
      security:
        - oauth:
            - basic
      responses:
        200:
          description: server ping success
        default:
          description: unexpected error
```

Proposal:
1. To authorize access to an application using Oauth2.0 basically requires. redirection URL, authorization URL and Token URL. Please refer to the following [link](https://github.com/golang/oauth2/blob/df5b72659a3b1789a345ea643bb7c28442681652/google/google.go#L44-L50)
2. Parameters or definitions should be accepted to make a request to authorization URL to get a request for authorization code which is sent to redirect URL .
3. Redirect URL should be a customizable interface as per users auths requirements which makes a request to token URL to get token for that session.

Suggestions and comments are welcome to make a better proposal

**Comment by fredbi** [comment]
Duplicates #1217, where this topic is discussed

**Comment by fredbi** [comment]
Closed as marked for duplicate
