### ISSUE TITLE
Code gen: missing import restapi/operations/[name]/get_[name]_parameters.go ; "github.com/go-openapi/runtime/middleware"

### ISSUE THREAD

**Issue by myles-mcdonnell-m3** [go-swagger/go-swagger#590]
## Problem statement

Generated get_[name]_parameters.go is missing "github.com/go-openapi/runtime/middleware" import.

go-swagger revision (installed from source) : 3981236c3f6bd9eabb26f14e9d31b853d340405f 
## Swagger specification

2.0
## Steps to reproduce

generate server skeleton code

**Comment by casualjim** [comment]
if you vendor or do `go get -u github.com/go-openapi/runtime` then issues #591, #592 and this one will go away

**Comment by linearregression** [comment]
@casualjim 
Did that but the import is still missing

**Comment by casualjim** [comment]
We rely on the goimports command to gather and optimize the imports.
So if you have the vendoring done, you may have to regenerate but the imports should be found

**Comment by casualjim** [comment]
if this is not the case can you post the spec that fails?

**Comment by jdamick** [comment]
i encountered the same issue and after regenerating it did add the correct imports..  but it is a little bit confusing if you generate for a fresh project and then vendor and then you have regenerate for it to add those imports.

**Comment by casualjim** [comment]
that's true, so do you have a suggestion how to remove that requirement? perhaps add a flag to call the vendoring command of choice? 
I use gvt, other people use gb, yet other ones use glide or govendor and so on.

There are other options too, looking forward to get some suggestions though?
Or should it first scan the path and fail if the necessary dependencies aren't there? Or ...

**Comment by jdamick** [comment]
maybe a parameter to do that introspection or else just always add the imports so that then when you run glide (or whatever) it will just do the right thing.  Seems like that would be majority case for people just starting off?

**Comment by JrCs** [comment]
I have the same problem: "github.com/go-openapi/swag" is still missing SOMETIME !
I have start a number of `swagger generate server` commands and SOMETIME the import is here, SOMETIME is not.
The import `github.com/go-openapi/runtime` is in my vendor directory

The code i'm using to test: 
```bash
for i in $(seq 1 20); do
    echo -n "Test $i:"
    swagger generate server &>/dev/null
    grep -q 'github.com/go-openapi/swag' models/application_set_report.go && echo "Found" || echo "NOT found"
done
```
Result:
```
Test 1:Found
Test 2:Found
Test 3:Found
Test 4:Found
Test 5:NOT found
Test 6:Found
Test 7:Found
Test 8:Found
Test 9:NOT found
Test 10:Found
Test 11:Found
Test 12:NOT found
Test 13:NOT found
Test 14:Found
Test 15:Found
Test 16:Found
Test 17:Found
Test 18:Found
Test 19:Found
Test 20:Found
```

**Comment by JrCs** [comment]
Ok i found the bug ! 
It's in go-imports. When go-imports scan the directories if it found an error (like a directory that it can't read) it will stop the scan and so the import are not found and the line not added in the import section.

It easy to reproduce: create a directory that can't be read by the current user in the vendor directory:
```bash
sudo mkdir vendor/a
sudo chmod 0 vendor/a
```
and try to generate the code with `swagger` and no import will be found.

**Comment by JrCs** [comment]
The best to resolve such error, is perhaps to add:
github.com/go-openapi/runtime/middleware
github.com/go-openapi/swag
by default in the templates files where they can be used.
So go-imports, will remove this imports if not used in the code, instead of adding missing import. The solution "fix" also the problem when vendor directory have missing pkg: the compilation will fail reporting that the pkg is missing.
