### ISSUE TITLE
Code gen: missing import restapi/service.go ; "github.com/go-openapi/swag"

### ISSUE THREAD

**Issue by ghost** [go-swagger/go-swagger#592]
## Problem statement

Generated resetapi/server.go file is missing "github.com/go-openapi/swag" import

go-swagger revision (installed from source) : 3981236c3f6bd9eabb26f14e9d31b853d340405f
## Swagger specification

2.0
## Steps to reproduce

generate server skeleton code

**Comment by fredbi** [comment]
Duplicates #590, which has been closed.
