### ISSUE TITLE
How to implement URLs to resources?

### ISSUE THREAD

**Issue by christianklotz** [go-swagger/go-swagger#604]
Let's imagine we have a list of products that are available at a store. A product resource should include a reference to the store it's available in but instead of including the entire store resource I would like to include a url to the store. 

What's the best approach to generate the url dynamically?
### Example

`/v1/products/:id`

```
{
   "id": 123,
   "name": "Book",
   "available_at_url": "https://api.example/com/v1/stores/456"
}
```

`/v1/stores/:id`

```
{
  "id": 456,
  "name": "Book Store",
  "address": "1 Main Road"
}
```

**Comment by atremblay-seniorlink** [comment]
From what I've found there's no way in go-swagger to link the value of a primitive inside Object 1 into a formatted string primitive in Object 2. It might not even be possible inside the OpenAPI spec. 

A swagger:response does have a pattern property, which would get you most of the way there,  that and a well-worded description is your best bet, I think.

**Comment by casualjim** [comment]
openapi 3 will support HATEOAS style links.

**Comment by casualjim** [comment]
A url builder was added in the 0.7.x series, I think that addresses this request
