### ISSUE TITLE
`validate` failing with out of memory error

### ISSUE THREAD

**Issue by rgarcia** [go-swagger/go-swagger#605]
## Problem statement

Running `swagger validate <file>` on the specification below hangs and eventually fails with an out of memory error.
## Swagger specification

``` yaml
swagger: '2.0'
info:
  title: swagger validate out of memory
  version: 0.1.0
paths:
  /foos:
    post:
      operationId: createFoo
      responses:
        200:
          schema:
            $ref: '#/definitions/Foo'

definitions:
  Foo:
    type: object
    properties:
      bar:
        $ref: '#definitions/Bar'
      baz:
        $ref: '#definitions/Baz'

  Bar:
    type: string
    enum:
      - a
      - b

  Baz:
    type: array
    items:
      type: string
```
## Steps to reproduce

Run `swagger validate` on the specification above.

Strangely, if I comment out either `bar` or `baz` as properties on `Foo`, it validates. Only when both properties are present does the command hang.

**Comment by rgarcia** [comment]
I should also note that there are a couple of things incorrect about this config:

1. `#definitions/Bar` and `#definitions/Baz` should be `#/definitions/Bar` and `#/definitions/Baz`, respectively.
2. There should be a description on the 200 response.

The online validator at http://editor.swagger.io passes once both of these are changed. `go-swagger` passes once (1) is changed. So there are perhaps two bugs here:

- Whatever is causing go-swagger to hang on the config
- (assuming editor.swagger.io is correct) go-swagger doesn't fail validation if a response lacks a description

**Comment by casualjim** [comment]
this is fixed now
