### ISSUE TITLE
[validation] pathItems properties are not strictly validated

### ISSUE THREAD

**Issue by dolmen** [go-swagger/go-swagger#62]
This spec is invalid (`invalid-property` is not allowed in a `pathItem`) but go-swagger accepts it:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger of additionalProperties in pathItem"
  },
  "paths": {
    "/": {
      "invalid-property": null
    }
  }
}
```

Only vendor extensions (properties starting with `x-` should be accepted in addition to the normalized properties. See [`/definitions/pathItem` in the JSON schema for Swagger 2.0](/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L290).

**Comment by casualjim** [comment]
afaik I'm allowed to just ignore invalid things, this could be a validation error though, is that what you mean?

**Comment by dolmen** [comment]
> this could be a validation error though

That's what I mean.
