### ISSUE TITLE
Generated code validation

### ISSUE THREAD

**Issue by nicolaifsf** [go-swagger/go-swagger#625]
## Problem statement

Generated code validation when checking for max string length does not work. tries casting to an int64 rather than checking for the length of the string

## Swagger specification

http://a4677c9873c9611e6aa7102b92f75d5c-1135862614.us-west-2.elb.amazonaws.com/v3/swagger.json

## Steps to reproduce

Generate the code with go-swagger and look at /models/get_job.go line 95

**Comment by casualjim** [comment]
maximum is a validation for numbers. If you want to specify a max length for a string you should use maxLength as validation instead.
See here for more info: http://json-schema.org/latest/json-schema-validation.html#anchor26
