### ISSUE TITLE
Error while updating dependencies

### ISSUE THREAD

**Issue by frosenberg** [go-swagger/go-swagger#627]
## Problem statement

I use swagger version `0.5.0-145-g163c0cd` and I updated all my project dependencies (`go get -t -u ./...`). I'm seeing the following error when trying to start my REST API server. 

```
# github.com/go-openapi/runtime/middleware
../../../github.com/go-openapi/runtime/middleware/router.go:233: cannot use parameters (type map[interface {}]spec.Parameter) as type map[string]spec.Parameter in field value
../../../github.com/go-openapi/runtime/middleware/router.go:235: cannot use parameters (type map[interface {}]spec.Parameter) as type map[string]spec.Parameter in argument to newUntypedRequestBinder
```

Any ideas or maybe this is not related to swagger?

**Comment by casualjim** [comment]
are you vendoring your dependencies by any chance?

I think this is caused by a PR that got merged this morning. So if you're vendoring, i want to ask if you can go back to go-openapi/analysis#9f487a0bf7e69478955d3a8bd1642d1a1edddcc4 
That is prior to the change in signature being merged.

**Comment by frosenberg** [comment]
Thanks for the quite reply. Not yet, but I guess the time has come.

**Comment by frosenberg** [comment]
Thanks that fixes it.

**Comment by casualjim** [comment]
I fixed it on master of that library now too, so you don't strictly need to vendor anymore
