### ISSUE TITLE
[validation] incorrect validation of path parameters defined in /parameters

### ISSUE THREAD

**Issue by dolmen** [go-swagger/go-swagger#63]
The following Swagger 2.0 spec is valid but `swagger validate` reports a false negative:
```
The swagger spec at "global-parameters.json" is invalid against swagger specification 2.0. see errors :
- path param "userId" is not present in the path
```
Parameter `userId` is not used in any path (there is no `parameters` section for path `/` with a `$ref` to `/parameters/userId`). This should not be reported as an error.
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger global parameters"
  },
  "parameters": {
    "userId": {
      "name": "userId",
      "in": "path",
      "type": "string",
      "required": true
    }
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "description": "Successful"
          }
        }
      }
    }
  }
}
```

**Comment by dolmen** [comment]
The [specification](http://swagger.io/specification/#schemaObject) says about `/parameters`:
> An object to hold parameters that can be used across operations. This property does *not* define global parameters for all operations.

**Comment by dolmen** [comment]
To workaround this issue, I wrote [a Perl 5 script that inlines parameters defined at global scope](https://gist.github.com/dolmen/1ddd5e6a0f8ff54b5df8).

**Comment by casualjim** [comment]
O I get it now. You still have to reference your parameter. The global parameters are not defaults for every operation. They are like a databag to share, but you still have to provide a $ref to the named parameter if you want to use them

**Comment by dolmen** [comment]
Why is this issue closed? I don't see a commit that fixes it...

**Comment by casualjim** [comment]
because there is nothing to fix, see my comment. You have to still refer to them as $ref wherever you want to use them.
Whatever you define in the parameters property at the top level is like definitions, they  aren't defaults for every single operation in your spec.

**Comment by dolmen** [comment]
> because there is nothing to fix, see my comment. You have to still refer to them as $ref wherever you want to use them.

Yes, that's exactly how I'm using them. So why is `swagger validate` complaining about `path param "userId" is not present in path "/"` with the example initially presented? (I updated to the latest master)

The issue is NOT FIXED.

**Comment by dolmen** [comment]
Here is another example. Parameter `userId` is used in path `/users/{userId}`. It is not used in either path `/foo` and `/bar`.

The issue is that each parameter in `/parameters` is reported as a error for any operation where it is **NOT** used.

The output:
```
The swagger spec at "global-parameters-2.json" is invalid against swagger specification 2.0. see errors :
- path param "userId" is not present in path "/foo"
- path param "userId" is not present in path "/bar"
```
The spec:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger global parameters"
  },
  "parameters": {
    "userId": {
      "name": "userId",
      "in": "path",
      "type": "string",
      "required": true
    }
  },
  "paths": {
    "/foo": {
      "get": {
        "responses": {
          "200": {
            "description": "Successful"
          }
        }
      }
    },
    "/bar": {
      "get": {
        "responses": {
          "200": {
            "description": "Successful"
          }
        }
      }
    },
    "/users/{userId}": {
      "parameters": [
        { "$ref": "#/parameters/userId" }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Successful"
          }
        }
      }
    }
  }
}
```

**Comment by dolmen** [comment]
Parameters in global scope seem to be fixed.
But there is also an issue with parameters defined at path scope. I will open a separate issue.
