### ISSUE TITLE
Debug prints regorganization

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#634]
## Problem statement

I see lot of places where the code looks like this:

```
if Debug {
    log.Println("absolute path", fa)
}
```

Event though it is trivial and debug only, it contributes into the code size overall reducing readability.
## Proposition.

 I would consider moving it out into just one function that supports some kind of log levels or I would just use an existing logging library.

Thoughts?

**Comment by casualjim** [comment]
even when it uses a logging library, there would still need to be if guards or lazy evaluation of arguments to get any real benefit from it.
The one immediate benefit I see would be colors for levels

**Comment by fredbi** [comment]
How about using the following constructs:
```go
func logDebug(...) bool {
 log.Printf(....)
}

_ := Debug && logDebug("message")
```

Then we could move the logDebug() func to any logger available out there. For instance `rs/zerolog` seems an efficient, yet simple, one.

For the `json.MarshalIndent()` stuff, another wrapper would be appropriate, e.g: 
```go
func logDebugAsJson(v) bool {
 bbb, _ := json.MarshalIndent(v)
 log.Printf(string(b))
return true
}
```

This would make code more readable and test coverage analysis more accurate.

Another useful point is to enable debug for a given module. Currently, all go-openapi packages are guided by the same env variable `SWAGGER_DEBUG`.

Debugging text would be clearer if we could support things like `export SWAGGER_DEBUG=go-swagger:validate:runtime`.
