### ISSUE TITLE
What is the minimal go version required?

### ISSUE THREAD

**Issue by lucas-natraj** [go-swagger/go-swagger#636]
## Spec generation failing on Ubuntu after d4320763baca34e95720ad77880a3fd0ed882309

Error message:
`Failed to load template serverConfigureapi: template: serverConfigureapi:23: illegal number syntax: "-"`

It does NOT occur when running on Mac OS X, but our CI builds are on Ubuntu which started failing yesterday.
## Steps to reproduce

This should be reproducible on any go application.

If you need one, grab the small sample project from https://github.com/lucas-natraj/go-notes and follow the standard setup instructions on the README.

The error is easily seen when running: 

```
$ ./bin/swagger generate spec --input=./swagger-aux.json --output=./swagger.json --base-path=./src/notes/app/
```

I have forked the repo to https://github.com/lucas-natraj/go-swagger and reverted the aforementioned commit, and the error message no longer occurs.

**Comment by emosbaugh** [comment]
I believe that commit broke compatibility with go < 1.6
https://github.com/golang/go/issues/14381

**Comment by lucas-natraj** [comment]
@emosbaugh: Yeah, that looks like it. Thanks for finding that.

**Comment by casualjim** [comment]
do you need go < 1.6?

I'm asking because it has implications for the templates of which I have many complicated ones

**Comment by lucas-natraj** [comment]
@casualjim Nope. I'm perfectly fine with the change. I'm upgrading our CI builds accordingly. 
I just didn't find anything to explain why this was failing, so I figured it'd be easier to just submit this issue in case anyone else hit the same problem.

**Comment by emosbaugh** [comment]
Change is ok by me.

For those who run into this issue in circleci:
The default build environment ships with go 1.5. It's possible to update the project build environment to use Ubuntu 14.04 image which ships with go 1.6.
