### ISSUE TITLE
How to validate an iso8601 date

### ISSUE THREAD

**Issue by haroldcarr** [go-swagger/go-swagger#643]
Given the attached swagger, the validator complains:

```
"/register.modifiedOn in body should match 'yyyy-MM-dd'T'HH:mm:ss.SSS'Z''",""
```

both when the example is given as

```
"modifiedOn":"2015-05-05'T'12:09:33.281'Z'"
```

or (the correct one):

```
"modifiedOn":"2015-05-05T12:09:33.281Z"
```

[DM.zip](https://github.com/go-swagger/go-swagger/files/443555/DM.zip)

**Comment by casualjim** [comment]
can you change your type definitions?

```json
  {"description":
     "The date and time that the device was registered.",
     "type":"string",
     "format": "date-time"
}},
```

json schema and swagger define ISO8601 dates as a known format, that will fix your validation
