### ISSUE TITLE
Swagger_linux_amd64 does not match master branch of go-swagger

### ISSUE THREAD

**Issue by nicolaifsf** [go-swagger/go-swagger#647]
## Problem statement

Latest release for swagger_linux_amd64 does not match the master branch of go-swagger.  
The release's version results to 0.5.0, however when doing a `go install` under the go-swagger/cmd/swagger directory generates version 0.5.0-166-gd492656

## Steps to reproduce

Generated a swagger client with swagger_linux_amd64

**Comment by casualjim** [comment]
https://github.com/go-swagger/go-swagger/releases/tag/0.6.0
