### ISSUE TITLE
swagger generate spec: type aliases in query parameters

### ISSUE THREAD

**Issue by whiter4bbit** [go-swagger/go-swagger#649]
I have code like this:

```
type Weekday int

type Parameters struct {
    //in:query
    Day Weekday
}
```

generate spec generates this json for parameter:

```
{
  "$ref": "#/definitions/Weekday",
  "x-go-name": "Day",
  "name": "Day",
  "in": "query"
},
```

what is invalid, because query parameter can have one of predefined datatypes according to spec.

Is it possible somehow to force go-swagger to use custom parameter type for spec generation?

Like:

```
type Parameters struct {
  //in:query
  //type:int
  //minimum:1
  //maximum:7
  Day Weekday
}
```

**Comment by casualjim** [comment]
I think the solution is not to add type info on the property, but go swagger should follow aliased types when they are params and get to the one they actually represent.
