### ISSUE TITLE
Why all the pointers?

### ISSUE THREAD

**Issue by themalkolm** [go-swagger/go-swagger#651]
Maybe it is a way to go now but it breaks all our code. Basically it always generates pointers even if property is required.

Note how Code field is generated. In 0.5.0 it is an int while 0.6.0 generates pointer there.

```
$ cat /tmp/swag.json
{
    "swagger": "2.0",
    "info": {
        "title": "Borked"
    },
    "definitions": {
        "Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            },
            "required": [
                "code",
                "message"
            ]
        }
    }
}
```

**0.5.0**

```
$ env GOPATH=/tmp /opt/swagger-0.5.0/swagger_linux_amd64 generate client -f /tmp/swag.json -t /tmp/src/
...
$  cat tmp/src/models/error.go | head -32
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
        strfmt "github.com/go-swagger/go-swagger/strfmt"

        "github.com/go-swagger/go-swagger/errors"
        "github.com/go-swagger/go-swagger/httpkit/validate"
)

/*Error error

swagger:model Error
*/
type Error struct {

        /* code

        Required: true
        */
        Code int64 `json:"code"`

        /* message

        Required: true
        */
        Message string `json:"message"`
}

// Validate validates this error
```

**0.6.0**

```
$ env GOPATH=/tmp /opt/swagger-0.6.0/swagger_linux_amd64 generate client -f /tmp/swag.json -t /tmp/src/
...
$  cat tmp/src/models/error.go | head -32
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
        strfmt "github.com/go-openapi/strfmt"

        "github.com/go-openapi/errors"
        "github.com/go-openapi/validate"
)

/*Error error

swagger:model Error
*/
type Error struct {

        /* code

        Required: true
        */
        Code *int64 `json:"code"`

        /* message

        Required: true
        */
        Message *string `json:"message"`
}

// Validate validates this error
```

**Comment by themalkolm** [comment]
It breaks everything but I couldn't find any BREAKING change for 0.6.0.

**Comment by casualjim** [comment]
The reason for the change is that a zero value for a required property is a valid value.
So for a string "" is valid but nil or absence of the key isn't.

You can change your spec and add `x-nullable: false`

**Comment by casualjim** [comment]
I added the entry about the breaking change to the release notes too. Thanks for that.

**Comment by themalkolm** [comment]
Probably you should regenerate all examples, revisit all docs and tutorials as they are simply broken now.

**Comment by themalkolm** [comment]
@casualjim no, `x-nullable` doesn't help as if, say, int64 field is set to 0 then server code still treats it as a missing one. Sure, this happens before 0 value is the zero value for int64 type.

**Comment by vburenin** [comment]
This is a problematic part here. If value is a required property, the only
thing you can do is to have a pointer.
I really understand your problem, I went through this suffering too. It
broke many things on my side as well, but it is not as critical as it could
be. It just took 2 hours for me to update all projects to handle this
change gracefully.
Yes, access values like *v - looks very ugly, but this is necessary evil to
make things right.

Also, this change will be very helpful when swagger switch over to the
bitset for indication if the value is nil and set. You practically will
just need to change v == nil to v.IsNil()

**Comment by casualjim** [comment]
You can make use of this: https://github.com/go-openapi/swag/blob/master/convert_types.go
To make the referencing/dereferencing easier

**Comment by themalkolm** [comment]
@vburenin meh, I'm ok to have zero values  everywhere by default. I we have golang client talking to golang server. Having pointers makes it awkward on both sides.

**Comment by themalkolm** [comment]
I close this issue as we decided to simple not upgrade. Doesn't worth the effort for us.

**Comment by bamarni** [comment]
How about generating something like this? https://godoc.org/github.com/google/go-github/github#App

Then it is possible to make the difference between a missing and zero value but it gives nice getters on top of it for consumers. Having to use https://github.com/go-openapi/swag/blob/master/convert_types.go is not that user-friendly.
