### ISSUE TITLE
Question : How to set http header to enable CROS

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#654]
## Swagger specification
latest Swagger 2.0 from master, (build with src)

I'd like to know how to set global header of the server? cause in Swagger-UI, i get "Can't read from server. It may not have the appropriate access-control-origin settings."

Thanks a lot

**Comment by casualjim** [comment]
http://goswagger.io/use/middleware.html#byo-middleware
https://github.com/go-swagger/go-swagger/issues/481#issuecomment-224503845

https://github.com/rs/cors
