### ISSUE TITLE
API Gateway vendor extensions?

### ISSUE THREAD

**Issue by FryDay** [go-swagger/go-swagger#659]
Is there any way to implement the Amazon API Gateway vendor extensions (x-amazon-apigateway*) easily for spec generation?

Basically I'm looking for a way to add custom vendor extensions.

**Comment by casualjim** [comment]
at which stage?

**Comment by casualjim** [comment]
or how are you using go-swagger :)

**Comment by FryDay** [comment]
I have my paths being generated, but I need to be able to add the amazon extensions to them. Hopefully this example helps. If there is an easy way for me to add my own extensions that can be generated from comments, it would be awesome.

```
"paths": {
  "/": {
    "options": {
      stuff
    }
"x-amazon-apigateway-integration": {
  "requestTemplates": {
    "application/json": "{\"statusCode\": 200}"
  },
  "passthroughBehavior": "when_no_match",
  "responses": {
    "default": {
      "statusCode": "200",
      "responseParameters": {
        "method.response.header.Access-Control-Allow-Methods": "'OPTIONS'",
        "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'",
        "method.response.header.Access-Control-Allow-Origin": "'*'"
      }
    }
  },
  "type": "mock"
}
```

**Comment by FryDay** [comment]
The extensions I need to add are these: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

**Comment by FryDay** [comment]
Is there anyway for me to easily integrate these extensions?

**Comment by casualjim** [comment]
you could use a spec that gets merged in during the generation process, but other than that it would require changes to the scan package

A syntax has to be created and then added to the parsers here: https://github.com/go-swagger/go-swagger/blob/master/scan/routes.go#L199

**Comment by FryDay** [comment]
Okay, I have a solution in the works, but I have another issue. AWS does not support response refs. Is there an easy way to make go-swagger put responses inline instead of as $refs?

**Comment by casualjim** [comment]
Not easy it would involve making the strategy for setting responses on a route configurable

https://github.com/go-swagger/go-swagger/blob/master/scan/routes.go#L193
https://github.com/go-swagger/go-swagger/blob/master/scan/validators.go#L568-L595

**Comment by pritesh-lahoti** [comment]
@FryDay Were you able to get this through?
