### ISSUE TITLE
Question: After set authentication , CROS handler doesn't work

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#663]
## Problem statement
In Swagger UI, after I set authentication of API KEY, then it said it doesn't enable CROS, but I configure CROS handler already in :

`
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	handleCORS := cors.Default().Handler
	return handleCORS(handler)
}
`
Do u have any idea? 
Thanks a lot

**Comment by casualjim** [comment]
can you share a spec and the error message?

**Comment by xuanzhaopeng** [comment]
Fixed and debuged by following source code:

``` go
import "github.com/rs/cors"

func setupGlobalMiddleware(handler http.Handler) http.Handler {
	corsHandler := cors.New(cors.Options{
		Debug: false,
		AllowedHeaders:[]string{"*"},
		AllowedOrigins:[]string{"*"},
		AllowedMethods:[]string{},
		MaxAge:1000,
	})
	return corsHandler.Handler(handler)
}
```
