### ISSUE TITLE
Duplicate imports in main.go on pet-store's swagger file.

### ISSUE THREAD

**Issue by li3p** [go-swagger/go-swagger#665]
I am using the `swagger.yaml` from [http://petstore.swagger.io/v2/swagger.json](http://petstore.swagger.io/v2/swagger.json)

And I generate the server code by using the command:
`swagger generate server -A PetStore -f specs/swagger.yaml`

In the generated `cmd/pet-store-server/main.go`， there are duplicated imports
on `user, pet, store` :

``` go
package main

import (
   ...

  "iriswag/models"
  "iriswag/restapi/operations/user"
  "iriswag/restapi/operations/pet"
  "iriswag/restapi/operations/store"
  "iriswag/restapi/operations/user"
  "iriswag/restapi/operations/store"
  "iriswag/restapi/operations/pet"
  "iriswag/restapi"
  "iriswag/restapi/operations"  
)
```

**Comment by casualjim** [comment]
there is an issue with escaping the backticks ` in the long description, which makes the file not compile. Because of that the imports aren't being cleaned up by goimports.
