### ISSUE TITLE
How to use swagger:params

### ISSUE THREAD

**Issue by xiawenji** [go-swagger/go-swagger#668]
## Problem statement

The route is // swagger:route GET /services/{serviceName}/version/{version}  pets listOneService
,How to comment the two params('serviceName' and 'version')

**Comment by casualjim** [comment]
swagger:params is used to indicate which operations the properties of the operation are included in the struct.

So you'd use something like these:

https://github.com/go-swagger/go-swagger/blob/master/fixtures/goparsing/petstore/rest/handlers/orders.go#L24-L46

or 

```go
// swagger:params listOneService 
type ListOneParams struct {

  // ServiceName description goes here
  // 
  // in: path
  // required: true
  ServiceName string `json:"serviceName"`

  // Version description goes here
  //
  // in: path
  // required: true
  Version string `json:"version"`
}
```

**Comment by tonyghita** [comment]
@casualjim I noticed you used `json:"paramName"` for the path param. When would you want to use `param:"paramName"`?

**Comment by xiawenji** [comment]
@casualjim thank you！

**Comment by casualjim** [comment]
@tonyghita  I don't think there is a param:"paramName" atm. I chose to piggyback on the json tag because swagger typically does json requests.
