### ISSUE TITLE
Is it possible to pass extra parameters when start server

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#669]
## Problem statement

Hi, 
Is it possible to pass extra parameters when I start server, such as --my-custom-arg 123,

I try to change server.go, but I found it will change back each time when I regenerate the model. Besides, I checked swagger generate server --help, it seems I cannot pass extra arguments to generate server.go

Thanks a lot

**Comment by vburenin** [comment]
Sure, it is possible.  There is a function in your generated code that is named as configureFlags.
It is being called each time server starts. You can update it appropriately.
Here is an example for you:

```Go
func configureFlags(api *operations.MyAPI) {
	param1 := swag.CommandLineOptionsGroup{
		ShortDescription: "Additional configuration parameters",
		Options:          ConfigParams,
	}
	api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{param1}
}
```

**Comment by nelz9999** [comment]
There's also an example: https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go

**Comment by xuanzhaopeng** [comment]
Cooool! Excellent !

**Comment by vburenin** [comment]
Reopening since it is a useful question/answer for others.

**Comment by Magicking** [comment]
Example linked by @nelz9999 is here: https://github.com/go-swagger/go-swagger/blob/4b51e30da51575d6b0fd28b4fd330bd8ad3147dc/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go

**Comment by JrCs** [comment]
Thanks but how can we retrieve the value of custom-args after the parsing ?
