### ISSUE TITLE
Improve readability of templates used for code generation

### ISSUE THREAD

**Issue by dnephin** [go-swagger/go-swagger#673]
golang templates [support the use of `{{- ... -}}`](https://golang.org/pkg/text/template/#hdr-Text_and_spaces) to remove extra whitespace between tags in templates.

This allows you to write templates which are easily readable by humans, without the extra whitespace changing the output of the rendered template.

I have found that using this style makes it a lot easier to understand the templates.

**Comment by dnephin** [comment]
I've submitted an example of this in #674. If the PR is accepted I can make similar changes to a few other templates.

**Comment by fredbi** [comment]
Most templates have now been refactored: some large ones have been split, the template logic indented, etc.
With the latest round of such refactoring efforts (#2221), we can say that this is now achieved.
