### ISSUE TITLE
No way to generate type `int` (always uses `int64`)

### ISSUE THREAD

**Issue by dnephin** [go-swagger/go-swagger#675]
Looking at `generator/types.go` it seems like there is no way to force `go-swagger` to generate a model that uses golang type `int`. It defaults to `int64` and I can't find a format that will give me `int`.

Is this by design, or did I miss something?

**Comment by casualjim** [comment]
This is by design, this might have been a mistake though.
The mapping happens here: https://github.com/go-swagger/go-swagger/blob/master/generator/types.go#L143

A good way to enable just int is perhaps through providing a flag, because people get upset when we make breaking changes like this.

**Comment by dnephin** [comment]
I think I might opt for using more explicit types for now. I'll close this issue until I run into a case where it's not working well.

**Comment by allencloud** [comment]
To be honest, this is not so user-friendly. I think it is some kind of against other thing's design.
