### ISSUE TITLE
Generating a model from an inline response schema

### ISSUE THREAD

**Issue by dnephin** [go-swagger/go-swagger#676]
In the [swagger spec I'm working with](https://github.com/bfirsh/docker-api-reference/blob/master/swagger.yaml) there are lots of inlined response schemas. I'd like to generate a model for them using `swagger generate model ...`. As far as I understand it, currently you can only generate models for the schemas under `definitions`.

I'd like to add a feature to generate a model from these inline response schemas.  The name of the model would be `<operationId><response code>Response`.

Do you think there is value in this, or is there some easier way to work with inline schemas?

**Comment by casualjim** [comment]
you can use `swagger generate model` for the definitions and `swagger generate operation --skip-handler` for the other inlined schemas.
Now you'd be the first one that I know of to be using that flag, so thanks for the validation :)  We may have to make a few small changes to make this work properly though (a few more superficial if guards)

**Comment by dnephin** [comment]
Ah perfect, I'll try it out, thanks!

**Comment by dnephin** [comment]
`generate operation` is looking promising. I think I need to add a `--skip-validator` to match `generate model`. 

The model name is a bit unfortunate (ex: `VolumesListOKBodyBody`), Something like `VolumeListOkResponseBody` would be a lot nicer.  I haven't had a chance to look into why the name is that way.
