### ISSUE TITLE
Extra function in example

### ISSUE THREAD

**Issue by Alessar** [go-swagger/go-swagger#68]
File:  go-swagger/fixtures/goparsing/classification/operations/todo_operation.go
Func: mountItem looks like extra function.
Swagger tool generate correct specification for proposed routes without calling fake func mountItem.
The main rule is empty line between swagger:routes like that:

``` go
// ServeAPI serves the API for this record store
func ServeAPI(host, basePath string, schemes []string) error {
    // swagger:route GET /pets pets users listPets

    // swagger:route GET /orders orders listOrders

    // swagger:route POST /orders orders createOrder

    // swagger:route GET /orders/{id} orders orderDetails

    // swagger:route PUT /orders/{id} orders updateOrder

    // swagger:route DELETE /orders/{id} orders deleteOrder
    return nil
}
```

**Comment by hoxnox** [comment]
There are two problems with the "empty-line" approach:

1. gofmt eliminates these empty lines.
2. What about swagger:operation with full description?

**Comment by casualjim** [comment]
it reads comments in blocks and follows go parsing rules

// swagger:route ....
//
// full description here
