### ISSUE TITLE
Configure TLS

### ISSUE THREAD

**Issue by kstedman9** [go-swagger/go-swagger#685]
## Problem statement

I am trying to configure the TLS from within the code. Do not want to pass the TLSCertificate nor the TLSCertificateKey on the command line.  We have a secrets server that we have to talk to to get the TLS information.  So I tried to accomplish this using the configureTLS function, but several errors were observed.  All errors caused me to make changes to the server.go code which gets automatically generated.

In my generated server.go code in the Listen function I had to remove the first if s.hasScheme(schemeHTTPS) block because it is checking for the required command line flags `--tls-certificate` and `--tls-key`.  (see attached file line 206-223)

In the Serve function after the configureTLS function call there is an err check that I also had to comment out.  It was the error from trying to load the tls certificates from the command line.  (see attached file line 182-184)

I would like to be able to auto generate without fixing the code for this situation.  I attached the server.go file that was generated with my lines commented out for reference.
[server.go.txt](https://github.com/go-swagger/go-swagger/files/519896/server.go.txt)

**Comment by casualjim** [comment]
which go-swagger version are you using?

**Comment by kstedman9** [comment]
It was the docker from quay.io/goswagger/swagger:dev from 2 weeks ago.  It looks like it has been updated recently, but I have not updated it yet.
