### ISSUE TITLE
Possibility to add any headers

### ISSUE THREAD

**Issue by Alessar** [go-swagger/go-swagger#70]
It will be good if possibility to add any headers (in all routes) is exist.
For example: in some doc.go 
```go
// Consumes:
// - application/json
// Header:Version-V1 // This is expected header (or something like that)
//
// swagger:meta
```
And after generate spec we get swagger.json like that:
```json
 "consumes": [
  "application/json",
  "Version/V1"
 ]
```
and swagger-ui will generate all requests with additional header Version like that:
```
curl -X GET --header "Accept: application/json" --header "Version: V1"
```

**Comment by casualjim** [comment]
instead of requiring 2 headers, if you're going to do versioning through headers. it should be in your media type.
So you want something like: application/vnd.company.app-v1+json

**Comment by Alessar** [comment]
Header **Version** is only for example.
It will be better if possibility exists to add any headers.

**Comment by casualjim** [comment]
You can add headers to responses and to parameters. Those can in turn be shared to a certain degree through the use of $ref

From the swagger specification:

* [Content Types](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#mime-types)
* [Fixed fields on parameter object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-7)
* [Fixed fields on response objects](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-10)

If you think the specification would be improved by adding global headers to the API, you can submit an issue at the [swagger-spec](https://github.com/swagger-api/swagger-spec) repo, there are many more people following that repository and it will get a discussion going.
