### ISSUE TITLE
need a way to specify context for authenticators

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#726]
## Problem statement

Sometimes it's useful to have more context than just the header value or query param value in an authenticator. They could take an extra context parameter.

**Comment by Crevil** [comment]
This could be a great addition. We currently have a need for adding scopes to an `apiKey` authentication mechanism.

**Comment by casualjim** [comment]
scopes is supported through bearer auth

**Comment by fredbi** [comment]
Now referred to in greater details by #2070
