### ISSUE TITLE
swagger generate client fails on validated swagger.json

### ISSUE THREAD

**Issue by claasstoertenbecker** [go-swagger/go-swagger#733]
## Problem
swagger generate client wont build a client on a validated swagger.json

## Swagger specification
https://esi.tech.ccp.is/latest/swagger.json

## Steps to reproduce
swagger validate https://esi.tech.ccp.is/latest/swagger.json
The swagger spec at "https://esi.tech.ccp.is/latest/swagger.json" is valid against swagger specification 2.0

swagger generate client -f https://esi.tech.ccp.is/latest/swagger.json -A esi
2016/11/11 13:04:03 building a plan for generation
2016/11/11 13:04:04 planning definitions
2016/11/11 13:04:04 planning operations
object has no key "GetCharactersCharacterIDMailOKBodyItems0"

**Comment by claasstoertenbecker** [comment]
seems like its some sort of formatting error

##Steps to reproduce
loaded https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility into http://editor.swagger.io/#/
generated a client swagger.json
swagger generate client -f ./swagger.json -A esi
executed sucessfully

**Comment by casualjim** [comment]
I can reproduce the error you see in your spec, just haven't found the cause for it yet.
Golang never orders map keys the same way twice so that makes it so that that very sometimes it succeeds but more often than that it fails.

**Comment by claasstoertenbecker** [comment]
the swagger.json that is generated with the client sdk of http://editor.swagger.io/#/ is actually a different one than the original.
i think it only puts client stuff in there.
maybe is helps if you compare the original from https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility and the one that is generated with http://editor.swagger.io/#/
