### ISSUE TITLE
Couldn't find swag.DateTime(strfmt.DateTime) *strfmt.DateTime

### ISSUE THREAD

**Issue by anisimovsergey** [go-swagger/go-swagger#734]
It would be nice to have functions similar to `swag.String(v string) *string` but for 
* strfmt.DateTime
* strfmt.Date
* strfmt.Duration

**Comment by GlenDC** [comment]
This has been resolved by adding a `conv` package to `go-openapi/strfmt` as can be seen in following (merged) PR: https://github.com/go-openapi/strfmt/pull/10

Thus besides importing `github.com/go-openapi/strfmt` you'll probably also want to import `github.com/go-openapi/strfmt/conv`.

The conv package provides the functions you are looking for, provided for all types defined in the main strfmt package.
