### ISSUE TITLE
Is it possible to suppress the default value for a date-time filed?

### ISSUE THREAD

**Issue by anisimovsergey** [go-swagger/go-swagger#736]
When I'm trying to use date-time format in my swagger spec for a response like this:
```json
 properties:
   testTimeField:
     type: string
     format: date-time
```
I'm getting a property of type `strfmt.DateTime` in my model
```golang
TestTimeField strfmt.DateTime `json:"testTimeField,omitempty"`
```
The problem that, even though this property is optional and contains "omitempty", the value of this property is always present in the response even if the property is not set: 
```json
  "testTimeField": "0001-01-01T00:00:00.000Z"
```

**Comment by casualjim** [comment]
make it a pointer by adding `x-nullable: true`

**Comment by anisimovsergey** [comment]
Thank you for the help!
