### ISSUE TITLE
Generator makes consts generated from a swagger enum as internal to a package

### ISSUE THREAD

**Issue by HAlakeshwar** [go-swagger/go-swagger#739]
## Problem statement
I have moved from go-swagger 0.7.2 to go-swagger 0.7.4. My implementation relied on accessing swagger enumeration as constant values from the generated models package. The current implementation restricts the scope of these constansts to a package which breaks my implementation. 

## Swagger specification

  Cluster:
    type: object
    description: The cluster layout.
    required:
      - links
      - data
    properties:
      links:
        type: object
        required:
          - self
        properties:
          self:
            $ref: "#/definitions/Link"
      data:
        type: object
        required:
          - status
        properties:
          noOfNodes:
            type: integer
            format: int32
            description: Number of nodes the cluster has
          scheduler:
            type: string
            description: The scheduler that needs to be used by the job scheduler.
          status:
            type: string
            default: "scheduled"
            description: The status of the cluster. It will be one of scheduled, building, up, deleting, exited or error.
            enum:
              - scheduled
              - building
              - up
              - deleting
              - exited
              - error
          clusterError:
            type: string
            description: Error associated with building or tearingdown the cluster.

This would generate 

## Steps to reproduce
1) Generate go from the swagger description
2) The models package will contain a cluster.go file with a cluster struct and a Status property of type string
3) The cluster.go file will also contain the following const values.
const (
	clusterDataStatusScheduled string = "scheduled"
	clusterDataStatusBuilding  string = "building"
	clusterDataStatusUp        string = "up"
	clusterDataStatusDeleting  string = "deleting"
	clusterDataStatusExited    string = "exited"
	clusterDataStatusError     string = "error"
)

Thank you for looking at the problem.

**Comment by anisimovsergey** [comment]
I can see the same issue. 
From my perspective it's not a bug then it's a serious breaking change.

**Comment by HAlakeshwar** [comment]
Thank you Ivan.
