### ISSUE TITLE
Examples: what is the right pattern to inject middleware like Authentication and Content negotiation?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#745]
## Problem statement

This is the first time around building an API, and with go-swagger I am often uncertain how certain patterns are supposed to work. I am looking for the designer's insight in what the middleware injection for Authentication and Content Negotiation are supposed to look like. 

Authentication is clearly a pattern that most APIs use, but I haven't found an example of it in the examples or tutorial directory. 

Similarly, I was thinking that it would be nice to return json or html so that you can use a browser to test the RESTfulness of an API, in which case I need to implement content negotiation. Again, looking for the patterns that the generator authors had in mind to implement this with go-swagger.

## Swagger specification
2.0

**Comment by casualjim** [comment]
content negotiation based on Accept header and content type is done through the consumes/produces bits in a swagger spec. In go-swagger you have to hook up the consumers and producers. 
I've added your spec from #747 as example

https://github.com/go-swagger/go-swagger/tree/master/examples/authentication
