### ISSUE TITLE
Should generate strfmt.DateTime as a pointer? 

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#746]
## Problem statement

Hi,

It seems when I generate a date attribute of a model, it always use strfmt.DateTime as type, is it possilbe to make it as a pointer ? such as *strfmt.DateTime

Thanks

**Comment by casualjim** [comment]
add `x-nullable: true`

**Comment by xuanzhaopeng** [comment]
Cool thanks!
