### ISSUE TITLE
[Question] How to add some cookies before response in Handler

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#748]
## Problem statement

I saw in handlerFunc , which will return middleware.Responder, so all our generated response function are extend the interface of middleware.Responder , so everyone will generate a WriteResponse function. 

So my question is, how could I add other items, such as cookies , before I WriteResponse() ? 

Should I write something like 

```go
	middleware.ResponderFunc(myhandler)
```

Thanks

**Comment by casualjim** [comment]
you may want to make your own responder, then you have access to the response writer and you can set your cookie

**Comment by xuanzhaopeng** [comment]
Hi @casualjim , thanks for your quick response

For example I have function like, which generated by Swagger
```go
type RegisterHandlerFunc func(RegisterParams, interface{}) middleware.Responder
```

Could u kindly give an short example, how could I use my own Responder? 

Thanks a lot

**Comment by xuanzhaopeng** [comment]
Just share my solution:
```go
import (
	"net/http"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

type CustomResponder struct {
	responder middleware.Responder
}

func NewCustomResponder(responder middleware.Responder) *CustomResponder {
	return &CustomResponder{
		responder: responder,
	}
}

func (this *CustomResponder) WriteResponse(rw http.ResponseWriter, p runtime.Producer) {
	cookie := http.Cookie{Name: "robin", Value:"abcd"}
	http.SetCookie(rw, &cookie)
	this.responder.WriteResponse(rw, p)
}
```
