### ISSUE TITLE
If Swagger spec doesn't include a definition schema reference in a response, the generated client returns nil

### ISSUE THREAD

**Issue by anweiss** [go-swagger/go-swagger#749]
## Problem statement

I'm currently generating a client from a spec in which one of the API operations doesn't reference a response definition. The API still returns a response, but it is not accessible since the `readResponse` implementation simply does a `return nil` since there is no model for it to reference.

Is there a way to return a generic response in this case?

## Swagger specification

2.0

## Steps to reproduce

Generate client from existing Swagger spec with an operation whose "200" response does not include a "schema" property

**Comment by casualjim** [comment]
people typically return a 204 for success responses that don't have content.
