### ISSUE TITLE
When scanning a response the definition is not ref'ed

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#75]
Doesn't seem to scan 

```go
// swagger:response resp
type Resp struct {
  User User
}
```

It's totally possible that this is better handled through documenting usage, but add a test to verify the right thing happens with the right annotations

**Comment by drewwells** [comment]
I'm still having issues with responses and I think this ticket is related...

swagger validate passes, but there's errors about missing definitions on editor.swagger.io which seems to manifest as missing responses on all the endpoints on swagger-ui here: https://skillful-elf-105206.appspot.com/swagger/#/admin/bookings/

My route looks like this:
```
// Bookings swagger:route GET /admin/bookings/ booking Bookings
//
// Bookings lists all the appointments that have been made on the site.
//
//
// Consumes:
// application/json
//
// Schemes: http, https
//
// Produces:
// application/json
//
// Responses:
// 200: BookingResponses
```

My response looks like this:
```
// BookingResponses is a slice of bookings
//
// swagger:response BookingResponses
type BookingResponses struct {
	// Booking slice
	//
	// in: body
	// required: true
	Bookings []makeplans.Booking `json:"bookings"`
}
```

**Comment by casualjim** [comment]
if I follow the packages then the makeplans.Booking model lives in a different repo is that right?
And one is a git repo and the other a mercurial one?

**Comment by drewwells** [comment]
The bookingresponse is in a private git bit bucket repo and wraps booking
in a separate repo. I can make a complete example in a gist so you can see
it end to end.

**Comment by drewwells** [comment]
Here's a gist and output from `swagger generate spec`: https://gist.github.com/drewwells/f6bad58215d15ab0d8b4

swagger-ui doesn't validate b/c something is off, but I think that's unrelated to the responses models being empty.

**Comment by casualjim** [comment]
in that gist there is no mention of booking responses besides the mention in the route comment. I'm assuming in the actual code there is a thing like:

```go
type BookingResponses []BookingResponse
```

**Comment by drewwells** [comment]
ack, you are right there's a typo in the gist. I reran it as BookingResponse

Here's the output from swagger-ui about the response model: `https://gist.githubusercontent.com/drewwells/f6bad58215d15ab0d8b4/raw/01c783261ea02f7e7f52d31a8573760077826d68/gist.json#/definitions/Booking is not defined!`

**Comment by casualjim** [comment]
In the end the generated spec has a faulty ref where it uses the model instead of the response as $ref. Manual editing fixes this

```diff
     "BookingResponse": {
       "description": "BookingResponse represents a scheduled appointment",
       "schema": {
-        "$ref": "#/definitions/Booking"
+        "$ref": "#/definitions/BookingResponse"
       }
     }
   }
```

**Comment by drewwells** [comment]
This is consistent with my experience. When the internal structs do get definitions, they get shown in the swagger-ui output. So instead of it showing my nested responses `BookingResponse{ Booking: {} }` in the response model, it shows just `Booking{}`. So there must be some unwrapping going on here.

**Comment by casualjim** [comment]
I can't reproduce this problem.

for the code in that gist I get the following spec.

```json
{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "the purpose of this application is to provide an application\nthat is using plain go code to define an API",
    "title": "API.",
    "version": "0.0.1"
  },
  "host": "localhost",
  "paths": {
    "/admin/bookings/": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "schemes": [
          "http",
          "https"
        ],
        "tags": [
          "booking"
        ],
        "summary": "Bookings lists all the appointments that have been made on the site.",
        "operationId": "Bookings",
        "responses": {
          "200": {
            "$ref": "#/responses/BookingResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "description": "A Booking in the system",
      "type": "object",
      "required": [
        "id",
        "Subject"
      ],
      "properties": {
        "Subject": {
          "description": "Subject the subject of this booking",
          "type": "string"
        },
        "id": {
          "description": "ID the id of the booking",
          "type": "integer",
          "format": "int64",
          "x-go-name": "ID",
          "readOnly": true
        }
      },
      "x-go-package": "github.com/go-swagger/scan-repo-boundary/makeplans"
    }
  },
  "responses": {
    "BookingResponse": {
      "description": "BookingResponse represents a scheduled appointment",
      "schema": {
        "$ref": "#/definitions/Booking"
      }
    }
  }
}
```

**Comment by drewwells** [comment]
That's the behavior I'm trying to understand

```
"responses": {
    "BookingResponse": {
      "description": "BookingResponse represents a scheduled appointment",
      "schema": {
        "$ref": "#/definitions/Booking"
      }
    }
  }
```

BookingResponse is being unwrapped. So `Booking:{}` is returned instead of `BookingResponse{Booking:{}}`. The response is BookingResponse, not Booking. swagger-ui makes this worse, since it has a bug with looking up that remote ref in the definition.

**Comment by drewwells** [comment]
Working as intended, this can be closed

**Comment by casualjim** [comment]
thanks for the effort :100:
