### ISSUE TITLE
io.EOF error when getting successful HTTP 200 response

### ISSUE THREAD

**Issue by anweiss** [go-swagger/go-swagger#752]
## Problem statement

Getting an io.EOF error that is not properly checked when unmarshalling a discriminator field that is empty at the time of the GET request. I've modified the generated client code to resolve this as follows:

Before:

```go
<myDiscriminator>, err := Unmarshal<myDiscriminator>(bytes.NewBuffer(<myDiscriminator>), runtime.JSONConsumer())
if err != nil {
  return err
}
```

After:

```go
<myDiscriminator>, err := Unmarshal<myDiscriminator>(bytes.NewBuffer(<myDiscriminator>), runtime.JSONConsumer())
if err != nil && err != io.EOF {
  return err
}
```

## Swagger specification

2.0

## Steps to reproduce

1. Use v0.7.4 of CLI
2. Generate client from existing spec with references to discriminator
3. Execute client operation that returns HTTP 200 with an empty response in the discriminator field

**Comment by casualjim** [comment]
A discriminator field can't be empty. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object

> Adds support for polymorphism. The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. The property name used MUST be defined at this schema and it MUST be in the required property list. When used, the value MUST be the name of this schema or any schema that inherits it.

Is there any chance you can actually submit swagger specifications to reproduce your issues?

**Comment by anweiss** [comment]
Hmm, good point. So my explanation of the issue may be incorrect. I'm using the Swagger spec here -> https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics.V2.0/export?DocumentFormat=Swagger&ApiName=Azure%20Machine%20Learning%20-%20Text%20Analytics

More specifically, when I call the /operations/{operationId} endpoint, the operationProcessingResult property of the OperationResult is empty on the first few HTTP 200 responses. The <myDiscriminator> placeholder in my code snippet is actually the OperationProcessingResult type.
