### ISSUE TITLE
unable to determine package for

### ISSUE THREAD

**Issue by aep** [go-swagger/go-swagger#753]
````
//Foo does stuff
//swagger:response Foo
type Foo struct {
    Bar int
}
````

simply results in swagger exiting with:
`unable to determine package for /.../api.go`

removing "swagger:response" will make it work again, but i'm trying to add a result type here. or actually a model, but models can't be used as result.
Generally it would be nice if
 - there was a working example. The docs aren't exactly obvious.
 - swagger had error messages rather than just exiting.

**Comment by casualjim** [comment]
Thanks for your feedback.
I'm sorry you have a tough time, but this project is very much a project of volunteers. A number of people have fixed issues that they ran into. Similarly I use this project for work, so the little free time I have I spend on the issues that affect the teams I work with directly.

Are you sure you're using this in a gopath? And are your imports fully qualified imports?
As far as I know the examples in the [examples](https://github.com/go-swagger/go-swagger/tree/master/examples) folder all work correctly.
There is also the project I use for the tests of the scanner: https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing/classification

**Comment by aep** [comment]
ah yes, it could be me not understanding gopath.
````
mkdir foo
cd foo 
cat > main.go <<EOF
package main
//swagger:response Foo
type Foo struct {
    Bar int
}
EOF
GOPATH=$PWD swagger generate spec
unable to determine package for /tmp/foo/main.go

````


note that this only happens with response. everything else generates fine

**Comment by casualjim** [comment]
can you try this:

```
mkdir -p /tmp/go/src/foo
cat > /tmp/go/src/foo/main.go <<EOF
package main
//swagger:response Foo
type Foo struct {
    Bar int
}
EOF
GOPATH=/tmp/go swagger generate spec
```

go is opinionated about the gopath, you can read more about it here:
https://golang.org/doc/code.html
https://github.com/golang/go/wiki/GOPATH

**Comment by aep** [comment]
strange, but thanks alot for the explanation!
I'm using gom to ease the pain that is gopath, and gom exec didn't do the right thing in this specific case apparently. It would be nice if go-swagger just failed completely rather than just for response, so gom users can see the issue.

**Comment by aep** [comment]
actually this fixed my issue with gom:

````
mkdir src
ln -s .. src/main
gom exec sh -c "cd  src/main; swagger generate spec"
````

**Comment by casualjim** [comment]
I've added this to the faq now
