### ISSUE TITLE
How do you integrate the flag sets of go-swagger and other packages, in particular, glog?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#762]
## Problem statement

I am trying to integrate a package into a go-swagger generated API that is using the 'github.com/golang/glog' logger. When I initialize the glog logger it appears to shield the flags defined in the go-swagger runtime.

```
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\bin\runnerw.exe" "C:\Users\Theodore\AppData\Local\Temp\Build main.go and rungo" --tls-certificate ./security/mp.crt --tls-key ./security/mp.key --host 0.0.0.0 --tls-port 8090
GOROOT=C:/Go
GOPATH=C:/Users/Theodore/dev/Golang
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\bin\runnerw.exe" C:/Go\bin\go.exe build -o "C:\Users\Theodore\AppData\Local\Temp\Build main.go and rungo" C:/Users/Theodore/dev/Golang/src/github.com/medicarepathfinder/scoring_engine_mvp/api/cmd/mp-scoring-server/main.go
flag provided but not defined: -tls-certificate
Usage of C:\Users\Theodore\AppData\Local\Temp\Build main.go and rungo:
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

## Swagger specification
any

## Steps to reproduce
add a package with this code:
```
package engine

import (
	"github.com/golang/glog"
)

func init() {
	flag.Parse()
}

func EngineFunctionPoint() {
        glog.Info("EngineFunctionPoint called")
}
```

and call the EngineFunctionPoint() in the configureAPI() function of the API.

**Comment by casualjim** [comment]
the api has a Logger property that is a function with signature: `func(string, ...interface{})`
You can configure it with any logger that exposes the signature.
eg.: https://github.com/go-swagger/go-swagger/blob/master/examples/authentication/restapi/configure_auth_sample.go#L33

**Comment by Ravenwater** [comment]
Still having a problem with how and where to initialize glog so that both sets of flags are honored: the runtime flags, such as --tls-certificate and the glog flags like -log_dir and -stderrthreshold.

If I initialize glog in the config_xxx.go I don't get the go-swagger runtime flags, and if I initialize glog in the engine, I get the error, logging before flag.Parse.

**Comment by golisandeep3** [comment]
I am having the same problem, is there any fix for this ?

**Comment by casualjim** [comment]
You can generate a server with `--flag-strategy pflag`

After that you can use its integration to add goflags, you would do this in the main file. subsequently it's probably a good idea to generated code with `--exclude-main` so the update is preserved.

https://github.com/spf13/pflag#supporting-go-flags-when-using-pflag

```
import (
    goflag "flag"
    flag "github.com/spf13/pflag"
)

var ip *int = flag.Int("flagname", 1234, "help message for flagname")

func main() {
    flag.CommandLine.AddGoFlagSet(goflag.CommandLine)
    flag.Parse()
}
```
