### ISSUE TITLE
NSwag is generating strange types

### ISSUE THREAD

**Issue by chapas** [go-swagger/go-swagger#764]
Hi,
I'm using this code to generate the Swagger file:

`    private static readonly Lazy<NSwag.SwaggerDocument> _swagger = new Lazy<NSwag.SwaggerDocument>(() =>
        {
            IHttpRoute defaultRoute = new HttpRoute();
            GlobalConfiguration.Configuration.Routes.TryGetValue("DefaultApi", out defaultRoute);
            var settings = new WebApiToSwaggerGeneratorSettings
            {
                DefaultUrlTemplate = (defaultRoute == null ? "DefaultApi" : defaultRoute.RouteTemplate),
                IsAspNetCore = false,
                Title = "VBPISAPI",
                Description = "Business level API from APIS",
                Version = Assembly.GetExecutingAssembly().GetName().Version.ToString()
        };
var generator = new WebApiToSwaggerGenerator(settings);

            List<Type> derivedTypes = VType.GetDerivedTypes(typeof(ApiController), Assembly.GetExecutingAssembly());

            return generator.GenerateForControllers(derivedTypes);
        });
        public static void GenerateSwaggerFile()
        {
            string strJson = JsonConvert.SerializeObject(_swagger.Value, Formatting.Indented);

            File.WriteAllText(AppDomain.CurrentDomain.BaseDirectory + @"vbpisapi-swagger.json", strJson);
        }`

The file gets generated and somewhere in the definitions I find this:

`     "definitions": {
    "AssessmentStatus": {
      "type": "integer",
      "x-typeName": "AssessmentStatus",
      "x-enumNames": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "enum": [
        0,
        1,
        2
      ],
      "description": ""
    },
...... more definitions in between ....
    "ref_62c1b6ef_5b69_4574_be54_d9c177526403": {
      "type": "string",
      "x-typeName": "AssessmentStatus",
      "x-enumNames": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "enum": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "description": ""
    },`

Where did this "ref_" came from?

**Comment by casualjim** [comment]
This probably belongs on https://github.com/swagger-api/swagger-core or one of the repos in the https://github.com/swagger-apiswagger-api org  
This project is only about the go bindings for swagger
