### ISSUE TITLE
Definition field name not showing when string pattern validation failed, if use $ref to reference another one in defintions 

### ISSUE THREAD

**Issue by Simon-Li** [go-swagger/go-swagger#767]
## Problem statement
When a pattern validation fails on a field in request body, which is a type definition referencing to another definition, the returned error message won't show the validation failed field name, causing trouble to read what field failed at validation. 

## Swagger specification
'''
swagger: "2.0"
info:
  description: The product of a tutorial on goswagger.io
  title: A To Do list application
  version: 1.0.0
consumes:
- application/io.goswagger.examples.todo-list.v1+json
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
paths:
  /:
    get:
      tags:
        - todos
      operationId: findTodos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - todos
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - todos
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  IdentifierType:
    type: string
    format: identifier
    pattern: ^[A-Za-z][-A-Za-z0-9_]*$
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        $ref: '#/definitions/IdentifierType'        #<------ use another definition above, this causes the issue
#<----- if replacing the $ref reference to its direct definition, the issue is gone.
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
'''

## Steps to reproduce
a git repo can be provided if needed.

**Comment by Simon-Li** [comment]
repaste the yaml spec (for better print).

```yaml
swagger: "2.0"
info:
  description: The product of a tutorial on goswagger.io
  title: A To Do list application
  version: 1.0.0
consumes:
- application/io.goswagger.examples.todo-list.v1+json
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
paths:
  /:
    get:
      tags:
        - todos
      operationId: findTodos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - todos
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - todos
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  IdentifierType:
    type: string
    format: identifier
    pattern: ^[A-Za-z][-A-Za-z0-9_]*$
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        $ref: '#/definitions/IdentifierType'  #use its definition above, this causes the issue, if replacing the $ref reference to its direct definition, the issue is gone.
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
```

**Comment by Simon-Li** [comment]
Here is the error in rest response:

```
curl -l localhost:58408 -d "{\"description\":\"____message\"}" -H 'Content-Type: application/io.goswagger.examples.todo-list.v1+json'

{"code":605,"message":" in body should match '^[A-Za-z][-A-Za-z0-9_]*$'"}
# missing "description" field name in the above log, actually showing empty before "in body should..."
```

**Comment by Simon-Li** [comment]
@casualjim solved this issue on an internal codebase, would you mind that I initiate an PR for it? thanks!

**Comment by casualjim** [comment]
by all means!

**Comment by casualjim** [comment]
Reopened until a solution that is backwards compatible can be added
