### ISSUE TITLE
Question: Is it possible to use existing type instead of generated model?

### ISSUE THREAD

**Issue by nikolay-turpitko** [go-swagger/go-swagger#778]
## Problem statement

I'm trying to generate client code from yaml spec. There is a complex type (JWK), which is returned by API and already modeled within app with existing type ("github.com/mendsley/gojwk"). This type is able to unmarshal itself from json, besides, it does some computations to decode keys after that (because of that I cannot replace it with generated one).

Currently, I described fields of JWK in the yaml spec and go-swagger generates me a parallel type,  which I have to convert to desired type copying all fields one-by-one. I wonder, if some more convenient option exists for that? May be I can provide desired type name in yaml spec somehow, so that go-swagger would use it instead of generating a new one?

## Swagger specification

swagger 2.0 yaml

**Comment by casualjim** [comment]
unfortunately this doesn't exist today, the only thing you can do is exclude models from being generated.
That being said I think this would not be terribly hard to add though as an extra set of flags or a part of the config file.
I think it would be a valuable addition to this toolkit and I'd welcome a PR that added support for this.

**Comment by nikolay-turpitko** [comment]
@casualjim: Well, I tried to sort it out myself, but have a couple of questions and a sense that may be I am heading in a wrong direction. Could you please take a look at [the gist](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690)?

What I want to achieve. I have [this definitions in the swagger yaml spec](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690#file-spec-yaml-L265) - an array of JWKs, and I want JWK be modeled with [this existing go class](https://github.com/mendsley/gojwk/blob/master/key.go), which come from the lib. I wrapped lib's class with [my own one](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690#file-jwk-go) to add a stub Validate method (so that generated code be able to compile). Now I want from the go-swagger that it generate me a go code with an array of my custom jwk elements.

What I tried so far. Not sure, whether it is a misuse for  `x-go-name` and `x-go-package` tags, but I like names and decided to use them, [I added these tags to the JsonWebKey type definition in the spec](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690#file-spec-yaml-L305). Next, I hacked go-swagger's `generator/model.go` to skip the definition with `x-go-package` tag. And hacked `typeResolver` to return `jwk.Key` as go type for it (name constructed as base name of the package from the `x-go-package` plus name from the `x-go-name`). I created a [patch](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690#file-patch) to illustrate changes (it's not a PR, just for the sake of the question). OK, with these changes it [kinda did what I wanted](https://gist.github.com/nikolay-turpitko/a2a79a5b83462339bcf0fefccc306690#file-json_web_key_set-go). This code compiled and go tests in `go-swagger/genearator` passed (have not tried all other tests yet, though).

It's almost OK, but I cannot figure out where the import string came from. It magically appeared and happened to be correct. But if I change package name to, for example `gojwk`, it finds and imports the package with the same name from the lib, not the package from my project. I want to put my full package name from the `x-go-package` somewhere, so that it always be used.

And overall, this hack feels a bit clumsy, I'd anticipate to fix the method t.goTypeName() instead, so that approach would work not only in `resolveSchemaRef`, but whenever t.goTypeName() invoked. But if I try to move fix there, some existing go tests fails. Also, some hack already existed for `x-go-name` exactly at the same spots.

**Comment by casualjim** [comment]
I think it might be worth defining 2 new vendor extensions because I think x-go-package and x-go-name have a slightly different reason for existing. Perhaps something like `x-go-type` and `"x-go-import": { "package": "github.com/user/package", "alias":"jwk" }`

We can also make the check for the Validate implementation optional and only when it can be converted to that interface we'll call the method. That can save you having to wrap the type for the sake of implementing a dummy interface.

> but I cannot figure out where the import string came from
When a go file is generated we call `goimports` which fixes up imports and formats the file, so that might explain why you get the automatic import in there.

I think you're on the right track with this fix

**Comment by nikolay-turpitko** [comment]
@casualjim: Ivan, I like idea with additional extensions. But should it be two separate extensions or just one? Like `"x-go-type": {"name": "Key", "package": "github.com/user/package", "alias":"jwk"}`. Right now I can't come up with example of separate usage of `x-go-type` and `x-go-import`.
