### ISSUE TITLE
Make it easier to re-use parameter config

### ISSUE THREAD

**Issue by clawconduce** [go-swagger/go-swagger#781]
## Problem statement

I have several endpoints that have very similar urls (GET, PUT, DELETE) all have an id in the URL.  These calls all accept different parameters in the body though.  I would like to specify the URL/in path parameters separately from the body and/or header parameters.

**Comment by clawconduce** [comment]
I just noticed that parameters can be references: http://swagger.io/specification/#parametersDefinitionsObject

Which fits nicely with this issue.  Here is an example of it being used: https://portal.victorops.com/public/api-docs/victorops-api-v1.yaml

**Comment by casualjim** [comment]
You can already reuse parameters, that captures this case
I think this is answered by: https://github.com/go-swagger/go-swagger/issues/782#issuecomment-266334244

**Comment by clawconduce** [comment]
Thanks!  I didn't realize the parameters structs joined together.  (Also, I hadn't found this doc yet <https://godoc.org/github.com/go-swagger/go-swagger/scan> until I grepped for the comment in the #782 comment, I've been using examples up until now).

Anyways, this works really well!  I still have a request though, which I think falls more under #782.  It believe in many cases, it would be more intuitive if the route could point to several `swagger:parameters`, than if several `swagger:parameters` pointed to the same route.  I will follow up there.
