### ISSUE TITLE
Question: How to include all operations?

### ISSUE THREAD

**Issue by bobvanluijt** [go-swagger/go-swagger#800]
## Problem statement

When I run: `swagger generate server --name=MyName --spec=current.json --default-scheme=https` I get the output: `no operations were selected`

Probably a n00b question, but how can I generate a server with _all_ operations? If I have missed the documentation, I would love to get the URL.

Thanks!

PS:
I have _many_ operations so, would be nice if I just can include all of them...

**Comment by casualjim** [comment]
is your spec valid? because the default behavior is everything

**Comment by GlenDC** [comment]
Would it be possible to perhaps include the spec file you're using, might help others in knowing why it doesn't work for you.

**Comment by bobvanluijt** [comment]
Thanks all, completely misunderstood this... Got it now.
