### ISSUE TITLE
Support array type validation for $ref definitions

### ISSUE THREAD

**Issue by Simon-Li** [go-swagger/go-swagger#805]
## Problem statement
Go-swagger supports array type validation for the modals that uses direct definition, while if the modal definition is set by $ref (aliased), the validation logic are not generated in Swagger templates rendering, causing Rest server unable to prevent invalid rest calls.

## Swagger specification
```
definitions:
  IdentifierType:
    type: string
    pattern: ^[A-Za-z][-A-Za-z0-9_]*$
  item:
    type: object
    properties:
      idlist:
        type: array
        items:
          $ref: '#/definitions/IdentifierType'
```
## Steps to reproduce
Generated rest server have no validation code rendered for array elements schema validation.

**Comment by linearregression** [comment]
@Simon-Li  why is this closed. I am seeing something similar. Did you find a solution?
