### ISSUE TITLE
unresolvable blank format, generates in swagger-codegen, created repo with results

### ISSUE THREAD

**Issue by techzilla** [go-swagger/go-swagger#811]
## Problem statement
```
2016/12/22 23:44:31 building a plan for generation
2016/12/22 23:44:31 planning definitions
unresolvable: [null] (format "")
```
## Swagger specification
https://github.com/techzilla/examplegolangrestapi/blob/master/swagger.json

Commited results of using swagger-codegen,
https://github.com/techzilla/examplegolangrestapi

## Steps to reproduce

    swagger generate server swagger.json

**Comment by casualjim** [comment]
The reason it generates with swagger-codegen is because swagger-codegen doesn't generate any of the models.
In the spec there is a property language with type: "null"
This is allowed in json schema but not in swagger 2.0's interpretation of json schema.
