### ISSUE TITLE
Provide check for runtime version

### ISSUE THREAD

**Issue by GlenDC** [go-swagger/go-swagger#818]
## Problem statement

The generator relies on the `go-openapi/runtime`, found in your `$GOPATH`. In case it or its dependencies are out-of-date, your generated code might be incorrect.

## Proposes Solution

Ideally we should probably make the go-swagger commands fail in case the runtime or (one of) its dependencies are out-of-date.

This issue is probably blocked until the official Golang dependency manager has been released.

**Comment by fredbi** [comment]
The generator depends on vendored runtime which is part of the repo (and for what matters, other dependencies), so it is not affected by the state of other instances of the runtime package in the `$GOPATH`  or elsewhere. So I think this one may be closed now.
