### ISSUE TITLE
various client generation fixes

### ISSUE THREAD

**Issue by vikstrous** [go-swagger/go-swagger#82]
Please take a look at these changes I made in my fork to get the client generation to work for my schema. Sorry, I can't provide a simple test case right now, and I don't know if this is the correct solution, but it works for me right now.

https://github.com/vikstrous/go-swagger/commit/35e98933b7cdc13f9811f07bc004932385a02dc0#diff-4d4fdff26b287fb670cca8f91d5fab55L46

https://github.com/vikstrous/go-swagger/commit/35e98933b7cdc13f9811f07bc004932385a02dc0#diff-6b20cc8a4514b56c8fc0488c02ece5f0R26

I also needed basic auth and a way to set the schema, which I hacked in here: https://github.com/vikstrous/go-swagger/commit/35e98933b7cdc13f9811f07bc004932385a02dc0#diff-a52382dc63bff4be8c1f89ca5125811bL75 

This line was messing up the paths, so I had to remove it: https://github.com/vikstrous/go-swagger/commit/35e98933b7cdc13f9811f07bc004932385a02dc0#diff-a52382dc63bff4be8c1f89ca5125811bL77

Feel free to apply some of these fixes to the main project. I don't know if my solution is the correct one and I just wanted to get something working first.

**Comment by casualjim** [comment]
I'm going to close this issue because the information from these commits have been added to the master branch here.

**Comment by vikstrous** [comment]
Sweet! Thanks!
