### ISSUE TITLE
Fail to include import "github.com/go-openapi/validate" in first go generate

### ISSUE THREAD

**Issue by etsangsplk** [go-swagger/go-swagger#824]
## Problem statement
On first go generate, the that import statement is missing. But issue second go generate without cleaning, that import statement will be included. But only on the code generated responses.
Makign any call to if err := validate.Required fail because of missing imports

## Swagger specification
Cannot incldue the whole spec but only the area that is causing the issue.
# define reusable parameters:

```yaml
parameters:
  MaxResults:
    name: maxResults
    required: false
    description: xXXXXXXXXXXXXX.
    type: number
    format: integer
    default: 100
    minimum: 0
    maximum: 10000
    exclusiveMinimum: true
    exclusiveMaximum: false
    in: query

paths:
  /Logs:
    get:
      operationId: "getLogs"
      summary: YYYYYYYYYYYYYY
      parameters:
       - $ref: "#/parameters/MaxResults"
.......
      responses:
        200:
          description: XXXXXXXXXXXXXX
          schema:
            type: object
            properties:
              nextToken:
                type: string
              assets:
                $ref: '#/definitions/Services'     <<<<---------
```
## Steps to reproduce
First go generate
Second go generate  will include the missing import statement.

**Comment by casualjim** [comment]
you need to get those packages on your gopath either by vendoring or go getting them.
After you've done that and regenerate everything should work. It's because we use goimports to reformat the file and optimize imports.

related: #817

**Comment by etsangsplk** [comment]
I checked vendor.json and it shows:

	{
			"checksumSHA1": "6UO+LC1EPixDQliIfk7XC/ikcJg=",
			"path": "github.com/go-openapi/validate",
			"revision": "027696d4b54399770f1cdcc6c6daa56975f9e14e",
			"revisionTime": "2016-10-15T05:30:59Z"
		},

**Comment by etsangsplk** [comment]
I tried to update to the latest validate but it seems worse off 
..... 
vendor/github.com/go-openapi/validate
vendor/github.com/go-openapi/validate/spec.go:198: s.spec.SpecFilePath undefined (type *loads.Document has no field or method SpecFilePath)
vendor/github.com/go-openapi/validate/spec.go:199: undefined: spec.ResolveRefWithBase
vendor/github.com/go-openapi/validate/spec.go:199: undefined: spec.ExpandOptions
vendor/github.com/go-openapi/validate/spec.go:623: s.spec.SpecFilePath undefined (type *loads.Document has no field or method SpecFilePath)

I cannot attach the whole vendor.json but only the lines about go-openapi

Part of the vendor.json that contains infor on go-openapi:

		{
			"checksumSHA1": "Ws2ljgpeN1KOb3np3u/18pPjZvo=",
			"path": "github.com/go-openapi/analysis",
			"revision": "7222828b8ce19afee3c595aef6643b9e42150120",
			"revisionTime": "2016-10-09T06:10:32Z"
		},
		{
			"checksumSHA1": "qdDVSYjJg4Z0RCOMN+H8THb7VgM=",
			"path": "github.com/go-openapi/errors",
			"revision": "4178436c9f2430cdd945c50301cfb61563b56573",
			"revisionTime": "2016-08-30T19:04:10Z"
		},
		{
			"checksumSHA1": "Au2qpfa4VkYqoEUjkd+pAzyL2cc=",
			"path": "github.com/go-openapi/jsonpointer",
			"revision": "46af16f9f7b149af66e5d1bd010e3574dc06de98",
			"revisionTime": "2016-07-04T18:59:06Z"
		},
		{
			"checksumSHA1": "jzzeiYHpHiEhmBNVQlBFw5Knvh0=",
			"path": "github.com/go-openapi/jsonreference",
			"revision": "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272",
			"revisionTime": "2016-07-04T19:01:45Z"
		},
		{
			"checksumSHA1": "1vfk/gaZY8+35N9yNFOTIUg1H4A=",
			"path": "github.com/go-openapi/loads",
			"revision": "9168874c33ac10e241ee7767ed9f5d209c2a5ab0",
			"revisionTime": "2016-10-15T05:15:24Z"
		},
		{
			"checksumSHA1": "oKtPUiZeACj17cKUpLPs9H3pDjg=",
			"path": "github.com/go-openapi/loads/fmts",
			"revision": "9168874c33ac10e241ee7767ed9f5d209c2a5ab0",
			"revisionTime": "2016-10-15T05:15:24Z"
		},
		{
			"checksumSHA1": "K/UP0+bs3W9f+krIVlyNJJlRveg=",
			"path": "github.com/go-openapi/runtime",
			"revision": "12c07accf0687ab20b1e7b6293d8012ce282499c",
			"revisionTime": "2016-11-12T08:02:51Z"
		},
		{
			"checksumSHA1": "EBbEdiRHuI/u0whMY15oJNbaZB0=",
			"path": "github.com/go-openapi/runtime/client",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "k/v0woh+D5uViAfNI59pG8cKj1k=",
			"path": "github.com/go-openapi/runtime/flagext",
			"revision": "14b161b40ece9dac8e244ab2fde2d209e108c6f5",
			"revisionTime": "2016-11-24T20:43:25Z"
		},
		{
			"checksumSHA1": "hEfnshtHJsDTD+WNrVcbymBbupo=",
			"path": "github.com/go-openapi/runtime/internal/testing",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "0eungaSRPI/TsdGMs9oe8KJjn3w=",
			"path": "github.com/go-openapi/runtime/internal/testing/petstore",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "+cbiC4kf2T07TynJFKo4w8YFWb8=",
			"path": "github.com/go-openapi/runtime/middleware",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "NcTUgn9dgtv404Xz3UNAlqZfg4M=",
			"path": "github.com/go-openapi/runtime/middleware/denco",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "LAXDYZDlho3/kTzzHvJahQd44ns=",
			"path": "github.com/go-openapi/runtime/middleware/header",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "F7CZ0biPX37d51UhPyuT/DHD0d0=",
			"path": "github.com/go-openapi/runtime/middleware/untyped",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "mPl1xXsO+Ugmdlj7ZNfbbNcG6mk=",
			"path": "github.com/go-openapi/runtime/security",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "Mj44wpoxrYOMpZUK5ACmMh0Po7U=",
			"path": "github.com/go-openapi/runtime/yamlpc",
			"revision": "2faaf90bf67e0616db00094f2141f99b00a9ebc2",
			"revisionTime": "2016-10-19T07:03:01Z"
		},
		{
			"checksumSHA1": "6QkdP1VGwazrtwSbzHeKAjdZJSE=",
			"path": "github.com/go-openapi/spec",
			"revision": "8f2b3d0e3aa15100eea0ab61dc6fa02f00f5e713",
			"revisionTime": "2016-10-13T15:53:17Z"
		},
		{
			"checksumSHA1": "CfKtwdQamXbI88cSI5JTLWwZtcc=",
			"path": "github.com/go-openapi/strfmt",
			"revision": "d65c7fdb29eca313476e529628176fe17e58c488",
			"revisionTime": "2016-08-12T05:05:34Z"
		},
		{
			"checksumSHA1": "oncFAnX5ic6dHOHUz3HmmIxu6m8=",
			"path": "github.com/go-openapi/swag",
			"revision": "3b6d86cd965820f968760d5d419cb4add096bdd7",
			"revisionTime": "2016-10-24T02:49:19Z"
		},
		{
			"checksumSHA1": "6UO+LC1EPixDQliIfk7XC/ikcJg=",
			"path": "github.com/go-openapi/validate",
			"revision": "027696d4b54399770f1cdcc6c6daa56975f9e14e",
			"revisionTime": "2016-10-15T05:30:59Z"
		},
		{
			"checksumSHA1": "JSHl8b3nI8EWvzm+uyrIqj2Hiu4=",
			"path": "github.com/golang/mock/gomock",
			"revision": "bd3c8e81be01eef76d4b503f5e687d2d1354d2d9",
			"revisionTime": "2016-01-21T18:51:14Z"
		},
		





vendor/github.com/go-openapi/validate/spec.go:623: too many arguments in call to r.IsValidURI

**Comment by casualjim** [comment]
with govendor you need to update the dependencies manuall
so you also need to update:

* github.com/go-openapi/loads
* github.com/go-openapi/analysis
* github.com/go-openapi/runtime
* github.com/go-openapi/spec
* github.com/go-openapi/swag

**Comment by linearregression** [comment]
The error goes away if juse use concrete type like just array 
instead of a compound one like in the first comment. If you do something like the first comment shows to use type object to return a primitive type and then a list of a struct the the erro comes back

**Comment by casualjim** [comment]
the spec is invalid too. If you want an integer number you need to use

```yaml
# int32
type: integer
format: int32
# int64
type: integer
format: int64
```

**Comment by etsangsplk** [comment]
I made the change but the error still pops up.  So the spec is like
```
  MaxResults:
    name: maxResults
    required: false
    description: The maximum number of results to return.
    type: integer
    format: int64
    default: 100 
    minimum: 0
    maximum: 10000
    in: query
```
Adding or removing   exclusiveMinimum or exclusiveMaximum, does not make a dent to the issue.
I can see the code generate but jsut not the required import at the top:
```
import (
	"net/http"

	"github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
       ....
)
```
```
// swagger:model WhyIsThisHappening
type WhyIsThisHappening struct {

	// assets
	// Required: true
	Assets models.Clusters `json:"assets"`

	// next token
	// Required: true
	NextToken *string `json:"nextToken"`
}

// Validate validates this list clusters pages o k body
func (o *WhyIsThisHappening) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssets(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateNextToken(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WhyIsThisHappening) validateAssets(formats strfmt.Registry) error {

	if err := validate.Required("listClustersPagesOK"+"."+"assets", "body", o.Assets); err != nil {
		return err
	}

	return nil
}

func (o *WhyIsThisHappening) validateNextToken(formats strfmt.Registry) error {

	if err := validate.Required("listClustersPagesOK"+"."+"nextToken", "body", o.NextToken); err != nil {
		return err
	}

	return nil
}```

**Comment by casualjim** [comment]
What's the go version you're using?
What's the OS you're using?
Would it be possible to post a single complete spec that exhibits the issue (something that can be added to the tests)?

**Comment by etsangsplk** [comment]
I replaced some string with "whyIsThisHappening" because it is too specific.
go version go1.7.4 darwin/amd64

```
2016/12/28 11:39:28 making gen schema (anon: true, req: true, tuple: false) whyIsThisHappening
2016/12/28 11:39:28 {
  "type": "object",
  "properties": {
    "assets": {
      "$ref": "#/definitions/Clusters"
    },
    "nextToken": {
      "type": "string"
    }
  }
}
2016/12/28 11:39:28 after shortcuit named ref
2016/12/28 11:39:28 {
  "type": "object",
  "properties": {
    "assets": {
      "$ref": "#/definitions/Clusters"
    },
    "nextToken": {
      "type": "string"
    }
  }
}
2016/12/28 11:39:28 after lifting special all of
2016/12/28 11:39:28 {
  "type": "object",
  "properties": {
    "assets": {
      "$ref": "#/definitions/Clusters"
    },
    "nextToken": {
      "type": "string"
    }
  }
}
2016/12/28 11:39:28 building all of for 0 entries
2016/12/28 11:39:28 {
  "type": "object",
  "properties": {
    "assets": {
      "$ref": "#/definitions/Clusters"
    },
    "nextToken": {
      "type": "string"
    }
  }
}
2016/12/28 11:39:28 model.go:1317: resolving schema (anon: true, req: true) 
2016/12/28 11:39:28 types.go:696: resolving object (anon: true, req: false)
2016/12/28 11:39:28 gschema rrequired true nullable false
2016/12/28 11:39:28 gschema nullable true
2016/12/28 11:39:28 model.go:1339: resolving schema (anon: true, req: true) 
2016/12/28 11:39:28 types.go:696: resolving object (anon: true, req: false)
2016/12/28 11:39:28 gschema nnullable true
2016/12/28 11:39:28 building properties whyIsThisHappening (parent: whyIsThisHappening)
2016/12/28 11:39:28 building property whyIsThisHappening["assets"] (tup: false) {
  "type": "object",
  "properties": {
    "assets": {
      "$ref": "#/definitions/Clusters"
    },
    "nextToken": {
      "type": "string"
    }
  }
}
2016/12/28 11:39:28 model.go:614: resolving schema (anon: true, req: false) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: false) #/definitions/Clusters
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: false) 
2016/12/28 11:39:28 types.go:666: resolving array (anon: false, req: false)
2016/12/28 11:39:28 types.go:464: resolving schema (anon: true, req: false) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: false) #/definitions/Cluster
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: false) 
2016/12/28 11:39:28 types.go:696: resolving object (anon: false, req: false)
2016/12/28 11:39:28 types.go:505: known def type: ""
2016/12/28 11:39:28 types.go:505: known def type clear: "" -> ""
2016/12/28 11:39:28 types.go:349: known def type: "Cluster"
2016/12/28 11:39:28 types.go:349: known def type clear: "Cluster" -> "models.Cluster"
2016/12/28 11:39:28 type name models.Cluster, package , alias 
2016/12/28 11:39:28 types.go:349: known def type: "Clusters"
2016/12/28 11:39:28 types.go:349: known def type clear: "Clusters" -> "models.Clusters"
2016/12/28 11:39:28 type name models.Clusters, package , alias 
2016/12/28 11:39:28 new struct branch whyIsThisHappening (parent whyIsThisHappening)
2016/12/28 11:39:28 cloning context whyIsThisHappening
2016/12/28 11:39:28 made new struct branch assets (parent whyIsThisHappening)
2016/12/28 11:39:28 making gen schema (anon: true, req: true, tuple: false) assets
2016/12/28 11:39:28 {
  "$ref": "#/definitions/Clusters"
}
2016/12/28 11:39:28 after shortcuit named ref
2016/12/28 11:39:28 {
  "$ref": "#/definitions/Clusters"
}
2016/12/28 11:39:28 after lifting special all of
2016/12/28 11:39:28 {
  "$ref": "#/definitions/Clusters"
}
2016/12/28 11:39:28 building all of for 0 entries
2016/12/28 11:39:28 {
  "$ref": "#/definitions/Clusters"
}
2016/12/28 11:39:28 model.go:1317: resolving schema (anon: true, req: true) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: true) #/definitions/Clusters
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: true) 
2016/12/28 11:39:28 types.go:666: resolving array (anon: false, req: false)
2016/12/28 11:39:28 types.go:464: resolving schema (anon: true, req: false) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: false) #/definitions/Cluster
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: false) 
2016/12/28 11:39:28 types.go:696: resolving object (anon: false, req: false)
2016/12/28 11:39:28 types.go:505: known def type: ""
2016/12/28 11:39:28 types.go:505: known def type clear: "" -> ""
2016/12/28 11:39:28 types.go:349: known def type: "Cluster"
2016/12/28 11:39:28 types.go:349: known def type clear: "Cluster" -> "models.Cluster"
2016/12/28 11:39:28 type name models.Cluster, package , alias 
2016/12/28 11:39:28 types.go:349: known def type: "Clusters"
2016/12/28 11:39:28 types.go:349: known def type clear: "Clusters" -> "models.Clusters"
2016/12/28 11:39:28 type name models.Clusters, package , alias 
2016/12/28 11:39:28 gschema rrequired true nullable false
2016/12/28 11:39:28 gschema nullable false
2016/12/28 11:39:28 model.go:1339: resolving schema (anon: true, req: true) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: true) #/definitions/Clusters
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: true) 
2016/12/28 11:39:28 types.go:666: resolving array (anon: false, req: false)
2016/12/28 11:39:28 types.go:464: resolving schema (anon: true, req: false) 
2016/12/28 11:39:28 types.go:648: resolving ref (anon: false, req: false) #/definitions/Cluster
2016/12/28 11:39:28 loading with base: ./specs/omg.yaml
2016/12/28 11:39:28 types.go:341: resolving schema (anon: false, req: false) 
2016/12/28 11:39:28 types.go:696: resolving object (anon: false, req: false)
2016/12/28 11:39:28 types.go:505: known def type: ""
2016/12/28 11:39:28 types.go:505: known def type clear: "" -> ""
2016/12/28 11:39:28 types.go:349: known def type: "Cluster"
2016/12/28 11:39:28 types.go:349: known def type clear: "Cluster" -> "models.Cluster"
2016/12/28 11:39:28 type name models.Cluster, package , alias 
2016/12/28 11:39:28 types.go:349: known def type: "Clusters"
2016/12/28 11:39:28 types.go:349: known def type clear: "Clusters" -> "models.Clusters"
2016/12/28 11:39:28 type name models.Clusters, package , alias 
2016/12/28 11:39:28 gschema nnullable false
2016/12/28 11:39:28 building properties assets (parent: whyIsThisHappening)
2016/12/28 11:39:28 finished gen schema for "assets"
```

**Comment by etsangsplk** [comment]
Sorry I can't because it is not an opensource project.

**Comment by GlenDC** [comment]
Could you perhaps try to make a small isolated yaml/json that reproduces the issue you're facing? This would help us debug your problem, while preventing you from having to share your actual swagger spec?

**Comment by casualjim** [comment]
Can you reproduce this with a minimal spec that you just make up? A minimal example that has nothing to do with your actual project. Something completely unrelated to your actual project. We don't care

With information like you shared the most likely outcome is nobody is going to look at it because too much effort/guesswork to reproduce this issue, or you have to debug it yourself.

The code that does the imports is here: https://github.com/golang/tools/tree/master/cmd/goimports
Swagger reformats and adds imports here: https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L95-L102

**Comment by etsangsplk** [comment]
It turns out it is related to this:

https://github.com/go-swagger/go-swagger/issues/756
The validate package is for some reason missing but other packages like github.com/go-openapi/strfmt is ok. So when goimport try to do its job, the package is not there and the import is missing as a result but just for those files (which are server response). There is a validate package but it is under go-openapi/vendor. For now I just add a goimport after the post processing to get around it.

Now have to add go get -u github.com/go-openapi/validate in generate.go, then $GOPATH/bin/goimports -w -v just fo fix those problematic files for a workaround
