### ISSUE TITLE
Enhancement: Include test suite

### ISSUE THREAD

**Issue by willis7** [go-swagger/go-swagger#831]
As a noobie to the language and the go-swagger tool, I feel like the documentation (even the auto generated code), would benefit from some programmatic tests. Especially, [this](https://goswagger.io/tutorial/todo-list.html) article.

I think providing a test suite will help build consumer confidence, especially around the code they are changing.

**Comment by GlenDC** [comment]
Related issues: #100, #99, #841

**Comment by fredbi** [comment]
Closes as this duplicates #100, #99 , #841
