### ISSUE TITLE
Implement ValidateNamed method to support validation errors with proper names

### ISSUE THREAD

**Issue by Simon-Li** [go-swagger/go-swagger#837]
Per @casualjim advice, a new method (ValidateNamed) should be considered to add in order to support validation errors with proper names. This is especially useful for the use case of aliased property types, in which a model can be referenced commonly (via $ref) by another property. For the sake of cleanness for the existing `Validate` implementation, the `ValidateNamed` method is therefore taken into this implementation.

**Comment by casualjim** [comment]
I've been thinking a bit more about this and because the thing being validated would always be called from another method., that method could just rewrite the errors by adding the field name info in there.
Less invasive

**Comment by Simon-Li** [comment]
@casualjim Woo... great hints! will verify it.
