### ISSUE TITLE
Type using allOf in generate server has broken MarshalJSON and UnmarshalJSON in 0.8.0

### ISSUE THREAD

**Issue by gregmarr** [go-swagger/go-swagger#847]
## Problem statement

A type, using allOf, generated by 0.7.4, doesn't implement MarshalJSON and UnmarshalJSON and works properly.  This same type, generated by 0.8.0, includes these functions, and they're broken.  
## Swagger specification

```yaml
swagger: '2.0'

info:
  title: ""

paths:
  /execute:
    post:
      responses:
        200:
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExecuteParametersWorkspace"

definitions:
  ExecuteParameters:
    type: "object"
    properties:
      WantGeometry:
        type: "boolean"

  ExecuteParametersWorkspace:
    allOf:
    - $ref: "#/definitions/ExecuteParameters"
    - required:
      - "Workspace"
      properties:
        Workspace:
          type: "string"
```

## Steps to reproduce

`swagger generate server`

Broken functions in 0.8.0:

```go
// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExecuteParametersWorkspace) UnmarshalJSON(raw []byte) error {

	var aO0 ExecuteParameters
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ExecuteParameters = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExecuteParametersWorkspace) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.ExecuteParameters)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}
```

**Comment by Simon-Li** [comment]
Curious what do you mean `broken functions` in 0.8.0? Just tested with the above spec, not seeing errors though.

**Comment by GlenDC** [comment]
@casualjim what's actually the reason that you added an explicit Marshal-/UnmarshalJSON function in v0.8.0 (https://github.com/go-swagger/go-swagger/commit/de870963a73dd4cc2f2d11d0099e51b26eb33020)? In what cases was the implicit version not good enough?

**Comment by casualjim** [comment]
For composed objects there might also be inheritance involved etc. At first glance I don't know why the custom marshaller was triggered because there is no discriminator involved.
 
In the future it would be nice to generate custom marshal/unmarshal methods for every generated struct using https://github.com/mailru/easyjson

**Comment by gregmarr** [comment]
@GlenDC Yes, that's what I meant.  Thanks for clarifying.  I totally missed that I didn't say how it was broken.

**Comment by GlenDC** [comment]
@casualjim but AFAIK the default marshaller works fine with inheritance, did a play ground test before asking my previous question to be sure. Can you give a situation where the implicit marshaler wouldn't work?

**Comment by casualjim** [comment]
when a discriminator is involved because then you have only an interface and it needs to be able to marshal a concrete type

**Comment by gregmarr** [comment]
Looks like this "use the polymorphic marshal" is triggered by the type having a property that is a parametric type or an array of a polymorphic type:

```
  Values:
    type: "object"
    properties:
      Value:
        $ref: "#/definitions/Value"
      Array:
        type: "array"
        items:
          $ref: "#/definitions/Value"

  Value:
    type: "object"
    discriminator: "ValueType"
    required:
    - "ValueType"
    properties:
      ValueType:
        type: "string"

  ValueNumber:
    allOf:
    - $ref: "#/definitions/Value"
    - required:
      - "Value"
      properties:
        Value:
          type: "number"
```

This function is failing because I only set one or the other of `Array` or `Value` (since Swagger doesn't have `anyOf` yet), and this returns an error at the read of `Value` when it isn't provided.  It checks to see if `Array` is there before it tries to read it, but not `Value`.

```
// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *Values) UnmarshalJSON(raw []byte) error {
	var data struct {
		Array json.RawMessage `json:"Array,omitempty"`

		Value json.RawMessage `json:"Value,omitempty"`
	}

	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var array []Value

	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	untypedObj := make(map[string]interface{})
	if err := dec.Decode(&untypedObj); err != nil {
		return err
	}
	if untypedArray, ok := untypedObj["Array"]; ok {
		if slcArray, ok := untypedArray.([]interface{}); ok {
			for _, slcEl := range slcArray {
				slcJSON, _ := json.Marshal(slcEl)
				slcObj, err := UnmarshalValue(bytes.NewBuffer(slcJSON), runtime.JSONConsumer())
				if err != nil {
					return err
				}
				array = append(array, slcObj)
			}
		}
	}

	value, err := UnmarshalValue(bytes.NewBuffer(data.Value), runtime.JSONConsumer())
	if err != nil {
		return err
	}

	var result Values
	result.Array = array
	result.Value = value
	*m = result
	return nil
}
```

Here is the json that it's trying to unmarshal, to an array of `Values` objects:
```
[ { "Value": { "ValueType": "ValueNumber", "Value": 2 } } ,
  { "Array": [ { "ValueType": "ValueNumber", "Value": 0 } ] } ]
```

**Comment by gregmarr** [comment]
I made this function work by some slight modifications of the generated code:
```
	var value PortValue

	if len(data.Value) > 0 {
		var err error
		value, err = UnmarshalPortValue(bytes.NewBuffer(data.Value), runtime.JSONConsumer())
		if err != nil {
			return err
		}
	}
```

**Comment by yan-zhuang** [comment]
I used the latest swagger today, and it's still broken, i.e: the properties other than allOf are not marshaled/un-marshaled.

**Comment by yan-zhuang** [comment]
It's broken since 71225c4a7882ae49cd57e22292a58dff382908e8.
Would some one bring this fix in?
Thanks

**Comment by yan-zhuang** [comment]
I created a new issue about this. https://github.com/go-swagger/go-swagger/issues/1042
