### ISSUE TITLE
handler in todo-list tutorial doesn't match the example code

### ISSUE THREAD

**Issue by nathany** [go-swagger/go-swagger#858]
The tutorial at https://goswagger.io/tutorial/todo-list.html contains the following handler with an obvious race condition:

```go
api.TodosDestroyOneHandler = todos.DestroyOneHandlerFunc(func(params todos.DestroyOneParams) middleware.Responder {
  delete(items, params.ID)
  return todos.NewDestroyOneNoContent()
})
```

The example code is quite different these days:
https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go#L116

Should the tutorial be updated? And if so, should it match the example code exactly?

**Comment by GlenDC** [comment]
@nathany the tutorial code should indeed match the example code directly. The example code is usually pretty up to date.

To be sure you can also always regenerate the examples as follows:

1. fetch master & rebase it on your local master;
2. install latest swagger cmd via `go install ./cmd/swagger`;
2. run `./hack/regen-samples.sh` on a *nix system;

This will regenerate all examples using the swagger tool. Should always be up to date, but in case you notice that it is out of date with the latest master, feel free to open a PR with those changes.

**Comment by fredbi** [comment]
Source is now provided as a link in the doc.
The race condition mentioned above is fixed in the example.
Examples have been recently refreshed with PR #1478
