### ISSUE TITLE
swagger validate: the need for better error messages

### ISSUE THREAD

**Issue by nathany** [go-swagger/go-swagger#859]
## Problem statement

`swagger validate` produces some pretty unhelpful error messages, such as `object has no key ""` for the following incomplete swagger spec.

Contrast with an online Swagger validator like http://bigstickcarpet.com/swagger-parser/www/index.html (based on https://github.com/BigstickCarpet/swagger-parser) which specifically calls out:

```
Error resolving $ref pointer "#/responses/". 
Token "responses" does not exist.
```

Much more helpful.

## Swagger specification

```
{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "description",
    "title": "title",
    "version": "1.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/v1/authenticate": {
      "get": {
        "summary": "Authenticate with a token (JWT).",
        "operationId": "authHandler",
        "responses": {
          "200": {
            "$ref": "#/responses/"
          }
        }
      }
    }
  },
  "definitions": {}
}
````

## Steps to reproduce

```
❯ swagger validate swagger.json
The swagger spec at "swagger.json" is invalid against swagger specification 2.0. see errors :
- object has no key ""
```

**Comment by aleksclark** [comment]
I'd like to suggest this issue be closed, or at least raised to the go-openapi/jsonpointer repository.

This error:
1) is perfectly valid - parsing `"#/responses/"` has resulted in an empty key
2) is being generated by go-openapi/jsonpointer
3) doesn't possess the document context sufficient to provide a line number for where it has been generated (but that's again, a matter for the jsonpointer package)

**Comment by nathany** [comment]
@aleksclark By all means, if the issue is in a dependency, it makes sense to open an issue there. (I had no way of knowing that).

**Comment by casualjim** [comment]
json ast with support for parser position. https://github.com/ajeddeloh/go-json

**Comment by spragchris** [comment]
Is this only for open api? Is there any hope to fix error messages for swagger editor for 2.0? The messages are so horrific that I spend hours in trial and error fixing my documentation.

**Comment by gregmarr** [comment]
This is just for the Go framework.  It has no relation to the main project editors.

I agree that the editor error messages are generally awful.

**Comment by spragchris** [comment]
Ah... ok. Well then I'm glad we at least shared that pain! Nevermind!

**Comment by flwrchild42** [comment]
What do I do
