### ISSUE TITLE
Debugging generated client at runtime

### ISSUE THREAD

**Issue by ezeev** [go-swagger/go-swagger#862]
## Problem statement

https://goswagger.io/generate/client.html

The instructions on this page state the following:

`If you want to debug what the client is sending and receiving you can set the environment value DEBUG to a non-empty value.`

I'm trying to debug what a client I generated with go-swagger is sending and receiving but I'm not seeing any output other than the error I'm catching: "context deadline exceeded". 

I set an env variable, `export DEBUG=true` before generating and using the packages, but it doesn't appear to be creating any extra output. I searched the generated code and don't see any attempts to read a "DEBUG" env var.

Is this a bug in the docs or am I interpreting it wrong?

Thanks,
Evan

**Comment by casualjim** [comment]
you can run your code with DEBUG=1 env var and it will print request/response

**Comment by GlenDC** [comment]
@casualjim: the code and the documentation do specify slightly different behavior:

The documentation specifies:

> If you want to debug what the client is sending and receiving you can set the environment value DEBUG to a non-empty value.

Yet the code (https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L158) specifies:

```go
rt.Debug = os.Getenv("DEBUG") == "1"
```

I think the documentation makes more sense, as it's the more common liberal approach. So should I open a PR in https://github.com/go-openapi/runtime to make the documentation and code match once again?

**Comment by casualjim** [comment]
go for it
