### ISSUE TITLE
Generator don't generates validation for embended models

### ISSUE THREAD

**Issue by westito** [go-swagger/go-swagger#866]
## Problem statement
When I write the model schema directly into the query (and not use separete definition for the model) the validations like maxLength, required do not generates for the model. But when I but the schama in the definition section, and $ref to it, the validations are get generated.

## Swagger specification
```yaml
responses:
        200:
          description: Success
          schema:
            required:
              - data
            properties:
              data:
                required:
                  - account_id
                  - access_token
                properties:
                  account_id:
                    type: integer
                    format: int64
                  access_token:
                    type: string
                    maxLength: 64
```

**Comment by casualjim** [comment]
a work around for this is to flatten the spec before generating it
