### ISSUE TITLE
Cannot parse time formats that look like this: 2017-01-17T22:58:45

### ISSUE THREAD

**Issue by ryanwalls** [go-swagger/go-swagger#873]
## Problem statement

When deserializing JSON from a server that has date formats that look like this: `2017-01-17T22:58:45`, I get a parsing error:
```
parsing time \"\"2017-01-17T22:58:45\"\" as \"\"2006-01-02T15:04:05Z07:00\"\": cannot parse \"\"\" as \"Z07:00\"
```

## Steps to reproduce
Try to deserialize `2017-01-17T22:58:45` into a strfmt.DateTime field

Suggestions?  I tried manually changing the generated code to a time.Time, but still get the error.

**Comment by casualjim** [comment]
This time stamp is missing zone info, it should end with Z for UTC IIRC
It can be fixed by adding more patterns here: https://github.com/go-openapi/strfmt/blob/master/time.go#L60
