### ISSUE TITLE
`target must reside inside a location in the $GOPATH/src` for binary distribution

### ISSUE THREAD

**Issue by NaNuNaNu** [go-swagger/go-swagger#892]
## Problem statement
When using the brew installed binary and running `swagger generate client` inside $GOPATH/src/something, generation fails with `target must reside inside a location in the $GOPATH/src`
Using the binary by getting it with `go get` works fine.

## Steps to reproduce

brew install go-swagger
download a swagger json definition file and place it in a subdirectory under $GOPATH
swagger generate client
`target must reside inside a location in the $GOPATH/src`

brew uninstall go-swagger
go get -u github.com/go-swagger/go-swagger/cmd/swagger
swagger generate client
`Generation completed!`

## Environment
swagger version: brew 0.8.0, go get dev  
go version: go1.7.3
OS: macOS 10.12.2

**Comment by GlenDC** [comment]
Possibly related to #887

**Comment by GlenDC** [comment]
I cannot reproduce your steps. For me it works fine, even using the brew version.

Are you working in a container? As that is what was causing the issues in #887.

**Comment by NaNuNaNu** [comment]
No I was just using it raw. I'll try to generate a more detailed report for you.

**Comment by NaNuNaNu** [comment]
Can't reproduce it anymore myself so might as well close this i guess.
