### ISSUE TITLE
Flattened spec does not validate.

### ISSUE THREAD

**Issue by marcusljx** [go-swagger/go-swagger#898]
## Problem statement
Flattened swagger definition with empty `definitions` body throws an error when used with `swagger generate`

## Swagger specification
As detailed in #890 

## Steps to reproduce
run `swagger flatten ./_api/index.yaml -o ./_api/swagger_flattened.json`
produces flattened swagger file.
run `swagger validate ./api/swagger_flattened.json`

## Expected Outcome
Flattened spec validates

## Actual Outcome
`swagger validate` throws error:
```
The swagger spec at "_api/swagger_flattened.json" is invalid against swagger specification 2.0. see errors :
- definitions in body must be of type object: "null"
```
which is weird because the `"definitions": null` line is added by `swagger flatten`.

## Environment
swagger version: dev
go version: 1.7 linux/amd64
OS: Linux Ubuntu 16.04LTS

**Comment by GlenDC** [comment]
The issue for this bug has been found and a [PR for go-openapi/spec][PR], containing that fix, is opened.

Once that [PR][] has been accepted, we'll have to update the vendored version used for go-swagger, which will fix this issue when merged in.

[PR]: https://github.com/go-openapi/spec/pull/19
