### ISSUE TITLE
Path not found error for endpoint with trailing slash

### ISSUE THREAD

**Issue by alexmontecucco** [go-swagger/go-swagger#899]
## Problem statement

Hello
When I specify endpoints ending with a slash in my swagger file, at runtime when trying to reach the same endpoint I get a `{"code":404,"message":"path /trailingslashpath/ was not found"}` response.

It looks related to this: [github.com/go-swagger/go-swagger/pull/292](https://github.com/go-swagger/go-swagger/pull/292) but the problem does not come from the same code.

I don't know if this is an expected result or not.
The behavior seems to be due to the [DefaultRouter](https://github.com/go-openapi/runtime/blob/master/middleware/router.go) function. It calls the 'path.Join' function which removes any trailing slash except for the root path. 
The result is that no handler seems to be registered. 

## Swagger specification

```swagger: "2.0"
info:
  title: api
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: /
paths:
  /trailingslashpath/:
    get:
      responses:
        204:
          description: OK no content
```

## Steps to reproduce

- Start the server generated using the swagger
- Call the server on the `/trailingslashpath/`

## Environment
swagger version: dev
go version: 1.7.3
OS:  Debian 8.7

**Comment by GlenDC** [comment]
@casualjim did you have a local fix somewhere for this, or do you need people to look at this?

**Comment by casualjim** [comment]
I have a fix locally for this, but still need to write a test for it. Work gets in between

**Comment by cameacke** [comment]
I'm on tip of master and I'm still having this problem even though a fix has been merged in.

**Comment by casualjim** [comment]
you have to update github.com/go-openapi/runtime that's where the fix really was made

**Comment by alexmontecucco** [comment]
It does not seem to be fixed. I updated the libs, but the thing is that in the `restapi/operations/api.go` generated file there is the following:
```
// HandlerFor gets a http.Handler for the provided operation method and path
func (o *API) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

...

func (o *API) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/trailingslashpath/"] = NewGetTrailingslashpath(o.context, o.GetTrailingslashpathHandler)

}
``` 

The problem is that `HandlerFor` is called with a path parameter without trailing slash and `initHandlerCache` is a map containing paths with trailing slashes.

Also, I could not fully understand the intended behavior from the fix. Do we want both with and without trailing slash paths to be handled the same way, or are they distinct paths ?

**Comment by alexmontecucco** [comment]
Fixed it thx.
Just to be sure: the expected result is that path with and without trailing slash are handled the same way ?

**Comment by casualjim** [comment]
yes according to the URI RFC a trailing slash is not significant
