### ISSUE TITLE
How to build hierarchical definitions for aggregation models?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#901]
## Problem statement
As the API endpoints proliferate, I am in need of aggregating leaf models into larger aggregate models through composition.

I thought I was getting the hang of the spec by doing this:

```
  plan_attributes:
    type: object
    required:
      - birthday
      - fipsCode
      - healthAssessment
    properties:
      birthday:
        type: string
        format: string
        minLength: 8
      fipsCode:
        type: string
        format: string
      healthAssessment:
        type: string
        format: string
      services:
        type: object
        $ref: "#/definitions/medicalServices"
      medications:
        type: object
        $ref: "#/definitions/drugList"
```

but that yields warnings like these from 'swagger serve my-api.yml':
Warning: Other properties are defined at the same level as $ref at "#/definitions/plan_attributes/properties/medications". They are IGNORED according to the JsonSchema spec
Warning: Other properties are defined at the same level as $ref at "#/definitions/plan_attributes/properties/services". They are IGNORED according to the JsonSchema spec

What is the proper way to aggregate leaf models into larger entities, without having to copy and paste all the attributes in the aggregation models?

## Environment
swagger version: dev  
go version: 1.7.4
OS: Windows 10

**Comment by casualjim** [comment]
remove `type: object` and you have the way

**Comment by Ravenwater** [comment]
That indeed was the way. This issue can be closed.
