### ISSUE TITLE
repeated resolve of remote ref fails

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#908]
local file: 

```yaml
swagger: "2.0"
info:
  title: Test external refs
  version: 0.0.0

x-external:
  $ref: https://gist.githubusercontent.com/caryfitzhugh/ee2c09cd7ad526bd23e3e1828c508272/raw

paths:
  /:
    get:
      parameters:
        - $ref: "#/x-external/parameters/complex-id"
      responses:
        default:
          description: who knows
```

remote file:

```yaml
parameters:
  complex-id:
    name: complex-id
    required: true
    in: path
    description: a complex id
    type: string
    pattern: '^(notcomplex.*)$'
```

**Comment by Grillz** [comment]
This has become a bit of a blocker for my team. If I can help out in any way here, let me know. Thanks

**Comment by casualjim** [comment]
the core of the issue will be found in this file: https://github.com/go-openapi/spec/blob/master/expander.go
And there are a bunch of tests for the functionality: https://github.com/go-openapi/spec/blob/master/expander_test.go

The current implementation mixes local and remote refs and doesn't favor remote refs as more important. This can be alleviated to some degree by using the flatten command before generating which does prioritize remote refs over local refs. Although it still doesn't deal with recursive remote refs, the source for it is here: https://github.com/go-openapi/analysis/blob/master/flatten.go
https://github.com/go-openapi/analysis/blob/master/flatten_test.go

**Comment by fredbi** [comment]
@casualjim this one should be working now don't you think?
