### ISSUE TITLE
UUIDs do not appear to be validated

### ISSUE THREAD

**Issue by bschofield** [go-swagger/go-swagger#909]
## Problem statement

In a server: When attempting to validate a UUID in client-supplied data, the generated code under `restapi/operations` will make a call like

    value, err := formats.Parse("uuid", raw)

This will cause the `Parse()` function in `go-openapi/strfmt/format.go` to be called, which will attempt to validate the format of the client-supplied data by applying the `strfmt.UUID.UnmarshalText()` function. 

However, the `strfmt.UUID.UnmarshalText()` function (defined in `go-openapi/strfmt/default.go`) actually accepts any input string and not just those formatted as UUIDs. (There is a comment associated with that function: "validation is performed later on".)

Should validation of UUIDs should actually be performed using `strfmt.IsUUID()`?

## Environment

swagger version: 0.8.0 (commit: d1a0b6c1007402b2ccde73702eb0e8e43a5e7498)
go version: 1.7.4 linux/amd64 
OS: Fedora 25

**Comment by bschofield** [comment]
Looking at this some more, it seems that `formats.Parse()` is actually working as designed, but is not intended to actually validate the string. Validation could be achieved by calling `formats.Validates("uuid", raw)` and checking the return value -- however this does not appear to happen in the generated code.

Is this something which should be happening, or have I misunderstood?

**Comment by bschofield** [comment]
It might also be worth mentioning that this is a parameter which is passed directly in the query string of a GET request, with no model generated. Relevant extract from spec:-

    /endpoint:
      get:
        parameters:
          - name: queryId
            in: query
            type: string
            format: uuid
            required: true

**Comment by casualjim** [comment]
this is a bug I think the format validator is never generated for the field

**Comment by fredbi** [comment]
It's a generic problem for all format validations occuring on all simple parameters (it works for schema).

@casualjim do you remember any specific reason to call directly strfmt rather than validate.FormatOf() like we do for schemas?

**Comment by fredbi** [comment]
The bug is similar to the one in #1347 
I'm testing a fix along the same lines: hasValidation should be true when a customFormat is applied.

I am suspecting there ae similar shortcomings with headers (as param, as response) and items in SimpleSchema params/headers

**Comment by fredbi** [comment]
Fixed operation binder would look like this. Tell me if you find anything wrong with this.
```golang
func (o *GetOptionalParams) bindNotAnOption2(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("notAnOption2", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("notAnOption2", "query", raw); err != nil {
		return err
	}

	if err := o.validateNotAnOption2(formats); err != nil {
		return err
	}

	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("notAnOption2", "query", "strfmt.UUID", raw)
	}
	o.NotAnOption2 = *(value.(*strfmt.UUID))

	return nil
}

func (o *GetOptionalParams) validateNotAnOption2(formats strfmt.Registry) error {

	if err := validate.FormatOf("notAnOption2", "query", "uuid", o.NotAnOption2.String(), formats); err != nil {
		return err
	}

	return nil
}
```
