### ISSUE TITLE
Can we set a User-Agent header?

### ISSUE THREAD

**Issue by thommahoney** [go-swagger/go-swagger#911]
## Problem statement

We would like to be able to set an arbitrary user-agent header either at client generation time or at compile time. Is it possible to do this?

## Swagger specification

The Swagger specification is irrelevant in this case because we are using the same specification to generate many clients.

**Comment by casualjim** [comment]
You can use a custom transport which allows you to set the user agent.
https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L132

And you can configure it with this constructor method
https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todo_list_client.go#L52


You can also configure that runtime with a stdlib http.Client 
https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L167

**Comment by thommahoney** [comment]
If I understand correctly, you're saying that we ought to write our own `Submit()` function (defined [here](https://github.com/go-openapi/runtime/blob/9d874dfae14238a34a7263c7278ce5663acb5fa8/client/runtime.go#L208)) that implements the `runtime.ClientTransport` interface and configure our client to use that instead using the `New()` function?

**Comment by casualjim** [comment]
You can extend intercept a http request with the http.RoundTripper interface. https://godoc.org/net/http#RoundTripper

which you can set here: https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L116
so for the client here: 

```go
var myRoundTripper http.RoundTripper = createRoundTripper()
transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
transport.Transport = myRoundTripper
todoListClient := New(transport, nil)
```

**Comment by thommahoney** [comment]
All set here. Thanks. Feel free to close this issue.

**Comment by casualjim** [comment]
reopened so people can find it easily

**Comment by polds** [comment]
Can the same pattern of using an `http.RoundTripper` be used to implement the AWS Signature v4 which requires reading and modifying the `*http.Request` before its sent?

**Comment by casualjim** [comment]
yes it can, the roundtripper is the last thing executed before sending the request on the wire

**Comment by polds** [comment]
Indeed it can, thank you.

**Comment by Sef1995** [comment]
Is it possible to do this without a http.RoundTripper? I'm using gock for mocking the request in a test. But the test won't work because the roundtripper var is already set. See; https://github.com/h2non/gock/issues/27

**Comment by sachnk** [comment]
@Sef1995 Did you ever get [gock](https://github.com/h2non/gock) working with go-swagger? I'm running into the same issue -- I can't figure out how to get gock to intercept my traffic that originates from my client generated code.

**Comment by fredbi** [comment]
@sachnk we don't follow up closed issues. If the above answers do not address your expectations, I'd suggest you create a new issue in which you describe your use case in details. Thanks.
