### ISSUE TITLE
Can't specify a custom producer or consumer

### ISSUE THREAD

**Issue by thommahoney** [go-swagger/go-swagger#912]
## Problem statement

I see this line of code in the runtime https://github.com/go-openapi/runtime/blob/4affd1e7cac55dd6f127f97efa114d2e02cddb55/client/runtime.go#L136 which indicates that the producers and consumers should be inferred from the specification. Is this work planned? If not, is it possible to register our own producers and consumers? We're using [json:api](http://jsonapi.org/) which requires a specific `Accept` and `Content-Type` header.

## Swagger specification

```
  /resources:
    get:
      description: |
        Returns a list of resources in JSON-API format
      consumes:
        - application/vnd.api+json
      produces:
        - application/vnd.api+json
      parameters:
        - name: filter[attribute]
          in: query
          description: Optional parameter for filtering by attribute
          required: false
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/ResourceCollection'
```

**Comment by casualjim** [comment]
you can set your own producers and consumers.
The ones you've got in your example will do the right thing, the code generator knows about that naming pattern for json

**Comment by thommahoney** [comment]
@casualjim I'm getting `panic: no consumer: "application/vnd.api+json"` using the spec above.

**Comment by GlenDC** [comment]
@thommahoney, ustom Consumers/Producers for the client an be set as follows:

```go
import (
    // ...
    httptransport "github.com/go-openapi/runtime/client"
    strfmt "github.com/go-openapi/strfmt"
    myclient "github.com/username/repo/api/client" // your generated client package
    // ...
)

// ...

rt := httptransport.New(DefaultHost, myBasePath, mySchemes)
rt.Consumers["application/vnd.api+json"] = httptransport.JSONConsumer()
rt.Producers["application/vnd.api+json"] = httptransport.JSONProducer()

// Create Client using the function below
// instead of myclient.NewHTTPClient / myclient.NewHTTPClientWithConfig
myclient.New(rt, strfmt.Default)

// ...
```

**Comment by GlenDC** [comment]
Relevant runtime issues:

+ https://github.com/go-openapi/runtime/issues/33
+ https://github.com/go-openapi/runtime/issues/32

**Comment by thommahoney** [comment]
Thank you both for your help on this. 👍

**Comment by GlenDC** [comment]
@thommahoney, is your service now working as expected?

**Comment by thommahoney** [comment]
Yes, you can close this issue.

**Comment by ZandorZ** [comment]
@GlenDC  I had the same problem and Instead of httptransport.JSONConsumer()
i had to change to:

runtime.JSONConsumer()

from import "github.com/go-openapi/runtime"

**Comment by GlenDC** [comment]
Yes @ZandorZ, you are correct. My original comment was wrong :) Same goes for any of the producers/consumers you might wish to use from the runtime (root) package.
