### ISSUE TITLE
Similar routing paths that differ at the leaf got dropped out 

### ISSUE THREAD

**Issue by candysmurf** [go-swagger/go-swagger#918]
## Problem statement

In the code base, when annotated with: 

         swagger:route GET /plugins/{ptype}/{pname}/{pversion} getPlugin

it generated with "path" inside swagger.json. While we have a similar route as:
     
        swagger:route GET /plugins/{ptype}/{pname}/{pversion}/config getPluginConfig

The annotation didn't get pick up into the swagger.json

## Environment
swagger version: dev
go version: go1.7 
OS:   darwin/amd64

**Comment by casualjim** [comment]
is the code for this available?

**Comment by candysmurf** [comment]
@casualjim, yes. What I found is that it works in other cases. Only one particular case does not work which has the route as /plugins/{ptype}/{pname}/{pversion}/config for GET, PUT and DELETE. They're totally missing. This set of response has custom Marshal/Unmarshal. Could this be the issue?

**Comment by casualjim** [comment]
I'm not sure without being able to look at the code with the annotations :(
It can be as simple as a spelling mistake on the parameters or it can be a bug with the path detection.
Is running it with DEBUG=1 SWAGGER_DEBUG=1 helpful at all?

**Comment by candysmurf** [comment]
Thanks, @casualjim. 

Here is the link to the annotation:  https://gist.github.com/candysmurf/43cd4a179a8af12b95696e352091a19e

Here is the gist for swagger.json
https://gist.github.com/candysmurf/8294d9dd7afa348f6f568b3e9582c8c5

Thank you!

**Comment by candysmurf** [comment]
@casualjim, apparently fields in the config type was not exported. After I had exported those fields, it worked as expected. Thanks for your help. I'm going to close this issue.
