### ISSUE TITLE
How to change casing of generated models to camelCase?

### ISSUE THREAD

**Issue by mpalomas** [go-swagger/go-swagger#920]
Hi,

This is a more a question than a issue but I can't find how to tag it as such... I could not find anything in the existing FAQ, but I may have overlooked it:

Basically, I want to use camelCase instead of PascalCase in the generated models. I'm talking about the properties, not the model file name. 

I've tried to use custom templates and --template-dir but I'm still a bit confused: which template file from the go-swagger/generator-templates I am supposed to copy and edit to achieve my goal? So far I don't see any change so I guess model.gotmpl is not the right none...

Thanks!

**Comment by mpalomas** [comment]
I've just realised I should add one thing:
I am aware we need PascalCase because obviously the properties need to be public/exported.
But, is there a way to tell the json serializer to be smart enough to accept and output camelCase?

**Comment by GlenDC** [comment]
@mpalomas can you share your `swagger.{json,yaml,yml}` file? Basically if you specify your properties as _camelCase` in your specification file, than your JSON annotations so be generated as camelCase as well. Is that not happening in your case?

**Comment by mpalomas** [comment]
Well, that seems to work indeed. I was pretty much sure I tried this already as it's so obvious... I guess I either did not regenerate or made a mistake.
Sorry for the noise!

**Comment by GlenDC** [comment]
No problems, questions are always welcome, better then to be confused/frustrated :)
