### ISSUE TITLE
go-swagger generating apparently invalid .json file

### ISSUE THREAD

**Issue by flimzy** [go-swagger/go-swagger#922]
## Problem statement

When I view the API spec using `swagger serve`, I receive the following warning for several definitions:

> **Warning:** Other properties are defined at the same level as $ref at "#/definitions/TicketListItemJSON/properties/assignedTo". They are IGNORED according to the JsonSchema spec

## Steps to reproduce

I have created a minimal test case:

Create this file `foo.go` in an empty directory:

    package foo

    // Response is a response for foo
    // swagger:response FooResponse
    type Response struct {
    	Tickets Tickets `json:"tickets"`
    }

    type Tickets []*Ticket

    type Ticket struct {
    	// The assignee
    	AssignedTo *Foo `json:"assignedTo"`
    }

    type Foo struct{}

Then run:

    swagger generate spec -o swagger.json

Then observe the resulting file and notice the section:

        "assignedTo": {
          "description": "The assignee",
          "x-go-name": "AssignedTo",
          "$ref": "#/definitions/Foo"
        }

## Environment

    $ swagger version
    dev
    $ go version
    go version go1.7.4 linux/amd64

**Comment by gaplyk** [comment]
@flimzy this is only the part of json file. Could you provide this source code and generated schema somewhere on github? I had similar problem before, afair.

**Comment by flimzy** [comment]
@gaplyk https://github.com/flimzy/swagger-test

**Comment by gaplyk** [comment]
current schema is valid so it is not spec generator issue.

**Comment by flimzy** [comment]
So it's a problem with the serve command I guess?

**Comment by kinukawa** [comment]
@flimzy 
I also encountered the same problem and resolved.

JSON reference said 
> Any members other than "$ref" in a JSON Reference object SHALL be ignored.
https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3

`json:"assignedTo"` tag attache "x-go-name" property.
so you should remove `json:"assignedTo"` and annotate to the definition of AssignedTo.

**Comment by kinukawa** [comment]
@flimzy 
I also encountered the same problem.

JSON reference said 
> Any members other than "$ref" in a JSON Reference object SHALL be ignored.
https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3

`json:"assignedTo"` tag attache "x-go-name" property.
But I want to use the json tag, so this problem is not solved.
Ignoring warnings.

**Comment by casualjim** [comment]
the values other than $ref don't matter, it doesn't affect validity of the spec it just means other fields than $ref are ignored.

**Comment by flimzy** [comment]
> the values other than $ref don't matter, it doesn't affect validity of the spec it just means other fields than $ref are ignored.

But they aren't ignored. That's the whole problem. They cause ugly warnings when running 'swagger serve'.

**Comment by casualjim** [comment]
I suppose we can fix issues like this by adding  a post processing of the spec to clear warnings. Perhaps here? https://github.com/go-swagger/go-swagger/blob/master/scan/scanner.go#L324

**Comment by andreigornostajev** [comment]
Just updated go-swagger and found that you have removed `x-go-name` properties from ref types. This as very sad as we had a custom implementation based on these fields (ordering of properties in definitions to be the same as in go models).

Is it possible to restore them back and fix `serve` command instead as I understand the issue actually was with `serve` command?
