### ISSUE TITLE
How do you remove a not required date-time from your JSON output?

### ISSUE THREAD

**Issue by rhardey** [go-swagger/go-swagger#927]
In my go-swagger built API I have a date-time property that is not required, i.e. I would like to exclude it from the JSON output if the source DB value is NULL.  I successfully select the value into a sql.NullString value (endTime) then convert to a strfmt.DateTime (endTimeStr) to populate the model:

    endTimeStr := strfmt.DateTime{}
    (&endTimeStr).Scan(endTime.String)

When the value in the database is NULL then instead of this value being suppressed in the JSON output I see the following:

    "end_time": "0001-01-01T00:00:00.000Z",

The above value means nothing in my context so I would rather see it suppressed.  Am I able to do this?

Note non-required values of other data types are not placed in the JSON, do I have to do anything extra in the case of date-time values to hide these too?

Thanks for any help you can provide.

**Comment by casualjim** [comment]
you can annotate your date property with `x-nullable: true` that gives you a pointer value for the strfmt.DateTime property and allows you to retain the NULL

**Comment by rhardey** [comment]
Thank you casualjim, that is what I was looking for.
