### ISSUE TITLE
Path parameters not unescaped correctly

### ISSUE THREAD

**Issue by kPshi** [go-swagger/go-swagger#928]
## Problem statement

We have a Swagger Spec with a string parameter defined. When now the value contains some URL escaped characters (e.g. a space, correctly encoded as + or %20 by the client), these are not unescaped before being passed into the actual service implementation.
We now implemented a workaround but I'm quite sure this is a bug.

## Swagger specification
```json
{
   "/v1/choices/{type}/{value}" : {
      "get" : {
         "produces" : [
            "application/json"
         ],
         "responses" : {
            "200" : {
               "description" : "Choice details.\n",
               "schema" : {
                  "$ref" : "#/definitions/choice"
               }
            }
         },
         "parameters" : [
            {
               "in" : "path",
               "required" : true,
               "type" : "string",
               "name" : "type"
            },
            {
               "name" : "value",
               "type" : "string",
               "in" : "path",
               "required" : true
            }
         ],
         "description" : "Details about one choice by its value."
      }
   }
}
```

## Steps to reproduce

For this example:
    curl 'http://127.0.0.1:8889/v1/choices/os/Ubuntu%2014.04'
will end up in some value "Ubuntu%2014.04"
while
    curl 'http://127.0.0.1:8889/v1/choices/os/Ubuntu 14.04'
becomes "Ubuntu14.04" (with no space at all)

## Environment
swagger version: dev (as of 2017-02-10)
go version: 1.6.2
OS:   Ubuntu 14.04

**Comment by casualjim** [comment]
fixed by go-openapi/runtime@76cda4f

**Comment by kPshi** [comment]
One additional special case which I'm not even very sure about whether it's an error in go-swagger or not:

For the case above a client sends a plus sign which is really meant to be a plus sign. It's not escaped as %2b and the customer claimed this would be correct. We discussed that for a while and indeed: RFC2616 says "" and does not say anything about an encoding a space as +, but for body content of application/x-www-urlencoded the + is an alternative for %20 ([https://tools.ietf.org/html/draft-hoehrmann-urlencoded-01](url)): "For compatibility with the RFC 1866 format the ampersand character is tolerated as alternative separator character, and the plus sign may be used to represent space characters."

So from my point of view a + in a path variable would have to stay +, only %20 should be unescaped while for form data a + would have to be encoded as %2b on client side while the server may decode + to space.

Sorry for nitpicking and discussing here. The potential problem I see is that it seems like several libraries do not encode correctly so implementing it to the letter of the spec could mean to cause problems with those in reality. On the other hand when the encoding bug has just recently been reported and fixed there seem not to be too many implementations even using it.

**Comment by kPshi** [comment]
Should work like so:
```diff
diff --git a/middleware/router.go b/middleware/router.go
index 84b26f8..9cd4e04 100644
--- a/middleware/router.go
+++ b/middleware/router.go
@@ -184,7 +184,8 @@ func (d *defaultRouter) Lookup(method, path string) (*MatchedRoute, bool) {
                                debugLog("found a route for %s %s with %d parameters", method, path, len(entry.Parameters))
                                var params RouteParams
                                for _, p := range rp {
-                                       v, err := url.QueryUnescape(p.Value)
+                                       // according to RFC2616 a + (plus) in a path is just a +
+                                       v, err := url.QueryUnescape(strings.Replace(p.Value, "+", "%2B", -1))
                                        if err != nil {
                                                debugLog("failed to escape %q: %v", p.Value, err)
                                                v = p.Value
diff --git a/middleware/router_test.go b/middleware/router_test.go
index e64fe35..ab61b67 100644
--- a/middleware/router_test.go
+++ b/middleware/router_test.go
@@ -163,14 +163,14 @@ func TestRouter_EscapedPath(t *testing.T) {
        assert.Equal(t, 200, recorder.Code)
 
        recorder = httptest.NewRecorder()
-       request, _ = http.NewRequest("GET", "/api/pets/abc%2Fdef", nil)
+       request, _ = http.NewRequest("GET", "/api/pets/abc%2Fde+f", nil)
 
        mw.ServeHTTP(recorder, request)
        assert.Equal(t, 200, recorder.Code)
        ri, _ := context.RouteInfo(request)
        if assert.NotNil(t, ri) {
                if assert.NotNil(t, ri.Params) {
-                       assert.Equal(t, "abc/def", ri.Params.Get("id"))
+                       assert.Equal(t, "abc/de+f", ri.Params.Get("id"))
                }
        }
 }
```
