### ISSUE TITLE
Beam file not being generated.

### ISSUE THREAD

**Issue by k-sathireddy** [go-swagger/go-swagger#930]
I want to implement push notifications with ejabberd server. I followed instructions as mentioned here:

but i got the following issues:

Recompile: src/mod_onesignal
src/mod_onesignal.erl: undefined parse transform 'lager_transform'

Please answer it as soon as possible.

**Comment by casualjim** [comment]
I think you made this issue on the wrong repo. This repo is about creating go code fro swagger specifications. Your issue seems to be with erlang compilation.

**Comment by k-sathireddy** [comment]
@casualjim Thank you so much. By mistake i posted here.
