### ISSUE TITLE
Request response can have different objects returned based on query parameters

### ISSUE THREAD

**Issue by Sakibs** [go-swagger/go-swagger#932]
## Problem statement

I have a POST request that returns different object models based on the query parameters.
Is there any way to add multiple responses under the swagger route annotation like

```
Responses:
  200: response1
  200: response2
... etc

```

Also is it possible to have different models for the request too?

**Comment by casualjim** [comment]
this is not supported in openapi 2.0 specification

**Comment by karux** [comment]
sakibs,   if you specify a wrapper class or base class, you can return multiple responses. for example (in pseudo-swagger),

ResponseWrapper
type: object
properties:
   response1: $ref: '#/definitions/response1'
   response2: $ref: '#/definitions/response2'

or more elegantly
BaseObject:
type: object
properties:
    id: type: string   format: uuid

Response1:
  allOf:
     - $ref: '#/definitions/BaseObject'
     - type: object
        properties:
             extendedAttributeForResponse1

Response2:
  allOf:
     - $ref: '#/definitions/BaseObject'
     - type: object
        properties:
             extendedAttribForResponse2

**Comment by gregmarr** [comment]
I would assume that with OpenAPI 3.0 you'll be able to do `anyOf:` with the different response types.

**Comment by casualjim** [comment]
In swagger 2.0 there is no support for this, however you can still achieve this by putting the query params that dictate the models in the path.

```yaml
paths:
  "/something?objectType=thisThing":
    get: 
      ...
  "/something?objectType=otherThing":
    get:
      ...
````

**Comment by fredbi** [comment]
This thread has been archived in our [FAQ](http://goswagger.io/faq/). You may access it directly [here](http://goswagger.io/faq/faq_model.html#request-response-can-have-different-objects-returned-based-on-query-parameters)

(with PR #1342)

**Comment by Marcosaurios** [comment]
As new OpenAPI 3.0 specification is supporting, together with Swagger UI 3.23.0, multiple response examples should be accepted as correct, right? As states  [swagger-ui issue 2651](https://github.com/swagger-api/swagger-ui/issues/2651#issuecomment-493245789) and support in [swagger-ui v3.23](https://github.com/swagger-api/swagger-ui/issues/2651#issuecomment-506982837)
<details>
<summary>
Open referred picture 
</summary>

![57889415-fe5f6880-77f1-11e9-95d4-bb52f8391146](https://user-images.githubusercontent.com/24393669/110107805-abcab400-7dab-11eb-9a93-c91997bc1466.png)

</details>


Should we consider reopening the issue? Thanks!
