### ISSUE TITLE
goswagger.io link to "source for this tutorial" is broken

### ISSUE THREAD

**Issue by grogsaxle** [go-swagger/go-swagger#934]
## Problem statement
The tutorial for Simple Server on goswagger.io is broken.  It should probably point to https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go

**Comment by GlenDC** [comment]
Already fixed by @nathany in https://github.com/go-swagger/go-swagger/pull/857. Once there is a new Release for Go-Swagger, the documentation on the website will be updated accordingly.

**Comment by grogsaxle** [comment]
@GlenDC, Thanks!
