### ISSUE TITLE
Set HTTP header on the client side without an explicit swagger parameters

### ISSUE THREAD

**Issue by frosenberg** [go-swagger/go-swagger#935]
## Problem statement

We have a need to set HTTP header parameters in the (generated) client code that are not necessarily part of the swagger documentation.  We know that we could specify the header parameter in swagger but that is not feasible as it should not be exposed to the public users (it will be set automatically by the gateway but for internal development we also want to set it).

However, I don't really have access to the http request from any of the `Params` object. Unless I'm missing something, I would have to make a copy of the swagger doc with the parameter that I then use for client code generation and one for external use without the parameter.

Is there a better way to solve this by letting met set custom headers that are not specified in the swagger document? Alternative would be hidden parameters in the swagger doc but I don't think that exists.

**Comment by casualjim** [comment]
You can use a roundtripper for this purpose, see here: https://github.com/go-swagger/go-swagger/issues/911

**Comment by frosenberg** [comment]
Awesome, i'll look into this. Always appreciate you fast response :).

**Comment by frosenberg** [comment]
This resolved my problem and this issue can be closed.
