### ISSUE TITLE
swagger:meta custom description

### ISSUE THREAD

**Issue by lucval** [go-swagger/go-swagger#937]
Hi,

I have the following swagger:meta defined in a doc.go file within a public package:

> // Package public ESB monitoring endpoints.
> //
> // The purpose of this API is to provide information over the status of
> // components (API clients) and services (among others SIM, porting, compass
> // provisioning) running in the Speakup ESB
> //
> //     Schemes: http, https
> //     Version: 0.0.1
> //     Contact: Luca Valtulina<luca@speakup.nl>
> //
> // swagger:meta
> package public

when generating the swagger documentation though, it randomly happens that the swagger info attribute is as following:

> "info": {
>    "description": "You give it a main file and it will parse all the files that are required by that main\npackage to produce a swagger specification.\n\nTo use you can add a go:generate comment to your main file for example:\n\ngo:generate swagger generate spec\n\nThe following annotations exist:",
>     "title": "provides a scanner for go files that produces a swagger spec document.",
>     "contact": {
>       "name": "Luca Valtulina",
>       "email": "luca@speakup.nl"
>     },
>     "version": "0.0.1"
>   },

This description and title can be found in the go-swagger/go-swagger/scan/doc.go file. I believe that this is triggered by the fact that I import "github.com/go-swagger/go-swagger/cmd/swagger/commands/generate" in my project (I need to generate the swagger documentation at runtime and I do that by instantiating a generate.SpecFile with as basePath the path to my public package and as input the doc.go file).

If you think that this cannot be considered an issue, since go-swagger is meant to be executed separately and not to be imported as a library package than please feel free to close this.

Thanks in advance,
Luca

**Comment by casualjim** [comment]
you need to generate the spec at build time (the code is not likely to change at runtime is it?)
You can then use a tool like go-bindata to embed the generated spec in your binary too
And you can then use the go-openapi/loads or go-openapi/spec packages to load or serve that file.

**Comment by lucval** [comment]
@casualjim thanks for your reply.

if with "at build time" you mean prior to building the golang binary (sorry newbie here) using the 'swagger generate spec' cmd then the result is unfortunately not different (4 out of 10 times the description and title in the swagger doc are incorrect).

**Comment by casualjim** [comment]
you should not have go-swagger/go-swagger in your vendor or use types out of go-swagger/go-swagger
It's not meant to be embedded

**Comment by gregmarr** [comment]
FYI, we have `go-swagger` in our vendor directory so that we can ensure a given version, even if that version isn't yet released, but we don't use any of its types from there.  We just run it from the vendor directory.  We haven't had any problems with that, so it would be good if it would continue to work that way.

**Comment by casualjim** [comment]
yes the problem is occurs when you start importing types out of go-swagger/go-swagger. You can have it in your vendor.
The only reason swagger generate spec would discover descriptions in other types is if they are detected to be used from a codepath that starts at your main file.

**Comment by lucval** [comment]
Thanks @casualjim for the clarifications. I think we can considered this issue a non-issue then but simply a misuse from my side.
