### ISSUE TITLE
Not able to generate proper swagger spec

### ISSUE THREAD

**Issue by Krashcan** [go-swagger/go-swagger#938]
## Problem statement

I am trying to generate swagger spec for https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing/petstore . But the resulting swagger spec doesn't contain all the routes,models etc. Infact it only contains the data provided in doc.go .

## Swagger specification

    {
      "consumes": [
        "application/json"
      ],
      "produces": [
        "application/json"
      ],
      "schemes": [
        "http",
        "https"
      ],
      "swagger": "2.0",
      "info": {
        "description": "the purpose of this application is to provide an application\nthat is using plain go code to define an API\n\nThis should demonstrate all the possible comment annotations\nthat are available to turn go code into a fully compliant swagger 2.0 spec",
        "title": "Petstore API.",
        "termsOfService": "there are no TOS at this moment, use at your own risk we take no responsibility\ngo:generate swagger generate spec -o swagger.json",
        "contact": {
          "name": "John Doe",
          "url": "http://john.doe.com",
          "email": "john.doe@example.com"
        },
        "license": {
          "name": "MIT",
          "url": "http://opensource.org/licenses/MIT"
        },
        "version": "0.0.1"
      },
      "host": "localhost",
      "basePath": "/v2",
      "paths": {}
    }

## Steps to reproduce

I added `//go:generate swagger generate spec -o swagger.json
` in doc.go and did `go generate` in the folder containing doc.go

## Environment
swagger version:   dev
go version: 1.6.2  
OS:   Windows 10

**Comment by casualjim** [comment]
you need to start from your main because that's where it starts reflecting over your packages.
it works its way back from main to discover all the packages that are in use by your program, like the go compiler does.
Alternatively you can import all the packages you need with in your doc.go so the tool knows what to look at.
```go
import (
  _ "package/with/routes"
  _ "package/with/more/routes"
)
```

**Comment by Krashcan** [comment]
Thank you, it works that way.
