### ISSUE TITLE
Error "target must reside inside a location in the $GOPATH/src", target is in $GOPATH/src (Windows)

### ISSUE THREAD

**Issue by RobertPepkaSEL** [go-swagger/go-swagger#940]
## Problem statement

go-swagger can misidentify the $GOPATH/src folder in Windows. This manifests in a confusing `target must reside inside a location in the $GOPATH/src` error even though the path IS in $GOPATH/src.

It came up for me doing a 'generate server' command.

`filepath.Abs` (at least, on this version of Windows) returns capital letters for path, for example: `C:\dev\src\myproject`. However, the environmental variable GOPATH comes from user input. It may be an upper or lower case letter, eg:  `GOPATH = c:\dev`. This causes go-swagger, in  `generator/support.go`, in `func baseImport`, line 157 `if strings.HasPrefix(p, pp) {` to fail this check, even though on windows these two strings are the same location.

## Steps to reproduce

1. Set gopath to `c:\dev`
2. Create a project in c:\dev\src called 'myproject'
3. Use any swagger file.
4. Install as a vendor library (e.g., with glide)
5. Run with a relative path. "go run go run .\vendor\github.com\go-swagger\go-swagger\cmd\swagger\swagger.go generate server"

## Environment
swagger version: 0.8.0  
go version: go1.7.4 windows/amd64
OS:   Windows 10 Enterprise 64-bit, Intel Xeon E31245

## Workaround

Swap the GOPATH to an upper case drive letter in your environment variables. :-)

**Comment by casualjim** [comment]
I think this is fixed on master:

https://github.com/go-swagger/go-swagger/pull/821/

**Comment by RobertPepkaSEL** [comment]
Great to hear! Hopefully this issue can be a target for folks searching for the problem.
