### ISSUE TITLE
Generated import path ignores capitalization

### ISSUE THREAD

**Issue by ntoljic** [go-swagger/go-swagger#941]
## Problem statement & Steps to reproduce

When generating a server with `swagger generate server -f swagger.json` within a directory in `$GOPATH`, the import paths in the generated files are all lower case even though the path contains a directory with capitalized letters (e.g. /go/src/github.com/FOO/bar).

Is this something go recommend/enforces and therefore desired behavior?

## Environment
swagger-codegen: stable 2.2.1
swagger version: 0.8.0  
go version: 1.8

**Comment by casualjim** [comment]
we use goimports for finding imports and optimizing imports,
https://godoc.org/golang.org/x/tools/cmd/goimports

**Comment by ntoljic** [comment]
Ok, I might raise it with them if I get around to it. In the meantime I simply renamed our organization name (well, the URL) and the directory in the `$GOPATH`.
