### ISSUE TITLE
Unable to respond with file and application/octet-stream producer

### ISSUE THREAD

**Issue by robbert229** [go-swagger/go-swagger#943]
## Problem statement
I have an endpoint that returns a file and should be using the "application/octet-stream" producer. The specification is valid according to go-swagger, and the generated code compile fine. When I attempt to use the endpoint it panics `ByteStreamProducer can only deal with io.Reader`.

There is a high probability that this is due to human error ( on my part ), but this issue might help others encountering the same issue that I am later on.

EDIT: After some digging I have discovered that `runtime.File` doesn't implement `io.Reader`, which `ByteStreamProducer` requires.

## Swagger specification
https://github.com/robbert229/swagger-download-file-bug/blob/master/swagger.yaml

## Steps to reproduce
1. clone the repository && run the application
3. open up swagger ui and load the locally hosted spec.
4. upload a file ( via POST /file )
5. attempt to download said file ( via GET /file )

https://github.com/robbert229/swagger-download-file-bug

## Environment
swagger version: Master
go version: go1.7.5 linux/amd64
OS:   linux ( archlinux )

**Comment by robbert229** [comment]
Making `runtime.File` implement `io.Reader` with the following implementation solves my issue.

```
// in github.com/go-openapi/runtime/interfaces.go

// File represents an uploaded file.
type File struct {
	Data   multipart.File
	Header *multipart.FileHeader
}

// my addition
func (f File) Read(p []byte) (n int, err error) {
	return f.Data.Read(p)
}
```

**Comment by casualjim** [comment]
both those orgs are owned by me, feel free to submit a pr to runtime :) This is a great addition!

**Comment by robbert229** [comment]
Planning on it!

**Comment by casualjim** [comment]
resolved by @robbert229
