### ISSUE TITLE
Swagger Contract Model fields displaying as requestModel.<fields>

### ISSUE THREAD

**Issue by GaneshMeenakshisundaram** [go-swagger/go-swagger#944]
## Problem statement
Upon integrating Web API with Swagger (on Owin), the Model fields are displayed as requestModel.<fieldname>

Please remove the sections that don't apply

## Swagger specification
Swashbuckle.Core

## Environment
swagger version: v4.0.30319
![swagger contract model issues](https://cloud.githubusercontent.com/assets/14163306/23232135/35f20664-f918-11e6-80c9-e808be1475c1.jpg)

OS:   Windows 7 Enterprise

**Comment by robbert229** [comment]
This is *go-swagger*, I think you are looking for -> https://github.com/domaindrivendev/Swashbuckle

*go-swagger* is tooling for using swagger with *golang*.
