### ISSUE TITLE
Upgrade mailru/easy json to latest version, for Google App Engine

### ISSUE THREAD

**Issue by mpalomas** [go-swagger/go-swagger#947]
Hello,

So far mailru/easyjson could not be used on Google App Engine due to the usage of unsafe package. Good news is that they have introduced build flags to workaround this issue:

https://github.com/mailru/easyjson/issues/34

Would you consider upgrading to latest version of easyjson? So that go-swagger itself becomes fully compatible with App Engine?

Actually to be honest, it seems App Engine does not play nice with vendoring and just ignores any vendor folder, and go get latest of each dependency instead (known issue). Therefore upgrading your vendor folder may not be necessary

**Comment by casualjim** [comment]
The good news is that you don't have to wait until I upgrade. The mailru in this repo is for the CLI but you are free to upgrade the one in your vendor.
I'll try to upgrade this week though

**Comment by casualjim** [comment]
i upgraded a while ago
