### ISSUE TITLE
swagger GSMA

### ISSUE THREAD

**Issue by jerome-laforge** [go-swagger/go-swagger#951]
## Problem statement
```
base_quotation.go:137: no new variables on left side of :=
base_reversal.go:141: no new variables on left side of :=
base_transaction.go:183: no new variables on left side of :=
batch_completion.go:103: no new variables on left side of :=
batch_rejection.go:101: no new variables on left side of :=
request_quotation.go:20: undefined: swag in swag.ReadJSON
request_quotation.go:32: undefined: swag in swag.WriteJSON
request_quotation.go:38: undefined: swag in swag.ConcatJSON
request_quotation.go:50: undefined: errors
statement_entry.go:141: no new variables on left side of :=
request_quotation.go:50: too many errors
```

## Swagger specification
https://mmapi.gsma.com/swagger/swagger.json

## Steps to reproduce
```
wget https://mmapi.gsma.com/swagger/swagger.json
swagger generate model -f swagger.json

go install
```
## Environment
swagger version: commit 43b65696977223b6c112fe99050b13c30485959b
go version: 1.8.0
OS:   linux

**Comment by fredbi** [comment]
Todo: 
- [ ] Reproduce
- [ ] Add gsma spec to known fixtures

**Comment by fredbi** [comment]
gsma spec compiles well now.

**Comment by fredbi** [comment]
The validation does not pass (essentially, duplicate properties found in allOf), but the generated code compiles:
swagger generate server --skip-validation --spec=swagger-gsma.json --target=tmp --name=codegensrv --output=swagger-gsma.log
