### ISSUE TITLE
Read request body in middleware.

### ISSUE THREAD

**Issue by mikeb333** [go-swagger/go-swagger#955]
Is it possible to read the request body in either the setupMiddleware or setupGlobalMiddleware functions? 

We are trying to validate that a request body contains correct info and we wanted to check it in the middleware.  When we stick the following into the handler function of either setup middleware functions we always get an empty body. The body is always empty even though the POST request does have a body.

```
var val []byte
i, err := r.Body.Read(val)
r.Body.Close()
if err != nil{
	log.Print(err)
} else {
	log.Println(i)
	log.Println(string(val))
}
```

**Comment by casualjim** [comment]
I assume this is for validations that fall outside of what swagger can do for you, and prior to databinding the body property?  

If you want to read the body more than once you have to put it back as an io.ReadCloser so you can read it in a []byte and then replace r.Body with a bytes.NewBuffer(theBytes)
These readers are single use only

**Comment by mikeb333** [comment]
Thanks for the info. We were able to get this working.
