### ISSUE TITLE
Client Generator hangs on swagger with circular dependencies.

### ISSUE THREAD

**Issue by dimitertodorov** [go-swagger/go-swagger#957]
Please see my swagger Here:
https://gist.github.com/dimitertodorov/c4b5e4e7020c97f8ab34e2460403688e
Trying to create client with:
```
swagger generate client -f sw.json -A nmdb_client
```
**Issue**
Circular dependencies seem to be freezing swagger
The JSON passes validation against 2.0 schema.
This problem also occurs with swagger-ui.

If I remove the circular dependencies, it loads fine.
## Environment
swagger version: 2.0
go version: 1.8 
OS:   OSX

**Comment by casualjim** [comment]
the spec generates fine for me when I skip validation

```
swagger generate client -A Nmdb --skip-validation -f sw.json
```
Any tool I've tried has issues validating the spec in your example.
Would it be possible to get a smaller repro of the circular dependency, the spec in your example is large and complex

**Comment by fredbi** [comment]
Tested again this one with current master and also with master spec package (with circular ref fixes).
Still hanging.
Generate server hangs as well.

I am giving up on that one since the spec is too large to figure out what is wrong.

**Comment by fredbi** [comment]
Working on a fix in spec
