### ISSUE TITLE
generated models omit values which logically shouldn't be

### ISSUE THREAD

**Issue by JohnRowleySEL** [go-swagger/go-swagger#959]
( Previously I have filed issues under @robbert229 but work policy for open source contributions is finally starting to take shape so I now am required to use a corporate account. )
## Problem statement
When a `definition` has a property N, if N is a number, and is not required its' generated model has the structflag `omitempty` for N. This means that when N has been set to 0 the generated JSON omits N, despite it being validly set to 0. I would still like to allow this variable to be unset, by setting it to null for example. This will also apply for returning objects that return false and so on.

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an  empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or  string.

From - https://golang.org/pkg/encoding/json/#Marshal

A workaround for this is to use `x-nullable` on my properties, but I feel like this shouldn't be required to be able to send a property whose value happens to be the default value for that type. I also understand why this is done, and it does make sense. 

## Swagger specification
https://github.com/JohnRowleySEL/go-swagger-number-ommited-bug/blob/master/swagger.yaml
## Steps to reproduce
1. Generate server with spec -> https://github.com/JohnRowleySEL/go-swagger-number-ommited-bug/blob/master/swagger.yaml
2. Attempt to send error with a code of 0

The error is ommited from the response because of `omitempty` as a struct tag https://github.com/JohnRowleySEL/go-swagger-number-ommited-bug/blob/master/models/error.go#L17

## Environment
swagger version: tip
go version: 1.8 linux/amd64
OS:

**Comment by casualjim** [comment]
I think you can use `x-nullable: true` for this use case

**Comment by JohnRowleySEL** [comment]
That is what I am currently doing, but for those new to go-swagger it is not apparant that there are edge cases where your model won't properly serialize if you don't use `x-nullable` to annotate parameters.

( this issue is partially filed so that people running into the issue where your model isn't showing up correctly on the client can find somthing useful )
