### ISSUE TITLE
migrate to use net.Context

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#96]
Currently this uses gorilla's context to provide storage for request specific information.
Explore using net.Context and a deadline for this instead.

**Comment by dolmen** [comment]
What is this `net` package you are refering to?
I see no `Context` in [stdlib `net`](https://golang.org/pkg/net/)...

**Comment by casualjim** [comment]
it's this package: https://godoc.org/golang.org/x/net/context

**Comment by fredbi** [comment]
@casualjim I believe this one has been closed long ago, isn't it? (just regular housekeeping on older issues)
