### ISSUE TITLE
Maps as swagger:parameters

### ISSUE THREAD

**Issue by ren90** [go-swagger/go-swagger#960]
Hi, 

I'm using go-swagger to generate my Swagger docs from code, and I came across a problem with a given parameter.
When I annotate a given struct that has a map[KeyType]OtherKeyType with `swagger:parameters`, it returns `items doesn't support maps`. I can tell the current version may not support `map`s  in the parameter delcaration, but I'm writing to (i) know if this feature may be inline for release (ii) know if there is any workaround for declaring `map`s in parameter structs.
 
Thanks in advance and congrats for the great work,
Renato Vieira

go-swagger version: 0.8.0  
go version:1.7.4  
OS: Ubuntu 16.04

**Comment by gaplyk** [comment]
Can you provide examples

**Comment by casualjim** [comment]
in non-body parameters maps are not supported in the swagger spec.
In the body json schema only allows maps with string keys
