### ISSUE TITLE
todo-list client throws "runtime error: invalid memory address"

### ISSUE THREAD

**Issue by gothenti** [go-swagger/go-swagger#968]
## Problem statement
When I'm trying to add a new item with the todo-list client from the examples section go breaks up:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x129d927]

goroutine 1 [running]:
github.com/go-openapi/runtime/client.(*request).BuildHTTP(0xc420019500, 0x1395e99, 0x31, 0xc4201dc4e0, 0x0, 0x0, 0x0, 0x0, 0x110)
        /Users/***/go/src/github.com/go-openapi/runtime/client/request.go:187 +0x857
github.com/go-openapi/runtime/client.(*Runtime).Submit(0xc4203924e0, 0xc4200fc000, 0x0, 0x0, 0x0, 0x0)
        /Users/***/go/src/github.com/go-openapi/runtime/client/runtime.go:241 +0x458
example.com/swagger2/client/todos.(*Client).AddOne(0xc4204d5f60, 0xc4201dc510, 0x0, 0x0, 0x0)
        /Users/***/go/src/example.com/swagger2/client/todos/todos_client.go:45 +0x2fa
main.main()
        /Users/***/go/src/example.com/swaggercimpl/client.go:34 +0x1f3

## Swagger specification
https://raw.githubusercontent.com/go-swagger/go-swagger/master/examples/todo-list/swagger.yml

## Steps to reproduce
```
func main() {
	// create the transport
	transport := httptransport.New("127.0.0.1", "", nil)

	// create the API client, with the transport
	client := apiclient.New(transport, strfmt.Default)

	description := "TEST"
	var item *models.Item
	item = new(models.Item)
	item.Description = &description

	params := todos.NewAddOneParams()

	params.Body = item

	// make the request to get all items
	resp, err := client.Todos.AddOne(params)
	if err != nil {
		log.Fatal(err)
	}
}
```
## Environment
swagger version: dev/master
go version: go version go1.8 darwin/amd64
OS:   OS X - 10.11.6

**Comment by RomanBuzuk** [comment]
I have same problem. I tried to write client to todo-list from example, but I get same error. 
```package main

import (
	"log"
	"os"

	"github.com/go-openapi/strfmt"

	httptransport "github.com/go-openapi/runtime/client"
	apiclient "github.com/go-swagger/go-swagger/examples/todo-list/client"
	"github.com/go-swagger/go-swagger/examples/todo-list/client/todos"
)

func main() {

	// create the API client
	client := apiclient.New(httptransport.New("", "", nil), strfmt.Default)

	// make the authenticated request to get all items
	apiKeyHeaderAuth := httptransport.APIKeyAuth("X-API-TOKEN", "header", os.Getenv("API_KEY"))
	_, err := client.Todos.AddOne(&todos.AddOneParams{}, apiKeyHeaderAuth)
	log.Fatal(err)
}
```

Can someone explain, how to fix this problem?

**Comment by casualjim** [comment]
It doesn't know about the producer for that mime type, it works for me when I do it like this:

```go
package main

import (
	"log"
	"os"

	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	apiclient "github.com/go-swagger/go-swagger/examples/todo-list/client"
	"github.com/go-swagger/go-swagger/examples/todo-list/client/todos"
)

func main() {

	// create the API client
	tr := httptransport.New("127.0.0.1", "", nil)
	tr.Producers["application/io.swagger.examples.todo-list.v1+json"] = runtime.JSONProducer()
	tr.Consumers["application/io.swagger.examples.todo-list.v1+json"] = runtime.JSONConsumer()
	client := apiclient.New(tr, strfmt.Default)

	// make the authenticated request to get all items
	apiKeyHeaderAuth := httptransport.APIKeyAuth("X-API-TOKEN", "header", os.Getenv("API_KEY"))
	_, err := client.Todos.AddOne(todos.NewAddOneParams(), apiKeyHeaderAuth)
	log.Fatal(err)
}
```
