### ISSUE TITLE
Question: package names

### ISSUE THREAD

**Issue by kenjones-cisco** [go-swagger/go-swagger#971]
## Problem statement
When generating a client, the pascal name applied to the packages under client/ are not consistent.

For one group of operations, I have the tag `DNS`, and for another I have a tag of `SLB`. When the package name is created, the `DNS` tag becomes package `dns`. But for `SLB` the package becomes `s_l_b`.

I've tried looking through the debug output but not sure why one has underscores and the other does not.
What are the rules associated `{{ pascalize .NAME }}`

## Environment
swagger version: master  
go version: 1.8.x  
OS:   debian (via container golang:1.8)

**Comment by casualjim** [comment]
This discrepancy is because of how golint wants naming to be done.  There are a set of blessed initialisms: https://github.com/golang/lint/blob/3390df4df2787994aea98de825b964ac7944b817/lint.go#L732-L769 and those are not split up by to the rules defined here: https://github.com/go-openapi/swag/blob/master/util.go#L145-L175

**Comment by kenjones-cisco** [comment]
Is there any way from a `go-swagger` perspective to be able to override, influence, or customize it?

if the value was all lower case then it would just stay `slb` and not be separated by `_` correct?

**Comment by casualjim** [comment]
if it would be Slb that is correct. There isn't at this point unfortunately. it would require extending the configuration mechanism with a way to override the filters. And a way to dynamically load code.
I'll open a ticket about introducing a plugin mechanism for go 1.8 and beyond

**Comment by kenjones-cisco** [comment]
Thanks! I will tweak the tag to force the desired name in the near term.
