### ISSUE TITLE
Client Request Parameters - lint error

### ISSUE THREAD

**Issue by kenjones-cisco** [go-swagger/go-swagger#973]
## Problem statement

The following lint error is generated by `staticcheck`, `errcheck`, and `gosimple`, and running `go test` will fail as well.
`warning: invalid operation: cannot indirect o.Profile.String() (value of type string) (staticcheck)`

In the client request parameters, `WriteToRequest` has checks if the parameter is nullable and if so there is a block to check if the parameter is `nil` before attempting to use the value.

In this particular case, Profile is a `UUID`, so the desired result is `o.Profile.String()` but the generated code currently results in `*o.Profile.String()`. 

I was initially thinking the issue might be as simple as the following:
FROM:
```
  if err := r.SetHeaderParam({{ printf "%q" .Name }}, {{ if .Formatter }}{{ .Formatter }}({{ if .IsNullable }}*{{end}}{{ .ValueExpression }}){{ else }}{{ if .IsNullable }}*{{end}}{{ .ValueExpression }}{{ if .IsCustomFormatter }}.String(){{end}}{{end}}); err != nil {
```

TO:
```
  if err := r.SetHeaderParam({{ printf "%q" .Name }}, {{ if .Formatter }}{{ .Formatter }}({{ if .IsNullable }}*{{end}}{{ .ValueExpression }}){{ else }}{{ .ValueExpression }}{{ if .IsCustomFormatter }}.String(){{end}}{{end}}); err != nil {
```

But if there is no custom formatter, then it could be a real value that needs to be deref for the real value instead of the pointer to the value. 

Right now I'm manually changing the generated code to remove `*` as it is only a single file currently but it does seem like it could be a problem if this happens across several files.

## Swagger specification
snippet
```
paths:
  /dns/rrset:
    get:
      tags: [DNS]
      summary: Get Resource Records
      operationId: getResourceRecords
      description: |
        Retrieve the resource record sets for the domain.
      parameters:
        - name: profile
          description: |
            The profile context for which resource records are associated.
          in: header
          required: false
          type: string
          format: uuid
        - name: name
          description: |
            The associated DNS name to view.
          in: query
          required: false
          type: string
      responses:
        200:
          description: Resource records for the domain.
```

Because `profile` is not required depending on usage, the value is nullable.

## Steps to reproduce
swagger generate client -f ./api.yaml

## Environment
swagger version: master  
go version: 1.8.x  
OS:   debian (via golang:1.8 container)

**Comment by susyo** [comment]
workaround: @kenjones-cisco required: true in swagger seems to workaround that issue
