### ISSUE TITLE
Integrating UI Into An Existing API

### ISSUE THREAD

**Issue by jtaylor32** [go-swagger/go-swagger#976]
## Integrating UI Into An Existing API

Is there anyway to easily integrate documentation and a client without having to auto generate a server API? 

I don't want my API server to be auto generated for me when I already have a complex service finished. Another reason I want this capability is because I have to support many transports (gRPC & http) in a microservices architecture. 

I just want to have an easy way to document the service and supply a frontend for other to interact with.

Thanks!

**Comment by casualjim** [comment]
the 2 things are orthogonal concerns. Whatever serves the UI in go-swagger is just a middleware
https://github.com/go-openapi/runtime/blob/master/middleware/redoc.go

to integrate swagger-ui you would need to figure out how to serve the static files and call the UI with: `?url=https://example.com/swagger.json`

**Comment by jtaylor32** [comment]
@casualjim that's exactly how we are going to have to do it. Thank you for your help.
