### ISSUE TITLE
incorrect API response if using allof ref

### ISSUE THREAD

**Issue by upendrasahu** [go-swagger/go-swagger#979]
## Problem statement
I am using swagger to generate server code.
I have this definition object and I am using this as response schema for one of the API

```json
"Cluster": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/NewCluster"
        },
        {
          "properties": {
            "result": {
              "description": "results of cluster creation",
              "type": "string"
            },
            "status": {
              "description": "status of cluster created|updated|running|deleted",
              "type": "string"
            }
          }
        }
      ]
    },
    "NewCluster": {
    :::::::
   }
```
In response I am only getting NewCluster json, Not getting result and status property in response

Generated model

``` go
// Cluster cluster
// swagger:model Cluster
type Cluster struct {
	NewCluster
	// results of cluster creation
	Result string `json:"result,omitempty"`
	// status of cluster created|updated|running|deleted
	Status string `json:"status,omitempty"`

}
````
## Environment
swagger version: 2.0
go version: 1.7.5
OS:   Ubuntu14.04

**Comment by gregmarr** [comment]
When I use `allOf` when generating a server, I have to put `"type": "object"` in any local definition (not using `$ref`).   I'd try adding that before `"properties": {`.

FYI, if you put a line with just ``` before and after your code, you'll get better formatting.
