### ISSUE TITLE
Invalid JSON tags in model

### ISSUE THREAD

**Issue by MaxNosov** [go-swagger/go-swagger#981]
## Problem statement
Generated client or server models have incorrect JSON tags of fields.
Generator uses **x-go-name** field to generate JSON tag instead of JSON field name.
I have following model to generate spec

```
// User - user model
// swagger:model
type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`

	// User type
	// min: 1
	// max: 5
	Type int `json:"user_type"`
}
```

Then after swagger spec has been generated I generated client (or server) using that spec.
As result I got incorrect JSON tags of fields in model.

```
// User User - user model
// swagger:model User
type User struct {

	// first name
	FirstName string `json:"FirstName,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// last name
	LastName string `json:"LastName,omitempty"`

	// User type
	// Maximum: 5
	// Minimum: 1
	Type int64 `json:"Type,omitempty"`
}
```

I got "json:"**LastName**,..." instead of "json:"**last_name**,..." for LastName field
or for example "json:"**Type**,..." instead of "json:"**user_type**,..." for Type field,
and so on for other fields.

And also I got incorrect validation code for Type:

```
func (m *User) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.UserType) { // not required
		return nil
	}

	if err := validate.MinimumInt("user_type", "body", int64(m.UserType), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("user_type", "body", int64(m.UserType), 5, false); err != nil {
		return err
	}

	return nil
}
```

I got "if swag.IsZero(m.**UserType**)" instead of "if swag.IsZero(m.**Type**)"

## Steps to reproduce

1. Create model such as
```
// User - user model
// swagger:model
type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`

	// User type
	// min: 1
	// max: 5
	Type int `json:"user_type"`
}
```

2. Run spec generating
swagger generate spec -m -b ./<path_to_model> > swagger.json

3. Run client generating 
swagger generate client -f ./swagger.json -t ./output

## Environment
swagger version: 0.7.4, 0.8.0  
go version: 1.8.0  
OS:  Ubuntu Linux 16.10, Windows 10 x64

**Comment by casualjim** [comment]
This has been fixed on master IIRC

**Comment by MaxNosov** [comment]
And also I found that some structures such as

```
/*DataItems0 data items0
swagger:model DataItems0
*/
type DataItems0 struct {
	models.Media

	// distance
	Distance float64 `json:"distance,omitempty"`
}
```

in code generated with wrong call

```
// UnmarshalJSON unmarshals this object from a JSON structure
func (o *DataItems0) UnmarshalJSON(raw []byte) error {

	var aO0 models.Media
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	o.models.Media = aO0 // <- must be 	o.Media = aO0, not o.models.Media = aO0

	return nil
}
```

Must be **o.Media** = aO0, not ***o.models.Media*** = aO0

**Comment by casualjim** [comment]
would it be possible to share the spec that leads to  this? Although this second comment would probably be better in a separate issue

**Comment by MaxNosov** [comment]
Described in new issue https://github.com/go-swagger/go-swagger/issues/982

**Comment by MaxNosov** [comment]
I've tried version from master.
Tags were generated correctly.
But now field names of model generated ignoring x-go-name.
e.g. For "x-go-name: Type" tool generates UserType instead of Type.
Is it correct?
