### ISSUE TITLE
Nested properties generates invalid code

### ISSUE THREAD

**Issue by anopheles** [go-swagger/go-swagger#984]
Following swagger definition
https://gist.github.com/anopheles/cff863e0d783eba2118e2429b095c3c4

when run with `swagger generate server ...` and finally compile the code, I get following error message:

restapi/operations/post_xxx_add.go:61: undefined: ParametersTest

Why is the ParameterTest object not created? The specified swagger definition should be valid as per http://editor.swagger.io/.

**Comment by kbj** [comment]
I ran into this bug as well. Any idea where in the code to look? If I could get an indication on where in the code base to start looking, I'd be happy to help debug it.

**Comment by casualjim** [comment]
can you use `swagger flatten` before generating

**Comment by kbj** [comment]
@casualjim worked perfectly, thanks!

**Comment by fredbi** [comment]
This works now.
There is just a little catch with the gist provided: since the "test" name is used as a suffix for source code, there is a xxx_test.go file that is not included in regular builds... Moving to "retest" for instance, and this compiles fine.
