### ISSUE TITLE
no README in examples/todo-list

### ISSUE THREAD

**Issue by dfong** [go-swagger/go-swagger#986]
## Problem statement

the todo-list example should have its own instructions.  there is a README.md in the stream-server example, but it is not clear that it is supposed to apply to this example as well.  (and i could not get that example to work either.)

really it'd be nice to have a simple makefile that has targets for build, test, and clean.

this would be useful for doing CI on the examples as well, if you're doing that.

**Comment by kenjones-cisco** [comment]
I actually had the same thoughts regarding a Makefile. I had started on one based on one I use across projects that supports running locally as well as performing all the tasks within a Docker container. 

@casualjim Would you be interested in having such a Makefile?

**Comment by casualjim** [comment]
I will never stand in the way of improvements, bear in mind that I want to migrate to circle ci 2.0 manifests this weekend but that should be easy enough to support
