### ISSUE TITLE
detection of consumers/producers for codegeneration fails when not top-level

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#987]
## Problem statement

detection of consumers/producers for codegeneration fails when not top-level
http://stackoverflow.com/questions/42632267/example-code-for-a-working-post-in-swagger-go/43108506#43108506

Please remove the sections that don't apply

## Swagger specification

```yaml
---
swagger: '2.0'
info:
  version: 1.0.0
  title: Greeting Server

basePath: "/api/greeting/2.0"

paths:
  /revisit:
    post:
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
        - name: site
          required: true
          type: string
          in: query
          description: site name

        - name: userlist
          in: body
          description: list of users
          required: true
          schema:
            "$ref": "#/definitions/Userlist"


      operationId: trackingRevisit

      responses:
        200:
          description:  return list of users which need revisit
          schema:
            type: string
```

**Comment by AbderrahmanL** [comment]
Hello i am in a situation where i cannot regenerate the server since it is already in place, how do i solve this problem without regenerating if there is a way to do it.

**Comment by AbderrahmanL** [comment]
Hello,
 I am in a situation where i cannot regenerate the  server since it is already in place, how do i solve this problem without  regenerating if there is a way to do it.
Best regards
