### ISSUE TITLE
Nested Packages: Generating Spec File

### ISSUE THREAD

**Issue by jtaylor32** [go-swagger/go-swagger#991]
## Environment
swagger version: 0.8.0
go version: 1.8
OS: Mac OSX

I am trying to find a way to generate a spec file with the `swagger generate spec -o ./swagger.json` command that will detect the nested packages in my project structure.

I have `internal/` business logic that I want to keep separated but I have no way to generate the swagger spec file for those packages.

Structure would look similar to this.

```
/
cmd/
|     main.go
internal/
│   blah/
│  │   *.go
│   blahblah/
│  │   *.go
│   blahblahblah/
│  │   *.go
<root files...>
```

Is there a way to do something similar to the go tools ie. `go test ./...`? I

**Comment by casualjim** [comment]
Swagger uses the go compiler infrastructure. So as long as packages can be detected as being in use in code paths, the scanner should find out all the annotations defined in those files.

**Comment by jtaylor32** [comment]
@casualjim so if I have a blank `main.go` file that imports those internal packages it will generate that spec file?

**Comment by casualjim** [comment]
yep you can use `_ "blah/internal/blah"`

**Comment by jtaylor32** [comment]
Cheers! @casualjim thank you so much
