### ISSUE TITLE
Example for dynamic client?

### ISSUE THREAD

**Issue by sanjeevdatla** [go-swagger/go-swagger#996]
## Problem statement
Just like the untyped dynamic server example in go-swagger, is there an example for a dynamic client. Can a REST client be created at runtime by loading a swagger spec file, without going through a code generation and compilation? Thanks.

**Comment by casualjim** [comment]
What would you expect from a dynamic client?
What would it add on top of the default http client?

**Comment by sanjeevdatla** [comment]
Thanks for taking the time to ask. If I have the swagger spec file for an existing 3rd party REST service for their application, a dynamic client would allow me to load the swagger spec file and provide the ability to formulate requests and parse responses based on the loaded spec file. For e.g. there are REST client packages for go like go-resty that provide a nice interface to interact with a REST server, but go-resty doesn't comprehend swagger specs.

**Comment by sanjeevdatla** [comment]
Adding a bit more context, can I get the rest client functionality without first generating a client using go-swagger and then compiling it back into the code. Can this be done dynamically like the dynamic server example.
