### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by Ragnar-BY** [go-swagger/go-swagger#997]
## Problem statement
Is it possible to write own validation for custom types ? If it is, can someone give me example ? 

## Environment
swagger version: 0.8.0

**Comment by casualjim** [comment]
Can you elaborate a little bit more on this use case?

**Comment by RomanBuzuk** [comment]
For example. 
There is bookstore, with info about books: author, title, price. And we want, that books from some author will not cost more the some price. So I want write function ValidateBookCustom() like
if book.author == "Some author" {
    if book.price > 1000 {
       return false
   }
    else return true
}
```

And I want to use this function.

**Comment by sluchznak** [comment]
For example, I want to validate is value of field exists in DB.

**Comment by sluchznak** [comment]
@RomanBuzuk probably you can use custom format for string field:
- https://goswagger.io/generate/spec/model.html
- https://goswagger.io/generate/spec/strfmt.html

**Comment by fredbi** [comment]
See also #1334
