### ISSUE TITLE
x/net/context vs context pkg

### ISSUE THREAD

**Issue by msample** [go-swagger/go-swagger#998]
## Problem statement

Generated Go server using --with-context fails to compile due to mixed use of "context" and "x/net/context"

## Environment
swagger version: dev/HEAD as of today
go version: 1.8
OS:   OSX

Fix for me was to update the following templates (did client one as well but did not test) and 'go generate' bindata.go again.

    generator/templates/client/parameter.gotmpl
    generator/templates/server/configureapi.gotmpl
    generator/templates/server/operation.gotmpl

    context "golang.org/x/net/context"  -->  context "context"

**Comment by jbub** [comment]
Similar issue, in `builder.gotmpl`, there is no "context" import, when formatting code, goimports resolves context import as "context" not "golang.org/x/net/context", so there is mixed usage of context again, i worked around it by using sed right after generating:

```
gofmt -w -r '"context" -> "golang.org/x/net/context"' server/operations/my_api.go
```

**Comment by casualjim** [comment]
the problem isn't isolated to go-swagger, it's that many other things use the golang/x/net context and you want to be able to pass them along.
To make this work we have to define a default import for the context package that will solve it.
it goes in generator/operations.go and generator/support.go

**Comment by msample** [comment]
In retrospect, given that one can get the http.Request from params, and one can get the context from that by calling req.Context(),  perhaps the 'go-swagger generate server' no longer needs the '--with-context' flag?

**Comment by casualjim** [comment]
that is correct I'll remove it in the version that will work with openapi 3.0 spec

**Comment by msample** [comment]
Thanks @casualjim.  It appears this is a non-issue and can be closed.  

BTW the docs on goswagger.io are a big help, thank you. Appreciate the design rationale.  Emphasizing this one point would have given me a much smoother start: you MUST generate into a package on under $GOPATH/src or bad things happen (I was getting weird import pkg paths).   By the looks of it, the spots that use $GOPATH in go-swagger may need the 1.8 $HOME/go defaulting when GOPATH is empty.

**Comment by casualjim** [comment]
Yes excellent suggestion
